pycbc/__init__.py
pycbc/distributions/angular.py
pycbc/distributions/bounded.py
pycbc/events/veto.py
pycbc/io/sqlite.py
pycbc/vetoes/chisq_cuda.py
setup.py
test/test_fftw_openmp.py
test/test_fftw_pthreads.py
test/test_lalsim.py
test/test_pnutils.py
test/test_spatmplt.py
test/test_threshold.py
test/test_tmpltbank.py
test/test_waveform.py
test/utils.py

Some more changes addressing simple Python 3 incompatibilities.
With this patch I am actually able to install PyCBC on my laptop using `python3 setup.py install`. Installing the dependencies fails immediately on pycbc-glue, but at least I get a partially importable PyCBC. The unit test infrastructure works and a couple tests actually pass. The most concerning issues in the failing tests seem to be weave and pycbc-glue.
I split the changes into different commits by topic and amount of possible impact. The first commit is trivial and should have no effect, but you may want to have a look at the other ones.

Fixes towards Python 3 compatibility

---

pycbc/inference/option_utils.py
pycbc/transforms.py

Adds functions to load transforms from a config file. Also adds the ability to read sampling parameters from the config file that should be used in place of the variable args. (Support in likelihood coming in another patch.)
The syntax is very similar to distributions: separate sections are used for each transformation. Nested transforms can be specified, in which case the transforms are ordered by their nesting. The returned list can the be used with `apply_transforms`.
Example, with config file:
```
[sampling_parameters]
; left side are parameters with priors defined
; right side are parameters to map them to for
; sampling
mass1, mass2 = mchirp, logitq
[sampling_transforms-mchirp+q]
; inputs are mass1, mass2
; outputs are mchirp, q
name = mass1_mass2_to_mchirp_q …
```

Read transforms from config file

---

pycbc/transforms.py

There is a bug in the master version of transforms.py:
```Traceback (most recent call last):
File "check_likelihood.py", line 53, in <module>
fp, parameters, _, samples = option_utils.results_from_cli(opts)
File "/home/miriam.cabero/virtualenvs/pycbc-master/local/lib/python2.7/site-packages/PyCBC-d93c5f-py2.7.egg/pycbc/inference/option_utils.py", line 499, in results_from_cli
parameters, fp.variable_args)
File "/home/miriam.cabero/virtualenvs/pycbc-master/local/lib/python2.7/site-packages/PyCBC-d93c5f-py2.7.egg/pycbc/transforms.py", line 1089, in get_common_cbc_transforms
requested_params = set(requested_params + new_params)
TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('S12') dtype('S12') dtype('S12')
```
This PR should take care of that issue

Fix bug in transforms.py

---

pycbc/conversions.py
pycbc/distributions/bounded.py
pycbc/inference/sampler_emcee.py
pycbc/transforms.py
pycbc/waveform/__init__.py
pycbc/waveform/generator.py
test/test_inference.py

Separates out the ``ChangeOfVariables`` commits from #1679.
This PR:
* Changes ``PrecessionMassSpinToCartesianSpin.transform`` so that the primary and secondary masses are always mapped to the correct functions.
* Removes functions at top of ``generator.py``.
* Generators now use ``transforms.py`` to get transformations.
* Update a docstring in ``bounded.py``.
* Updates ``phi_a`` to pick the primary and secondary mass.
I realize now that since the logit transformation is initialized with bounds, etc. we will need some way to pass those to the generator. But this works for ``mchirp``-``q``, effective spins, etc.

Replace generator.py functions with transforms

---

bin/inference/pycbc_inference

Do not require that all samplers have a write_state implemented for pycbc_inference

---

pycbc/waveform/ringdown.py

After a while not directly calling the functions to generate ringdown waveforms, I had forgotten that if one wants the mode '220' has to specify '221' (because the last number is the number of overtones, and not which "n"). From the error message I was getting, it was not immediately obvious where the problem was, so I thought it would be nice for new people using the code (and forgetful people like me) to add an error message that specifically will tell to change the zero (the documentation on the multi-mode function does provide information to figure out how it works).

Add error message to ringdown module

---

pycbc/transforms.py

Ensures that the `mass2` in the `MchirpQToMass1Mass2` jacobian is really the smaller component mass. This is needed if transforming from the uniform in component mass distribution. Also adds the inverse Jacobian.

Ensure m2 < m1 in mchirp jacobian

---

bin/bank/pycbc_brute_bank

This is the absolute simplest change to allow td approximants. It doesn't try to optimize them for matches, but should work if you provide a proper buffer length. A future patch may try to optimize this.

simplest change to allow td approximants

---

bin/hwinj/pycbc_generate_hwinj

This patch adds a new optional argument to `pycbc_generate_hwinj`
You can now specify the coa_phase or reference orbital phase parameter that will be passed to LALSimulation when you generate the waveform. This parameter is important for waveforms that have higher modes or are precessing.

Add coaphase to hwinj

---

pycbc/distributions/__init__.py
pycbc/distributions/arbitrary.py
pycbc/transforms.py

This moves the guts of `FromFile` to its own distribution called `Arbitrary`. Arbitrary takes an array of samples, so it can be created without a file. FromFile just inherits from Arbitrary now.
This also uses the Logit transform to implement bounds. If bounds are specified, the internal kde is created in the logit coordinates. This means no re-normalization needs to be done, as was done before.
A plot of an Arbitrary created from a Uniform distribution between [-1,1): [here](https://www.atlas.aei.uni-hannover.de/~cdcapano/LSC/scratch/arbitrary_check-uniform.pdf). Gaussian with same bounds: [here](https://www.atlas.aei.uni-hannover.de/~cdcapano/LSC/scratch/arbitrary_check-gaussian.pdf).

Add Arbitrary distribution

---

pycbc/distributions/__init__.py
pycbc/distributions/spins.py

This adds the independent (and uniform) chi_p, chi_eff distribution to `distributions.py`; it's placed in its own new file called `spins.py`. (I'm open to suggestions for a better name.)
Because of the complicated constraints, the distribution generates the two component masses along with all 6 spin degrees of freedom itself. I also couldn't easily figure out an analytic form for the pdf due to the constraints. Instead, I just generate a bunch of samples using rejection sampling, create a kde from them, then use the kde's pdf for the distribution's pdf. It isn't perfect, but works for now. We can fix this if we can figure out an analytic form for the pdf. In addition, the mass parameters are forced to be mass1 and mass2; at some point we might want to generalize, but since the standard …

Add independent chi_p, chi_eff distribution

---

bin/inference/pycbc_inference
pycbc/inference/likelihood.py
pycbc/inference/option_utils.py
pycbc/inference/prior.py
pycbc/inference/sampler_base.py
pycbc/inference/sampler_emcee.py
pycbc/inference/sampler_kombine.py
pycbc/io/inference_hdf.py
pycbc/transforms.py
pycbc/waveform/generator.py
test/test_inference.py

This patch adds the ability to define transforms to sample in a different parameter space than the parameter space of the variable args (which the priors are defined with). Multiple transforms may be used to get from the variable args to the sampling args, and the sampling args need not have a distribution defined for them. This allows, e.g., the sampler to sample in the `logit` of a parameter.
The `LikelihoodEvaluator` controls the transformations between the priors and the sampler. When the initial positions are set, the likelihood evaluator converts them to sampling space before passing to the sampler class. At each iteration, when the sampler passes values to the likelihood evaluator, the values are transformed back to the variable args space before passed to the prior distributions. …

Sample in different parameter space than variable args

---

pycbc/filter/matchedfilter.py

This fixes a bug in the normalization of an intermediate quantity that is computed while calculating the *sky-maxed* SNR/statistic. Ian says "It looks like this was introduced in some recent reorganization and was *not* present in the version used for the paper: https://github.com/spxiwh/pycbc/blob/VERSION_USED_FOR_PAPER_RUNS/pycbc/filter/matchedfilter.py#L438"

bugfix in normalization, inside compute_max_snr_over_sky_loc_stat

---

pycbc/distributions/power_law.py

Correctly normalizes the PDF and draws samples.
The docstring has been updated.

Allow UniformPowerLaw to use non-zero lower bounds

---

bin/hwinj/pycbc_generate_hwinj
docs/hwinj.rst
examples/cal/foton_filter_esd_saturation/README.rst

If the argument `--fake-strain-from-file` is used in `pycbc_generate_hwinj`, https://github.com/ligo-cbc/pycbc/blob/master/bin/hwinj/pycbc_generate_hwinj#L332 to https://github.com/ligo-cbc/pycbc/blob/master/pycbc/strain.py#L316 requires an input argument named `--low-frequency-cutoff`. That is equivalent to the current `--psd-low-frequency-cutoff` in the code. The code fails for this case if `low-frequency-cutoff` is not provided. So this PR changes `--psd-low-frequency-cutoff` --> `--low-frequency-cutoff`. Also `--psd-high-frequency-cutoff` --> `--high-frequency-cutoff` to keep the names similar.
@cmbiwer Could you please take a look?

Change the frequency cutoff names to satisfy the requirements of reading in asd from file

---

bin/inference/pycbc_inference_plot_movie

With pycbc_inference_plot_movie one can create frames to put them together into a movie. Because creating a movie requires having ffmpeg installed (which is not a pycbc requirement), we left that last step out and the user had to run it manually after generating the frames.
Here we add the option --make-movie, where the user can specify a path for creating the movie if ffmpeg is installed, and the option --cleanup, which will only work if --make-movie has been specified, with the purpose of removing the individual frames after creating the movie.

Add option to automatically create movie in plot_movie

---

pycbc/conversions.py
pycbc/inference/likelihood.py
pycbc/inference/option_utils.py

As title says.
Inference executables can then plot Network SNR with ``--parameters-group likelihood_stats --parameters "snr_from_loglr(loglr):Network SNR"``.

Allow FieldArray access to snr_from_loglr

---

.landscape.yml
.travis.yml
requirements.txt
tools/docker_build_dist.sh

This patch:
* Fixes the Travis build failure by using pip to install the contents of requirements.txt
* Update requirements.txt to match setup.py and remove pycbc (pycbc cannot require itself!)
* Fixes a syntax problem in travis.yml so that we actually run the test scripts.
* Ensures landscape does not run on build products
@ahnitz @duncan-brown Please feel free to approve this, but @duncan-brown has indicated I should push this if it works as it is holding up all other pull requests.

Fix Travis issues

---

pycbc/inference/likelihood.py

When using a transform to sample in different coordinates than the parameters, the sampler can wander in to unphysical regions, giving a nan. For example, if sampling in mchirp, q with a prior defined in mass1, mass2, the sampler may go to negative q. The inverse transform then returns nans for mass1 and mass2, which in turn causes the uniform prior to return a nan. This catches that by setting the prior to -inf if the returned value is nan.

Catch nans from transform

---

bin/pycbc_live
pycbc/filter/matchedfilter.py
pycbc/frame/frame.py
pycbc/io/live.py
pycbc/strain.py

Adds a check for the state and DQ of followup detectors when calculating the SNR timeseries for PyCBC Live. Needs testing, but I am opening for consideration. In particular I want to make two notes:
* A followup detector is ignored if it was offline or had DQ issues at any point during the duration of the template, with some padding and taking into account the duration of the SNR timeseries. Maybe this is too strict though. I.e. if DQ issues affect just a few samples at the beginning or end of the SNR series, there may still be value in sending the timeseries to BAYESTAR. Sounds like some risk/benefit tradeoff needs to be discussed. For the moment it might be ok to be overly conservative, and maybe revisit the decision once Virgo proves to be super valuable for sky localization.
* …

pycbc_live: check state & DQ of followup detectors

---

pycbc/distributions/__init__.py
pycbc/distributions/uniform_log.py

Test with:
```
#! /usr/bin/env python
import numpy
from pycbc.distributions import uniform_log
n = 50000
nbins = 50
A = 5
B = 12
dist = uniform_log.UniformLog10(x=(A, B))
samples = dist.rvs(n)
x = numpy.arange(A, B + 0.05, 0.05)
pdf = [dist.pdf(**{"x" : xx}) for xx in x]
print pdf
plt.plot(x, pdf, "r--")
plt.hist(samples["x"], 50, normed=True, label="log10(x)")
plt.legend()
plt.ylabel("PDF")
plt.xlabel("x")
plt.savefig("param.png")
plt.close()
plt.hist(numpy.log10(samples["x"]), 50, normed=True)
plt.ylabel("PDF")
plt.xlabel("log10(x)")
plt.savefig("log10_param.png")
plt.close()
```
Plot of ``rvs`` and ``pdf`` functions: https://sugwg-jobs.phy.syr.edu/~cbiwer/projects/inference_distriubtions/uniform_log/param.png
Plot of ``numpy.log10`` of samples from …

Add distribution that is uniform in log base 10

---

pycbc/conversions.py

The `det_tc` function in `conversions.py` tries to call `time_delay_from_center`; it should be `time_delay_from_earth_center`.

Fix function name error in det tc

---

bin/pygrb/pycbc_make_offline_grb_workflow
pycbc/results/legacy_grb.py
pycbc/workflow/segment.py

Hi all,
This change is designed to let PyGRB handle arbitrarily many IFOs, letting the code decide on the best combination of available IFOs for the analysis. Currently this is done only based upon coherent science segment duration.
Examples can be seen in the plots [here](https://ldas-jobs.ligo.caltech.edu/~andrew.williamson/pygrb/review/three_detector_upgrade/).
One specific example is the edge case where there is science data in all three IFOs but not enough coherently across all three, and so the best 2 detector case must be selected. See the result [here](https://ldas-jobs.ligo.caltech.edu/~andrew.williamson/pygrb/review/three_detector_upgrade/H1_OK-L1_OK_trimmed-V1_OK_trimmed-969641000.png) and PyGRB's logging output for this example …

Triggered coherent segment generation upgrade

---

bin/inference/pycbc_inference
pycbc/distributions/constraints.py
pycbc/inference/option_utils.py
pycbc/inference/prior.py
pycbc/inference/sampler_base.py
pycbc/inference/sampler_emcee.py

This PR:
* Updates ``pycbc_inference``, ``option_utils``, and ``.set_p0`` functions to allow ``PriorEvaluator`` to use passed constraints
* Fixes to emcee sampler trying ``write_state`` and writing samples.
* Adds a ``constraint`` module with constraint definitions. The ``custom`` constraint takes a str and evaluates it.
Can use ini file like:
```
[constraint-1]
name = mtotal_lt ; pre-defined constraint
mtotal = 30
[constraint-2]
name = custom ; let's make things up
func = params["mass1"] + params["mass2"] < self.mtotal
mtotal = 30
```

Allow pycbc_inference to apply multi-dimensional constraints from ini file

---

bin/bank/pycbc_geom_nonspinbank

Numpy now requires integer indexes. We had been abusing float-but-actually-integer (ie. 7.0) values here. A better fix would be to not use floats at all here, but this allows the code to run with current numpy.

Cast to integer

---

pycbc/strain.py

This forces the strain retrieved by `from_cli` to be double precision if the precision argument is set to double. Also checks that the precision argument is either 'single' or 'double', raising an error otherwise.

Ensure strain is double precision

---

pycbc/fft/fftw.py

This removes the global declaration from fftw.py.
@josh-willis @ahnitz here is the change discussed in the chat.

Remove global declaration

---

bin/pycbc_live
pycbc/events/single.py
pycbc/io/live.py

* pycbc live can now be told which gracedb server to use on the command line
* Keywoards are now passed to single detector events as well as standard coinc ones (so H1V1 time series should now be possible, have not tested this scenario, however). 
Example upload to the gracedb-test server
https://gracedb-test.ligo.org/events/view/T249742

add option to set gracedb server

---

bin/inference/pycbc_inference
pycbc/inference/likelihood.py

When running pycbc inference, the sampler may propose a jump that is in to an unphysical part of parameter space. This is ok, since the prior will just return -inf for such jumps before trying to generate a waveform, and so the sampler will move on (and if it doesn't, the waveform generator will raise an error anyway). However, with the default settings, numpy will print a warning to stdout when transforming these unphysical values to parameters needed by the prior/waveform generator. For example, when sampling in mchirp and q, the sampler may make several proposals with -q at the beginning. When transforming this to m1, m2 this causes numpy to print:
```
/home/cdcapano/.virtualenvs/pycbc_master/lib/python2.7/site-packages/PyCBC-693686-py2.7.egg/pycbc/transforms.py:254: RuntimeWarning: …
```

Silence numpy warnings in inference

---

bin/pycbc_live
pycbc/frame/__init__.py
pycbc/frame/frame.py
pycbc/psd/estimate.py

See individual commits for descriptions. The critical one is a fix for this error from a recent commit:
```
File "/mnt/qfs2/pycbc.live/testing/env/bin/pycbc_live", line 459, in <module>
evnt.check_singles(results, data_reader, psds, args.low_frequency_cutoff)
File "/mnt/qfs2/pycbc.live/testing/env/bin/pycbc_live", line 109, in check_singles
data_readers=data_readers,
NameError: global name 'data_readers' is not defined
```
The psd.welch change enables correct time stamps on the PSDs saved by PyCBC Live.
I just launched a live (offline) run with this patch on CIT, will look at the generated events tomorrow.

Various fixes/improvements to PyCBC Live

---

bin/workflows/pycbc_make_coinc_search_workflow

It was pointed out in the chat that it isn't easily to see what CAT1 times are removed from the data. Here I add an explicit (SCIENCE - CAT1) entry to A4. An example of this was shown in the chat, I removed the SCIENCE-CAT2 and SCIENCE-CAT3 entries as they were not helping.

Add SCIENCE - CAT1 to A4 on summary pages

---

bin/pycbc_live
pycbc/io/live.py

During ER11, gracedb-test went down a few times, taking PyCBC Live down with it. This catches GraceDB exceptions and ensures that the relevant files remain available to be uploaded manually later.
This also fixes an error which prevented PSDs of followup detectors to make their way into GraceDB for single-detector events.

pycbc_live: survive GraceDB errors

---

bin/pycbc_hdf5_splitbank

This PR removes the `skip_fields=template_duration` from the splitbank code so that when the sub banks are used in a workflow, `template_duration` does not have to be generated again. This would help in saving time when generating waveforms. The compressed waveform banks now store the `template_duration`. But due to the `skip_fields` condition in the spiltbank code, they were not getting written in the sub banks, and so were being regenerated when running the pipeline.

Enable splitbank code to write template duration in sub banks

---

.travis.yml
tools/docker_build_dist.sh
tools/einsteinathome/pycbc_build_eah.sh
tools/install_travis.sh
tools/test_coinc_search_workflow.sh

This pull request adds a specific version tag to the docker pull for the PyCBC base images. It is needed so that I can finish https://github.com/ligo-cbc/pycbc/pull/1756 without breaking the current Travis build. I also switched the pull for the MKL files from code.pycbc.phy.syr.edu to git.ligo.org.

Pull PyCBC docker images with a specific tag and switch to git.ligo.org

---

bin/pycbc_inspiral
pycbc/events/events.py
pycbc/filter/qtransform.py
pycbc/io/hdf.py

pycbc_inspiral changes:
1.) added import of qtransform.py script from pycbc.filter
2.) generate qtransform for each segment in a pycbc_inspiral run
- Still need to save output to ref.hdf file
-Make output compatible with pycbc_coinc_mergetrigs module
qtransform.py changes:
1.) qplane function now returns uninterpolated qtransforms by default
2.) functions for use of qtransform.py in pycbc_inspiral have been added
3.) new functions to recursively save/convert multilevel python dictionary to h5py file and vice versa.

Start of pycbc qtransform inspiral integration

---

tools/einsteinathome/pycbc_build_eah.sh

- a certificate issue prevents six from being installed via
dependency on Debian4 in a 'clean' E@H build

E@H build: install six unconditionally

---

pycbc/types/timeseries.py

Make it more convenient to slice a time series using gps times. 
i.e.
p = data.select_time(1192343232.50, 1192343232.90)

add helper to get a slice of a time series using actual times

---

pycbc/transforms.py

The `PrecessionMassSpinToCartesianSpin` transform uses `numpy.concatenate`, giving the list of arrays to concatenate as a list of arguments. However, concatenate apparently expects only the first argument to be a list or tuple of arrays. I'm not sure how this worked before; it may be a change that was introduced in newer versions of numpy. Anyway, this patch fixes that.

Fix bug in call to concatenate

---

tools/docker_build_dist.sh
tools/einsteinathome/pycbc_build_eah.sh
tools/install_travis.sh

This adds an option to ``pycbc_build_eah.sh`` to use an alternative URL to ``albert.phys.uwm.edu`` for downloading the frame, bank, and ROM data needed by the E@H test. It then uses this option to switch the Travis build to pull the data from ``git.ligo.org``.
This is needed, as I am seeing very slow download times from albert:
```
[pycbc@sugwg-test1 travis]$ wget http://albert.phys.uwm.edu/download/lal-data-r11.tar.gz
--2017-06-26 14:06:13--  http://albert.phys.uwm.edu/download/lal-data-r11.tar.gz
Resolving albert.phys.uwm.edu (albert.phys.uwm.edu)... 129.89.61.67
Connecting to albert.phys.uwm.edu (albert.phys.uwm.edu)|129.89.61.67|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 604681670 (577M) [application/x-gzip]
Saving to: ‘lal-data-r11.tar.gz’ …
```

Use git.ligo.org for E@H test data on Travis

---

pycbc/workflow/configuration.py
requirements.txt
setup.py

This patch allows PyCBC to download files from ECP cookie authenticated servers as well as regular http and https. It has been tested as follows:
First, check for a sane failure mode:
```
(pycbc-dev)[dbrown@sugwg-condor pycbc]$ rm -f /tmp/ecpcookie.u620 
(pycbc-dev)[dbrown@sugwg-condor pycbc]$ python -c 'import pycbc.workflow; pycbc.workflow.resolve_url("https://git.ligo.org/duncan-brown/veto-definitions/raw/5fde1cd3f84e5983b81995f901b69b210b15d051/cbc/O2/H1L1-HOFT_C01_O2_CBC.xml")'
File "<string>", line 1, in <module>
File "pycbc/workflow/configuration.py", line 186, in resolve_url
raise ValueError(errMsg)
ValueError: The attempt to download the file at
https://git.ligo.org/duncan-brown/veto-definitions/raw/5fde1cd3f84e5983b81995f901b69b210b15d051/cbc/O2 …
```

Allow configuration and veto files to be on ECP authenticated servers

---

tools/docker_build_dist.sh
tools/test_coinc_search_workflow.sh

This will run the Travis test that builds the workflow against an ECP cookie authenticated server to perform a unit test of the new code in https://github.com/ligo-cbc/pycbc/pull/1773
@ahnitz this won't be exercised unless it's on the master or a tag of the master because security, so please go ahead, override the checks, and merge this. If there are any errors, I'll have to debug on master.

Run the workflow test using an ECP authenticated server

---

pycbc/workflow/configuration.py

If the source and destination config files are the same, don't attempt to make a copy. This fixes https://github.com/ligo-cbc/pycbc/issues/1781

Catch error if source and destination configuration file are the same

---

bin/pycbc_create_injections
pycbc/inference/option_utils.py
setup.py

I got tired of f*cking around with `lalapps_inspinj`, so I added an executable to create an injection set using the distributions module and write it to either an xml or hdf file. This won't replace `lalapps_inspinj` yet, as it doesn't have a number of that program's distributions. It also can't distribute injections in time the way that inspinj does. However, it is a first step (and is all we need for making injections for a PE PP test). With the exception of distributing injections in time, I think getting it up to snuff with `lalapps_inspinj` would just require more additions to the distributions module, and not necessarily additions to this executable. The time step stuff may also be handled in the distributions module.
Instead of specifying everything on the command line, this …

Add an executable to create injection distributions

---

pycbc/workflow/configuration.py

This pull request fixes two issues in ``resolve_url()``
First, this patch makes ``resolve_url()`` idempotent. Before, you could get different URLs returned if Python thought that the file was the same:
```
In [6]: pycbc.workflow.resolve_url("file:///home/dbrown/x509_test/x509_test.2461667.log")
Out[6]: '/home/dbrown/x509_test.2461667.log'
In [7]: pycbc.workflow.resolve_url("file:///home/dbrown/x509_test/x509_test.2461667.log")
Out[7]: '/home/dbrown/x509_test/x509_test.2461667.log'
```
This is now fixed:
```
In [7]: pycbc.workflow.resolve_url("/home/dbrown/x509_test/x509_test.2461667.log")
Out[7]: '/home/dbrown/x509_test.2461667.log'
In [8]: pycbc.workflow.resolve_url("/home/dbrown/x509_test/x509_test.2461667.log")
Out[8]: '/home/dbrown/x509_test.2461667.log'
In [9]: …
```

Fixed edge cases in resolve_url

---

pycbc/noise/reproduceable.py

Add a module to make noise that is the same at a given time and seed value. This makes it independent of the start / end of the noise you request. If you give the same seed value, the same time will have the same data. This makes it a lot easier to coordinate workflows on fake data without having to pregenerate  frame files, or in other programs where fake noise is needed with different overlapping intervals.

add module to make noise reproduceably

---

descr.txt
setup.py

This text shows up in the pypi project description page when we make the next release. Currently we have a blank section.

add description for the pypi page

---

bin/pycbc_ringinj
pycbc/waveform/generator.py
pycbc/waveform/ringdown.py

Up to now, the ringdown damped sinusoid approximant with higher modes would take the mass and the spin of the black hole as arguments and internally compute the frequencies and damping times of each mode using Berti's fits (general relativity).
For tests of GR, one needs to loosen the assumption that a certain mass and spin translate into certain frequencies and damping times. For that purpose, this PR adds a new ringdown damped sinusoid approximant with higher modes whose arguments are the frequency and damping time for each mode instead of the mass and the spin.

New multi-mode ringdown approximant

---

bin/hdfcoinc/pycbc_plot_singles_timefreq
bin/workflows/pycbc_make_coinc_search_workflow
pycbc/noise/reproduceable.py
pycbc/strain.py
pycbc/workflow/datafind.py
pycbc/workflow/jobsetup.py
pycbc/workflow/psd.py

I'm opening this to start the debug process on travis. I can do no testing atm due to ATLAS being down though. This should be the minimal change set required to make this work in a reasonable fashion, in conjuction with changes to the config file for this mode. I haven't changed segment handling so atm, that is bootstrapped with whatever you like. That could be simplified as well to have a no segments query mode, where all time is good option.
For all PyCBC user: When this is merged, fake strain will not return the same realization it used to.

allow workflows to run on internaly made Gaussian noise with a given PSD

---

docs/inference.rst

This updates the inference documentation page to use a mass prior uniform in mass1, mass2, while sampling in mchirp, q. This also changes the distance prior to `uniform_radius`, so that a uniform volume prior is used.

Use sampling transforms in inference docs

---

pycbc/inference/sampler_emcee.py

Currently, `emcee_pt` will fail with the dreaded pickling bug when using with multiprocessing. This is because it wasn't properly updated to use @ahnitz's global fix to avoid pickling problems. The difficulty with emcee_pt was that it needs the loglikelihood and prior functions separately. This patch fixes that by wrapping the global likelihood evaluator call function, just setting the keyword argument call to the appropriate function. I'm not sure why my test scripts missed this earlier, but I've run this patch on a test case that definitely had the error before this patch.

Fix emcee_pt pickling bug

---

test/fft_base.py

* Check for _delta_t and _delta_f in deciding what type an array is
* Disable lal fft tests
Hi, this is related to the issues I reported in the mattermost https://chat.pycbc.phy.syr.edu/pycbc/channels/pycbc-code the other day.
I had to make a couple of tweaks to get the unit tests to succeed on my desktop at home (ubuntu 17.04, python 2.7.13, pycbc and lalsuite recent master)
I'd be terribly surprised if this is a serious issue but I don't know why nobody has run into it before so it seemed best to just make a simple patch and pass it on to the maintainers of this file (Josh? Duncan?)
The 1st change about delta_t vs _delta_t seems trivial, but I don't know why my FrequencySeries have delta_t nor why my TimeSeries have delta_f. Maybe that's correct, but it seems the check in the code here …

Fix tests/fft_base.py

---

pycbc/filter/autocorrelation.py

There is a bug in the way that ACFs are computed: the chains are not zero-padded, so the ACF comes out periodic.  This pull request fixes it.

Fix zero-padding bug in ACF computation.

---

test/bankvetotest.py
tools/travis_build_and_test.sh

@duncan-brown seems to have disabled some of the sanity tests in Travis. This probably comes from some previous time when these tests were failing. I patched the failing tests in January, so these should be re-enabled now. This would have caught the issue @johnveitch reports in #1803. Until #1803 is pushed and this is rebased it will fail, this is expected.
I also added a few lines to make the bankveto script work again. This isn't a formal test script (maybe it should be made one), but we can at least exercise it here.
Lalsimulation testing is still disabled. This currently uses the ROM waveforms which are not available in Travis. Fixing that should be done, but maybe in a separate pull request.

Reenable important tests

---

pycbc/waveform/waveform.py

Simple patch to support EOBNRv2_ROM as a template waveform.

Allow EOBNRv2_ROM as template waveform

---

pycbc/frame/frame.py

With this override:
```
workflow-datafind:datafind-backup-datafind-server:ldr.ligo.caltech.edu
```
I get this error:
```
2017-07-27 22:25:44,645:INFO : Setting up connection to datafind server.
File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_deb_8/virtualenv/pycbc-v1.7.5/bin/pycbc_make_coinc_search_workflow", line 4, in <module>
__import__('pkg_resources').run_script('PyCBC==1.7.5', 'pycbc_make_coinc_search_workflow')
File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_deb_8/virtualenv/pycbc-v1.7.5/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 741, in run_script
self.require(requires)[0].run_script(script_name, ns)
File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_deb_8/virtualenv/pycbc-v1.7.5/local/lib/p …
```

workflow: fix error when datafind server port is not given

---

bin/pycbc_compress_bank

Compress bank currently sets the segment length used to generate each template based on an estimate of each template's duration using chirp mass. This estimate can be too short for high-mass, high-spin templates, causing the `delta_f` used for the original waveform, and that used in the tolerance calculation, to be too large. This can cause mismatches between the original waveform and the compressed waveform that are actually larger than the tolerance, if the waveforms are generated at a longer segment length.
This patch fixes this by just using the same segment length for all templates, which is specified on the command line. A check is included that the segment length is at least twice as long as the estimate of each template. This allows for using the same segment length as is used in …

Fix segment length bug in compress bank

---

docs/inference.rst

This changes the low-frequency cutoff used in the example script to 20Hz (along with the high pass filter frequency), and sets f_ref. I also changed the PSD segment length to 16s, with a stride of 8s, to be consistent with what is done in the search.

Some more updates to the inference docs

---

pycbc/waveform/generator.py

PR #1694 removed the wildcard import from `waveform.generator` in `waveform.__init__` to resolve namespace conflicts. That broke the examples in the doc strings in `generator.py`. This patch fixes this by importing the given class directly from the generator module in the examples.
Aside: the whole wildcard import in modules' `__init__` is becoming a real mess. I'm going to open an issue on this; I think we need to adopt a new policy to straighten this out pycbc-wide.

Update examples in waveform.generator

---

pycbc/workflow/tmpltbank.py

Currently there are subtle format differences between PyCBC and sbank HDF template banks (specifically the template_hash column), which cause failures if banks are fed directly to pycbc_inspiral. This can be solved by running bank2hdf to convert a sbank HDF bank to a PyCBC compatible HDF bank. Removing the necessity of this step can be a post-O2 goal.

Always run bank2hdf for HDF banks

---

bin/inference/pycbc_inference_extract_samples
pycbc/inference/option_utils.py
pycbc/inference/sampler_base.py
pycbc/inference/sampler_emcee.py
pycbc/io/inference_hdf.py
setup.py

This adds an executable, `pycbc_inference_extract_samples`, that will copy an inference result file to another inference file, but only writing out the desired samples. What samples to extract are given by the standard `--thin-start/end/interval / --iteration` arguments. If these are not provided, the acl and burn_in_iterations in the file will be used. By default, the program will write the samples to the new file with the same group structure as the original. In this case, the file could still be used as the starting point for another run even though it contains fewer samples.
If `--posterior-only` is given, the samples will be written as flat arrays, and a `posterior_only` attribute to be set in the output file. This causes information to be lost about walkers/temps/etc., but yields …

Add program to extract posterior samples from inference files

---

requirements.txt
setup.py

To introduce support for FITS files, I've added the latest version of astropy (v2.0.1) to the list of python packages in `requirements.txt` and `setup.py`. Since astropy requires numpy>=1.9.0, I have also updated the minimum required version of numpy from >=1.6.4 to >=1.9.0. The current virtualenv installation contains numpy v1.13.0, so this update shouldn't have any effect other than to guarantee compatibility with astropy.

Adding astropy to required packages

---

bin/pycbc_hdf5_splitbank

Line 106 of HDF split bank randomizes the order of the templates. However, the randomized bank is never actually written out to file. The randomization step at line 106 causes a copy of the template table to be made, which is then named "templates". But because `tmplt_bank.table` is never reset to this randomized copy, the original ordered table is the one that is written out by `write_to_hdf`. This patch fixes that by resetting the bank's table attribute to point to the new copy after the randomization. Thanks to @josh-willis for catching this.

HDF split bank doesn't actually randomize template order

---

pycbc/vetoes/chisq.py

pycbc_live log files are dominated by a few messages coming from chisq calculation for every trigger. I propose removing those messages, this drops the log size by almost 20 times.

pycbc.vetoes.chisq: silence ultra-verbose log messages

---

docs/conf_std.py
pycbc/inference/likelihood.py

This renames `_BaseLikelihoodEvaluator` to `BaseLikelihoodEvaluator` so that it will show up in the pycbc documentation page. That class defines a number of terms in its docs string which are useful to have in the docs pages. This patch also fixes some typos in the doc strings for both `BaseLikelihoodEvaluator` and `GaussianLikelihood`. Sample page is [here.](https://www.atlas.aei.uni-hannover.de/~cdcapano/LSC/scratch/testdocs/latest/html/pycbc.inference.html#pycbc.inference.likelihood.BaseLikelihoodEvaluator)
One thing that I haven't been able to fix, and can't figure out why, is the doc string for [GaussianLikelihood](https://www.atlas.aei.uni-hannover.de/~cdcapano/LSC/scratch/testdocs/latest/html/pycbc.inference.html#pycbc.inference.likelihood.GaussianLikelihood). The first equation …

Update likelihood docs

---

pycbc/frame/frame.py
pycbc/strain.py

Over the last few days, this error killed the analysis a couple times:
```
File "/home/pycbc.live/projects/pycbc_live_production/local/bin/pycbc_live", line 4, in <module>
__import__('pkg_resources').run_script('PyCBC==1.7.4', 'pycbc_live')
File "/home/pycbc.live/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
self.require(requires)[0].run_script(script_name, ns)
File "/home/pycbc.live/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1504, in run_script
exec(code, namespace, namespace)
File "/home/pycbc.live/projects/pycbc_live_production/local/lib/python2.7/site-packages/PyCBC-1.7.4-py2.7.egg/EGG-INFO/scripts/pycbc_live", line 415, in <module>
status = data_reader[ifo].advance(valid_pad, …
```

pycbc_live: survive vanishing frame files

---

bin/inference/pycbc_inference
pycbc/inference/option_utils.py
pycbc/inference/sampler_base.py
pycbc/inference/sampler_emcee.py
pycbc/io/inference_hdf.py

This patch adds a `--n-indepedent-samples` option to `pycbc_inference` that can be used instead of `--niterations`. If the new option is given, `pycbc_inference` will run until it estimates that it has obtained at least the requested number of independent samples. The number of independent samples is recalculated at each checkpoint. At the checkpoint the burn-in-iterations are updated and the ACLs re-calculated. The number of independent samples is then obtained by retrieving every ACL-th sample starting from the burn in iteration until the end from every walker. This should make doing large-scale PP tests easier.
At the moment this is probably overly conservative, since we're using the max ACL across all walkers. The issue reported in #1815  will probably make this more efficient.
Also, …

Specify desired number of indep. samples in pycbc inference

---

pycbc/events/simd_threshold.py
pycbc/filter/simd_correlate.py

I had trouble with some of the `weave` code for doing correlations and thresholding because I'm running on Mac OS X where both `clang` and `gcc` (even the *real* `gcc`) do not supply `error.h` (which is a non-standard GCC extension).  The behaviour is simple enough to mock up, at least for these uses where the format strings are simple.  The patch does so (I think), and would prevent all sorts of dirty hacks to get the code to compile on OS X.

Removed dependence on GCC function for better standards compliance.

---

bin/inference/pycbc_inference_plot_acf
bin/inference/pycbc_inference_plot_acl
pycbc/inference/sampler_base.py
pycbc/inference/sampler_emcee.py

This addresses #1815. @cmbiwer @farr it was fairly quick for me to do this, and I wanted it for my PP runs. I haven't added ACF support for emcee_pt yet, hence the work in progress tag.
Example output of `plot_acf` [here](https://www.atlas.aei.uni-hannover.de/~cdcapano/LSC/projects/pycbc_inference/cbc/gw150914/kombine/example_test-nindep_samples-max_post/plot_acf_test.png).
@farr For emcee_pt: right now I'm computing the ACL separately for each temperature, than taking the max over all temperatures. Is that the correct thing to do?

Average ACF/L over walkers

---

pycbc/inference/sampler_emcee.py

The recent changes to the ACL code introduced two typos in the Emcee PT sampler's treatment of the ACL.  This branch fixes them.  Without the fix, attempting to run a simulation with the PT sampler gives errors like 
```
File "/Users/farr/anaconda3/envs/py2/bin/pycbc_inference", line 4, in <module>
__import__('pkg_resources').run_script('PyCBC==8876', 'pycbc_inference')
File "/Users/farr/anaconda3/envs/py2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 744, in run_script
File "/Users/farr/anaconda3/envs/py2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1499, in run_script
File "/Users/farr/anaconda3/envs/py2/lib/python2.7/site-packages/PyCBC-8876-py2.7.egg/EGG-INFO/script …
```

Fix  typo in emcee PT ACL computation.

---

bin/pycbc_condition_strain
pycbc/strain.py

There is currently an inconsistency in `pycbc.strain.from_cli`: the `dyn_range_factor` argument is ignored when generating fake strain in double precision, but it is honored in all the other cases (i.e. reading real frames, or outputting strain in single precision). This patch fixes that inconsistency so that `dyn_range_factor` is considered both when reading frames and generating fake strain, and irrespective of the output precision.
This patch also gives `pycbc_condition_strain` an explicit option to generate frames which are not scaled by the dynamic range factor. Previously this behavior was implicitly achieved by virtue of the inconsistency in `pycbc.strain.from_cli`. Thanks Derek Davis and @stevereyes01 for finding this.
A couple docstrings have also been updated to (hopefully) …

Fix inconsistency in pycbc.strain.from_cli, add option to condition_strain

---

setup.py

Create a 1.7.6 release so that we get the statmap file from CVMFS not git.ligo.org

Set for 1.7.6 release

---

pycbc/waveform/ringdown.py

When introducing the spherical harmonics into the ringdown, I forgot to add them to the taper too, so that the td ringdown with tapering ended up looking like
https://www.atlas.aei.uni-hannover.de/~miriam.cabero/LSC/tests/ringdown_approximants/wfMassSpin_taper.png
That also brought to my attention that the epoch for the multi-mode tapered ringdown was wrong, although this must have been introduced later because I remember doing some sanity checks when I first added the tapering option, such as https://www.atlas.aei.uni-hannover.de/~miriam.cabero/LSC/tests/ringdown_taper/multi_mode.png
Anyway, in this PR I tried to fix both issues, so that a tapered ringdown now looks like https://www.atlas.aei.uni-hannover.de/~miriam.cabero/LSC/tests/ringdown_taper/spherharms_MassSpin.png
My only problem …

Solve issues with td ringdown tapering

---

pycbc/noise/reproduceable.py
pycbc/psd/estimate.py
pycbc/strain.py

This reduces the high memory usage in inverse_spectrum_truncate, keeping `pycbc_inspiral` within 2GB (at least during this stage). There's no real change in functionality, I just do some reordering and avoid calling `inverse_spectrum_truncation` on the full PSD when needed as that code stores a few representations of the full PSD, which is quite big in this case.
... This also fixes a minor issue that the PSD representation previously changed (slightly) based on the amount of data being requested, so you wouldn't always get exactly the same data back. Here the time-domain representation of the PSD does not vary based on the amount of data being requested, so this should be a little more consistent.
I also added some comments because it took a while to get my head around all the PSD …

Reduce mem usage in noise.reproducible

---

bin/inference/pycbc_inference_plot_prior

Addresses the Issue #1802 - sorry, I seemed to have forgotten about this.
As far as @cdcapano comment in #1802, there would need to be some reworking of that plotting function. The points need to be weighted. But yeah, we should move from corner now. I do like the aesthetics of the plots you've put together.
If you want ``import corner`` gone ASAP, instead of plotting the PDF we can draw from the prior and set the default very high.

Reorder imports in prior exe plotting

---

pycbc/strain.py

The witness-frame-type options were added to the strain option group, but not the multi ifo strain option group. That broke `pycbc_inference`, or any other program that uses the multi ifo option group. This fixes that by checking if the attribute exists in `from_cli` before trying to access it.

witness-frame-type option breaks from_multi_ifo

---

bin/hdfcoinc/pycbc_page_foreground
bin/hdfcoinc/pycbc_page_snrifar
bin/hdfcoinc/pycbc_page_snrratehist

This changes the behaviors of the plotting codes so that instead of failing when given too many hierarchical removals, they instead produce empty plots or an empty table.
Relevant plots for these cases:
SNR-RATE-HIST makes if you ask it to plot 3 hierarchical removals: 
https://www.atlas.aei.uni-hannover.de/~steven.reyes/LSC/O2/test_h_removal_plots_remake/snrrate-h-removal-3.png
SNR-IFAR CUMULATIVE HIST makes:
https://www.atlas.aei.uni-hannover.de/~steven.reyes/LSC/O2/test_h_removal_plots_remake/snrifar-h-removal-3.png
SNR-IFAR SIGNIFICANCE PLOT makes:
https://www.atlas.aei.uni-hannover.de/~steven.reyes/LSC/O2/test_h_removal_plots_remake/snrifar-not-cum-h-removal-3.png
Foreground Table makes:
https://www.atlas.aei.uni-hannover.de/~steven.reyes/LSC/O2/test_h_removal_plots_remake/H1L1-PAGE_F …

Let hierarchical removal plotting codes generate empty plots

---

tools/docker_build_dist.sh

This adds the [hide cell](https://github.com/kirbs-/hide_code/) jupyter extension to the PyCBC Docker image and the virtual environment.

Install module for hiding cells in notebooks

---

bin/workflows/pycbc_make_coinc_search_workflow
pycbc/workflow/__init__.py
pycbc/workflow/gatefiles.py

This restores the ability to set gating files for a detector at the workflow level and adds the gating files to all the codes that need them, rather than managing this on a per-job basis.
To enable this run ``pycbc_make_coinc_search_workflow`` with, e.g.
```
--config-overrides \
"workflow-gating:gating-method:PREGENERATED_FILE" \
"workflow-gating:gating-file-h1:https://git.ligo.org/detchar/veto-definitions/raw/4e17592aa5e8b2f832cefca4bb8d42d2a20b54ea/cbc/O2/H1-GATES-1185937218-1375500.txt" \
"workflow-gating:gating-file-l1:https://git.ligo.org/detchar/veto-definitions/raw/4e17592aa5e8b2f832cefca4bb8d42d2a20b54ea/cbc/O2/L1-GATES-1185937218-1375500.txt" \
```
This adds will download the gating files, store them in the ``output`` directory and add the gate files to the DAX:
```xml
<file …
```

Setup gating files at the workflow level

---

pycbc/frame/frame.py
pycbc/strain.py

This adds a ``--frame-sieve`` command line argument which exposes the [``lal.CacheSieve``](http://software.ligo.org/docs/lalsuite/lal/group___l_a_l_cache__h.html#gaf03f09f0250f09e8fd718c7a4563c120) function to filter frame files. The string given to ``--frame-sieve`` is used to filter the frame files found (either on the command line or located by datafind).
For example, to use only frames from the local filsyste, ``/frames`` and not CVMFS:
```shell
(pycbc-dev)[dbrown@sugwg-condor ~]$ pycbc_plot_singles_timefreq --f-low 20 --rank newsnr --num-loudest 20 --approximant 'SPAtmplt:mtotal<4' 'SEOBNRv4_ROM:else' --strain-high-pass 15 --sample-rate 2048 --pad-data 8 --frame-type L1_HOFT_C00 --channel-name L1:GDS-CALIB_STRAIN --trig-file …
```

Allow filtering of frames by url

---

bin/hdfcoinc/pycbc_page_snrifar

Revert to pycbc_page_snrratehist format where passing null produces either the full level of hierarchical removals (whether that is 0 or full).
That means we now produce :
Cumulative Plots:
0 passed as argument
https://sugwg-jobs.phy.syr.edu/~steven.reyes/O2/hierarchical_examples_gw170104/snr_ifar_cum_hist_0.png
no option given
https://sugwg-jobs.phy.syr.edu/~steven.reyes/O2/hierarchical_examples_gw170104/snr_ifar_cum_hist_null.png
Significance Cumulative Plots:
0 given as argument
https://sugwg-jobs.phy.syr.edu/~steven.reyes/O2/hierarchical_examples_gw170104/snr_ifar_not_cum_hist_0.png
no option given
https://sugwg-jobs.phy.syr.edu/~steven.reyes/O2/hierarchical_examples_gw170104/snr_ifar_not_cum_hist_null.png

Let pycbc_page_snrifar be consistent with other hierarchical removal plots

---

bin/pycbc_submit_dax
pycbc/workflow/datafind.py
pycbc/workflow/pegasus_files/pegasus-properties.conf
requirements.txt

This pull request allows the workflow generator to make use of multiple different PFNs for the same frame file. It also fixes a bug where ``convert_cachelist_to_filelist`` assumed that the frames were sequentially ordered in time, but nothing guarantees this.
I also added a ``condor_reschdule`` to ``pycbc_submit_dax`` to get a speedier response when submitting workflows.
I have tested both in the independently with the code:
```python
import os
import pycbc.workflow.datafind
from pycbc_glue import segments, lal
```
```python
urls = ['file://localhost/frames/O2/hoft_C01/H1/H-H1_HOFT_C01-11742/H-H1_HOFT_C01-1174200320-4096.gwf',
'file://localhost/cvmfs/oasis.opensciencegrid.org/ligo/frames/O2/hoft_C01/H1/H-H1_HOFT_C01-11742/H-H1_HOFT_C01-1174200320-4096.gwf', …
```

More flexible use of frame files in the workflow

---

bin/hdfcoinc/pycbc_coinc_statmap
bin/hdfcoinc/pycbc_page_ifar

The code works as follows.
```
usage: pycbc_page_ifar [--options]
Plots a cumulative histogram of IFAR forcoincident foreground triggers and a
subset ofthe coincident time slide triggers.
optional arguments:
-h, --help            show this help message and exit
--version             show program's version number and exit
--trigger-file TRIGGER_FILE
Path to coincident trigger HDF file.
--output-file OUTPUT_FILE
Path to output plot.
--decimation-factor DECIMATION_FACTOR
Decimation factor used in background
estimation.Decimation factor means that every nth
timeslide kept all of its coincident triggers inthe
HDF file.
--all-decimated-background-min-ifar VAL
Threshold the IFARs of decimated background events
before combining them and rescaling to zerolag (green
line). Plotting all decimated …
```

Add hierarchical removal plots for pycbc_page_ifar

---

bin/hdfcoinc/pycbc_page_foreground
bin/hdfcoinc/pycbc_page_ifar
bin/hdfcoinc/pycbc_page_snrifar
bin/hdfcoinc/pycbc_page_snrratehist
bin/workflows/pycbc_make_coinc_search_workflow

Minor patches to improve the clarity of the message printed when there are no more events louder than the background and the section titles.

Clean up removal messages

---

bin/inference/pycbc_inference
pycbc/inference/sampler_emcee.py

This patch allows emcee and emcee_pt to start from a given samples file. No setting state support has been added yet, so this will not give the same result as if no break were carried out. A warning is printed to screen informing the user of this.

Allow emcee to start from samples file

---

pycbc/workflow/minifollowups.py
setup.py

This is done correctly for ``pycbc_single_template`` but not for ``pycbc_plot_singles_timefreq `` which causes the ``pycbc_plot_singles_timefreq`` jobs to fail with:
```
IOError: [Errno 2] No such file or directory: &apos;file://localhost/home/dbrown/projects/aligo/o2/analysis-21/o2-c00-analysis-21-v1.7.9-vdf-5c09540-auto-dch-gates/output/gating/L1-GATES-1185937218-1375500.txt&apos;
```
Temporary patch for a running DAX is
```
perl -pi.bak -e  's+--gating-file file://localhost+--gating-file +g' /usr1/dbrown/pycbc-tmp.fsMfVJH09l/work/o2-c00-analysis-21-v1.7.9-vdf-5c09540-auto-dch-gates-main_ID0000001/*MINIFOLLOWUP*/*.sh
```
but this fixes it properly.
This also sets the release tag to 1.7.10 to make a new release with this fix.

The minifollow up generator need to be told that --gating-file takes a file

---

bin/hdfcoinc/pycbc_page_foreground

Fix bug that if no hierarchical removals were done that the results page doesn't crash trying to access something that's not written to file. That is to say, if no hierarchical removals were done, the original code tries to access `f['foreground_h0']` which is not written if hierarchical removals are not done. This also insures that old statmap files are still compatible with `pycbc_page_foreground`.
This also permits backwards functionality with old coinc files to default to original behavior.

Fix bug that in pycbc_page_foreground if no hierarchical removals were done

---

bin/pycbc_condition_strain

It seems this would fix the problem @a-r-williamson is having with Virgo data in coh_PTF. What do people think?

pycbc_condition_strain: permit unscaled single precision output

---

bin/hdfcoinc/pycbc_page_ifar

There was a bug in the foreground events that were being printed when hierarchical removals were done in the statmap code.
The code previous to this PR would print the correct results for all hierarchical removals, except it was plotting the wrong result for showing no hierarchical removals. The executable wouldn't fail, it just showed the wrong results.
This plot shows the O1 GW's, but at the stage of no hierarchical removal, GW150914 has an IFAR > 10^6 years, whereas GW151226 should display an IFAR of 700 years or so.
https://sugwg-jobs.phy.syr.edu/~steven.reyes/O2/exclusive_hierarchical_removal_tests_3GWs_O1/ifar_lightning_exclusive_0_open.png
The other plots for running without an option (full results), and hierarchical removal results at stages 1, 2, N, were all correct.
This new …

Patch pycbc_page_IFAR, h_0 level plot

---

examples/cal/foton_filter_esd_saturation/pycbc_foton_filter
pycbc/filter/fotonfilter.py

I needed to make these modifications when testing DetChar hardware injections to check for PCAL saturations. It seems ROOT dependencies have been pulled into the foton package.

Modified pycbc.fotonfilter module to work with new version of foton

---

pycbc/events/events.py

As discussed some time ago the `threshold` function within events.py uses memory caching which can be confusing. For CPU usage at least, the simple `threshold_only` function will suffice in most cases, and avoids this gotcha.
I would like to expose this for both GRB coherent development and for the HOM search.

Expose threshold_only

---

pycbc/distributions/arbitrary.py

This argument is no longer used.

Remove extra argument in FromFile.from_config

---

pycbc/events/stat.py

There is currently no option to do new SNR *and* SG veto, but *not* use the phase-time stuff. This combination will be useful for testing of higher-order mode search development in the coming months, where phase-time may not be so obvious!
This has been tested on end-to-end runs as part of a short-author paper on higher-order modes. (Although we then realised that SG stat is not published anywhere, so we are not using those results)

Add newSNR + SG stat

---

.gitignore

This one's pretty simple: Add the `PyCBC.egg-info` directory to .gitignore so git status doesn't list this.

Ignore the egg-info directory

---

pycbc/inject/inject.py

This allows the inject module to use hdf files created by `pycbc_create_injection`. Since we need to continue to support xml at the moment, I've added this ability by copying the current `InjectionSet` to two different classes, `_HDFInjectionSet` and an `_XMLInjectionSet`, and modified the former to read hdf files. Now, `InjectionSet` initializes one of those based on the file extension. I figure that when we get to the point that we can drop xml support, we can just delete `_XMLInjectionSet` and rename `_HDFInjectionSet` to `InjectionSet`.
I've tested this on a single injection using `pycbc_condition_strain`. Here is a plot of the injection in zero noise when generated from the xml file:
https://www.atlas.aei.uni-hannover.de/~cdcapano/LSC/scratch/hdfinj_tests/xml_strain.png
the hdf file: …

Add ability to read hdf files in inject module

---

bin/hwinj/pycbc_generate_hwinj

This is a pull request to allow the use of tidal parameters when using pycbc_generate_hwinj. This would be much easier if we had moved to HDF injection files as XML does not include these column names. The solution here is not great, but it's the best I can do.
The basic idea is that if tidal terms are given we dynamically update the definition of the SimInspiral table to include those terms and output an XML file containing them. We *could* output an XML file omitting these terms, but I would prefer that the XML file actually be a representation of the injection that was done.
This is currently being tested, but I open this here for feedback.

Allow tidal terms in pycbc_generate_hwinj

---

.travis.yml
docs/building_bundled_executables.rst
pycbc/workflow/pegasus_files/osg-site-template.xml
tools/docker_build_dist.sh

This switches the ROM data from the old SVN release to git hash e02dab8c from the new repository at https://git.ligo.org/lscsoft/lalsuite-extra

Switch ROM data path from SVN rev 11 to git hash e02dab8c

---

pycbc/distributions/arbitrary.py

As pointed out in issue #1882, `FromFile`'s `from_config` function is currently broken. This was due to changes in PR #1704; when `FromFile`'s parent class was changed from `BoundedDist` to `Arbitrary`, the `from_config` no longer worked. This patch fixes this by just calling the `bounded.bounded_from_config` function directly.

Fix FromFile's from_config function

---

.travis.yml
Dockerfile
docs/install_lalsuite.rst
tools/docker_build_dist.sh
tools/einsteinathome/pycbc_build_eah.sh
tools/install_travis.sh

This updates the PyCBC build to use the lalsuite commit https://github.com/lscsoft/lalsuite/commit/95ad957cee1a37b7fc3128883d8b723556f9ec38
It also removes PyLAL from the PyCBC virtual environment.
To avoid hitting Travis disk space limits, I also reduced the disk space needed in the Travis build by using ``language: minimal`` for all of the builds that run inside Docker containers.
This patch makes the Docker image build more robust by adding ``|| exit 1`` in the Travis script so that Travis will fail if Docker commands fail.
The new lalsuite build requires that lalapps be configured with the additional flags ``-lcrypto -lssl -lstdc++`` and installs ``openssl-static`` needed by these commands.
It enables the ``hide_code`` jupyter extension, which was previously installed by not turned …

Update lalsuite hash to 95ad957

---

bin/inference/pycbc_inference_plot_posterior
pycbc/inference/option_utils.py
pycbc/results/scatter_histograms.py

Adds capability to plot multiple posteriors from different files on top of each other. This feature has been requested by a few people.
Example of PR so far: https://sugwg-jobs.phy.syr.edu/~cbiwer/projects/inference_multi_io/test/test.png
Want to make the colors in the titles of the histograms match the contour colors but matplotlib apparently doesn't have very good support for LaTeX colors so I'll get back to this.
Also need to scale histograms over all inputs instead of the last one plotted.

Allow multiple posteriors overlaid on each other

---

requirements.txt

This is required to ensure that an old version of pyOpenSSL doesn't get installed, which is breaking the Travis build. This patch should be reverted when dqsegdb declares that it requires a later-than-version X version of pyOpenSSL.

Use recent version of pyOpenSSL

---

bin/inference/pycbc_inference
pycbc/inference/likelihood.py
pycbc/transforms.py
pycbc/waveform/generator.py

This patch does two things: adds a `CustomTransform` class, and the ability to specify `waveform_transforms` in the ini file.
The `waveform_transforms` can be used to specify transforms to go from the variable args to parameters understood by the waveform generator. (This is different from the sampling transforms, which provide transforms to go to/from variable args to sampling args.)
The `CustomTransform` class can be used to define custom transforms in the config file using functions in `FieldArray`'s `functionlib`. At the moment it doesn't support inverse transports, but what's there now is enough to use with the waveform transforms.
Example for the inference ini file:
```
[waveform_transforms-dquad_mon1]
name = custom
inputs = lambda1
dquad_mon1 = dquadmon_from_lambda(lambda1)
```

Add waveform transforms, and CustomTransform

---

pycbc/inference/sampler_kombine.py

When saving kombine's kde dataset when checkpointing the number of walkers are used to set the maximum size. However, kombine may use more points in its kde than the number of walkers. This means our checkpointing will break if, e.g., Ben pushes [this branch](https://github.com/bfarr/kombine/commit/0d8d72dce5475d17f2a75239625c7b653c402d2b) to kombine's master. This patch future proofs this by using the sampler's kde size.

Allow for different sized kde

---

pycbc/waveform/parameters.py
pycbc/waveform/waveform.py

This PR replaces [#1763](https://github.com/ligo-cbc/pycbc/pull/1763) with this rebased and cleaner PR.
mode_array was introduced in lalsimulation in this
redmine issue https://bugs.ligo.org/redmine/issues/5592
see example python script: https://bugs.ligo.org/redmine/attachments/5911/mode-array-example.py
It is a method that allows the user to specify the exact
(l,m) modes to use when generating a waveform.
Currently on the NR waveforms are supported.
This patch adds the mode_array parameter to get_td_waveform
Note: the default behaviour is completely unchanged.
```
import matplotlib
matplotlib.use('Agg')
import lal
import lalsimulation as lalsim
from pycbc import pnutils
import h5py
import numpy as np
from pycbc.waveform import get_td_waveform
filepath = …
```

add mode_array support for get_td_waveform

---

bin/inference/pycbc_inference_plot_movie
pycbc/inference/option_utils.py

PR #1892 broke `pycbc_inference_plot_movie`: `option_utils` now expects `opts.input_file` to be a list, but the `opts.input_file` in `plot_movie` is a string, as it can only handle a single file. (I suppose we might change this in the future; not sure.) This patch to `option_utils` fixes that. The patch to `pycbc_inference_plot_movie` also fixes a pre-existing bug that prevented it from working on `emcee_pt` results.

Fix bugs introduced in plot movie

---

pycbc/results/legacy_grb.py

This is a very small change that allows PyGRB results to show the FAP as an upper bound when the on-source event is louder than all background.
See also: ligo-cbc/pycbc-pylal#44

Minor change to fix display of FAP for PyGRB results

---

pycbc/catalog/__init__.py
pycbc/catalog/catalog.py
setup.py

This allows things like. 
```
import pylab
import pycbc.catalog
c = pycbc.catalog.Catalog()
print c.names
pylab.scatter(c.median1d('mass1'), c.median1d('mass2'))
pylab.show()
```
>>>['GW170814', 'GW150914', 'LVT151012', 'GW151226', 'GW170104']
and
```
m = pycbc.catalog.Merger("GW150914")
ts = m.strain("H1").whiten(3, 3)
ts = ts.highpass_fir(35, 512).lowpass_fir(250, 512)
ts = ts.time_slice(m.time-.2, m.time+.15)
pylab.plot(ts.sample_times, ts)
pylab.show()
```

add some basic classes for accessing information about cbc events

---

bin/hdfcoinc/pycbc_plot_singles_vs_params

Setting should be 0 since only 'less than minimum' counts are excluded.

fix tiny bug in hexplots

---

bin/hdfcoinc/pycbc_plot_psd_file

This adds an `--ifos` argument to `plot_psd` to specify what PSDs to plot. This is so that this code can run on `pycbc_inference` result files (which do not have an `ifo_list` attribute, but do store the psds used in the same group format as the search's psd files). If no `--ifos` is provided, the code defaults to its current behavior.

Add an ifos argument to plot_psd

---

bin/pycbc_upload_xml_to_gracedb

Enable giving an IFAR threshold to `pycbc_upload_xml_to_gracedb`, so it does not dirt GraceDB with garbage events each time we find something in a box.

GraceDB upload threshold

---

bin/inference/pycbc_inference
pycbc/gate.py
pycbc/waveform/generator.py

This adds gating to both the template and data in `pycbc_inference`. I've tested by generating a template with/without a gate using FDomainDetFrameGenerator, then adding to some data with the same gate applied. [This plot](https://www.atlas.aei.uni-hannover.de/~cdcapano/LSC/scratch/template_with_gated_data.png) shows a Q scan of the template not gated; [this plot](https://www.atlas.aei.uni-hannover.de/~cdcapano/LSC/scratch/gated_template_with_gated_data.png) shows the template gated. I'm running a test run now.

Gate template along with data

---

pycbc/catalog/__init__.py
pycbc/catalog/catalog.py

Make the data retrieval a bit more robust to work in places like Azure notebooks. Now all events prior to GW170814 are accessible this way. The change in server after this point seems to be causing some remaining issue, but I think solving that requires coordination with LOSC.

add gw170814, use requests which is more robust

---

bin/inference/pycbc_inference_extract_samples
pycbc/inference/option_utils.py
pycbc/io/__init__.py
pycbc/io/inference_hdf.py
pycbc/io/inference_txt.py

Makes it easier for people to write CSV files from inference results.
Example command is:
```
pycbc_inference_extract_samples --input-file ${INPUT_FILE} --parameters mass1:m1 mass2:m2 --iteration 1000 --output-file test.dat --csv
```
The header of the CSV file will be the label from the ``--parameters PARAM:LABEL``.
Will write a CSV file where each row is an independent sample, eg. from above command:
```
m1 m2
1 1
2 2
3 3
```

Allow extract samples to write CSV.

---

pycbc/filter/matchedfilter_numpy.py
pycbc/scheme.py

As Alex and I discussed on Mattermost some time ago, there are times and cases where optimizations being used for the 256 * 2048 length FFTs, that we use regularly in analysis are highly sub-optimal when performing much shorter FFTs (1 * 2048 for example).
These shorter FFTs are regularly used in applications such as:
* sbank
* Brute-force PE
* Banksim
* Faithsim
Where one can greatly reduce the frequency spacing of waveforms before computing a match. Such codes can be slowed down by using the standard CPU scheme, so here I add a numpy scheme, as discussed, that is designed to be optimal, and used for, the short FFT cases.

Numpy scheme

---

docs/waveform.rst
examples/waveform/plot_detwaveform.py

It was pointed out to me this morning that we have no example in the documentation for generating a single waveform and projecting it into H1, L1, V1, ... This is easily fixed:
https://galahad.aei.mpg.de/~spxiwh/pycbc_docs/waveform.html#generating-one-waveform-in-multiple-detectors
(also adding notes about ra,dec,inclination,coa_phase conventions, as dec and inclination use different conventions).

Add new waveform example

---

bin/inference/pycbc_inference
pycbc/inference/burn_in.py
pycbc/inference/sampler_base.py
pycbc/io/inference_hdf.py

Currently, when using `n-independent-samples` in `pycbc_inference`, you need to specify a number larger than the number of walkers, otherwise the code will just quit after the first checkpoint. Specifying a number larger than the number of walkers means that an ACL must be calculated so that more than one sample can be retrieved from each walker. Getting an ACL can lead to running for a very long time after burn in has finished.
This patch fixes this by adding an `is_burned_in` array and attribute to inference files. This records whether or not each chain (and for the attribute, whether all chains) are burned in. When `n-independent-samples` is used, `pycbc_inference` will only count samples if `is_burned_in` is True. This allows the desired number of samples to be the same as the number …

Save burn-in state to file

---

bin/inference/pycbc_inference
pycbc/inference/likelihood.py
pycbc/inference/option_utils.py
pycbc/inference/sampler_base.py
pycbc/inference/sampler_emcee.py
pycbc/inference/sampler_kombine.py
test/test_inference.py

This patch adds a likelihood evaluator in which the likelihood function is the pdf of a multivariate normal distribution. The number of dimensions in the distribution is set by the number of variable args in the config file.
Example:
With config file:
```
x =
y =
[prior-x]
name = uniform
min-x = -10
max-x = 10
[prior-y]
name = uniform
min-y = -10
max-y = 10
```
And arguments:
```
pycbc_inference --config-files normal2d.ini --output-file test_normal2d.hdf --sampler kombine --verbose --likelihood-evaluator test_normal --niterations 10 --nwalkers 2000 
```
Yields: [2D norm posterior](https://www.atlas.aei.uni-hannover.de/~cdcapano/LSC/scratch/2dnorm.png).
You can also do 1D, although I found that kombine fails with a 1D p0 (this appears to be a kombine error, so not …

Add test gaussian likelihood

---

pycbc/inference/burn_in.py

This PR adds a function in the burn_in module to calculate the KS test between the samples from the last iteration and those from the midpoint of the portion of the chain being considered for each variable-args parameter, and return the `burn_in_idx` and the `is_burned_in` array to indicate whether the chain is burned in. The chains would be considered to be burned in if the p-value returned by the KS test is > 0.1 and < 0.9 for each of the parameters. The `burn_in_idx` array returned is used to advance the sampler.

Add function to perform the KS test to indicate if chains are burned in

---

examples/distributions/example.ini
pycbc/inference/option_utils.py
tools/docker_build_dist.sh

If a prior section is missing for one or more variable arg, raise an error stating which parameter the prior is missing for. This is to address issue #1950.

Give meaningful error when priors section missing

---

pycbc/io/record.py

This allows a single value to be passed to `add_fields` and `merge_list` when adding to a length-one array. This is to avoid errors like:
```
File "/Users/vivien/pe/master/lib/python2.7/site-packages/pycbc/io/record.py", line 327, in <genexpr>
if not all(merge_list[0].shape == arr.shape for arr in merge_list):
AttributeError: 'float' object has no attribute 'shape'
```

Allow fields to be added that are a single value

---

bin/inference/pycbc_inference_plot_posterior
pycbc/inference/option_utils.py
pycbc/results/scatter_histograms.py

When plotting two or three posterior distributions on the same plot it can get a bit messy with all the 50% and 90% contours and lines (see https://www.atlas.aei.uni-hannover.de/~miriam.cabero/LSC/plots/area_theorem/tst2.pdf).
With this patch, one can choose which confidence levels to plot, for instance to remove the 50% contour and line
https://www.atlas.aei.uni-hannover.de/~miriam.cabero/LSC/plots/area_theorem/O1_ringdown_posteriors.pdf
or to use completely different confidence levels, like 66% and 99%
https://www.atlas.aei.uni-hannover.de/~miriam.cabero/LSC/plots/area_theorem/tst.pdf

Add option to choose percentiles in pycbc_inference_plot_posterior

---

bin/inference/pycbc_inference
pycbc/inference/sampler_base.py
pycbc/inference/sampler_emcee.py

This simplifies the inputs to the `write_{results/chain/samples_group}` functions in the inference samplers. Currently these functions take optional `start_iteration`, `end_iteration`, and `index_offset` keyword arguments. The start/end iteration specify the start/end iteration of the chain in memory to write, while the index offset is used to write to a different set of indices in the file. This is more machinery than we need. We always write all data in memory to the file. The only thing we need to make sure of is that we append new data to the end of the dataset that is stored in the file.
This patch removes all of these keyword arguments, keeping only `start_iteration`. Now, `start_iteration` gives the index of the dataset in the file from which to start writing. If this is set to …

Simplify writing samples to inference file

---

pycbc/inference/sampler_base.py
pycbc/inference/sampler_emcee.py

Currently, we are writing samples to files in `fp['samples/{param}/[temp{k}/]walker{i}]`. It turns out that if we simply saved the (ntemps x) nwalkers x niterations as a multi-dimensional array to `fp['samples/{param}']` (so, basically the same way we hold this in memory) the output files are much smaller, it's faster to read and write, and it might mitigate one of the errors I was seeing when running PP tests.
This patch does exactly that. The write functions now just store the arrays for each parameter as-is to disk, instead of trying to separate walkers/temps into different groups. To preserve backward compatability with older files, I've renamed the old read function `_oldstyle_read_fields`. A decorator around `read_samples`, `_check_fileformat`, is used to figure out which …

Write samples to arrays instead of groups

---

pycbc/inference/likelihood.py

This patch adds a likelihood evaluator in which the likelihood function is the pdf of an 'eggbox function' as defined here: https://arxiv.org/pdf/1312.5638.pdf
e.g.
Example:
With config file:
```
x =
y =
[prior-x]
name = uniform
min-x = 0
max-x = 31.5
[prior-y]
name = uniform
min-y = 0
max-y = 31.5
```
and arguments:
```
pycbc_inference --config-files eggbox2d.ini --output-file test_eggbox2d.hdf --sampler kombine --verbose --likelihood-evaluator test_eggbox --niterations 100 --nwalkers 2000
```
we get: [eggbox2d_posterior](https://sugwg-jobs.phy.syr.edu/~daniel.finstad/inference/analytic_likelihoods/eggbox2d_likelihood.png)

add test eggbox likelihood

---

pycbc/inference/likelihood.py

This patch adds a likelihood evaluator in which the likelihood function is the pdf of the Rosenbrock function as defined here: https://arxiv.org/pdf/1312.5638.pdf
e.g.
Example
Using config file:
```
x =
y =
[prior-x]
name = uniform
min-x = -20
max-x = 20
[prior-y]
name = uniform
min-y = -20
max-y = 20
```
and arguments:
```
pycbc_inference --config-files rosenbrock2d.ini --output-file test_rosenbrock2d.hdf --sampler kombine --verbose --likelihood-evaluator test_rosenbrock --niterations 100 --nwalkers 2000
```
yields: [Rosenbrock2d_posterior](https://sugwg-jobs.phy.syr.edu/~daniel.finstad/inference/analytic_likelihoods/rosenbrock2d_likelihood.png)

add test Rosenbrock likelihood

---

pycbc/events/simd_threshold.py
pycbc/events/threshold_cpu.py
pycbc/filter/matchedfilter_cpu.py
pycbc/filter/simd_correlate.py
pycbc/types/array_cpu.py
pycbc/vetoes/chisq_cpu.py
pycbc/waveform/compress.py
pycbc/waveform/spa_tmplt_cpu.py
pycbc/waveform/utils.py
pycbc/weave.py

It seems that on some platforms (or maybe just within cvmfs.. more testing needed to verify) the import order is such that local imports are *not* preferred over absolute ones. This causes the weave package to be picked up instead of pycbc.weave and so in executables that didn't explicitly do an import of pycbc.weave, the file locking is not always enabled.

be explicity about not using a relative import

---

bin/pycbc_live

This makes it so pycbc_live only checks the connection to gracedb if the executable is set to upload triggers. This default had caused the program to fail in testing mode, when no upload was desired, and no connection was available.

Has pycbc_live only check access to GraceDB if upload enabled

---

pycbc/frame/frame.py

The integrity check is extremely expensive for large files with many channels as it requires reading the entire file for each verification.

add check integrity option to query and read

---

bin/inference/pycbc_inference
pycbc/io/inference_hdf.py

This PR allows the injection parameters to be saved to the Inference file under a group `injection_parameters`, if pycbc_inference is using an injection file. This is only implemented for injection files in hdf/h5 format.

Save injection parameters to InferenceFile

---

pycbc/inference/likelihood.py

This patch adds a likelihood evaluator in which the likelihood function is a two-dimensional 'volcano' function, e.g.
Example:
using config file
```
x =
y =
[prior-x]
name = uniform
min-x = -20
max-x = 20
[prior-y]
name = uniform
min-y = -20
max-y = 20
```
and arguments
```
pycbc_inference --config-files volcano2d.ini --output-file test_volcano2d.hdf --sampler kombine --verbose --likelihood-evaluator test_volcano --niterations 100 --nwalkers 2000
```
yields [volcano2d_posterior](https://sugwg-jobs.phy.syr.edu/~daniel.finstad/inference/analytic_likelihoods/volcano2d_posterior.png)

add test volcano likelihood

---

bin/inference/pycbc_inference_plot_inj_recovery
setup.py

This PR depends on #1988. Keep this on hold until something with #1988 is done.
Adds an executable that plots the recovered vs injected parameter values for a population of injections analyzed with ``pycbc_inference``.
Example plot: https://sugwg-jobs.phy.syr.edu/~cbiwer/projects/inference_write_inj/plots/test2.png
Example command line on ``sugwg-condor``: https://sugwg-jobs.phy.syr.edu/~cbiwer/projects/inference_write_inj/plots/run_pycbc_inference_plot_inj_recovery.sh

Add recovery plot for inference injection runs

---

docs/inference.rst

@micamu just pointed out to me that the PSD start/end times in the inference docs are using a larger time than expected. The PSD start time should be the trigger time +/- the desired PSD data length (1024s) / 2. The way the script sets it up now, however, it uses the gps start/end time -/+ the data length / 2, giving a total data length of 1024s + 16s. This isn't terrible, it just results in using slightly more time than what you might expect. Still, better to fix to be obvious.

Fix the psd start/end times in the inference docs

---

pycbc/waveform/generator.py

Right now, if a parameter exists in the variable args that are passed to `CBCGenerator` that is not recognized in the list of parameters, an error is raised. This unnecessarily limits the freedom to try out new changes to the waveforms code, and prevents being able to provide priors on arbitrary functions of parameters. This patch causes a warning to be printed instead if an unrecognized parameter is passed.

Do not raise an error if an unrecognized parameter is passed to the CBC generator

---

docs/index.rst
docs/inference.rst
docs/inference/viz.rst

Makes the inference docs a bit more heirarchical and also show more in the tree at the top-leve. See exampl here. 
https://ldas-jobs.ligo.caltech.edu/~ahnitz/home/projects/play/pycbc/docs/_build/html/index.html

make the pycbc inference docs a bit more heirarchical

---

docs/install.rst

We've deprecated pycbc-glue, so we probably should not encourage installing a development version (nor add to clutter on the install instructions).

remove pycbc-glue develop doc

---

setup.py

`trace.fullmodname` was undocumented in Python 2 and actually became an internal function in Python 3. We should not depend on it.

Fix import error in setup.py under Python 3

---

tools/travis_build_and_test.sh

#1941 introduces a change that requires a fairly recent lalsuite version for the Travis tests to pass. From the current Travis configuration it looks like the lalsuite version is older than the requirement, but nevertheless Travis passes for #1941. If you go to the Travis log, you clearly see all template bank tests failing, but the end result marked as a success nevertheless. This may be the culprit.

Fix error in Travis test script

---

bin/hdfcoinc/pycbc_page_foreground

Not sure how this happened or didn't get picked up in automated tests, but `pycbc_page_foreground` is not currently a python executable.

Bug-fix for pycbc_page_foreground

---

pycbc/inference/likelihood.py

This patch rescales the test_volcano distribution so that the ratio of likelihood on the rim to that in the central depression is less so that the posterior contains samples in the central region.
The rescaled distribution:
A minimal example using config file:
```
x =
y =
[prior-x]
name = uniform
min-x = -20
max-x = 20
[prior-y]
name = uniform
min-y = -20
max-y = 20
```
and arguments:
```
pycbc_inference --config-files volcano2d.ini --output-file test_volcano2d.hdf --sampler kombine --verbose --likelihood-evaluator test_volcano --niterations 100 --nwalkers 2000
```
gives [shallow_volcano_posterior](https://sugwg-jobs.phy.syr.edu/~daniel.finstad/inference/analytic_likelihoods/shallow_volcano.png).
And a fully burned-in run gives …

rescale test_volcano likelihood evaluator

---

pycbc/io/inference_hdf.py

@cdcapano I think you forgot to change how some functions are called when you changed the ``InferenceFile`` class.
EDIT: For a little more info, the attribute ``self.sampler`` no longer exists.

Use sampler class attribute in Inference HDF

---

bin/inference/pycbc_inference_plot_posterior

Adds meta-data to ``pycbc_inference_plot_posterior`` executable.

Add metadata to posterior plot.

---

pycbc/inference/sampler.py
pycbc/inference/sampler_kombine.py
pycbc/inference/sampler_mcmc.py
pycbc/results/scatter_histograms.py

This pull requests adds a very, very simple [Metropolis–Hastings](https://en.wikipedia.org/wiki/Metropolis%E2%80%93Hastings_algorithm) algorithm as a `mcmc` sampler.
It's meant more as an illustration of how to add a simple sampler (and as a learning exercise for me). As such, I'd really appreciate feed-back, in particular:
-  To specify parameter values ended up using numpy's structured arrays, record arrays, lists, dictionaries, tuples, and pycbc's FieldArrays. There is got to be a way that does not involve so much conversion.
- I also added `normed=True` to the histogram plotting to make it easier to over-plot a target distribution, such as the normal distribution:
Future improvements could include parallel tempering and jump-size adaptation.

Mcmc sampler

---

pycbc/frame/frame.py

This allows the gw_data_find option urltype to be specified in the frame_paths function.

Option to specify url type in frame_paths

---

bin/pycbc_optimal_snr

This is no longer needed since the weave cache should no longer have lock problems here.

remove optimal snr kludge

---

bin/pycbc_optimal_snr

This patch will randomly sort a list of injections before doing the parallel stuff in optimal SNR to ensure that one process doesn't get all the injections if the injection file covers a time span much larger than the time being analysed.

Randomize optimal_SNR

---

bin/hdfcoinc/pycbc_page_coinc_snrchi
pycbc/events/triggers.py
pycbc/io/hdf.py
pycbc/pnutils.py

The conversions module is replacing functions in pnutils. This removes the phenomb_chi function which called into lalsimulation in favor of the existing pure python version.

remove phenomb_chi 

---

pycbc/results/scatter_histograms.py

Right now when you call the ``scatter_histogram`` module to create a plot, if you give 1 parameter and ask for a scatter plot it fails. This PR makes sure than only when there is more than 1 parameter, then it will plot a scatter plot.

Avoid trying to do scatter plot if not enough parameters

---

pycbc/inference/sampler_base.py
pycbc/inference/sampler_emcee.py
pycbc/inference/sampler_kombine.py
pycbc/io/inference_hdf.py

This adds a function to do some simple integrity checks on an inference file to ensure it was not corrupted when written. The checks that are done are:
- can the file open?
- do all of the datasets in the samples group have the same shape?
- can the first and last sample in all of the datasets in the samples group be read?
Errors are raised if any of these fail; otherwise, the function just returns. If we want to add more checks in the future, they can just be added to this function.
This also turns on a [checksum](http://docs.h5py.org/en/latest/high/dataset.html#fletcher32-filter) on all data sets, which is h5py's way of checking for corruption. (Unfortunately, the docs don't indicate what error will be raised if a corrupted segment is detected, and I was unable to produce a single …

Check InferenceFile integrity

---

tools/docker_build_dist.sh

This (I think) will add sbank scripts to the release virtualenvs on CVMFS, so they can be used to build template banks with the hyperbank workflow. Addresses #2017.

Add sbank scripts to released virtualenvs

---

bin/pycbc_optimal_snr

I broke optimal SNR because I used `sorted`, which returns a list, when I needed to keep the object as a sim_inspiral table. `sort` is a much better choice here anyway and swapping to that fixes the issue (tested on ongoing NR injection IMBH tests).

Optimal_snr quick fix

---

pycbc/inference/sampler_mcmc.py
pycbc/io/record.py

Numpy 1.14 seems to have changed the way recarrays work, requiring
`__setitem__` to be given a tuple instead of an ndarray. This changes such
operation in a couple places in the inference code. Fixes #2038.
Note that the way I did it for FieldArray may not be the most efficient.

Fix inference test failure with numpy 1.14

---

bin/hdfcoinc/pycbc_page_coinc_snrchi
bin/hdfcoinc/pycbc_page_foundmissed
bin/hdfcoinc/pycbc_page_injtable
pycbc/events/events.py

I saw some failures in plotting jobs in an IMBH testing run, which was due to there being 0 found injections in the 300 + 300 injection set. The code should be able to handle this. A few tweaks are needed to allow this.
Note that some codes declare `/usr/bin/python` as the executable. This should always be `/usr/bin/env python` but I only fixed this in the codes that I touched (lots of cases have this wrong, but the EGG installation prevents this from being a problem in most cases).
Note also the events.py had some weird bit of code to allow one (I think!) to specify floats as input to the newsnr/effective SNR routines. This caused failures if the inputs were empty arrays (or length one arrays in many cases), so I've now fixed this to return output in the same format as the input (ie. if …

Fix zero-found-injections failures

---

bin/minifollowups/pycbc_foreground_minifollowup
bin/minifollowups/pycbc_injection_minifollowup
bin/minifollowups/pycbc_sngl_minifollowup
bin/plotting/pycbc_plot_qscan
pycbc/workflow/minifollowups.py
setup.py

This patch adds an omega scans executable to PyCBC and implements it within the PyCBC workflow. An example of this is here:
https://ldas-jobs.ligo.caltech.edu/~spxiwh/aLIGO/O2/analyses/O2_chunk19_HM/run3B/3._single_triggers/3.07_H1_loudest_noncoinc_time/
These new plots will appear in injection, single and coincident minifollowups.
This requires some minor changes to configuration files to add the new executable and options. Please advise on what file I should add those changes to?

Add omega scans to workflow

---

bin/pycbc_single_template

in addition to fixing the bug of not always recording the input trigger time value, disallow inconsistent options.

fix trigger time recording in single_template, also whitespace (alas)

---

docs/install_lalsuite.rst

See diff.  Disable lalapps is still the default but the user is offered the simplest alternative of not disabling lalapps.  The tricky/potentially unreliable (due to install location) instructions to just build static binaries and copy them by hand are hived off into a separate section.

Simplify lalapps build instructions and improve doc formatting

---

bin/inference/pycbc_inference_plot_acceptance_rate
pycbc/inference/sampler_base.py
pycbc/inference/sampler_emcee.py
pycbc/inference/sampler_kombine.py

This PR :
* Redefines `acceptance_fraction` for `kombine` in pycbc as "array of fraction of steps accepted by each walker" (like in emcee) ie of dimension `nwalkers` instead of "array of fraction of walkers accepted by each iteration", ie. dimension `niterations`. 
* Generalizes reading and writing acceptance_fraction for `kombine` and `emcee` samplers.
* Make changes in`pycbc_inference_plot_acceptance_rate` so as to specify the list of indices of temperatures (for parallel-tempered samplers) and list of indices of the walkers whose `acceptance_fraction`s will be plotted.
* Makes `pycbc_inference_plot_acceptance_rate` plot a histogram of the `acceptance_rate`s for all walkers. This used to plot a line plot before because it used to plot the acceptance fraction over the iterations based on …

Make acceptance function plotting code work for all current samplers

---

pycbc/frame/losc.py

This updates the losc module to add the O1 start end times. One can now do. 
>>> ts = pycbc.frame.query_and_read_frame('LOSC', 'L1:LOSC-STRAIN', 1126259362, 1126259662)
In addition, the standard strain cli functions can now operate on O1 events without needing for the instructions to explicitly name frame files. Simple change the frame-type to LOSC and set the channel name to H1/L1:LOSC-STRAIN.

add times for O1 data

---

bin/pycbc_inspiral
bin/pycbc_live
pycbc/fft/backend_cpu.py
pycbc/fft/backend_cuda.py
pycbc/fft/backend_mkl.py
pycbc/fft/fftw.py
pycbc/fft/mkl.py

This pull request makes several changes to how FFTs are handled in PyCBC. The main changes are:
* Always set a default backend (same as #2034, but for all schemes not just CPU)
* Remove the caching of 'plans' and similar data structures in FFTW/MKL support. This means that plans will be re-generated for the function-based API; users wanting to amortize that overhead should instead used the class-based API
* The options related to wisdom files are no longer performed as part of `fftw.from_cli`. This change allows that function to now occur anywhere within an executable, not just after entering a processing scheme context. So if specifying `--fft-backend mkl` users should see MKL used for all FFTs, not just those in the context block. This requires making explicit calls to the import wisdom …

Several changes to FFT infrastructure

---

bin/minifollowups/pycbc_sngl_minifollowup

The addition of the omega scans executable has highlighted a bug in pycbc_sngl_minifollowup, which would have caused some odd looking singles_timefreq plots on occasion. Basically `insp_data_seglists` is used to identify data that should be read in. It needs to be coalesced in these codes (as it is in the other two minifollowups executables). There are comments in the sub-functions in minifollowups.py where this variable is used saying "This input must be coalesced".

Segments need coalescing

---

pycbc/results/color.py

This PR modifies `pycbc.results.color` to import the IFO-prefix-based colour scheme from `gwpy.plotter.colors`, falling back to a copy from gwpy-0.7.
This will modify the PyCBC results pages to use the same colour schemes as recent publications (mainly H1=red, L1=blue), and the summary pages, which should improve the readability of the figures.

Import IFO colour scheme from GWpy (if available)

---

setup.py

The PyCBC library does not currently use astropy, so remove from setup.py requirements. It will still be installed onto CVMFS builds though so people who may be interested in using that can. It may be re-added in the future if the library itself is used.

remove astropy from setup.py requirements

---

pycbc/waveform/parameters.py
pycbc/waveform/waveform.py

Problem: EOB tidal wants to move to a mode where a user supplies lambda1 and lambda2, and, if the dQuadMon parameters are not set, the values of the dQuadMon terms will be calculated using universal relations. Alternatively the user can supply both lambda *and* dQuadMon input quantities. Therefore in this case dQuadMon = 0 and dQuadMon not set in the lal_dict structure are handled differently. Generically, this case might need to be handled in other instances as well, pycbc is supposed to be a connection to lalsimulation, and needs to be able to supply the same functionality as possible with lalsimulation commands directly.
@ahnitz suggested setting a default value of -1. This would work for this case, for most users, but one *might* consider a case where negative values of dQuadMon are …

Distinguish between dQuadMon = 0 and dQuadMon not given.

---

pycbc/workflow/core.py

I got frustrated with the multitude of _parsed_21312342345.ini files.
This patch swaps stuff around so the ini files are written when saving the workflow. This means they get written in the same directory as the .dax files and .map files. Now I am not frustrated :-).

Move the parsed configuration files

---

pycbc/results/versioning.py

We shouldn't be importing lalinspiral or lalmetio anymore so let's not do so in the versioning either. This prevents lalsuite builds without these packages explicitly for the core library.

clean up versioning

---

bin/hdfcoinc/pycbc_coinc_mergetrigs
pycbc/events/events.py

This is helpful when tracking overall usage of a workflow.  It doesn't add anything to the results pages, but does record into merged trigger files the runtime of each inspiral job.
If possible, I'd really like this in the release we're making for reruns.

record runtime of inspiral jobs

---

pycbc/conversions.py

Patch to add the conversion from final mass and spin to ringdown frequency and damping time into the conversions module (for plotting of pycbc_inference ringown posteriors).
The function `get_lm_f0tau` is also in the ringdown module. For some reason, in my branch I had re-defined it in this module. Maybe there are problems importing the ringdown module? Or should I change it to just call the ringdown function?

Add ringdown conversions from mass-spin to freq-tau

---

pycbc/events/events.py

There was an erroneous `:` in events.py that is causing a Sphinx failure. This fixes it.

Fix Travis build failure

---

pycbc/transforms.py

Currently, `CustomTransform` can only be used on single floats. This causes an error if trying to use a custom transform with `pycbc_create_injections` and more than one injection. This fixes that so that `CustomTransform` can be used with arrays or list of values. It also adds some more documentation.

Allow CustomTransform to work with arrays

---

bin/pycbc_create_injections

This PR : Allows `pycbc_create_injections` to use `waveform_transforms` from the config file. Also saves the additional parameters that are returned after applying the transforms, to the output hdf file.

Use waveform_transforms in pycbc_create_injections

---

pycbc/psd/estimate.py

This PR modifies `pycbc.psd.estimate.welch()` to accept `window` as a `numpy.ndarray`. This allows users to specify their own arbitrary window, without requiring pycbc to handle more name->function mappings.
The sanity checks have been updated to fail if
- `window` is given as an array that doesn't match `seg_len`
- `window` is not an array, and isn't in the `window_map`

Updated psd.estimate.welch to allow window as ndarray

---

pycbc/frame/frame.py

If asking for frame times covering non-integer end times the datafind server (which only takes integers) needs to round the frame time *up*, not down. The fix here should be uncontroversial.

Need to round non-integer frame times up

---

pycbc/conversions.py
pycbc/cosmology.py
pycbc/distributions/spins.py

Currently, functions in the conversions module that need to do boolean operations (such as `primary_mass`) use the `ensurearray` function to make sure all inputs are arrays, so it can use the masking features of numpy. The results are passed through `formatreturn` before being returned. If the results have length 1, `formatreturn` will just return the single item in the array. This way, if you input floats, you get back floats.
The problem is if you give one of these functions a length-1 array you get back a float. This is inconsistent with how you would normally expect a python function to act when given a numpy array, and it can cause errors when using these functions. For example:
```
>>> conversions.primary_mass(10., 20.)
20.0
>>> conversions.primary_mass(numpy.array([10., 1.4]), …
```

Make conversions module consistent with numpy

---

bin/plotting/pycbc_plot_qscan

There's an issue with the `pycbc_plot_qscan` code with events right at the edge of science times. I hadn't realised that the whitening was removing data, which is causing issues where the trigger itself can be removed in the whitening.
It's not ideal, but I propose to fix this by just not removing the "corrupted" data in the case that the trigger is within the corrupted times.
This issue can cause failures in the current code, but it seems that in most cases you get non-sensical output rather than a failure.

FIx edge effect bug

---

bin/inference/pycbc_inference_plot_inj_intervals

This patch does a few things to `pycbc_inference_plot_inj_interval`:
* Drops the quantiles option, instead using `scipy.stats.percentileofscore` to calculate the x and y axes. This results in a more fine-grained line that always terminates at (1,1), as expected.
* Adds a KS test, and reports the results in the legend.
* Adds metadata to the plot so it'll appear in the results pages.
* Casts the injection table to a `FieldArray` so that the same functions can be used on both the samples and the injection parameters (e.g., currently, you'll get an error if you try to use the `primary_mass` function).
Old plot:
https://www2.atlas.aei.uni-hannover.de/~work-cdcapano/projects/pycbc_inference/pp_tests/emcee_pt/nonspinning_phenomd_n100-extra_plots/mass1_pp.png
New plot: …

Updates to plot_inj_interval

---

bin/inference/pycbc_inference

Adds a `--save-backup` option to `pycbc_inference`. If turned on, the backup file will not be deleted.

Give option to save backup

---

bin/inference/pycbc_inference
pycbc/inference/sampler_base.py

Currently, `BaseMCMCSampler.n_independent_samples` returns at least the number of walkers even if the sampler has not burned in yet. This results in a `pycbc_inference` quitting prematurely when resuming from checkpoint: if you are resuming from a checkpoint, then at start up the number of independent samples are retrieved, here: https://github.com/ligo-cbc/pycbc/blob/master/bin/inference/pycbc_inference#L394. If you have requested the number independent samples to be the same as the number of walkers, then the code will immediately think it has enough samples, and will exit.
This patch fixes that by having `BaseMCMCSampler.n_independent_samples` return 0 if it has not burned in yet. Since this is now checked by the sampler, it removes needing to check for burn in the loop over …

Check for burn in when counting number of independent samples

---

bin/inference/pycbc_inference_plot_inj_intervals
bin/inference/pycbc_inference_plot_movie
bin/inference/pycbc_inference_plot_posterior
pycbc/inference/option_utils.py
pycbc/results/scatter_histograms.py

This adds a `--plot-injection-parameters` to `plot_posterior` and `plot_movie`. With it on, the injection parameters will be retrieved from the file and plotted as the expected parameters. Example:
```
pycbc_inference_plot_posterior --input-file marginalization.hdf --output-file posterior.png --plot-scatter --plot-marginal --z-arg snr --verbose --plot-injection-parameters
```
yields [this](https://www2.atlas.aei.uni-hannover.de/~work-cdcapano/projects/test_phase_marginalization/marginalization_no_coa_phase/posterior.png) and
```
pycbc_inference_plot_movie --input-file marginalization.hdf --output-prefix movie_frames --movie-file movie.mp4 --frame-step 25 --plot-scatter --plot-marginal --z-arg snr --verbose --plot-injection-parameters --nprocesses 16
```
yields …

Plot injection values in plot posterior

---

pycbc/waveform/parameters.py

According to the general convention in literature, \lambda is the deformability parameter which has units [gm cm^2 s^2], amd \Lambda is the dimensionless tidal deformability parameter. What we use in our calculations in pycbc is \Lambda. This label is also used in plotting PE posteriors, so using the correct symbol might help in avoiding any confusion.

Fix Lambda label

---

pycbc/waveform/waveform.py

As caught by landscape, using an empty list as a default is dangerous. This make the default `required_args` in `waveform.props` `None` instead of `[]`. The `None` is replaced with `[]` in the function.

Use None for required args default

---

pycbc/results/legacy_grb.py

This is a minor change to reduce requirements on the version of lal that may be installed for basic pycbc library usage. I.E. allow some lal functionality without some of the python modules included in lalsuite.

don't explicitly require lal gpstime python module

---

docs/inference.rst

This option is required to generate gaussian noise, and is not provided by the gaussian noise example. This updates the docs to include a value, so one won't get an error.

provide strain high pass option for gaussian noise

---

pycbc/__init__.py

This PR removes the printing of the `ImportError` raised from the attempt to import `pycbc.fft.mkl` in `pycbc/__init__.py`.
The upstream error will always be empty:
https://github.com/ligo-cbc/pycbc/blob/e5a335efb8c4dae4a529f5ba86b132d00918bdbb/pycbc/fft/mkl.py#L6-L8
and as such is just annoying to print.

Removed print of mkl ImportError from __init__.py

---

pycbc/__init__.py

This PR fixes #2106 by modifying `pycbc/__init__.py` to use a relative import (which will be required for python3 anyway), and also provides `pycbc.__version__`, the standard metadata variable.

Fixed bug in import version info to __init__

---

tools/einsteinathome/pycbc_build_eah.sh
tools/einsteinathome/pycbc_etch64_compile-usr-local.sh

These two commit fix issues with the PyCBC build for Einstein@Home on Debian 4:
- 'wget' links to the system's openssl library, which is too old for github's ssl (which the script uses to determine the 'blessed' version of LALSuite). There is a version of 'curl' built manually and linked with a newer version of openssl on that machine. Howver, 'curl' is not installed e.g. on the Cygwin build system. So I introduced a (shell function) wrapper that uses 'curl' when available and falls back to 'wget' if not.
- Recent versions e.g. of matplotlib require the Python module 'bz'. This requires the package `libbz2-dev` to be installed on the machine, so I added this to the catalog of packages to be installed when setting up the machine.

Fix Debian4 Einstein@Home/OSG build

---

pycbc/waveform/utils.py

This adds functions to taper a frequency series using a Kaiser window (`fd_taper`), and a function to apply that to a FD waveform before transforming to the time domain (`fd2td`), both to `waveform.utils`.
Example:
```
hp, _ = waveform.get_fd_waveform(mass1=35., mass2=35., delta_f=1./32,
f_lower=15., approximant='IMRPhenomD')
waveform.apply_fseries_time_shift(hp, 16., copy=False)
h = waveform.fd2td(hp, delta_t=1./2048, left_window=(15.,20.))
fig = pyplot.figure()
ax = fig.add_subplot(111)
ax.plot(h.sample_times, h)
ax.set_xlim(-17.3,-15.9)
pyplot.show()
```
Yields:
https://www.atlas.aei.uni-hannover.de/~cdcapano/public_scratch/imrphenom_test.png
A TaylorF2 test, applying a window to both sides:
```
from pycbc import pnutils
f_isco = pnutils.frequency_cutoff_from_name('SchwarzISCO', 5., …
```

Add fd2td waveform functions

---

pycbc/inference/burn_in.py

This adds an burn in test based on ACL. The test considers the sampler to have been burned in if it has run for at least 10 ACLs. The choice of 10 is based on a suggestion in the emcee paper.
This test also fixes the KS test burn in: now a the sampler is considered burned-in if the p-value returned by the KS test is > than a threshold keyword argument, which defaults to 0.9.

Add ACL-based burn in and fix ks test burn in

---

pycbc/waveform/waveform.py

This allows injection of fourier domain approximants by exposing them all through the get_td_waveform interface. This is done in a way that ensures no time offset / phase offset is introduced in the conversion from fd to td. 
These are added with a new approximant name to differentiate.
The following all generated IMRPhenomD in the time domain now, but the get_td_waveform version will apply reasonable tapering at the start. 
In case anyone is wondering, injection in the time domain is still desired to avoid wraparound issues. An example would be where we want only part of the waveform to be injected since we are looking at a segment of strain that only contains a part of the signal. The waveform should *not* wrap around to the other end of the segment. Ensuring this is straightforward in …

allow injection of fourier domain approximants

---

examples/distributions/example.ini
pycbc/distributions/__init__.py
pycbc/distributions/masses.py
test/test_distributions.py

This addes a `UniformComponentMasses` distribution. This is mostly a wrapper around `Uniform`, but it requires that `mass1` and `mass2` be provided, and it ensures that `mass1 >= mass2` in the array returned by the `rvs` function.  This should fix annoying book-keeping issues when doing PP tests.
I stuck the distribution in a new module. If we add more mass-specific priors in the future, they can be added to this module.

Add uniform component masses distribution

---

tools/docker_build_dist.sh

This PR updates the `cvmfs` virtualenv builder to install LALSuite into the standard `VIRTUAL_ENV` path, rather than `VIRTUAL_ENV/opt/lalsuite`. This removes the need to use the `lal*-user-env.sh` scripts, which set numerous variables that aren't unset by `deactivate` (so result in a corrupt environment after `deactivate`).
Fixes #2089.
This means that the following environment variables are no longer set/modified
- `PKG_CONFIG_PATH`
- `PYTHONPATH`
- `LAL*_PREFIX`
- `LAL*_DATADIR`

Updated virtualenv builder to install LALSuite into standard virtualenv path

---

pycbc/inference/burn_in.py

Should've tested #2112 with `emcee_pt`... this allows the `n_acl` burn in to work with either single or parallel tempered samplers. Currently, when `n_acl` with `emcee_pt` you get the following error:
```
acl = max(sampler.compute_acls(fp, start_index=0).values())
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

Fix bug in acl burn in when using emcee_pt

---

pycbc/inference/likelihood.py
pycbc/inference/sampler_base.py
pycbc/inference/sampler_emcee.py
pycbc/io/live.py
pycbc/io/record.py
pycbc/transforms.py
pycbc/workflow/core.py
requirements.txt
setup.py

This PR updates string type checks for python3 by replacing references to unicode with `six.string_types` where appropriate.
**This adds a dependency on `six`** which has been added to `setup.py` and `requirements.txt`.
I deliberately didn't update `pycbc.ligolw` because `glue.ligolw` has already been patched.

Use string_types for string type checking

---

pycbc/waveform/parameters.py

This PR modifies `pycbc.waveform.ParameterList` to use `collections.OrderedDict` for all `ParameterList.xxx_dict` properties, to preserve the order of parameters.

Modified ParameterList to use OrderedDict for dicts

---

pycbc/distributions/joint.py
pycbc/events/stat.py

This PR fixes two lingering uses of the python2 `print` statement, these need to be `print()` function calls in python3.

Fixed two uses of python as a statement

---

pycbc/cosmology.py

This PR modifies `pycbc.cosmology._DistToZ` to store `numpoints` internally as `int`, meaning when `numpy.linspace` is called, we don't get a `DeprecationWarning` any more.

Fixed DeprecationWarning when using numpy.linspace

---

bin/hdfcoinc/pycbc_coinc_statmap

Add checks to not crash downstream code if there are not any foreground events after hierarchical removals.
This bug will creep up in downstream plotting codes if one runs a very small analysis on a gw event, or if somehow everything gets hierarchically removed.

Edge case of no foreground events after hierarchical-removal

---

pycbc/transforms.py

Right now the `MchirpQToMass1Mass2` transform and inverse assumes q > 1. This is problematic for PE if you are using a prior that is not symmetric around the mass1 = mass2 line, since it results in a sampler only sampling the mass1 > mass2 part of parameter space. This fixes this by making the transform return mass2 > mass1 if q < 1.

Allow mchirp, q transform to handle either q > 1 or q < 1

---

pycbc/noise/reproduceable.py

The colored noise function in the noise module has a default value for the low frequency cutoff. According to the documentation, that value us 10. Hz, but according to the function's arguments, that value is 1.0 Hz. 
This looks like a bug and it probably should be 10 Hz, so in this PR I am changing the function's argument to be low_frequency_cutoff=10.0

Fix bug in colored_noise function

---

examples/gw150914/gw150914_h1_snr.py
examples/gw150914/gw150914_shape.py

In the GW150914 examples, the delta_f arguments are given as 1./32
This seems not very informative for people who are not familiar with signal processing. First, they would have to notice that there is a "32" in the frame file name and realize that they might be related. Second, they might not necessarily know that delta_f = 1/duration (or even that the 32 in the frame file name is the duration of the data).
To make it a little bit more clear, and since this was an easy change not requiring extra comments/explanations, I have changed those 1./32 by ```1./h1.duration```
It would be possible to even add some comments explaining, for example, what the arguments of the low/highpass_fir are, why choose those specific low_freqs, or things like that. I didn't dare to do that though because I …

Minor change in GW150914 examples

---

bin/pycbc_compress_bank
pycbc/waveform/compress.py

This patch does two things:
1. Fixes a bug in the calculation of the starting index used for `inline_linear`. Currently, the floor of `f_lower / df` is used when figuring out what index to start the interpolation, whereas it should be the ceil. This fixes inconsistencies between `inline_linear` and scipy's `linear` for the starting index that's uses for some templates.
2. Allows `pycbc_compress_bank` to read bank files that have compressed waveforms in them. The old compressed waveforms are ignored.

Fix bug in start index calculation and simplify inline linear; allow compress bank to run on compressed files

---

bin/minifollowups/pycbc_single_template_plot

Matplotlib's agg backend needs to be set before importing `pycbc.results` (see #2150 ). This also passes the docstring to argparse.

Fix pycbc_single_template_plot error on headless systems

---

bin/hdfcoinc/pycbc_combine_coincident_events
setup.py

This executable combines "STATMAP" files together into one database, which can be used with existing plotting code (e.g. plotifar or snrifar). For now I'm just combining the coincident events, and not worrying about the single-detector trigger information or the template bank parameters, but we could look to add that as a future feature if it becomes necessary.
This used the old `pycbc_combine_statmap` executable as an example to build on.

Add new coinc event combiner executable

---

pycbc/conversions.py
pycbc/transforms.py

This PR : 
1. Changes the formulae in `mass1_from_mchirp_q` and `mass2_from_mchirp_q` so that if q < 1 they will return mass1 as the smaller mass and mass2 as the bigger mass, based on the definition of `q=mass1/mass2` used in PyCBC.
2. Removes the check in `MchirpQToMass1Mass2` in `transforms.py` for the smaller or bigger mass based on whether q < 1 or q > 1.
testing this PR : 
```
In [10]: mchirp = conversions.mchirp_from_mass1_mass2(1.62402681, 3.24805362)
In [11]: q = 1.62402681/3.24805362
In [12]: mchirp
Out[12]: 1.9760000029651446
In [13]: q
Out[13]: 0.5
In [14]: conversions.mass1_from_mchirp_q(1.9760000029651446, 0.5)
Out[14]: 1.6240268099999997
In [15]: conversions.mass2_from_mchirp_q(1.9760000029651446, 0.5)
Out[15]: 3.2480536199999994
```
I get `mass1` as the smaller mass …

Change m_1 > m_2 when getting masses from mc and q

---

pycbc/strain.py

Currently, pycbc_condition_strain is a bit cryptic for new users trying to generate a fake strain:
* if the user chooses a fake-strain option but does not provide a low-frequency-cutoff, the code fails at generating the PSD complaining about not being able to divide a 'NoneType' and a 'float'. In this PR I have added a sanity check in the strain module, such that it will raise a ValueError asking for the low-frequency-cutoff if a fake-strain option has been selected without the frequency option. This will make it easier to understand why the code failed.
* if the user chooses a fake-strain option different from zero noise, the strain-high-pass option is required to be passed as low frequency cutoff for the colored_noise function. Again it raises the same error as in the previous case if …

Make understandable which options are missing for fake strain

---

bin/pygrb/pycbc_make_offline_grb_workflow

This change fixes a bug introduced in #2143, where if segments existed for multiple IFOs within the start and end times, but after applying our data requirements we were left with only one IFO, the workflow generator behaved as if we still had multiple IFOs.
This change has been tested.

Fix bug in some single IFO pygrb runs

---

pycbc/inference/burn_in.py

This adds a burn-in function that uses sets the burn-in iteration to either `n_acl` or `max_posterior`, whichever comes first. This is useful for kombine: normally, `max_posterior` seems to work fine, but for low-SNR events `n_acl` is a better measure.

Add burn in that uses the minimum of max posterior and n acl

---

bin/pygrb/pycbc_make_offline_grb_workflow

Hi @pannarale, this was the problem I believe. Within the loop the padding was being applied over and over since the segments for the different IFOs are actually all the same object.

Avoid applying additional gating padding multiple times

---

setup.py

While installing PyCBC into a virtual environment via `pip install pycbc`, I found that matplotlib requires `six>1.10` while the installer only checks for `six>1.4`. The system I was on already had 1.9.0, so it wasn't forced to upgrade the installation to a version compatible with matplotlib.
`pip install pycbc` shows:
```
Requirement already satisfied: six>=1.4 in /usr/lib/python2.7/site-packages (from unittest2->pycbc) (1.9.0)
```
and importing matplotlib shows:
```
File "/home/thomas.massinger/opt/pycbc-hwinj/bin/pycbc_plot_hwinj", line 23, in <module>
import matplotlib as mpl; mpl.use("Agg")
File "/home/thomas.massinger/opt/pycbc-hwinj/lib/python2.7/site-packages/matplotlib/__init__.py", line 195, in <module>
"Matplotlib requires six>=1.10; you have …
```

Install six>=1.10.0 in setup.py

---

pycbc/conversions.py
pycbc/transforms.py

This PR : 
1. Changes the `chi_a` calculation in `conversions.py` to use `spin1z`, `spin2z` instead of `spin_p`, `spin_s`
2. Makes `transforms.AlignedMassSpinToCartesianSpin` use `mass1`, `mass2`, `spin1z`, `spin2z` instead of `m_p`, `m_s`, `spin_p`, `spin_s`.
Test : 
```
In [5]: conversions.chi_a(1.2, 2.2, 0.5, 0.7)
Out[5]: 0.2764705882352941
In [6]: conversions.chi_eff(1.2, 2.2, 0.5, 0.7)
Out[6]: 0.6294117647058823
In [7]: conversions.spin1z_from_mass1_mass2_chi_eff_chi_a(1.2, 2.2, 0.6294117647058823, 0.2764705882352941)
Out[7]: 0.5000000000000001
In [8]: conversions.spin2z_from_mass1_mass2_chi_eff_chi_a(1.2, 2.2, 0.6294117647058823, 0.2764705882352941)
Out[8]: 0.6999999999999998
In [10]: t = transforms.AlignedMassSpinToCartesianSpin()
In [14]: t.transform({'mass1': numpy.array([1.2]), …
```

Remove primary-secondary mass constraints in chi_a calculations

---

bin/inference/pycbc_inference

Currently, the burn-in iteration is re-calculated at every checkpoint, even if the sampler has already burned in. This makes it so that burn-in is only calculated if the sampler hasn't burned in yet.

Only re-calculate burn-in if needed

---

pycbc/filter/autocorrelation.py

This switches the ACL algorithm to that used in emcee (see Daniel Foreman-Mackey's blog post [here](https://dfm.io/posts/autocorr/)), which comes from notes & papers by A. Sokal. This is very similar to the current algorithm we use, but uses the entire data set for computing the ACL instead of just the first half. The function is also simplified to make it easier to read.

Simplify ACL algorithm

---

pycbc/strain.py

In principle one could think that when generating a fake strain and using an ASD file there is no need to provide a channel name, since one might expect that the channel name is only used for reading frame files. However, when one tries to add an injection to this fake strain, then a not very helpful error message appears (if one does not know the strain module, it could take them a while to figure out what the problem is). That is because the strain module uses the first two letters of the channel name to figure out which detector it is injecting the signal to.
With this PR, if one wants to generate a fake strain and provides an injection file to add a simulated signal to the strain, but not a channel name, then the error message will request a channel name in the corresponding format.

Error message for fake strain with injections

---

pycbc/fft/fftw.py
pycbc/fft/mkl.py

MKL and FFTW plans are currently never freed. That is a large memory leak when repeatedly calling fft using the function api.

Fix a memory leak when creating FFTW / MKL plans

---

tools/einsteinathome/pycbc_build_eah.sh

Should automatically become ineffective once branch `fix_eah_windows` at `git.ligo.org` is deleted,  i.e. after https://git.ligo.org/lscsoft/glue/merge_requests/40 was merged.
Could be reverted then, but doesn't need to.

E@H: hotfix for Windos/Cygwin build until lscsoft-glue#40 was merged

---

pycbc/detector.py
test/test_injection.py

I was asked today "What detectors does PyCBC's detector module support?" Finding out the answer was not so easy! So I added a list of the names that are allowed.
Tested as:
```
In [2]: pycbc.detector.available_detectors
Out[2]: 
[('G1', 'GEO_600'),
('A1', 'ALLEGRO_320'),
('H1', 'LHO_4k'),
('T1', 'TAMA_300'),
('V1', 'VIRGO'),
('E3', 'ET3_T1400308'),
('C1', 'EXPLORER'),
('P1', 'CIT_40'),
('K1', 'KAGRA'),
('E2', 'ET2_T1400308'),
('E0', 'ET0_T1400308'),
('I1', 'LIO_4k'),
('E1', 'ET1_T1400308'),
('O1', 'AURIGA'),
('B1', 'NIOBE'),
('H2', 'LHO_2k'),
('L1', 'LLO_4k'),
('N1', 'Nautilus')]
```
(Yes, some of these aren't even interferometers, but that's what we get.) .... This also provides the DETECTOR_NAME as defined in LAL, as some of these prefixes are very opaque.
The code to do this is a bit …

Including names of detectors available in lal

---

pycbc/strain.py

I'm afraid I introduced a bug in PR #2173 when combining all the if statements into one.
When Xisco tried to run the pycbc_inference example from the PyCBC documentation, he was getting that error all the time even if he had specified the channel-name. After some trials I noticed the error would always appear if there was an injection-file given (I had been running with ringdown-injection-file, that's why I didn't spot it before).
In this PR I inverted the order of the options in the if statement to correct for that.

Fix bug introduced in error message

---

.codeclimate.yml

This PR moves the CodeClimate config management from the web front-end (visible only be me) to a config file in the repository. This starts from the existing config then:
* I add exclude rules for test, docs, examples and tools. 
* I have added support for pylint (currently in beta, but useful nonetheless, will move out of beta when it moves out of beta in CodeClimate)
* Loosened CodeClimate built-in test severity, following what @cdcapano did in GWIN.
* Added additional plugins used by GWIN, but not yet used here.
This might need some further tuning, but CodeClimate can help to explain how to disable a test if someone thinks some results are not useful (I can also mark issues in the front-end as "not a real issue" where needed).
.... I still miss landscape, but CodeClimate is coming …

Enable pylint and edit CodeClimate config

---

bin/inference/pycbc_inference
pycbc/pool.py

Checkpoint validation should be after the sampler creation as this is where the mpi process will branch. If you do it afterwards it ensures that this part is *only* run by the master process, preventing a failure mode where every process tries to do a file copy of the backup or checkpoint file.

move checkpoint check after pool lock

---

bin/hdfcoinc/pycbc_plot_singles_vs_params

This PR allows for custom trigger filtering in `pycbc_plot_singles_vs_params`.
The functionality of the `--min-snr` argument is retained by combining that option with `--filter-string` to make an overall trigger filter.
Code ran successfully when providing `--min-snr 5.` and `--filter-string "(self.snr < 100) & (self.mass1 > 30)"` as individual arguments, one at a time, and with neither provided.

Added option to provide a filter string in pycbc_plot_singles_vs_params

---

bin/pycbc_live

This is helpful as the head node may not be the same architecture and so can't import the same wisdom files. The files are only really needed for the compute nodes.

put wisdom import within try/except for pycbc live

---

bin/inference/pycbc_inference

Bugfix to allow inference to continue from a checkpoint after burn-in

Add burn_in iterations

---

requirements.txt
setup.py

I'm trying to start moving us towards python3 support. This removes some setup.py cruft and adds cython as a setup install requirement (I want to see now that our build environments will properly pull in cython before I start hard requiring it in the code).

remove setup.py cruft in prep for cython support

---

tools/einsteinathome/H1L1-SINGLE_TEMPLATE_BANK.xml
tools/einsteinathome/HL-INJECTIONS.xml
tools/einsteinathome/pycbc_build_eah.sh

There is currently a bug in the v1.11.1 bundled executable that it is missing some weave code needed for injections. This causes the error
```Traceback (most recent call last):
File "pycbc_inspiral", line 204, in 
File "pycbc/strain/strain.py", line 257, in from_cli
File "pycbc/inject/inject.py", line 355, in apply
File "pycbc/inject/inject.py", line 414, in make_strain_from_inj_object
File "pycbc/waveform/waveform.py", line 457, in get_td_waveform
File "pycbc/waveform/waveform.py", line 622, in get_td_waveform_from_fd
File "", line 2, in cyclic_time_shift
File "pycbc/types/array.py", line 77, in _noreal
File "pycbc/types/frequencyseries.py", line 492, in cyclic_time_shift
File "pycbc/waveform/utils.py", line 410, in apply_fseries_time_shift
File "weave/inline_tools.py", line 366, in …
```

Invoke pycbc_inspiral with injections in the bundle build

---

pycbc/workflow/datafind.py

Since the current set of LIGO data find servers don't do this properly yet, PyCBC's datafind module needs to know if a URL that it gets is available at other (backup) locations. This implements two changes:
1. Only the regular LIGO frames are available for gsiftp from UNL and CIT, so force a match on `file:///cvmfs/oasis.opensciencegrid.org/ligo/frames` to add those backup URLs.
2. The LOSC frames in `file:///cvmfs/gwosc.osgstorage.org/` are available on the OSG, so if the URL matches, add them to the OSG site.

Tell PyCBC that LOSC frames are available on the OSG

---

bin/inference/pycbc_inference_plot_inj_recovery
bin/workflows/pycbc_make_inference_inj_workflow
pycbc/workflow/inference_followups.py

The changes in #2136 and #2154 means that PP plots will not work anymore since mass1 will not necessarily be >= mass2 in the samples files. In order to get sane plots, we need to be able to pass `primary_mass(mass1, mass2)` from the workflow config file to `inj_interval` and `inj_recovery`. This patch does that by adding a `pp-plot-parameters` option to `workflow-inference` section. In this section you specify what parameters to plot for the PP and recovery plots. (If nothing is provided, it defaults to the variable args.) An example:
```
[workflow-inference]                                                            
; how the workflow generator should setup inference nodes                       
num-injections = 100 …
```

Allow  conversions to be used in PP dax

---

bin/inference/pycbc_inference
pycbc/inference/burn_in.py

This changes the `n_acl` burn-in function to do the following:
1. Only the second half of the chain is used to compute ACL.
2. If the number of iterations in the second half is > `n_acl * ACL`, then the sampler is considered burned in at the half way point.
The default `n_acl` is set to 25. If 200 walkers are used, with a desired number of independent samples of 5000, then this means the job will complete as soon as this burn-in test passes. This method seems to work best for `ecmee_pt`.
The way the ACL is computed is not changed. This PR supersedes #2169, which did something similar, but also switched to using the mean of ACLs instead of the ACL of the mean chain. Calculating ACL that way does not seem to work with `emcee_pt`, as the ACL was severely underestimated.
This also causes …

Updates to n acl burn-in

---

pycbc/inference/option_utils.py

This makes specifying labels for plots on the command line easier. If the parameter is one of the ones in `waveform.parameters`, you can just give that parameter name and you will get the label associated with it. For example,
before:
`--parameters 'mchirp_from_mass1_mass2(mass1, mass2):$\mathcal{M}$'`
now:
`--parameters 'mchirp_from_mass1_mass2(mass1, mass2):mchirp`.

Try to get labels from waveform.parameters

---

pycbc/io/inference_hdf.py

If the `acl-interval` argument introduced in PR #2174 is set to something other than the checkpoint-interval on a new run, a KeyError will be raised. This is because when the code checks for the number of independent samples, it tries to access the `is_burned_in` and `burn_in_iteration` attrs in `InferenceFile`, but these will not have been set yet. This fixes this by returning False if `is_burned_in` yet has not been set, and the number of iterations in the file if `burn_in_iteration` has not been set.

Fix for acl-interval argument

---

bin/inference/pycbc_inference
bin/pycbc_create_injections
pycbc/distributions/__init__.py
test/test_distributions.py

This makes the sections to read the variable parameters, static parameters, and constraints keyword arguments in `distributions.read_args_from_config`. The defaults are what we currently use (`variable_args`, `static_args`, and `constraint`). Since these section names can now be specified explicitly, this also gets rid of the `section_group` argument.

Make section names for distributions keyword args

---

bin/pycbc_create_injections

Makes use of PR #2239. Also fixes a documentation mismatch in `pycbc_create_injections`: the help message and `--dist-section` say that it looks in `distribution-{}` sections to set up the pdfs. But because the `dist_section` argument wasn't being passed to the read from config function, it was actually looking in `prior-{}` (the default in the distributions module).

Create injections: Allow sections to read parameters be set on command line

---

bin/hdfcoinc/pycbc_coinc_findtrigs

I've been struggling to push runs through on CIT for a few days (maybe some config change there)
The problem seems to be the following line. Without this change I see "Permission Denied" errors because the file cannot be opened with write permissions on multiple processes. Not really sure why we never saw this before.
Patch is simple and seems to fix the problem.

Don't open bank file for writing

---

pycbc/frame/frame.py

This is a quality of life update for pycbc live. One issue I've found is that it tried to read *all* the frame files in the frame-src to get their metadata information. However, if a file is gone before it can do so, it will fail. This can create a problem when trying to initially start up the analysis and a random node will drag behind and kill the entire analysis.

allow pycbc live to resolve only the latest frames

---

pycbc/scheme.py
pycbc/waveform/waveform.py
pycbc/weave.py
setup.py

This disables weave when in a python3 environment. Many things will be broken, but it allows *something* to run in python 3. Waveform generation, for example, *does* work with this patch.

allow pycbc to be installed in python3

---

bin/pycbc_optimal_snr

A simple attempt at addressing #2222. Feel free to post suggestions if this is not sufficient.
I also add an option to show a nice progress bar with ETA, which works even when using multiple cores. I am not sure how useful this is on a remote node, but I suspect it works when the log is watched using `tail -f`. At least one can still see the ETA.

optimal_snr: add verbosity for debugging bad approximants

---

pycbc/workflow/datafind.py

This commit adds URLs on `https://losc.ligo.org` as back-up URLs for the LOSC CVMFS frame data. Similar to the code above for the regular LIGO data, this should really be handled at the datafind server level, but we keep patching here for now.

Add LOSC https urls as fallback

---

bin/inference/pycbc_inference
pycbc/distributions/__init__.py
pycbc/distributions/constraints.py

This fixes `read_constraints_from_config` by removing `variable_args` from the required init parameters for constraints. The variable args were used for figuring out what transforms to apply. Instead, a `transforms` keyword may now be provided which gives the list of transforms to apply explicitly. In `pycbc_inference`, the combination of the sampling and waveform transforms are given as this keyword.

Make transforms a kwarg to custom constraints

---

pycbc/psd/analytical.py

This is a very trivial change that fixes the issue with the dictionary key sorting in line 70 of `analytical.py`. The original line is still in comment. This still does not fix the psd generation in Python3.6. I will open an issue with the other errors

Trivial change fixing dictionary key sorting in analytical.py

---

pycbc/fft/core.py
pycbc/types/aligned.py

This allows the fft related unit tests to run under python3. I've checked only that they work on a machine with fftw installed.

fixes to make test fftw unthreaded work in python3

---

pycbc/filter/qtransform.py

Occurred due to numpy doing a manual index of array.

fix performance regression in qtransform

---

bin/inference/pycbc_inference
pycbc/inference/likelihood.py
pycbc/inference/option_utils.py
test/test_inference.py

This PR adds the ability to read in different low-frequency cutoffs for every detector to pycbc inference. So one can provide for eg. : `--low-frequency-cutoff H1:20 L1:25` in the CLI. If a single low-frequency cutoff is provided, for eg. : `--low-frequency-cutoff 20`, that'll be used for all the detectors.

Add low-frequency cutoff option for every detector

---

bin/pycbc_losc_segment_query
tools/docker_build_dist.sh
tools/test_coinc_search_workflow.sh

Currently the Travis workflow test needs a LIGO proxy and ECP cookie to generate the test workflow, so it is only tested if the secure environment variables are available.
The changes the code to get segments from LOSC and frame PFNs from the open server on sugwg-condor, so LIGO credentials are no longer needed to test the workflow.

Use data from LOSC to check the workflow

---

docs/detector.rst
docs/index.rst
examples/detector/ant.py
examples/detector/delay.py
examples/detector/loc.py
examples/detector/travel.py
pycbc/__init__.py
pycbc/detector.py
requirements.txt
test/test_detector.py
tools/einsteinathome/pycbc_build_eah.sh

* Make several methods more pythonic and allow vector input
* Switch to python for several methods and rely on astropy for more accurate sidereal time
* Add unit tests for the detector module
* Add examples and associated docs
Note, that the injection path is not changed and will still call into lal functions for now. The antenna pattern functions will agree to some precision to the lal ones, but should be more accurate as the sidereal time calculation is less of an approximation when using astropy vs lalsuite.

improve detector module

---

pycbc/scheme.py

@soumide1102 This was the source of the 'array_mkl' print statements you were seeing. Sorry, this was a holdover debug statement. This patch removes that message.

remove debug print statement

---

docs/install.rst

https://github.com/gwastro/pycbc/pull/2259/commits/c421b023e9449db8efebf35d3549f41c743bf6b0 accidentally removed a "pip install" from the installation instructions.

Updated install.rst

---

pycbc/conversions.py

The function I used `return_base_10`, can be done via `log10(param)`. Simpler code which reverts https://github.com/gwastro/pycbc/pull/2285

Remove return_base_10

---

pycbc/conversions.py
pycbc/distributions/spins.py

This switches to using `numpy.broadcast_arrays` in `ensurearray`. That function both ensures that the inputs are arrays, and broadcasts all of them to have the same shape. As a result, `ensurearray` now can take multiple arguments at once. This simplifies calling, and removes the need to check for shapes.
This also makes all of the functions have more of a standard IO. Previously you'd have to make sure all arguments had the same shape for functions that used `ensurearray`, whereas other functions that did not could take a mixture of arrays and floats (as they would default to the using numpy's broadcasting rules). For example, `conversions.chi_eff(10., numpy.array([5., 10.]), 0.5, 0.5)` would work, but `conversions.chi_p(10., numpy.array([5., 10.]), 0.5, 0.5, 0.5, 0.5)` would raise an …

Make ensurearray more numpy like

---

pycbc/io/hdf.py

When reading, filtering and clustering merged single-detector triggers using SingleDetTriggers, I noticed very large memory usages which occasionally lead to MemoryErrors from `numpy.in1d`, even on machines with several tens of gigabytes of memory. This change appears to eliminate the error, although I have not made precise measurements of before/after memory usage. It also simplifies the code a bit and possibly makes it slightly faster, since `in1d` seems to sort the array, which is not necessary in this case.

Avoid MemoryErrors in SingleDetTriggers

---

bin/pycbc_live
pycbc/events/coinc.py
pycbc/fft/fftw.py

This requires #2292. 
Add a fix for the resize issue in #2253 
- add option to make it easier to debug / make plans for pycbc live. I.E.
- option to set fftw planning limit
- option to simulate run configuration on 2 nodes (i.e. master + one of the computes)

resize fix for pycbc live, some additional debug options

---

bin/pycbc_optimal_snr

Hopefully this will help clarifying what is happening in cases like #2294.

pycbc_optimal_snr: be more explicit on waveform failures

---

bin/pycbc_single_template
pycbc/waveform/waveform.py

We're currently seeing an issue where `pycbc_single_template` will fail when running with "injection as filter mode" and when the injection is longer than the filter length. Not sure what broke this, as we've definitely run in this configuration before. However, probably this was doing something silly before. This patch does two things:
* Raise an error in `td_waveform_to_fd_waveform` if the input TD waveform is longer than the filter length specified either with an output memory array of with an explicit length (without kwargs, the length is determined internally).
* Cut the injection in `pycbc_single_template` if running with this option so that the jobs can succeed.

Fix issue where injection is longer than filter length

---

bin/pycbc_single_template
pycbc/waveform/waveform.py
setup.py

Cherry-picks Ian's patch in #2302 to fix problems when the injection is longer than the filter length, and bumps version number on `v11_release_branch` in preparation for a new release with this fix.
I've tested this patch on one of the `pycbc_single_template` jobs that was failing in my current run under PyCBC v1.11.8, and it resolved the issue there.

Long injection patch

---

bin/inference/pycbc_inference

If we use `all_transforms = sampling_transforms`, that leads to `sampling_transforms` becoming `all_transforms` which includes the `sampling_transforms` + `waveform_transforms`. These waveform_transforms included in sampling_transforms then want to behave like sampling_transforms making the code to fail.

Prevent sampling_transforms from becoming all_transforms

---

pycbc/conversions.py
pycbc/distributions/__init__.py
pycbc/distributions/qnm.py
pycbc/waveform/ringdown.py
test/test_distributions.py

This adds final mass and spin from `f0`, `tau` functions to conversions. These functions use the Berti et al. fits. Currently, only support for l = m = 2 is provided.
A `qnm` module is also added to `distributions`, which includes a `UniformF0Tau` distribution. This distribution allows for constraints on final mass and spin to be provided.
Both of these are largely copied from @micamu area theorem branch.
Note: strictly speaking, the `UniformF0Tau` distribution isn't needed, since the same thing could be accomplished by providing a `Uniform` distribution (for f0 and tau) along with constraints (for final mass and spin) to the `JointDistribution`. That's a bit complicated though. `UnformF0Tau` is a convenience class, similar to `UniformSky`.

Some ringdown updates

---

pycbc/inject/inject.py
pycbc/waveform/parameters.py
pycbc/waveform/waveform.py

When loading an injection hdf file any static arguments stored in the hdf file's `.attrs` are expanded to an array using `numpy.repeat` and added as another field to `InjectionSet`'s `table`. This is problematic if the static argument is an array, list or tuple, as it would be for `mode_array`. In that case, the repeat ends up given a flattened array of integers, which is not what you want. For example, if a file had 8 injections in it and `mode_array = [(2, 2), (2, 1)]`, you end up with:
```
>>> ninj = 8
>>> mode_array = [(2,2), (2,1)]
>>> arr = numpy.repeat(mode_array, ninj)
>>> arr
array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
2, 2, 1, 1, 1, 1, 1, 1, 1, 1])
>>> table = WaveformArray.from_kwargs(mode_array=arr)
>>> table[0].mode_array
2
```
This patch fixes …

Allow mode array support in injection hdf files and fix bug with current implementation

---

pycbc/inference/option_utils.py
pycbc/inference/sampler_emcee.py
test/test_inference.py

This PR gives `pycbc_inference` the ability to read beta values from an external hdf file which stores them in its attrs `betas`. The file is read in using the argument `--inverse-temperatures-input-file`. Either the `--inverse-temperatures-input-file` or `--ntemps` will work, but not both. So this does not take away anything from how it works now. 
If `--ntemps` is provided, pycbc_inference will let `emcee` calculate the betas like it does now.
If `--inverse-temperatures-input-file` is provided, the `betas` will be read in from this file.

Add ability to read beta values in emcee_pt from external file

---

bin/hdfcoinc/pycbc_plot_range
bin/hdfcoinc/pycbc_plot_range_vs_mtot

This one should be pretty simple.
Matplotlib has now made it a failure if `fmt=None` is sent to the `plt.errorbar` function. This should now be `fmt='none'`. This has been deprecation warning since matplotlib 1.4, and we've been ignoring it. The fix is trivial and tested.

Fix a deprecation issue in matplotlib

---

Dockerfile

This changes the docker image to use the 89a30fc lalsuite tag (it has been stuck at an old tag for a while) and changes the pycbc home directory to `/opt/pycbc` so the docker image can be converted to singularity.

update to lalsuite 89a30fc and change base directory

---

pycbc/waveform/waveform.py

This PR removes a reference to the old waveform interface that isn't used anymore.
It should not effect anything.
Could keeping the `SimInspiralCreateWaveformFlags` cause a memory leak? Not sure :)

update waveform.py: remove old ref to flags

---

pycbc/psd/__init__.py
pycbc/psd/read.py

This one has been on the to-do list for a while: We should support XML input files in the XML `from_cli` function.
While PyCBC may be moving away from XML files, these are still used extensively elsewhere, including in template bank generation codes (sbank and Soumen's new code). So we need to be able to read these files in.
This patch does that without touching any other functionality. (A little bit of moving code around in `read.py` to avoid code duplication and to make it easier to add other `from_XXX` formats).

Support XML PSD files

---

pycbc/workflow/core.py

Allow file_input_options in workflow.core to use list of input files. The specific use case that brought this about is `pycbc_create_injections`, which might want to take a list of config files as input. @Cyberface will test this.

Allow file_input_options to take lists of files

---

bin/inference/pycbc_inference_plot_acceptance_rate
pycbc/inference/io/emcee.py
pycbc/inference/io/emcee_pt.py

Fixes histogram normalizing bug, puts necessary `numpy` imports in emcee and emcee_pt.
Using this ini file:
```
[model]
name = test_normal
[sampler]
name = emcee_pt
ntemps = 3
nwalkers = 5000
niterations = 9
checkpoint-interval = 4
[variable_params]
x =
y =
[prior-x]
name = uniform
min-x = -10
max-x = 10
[prior-y]
name = uniform
min-y = -10
max-y = 10
```
and this run script:
```
#! /usr/bin
pycbc_inference \
--verbose \
--config-files 2d_gauss.ini \
--output-file 2d_gauss.hdf \
--nprocesses 4 \
--force
```
and this is what comes out from:
```
$ pycbc_inference_plot_acceptance_rate --input-file 2d_gauss.hdf --output-file ~/secure_html/astro/check_pe/plot_accept_rate_gauss_2d_examp.png
```

Fix histogram bug and update for new versions of pycbc inference in pycbc_plot_acceptance_rate

---

bin/inference/pycbc_inference_plot_samples

Changing a few things around, and plotting the samples from gaussian example (x, y)
A future commit will reduce the number of time spend importing samples. It should just read all the samples and slice along the axis of walker. This should greatly reduce the time required to plot these samples.

Pycbc plot samples fix

---

bin/inference/pycbc_inference_plot_inj_intervals

Fixed the import and functions in injection interval plots. I plotted following plot from 2 test injections and runs:
pycbc_inference_plot_inj_intervals --input-file run_files/inference1.hdf:1 run_files/inference2.hdf:2 --output-file test.png --parameters mass1 mass2

Update plot_inj_interval for fix imports for io mv

---

.codeclimate.yml

At the moment this plugin is failing and I don't know why. I've opened an issue:
https://github.com/meuspedidos/codeclimate-pylint/issues/24
but for now we might have to disable this plugin.

Temporarily disable pylint in codeclimate

---

pycbc/conversions.py

This patch fixes a bug in `pycbc.conversions.lambda_tilde` where calling the function with integer or float values for `lambda1` and `lambda2` would return a TypeError:
```
In [1]: from pycbc.conversions import lambda_tilde
In [2]: lambda_tilde(1.4, 1.4, 500., 500.)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-284d36db949b> in <module>()
----> 1 lambda_tilde(1.4, 1.4, 500., 500.)
/home/daniel.finstad/src/pycbc/pycbc/conversions.py in lambda_tilde(mass1, mass2, lambda1, lambda2)
384     ldiff = lambda1 - lambda2
385     mask = m1 < m2
--> 386     ldiff[mask] = -ldiff[mask]
387     eta = eta_from_mass1_mass2(m1, m2)
388     p1 = (lsum) * (1 + 7. * eta - 31 * eta ** …
```

cast ldiff to array to avoid TypeError

---

pycbc/inference/option_utils.py

When using `pycbc_inference_plot_posterior` to plot from multiple files without providing the `--parameters` command-line argument, the plotting parameters default to being stored as a list of arrays. Then the line
```
parameters = parameters if isinstance(parameters[0], list) else [parameters]
```
wraps the parameters in another list, causing the following code block to fail with an 'unhashable type' error:
```
for p in parameters[0]:
if p not in mins:
mins[p] = numpy.array([s[p].min() for s in samples]).min()
if p not in maxs:
maxs[p] = numpy.array([s[p].max() for s in samples]).max()
```
This patch changes the default behavior to storing each file's plotting parameters as a list when `--parameters` is not provided.

Ensure plot parameters are stored as a list when --parameters argument is not provided

---

bin/inference/pycbc_inference_plot_inj_intervals
bin/inference/pycbc_inference_plot_inj_recovery

Fixed the import and functions in injection recovery plots. I plotted following plot from 2 test injections and runs:
>> pycbc_inference_plot_inj_recovery --input-file run_files/inference1.hdf:1 run_files/inference2.hdf:2 --parameters mass1 --output-file test2.png

Inference dev

---

bin/pycbc_inspiral
pycbc/events/events.py

@josh-willis This reduces the overhead a bit of using concatenate repeatedly. I think you had pointed this out before, but I've run into a corner case where this becomes problematic. Please find a patch attached. I've also taken the liberty of removing some only partially working code.

remove cruft, lower overhead of event manager

---

docs/_include/inference_io_inheritance_diagrams.py
docs/_include/sampler_inheritance_diagrams.py
docs/conf_std.py
docs/inference.rst
docs/inference/io.rst
docs/inference/sampler_api.rst
pycbc/inference/io/base_mcmc.py
pycbc/inference/io/base_multitemper.py
pycbc/inference/sampler/base.py
pycbc/inference/sampler/base_mcmc.py

Adds a page for the sampler classes and a page for the new IO classes. These are linked from the main inference help page, under a new section "For Developers".  Example is here:
[Sampler API](https://www.atlas.aei.uni-hannover.de/~cdcapano/public_scratch/github_prs/inference_dev-test_docs/html/inference/sampler_api.html)
[Inference IO](https://www.atlas.aei.uni-hannover.de/~cdcapano/public_scratch/github_prs/inference_dev-test_docs/html/inference/io.html)
@cmbiwer @soumide1102 Is this what you were thinking of?

Add documentation for developers about the new sampler API

---

.codeclimate.yml
pycbc/events/events.py
pycbc/fft/backend_support.py
pycbc/filter/matchedfilter.py
pycbc/types/array.py
pycbc/vetoes/chisq.py
pycbc/waveform/spa_tmplt.py

The error in pylint was, I think, tracked down to issues with some of the schemed function stubs (especially class initializations not actually returning classes).
Here I reenable pylint and make all the stubs raise errors if actually called.

Reenable pylint (hopefully)

---

bin/inference/pycbc_inference_plot_acf
pycbc/inference/io/base_mcmc.py
pycbc/inference/io/base_multitemper.py
pycbc/inference/io/emcee.py
pycbc/inference/io/emcee_pt.py
pycbc/inference/sampler/base_mcmc.py

Splits `MCMCIO` into `MCMCMetadataIO` and `SingleTempMCMCIO`. The latter only contains `read_raw_samples` and `write_samples`. Likewise, splits `MultiTemperMCMCIO` into `MultiTemperMCMCIO` and `MultiTemperMetdataIO`; the latter inherits from `MCMCMetadataIO`. This fixes the need to override `read_raw_samples` and `write_samples` for multi-tempered samplers, which also avoids changing the function signature.
Also fixes an issue in `pycbc_inference_plot_acf` that prevented it from working with both single temperature and multi-temperature samplers, which I came across while testing.

Separate MCMCIO classes into MetadataIO and samples IO

---

pycbc/distributions/arbitrary.py

Sometimes the Scott Bandwidth which is the preset in scipy.stats gaussian_kde isn't exactly what you want to use. This lets the user pre-set a bandwidth from file or change the bandwidth themselves.
example script:
```
import h5py
import numpy
from pycbc.distributions import Arbitrary
from pycbc.distributions import FromFile
f_h5_addr ="your_file.hdf"
f = h5py.File(f_h5_addr, "r")
x = FromFile(filename=f_h5_addr)
num_samples = len(f["mass1"][:])
scott_samples = x.rvs(num_samples)
bins = numpy.linspace(1.0, 2.0, 51, endpoint=True)
plt.hist(scott_samples["mass1"], bins=bins, histtype="step",
label="(Default) Scott Bandwidth", normed=True)
x.set_bandwidth(0.001)
small_bw_samples = x.rvs(num_samples)
plt.hist(small_bw_samples["mass1"], bins=bins, …
```

Allow changes to bandwidth for KDE from file

---

pycbc/transforms.py

This patch adds an explicit transform between component masses and mchirp, eta, allowing sampling in these parameters.

add explicit transforms between mass1, mass2 and mchirp, eta

---

examples/inference/bbh-injection/make_injection.sh

I noticed the `make_injection.sh` script in the BBH example points to the wrong configuration file. It should point to `injection.ini`, not `inference.ini`.

Point to the right ini file in BBH example

---

pycbc/cosmology.py

Uses `astropy.cosmology` in the cosmology module. Currently, only a `distance_from_comoving_volume` function is added (which will allow for injections uniform in comoving volume), but more can be added later.
Here is a plot showing the luminosity distance returned by the function vs comoving volume: [link](https://www.atlas.aei.uni-hannover.de/~cdcapano/public_scratch/github_prs/use_astropy_cosmology/dist-comoving_volume.png)
This patch also replaces the current `redshift` function with equivalent function from `astropy`. Here is a plot comparing the redshift as a function of luminosity distance between the current redshift function and the new one: [link](https://www.atlas.aei.uni-hannover.de/~cdcapano/public_scratch/github_prs/use_astropy_cosmology/redshift_compare.png). Results are …

Use astropy.cosmology in the cosmology module

---

bin/inference/pycbc_inference_plot_posterior

The inference dev branch introduced a bug into the input file labeling. This fixes that.
File labels are now automatically parsed from`--input-file file[:label]` and stored to `opts.input_file_labels` as a `file name -> file label` dict. The part where the legend is created is treating this as a list though, which results in the keys (the filenames) being used. Worse yet, because order isn't preserved in a dictionary, the colors and names could get swapped. This fixes that, ensuring order is preserved.

Fix bug in posterior file labelling

---

bin/minifollowups/pycbc_foreground_minifollowup
bin/minifollowups/pycbc_injection_minifollowup
bin/minifollowups/pycbc_sngl_minifollowup
bin/workflows/pycbc_make_inference_workflow
pycbc/workflow/core.py
pycbc/workflow/inference_followups.py
pycbc/workflow/minifollowups.py
pycbc/workflow/pegasus_files/orangegrid-site-template.xml
pycbc/workflow/pegasus_workflow.py

This pull request adds support for singularity containers in PyCBC workflows. It changes `pycbc/workflow` to use text-based transformation catalogs written using the [new python api](https://pegasus.isi.edu/docs/4.9.0dev/python/transformation_catalog.html), rather than putting the transformation catalog information in the DAX, since the XML-based transformation catalog code doesn't support the [Container](https://pegasus.isi.edu/docs/4.9.0dev/python/index.html#Container) class.
With that fix, it adds support for setting up Pegasus jobs to run in singularity containers with the following config overrides:
1.  `"pegasus_container-inspiral:type:singularity"` tells PyCBC to use [singularity](https://www.sylabs.io/docs/) containers for the `inspiral` jobs.
2. …

Add support for singularity containers in workflows

---

pycbc/workflow/core.py
pycbc/workflow/minifollowups.py

In order for the jobs in a minifollowup workflow to run from a container on OSGConnect, the staging sit must be passed to pegasus when it plans the minifollowup DAX.

Enable staging site for minifollowups

---

pycbc/events/events.py

@tdent I think the bug you ran into can be avoided by simply priming the list with an empty array.

prime the pump

---

pycbc/workflow/pegasus_files/pegasus-properties.conf

AMQP reporting requires python package amqplib to be installed.
if not installed and enabled, then it can break monitord population to sqlite backend.
this is now fixed in pegasus 4.9.1dev also
https://jira.isi.edu/browse/PM-1333
Additionally, the 4.9.1dev RPM's do have python-amqplib listed as a dependency.
If not installing from RPM, then please install amqplib via pip

turn on reporting of integrity error and other performance data

---

bin/pycbc_losc_segment_query

This fixed the problems with the script to fetch segments from LOSC. This code is a stopgap until https://github.com/gwastro/pycbc/pull/2310 is merged.
The code now downloads each NOT segment (CAT1, CAT2, and HWINJ) from LOSC, inverts the segment list, and taked the intersection with science mode. This means that only the CAT1, CAT2, and HWINJ segments that occur in science mode are written. Note that LOSC defines science mode (DATA) as (SCIENCE - CAT1) so the CAT1 list is always empty.

Reworked losc segment query tool

---

bin/hdfcoinc/pycbc_fit_sngls_binned
bin/hdfcoinc/pycbc_fit_sngls_by_template
bin/plotting/pycbc_plot_trigrate
pycbc/events/stat.py
pycbc/io/hdf.py

At the moment if one wants to try a new detection statistic they edit the `stat` module, but then they have to edit a bunch of different codes to allow that statistic to be used in the single-detector applications (minifollowups, plots, the fitting codes, ...). This can be a little frustrating.
As such I want to move all of this into the stat module. Of course the single-detector statistics are different from the multi-detector ones, but in most cases calling the "single" method of the Stat class gets what we want.
This patch implements the functionality where a "single-detector-statistic" dict is defined in the stat module, and this is inherited everywhere else. We might envisage Stat classes that might *only* have single methods, and only be valid for single-detector statistics, but for …

Rework single-detector stat

---

pycbc/inference/models/base.py
pycbc/inference/models/marginalized_gaussian_noise.py

Currently, Gaussian noise model does not load sampling transforms from the config file. This is a bug. This patch fixes this by moving the code that loads the sampling transforms into `_init_args_from_config`.
The marginalized Gaussian noise model was loading sampling transforms in its `from_config`. Since this is now done in `init_args_from_config`, I've removed that block of code from it.

Add sampling transforms back to Gaussian noise model 

---

pycbc/fft/mkl.py

This PR should fix #2202 . The problem was that the "descriptor" used by MKL's FFT was erroneously being passed by value to the destructor when it should have been passed by reference in the ctypes wrapping. This is now fixed for the function API; the class-based API has never attempted to free the descriptor (that would require a `__del__` method for the classes).

Pass MKL DFT descriptor by reference to desctructor

---

test/test_conversions.py

Working on adding a test to compare the chi_p function in pycbc with the lalsuite one.
I don't think I've implemented the test correctly but it's a start.

WIP: add chip test. compare to lal

---

examples/waveform/match_waveform.py
pycbc/filter/autocorrelation.py
pycbc/filter/matchedfilter.py
pycbc/filter/matchedfilter_cpu.pyx
setup.py
test/test_correlate.py
tools/install_travis.sh
tools/timing/correlate_perf.py

This moves the correlate functions to use cython. It uses the simplest implementations for this initial version. I'm sure @josh-willis may want to re-enable some optimizations later one, but for now, I'm advocating getting to python3 compatibility first. 
* Adds unittest for the Correlator and BatchBorrelator
* Adds performance testing script for correlation functions (can be run on older pycbc as well for later regression comparison)
This enables functionality like match and matched_filter now work in some simple cases on python3.

move correlate functions to cython

---

bin/inference/pycbc_inference
pycbc/inference/models/base.py
pycbc/inference/models/base_data.py
pycbc/inference/models/gaussian_noise.py

This moves stuff about waveform generation out of `BaseDataModel`. Now `BaseDataModel` only introduces attributes for data, and the concepts of log likelihood ratio and log likelihood noise. This should make it easier inheriting for things like the ROQ model.
Setting up the waveform generator is now moved to within `GaussianNoise.__init__`, with the actual generator setup farmed out to stand alone functions. This means that `GaussianNoise` no longer takes the generator as input, but instead uses the other inputs (which provide enough information) it already needed to set up the generator. This makes it simpler to initialize `GaussianNoise`.
Finally, I moved the stuff about loading low frequency cutoff from the config file that Stephan added to a stand alone function, which is now called …

Move waveform dependence out of BaseDataModel

---

bin/hdfcoinc/pycbc_get_loudest_params
bin/population/pycbc_population_plots
bin/population/pycbc_population_rates

This PR removes some unused/unnecessary imports of `matplotlib.pyplot` in the scripts, which can cause issues where `DISPLAY` is not set, etc etc.

Removed unused imports of matplotlib.pyplot

---

test/test_waveform_utils.py

Does what it says. A sine wave is shifted by +/- pi/2 in the frequency domain, then transformed back to the time domain and compared to a cosine. Next, a shift by a non-integer step of the delta t is done and compared to just calling `sin()` on the time stamps shifted by the same amount.
Both the C code and the numpy code are tested.

Add unit test for apply_fd_time_shift

---

examples/gw150914/gw150914_shape.py

Currently, the example "Plotting the whitened strain" for GW150914 in the documentation shows a plot that just looks as a zero line (with a small wiggle if someone is paying close attention):
https://pycbc.org/pycbc/latest/html/gw150914.html#plotting-the-whitened-strain
This PR just changes the y-limits to make the waveform nicely visible.

Make waveform visible in documentation

---

pycbc/strain/lines.py

First steps to incorporate a module that removes frequency lines from the data without using any auxiliary channels. For now, the functions take a list of frequencies and, for each frequency, take the inner product of the data with a line model  to obtain the amplitude and phase of the line. This is done taking the median over several time segments, to remove outliers that could originate from the presence of a signal.
The procedure works very nicely for calibration lines, which are stable and whose frequencies are well known. For other lines, which are time varying, the functions take also chunks of data and calculate the inner product in each chunk separately. Those lines do not get completely removed, but at least they reduced a few orders of magnitude. See for instance: …

Removing frequency lines

---

pycbc/transforms.py

Add one line in get_common_cbc_transforms in transforms.py : 
Before adding a transform from the base parameters to the requested parameters for automatic transformation, check if the intersection between requested parameters and the output of the transforms is already in the sampled parameters. If that is the case, we should not possibly gain anything useful from applying the transform, so this transform should not be added. 
Additionally, adding these transforms can lead to errors when plotting: If we request a parameter that is sampled in, for example q, and there is a transform that outputs this parameters AND another one, i.e. MChirp, which doesn't have q as an input parameter, than this transform will be added to the transforms that should be applied. Continuing the example, …

Remove unnecessary and impossible automatic transforms 

---

pycbc/conversions.py

This fixes the issue in https://github.com/gwastro/pycbc/issues/2247 where integer masses were causing the wrong value of chi_p to be calculated.
Below is an example of integer masses that gives the expected chi_p result.
```
In [1]: from pycbc.conversions import chi_p
...:
...: # primary black hole parameters
...: m_primary = 10
...: sx_p,sy_p = 0.1, 0.
...:
...: # seondary black hole parameters
...: m_secondary = 3
...: sx_s,sy_s = 0.5, 0.
...:
...: print(chi_p(m_secondary, m_primary, sx_s, sy_s, sx_p, sy_p))
...:
0.128571428571
```

add from future division

---

pycbc/inference/models/__init__.py
pycbc/inference/models/analytic.py

This adds the analytic zero-likelihood model, whose `loglikelihood` method just returns the `logprior`.

Add zero likelihood analytic model

---

pycbc/types/array.py

For a pycbc.types.timeseries.TimeSeries the prepend_zeros function can be called with negative arguments removeing samples in the front. If this number was larger than half the length of the TimeSeries the roll funtion would crash. This was caused by the roll function which would try to access negative array indices.
To fix this the function now adds n * len(array) to the shift, where n is the smallest (integer) value such that the shift is positive afterwards.
The check for a shift of 0 hence is now performed afterwards.

Fixed a bug in the roll function for time series.

---

bin/hwinj/pycbc_generate_hwinj_from_xml

Moved detector selection into a command line argument so that `--ifos H1 L1 V1` can be invoked rather than a hard-coded list. Tested using an injection XML.

Made hardware injections accept flexible list of detectors

---

pycbc/psd/estimate.py

This PR fixes a few issues in `pycbc.psd.estimate` to make it (the `welch` function) work under python3. Two categories of change:
- use `int` arguments when creating arrays of fixed size
- use `six.moves.range` instead of `xrange`

Minor updates to pycbc.psd.estimate for python3

---

pycbc/noise/gaussian.py
pycbc/waveform/utils.py

This PR just (similarly to #2507) just fixes some divisions to make sure they produce integers when the output values are being used as array indices.

Some Python 3 compatibility fixes

---

pycbc/waveform/waveform.py

Allows PhenomD_NRTidal and PhenomPv2_NRTidal
to be used with get_td_wavefrom and get_td_wavefrom_from_fd
PhenomPv2_NRTidal is now on the master branch of lalsuite too.

add time estimates for NRTidal

---

requirements.txt

The matplotlib version is quite old, which can cause problems when using the CVMFS build.

Bump matplotlib version to 2.0.0

---

pycbc/psd/estimate.py

I've fixed a few more Python 3 compatibility issues (see also #2508) to do with divisions in `estimate.py`.

A few more Python 3 compatibility int division fixes

---

pycbc/inference/io/posterior.py

The `read_raw_samples` function in the posterior module ignores the option "fields", so that it is reading samples for all parameters independently if how the function is called.
With this PR, it will read only samples for the parameters specified in "fields"

Inference: do not ignore option "fields" in posterior

---

bin/hdfcoinc/pycbc_coinc_hdfinjfind
bin/hdfcoinc/pycbc_fit_sngls_by_template

hdf injfind code altered to allow for multiifo-style input. The way to differentiate between original-style and multi-ifo-style input is in the input hdf file
Difference in output:
- `optimal_snr_N` where `N` is 1 or 2 becomes `optimal_snr_I1` for `I1` as detector Identifier
- `found/timeN` --> `found/I1/time`, similarly for `trigger_id` instead of `time` and `found_after_vetoes` instead of `found`
Note that some file-reading parts may change depending on throughput options chosen earlier in the pipeline

Multiifo hdf injfind

---

docs/inference.rst
examples/inference/bbh-injection/inference.ini
examples/inference/gw150914/inference.ini
pycbc/inference/burn_in.py
pycbc/inference/io/__init__.py
pycbc/inference/io/base_hdf.py
pycbc/inference/io/base_mcmc.py
pycbc/inference/io/base_multitemper.py
pycbc/inference/sampler/base.py
pycbc/inference/sampler/base_mcmc.py
pycbc/inference/sampler/emcee.py
pycbc/inference/sampler/emcee_pt.py

This introduces the ability to thin inference samples before writing to disk (for MCMC samplers), which should substantially cut down on checkpoint file sizes.
Two options for thinning are provided, which are set in the sampler section of the config file. You can either:
* Set `thin-interval` In that case, samples will be thinned by the given interval before being written to disk on each checkpoint. File sizes will still grow unbounded, but at a slower rate.
* Set `max-samples-per-chain`. In that case, the maximum number of samples that will be stored per walker and per temperature will be capped at the given value by increasing the thinning interval as the run goes on. This caps the file size to ~ `ntemps x nwalkers x nparameters x max-samples-per-chain x 8` bytes.
For …

Thin inference samples on the fly

---

bin/pycbc_live
pycbc/events/coinc.py
pycbc/filter/matchedfilter.py
pycbc/strain/strain.py
pycbc/types/timeseries.py
pycbc/waveform/bank.py

This adds multi ifo support to pycbc live. 
* Supports arbitrary number of detectors for outputting triggers
* All ifos contribute to significance of detectors
* No SNR threshold for all but the two ifos
The basic features are all there, so please review. 
[WIP]
* formatting / pep8 / some documentation.
Notes:
This removes the "followup" detector options. No detectors can just be followup at the moment, they will always contribute to significance and will have single triggers generated. We may want to add options to ignore some ifos for some purposes, but we can add that in a future patch.

add multi ifo support to pycbc live

---

bin/hdfcoinc/pycbc_page_foundmissed

needs extra input of --ifos to determine the multi-ifo nature of the input file
Adding ability to deal with hdf_injfind output as updated in #2499 
Note that decisive_distance and dec_chirp_distance are no longer sensible things to plot, so are ignored in the multi-ifo case

adding multi-ifo functionality to foundmissed plotting script

---

pycbc/inference/burn_in.py

Currently, the `nacl` burn in test will save the ACL it gets to the sampler's ACL, so that the sampler doesn't try to recalculate it. This was done as a time saving measure; it's fine if `nacl` is the only test being used. However, if multiple tests are being used -- e.g., `nacl & max_posterior` -- and the other test results in a burn in iteration after the `nacl` then the ACL saved will be wrong.
This patch fixes that by turning off saving the ACL in the `nacl` test if more than one burn in is specified. This will result in calculating the ACL twice on each checkpoint, but the thinning patch has made this a faster calculation anyway.

Only use ACL from nacl test if it is the only test being done

---

pycbc/inference/models/__init__.py
pycbc/inference/models/marginalized_gaussian_noise.py

This puts the `MarginalizedPhaseGaussianNoise` back into the models module, as it is currently broken in `MarginalizedGaussianNoise`. For now, I'll leave `MarginalizedGaussianNoise` in there. In retrospect, having Charlie stick all the possible marginalizations into a single class was a bad idea. The plan now is to slowly move out all of the different combinations of marginalizations (6) into their own classes. Once that is done, `MarginalizedGaussianNoise` should be removed.
This supercedes #2423.

Fix marginal phase

---

bin/inference/pycbc_inference

Currently, when you use MPI, all of the child processes print to screen before the pool is made, making for a bunch of repeated, confusing output. This shuts off logging for all child processes, so only the parent process prints.

Only allow master process to print to screen when using mpi

---

pycbc/inference/sampler/emcee_pt.py

EmceePT does not have blob data support. This means that the only statistics that you can retrieve from it are the log likelihood and the log prior. If sampling transforms are used, then the log prior is the log prior in the sampling coordinate frame rather than the variable parameter frame. Currently, the code tries to fix this by recalculating the log Jacobian and subtracting it from the log prior before returning model stats. Since this is only done on the parent process, this can make checkpointing take nearly as long as it takes to run the sampler. For example, in a run using 1000 walkers and 4 temperatures, calculating the log Jacobian for every point took up to 40 minutes, which doubled the wall clock time of the run.
This patch fixes this by turning off the log Jacobian …

Turnoff recalculating Jacobian in emcee pt

---

bin/hdfcoinc/pycbc_page_segtable

Making it so that H1 & L1 are not longer hardcoded, and that the table output now has all possible detector combinations

multi-ifo changes to pycbc_page_segtable

---

bin/hdfcoinc/pycbc_fit_sngls_by_template
bin/hdfcoinc/pycbc_fit_sngls_over_multiparam
bin/hdfcoinc/pycbc_fit_sngls_over_param

Adding `analysis_time` output to `fit_sngls_by_template`
This will be needed for calculation of the new multiiforanking statistic (noise rate for each template = number of triggers/analysis time)
The analysis time is calculated through the trigger file segments and vetos as used in the fitting already

fit_sngls_by_template analysis time output

---

bin/hdfcoinc/pycbc_plot_psd_file

This adds an `hdf-group` option to `plot_psd` to specify the group to look in for the PSD. This allows `plot_psd` to be run on inference hdf files, in which the psd is stored in the `data` group. If the `hdf-group` option isn't given, it will default to the top level group, as it does now.
This also makes it optional to plot a reference PSD. Right now, if you don't specify one of `psd-file`, `asd-file` or `psd-model`, you'll get an error.
Finally, I added a `low-frequency-cutoff` option so that this can be specified in case it isn't stored in the hdf file, as is (currently) the case for inference hdf files.

Allow psd group to be specified in plot_psd

---

bin/inference/pycbc_inference_plot_posterior

What the subject says. This way you can set the DPI to a lower value to reduce the file size when plotting a large number of parameters.

Allow plot posterior dpi to be set on command line

---

pycbc/results/scatter_histograms.py
pycbc/results/str_utils.py

Currently, the titles in `plot_posterior` force the quoted values to two decimal places in the uncertainty. This causes the precision of some poorly constrained parameters to be over quoted, while other well constrained parameters to be under quoted. For example, here is a plot of the [intrinsic](https://www.atlas.aei.uni-hannover.de/~work-cdcapano/scratch/quoted_intervals/orig_intrinsic_posterior.png) and [extrinsic](https://www.atlas.aei.uni-hannover.de/~work-cdcapano/scratch/quoted_intervals/orig_extrinsic_posterior.png) parameters of a BNS run. The chirp mass is quoted as '1.35 + 0.00 - 0.00' because the uncertainty is < 0.01, while effective spin is quoted as '-0.0874 + 0.1371 - 0.1251', which is ridiculous since the error is at the 100% level.
The `format_value` function can …

Use automatically determined number of sig. figs in posterior titles

---

bin/inference/pycbc_inference_plot_posterior
bin/inference/pycbc_inference_plot_prior
pycbc/inference/option_utils.py
pycbc/results/scatter_histograms.py

This adds the ability to plot the prior on the 1D marginal plots in `plot_posterior`. The prior is plotted as a dotted line (in black for single files; for multiple file inputs, the next color in the sequence is used). Examples can be seen in Figure 4 of https://arxiv.org/abs/1902.09496.
The prior is loaded from the config file. I moved the lines of code that do this in `plot_prior` to a function in `option_utils`, then have both `plot_posterior` and `plot_prior` call the same function.
This also fixes a couple of bugs I noticed:
1. The color of the confidence interval lines in the 1D marginal plots was being set to the contour colors. This meant that if you set the contour color to white (as you need to do when plotting density), the 1D marginal percentile lines wouldn't be visible.
2. …

Priors on 1D marginal posterior plots

---

bin/pycbc_live
pycbc/__init__.py
pycbc/events/coinc.py
pycbc/io/live.py
pycbc/workflow/core.py

* Save PyCBC version and command line into every output HDF file.
* Remove or clarify some log messages.
* Remove some unused code and options.
* Make `--enable-profiling` option more flexible.
* Add/fix CLI help.
* Record the number of live detectors into every output HDF file.
* ~~Record the command line arguments into the event XML files.~~ Multidetector arguments break LIGOLW :(
Should be merged after #2523 and after a quick test.

Improve PyCBC Live logging, help and metadata

---

bin/workflows/pycbc_create_offline_search_workflow
pycbc/workflow/coincidence.py

Implementing the combine statmap and injfind into the workflow

Implemetn combine statmap and injfind into wf

---

bin/pycbc_live

Change to a method which 1) uses a nominal livetime specified on the command line (eg 0.1yr) for p-value combination 2) does max ifar between the original and combined p-value and applies a trials factor of 2.  See https://github.com/gwastro/pycbc/wiki/pvalue-combining-tests for more detail

Change to p-value combination method for Live

---

bin/pycbc_ringinj
pycbc/waveform/ringdown.py

Currently the mass/spin ringdown approximant is a hybrid between a Kerr ringdown and an agnostic freq/tau damped sinusoid. It uses the NR formulae to map (mass,spin) -> (freq,tau), but it does not contain the M/d factor that appears in perturbation theory for a Kerr black hole. 
We did not introduce this before because it is just a constant factor, but it might easier to just include this factor when we want to understand how the SNR of the ringdown relates to the mass of the black hole and its distance. I have made the distance an optional argument, so if one does not give a distance the returned ringdown will be the same as before. I also noted in the documentation that when including this factor, the A_220 amplitude has a completely different order of magnitude (with a reference to a …

Add (optional) Kerr factor to ringdown mass/spin approximant

---

pycbc/workflow/core.py

PyGRB hit a problem. We use `file_input_options` to allow for common input files to be specified in the config files (as URLs or as paths). PyGRB uses the MultiDetector argument parsing, so might want to specify something like:
```
gating-file = H1:/path/to/file L1:https://URL/PATH/TO/FILE
```
That currently is not supported. To support it requires some of the same horribleness that was needed to support MultiDetector options in the first place. This adds that functionality.
The main tricksiness here is in parsing something like:
```
L1:https://URL/PATH/TO/FILE
```
or
```
https://URL/PATH/TO/FILE
```
and figure out whether `https` is a URL prefix or an ifo prefix.

Allow for multi-ifo input file options

---

bin/pycbc_live
pycbc/filter/matchedfilter.py
pycbc/waveform/sinegauss.py

Trying to add sgchisq to pycbc_live. I need a testing example so at the moment this is only me guessing at a few things. But I think this *might* work.
Basically:
* It seems that actually calculating sg_chisq is easy enough. Bruce chisq is calculated in the same way as in pycbc_inspiral, so we can add sg_chisq in the same place. I've done that.
* It seems that sg_chisq would now be populated in the result array.
* The statistic is computed using this result array and the standard stat classes. As far as I can see this will just use the `sg_chisq` array (maybe I got some of the names wrong, I need to test to see that)
So I think with this patch one can just flip the statistic. Am I missing anything?

Adding sgchisq calculation to PyCBC Live

---

pycbc/waveform/waveform.py

Here's another fix for a division that requires an integer output.

Integer division fix for Python 3

---

pycbc/frame/losc.py

This adds the run prefix for O2 so that we can read from gwosc using the pycbc api. (Will also need this prefix part for O2 segments once that patch is also applied).

allow to read from O2 losc data

---

pycbc/events/single.py

This switches the single ifo options for pycbc live to multi detector options. In this way they can be set different for each ifo independently. The run script will need to be updated if this is merged.
[untested]

use multi ifo action for pycbc live singles

---

bin/workflows/pycbc_create_offline_search_workflow
pycbc/workflow/plotting.py

I add plots to section 3 of the results page. I've also collected the section 2 plots, and added in a couple of missing section 8 plots. This is tested (see slack).
As there is currently no censor file, these are *not* removing coincident triggers from these plots. I've set this up so this can be fixed as a one-liner once that file exists.

Adding section 3 plots

---

pycbc/results/layout.py
pycbc/results/metadata.py

This change allowed me to use `pycbc.results` and `ligo.skymap` in the same env.

pycbc/results fixes for Python 3

---

pycbc/events/coinc.py
pycbc/events/stat.py
pycbc/filter/matchedfilter.py
pycbc/vetoes/sgchisq.py

Adds a `phasetd_newsnr_sgveto` statistic. As this is a coinc-only statistic it is not added to the singles statistic dictionary.
UNTESTED

Adding/fixing phasetd_newsnr_sgveto for PyCBC Live

---

pycbc/frame/losc.py

We must track the changes in frame channel names for getting GWOSC bulk data as it differs for O1 vs O2.

frame channel name changes in gwosc over time

---

pycbc/filter/resample.py

Another integer division fix for Python 3 compatibility.

resample.py: fix for integer division in indicies

---

pycbc/inference/option_utils.py

This PR adds the ability to load constraints from the config file in the `prior_from_config` function called for plotting priors.
@cdcapano Can we not just use 
```
variable_params, static_params = distributions.read_params_from_config(...)
dists = distributions.read_distributions_from_config(...)
```
instead of this block of code https://github.com/gwastro/pycbc/blob/master/pycbc/inference/option_utils.py#L488-L504 ?

Load constraints when reading prior from config for plotting

---

bin/hdfcoinc/pycbc_page_foreground
bin/workflows/pycbc_create_offline_search_workflow
bin/workflows/pycbc_make_coinc_search_workflow
pycbc/workflow/coincidence.py
pycbc/workflow/core.py
pycbc/workflow/plotting.py

I set out to add section 4 and 7 plots into the new workflow. In doing this I had to fix a few other issues, which all now appear together here (because separating this off is a major time sink). Many of the section 4/7 plots are currently not working with the new format inputs. However, when these codes are patched the corresponding lines in the commented out code below can be uncommented and these will be added. Here's the list of things included in this PR.
* Add all section 4/7 plots to the workflow
* After testing, comment out all section 4/7 plots that are not working.
* Clean up usage of tags in the new workflow (please don't add unneeded tags or send jobs tags that are not needed!!)
* Add a warning message to inform you if you are using too many tags
* Remove unused ancient …

Adding more plots, and a few other things

---

bin/inference/pycbc_inference_plot_prior
pycbc/inference/option_utils.py

Changes parser.add_argument from default = ["prior"] to default="prior".  It also changes the option name from --sections to --prior-section

Corrects an error caused by pull request #2562.

---

bin/hdfcoinc/pycbc_plot_singles_timefreq
bin/minifollowups/pycbc_foreground_minifollowup
bin/minifollowups/pycbc_page_coincinfo
bin/minifollowups/pycbc_plot_trigger_timeseries
bin/plotting/pycbc_plot_qscan
bin/workflows/pycbc_create_offline_search_workflow
pycbc/workflow/minifollowups.py

This PR gets the foreground minifollow to work. See slack for the test run and the page created.

Foregroud minifollowup dev

---

bin/inference/pycbc_inference
pycbc/inference/option_utils.py

It turns out that the strain module needs a low frequency cutoff option to be specified, for inverse spectrum truncation. Otherwise, the low frequencies will overwhelm the inverse PSD estimate, resulting in a junk PSD. Not realizing this has caused a few different people to get junk PE results now, which we only realized after several days of running.
This patch adds a catch that will raise an error if data is loaded, but no low frequency cutoff was provided. The help message for `low-frequency-cutoff` is also modified to make it clear that the command-line option is for PSD estimation (while likelihood cutoff is specified in the config file).

Make low frequency cutoff required when using data in pycbc inference

---

pycbc/dq.py
pycbc/frame/losc.py

This makes the segment query of GWOSC info run independent and not hardcoded to just O1 segment info.

Allow the segments to query O1 or O2 times

---

bin/inference/pycbc_inference
pycbc/inference/sampler/base_mcmc.py
pycbc/inference/sampler/emcee.py
pycbc/inference/sampler/emcee_pt.py
pycbc/workflow/jobsetup.py

This patch allows the user to specify a signal in the workflow ini file which triggers the sampler to exit after it has written a checkpoint. If the right set of ini options are specified, then the condor will restart the job, taking care of the transfer of checkpoint files.
To enable this using `SIGUSR2`, add the following pegasus profiles for the executable:
```
[pegasus_profile-inference]
pegasus|gridstart = NoGridStart
condor|+CheckpointExitBySignal = True
condor|+CheckpointExitSignal = 12
condor|+SuccessCheckpointExitBySignal = True
condor|+SuccessCheckpointExitSignal = 12
condor|+WantFTOnCheckpoint = True
condor|+CheckpointSig = 12
condor|periodic_remove = (HoldReasonCode is 13)
```
and the following option for the sampler:
```
[sampler]
checkpoint-signal = USR2
```

Implement condor checkpointing

---

pycbc/scheme.py

This PR adds support for setting the default processing scheme using the `PYCBC_SCHEME` environment variable (default `"cpu"`), which must match one of the available schemes. 
```pytb
$ python -c "from pycbc.scheme import *; print(scheme_prefix[DefaultScheme])"
cpu
$ PYCBC_SCHEME="numpy" python -c "from pycbc.scheme import *; print(scheme_prefix[DefaultScheme])"
numpy
$ PYCBC_SCHEME="blah" python -c "from pycbc.scheme import *; print(scheme_prefix[DefaultScheme])"
File "/Users/duncan/git/pycbc-fork/pycbc/scheme.py", line 164, in <module>
_default_scheme_class = _scheme_map[_default_scheme_prefix]
KeyError: 'blah'
During handling of the above exception, another exception occurred:
File "<string>", line 1, in <module> …
```

Allow setting scheme from environment

---

bin/pycbc_inspiral
pycbc/events/events.py

This helps smooth out the triggers a bit as a function of chirp mass more than the raw bins in chirp mass made by splitting the template bank. 
Adds *optional* argument to pycbc inspiral
--keep-loudest-log-chirp-window which allows binning in the log chirp mass of the template being analyzed. Clustering is then done in each bin separately over time.

add clustering option to pycbc inspiral to cluster triggers in chirp bins.

---

bin/pycbc_multi_inspiral

Fixed bug where if out vals had a value that was not None or one value per trigger then it would crash. This was previously fixed in eventManager but is instead fixed in pycbc_multi_inspiral to limit code changes to pycbc.

pycbc_multi_inspiral output bug fix

---

examples/inference/bbh-injection/inference.ini

Sets the number of walkers and temps in the example configuration file to 1000 and 4, instead of 200 and 20. Also adds `max_posterior` to the burn in tests, which protects against `emcee_pt` quitting too early.

Change suggested number of walkers and burn in

---

bin/inference/pycbc_inference
pycbc/inference/option_utils.py
pycbc/workflow/configuration.py

Currently, `pycbc_inference` used it's own config option group and parser (in `inference/option_utils`). This is redundant with the argument group and `from_cli` option that exists in `workflow/configuration`. It also lacks the `config-delete` option. This patch has `inference` use the functions in the workflow configuration module instead, and removes the redundant functions from `inference/options_utils`.
I also changes the heading and description on the configuration argument group, to make it less workflow-specific.

Use config argument group in pycbc inference

---

pycbc/workflow/jobsetup.py

This pull request addresses an issue where the assignment between splitbanks and inspiral jobs is somewhat random (and can apparently change). Here we sort the template banks to ensure a predictable matching. Note that as we are sorting by string `BANK10` is smaller than `BANK1` so `JOB1` might get `BANK10`, but at least the matching is predictable. If it is felt that there is a strong advantage to having `BANK1` -> `JOB1` I can add that, but it will be a little more complicated.
As a note: I'm still not sure what caused the ordering to change, but this change should make things a lot more stable!

Sort tmpltbanks

---

pycbc/inject/inject.py

In the _HDFInjectionSet class, the injvals are read from the hdf file using 
`injvals = {param: group[param][:] for param in parameters}`
It seems like this class targets hdf files that set a group of "static_args", which will be common for all variable_args, and it expects that if there is only one injection this will be stored in the static_args and then `injvals = []`.
However, it could also be a file that does not contain a group "static_args" and stores only one value for each param, so that `group[param][:]` will return an error
`ValueError: Illegal slicing argument for scalar dataspace`
This PR changes [:] for [()], so that it will work independently of how many values are stored in group[param]

Bug in _HDFInjectionSet

---

test/test_chisq.py

Before opening a PR to convert the chi-squared code to Cython, I want to improve the `test_chisq.py` code, so that it actually tests the chi-squared calculation. I figure testing consistency between the FFT-based approach and the currently-weave-based quick approach would be good enough here. I use examples from the ODW tutorials as a base.

Improve chi-squared test code

---

pycbc/conversions.py

This adds `final_mass_from_initial` and `final_spin_from_initial` to `conversions.py`. These functions take in the initial masses (and, optionally, spins) and returns the estimated final mass/spin. The fitting functions uses are the ones used by EOBNR. At some point it'd be good to add support for the PhenomD functions too, but this works for now.
Example:
```
>>> from pycbc import conversions
>>> conversions.final_mass_from_initial(35., 35.)
66.62499655233485
>>> conversions.final_spin_from_initial(35., 35.)
0.6864600000000001
```
These functions can be used when plotting posteriors.

Add final mass/spin from initial parameters to conversions

---

pycbc/io/live.py

This patch creates plots of the PSDs and SNR timeseries when uploading events to GraceDB. As all this stuff is already in memory this shouldn't raise any concerns about latency (although we could spawn off the upload as Alex said if it becomes necessary later).
A test if this is here (sorry Alex):
https://gracedb-playground.ligo.org/events/T14662/view/
I also fix a deprecation warning in uploading the HDF file and undo the dynamic range factor from the PSD uploaded in the HDF file (the XML file is fine).

Add basic plots to GraceDB uploads

---

bin/pycbc_live
pycbc/filter/matchedfilter.py

People suggested that we rather not populate the χ² fields of the LIGOLW uploads for the followup detectors, rather than setting them to zero. I think this is reasonable and should have no side effects.
I also spotted and fixed an incorrect behavior: some detector-dependent trigger fields (namely `sg_chisq` and `sigmasq`) were being copied from one of the above-threshold detectors into the fields of followup detectors. I think the only important side effect was that the effective distance of the followup detectors in GraceDB was incorrect. I now take the correct `sigmasq` from the SNR series calculation.

Live: avoid human confusion with χ² not being calculated

---

bin/hdfcoinc/pycbc_plot_singles_vs_params

We do not want codes to silently produce invalid plots if inputs are invalid.  Inputs should be restricted to valid values and/or checked when possible and informative error messages should be produced rather than empty or invalid output.

Automatic input checking and raise informative error for invalid z-var

---

bin/pycbc_live
pycbc/filter/matchedfilter.py
pycbc/frame/__init__.py
pycbc/frame/frame.py
pycbc/strain/strain.py

I do some refactoring of the data reader code in `pycbc_live`, and add the ability to use different analysis flags for different detectors. This is necessary for Virgo in O3.
Note that this patch will require a change in the current PyCBC Live configuration.
Needs testing.

Live: enable per-detector analysis flags

---

bin/minifollowups/pycbc_page_coincinfo

'time1' is not an attribute of the statmap file so this path failed in the 2-ifo workflow.

Bug in pycbc_page_coincinfo for 2-ifo workflow

---

bin/hdfcoinc/pycbc_coinc_findtrigs
bin/hdfcoinc/pycbc_multiifo_coinc_findtrigs

One issue with handling a lot of coincs in some of my test runs has been that sum jobs when sorted by mchirp produce very different memory useage patters. This PR addresses that problem by randomizing which templates are handled in each coinc job (but in a reproduceable way). 
I'll report back testing I'm doing on ATLAS when that's complete.

shuffle coincs to randomize between jobs

---

bin/hdfcoinc/pycbc_coinc_hdfinjfind

It looks like PR#2499 accidentally removed a critical line. This is causing injections to be counted as missed when in actuality they are not recoverable at all due to being in times you aren't analyzing. 
https://github.com/gwastro/pycbc/commit/426cae0cc9546cb16e2e98f0532a8178405c3e21#diff-83b130558a65c4e4349ba945877e1758

fix mistake in pr2499 which broken injection matching

---

bin/hdfcoinc/pycbc_fit_sngls_by_template

I've checked this produces the same number of triggers, etc. Reduces the memory useage of fits_sngl_by_template by a little over an order of magnitude when reading many triggers. 
In my case, this reduced peak memory useage from 78 GB -> 4 GB.

reduce memory useage of fit by template

---

docs/hwinj.rst

`pycbc_inspiral` can't write to xml.gz files now. https://github.com/gwastro/pycbc/blob/master/bin/pycbc_inspiral#L259 calls https://github.com/gwastro/pycbc/blob/master/pycbc/events/eventmgr.py#L364-L372 . So made the `pycbc_inspiral` example output file hdf and print the time and SNR from that file.
Also updated the ASCII/xml.gz default filenames that I noticed have changed.

Write/read from hdf in inspiral test run in hwinj docs & update filenames

---

pycbc/dq.py

The new DQ module fails if trying to analyse data outside of LOSC released times. For obvious reasons this is not good for those of us in the LVC.
Moving a try block is all that's needed here (but I'm sure if I like the "try both" approach, as it prints a confusing Traceback in python3 and prints warnings about O3 data not being in GWOSC).

Let's not fail if analysing O3 data

---

bin/bank/pycbc_geom_aligned_bank
bin/pycbc_make_banksim
bin/pycbc_make_faithsim
bin/workflows/pycbc_create_offline_search_workflow
bin/workflows/pycbc_make_coinc_search_workflow
pycbc/distributions/angular.py
pycbc/distributions/bounded.py
pycbc/events/coinc.py
pycbc/inference/models/gaussian_noise.py
pycbc/results/render.py
pycbc/results/versioning.py
pycbc/workflow/configuration.py
pycbc/workflow/core.py
pycbc/workflow/datafind.py
pycbc/workflow/grb_utils.py
pycbc/workflow/injection.py
pycbc/workflow/minifollowups.py
pycbc/workflow/pegasus_workflow.py
pycbc/workflow/plotting.py
pycbc/workflow/psd.py
pycbc/workflow/psdfiles.py
pycbc/workflow/segment.py
pycbc/workflow/tmpltbank.py

Python3-related changes necessary to generate the all-sky workflow in python3. There's still a separate issue with dqsegdb, and issues with pegasus, that means this won't run in python3 out of the box, but this is nicely contained under "python 3 compatibility changes that don't change python2 functionality". This is basically:
* Using six for module imports where names are different.
* Python3 string vs bytes handling is a little confusing when you're used to python2. We're careless about this, and it will doubtless cause issues in other places to be fixed going forward.
* Octals must be declared clearly, not as 0755 (compatible with python2 and 3)
* File opening *must* be clear about the difference between `r` and `rb` in python3 (although again string handling confuses this somewhat). …

Python3 compatibility in workflow generation

---

bin/hdfcoinc/pycbc_coinc_findtrigs
bin/hdfcoinc/pycbc_multiifo_coinc_findtrigs

Make the coinc code more flexible in terms of decimation levels. This *changes* the options to findtrigs
The new decimation option is 
```
--loudest-keep-values 9:10 8.5:100 8.0:100 7.5:10
```
Decimation is applied from left to right, so this can be read as (decimate all triggers < 9 by 10x) then (decimate remaining triggers < 8.5 by another 100x) and so on...

change coinc options to allow multiple decimation levels

---

bin/minifollowups/pycbc_page_coincinfo
bin/minifollowups/pycbc_page_snglinfo
bin/minifollowups/pycbc_sngl_minifollowup
pycbc/io/hdf.py

I'm trying to get the workflow to complete more consistently when handling larger numbers of triggers and some of the post-processing is unnecessarily choking. 
So far this patch addresses memory / performance issues with 
* pycbc_page_snglinfo 
* original useage in my 2-ogc runs peaked at ~79 GB of memory.
* ~ 50 x reduction in memory and compute time when following up a known trigger id 
* Single minifollowup workflow generator (also had to check it ran after changes to single triggers class)

update io to reduce memory useage

---

bin/bank/pycbc_aligned_bank_cat
bin/bank/pycbc_bank_verification
bin/bank/pycbc_geom_aligned_2dstack
bin/bank/pycbc_geom_aligned_bank
bin/bank/pycbc_geom_nonspinbank
bin/bank/pycbc_tmpltbank_to_chi_params
bin/hdfcoinc/pycbc_calculate_psd
bin/hdfcoinc/pycbc_page_segments
bin/hdfcoinc/pycbc_page_segplot
bin/hdfcoinc/pycbc_plot_bank_bins
bin/hdfcoinc/pycbc_plot_hist
bin/hdfcoinc/pycbc_plot_psd_file
bin/hdfcoinc/pycbc_plot_psd_timefreq
bin/hdfcoinc/pycbc_plot_singles_timefreq
bin/inference/pycbc_inference_plot_posterior
bin/pycbc_inspiral
bin/pycbc_split_inspinj
pycbc/filter/qtransform.py
pycbc/io/hdf.py
pycbc/io/record.py
pycbc/noise/reproduceable.py
pycbc/strain/strain.py
pycbc/tmpltbank/bank_output_utils.py
pycbc/tmpltbank/lattice_utils.py
pycbc/tmpltbank/partitioned_bank.py
pycbc/workflow/core.py
pycbc/workflow/segment.py
test/test_autochisq.py

Some more python3 fixes, which enable me to actually run a workflow up to (but not including) the INSPIRAL jobs.
* I changed *all* instances of `xrange` to `six.moves.range`
* I changed *all* instances of `.next()` to `next()`
* Dealing with other assorted failures that arose (one integer division issue, one dictionary.items() is no longer a list issue, ...)

More python3 compatibility changes

---

pycbc/distributions/__init__.py

pycbc_inference will raise an error if a variable_param has no priors section. However, if there is a priors section for a variable that is not specified in the list of variable_params, it will just run without sampling over that parameter (which would raise no warnings/errors if that parameter has a default value in the waveform approximants).
This PR raises an error when reading the config file if it finds a priors section that has no matching variable in the variable_params section.

Config file sanity check for inference

---

pycbc/inference/evidence.py

This module introduces 6 methods for estimating the evidence of a Bayesian Inference model.
The first method is the Arithmetic Mean Estimator. It is the simplest evidence estimator, and is done simply by drawing samples from the prior and calculating the log likelihood. This estimator converges to the true evidence in the limit that you sample the entire prior space. The calculation is done for log likelihoods and returns a log evidence.
The second method is the Harmonic Mean Estimator. It samples from the posterior distribution and is the harmonic mean of the log likelihood. This is a really bad estimator that should never be used, https://radfordneal.wordpress.com/2008/08/17/the-harmonic-mean-of-the-likelihood-worst-monte-carlo-method-ever/  . I've included it here with that warning. …

Evidence calculations module

---

examples/inference/bbh-injection/inference.ini
examples/inference/bbh-injection/run.sh
examples/inference/gw150914/inference.ini
examples/inference/gw150914/run.sh
examples/inference/gw150914/run_test.sh
pycbc/inference/models/gaussian_noise.py
pycbc/inference/models/marginalized_gaussian_noise.py
pycbc/inference/option_utils.py

As title says.
@cdcapano  The PR makes the low frequency cutoffs for likelihood calculation to be read from the config file as 
```
h1-low-frequency-cutoff = 20
l1-low-frequency-cutoff = 30
```
etc. These will be saved in fp.attrs as `'{}_likelihood_low_freq'.format(det)`. 
The low frequencies for multi ifos for data conditioning is read in the command line with the option `--data-conditioning-low-freq`. This is then saved to `opts.low_frequency_cutoff` for passing to strain.from_cli_multi_ifos and psd.from_cli_multi_ifos. I've removed the `low_frequency_cutoff_from_cli` function as it should not be needed anymore.
I don't see how I can save the data conditioning low freqs in the output file though, as the metadata is being written now in the models module which which does not have access …

Re-enable using different low frequency cutoffs for different detectors

---

bin/inference/pycbc_inference_plot_acf

If thinning was done on the fly with either `thin-interval` or `max-samples-per-chain`, the x-axis of `plot_acf` will be off by whatever thinning factor was used. This accounts for that. Example on 100 iterations, in which a thinning interval of 4 was used:
* [Before](https://www.atlas.aei.uni-hannover.de/~work-cdcapano/scratch/prs/fix_plot_acf/before.png)
* [After](https://www.atlas.aei.uni-hannover.de/~work-cdcapano/scratch/prs/fix_plot_acf/after.png)
The x-axis spans 0-100 in the update.

Account for thinning in plot ACF

---

bin/pycbc_create_injections
bin/workflows/pycbc_make_inference_inj_workflow
examples/inference/bbh-injection/make_injection.sh
pycbc/inference/io/base_hdf.py
pycbc/workflow/inference_followups.py

This changes to the convention of using `static_params` and `variable_params` in several places: the executables `pycbc_create_injections` and `pycbc_make_inference_inj_workflow`, and the `make_inference_summary_table` function in `pycbc.workflow.inference_followups`.
Note that `pycbc_make_inference_workflow` was already calling `make_inference_summary_table` with a `variable_params` arg.

Use naming convention params instead of args

---

bin/inference/pycbc_inference_plot_samples

This PR:
- makes `pycbc_inference_plot_samples` plot the average of all walkers for `--parameters` by default, if no `--walkers` is provided as input.
- Options for `--walkers` if provided are `'all'` which plots chains for all walkers from the common temperature `--temps`, or a sequence of indices which plots chains corresponding to those walker indices from the common temperature `--temps`. 
- plots the real iterations in the x axis now instead of intervals which were labeled as iterations before.
- added a figsize so that the labels are not cut off and some font edits.
Examples : 
No `--walkers` provided, so plots averaged chain : https://sugwg-jobs.phy.syr.edu/~soumi.de/tmp/samples_mchirp_m1_walkersNone.png
`--walkers 'all'` : …

Plot average chains for parameters by default

---

bin/inference/pycbc_inference_plot_acl

The y and x labels of plot acl are currently not correct, and it combines all parameters into a single histogram. Also, if thinning on the fly occurs (which is recorded by the `thinned_by` parameter), then it doesn't account for that in the histogram.
This updates `plot_acl` so that it creates separate histograms for each parameter. It also takes into account `thinned_by`, multiplying the ACLs accordingly. Example:
* [Before](https://www.atlas.aei.uni-hannover.de/~work-cdcapano/scratch/prs/fix_plot_acl/before.png)
* [After](https://www.atlas.aei.uni-hannover.de/~work-cdcapano/scratch/prs/fix_plot_acl/plotacl.png)

Fixes to plot ACL

---

bin/pycbc_optimal_snr

This PR fixes an example of deprecated `except` syntax.

Updated except syntax for python3

---

bin/pygrb/pycbc_make_grb_summary_page
pycbc/inference/models/base.py

This PR updates all references to python2's `ConfigParser` module (one update, removed one unused import).
I did notice that there is one example of
https://github.com/gwastro/pycbc/blob/bce57349af445f957f66ce2f28f8b633d9516a3e/pycbc/workflow/configparser_test.py#L3-L7
which is not guaranteed to give the same result as `from six.moves import configparser`, specifically in environments where the [`configparser`](https://pypi.org/project/configparser/) backports module is available.

Updated configparser imports for python3

---

pycbc/fft/backend_support.py
pycbc/inference/models/base.py
pycbc/inference/models/base_data.py
pycbc/waveform/waveform.py

This PR updates those functions that call `keys()` directly in the `return` statement to return `list(<var>.keys())` instead, which is required to retain the same return type when using python3.

Return keys() as list from functions

---

bin/pycbc_losc_segment_query
examples/gw150914/audio.py
examples/gw150914/gw150914_h1_snr.py
pycbc/frame/losc.py

This PR updates a few `urllib` imports to work for python3.

Updated urllib imports for python3

---

test/bankvetotest.py
test/test_autochisq.py
test/test_matchedfilter.py
test/test_skymax.py

This PR fixes a few failures with new versions of numpy that don't like creating arrays with the size given as a `float`, or similar.

Cast floats to int for numpy in test suite

---

test/test_autochisq.py

This PR replaces tabs with (hopefully correct) whitespace to appease python3's more pedantic parser.

Fixed inconsistent use of tabs in test module

---

pycbc/tmpltbank/bank_output_utils.py
test/test_detector.py

This PR fixes two instances of indexing/repeating an iterator that causes the test suite to fail when using python3. The simple solution is to cast to `list`.

Cast iterator to list where needed

---

pycbc/inference/io/base_hdf.py
pycbc/inference/io/base_mcmc.py
pycbc/inference/io/base_multitemper.py
pycbc/inference/io/multinest.py
pycbc/inference/models/base.py
pycbc/inference/option_utils.py
pycbc/inference/sampler/base_mcmc.py
pycbc/inference/sampler/base_multitemper.py

This PR removes `isinstance` references to `basestring` and `unicode` and replaces them with `six.string_types`.

Use string_types for type checking

---

bin/hdfcoinc/pycbc_calculate_psd
bin/hdfcoinc/pycbc_coinc_statmap_inj
bin/hdfcoinc/pycbc_multiifo_coinc_statmap_inj
pycbc/workflow/inference_followups.py

This PR fixes all uses of `izip` and `izip_longest` to work on python3 - most of those imports were unused.

Fixed use of izip and izip_longest for python3

---

pycbc/psd/analytical.py

I noticed a common error in the Python 3 unit test, seemingly due to passing non-int lengths to a LAL function taking a `size_t`.

Fix py3 error when analytical PSD length is not int

---

bin/workflows/pycbc_make_inference_workflow
examples/workflow/inference/inference.ini
examples/workflow/inference/workflow_config.ini

This PR changes the import for the call to ``pycbc.workflow.datafind`` from ``core`` to ``datafind``. It also checks if there were frame files returned from the module before added it to the ``File``.

Change import to pycbc.workflow.datafind and check if frame files returned from module

---

bin/workflows/pycbc_make_inference_workflow
pycbc/results/templates/files/file_default.html
pycbc/workflow/jobsetup.py
pycbc/workflow/segment.py

This PR updates calls to `dict.iter{items,values}` with their non-`iter` equivalents, so that they work with python 3.

Replaced dict.iter{items,values} with dict.{items,values}

---

bin/hdfcoinc/pycbc_plot_psd_file
bin/inference/pycbc_inference_plot_samples

This fixes a bug introduced in #2696 that caused PSD plotting to fail when running `pycbc_make_coinc_search_workflow`. The plotting code will now look for a low frequency cutoff in file locations used by both the search and inference workflows.

Make PSD plotting compatible with inference and search workflows

---

bin/minifollowups/pycbc_page_snglinfo
bin/minifollowups/pycbc_sngl_minifollowup
pycbc/workflow/minifollowups.py

This patch makes two quick fixes for sngl minifollowups:
* Order the sngls in the right order again (loudest event first, not last)
* Stop sending n-loudest by sngl_page_info, and make the code fail if it is sent both options (fixes #2728)
This is not yet tested.

Two quick fixes for minifollowups

---

pycbc/workflow/plotting.py

It looks like there's been some issues with plot_spectrum as this code now runs in the inference workflow.
One fail mode I've seen is that the list of ifos, and the list of PSD files, must match up (e.g. if H1 appears first in the ifo list, the H1 PSD file must go first). This doesn't appear to have caused problems in the past, but some combination of python3 changes and inference changes have now allowed this to be a failure mode.
The solution is simple: Don't tell plot_spectrum the ifos. If not given this option it just gets the ifos from the supplied files. This seems the "best" solution without providing redundant information.
This has been tested and fixes the failure mode I saw.

Don't send ifos to plot_spectrum - it can fail

---

bin/minifollowups/pycbc_sngl_minifollowup
bin/workflows/pycbc_make_coinc_search_workflow
pycbc/io/hdf.py
pycbc/workflow/minifollowups.py

This patch edits the `pycbc_single_minifollowups` code to be able to use the various `exp_fit` statistics, which require supplementary files. This has been tested as per examples shared in the SLACK channel.
We still need to send the same files to the jobs running within the DAX that this will produce, but I leave that to a separate PR.

Allow statistic files in single_minifollowup

---

pycbc/inference/io/base_hdf.py
pycbc/inference/io/base_sampler.py
pycbc/inference/models/base.py
pycbc/inference/models/base_data.py
pycbc/inference/sampler/base.py
pycbc/inference/sampler/base_mcmc.py
pycbc/inject/inject.py
pycbc/strain/calibration.py
pycbc/strain/recalibrate.py

This PR replaces all uses of the `__metaclass__` class variable with calls to `six.with_metaclass` to support applying metaclasses in python2 and python3 at the same time.

Use six.with_metaclass to add metaclasses in python2 and 3

---

pycbc/dq.py
requirements.txt
test/test_dq.py

This patch moves `dq.py` to `dqsegdb2` because the interface is simpler and does not explicitly require a version flag to be specified. I've also had better results with `dqsegdb2` in python3, although I did not properly debug the original `dqsegdb` in python3.
I also enforce that flag names must start with a `+` or a `-`. I have tested this change under LVC conditions, but I do want to test running this using a veto-definer file "properly".

Move to dqsegdb2 and a few minor fixes to dq.py

---

pyproject.toml

Pip looks at pyproject.toml to allow one to enforce that a package be installed *before* building a wheel out of your project. This is needed in python3 for pycbc to ensure numpy of the right version is available before building the compiled code. In python2 the wheel build fails anyway (related to weave) so it runs setup.py at the end of the process to finish the install and bypasses this problem. 
See https://www.python.org/dev/peps/pep-0518/ for details.

use build dependency feature now to enforce numpy / cython are available

---

pycbc/types/frequencyseries.py

This one is more interesting. Apparently the `LIGOTimeGPS` object can no longer take numpy float/int types directly in python3 (it can in python2). This patch converts the numpy type to the corresponding native python type if it needs to (thanks StackOverflow!)

LIGOTimeGPS cannot take numpy type in python3

---

pycbc/inference/burn_in.py
pycbc/inference/io/__init__.py
pycbc/inference/io/base_hdf.py
pycbc/inference/io/base_mcmc.py
pycbc/inference/io/base_multitemper.py
pycbc/inference/sampler/base_mcmc.py
pycbc/io/record.py

Here are the following changes necessary to make the inference examples run without failing on python3. I am reasonably certain that further changes will be needed to make things run smoothly, but I'll leave further testing for Collin.

Python3 fixes to make inference examples run

---

bin/minifollowups/pycbc_injection_minifollowup
bin/minifollowups/pycbc_page_injinfo
bin/plotting/pycbc_plot_qscan
bin/workflows/pycbc_create_offline_search_workflow

This PR enables injection minifollowups. Changes: give time = -1.0 to the plotting code when the injection is looked for an ifo that is not online. This is how combine statmap determines and foreground and single followup expects the codes.
Work in progress, some pycbc_single_template and pycbc_page_injinfo jobs still fail.

Multiifo inf minifollowup

---

bin/hdfcoinc/pycbc_coinc_findtrigs
bin/hdfcoinc/pycbc_multiifo_coinc_findtrigs

This is a simple bugfix to an issue in the default value for `--loudest-keep-values`. I think the issue arose from somewhat confusing behaviour in argparse itself. Basically if you provide the "default value" on the command line some processing is done to this, (in this case it becomes a list because of nargs). However the `default=` value is *not* processed in the same way and should be the python type that this value will be set to.
So TL:DR it needs to be a list. (I'll defer to the argparse help for more questions about what argparse does).

loudest-keep-values default must be a list

---

bin/workflows/pycbc_make_inference_inj_workflow
bin/workflows/pycbc_make_inference_workflow

This updates `pycbc_make_inference_inj_workflow` and `pycbc_make_inference_workflow` to make plotting of acceptance rate and sample chains optional. This makes the workflows compatible with nested samplers that might not have an acceptance rate or meaningful sample chains.
With this patch, to include plotting of acceptance rate or sample chains you simply need to include the corresponding `inference_rate` or `inference_samples` in the `executables` section of the workflow config file.

Make plotting acceptance rate and sample chains optional

---

.travis.yml
Dockerfile
docs/docker.rst

Apparently `docker commit` overrides `CMD` with whatever command you started the container with in `docker run`. This fixes that problem, simplifies the `CMD`, reduces the number of images as suggested by @spxiwh, and cleans up the documentation.

Fixes to docker container

---

pycbc/waveform/ringdown.py

The ringdown module has become a bit messy: two functions (time and freq domain) to create a single damped sinusoid, two functions to create the superposition of damped sinusoids with same l, m (i.e. add overtones), and two functions to create the superposition of different l, m modes with their overtones. In essence, all the functions are repeating the same lines over and over (getting the input parameters, making the output vector, etc.) and calling the previous functions. Also, the only difference between the mass-spin and the freq-tau approximants is the input parameters they take, but there are different functions for each approximant that again repeat the same lines.
Furthermore, the tapering option is not even working!
This PR tries to simplify all of this. I have create functions …

Ringdown module improvements

---

bin/pycbc_inspiral
pycbc/events/eventmgr.py

I've been noticing very large memory usage of INSPIRAL jobs in the current search workflow. This seems to grow slowly with time, so seems to be due to the large number of triggers being stored in memory in these jobs.
Most of these triggers are removed before writing to disk. This patch adds the ability to run the various "remove triggers" functions that are normally run at the end, every N templates. I also optimized one of these codes as it ran particularly slowly during testing (although it was being called more than expected because of a bug in my testing code, which is now fixed).
I also moved all of that stuff into `eventmgr.py` because it seems to make more sense there than in the inspiral code.

Consolidate triggers to control memory usage

---

pycbc/dq.py

The new DQ code fails if one provides a veto-definer that doesn't contain any CAT_2 entries (for example) for an active IFO. This patch ensures that all of the "special" VDF flags are added if using a veto-definer. (Tested with a VDF not containing entries).

Allow empty vdf

---

pycbc/events/eventmgr.py
pycbc/events/eventmgr_cython.pyx
pycbc/events/threshold_cpu.py
pycbc/fft/fftw_pruned.py
pycbc/fft/fftw_pruned_cython.pyx
pycbc/filter/matchedfilter.py
setup.py

I wanted to try to see if I could push towards a working python3 implementation of `pycbc_inspiral`.  The following places still use weave:
```
* pycbc/waveform/decompress_cpu.py
* pycbc/filter/simd_correlate.py
* pycbc/fft/fftw_pruned.py
* pycbc/events/eventmgr.py
* pycbc/events/threshold_cpu.py
* pycbc/events/simd_threshold.py
```
Decompress_cpu isn't [currently] used, so I left that one for now. Implementations of fftw_pruned (even though that also isn't really used) and eventmgr are included here. But then I hit the simd codes. These are quite detailed and appear to be highly optimized. I'm not sure what to do at this point. How do we port these codes out of weave?

Some more Cython functionality

---

pycbc/strain/strain.py

I introduced a bug into the gating routine by no longer passing a high pass frequency. This can't be reliably assumed to come from sample rate as this is not a required option any longer. In all cases it was assumed before to be 0.5 * the sample_rate so we simply move the resampling (if done) to before the gating routines. In this way the same frequency rate is used for gate time detection.

move resampling to before gating block in strain from_cli

---

.travis.yml
pyproject.toml
setup.py

The python3 travis test now passes, we should require it to pass now into the future.
Other minor changes
* Match pyproject.toml with setup.py so numpy can be less restrictive for python3

require python3

---

bin/hdfcoinc/pycbc_multiifo_coinc_findtrigs
pycbc/events/coinc_rate.py
pycbc/events/stat.py

Multiifo ranking statistic:
Currently calculates the expected rate of coincidences at a given snr value, and subtracts this from a mean coincidence rate (this is a rate for _all_ coincidences, not including the snr infromation) in that detector combination

Multiifo ranking statistic

---

docs/Makefile.gh_pages
docs/Makefile.std
docs/building_bundled_executables.rst
docs/remove_non_standard_imports.py
requirements.txt
setup.py

This starts with #2770 and continues that PR to get Travis actually working. Further to that PR we are now excluding CPnest.py in the documentation, as it cannot work without a cpnest import.
Close #2770

Fix docker build

---

docs/workflow/resources/example_dq.ini
docs/workflow/segments.rst

The multi-ifo workflow will soon be moved over to the new segments format. As requested by @tdent, we need to improve the documentation to show how to use this new module. This patch contains the updated documentation, as discussed in SLACK. An example of the new page is here:
https://ldas-jobs.ligo.caltech.edu/~spxiwh/TMP_DOCS/latest/html/workflow/segments.html
but has the same content as this wiki:
https://github.com/spxiwh/pycbc/wiki/New-DQ-ini-syntax

Update segments documentation page

---

pycbc/waveform/bank.py

Another case of casting `bytes` to `str` ... This is happening a lot in our HDF code, we're going to need to watch out for this.

Another str<->bytes patch

---

pycbc/waveform/ringdown.py

Remove the `unicode` introduced in the ringdown module (PR #2651) for compatibility with python 3.

Remove unicode for python 3

---

setup.py

I think we are ready for a `v1.14` release, with "beta" support for python3 in at most of the main modules. (I think inference and tmpltbank are both untested in python3, and a bunch of executables haven't been tested, but most of the rest should work).

Prepare for new release

---

bin/inference/pycbc_inference
bin/workflows/pycbc_make_inference_inj_workflow

This allows to use the pp_workflow with a file containing pre-made injections. 
pycbc_make_inference_inj_workflow takes files with multiple injections and splits these into files containing one injection each for inference to run on. 
Also allows to insert the keyword 'injection' in the static_params section of the inference.ini file. Static parameters set to this are replaced with the value found in the corresponding injection.

Injections from file for pp-workflow

---

pycbc/inference/entropy.py

This PR adds three things to the entropy module:
* a function `entropy` that returns the regular information entropy for a single distribution https://en.wikipedia.org/wiki/Entropy_(information_theory)
* a function `js` to calculate the Jensen-Shannon divergence https://en.wikipedia.org/wiki/Jensen%E2%80%93Shannon_divergence
* the option `base` (defaults to scipy.stats's default), to have the option to get all these results in bits rather than nats.

Add Jensen-Shannon divergence to entropy

---

bin/hdfcoinc/pycbc_multiifo_combine_statmap
pycbc/workflow/coincidence.py

Give `foreground_time` and `foreground_time_exc` as outputs to the combine_statmap code
This output time is the amount of time for which two or more detectors are functioning, as well as this time with foreground events removed.
Note that if an event happens within >2 detector time, but has not triggered in all detectors, this will not be removed with the foreground veto
This helps to address https://github.com/gwastro/pycbc/issues/2727

Propagate analysis time

---

bin/hdfcoinc/pycbc_multiifo_combine_statmap

as required by https://github.com/gwastro/pycbc/pull/2783

output foreground_veto segments in multiifo_combine_statmap

---

bin/hdfcoinc/pycbc_multiifo_coinc_statmap_inj

The change I made to combine_statmap (in https://github.com/gwastro/pycbc/pull/2773) requires ifos as an attribute in the statmap files, but this was not the case in statmap_inj outputs. This PR addresses that

ifos attribute in statmap_inj output

---

pycbc/detector.py

Technically we use a utc scale, so set this consistently instead of leaving it to the default.

set time scale pedantically

---

bin/hdfcoinc/pycbc_coinc_hdfinjfind

It seems veto indices have not been being applied for some time due to an oversight in extracting the indices from segments. 
Also, `numpy.array([i for i in found_within_time if i not in vetoid])` is simpler than `numpy.delete(found_within_time, numpy.where(numpy.in1d(found_within_time, vetoid))[0])`

hdfinjfind: fix veto index bug, simplify some numpy logic

---

docker/etc/docker-install.sh

/opt/pycbc has a couple of directories owned by root. They should be owned by the pycbc user in the image.

Fix permissions on installed directories in docker image

---

bin/hdfcoinc/pycbc_coinc_hdfinjfind
bin/hdfcoinc/pycbc_page_foundmissed

hdfinjfind is removing some injections within valid time because of incorrect application of vetoes
This PR contains:
- updates to the veto removal logic to allow for vetos in one detector not to remove an injection which could be found coincident in others
- addition of a command line option which defines the minimum number of required ifos for an injection *not* to be vetoed
- a small update to foundmissed plots so that it isn't so 'blobby'

Multiifo injfind

---

pycbc/inference/models/base.py

Currently, you can't use static parameters in sampling and waveform transforms. This fixes that.

Allow static params to be in transforms

---

examples/workflow/inference/ringdown_inference.ini

I believe the current configuration file example for ringdown PE in the documentation would not work because of PR #2626.
Here I am just changing `low-frequency-cutoff = 20` for what it should be with the current code, i.e.
`h1-low-frequency-cutoff = 20
l1-low-frequency-cutoff = 20`

Minor fix in ringdown example docs

---

pycbc/inference/models/gaussian_noise.py
pycbc/waveform/generator.py

Currently, when the `GaussianNoise`  model initializes the waveform generator (`FDomainDetFrameGenerator`), it passes its `variable_params` to the generator. When initialized, `FDomainDetFrameGenerator` checks if tc, ra, dec, and polarization are present in either the variable or static params, raising an error if they are not. This is a problem if you want one of these parameters to be the output of a waveform transform. For example, the following seems like it should work:
```
[variable_params]
delta_tc =
<etc.>
[static_params]
trigger_time = 1126259462.42
<etc.>
[prior-delta_tc]
name = uniform
min-delta_tc = -0.1
max-delta_tc = 0.1
[waveform_transforms-tc]
name = custom
inputs = delta_tc, trigger_time
tc = delta_tc + trigger_time
```
Instead, you get the error:
```
ValueError: …
```

Allow location parameters to be in waveform transforms

---

pycbc/strain/strain.py

The function `insert_strain_option_group` has a `gps_times` keyword argument, which allows you to turn off adding `gps-start-time` and `gps-end-time` to a parser. This would be useful for `pycbc_inference`. However, I discovered that `insert_strain_option_group_multi_ifo` does not have the keyword argument. This adds the same functionality to the` _multi_ifo` function. Needed by #2803.

Add gps times option to strain multi ifo

---

bin/pycbc_live
pycbc/fft/fftw.py
pycbc/filter/matchedfilter.py
pycbc/strain/strain.py

Fixing a few more errors that happen when PyCBC Live runs under Python 3. With these changes, PyCBC Live successfully runs under Python 3 and produces HDF files as well as coinc LIGOLW files.
I have not yet done a careful checks of the correctness of the results and GraceDB uploads are not tested yet.
I am not sure about the h5py workaround I did for saving the approximant array. Comments/alternatives are welcome.

[WIP] More Python 3 fixes for PyCBC Live

---

pycbc/workflow/configuration.py

This adds a class method to `WorkflowConfigParser` that will convert all of the options in a given section into a command-line-like string of options. (The string can then be passed to an argument parser.) See the example in the doc string.
Needed by #2803.

Add method to convert a section into command-line string

---

pycbc/inference/models/gaussian_noise.py

This adds the normalization term to the `GaussianNoise` model (see second term of Eq. 8 in [arXiv:1409.7215](https://arxiv.org/pdf/1409.7215.pdf), and updates the doc string accordingly. This is the first step toward adding support for hierarchical inference over multiple events, and for marginalizing over PSD uncertainties.

Add normalization term to GaussianNoise model

---

pycbc/events/eventmgr.py

Fixing a bug where some template properties were being written out once per ifo rather than once per template.

coherent event manager template properties bug fix

---

pycbc/dq.py
pycbc/workflow/segment.py

Here we add support for the case where the veto-definer defines a flag to be valid until a time of `0`, which we should interpret as no ending time on the period of validity.
We also allow the user to choose a:
`segments-source=dqsegdb`
in the `[workflow-segments]` section of the config file. If this is done the code will not check GWOSC (and print confusing warning messages). This change is backwards compatible, so not providing this option will produce the previous behaviour.
I have tested that this fixes an instance where the end_time of 0 was needed to veto a missing stretch of data and tested both with and without the new flag.

Fix special veto-definer end_time=0 case, and allow dqsegdb ini file option

---

pycbc/strain/strain.py

There is an integer division problem in `detect_loud_glitches()` which causes the glitch detection algorithm to report wrong glitch times (by a large fraction of a second) when autogating is used in PyCBC Live. This was found while debugging #2627. In offline analyses the time series passed to `detect_loud_glitches()` is much longer, and the error becomes negligible. This patch fixes it and cleans up the autogating code a little bit in preparation for #2627.

Fix error in autogating & minor cleanup

---

bin/hdfcoinc/pycbc_multiifo_add_statmap
pycbc/events/stat.py

`pycbc_multiifo_add_statmap` code will use backgrounds of any coincidences where that detector combination is 'on'.
For example, if the foreground coincidence comes from H1L1, but V1 was also operating at the time, the background used for ifar/fap/ifar_exc/fap_exc calculation will combine backgrounds from H1L1, H1V1, L1V1 and H1L1V1

adding add_statmap code

---

pycbc/events/coinc_rate.py
pycbc/events/stat.py

performing exp of the log coinc rate (single statistic) in the coincident calculation (`coinc_multiifo` function) was causing numerical underflow with high-statistic singles
This PR changes the calculation to retain the log rates in order to prevent this
I do not know if we should remove the `combination_noise_coinc_rate` function from the `coinc_rate` module, or leave it, or rewrite to be a wrapper the log version (suggestions welcome)

exp_fit_sg_coinc_rate stat Inf issue

---

bin/workflows/pycbc_make_bank_verifier_workflow
pycbc/workflow/jobsetup.py

Adding a feature to allow user to only inject potentially EM-Bright signal when verifying a template bank with pycbc_make_bank_verifier_workflow.  This is very useful to verify the PyGRB template banks.

EM-Bright accessible from allow_em_bright_in_bankverifier

---

pycbc/results/__init__.py

The pygrb plotting module is setting parts of rcparams and is also setting up logging directly in the import. The former has minor unintended affects on plots in other workflows, the latter hides the logging output from other programs entirely (i.e. the standard 2-ifo coinc workflow). I can't verify this completely, but it seems that many modules are directly importing this module anyway, so I don't think it's necessarily needed to upimport everything. Can someone on the PyGRB side verify? 
i.e. this wouldn't need to change.
https://github.com/gwastro/pycbc/blob/07c32dc38591b324cd34971beea55de2a0989377/bin/pygrb/pycbc_pygrb_plot_skygrid#L32

Don't upimport pygrb results utils

---

bin/hdfcoinc/pycbc_fit_sngls_by_template
bin/hdfcoinc/pycbc_fit_sngls_over_multiparam

include median sigma value as an output to fit_by_template, and propagate through_fit_over_multiparam
This can then be used later in statistic calculation (for a later PR)

add median_sigma to fit_by_template and fit_over_multiparam

---

pycbc/inference/sampler/cpnest.py

After @cdcapano added normalisation constant to likelihood function, This PR is for providing option for using log_likelihood_ratio instead of log_likelihood for running CPNest sampler. One needs to provide option in [sampler] section in configuration file for parameter estimation:
loglikelihood_function=loglr

Adding support for running CPNest sampler with logllikelihood ratio 

---

bin/workflows/pycbc_make_inference_workflow

This supersedes #2741 after feedback from @cmbiwer , not removing any of the 3 options, but making them optional instead. By default, --output-file will be set to workflow_name.dax, while auto-naming for the map and transform catalog are handled by the Workflow.save() method already so they can just stay "None" by default.
```
pycbc_make_inference_workflow: optional file-path options
-normally, users shouldn't need to worry about filenames of
--output-map, --transformation-catalog and --output-file
-will be put in default --output-dir with default names automatically
-but can still be manually set if required
-closes #2739
```

pycbc_make_inference_workflow: optional file-path options

---

bin/hdfcoinc/pycbc_page_snrchi

I encountered an "edge-case bug" in `pycbc_page_snrchi`. Basically if you have a case where you have a set of triggers, where the maximum chi-squared is small, but the maximum SNR is not small the code to identify where best to put the plot label on the plot can fail. In this case it is better to do something than to fail, so I just choose an arbitrary location to put the plot label.
This might lead to the plot being a little obscured, but it's better than the code failing. I'll leave it to someone else to "improve" this edge case in the future if that ever becomes a problem.

Allow fallback in edge case in pycbc_page_snrchi

---

bin/pycbc_submit_dax

We haven't used the "label" clustering in pegasus in a long time now. It also doesn't play well with "horizontal" clustering in pegasus. I want to have horizontal clustering as an option to reduce load at certain stages of the workflow (e.g. grouping inspiral jobs if running small template banks, or grouping plotting jobs).

Change label to horizontal

---

pycbc/workflow/pegasus_files/pegasus-properties.conf

Pegasus' new integrity checking is causing problems. It is checksumming all the frame files (twice) when symlinking these into the workflow directory. As these are symlinked, they cannot be different. This is also causing file system strain in other file_in or file_out jobs. I get that there is some advantage here when running on grid environments, but at the moment it seems like this feature is hurting us more than it is helping us. Therefore I want to disable this as the default (it can always be reactivated on a per-workflow basis using the features in `pycbc_submit_dax`).

Turn integrity checking off

---

pycbc/events/eventmgr.py

The `--chisq-threshold` option in `pycbc_inspiral` is currently broken because of a bug about whether `chisq_dof` holds the actual DOF, or the number of frequency bins. This is a simple fix.

Fix chisq threhsold

---

bin/plotting/pycbc_create_html_snippet

This PR adds a simple utility script to `bin/plotting`, which will take a string of html on the command line, and dump it to a file that can be appropriately parsed by the web-page generation. The specific use case here is that I want to add small blocks of text separating sections in one of the minifollowups, but this could be used in other areas of the results page, where you just want to print some simple, short, information.
This cannot be done in the `pycbc_XXX_minifollowups` script itself, because these scripts do not run in the `local` universe, and so would have to declare outputs to pegasus etc. in advance of the script running. However, we may not know what blocks of html text we need until running the workflow generator.

Add code to write html snippet

---

examples/workflow/inference/workflow_config.ini

can be quite useful especially for new users who start by copying the example files
(as suggested by @cmbiwer in #2856 instead of my initially suggested extra commandline option)

add verbose flag to inference workflow_config.ini example

---

bin/pycbc_live
pycbc/strain/strain.py

Adds autogating functionality to the low latency searches: 
- pycbc_live argument `autogating-threshold` is default to `None`, and gating won't be triggered. Specifying an autogating-threshold value will trigger the autogating function. 
- `Clustering time`, `gating padding`, `gating window`, `corrupt time` could be specified in pycbc_live arguments.
[NOTE: Perhaps should add arguments in pycbc_live to specify psd duration and overlap for detect_loud_glitches(). For now it's hardcoded in to be (1s, 0.5s).]

Adding autogating to PyCBC Live

---

pycbc/distributions/gaussian.py

The `invcdf` function in the `Gaussian` distribution has a bug in it. For example, with:
```
meanx = 1.3420330148091835
varx = 0.0081
minx = 1.
maxx = 2.
```
I plotted the CDF (input) vs the inverse CDF (output) from pycbc, and compared to scipy's to `scipy.stats.truncnorm`, getting [this](https://www.atlas.aei.uni-hannover.de/~work-cdcapano/scratch/prs/fix_gaussian_invcdf/gaussian_invcdf_comp-bug.png). Clearly, something is wrong. This will bug will affect both multinest and dynesty when using a Gaussian distribution for any parameter prior.
This patch fixes this, and in the process adds a cdf function to  the `Gaussian` distribution. [Here is a notebook](https://www.atlas.aei.uni-hannover.de/~work-cdcapano/scratch/prs/fix_gaussian_invcdf/GaussianDistributionCheck.html) comparing results …

Fix invcdf in Gaussian distribution

---

bin/hdfcoinc/pycbc_coinc_hdfinjfind
bin/hdfcoinc/pycbc_page_sensitivity
bin/minifollowups/pycbc_injection_minifollowup
bin/minifollowups/pycbc_page_coincinfo

Temporarily suspending the calculation of inclusive IFAR for injections in the multi-ifo pipeline while we work out what to do with full data/zerolag.  (Also since as noted in #2824 the calculation is probably already buggy with existing code.)
These changes are needed to not break the pipeline given the absence of inclusive IFAR, but also preserve existing 2-ifo behaviour.

Inj exc ifar

---

pycbc/distributions/__init__.py

pycbc_inference ignores a variable_param (even if it has a priors section) when the same parameter appears in the static_args section. This can often happen when copying config files from other runs, and one would not notice until getting a matplotlib error when trying to plot the results.
This PR raises an error when reading the config file if it finds that a parameter is repeated both in the static_args and in the variable_args sections.

Inference warning when parameter repeated

---

bin/pycbc_live
pycbc/strain/strain.py

This makes PyCBC Live save autogates into the output HDF5 files for posterity. It also makes the autogating options consistent with the offline search code and documented.

PyCBC Live autogating fixes

---

bin/hdfcoinc/pycbc_cut_merge_triggers_to_tmpltbank
bin/hdfcoinc/pycbc_reduce_template_bank

Add two new executables that can be used to reduce the template bank to a specified region, and to cut out triggers from the removed templates from the various TRIGGER_MERGE files.
The bank is reasonably straightforward, but the TRIGGER_MERGE files are a little more involved as you have to remap the memory access objects and figure out which blocks of triggers you need, given the way that data is stored in that file. These codes have been quite extensively tested though.
The only weird part here is the desire to allow the user to supply some arbitrary region cut (which might be in any parameter, or derived parameter, contained in the bank). I hate supplying code on the command-line, which is one potential solution to this problem. Instead I ask the user to supply a python code, that …

Add new codes to cut out parts of the tmpltbank

---

Dockerfile

See discussion on pycbc-code. The RPM repo on software.ligo.org was reorganized, breaking our unit tests.

Fix URL to lscsoft RPM

---

pycbc/io/hdf.py

It looks like check statement got added incorrectly which is preventing statmap from running atm.

fix error in dict array init logic

---

pycbc/waveform/waveform.py

This adds a prototype functionality to allow one to pull in waveform approximants from python codes outside of pycbc.
The method here is you would set an environement variable to let pycbc know which libraries have this copability. On the other side, the external library would provide the function to add itself to pycbc. I think this functionality is useful for both PE and searches. 
We've been getting some requests form external groups to make it easier to support their models without having to modify our code. This is an approach I think we can test with them.

add hook to allow getting waveforms from external libraries to pycbc

---

bin/minifollowups/pycbc_foreground_minifollowup
bin/minifollowups/pycbc_page_coincinfo
bin/workflows/pycbc_make_coinc_search_workflow
pycbc/workflow/minifollowups.py

A long-time action item from my to-do list, but one that I now think is needed:
This PR adds a new section 4.1 to the HTML results pages. This section will show minifollowups of all the loudest background events. This can be useful to see which outliers are still affecting the background after applying Denty bins. Single events will usually show up numerous times here (e.g. the loudest X background events often contain a single L1 or H1 event found in multiple time slides with different events in the other ifo). I catch this on the result page and just add a snippet of html saying "Event X was found in the next Y loudest events, but I'm not going to bother showing you the same event numerous times".
This one might be a little rough, so suggestions for cleaning up the code welcome here!

Background minifollowups

---

bin/minifollowups/pycbc_foreground_minifollowup

I accidentally removed a line from `pycbc_foreground_minifollowups` rendering that code currently broken. Here I fix it. As my penance I've added the missing help text for this option, and the surrounding command line options.

Re-add missing line

---

pycbc/psd/variation.py

The PSD variation statistic at the moment is slow because its recomputing the full interpolation every time that `new_find_trigger_value` is called (and it's called a lot!) If we swap to scipy, and cache the interpolation itself, the code is no longer slow.
At the moment this results in about a factor of 6 slowdown if using PSD variation, so I would encourage people testing this to incorporate this patch.
.... Maybe for safety I should add a test to recompute the interpolation if the psd_var object changes??

Optimize the PSD variation statistic

---

pycbc/detector.py

Without the cast, the cos can't process `lal.LIGOTimeGPS` type:
```
File "/.../python3.7/site-packages/pycbc/detector.py", line 141, in antenna_pattern
cosgha = cos(gha)
AttributeError: 'lal.LIGOTimeGPS' object has no attribute 'cos'
```
Error encountered working with python 3.7 conda based dist, pycbc installed from pip.

added casting to float

---

bin/pycbc_live
pycbc/events/stat.py

When (some of) the worker nodes think a detector is unusable, but the master node thinks the opposite, the detector is still reported as being active despite no triggers are produced from it. This patch ensures that the detector is reported as inactive when there are no (or partial) results from it.
Also fixes a harmless confusion between objects in different namespaces.

PyCBC Live: fix issue in how the detector state is reported

---

bin/workflows/pycbc_create_offline_search_workflow

add in check that the exclude_zerolag stage is not performed if only using 2 detectors

Remove exclude foreground from workflow if only one coincidence type

---

bin/hdfcoinc/pycbc_multiifo_dtphase
bin/hdfcoinc/pycbc_stat_dtphase2

This is a rewritten version of pycbc_stat_dtphase to handle multiple ifos. The storage format is different. It stores, time, phase and amplitude differences. It performs some internal smoothing of the pdf based on similar rules to the old pta. You can provide fixed relative sensitivities between the detectors. 
In the application, the intention is to rescale the SNRs based on the effective distance to also account for variation over time of the relative sensitivities. 
Example command line. 
python ./pycbc_stat_dtphase2 \
--ifos H1 L1 \
--relative-sensitivities 1 .8 \
--sample-size 2000000 \
--snr-ratio 4.0 \
--seed 10 \
--output-file statHL.hdf \
--smoothing-sigma 2 \
--verbose

add alternate pta maker script

---

bin/hwinj/pycbc_generate_hwinj

Previously waveform_low_frequency_cutoff option was ignored when
computing the SNR. This can be a problem for example for
waveform approximants that need to start at an earlier frequency
than what is used for SNR computation. The following command is an example:
```
pycbc_generate_hwinj --network-snr 25 --ra 1.01 --dec 0.34 --polarization 1.821 --mass1 80.0 --mass2 40.0 --spin1x 0.88 --taper TAPER_STARTEND --waveform-low-frequency-cutoff 15.0 --low-frequency-cutoff 30.0 --gps-start-time 1000000000 --gps-end-time 1000000128 --approximant SEOBNRv3 --inclination 0.367 --geocentric-end-time 1000000080  --instruments H1 L1 V1 --sample-rate 4096 --psd-model H1:aLIGOZeroDetHighPowerGWINC L1:aLIGOZeroDetHighPowerGWINC V1:AdVDesignSensitivityP1200087  --order pseudoFourPN
```
This patch simply …

Make pycbc_generate_hwinj not ignore an option

---

tools/docker_build_dist.sh

This adds the Cardiff Hawk cluster to the part of the activate script that adds the Intel MKL libraries.

Add Cardiff ARCCA Hawk Cluster to MKL setup

---

bin/workflows/pycbc_create_offline_search_workflow
bin/workflows/pycbc_make_coinc_search_workflow

The binned_hist (Denty Bins) on the summary pages are currently reading in all triggers after CAT_2. The "pruning" settings are used to try to prevent this plot from considering actual detections (as with the codes used to produce the actual fits). However, this can be dangerous, leading to cases where real coincident events show on the summary pages.
I'm going to enforce the rule here that all closed_box plots must use the closed_box veto if considering single-detector triggers. Single-detector detections might still show up on this plot (as they show elsewhere in the closed box), and the pruning settings might be used to remove those. But I think we must remove the chance of coincident triggers appearing here.

Summary plots must use closed_box veto

---

pycbc/inject/injfilterrejector.py

Following up an unrelated error report made me realise that `injfilterrejector` will generate the "short" injections (injections with a compressed representation) regardless of whether or not these are actually needed.
For instance if using the chirp-time window, you will not need the "short" injections, but these will be generated anyway. A small fix will stop this happening. Probably not important for anything, but it seems cleaner.

Don't generate short injections when not needed

---

pycbc/inference/sampler/base.py

PyCBC Inference has a `--force` option that is supposed to check if the output file exists, and raising an error if it does (unless the user supplies `--force`). However, currently, the check is done on the checkpoint file rather than the output file. This causes two bugs. First, the output file will be overwritten even if you have not supplied `--force`. Second, if an invalid checkpoint file exists, it will cause the code to quit unless `--force` is supplied. This isn't what we want. If an invalid checkpoint file exists, it should just be overwritten. This has caused issues when running in a dax. If the job fails before the first checkpoint, then on restart the job fails again because it finds a checkpoint file without anything in it (i.e., an invalid checkpoint) then raises an error if …

Fix issue with invalid checkpoint file raising error

---

bin/hdfcoinc/pycbc_coinc_findtrigs

Without this, some statistics can't rely on these parameters to be set in a consistent way. We should just pass it in the two ifo case, same as the multi-ifo case.

two ifo coinc should still pass ifos

---

bin/hdfcoinc/pycbc_multiifo_add_statmap

Small issue when running the mult-ifo workflow with two-ifos. Add statmap produces and invalid foreground_segs variable which fails later in the code. This occurs as np.sum does not guarantee output types, and in fact converts to a numpy array when you only give it one element in the original code.

add statmap doesn't work when using two ifos (in multi-ifo workflow). 

---

bin/minifollowups/pycbc_foreground_minifollowup
bin/minifollowups/pycbc_injection_minifollowup

timefreq and qscan plots were being shown as blank plots in the case where the -1 sentinel value was found, whether data was available or not
For example for a HL coinc, the V qscan and timefreq were blank, even if V was running but did not trigger
Given these changes the minifollowup workflow creation now takes the mean time from the other detectors, and tries to create the plots. If they fail, as the time is outside of analysis time in that detector, then the plot will simply not be made.
This is a point where I ask whether we would _prefer_ a blank plot to show definitively that there is no data (or a standard 'this IFO has no data" image?)
This PR helps address #2882

Injection and foreground minifollowups missing triggers/data

---

setup.py

An attempt at fixing #2927. Not tested; comments welcome.

Restrict SSE 4.2 flag to x86_64

---

tools/docker_build_dist.sh

This aims to fix the recent Travis failures caused because the `yum -y update` command was upgrading the `ligo/lalsuite-dev:el7` environment from EPEL 7.6 to 7.7, which broke the (current) state of the lalsuite software in that container. We should probably decide if this should be just a temporary work-around or a permanent change in philosophy.

Do not 'yum update' when building RHEL virtualenv in Travis

---

bin/pycbc_upload_xml_to_gracedb

Some minor changes are needed to the graceDB upload script. As well as fixing a bit of backwards incompatibility the main change is to add the "OFFLINE" tag to any upload from this script. I also add a `--production-server` option to ensure that an extra flag needs to be given if you want the event to appear on the production server rather than the playground server.

Update gracedb upload script

---

bin/hdfcoinc/pycbc_fit_sngls_split_binned

Basic pruning added to split binned histograms, at this point, simply takes the loudest trigger in each split, removes anything within specified window, and repeats this procedure as many times as specified
An 'outlier test' might be good to add, but I'm not sure of how best to do this
I have not set a 'maximum number to remove' flag as in the unsplit pruning procedure

Add pruning in to fit_sngls_split_binned

---

bin/hdfcoinc/pycbc_multiifo_add_statmap

Adding in Hierarchical Removal to the multiifo workflow
Summary of actions:
- Use triggers clustered over different combinations
- Separate the clustered triggers back into per-combination sets
- Find highest IFAR over all IFO combinations
- removes this from foreground and any triggers within time window from background
- Recalculate IFAR in both separated and combined cases
- Output foreground and background for each combination and combined at each HR stage
- Save HRed datapoints and output as main `foreground` dataset once HR complete

Hierarchical removal multiifo

---

pycbc/inject/inject.py
pycbc/strain/strain.py

Here is a proposal for adding the ability to control/override f_ref and f_final when doing injections from an XML file, which carries no f_ref and which may have a bogus f_final. After reviewing the current injection code path, I decided to add two arguments `--injection-f-ref` and `--injection-f-final`, both taking frequencies in Hz. This keeps the amount of code change to a minimum.
*Needs testing*.

Control injection f_ref and f_final from the command line

---

bin/plotting/pycbc_plot_vt_ratio

standard mchirp options were making the vt ratio comparison plots bunched up on one side - add in ability to use log x axis

add log-x option to plot_vt_ratio

---

pycbc/vetoes/chisq_cuda.py

This MR attempts to deal with one issue I have encountered when testing the CUDA implementation of the standard power-chi-squared test. Not uncommonly, there were larger than expected differences in chi-squared (a few to tens of percents) when comparing a CPU and GPU trigger, even though SNR and similar quantities were much closer.  There are several reasons for this, but one subset were traceable to differences in the exponential factor `exp(2*pi*freq_index*trig_index/N)`, especially when the index of the trigger is large.  
The problem is that the complex exponential is implemented via calls to the CUDA intrinsic `__sincos` function.  But that function becomes increasingly less accurate, particularly for argument reduction (the first stage in calculating sine and cosine: reduce the …

Change CUDA chisq to use more accurate phase calculation

---

bin/minifollowups/pycbc_page_coincinfo
bin/minifollowups/pycbc_page_snglinfo
pycbc/results/table_utils.py

Here is the code that I used to add `psd_var_val` to the results tables in my testing. While this can handle the case that this quantity is not computed, it will still appear in the tables (with the value of 0). As the table headers are hardcoded, I didn't see a nice way to stop this being displayed, other than moving the headers out of `pycbc/results/table_utils.py` and constructing them in the executables .... Maybe that's the correct approach anyway (or moving the entire computation *into* table_utils?? For now, this is here for comments!

Add psd var val to tables

---

pycbc/events/stat.py

This requires #2942, and adds the statistics needed for the 2-ogc analysis for both the full and bbh sub-space. In includes handling of the new pta statistic files.

add the new phase time statistics and boiler plate for 2ogc / 2ogc bbh statistics

---

pycbc/strain/strain.py

Addresses problems in issue #2979 
Perform down-sampling after injections - this means that the injections can be made up to the ring-down frequency in as many cases as possible
Note that in the zeroNoise case, the frequency is now hard-coded to 16384 for injection application, and it is then down-sampled. I don't see a way to avoid this, and it is returned to the sample rate that it would have been at a later point so should not make a significant difference

Changes to perform downsampling after injections in fake data

---

pycbc/transforms.py

This adds log and exponential transforms (which are inverse pairs) to the transforms module. These are useful if you want to use a prior uniform in comoving volume. Since range in values for comoving volume can vary by several orders of magnitude, it's best to sample in the log of the volume. This was tested and used in the 2-OGC PE runs.

Add log and exponent transforms

---

pycbc/events/coinc.py
pycbc/events/stat.py

Fixes #2983. Requires a change in the PTA histogram files such that their `stat` attribute lists the detectors to which they apply.

PyCBC Live: fix str/bytes error related to PTA files on Python 3

---

bin/hdfcoinc/pycbc_plot_throughput

This PR changes the summary in the throughput legend to show the harmonic mean of the templates per core for each IFO, rather than the arithmetic mean.  In general, for this measure of performance, the harmonic mean is more useful, as it better predicts the overall computing usage (estimated as the product of the total detector livetime and the number of templates in the bank, and then divided by the "average" templates per core). However, the difference has become much more pronounced in O3 for injection runs, now that we are sorting the bank by mchirp, as the injection rejector setting can cause some of the inspiral jobs to be very quick, and the mean templates per core can be more than an order of magnitude larger than the harmonic mean.

Switch throughput templates-per-core to show harmonic mean

---

bin/hdfcoinc/pycbc_plot_psd_file

Currently, `plot_psd_file` assumes that the PSD in a hdf file has been scaled by `pycbc.DYN_RANGE_FAC`. While this is true for searches, in inference files, the `pycbc.DYN_RANGE_FAC` is not applied. The result is that the plotted ASD is off by ~26 orders of magnitude (which makes it look like a PSD even though it's actually an ASD). This fixes that by adding a `dyn-range-fac` option to the command line. The default is to use `pycbc.DYN_RANGE_FAC`, so this requires no adjustments to the search workflows. For the inference workflows, one can now just add `dyn-range-factor = 1` to the plot psd section of the workflow config file.
This also gets rid of looking for `ifo_list` in the attributes. This was something that had been added for older style inference files, but no `ifo_list` attribute …

Fix plot psd for inference files

---

pycbc/types/array.py
pycbc/types/frequencyseries.py
pycbc/types/timeseries.py

This patch gets rid of this (new?) warning from the `.save()` method of some types:
```
[...]frequencyseries.py:429: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
f = h5py.File(path)
```
It also ensures HDF files are safely closed.

Fix HDF5 deprecation warning and ensure files are closed

---

bin/pycbc_live
bin/pycbc_optimize_snr
pycbc/io/live.py

Fix a few errors coming from the PyCBC Live SNR optimization code when running in Python 3.
* [HDF5 file being left open](https://stackoverflow.com/questions/26613570/hdf5-file-created-with-h5py-cant-be-opened-by-h5py)
* `LIGOTimeGPS` being multiplied by a float.
* Another case of `dict_keys` being indexed.

PyCBC Live: fix errors from SNR optimization in Python 3

---

bin/hdfcoinc/pycbc_multiifo_coinc_findtrigs

@ahnitz As you are aware, code used in LVC analyses is subject to an internal review process. One thing that will make review of the new multi-ifo code much easier is we can block off changes and show that they are working/give identical output as before.
Therefore I add the ability here for the new `coinc_findtrigs` code to output a file in the same format as the old code *if* there are only two detectors in play, and it's H1 and L1.
I emphasize that this is a temporary patch (and you can bug me if this doesn't get reverted in good time). It's also quite a minor patch, and doesn't interfere with running the new code. I hope it's acceptable to have this on master for a short time.

Allow output of oldformat files (for HL only)

---

bin/minifollowups/pycbc_page_coincinfo

This patch makes some improvements to the formatting of page_coincinfo. Most importantly it ensures that the IFO is listed in the case where no summary page links are given. This has been tested.
Fixes #2995

Formatting changes to page_coincinfo

---

Dockerfile
docker/.singularity.d/env/90-environment.sh
docker/etc/docker-install.sh

The primary change introduced in this PR is to add the OSG repo to the Docker container, and then using that to additionally install the `osg-wn-client` and `osg-ca-certs` packages into the container. This in particular pulls in globus tools, so that the container can invoke `gfal-copy` without needing it to be present on the worker node via CVMFS or some other source. Since the worker node environments are by default present in container execution (so various directories under `/cvmfs` may have been added to `PATH`, `LD_LIBRARY_PATH`, `PYTHONPATH` and others), this new addition is intended to be invoked by adding the following three lines to the condor submit file for any OSG job desiring to ensure that the containerized versions of these tools are used:
```
+InitializeModulesEnv = False …
```

Add OSG tools to docker container

---

bin/plotting/pycbc_plot_qscan

This input argument is needed for creation of fake strain, but is not included when running `pycbc.strain.insert_strain_option_group(parser)`
The other place this strain creation/argument is used is in pycbc_inspiral, which uses the input argument in other places, hence why is is not in the stain module option group
This change does not affect normal running, but fixes for fake data

qscans not working for fake data

---

docs/workflow/pycbc_make_coinc_search_workflow.rst

Per request, this MR updates the documentation for running PyCBC search workflows on the Open Science Grid.  All reference to PyInstaller bundles have now been removed (they have not existed for some time) and several other simplifications have been made. This PR also documents the arguments needed for `pycbc_submit_dax` to instruct the OSG wrapper script to start Singularity in a container with a clean environment.
The rendered version of these updated docs can be viewed [here](http://josh-willis.github.io/pycbc/latest/html/workflow/pycbc_make_coinc_search_workflow.html#running-on-the-open-science-grid).

Swap out Singularity for PyInstaller bundles in search workflow docs

---

bin/pycbc_live
pycbc/frame/frame.py
pycbc/io/live.py

* Make sure the low-frequency cutoff used to make the PSD is ok for all templates (fixes #2713).
* Improve followup plots in GraceDB (sort detectors alphabetically, show more PSD).
* Show GraceDB ping response when testing access.
* Shorten a very common log messange.

PyCBC Live: misc improvements

---

bin/minifollowups/pycbc_injection_minifollowup

For some injection populations the search is tuned to miss the very loudest things (e.g. IMBH because of autogating, or loud BBHs in the focused BBH search). In this case I don't want to see injection minifollowups of things I have tuned my search to miss. I want to understand why the quieter stuff was missed.
This adds an option to set a maximum decisive SNR option to the injection minifollowup code. Any injection whose decisive SNR is larger than this will not be followed up.

Add maximum SNR option for injection minifollowups

---

bin/hdfcoinc/pycbc_multiifo_coinc_findtrigs
pycbc/events/stat.py

So I basically want to be able to choose a limit on the mchirp when doing mchirp reweighting in the new OGC statistic class. Although I want this to be optional, and I want the variable to be the user's choice.
But I wanted to discuss first how best to implement this, and how to provide it on the command line. I would think to provide this through `**kwargs` to the stat function. But should we add a `--stat-kwargs max_mchirp:40 some_other_value:20` command line option to `coinc_findtrigs`? ... That seems to be the best way to do this IMO.

Setting a chirp-mass limit on the mchirp reweighting

---

pycbc/types/array.py
pycbc/types/frequencyseries.py
pycbc/types/timeseries.py

#2994 causes PyCBC Live's trigger files to be wiped when the last PSD is written to them. This change fixes that by opening the HDF file in append mode (the old default in `h5py.File()`) rather than write mode.

Use append mode when saving arrays and time/frequency series to HDF

---

pycbc/transforms.py

Does what the title says, adds the existing `MchirpEtaToMass1Mass2` transform to the list of all transforms so that it can be used as a waveform transform.

Add mchirp_eta_to_mass1_mass2 to list of all transforms

---

pycbc/filter/qtransform.py

From Python 3.7 StopIteration raises a Runtime Execution Error.
This broken qtransform.
Fix proposed in PEP479 implemented. (Change Rayse StopIteration() to retuirn)

StopIteration Fixed in qtransform

---

.travis.yml
companion.txt
docs/Makefile.gh_pages
docs/_include/_dict_to_rst.py
docs/_include/sampler_inheritance_diagrams.py

This should solve two issues we've had. Namely
1) Race condition between python3 and python2.7 pushing to gh-pages, prefer 2.7 one for now (both will still be built as part of testing, just not deployed).
2) Overwrite gh-pages history. This will keep the branch from blowing up to high diskspace requirements like we've seen in the past.

only deploy python3.6 webpage to gh-pages, overwrite history

---

bin/minifollowups/pycbc_page_coincinfo

Make page_coincinfo work in the general case
This is as full data foreground, full data background and injections all have different requirements and this seems the most general way to get them all to work, and for it to be obvious that the requested value does not exist

page_coincinfo to work in multiifo general case

---

bin/pycbc_optimal_snr
pycbc/inject/inject.py

Several little fixes to `pycbc_optimal_snr` prompted by the observation of a weird memory leak and subsequent digging into various scripts and functions.
* Add an option to choose the sorting of input injections. Sorting by time may help opening less PSD files, although it does not seem to matter much anyway.
* LALSimulation's `SimInspiralTaylorLength()` (used in the injection module) is much more complex than I thought. It does a numerical integration and seems to have a [memory leak](https://git.ligo.org/lscsoft/lalsuite/issues/224). Replace with a trivial call to `pycbc.conversions.tau0_from_mass1_mass2()`, which gives very close or systematically larger values.
* Avoid actually using multiprocessing when using a single core.
* Clean up code and fix an integer division.

Several fixes to pycbc_optimal_snr

---

bin/hdfcoinc/pycbc_multiifo_add_statmap

Until the changes in #3019, there was no need to have background_exc output from add_statmap, but using _exc ensures that no triggers which appear in zerolag coincs will show up in the background coinc followups
This change simply collates the background_exc from the exclude_zerolag stage and puts into the add_statmap output
Note that background_exc ifars are defined only within it's own ifo combination and are not recalculated

add_statmap outputs background_exc

---

pycbc/waveform/decompress_cpu.py

The arguments were being handed off in the incorrect order, causing CPU waveform decompression to fail.  This should fix that.
Assuming this causes no other problems, I will also want to make a point release after it is merged. Without it waveform compression and decompression are completely broken.

Swap around arguments inside of inline_linear_interp

---

bin/workflows/pycbc_create_offline_search_workflow

The issue comes from the assignment of the `inj_summ` variable in an if statement for handling injection files. If there aren't any injections then the workflow will try to give the injection summary list to the summary list when `inj_summ` hasn't been created.
Patch is just to add an if-else statement. Not the most elegant solution to fixing `pycbc_create_offline_search_workflow`. But now the workflow generates and passes with this small patch.

Injections are optional, fix inj_summ var

---

bin/hdfcoinc/pycbc_page_snrifar

This is a fix for #2966 
I assume that any changes to be made for the offline multi-ifo pipeline should be backwards compatible as well, is this correct?
For future reference, should I always request a reviewer or just leave this?

Added IFO information to title to make result pages clearer

---

bin/plotting/pycbc_plot_qscan

`pycbc_plot_qscan --help` currently says that the default low-frequency bound is "10", but it is actually 30 Hz. Given that modern template banks go quite below that, I am also lowering the actual default to 20 Hz.

Fix qscan default (and set to 20 Hz)

---

bin/pycbc_submit_dax

This PR removes implicit (i.e. undeclared) dependencies on `perl` and `perl-HTML-parser` by replacing those with calls to `python` (in the case of `HTML::Entities`) and `sed` (in the case of `perl -p`).
I have no idea how to test the swap to `python` for HTML entity conversions because I don't know what the typical inputs to that are.
This should fix errors running `pycbc_submit_dax` from a conda installation of `pycbc`.

Removed dependence on perl in pycbc_submit_dax

---

bin/pycbc_single_template

When using an injection as template, `pycbc_single_template` uses the arrival time for the detector provided by the `sim_inspiral` table. Unfortunately, depending on how the injections where generated, this field is not always populated. When it is zero, `pycbc_single_template` generates a very confusing error:
```
XLALGPSSetREAL8(): overflow [a large GPS time]XLAL Error - XLALGPSSetREAL8 (XLALTime.c:83): Input domain error
XLAL Error - XLALGPSDivide (XLALTime.c:308): Internal function call failed: Input domain error
File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-v1.15.0/bin/pycbc_single_template", line 285, in <module>
template = waveform.td_waveform_to_fd_waveform(td_template, length=flen)
File …
```

Make single_template work with sim_inspiral tables that have no end times

---

pycbc/strain/strain.py

It seems that the injection strain module was broken from this commit:
https://github.com/gwastro/pycbc/commit/84e8c92167f77f19bc83e08724b67492550911a9#diff-33e2f03c191ff5208a6cbe46ee68fad7
As I ran into following error while running pycbc_inference with a simulated BBH injection:
File "/work/sumit.kumar/src/ve/python3.6/pycbc_inference_dev/lib/python3.6/site-packages/PyCBC-1e0583-py3.6-linux-x86_64.egg/pycbc/inject/inject.py", line 855, in from_cli
if opt.injection_f_ref is not None:
I have fixed it as suggested by @cdcapano and tested with a simulated BBH injection.

Added Injection f-ref option to multi-ifo strain function

---

pycbc/workflow/core.py

Currently, `Workflow.save_config` opens the file handler to save the file in binary mode ("wb"). This causes the following error in python 3:
```
TypeError: a bytes-like object is required, not 'str'
```
This fixes this by just opening the file handler in normal write mode ("w"). I'm not certain why mode "wb" was used to begin with, but just using "w" seems to work fine.

Fix Workflow.save_config for python3

---

pycbc/_version_helper.py

I noticed that with Python 3 the git info is sometimes unpopulated:
```
>>> import pycbc.version
>>> pycbc.version.git_hash
''
```
This seems to happen due to a bytes/str confusion, which leads to an exception in `setup.py`. The exception is silently caught so we do not see it, and it causes the strings to be empty. This patch fixes the bytes/str confusion.

Fix empty git info when using Python 3

---

pycbc/types/array.py

This implements the negation operator so you can do 
x = -a
instead of the obtuse
x = -1 * a

allow for negation of pycbc types

---

pycbc/events/single.py

rate_louder is a FAR, and so trials factors should be multiplied, not divided

Trials factor was applied incorrectly for singles

---

Dockerfile

Our travis tests are all failing the `PYCBC_CONTAINER=pycbc_docker DOCKER_IMG=pycbc/pycbc-el7` test because the release of `setuptools 45.0.0` dropped support for Python 2.  Thus we cannot simply upgrade pip and setuptools in the Dockerfile.  As a workaround, this PR simply pins both setuptools and pip to working versions (pip has not yet shown a problem, but I went ahead and included it in the pin).
We should of course revert this as soon as we are able to drop python2 support ourselves.

Pin versions of setuptools and pip in Dockerfile to workaround dropped python2 support

---

bin/hdfcoinc/pycbc_multiifo_add_statmap

h_iterations counter is higher than number of hierarchical removals by 1 at the time that it is put into output files - this was not taken into account at the time of writing
(My fault for not properly testing previously - sorry!)

hierarchical iterations counter bug

---

bin/pycbc_live

Add in ability to get followup data from other interferometers but without recalculating the IFAR of a single detector event
Example output: https://gracedb-playground.ligo.org/events/T244462

add in followup data to live singles

---

bin/hdfcoinc/pycbc_fit_sngls_split_binned
bin/hdfcoinc/pycbc_page_ifar
bin/minifollowups/pycbc_single_template_plot

Three changes to fix the python3 offline workflow.
pycbc_fit_sngls_split_binned
- The "bbox_extra_artist" option didn't work in python3
- Changed so it is consistant in python 2 and 3
pycbc_page_far
- poly_between is not in matplotlib 3 (fill_between is equivalent and exists in matplotlib 2)
pycbc_single_template_plot
- convert from byte object to string

Python3 workflow fixes

---

pycbc/fft/fftw.py
pycbc/types/__init__.py
pycbc/types/aligned.py
pycbc/types/array.py
pycbc/types/array_cpu.pyx
test/test_array.py
test/test_frequencyseries.py
test/test_schemes.py
test/test_timeseries.py
tools/timing/fft_perf.py

The original motivation for sub-classing `ndarray` in this way was to allow checking that an array had sufficient alignment for SIMD vectorized operations without incurring the overhead of performing that calculation over and over.
Since we have moved to providing classes to implement our time-critical operations (e.g. FFT, correlation, peak-finding) we avoid this overhead simply by using the same arrays over and over, and only checking alignment at class instantiation. In the meantime, it is often inconvenient to have a subclass of ndarray, though arguably this is because other packages don't properly check class types via `isinstance`. However, we have no control over what other packages do, so I think for us it is better to eliminate this subclass.
I noted that at some point our SIMD …

Remove ArrayWithAligned

---

bin/pycbc_live
bin/pycbc_optimize_snr

* Do not steal CPU cores from the main search when doing the SNR optimization
* SNR optimization timeout is now configurable from the command line
* Minor fixes

Improve PyCBC Live SNR followup

---

pycbc/psd/variation.py

This PR changes the calculation of the PSD variation TimeSeries in the function `psd.variation.calc_filt_psd_variation` to work whenever possible with numpy arrays, rather than pycbc array types. A few corresponding compatibility changes are also introduced in other functions.  No attempt has been made to modify other, similar functions in the variation module, but as this is the function called by `pycbc_inspiral`, the priority was fixing it.
The need for the change is to allow this code to run when `pycbc_inspiral` is executed on a GPU. Because the `calc_filt_psd_variation` function is only called once, and involves calls to other functions only implemented on numpy arrays, it is both sufficient and simpler to force this function to do most of its work on the CPU, even when the matched …

Modify PSD variation calculation to use numpy

---

pycbc/inference/sampler/emcee_pt.py

This is a convenience modification. I've found that if you get the betas order wrong, emcee pt will happily accept it but produce nonsense results. The order it requires is always descending, so this just makes it so that we always presort to it's desired order.

enforce betas order required by emceept

---

pycbc/results/layout.py
pycbc/results/render.py
pycbc/results/templates/orange.html

To invoke multiple wells you need to use the 'unique' keyword argument with your layout command. Add  any string so it can make a new one.  To make collapseable, add the collapse=True keyword.

Allow for mutiple wells in pycbc results pages and allow them to be collapsable

---

bin/pycbc_optimal_snr
bin/pycbc_optimize_snr
bin/pygrb/pycbc_pygrb_pp_workflow
pycbc/__init__.py
pycbc/vetoes/bank_chisq.py
pycbc/workflow/core.py
pycbc/workflow/datafind.py

For the past year, I've been getting a bunch of annoying messages from matplotlib about finding fonts whenever I run any of the inference plotting codes with verbose on. It turns out the issue is that the `pycbc.init_logging` function sets the logging level to `DEBUG` if you pass `verbose=True`. At some point, matplotlib must of added the finding font messages at the DEBUG level. The problem goes away if you set the logging level to `INFO`.
So... this patch sets the initial logging level in `pycbc.init_logging` to `INFO` if `verbose=True` rather than `DEBUG`. I added an option `level` keyword argument if you want to set it to `DEBUG` instead. This is more sane I think, since it will result in all of our `logging.log` messages to be printed without all the extra crud.

Silence annoying matplotlib messages

---

bin/pycbc_live

This applies the fix from https://github.com/gwastro/pycbc/blob/29822cc643def18020ba327d5a0aafd17b20665b/bin/pycbc_live#L222
To the singles followup data in
https://github.com/gwastro/pycbc/blob/29822cc643def18020ba327d5a0aafd17b20665b/bin/pycbc_live#L339
Testing will be started momentarily
#3088

Fix delta_t in singles followup data

---

bin/pycbc_live
pycbc/events/single.py

When single detector background is enabled, certain options are required. This change means that they are checked for before going into the main part of the live code
Another option would be to give defaults to single_reduced_chisq_threshold, single_duration_threshold and single_newsnr_threshold. But the fits file would still need checking for
I should check that we are happy to have a default value --sngl-ifar-est-dist of conservative?
(First commit can be ignored - reusing branch for previous PR)

Input sanitation for live singles options

---

pycbc/workflow/configuration.py

Currently, if you use `config-overrides` on the command line to change the value of an option in a config file, you cannot set values that have colons in them. This is problematic if you want to set a value that has colons in it; e.g., if you wanted to change the frame type used in a config file:
```
--config-overrides data:frame-type:H1:LOSC L1:LOSC
```
This is because the option uses colons to separate the section, option, and value. Using a colon is fine for splitting the section and option, since these two cannot include colons. The main issue is that `split(':')` is being used to parse the option. If the value contains a colon, the parser will split the value up before. So in the above example, `WorkflowConfigFile` gets `('data', 'frame-type', 'H1', 'LOSC L1', 'LOSC')` for the …

Allow values to have colons in config overrides

---

pycbc/inference/models/__init__.py
pycbc/inference/models/relbin.py
pycbc/waveform/spa_tmplt.py
pycbc/waveform/spa_tmplt_cpu.pyx

This implements a relative likelihood model according to the method introduced in https://arxiv.org/abs/1806.08792. The model uses a fiducial waveform whose parameters are known to be near the peak of the likelihood, and template waveform likelihoods are calculated relative to this fiducial waveform.
Currently the fiducial and all template waveforms are generated using the `SPAtmplt` approximant, and this patch makes necessary modifications to the `SPAtmplt` code to allow evaluation at specific frequencies which are provided as an input argument. Support for other approximants can be added in a future patch. 
Fiducial waveform parameters should be supplied in the `[model]` section of the inference config file, e.g.:
```
[model]
name = relative
low_frequency_cutoff = 20. …
```

Implement relative likelihood model

---

pycbc/inference/models/data_utils.py

Currently, running inference without explicitly providing `psd-start-time` and `psd-end-time` in the `[data]` section of the config file fails with the following error:
```
File "/home/daniel.finstad/opt/pycbc-dev/bin/pycbc_inference", line 123, in <module>
model = models.read_from_config(cp)
File "/home/daniel.finstad/opt/pycbc-dev/lib/python2.7/site-packages/pycbc/inference/models/__init__.py", line 175, in read_from_config
return models[name].from_config(cp, **kwargs)
File "/home/daniel.finstad/opt/pycbc-dev/lib/python2.7/site-packages/pycbc/inference/models/gaussian_noise.py", line 706, in from_config
opts = data_opts_from_config(cp, data_section, flow)
File "/home/daniel.finstad/opt/pycbc-dev/lib/python2.7/site-packages/pycbc/inference/models/data_ut …
```

Check for psd start/end times in dict values

---

pycbc/inference/sampler/dynesty.py

This adds the ability to pass additional arguments from the config file to dynesty to help configure how it will run.

allow to pass initialization args to dynesty

---

pycbc/inference/models/data_utils.py
pycbc/inference/models/gaussian_noise.py

Following up #3091: this writes the analyzed detectors, analysis segment, and PSD segment to the inference output file's `attrs`. Currently, this information isn't being saved anywhere, making it difficult to know if the PSD times were shifted or not, and if so, to where. Also, without the the analyzed detectors in the attrs, it is impossible to know which detectors were used if a posterior file is created with the `data` group.
In the process, I had to break up the `data_from_config` function into a few different functions. That should make code climate more happy anyway.
I've also added more documentation to the `GaussianNoise.from_config` function.

Write analysis and psd segments to inference file

---

pycbc/inference/sampler/base.py
pycbc/inference/sampler/base_mcmc.py
pycbc/inference/sampler/cpnest.py
pycbc/inference/sampler/dynesty.py
pycbc/inference/sampler/multinest.py

This patch is reviving #2836 which I'm not able to re-open for some reason. Additional changes made here address the comments by @cdcapano on that PR:
- `setup_output` has been made an abstract method of `BaseSampler` and its current functionality moved to a standalone convenience function in `base.py`
- `setup_output` methods have been added to `BaseMCMC`, `CPNestSampler`, and `DynestySampler` which call the new standalone function
- the `setup_output` method of `MultinestSampler` now manages the master process check and references the standalone function

Allow multinest to work with mpi

---

pycbc/inference/models/gaussian_noise.py
pycbc/inference/models/marginalized_gaussian_noise.py

This makes the normalization term that was introduced in #2795 optional, as it sometimes can cause numerical issues for nested samplers. By default, the normalization is set to False now. To turn it on, you set `normalize =` in the model part of the configuration file.
This also makes it so that the original data is stored to the output file, rather than the whitened data. It also fixes some documentation issues that were introduced in #2795.

Make normalization term optional and save data instead of whitened data

---

pycbc/inference/models/base_data.py
pycbc/inference/models/gaussian_noise.py
pycbc/inference/models/marginalized_gaussian_noise.py
pycbc/inference/models/relbin.py
pycbc/inference/models/single_template.py

Fixes the `SingleTemplate` and `RelativeSPA` models for the recent changes to how data is loaded. A `BaseGaussianNoise` class is introduced.
The `from_config` (which includes loading data) and everything related to setting up the inner product weight and calculation of the noise log likelihood is moved to `BaseGaussianNoise`. The `_loglikelihood` function is also implemented, as the difference between `_loglr` and `lognl`. A `_loglr` function is not implemented. The idea is that anything that assumes stationary Gaussian noise for the noise model of the (GW) data should inherit from this class, and implement there own `_loglr` function (since that is dependent on the signal model). `GaussianNoise`, `MarginalizedPhaseGaussianNoise`, `SingleTemplate`, and `RelativeSPA` now inherit from …

Add BaseGaussianNoise model to fix SingleTemplate and RelativeSPA

---

pycbc/transforms.py

This allows the name of the parameters used for mass1, mass2, mchirp, and q for the `MchirpQtoMass1Mass2` transform (and inverse) to be an option set in the configuration file. This is needed to sample in source masses instead of detector frame masses (in which case the prior parameter is something like `srcmass(1|2)` instead of `mass(1|2)`).
Default is to use the standard parameter names, so no changes need to be made to the standard config files.

Optional arguments in mchirp, q <-> mass1, mass2 transform

---

docs/inference.rst
examples/inference/gw150914/data.ini

This is a minor fix in inference documentation for GW150914 example. The downloaded frame files and channel names were not in sync.

Fixed a minor issue with frame file names in documentation

---

bin/inference/pycbc_inference_table_summary

Changes `pycbc_inference_table_summary` so that it prints out the credible interval (as `{50}^{+95}_{-5}`, as is done in plot posterior), maximum likelihood, and maximum posterior values. Also adds the option to print off metadata from the file's attrs. Example:
```
pycbc_inference_table_summary \
--input-file H1L1V1-EXTRACT_POSTERIOR_150914_09H_50M_45UTC-0-1.hdf \
--output-file ~/WWW/scratch/prs/update_table_summary/150914_test.html \
--parameters mass1 mass2 mchirp \
--print-metadata 'analyzed_detectors:Analyzed Detectors' \
--verbose
```
Yields:
https://www.atlas.aei.uni-hannover.de/~work-cdcapano/scratch/prs/update_table_summary/150914_test.html

Update table summary

---

pycbc/workflow/configuration.py
pycbc/workflow/core.py

As discussed in #3101, the `WorkflowConfigFile` class currently has two methods (`from_args` and `from_cli`) that do the same thing: parse command-line options. There is also a method (`add_config_opts_to_parser`) that is partial copy of `add_workflow_command_line_group`. This patch removes `from_args` in favor of `from_cli`. Although `from_args` is the older function, it isn't consistent with PEP8, and it does checks that are already done in the `__init__` function. This patch also gets rid of the `add_config_opts_to_parser`, which isn't being used by anything.
@spxiwh I know you had suggested renaming `from_cli` to `from_args`. However, grepping the repository, I found that `from_args` is only used in one place (in `workflow.core`), which I've updated. Calling it `from_cli` is more …

Remove redundant functions in workflow config

---

pycbc/workflow/segment.py

The new segment interface needs a way to reuse existing SCIENCE / VETOES xml files and not to try to reproduce them from inputs, either a veto-definer or from LOSC. (Rerunning these might not always give you what you expect, so direct reuse of output files is the best way to ensure reproducibility). 
This has been tested and works. If you choose the source of this information to be `file` it will access for that location/URL and copy to the expected output location.

Allow option to reuse SCIENCE/VETOES xml files

---

bin/pycbc_make_skymap
tools/pycbc_test_suite.sh

Added a new executable `bin/pycbc_make_skymap` that quickly produces sky localization given a the time, masses and spins of a trigger by utilizing a single template matched filter on strain data from a number of detectors. The sky localization is produced from the resulting SNR time series using BAYESTAR and therefore the user requires `ligo.skymap`installed in their environment. The script outputs a .png file and a .fits file of the skymap as well as an .xml file containing the SNR timeseries.

Added pycbc_make_skymap

---

bin/inference/pycbc_inference_plot_inj_recovery
bin/inference/pycbc_inference_plot_movie
bin/inference/pycbc_inference_plot_posterior
bin/inference/pycbc_inference_plot_samples
pycbc/inference/io/__init__.py

Currently, some of the plotting codes in the inference module try to apply transforms automatically to add some common cbc parameters if they do not exist in an input file, such as `mchirp` and `chi_eff`. The original intent was to save on having to write out functions on the command line when creating plots. However, this has led to a number of issues if you use anything but a standard CBC analysis. It's also impossible to know what transforms have been applied and what haven't, leading to confusion as to what should be called as a function and what should be called as an array. 
For example, the `--file-help` message in `pycbc_inference_plot_posterior` tells you that you can use functions in the conversions module on any of the parameters in your file. One of the functions is `chi_eff`. …

Remove automatic transforms when loading results

---

bin/pycbc_live
bin/pycbc_optimize_snr

Some improvements to comments on the logs of uploaded G events. Add explanation of which G events result from coincidences and which ones from single detectors. Link original and SNR-optimized G events with actual anchors and both ways.
Also includes some code cleanup.
Needs testing.

PyCBC Live: add more info to GraceDB log

---

pycbc/inference/io/base_mcmc.py
pycbc/inference/sampler/base_mcmc.py

Currently, the number of effective samples that exist after a checkpoint are being underestimated for MCMC samplers when max-samples-per-chain is used. This causes the sampler to run longer than it needs. The underestimation can be up to a factor of 2.
The reason for this is that the autocorrelation time (ACT)  is being overestimated. The ACT is the autocorrelation length times the thinning interval used to store samples; i.e., it's the number of iterations the sampler needs to run for to get a new independent sample (whereas the autocorrelation _length_ is the number of _thinned_ samples you need to skip, where the thinning interval is the one used for storing samples to the checkpoint file). When the ACT is calculated after a checkpoint, the method `get_thin_interval` is used to get the …

Fix effective number of samples estimate

---

pycbc/inference/models/base.py
pycbc/inference/models/base_data.py

This delays applying waveform transforms until either `loglikelihood` or `loglr` is called.
Currently, both sampling and waveform transforms are applied as soon as new parameters are set. If the sampler stepped into an unphysical region this can result in garbage parameter values. The prior should rule those points out. However, since the waveform transforms are applied before the prior is evaluated, a bunch of warning messages may be printed in the mean time. This often happens when sampling uniformly in comoving volume -- the sampler can easily step to unphysically large redshifts, resulting in a bunch of repeated messages to the user to call God if they want to know the luminosity distance (I thought it was funny when I wrote it...). Worse, if a function used in a waveform transform …

Delay applying waveform transforms

---

bin/pycbc_submit_dax

This PR patches `pycbc_submit_dax` to add `$@` to the helper scripts that it writes, allowing users to add arbitrary extra (optional) arguments when calling, e.g. `./status`.

Allow user to pass extra arguments to start/stop/status/debug scripts

---

bin/inference/pycbc_inference_plot_posterior

Currently, if you are running `plot_posterior` on a posterior file in which some parameters have been renamed or mapped to new parameters from what they were originally, you cannot plot the prior. The problem is the prior samples are drawn from the configuration file, which will only give you samples in terms of the original variable params. This fixes this by using the `remapped_params` attribute in the posterior file's `attrs` to transform the prior samples into the same parameter space as the posterior samples.
Example: in the 2-OGC runs, the masses were called `srcmass1` and `srcmass2` in the prior. For the posterior files that were releases, these were renamed to `mass1` and `mass2`. Consequently, if you try to plot the prior using the posterior file, you get:
``` …
```

Apply remapped params to prior in plot posterior

---

bin/pycbc_live
pycbc/io/live.py
pycbc/mchirp_area.py
pycbc/results/color.py

Adding code to calculate source probabilities from chirp mass and effective distance

Add calculation of source type probabilities to PyCBC Live

---

bin/pycbc_copy_output_map
bin/pycbc_stageout_failed_workflow

Given a workflow directory look at the main map file and stage-out any files that exist with non-zero size.
This is useful if one type of injection fails (as was the case recently with SpinTaylorT2) and many of the completed inspiral jobs are therefore never staged out.
Copy the output map of a workflow to a new file, with options to copy subsets of files (eg. inspirals) and to check that the files exist.

Add utility scripts to stage out a failed workflow and copy the output map

---

docs/inference/examples/bbh.rst
examples/inference/priors/gw150914_like.ini
examples/inference/single/single.ini
pycbc/inference/models/data_utils.py
pycbc/inference/models/gaussian_noise.py
pycbc/workflow/configuration.py

This switches the [model] low / high frequency cutoff options to work like multi-det options. At the moment they behave in their own special way and you can't set a global value for all ifos either. 
@spxiwh I've added a method to the configparse to return an option parsed through the cli methods. Does this make sense there? I think it does, but would like your check over. 
@cdcapano I've updated the examples, have I missed anywhere else? I've tested on the single template code to make sure it is setting the options appropriately if you are just setting a blanket for all ifos or setting each ifo separately. If you forget an ifo, but have set another, it will also produce an error.

switch to multidetoptions for low / high frequency cutoff model options

---

pycbc/inference/sampler/emcee_pt.py

Emcee pt does not store blob data. As a result, the only statistics that are available to be saved when an inference run finishes is the loglikelihood and logprior, as emcee pt knows them. The problem is if you used sampling transforms, the log prior will have a log jacobian included in it which is not recorded to file.  This means that when you get the maximum posterior point, it will be wrong, since you should include the log jacobian when calculating it.
This fixes that by calculating the logjacobian for all points and writing them to the output file before exiting. The step is done during the `finalize()` method, so it does not slow down checkpointing.

Correct jacobian for emcee pt

---

pycbc/distributions/arbitrary.py

This adds a `datagroup` option to the `FromFile` distribution to specify which group in hdf file to get samples from. (Currently, it tries to get samples from the top level.) By setting this argument to `samples`, you can use posterior files produced by `pycbc_inference_extract_samples` for the `FromFile` distribution. This allows the posterior from one event to be used as a prior for another.
This also fixes a python 3 bug in the `Arbitrary` distribution that was discovered when testing this.

Allow FromFile distribution to use posterior files

---

bin/inference/pycbc_inference_extract_samples

When `pycbc_inference_extract_samples` is used to combine multiple files, it will check that some of the top-level `attrs` are the same between the combined files. This can fail if an attr is an array in which order doesn't matter. That happens with the `sampling_params`: because the parameters are stored in memory as a dictionary, the order they are written to the file is arbitrary.
This fixes that by sorting all arrays stored in the `attrs` when comparing them.

Sort attr arrays before comparing them in extract_samples

---

pycbc/types/array.py

I was investigating some slow parts of pycbc inference during the initialization. 
There was a code that did this
```
f = h5py.File('./file.hdf')
f['something'] = MY_PYCBC_TYPE
```
This looks like a good patter, and we *want* people to do it this way as opposed to constantly converting types. Turns out the issue it was falling back to getitem to convert it to a numpy array. However, there is a way to avoid this by further hooking into numpy's support with an __array__ method. 
Speeds up part of pycbc inferences initialization by two orders of magnitude (the part where it is writing data / psds to the output file).

make it easier to conver to ndarray from pycbc array: speeds up a bunch of things!

---

bin/inference/pycbc_inference_plot_movie

Plot movie doesn't work if you provide frame number, due to the thinning on disk. This fixes that, and also ensures that you don't get errors when providing some values of frame step. It also changes "--start/end-sample" to "--start/end-index", as that is what you actually provide: an index of the samples to retrieve from the file.
Examples:
`pycbc_inference_plot_movie --input-file H1L1V1-INFERENCE_150914_09H_50M_45UTC-5-1.hdf --parameters 'srcmass1:$m_1$' 'srcmass2:$m_2$' --plot-scatter --plot-marginal --z-arg snr --movie-file ~/WWW/scratch/prs/fix_plot_movie/test_frame_number.mp4 --output-prefix frames/frame --cleanup --frame-number 30 --verbose`
Output: [test_frame_number.mp4](https://www.atlas.aei.uni-hannover.de/~work-cdcapano/scratch/prs/fix_plot_movie/test_frame_number.mp4) …

Fix plot movie

---

pycbc/workflow/configuration.py

Currently, when you initialize a `WorkflowConfigParser` it will automatically (and silently) copy the config file to the current working directory. This is done by the call to `resolve_url` that occurs in the `__init__`. While this make sense for remote files, it can lead to unexpected files getting created if the file exists locally.
This can be problematic when doing inference-related things. `WorkflowConfigParser` is used extensively throughout the inference package for specifying priors, models, samplers, etc. If you run `pycbc_inference` and point it to a configuration file not in the CWD, you'll get a copy of the file in your CWD which is never used for anything. That can be confusing. For example, it's happened to me where I edited the CWD copy after an initial inference run, …

Don't automatically copy config files

---

bin/inference/pycbc_inference_plot_samples
bin/workflows/pycbc_make_inference_plots_workflow
bin/workflows/pycbc_make_inference_workflow
pycbc/workflow/configuration.py
pycbc/workflow/core.py
pycbc/workflow/inference_followups.py

This updates `pycbc_make_inference_workflow` for the recent changes to `pycbc_inference` in which data is loaded from the inference config file. It also adds a number of improvements to the workflow including:
* simplifies the options needed to be provided to `pycbc_make_inference_workflow`;
* allows for multiple events to be analyzed at once by providing `[event]` sections in the workflow config file;
* adds creation of posterior files from the samples files;
* allows for multiple runs on the same event to be analyzed at once (with the results combined into a single posterior file);
* adds jobs to create `.fits` files and sky maps (python 3 only);
* overall cleanup of the results page;
* fixes a number of issues with the workflow (such as how plots are named);
* makes sampler-specific …

Update inference workflow

---

pycbc/inference/io/__init__.py

If you try to use an inference plotting program like `pycbc_inference_plot_samples` in python 3 on samples file that was created in python 2, you'll get an error if you do not provide any parameters. In that case, the command-line parser tries to get the parameters to load from the file's `variable_params` attribute. If the file was created in python 2, `variable_params` will return a list of bytes objects instead of a list of strings when run in python 3. This fixes that issue by trying to decode the bytes into strings before returning the parameters list. If the parameters are already strings (as they are if the file was created in python 3), then an AttributeError is raised by `decode`; in that case, the code just continues as-is.

Allow parameters to be read from py2 inference file in py3

---

bin/workflows/pycbc_make_inference_workflow
pycbc/workflow/jobsetup.py

In #3140, I inadvertently removed the condor checkpointing for inference jobs that was implemented in #2596. When setting up the inference nodes, I used `core.Executable`. I didn't realize there was a `PycbcInferenceExecutable` class in `jobsetup.py` that had extra things added to its `create_node` function to alert condor about the checkpoint file. This switches back to using that class in `jobsetup.py`, and updates that class to remove data-related things that are no longer set on the command line.

Restore condor checkpointing in inference

---

pycbc/events/veto.py

Numpy hstack is giving a FutureWarning that generators will not be allowed as input - this changes the input to hstack from a generator to a list

numpy hstack FutureWarning fix

---

bin/pycbc_live
bin/pycbc_optimize_snr
pycbc/io/hdf.py
pycbc/mchirp_area.py

Currently the source classification in PyCBC Live is only performed for triggers resulting from a two-detector coincidence. This PR extends it for the triggers resulting from the SNR maximization followup (`pycbc_optimize_snr`) as well as single-detector triggers (`check_singles()` in `pycbc_live`).

Extend source classification to all kinds of GraceDB uploads

---

bin/workflows/pycbc_create_offline_search_workflow

So that changes can be made easily to config for all combinations within a certain number of detectors, separate the ordered ifo list from the number of detectors when creating tags

Separate the ordered ifo list from the number of detectors in tags

---

bin/inference/pycbc_inference_extract_samples

Currently, `pycbc_inference_extract_samples` will only write out the samples group if a posterior is extracted from multiple files. This means you lose the `data` and `injections` in the posterior file if you do a run which combines results from multiple files. That prevents you from using plotting programs (like a PP test) that need the injection data to be present in the posterior file.
This fixes that by only skipping the `sampler_info` group when multiple files are provided. The `data` and `injections` are taken from the first file. No attempt is made to check that they are the same in this case, but the user is warned about that in the help message. If someone doesn't want that, they can always explicitly not write those groups using the `--skip-groups` option.

Keep groups when extracting posterior from multiple files

---

bin/inference/pycbc_inference
pycbc/inference/sampler/base.py
pycbc/inference/sampler/base_mcmc.py
pycbc/inference/sampler/cpnest.py
pycbc/inference/sampler/dynesty.py
pycbc/inference/sampler/emcee.py
pycbc/inference/sampler/emcee_pt.py
pycbc/inference/sampler/multinest.py

The initial condition for samplers at the start has been moved from pycbc_inference module to set_initial_condition function in BaseMCMC class. This will help in setting up initial condition for different samplers in their own way.

Setting initial conditions from checkpoint files

---

bin/hdfcoinc/pycbc_plot_psd_file
bin/inference/pycbc_inference_plot_movie
bin/inference/pycbc_inference_plot_posterior
pycbc/results/plot.py

This adds functions to `pycbc.results.plot` that will allow you to set the style used by matplotlib. 
Matplotlib provides a bunch of different style settings; see [here](https://matplotlib.org/3.1.1/gallery/style_sheets/style_sheets_reference.html) for a reference. This can be useful if you'd like to make colorblind-friendly plots, or want a black background for a talk.
To add this feature to a program, you add the option to the program's argument parser via:
```
pycbc.results.add_style_opt_to_parser(parser) 
```
This will add a `--mpl-style` option. After parsing the command line, tou then add:
```
pycbc.results.set_style_from_cli(opts) 
```
That will update matplotlib's `rcParams` with the requested style. If the `mpl-style` isn't set, it will just use the default (leaving things …

Add functions to set matplotlib style

---

bin/inference/pycbc_inference_extract_samples
pycbc/inference/io/__init__.py

Currently, if you provide a `--parameters` option to programs that use `pycbc.inference.io.ResultsArgumentParser`, then only the parameters that are listed will be loaded. This patch adds the ability to also pass a wildcard (`'*'`). If that is given, then all other parameters not listed will also be loaded. This is particularly useful for extracting posteriors, since you may want to make mass1 bigger than mass2, or add mchirp and q, and don't want to remember all the other parameters to list.
Example, given this samples file:
```
[cdcapano@atlas8 bbh-injection]$ h5ls inference.hdf/samples
coa_phase                Dataset {2, 1000, 6/Inf}
dec                      Dataset {2, 1000, 6/Inf}
delta_tc                 Dataset {2, 1000, 6/Inf}
distance                 Dataset {2, 1000, 6/Inf} …
```

Add wildcard to parameters option

---

bin/hdfcoinc/pycbc_page_ifar
bin/hdfcoinc/pycbc_page_snrifar
bin/hdfcoinc/pycbc_page_snrratehist
bin/inference/pycbc_inference_plot_thermodynamic_integrand
bin/plotting/pycbc_banksim_plot_fitting_factors
bin/pycbc_make_banksim
test/test_lalsim.py

TexLive is extremely hard to build and distribute alongside other projects, and is not supported by Anaconda or Conda-forge to the level required for Matplotlib. This PR removes the remaining `rcParams['text.usetex'] = True` settings to remove the LaTeX dependency from PyCBC.

Remove usetex from remaining plotting scripts

---

bin/inference/pycbc_inference_plot_inj_recovery
bin/inference/pycbc_inference_plot_pp
bin/inference/pycbc_inference_pp_table_summary
pycbc/inference/io/__init__.py
pycbc/inference/option_utils.py

In an inference file, the injection parameters may not be the same as the samples. For example, if you specified the injection's spin parameters in cartesian coordinates, but you used a prior uniform in spherical coordinates, the samples will have `spin1_(a,azimuthal,polar)` while the injection will have `spin1(x,y,z)`. Or, say you added an mchirp column to the samples in a posterior file; the injection group will still only have `mass1` and `mass2`. This is problematic for plotting results in which you want to compare the injected value to the recovered. It particularly a problem for PP tests, where you need to know which injection parameters correspond to which samples.
This adds an `--injection-samples-map` option which allows you to specify a mapping between injection and samples …

Option to map injection parameters to inference samples

---

docs/workflow/datafind.rst
pycbc/frame/frame.py
pycbc/workflow/datafind.py
requirements.txt
setup.py

This PR fixes #2916 by patching `pycbc.frame.frame` to use `gwdatafind`, rather than the (long deprecated) `glue.datafind` module.

Use gwdatafind instead of glue.datafind

---

pycbc/inference/sampler/base.py
pycbc/inference/sampler/cpnest.py
pycbc/inference/sampler/dynesty.py
pycbc/inference/sampler/multinest.py

As caught in Issue #3160, PR #2948 introduced a bug into setting up the multinest sampler. This fixes that. Also removes unused `setup_output` class methods in other samplers, and removes the `force` keyword argument in the `setup_output` function in `pycbc/inference/sampler/base.py`, since that isn't used by anything anymore.

Fix setup_output calls

---

pycbc/inference/sampler/__init__.py

@cdcapano Sorry, I missed this before, but the changes to add epsie support added it as a hard requirement. We should try to avoid this for to many things. This adds in the minimal protection to ensure epsie isn't required just for module support.

don't hard require epsie

---

companion.txt
examples/inference/single/single.ini
pycbc/inference/io/__init__.py
pycbc/inference/io/ultranest.py
pycbc/inference/sampler/__init__.py
pycbc/inference/sampler/base_cube.py
pycbc/inference/sampler/dynesty.py
pycbc/inference/sampler/ultranest.py

This adds minimal support for ultranest (https://github.com/JohannesBuchner/UltraNest). 
Does not include support for checkpointing, configuring ultranest, or really much except running the sampler in default mode. 
It works similarly to dynesty, so adding support is very similar. 
Why ultranest? 
Well, see the docs https://johannesbuchner.github.io/UltraNest/. It seems to include a lot of the latest advancements in sampling (or at least more recent than many other packages) and can target final error uncertainties or desired number of independent samples (not actually supported in this patch). 
It's also by someone who has developed a version of this sampler and written papers on it for years and is the author of pymultinest as well. This seems to be his most actively developed sampler …

add very basic support for ultranest sampler

---

pycbc/inference/sampler/base_cube.py

This is a minor modification. Both Dynesty and Ultranest do not support sampling transforms, therefore I modify the ValueError message to make it more accurate.

make the ValueError message more accurate by including dynesty

---

bin/pycbc_banksim

I found a couple errors after trying `pycbc_banksim` on Python 3. This patch fixes them and removes a bunch of unused imports.

Fix pycbc_banksim for Python 3

---

pycbc/inference/io/__init__.py

Makes it so that `EpsieFile` will only be imported into the `inference.io` namespace if epsie is installed. This should fix #3178 .

Optionally import epsie file

---

pycbc/inference/io/__init__.py
pycbc/inference/io/base_hdf.py

The dump and load state functions that are in epsie are very useful for other samplers too. This creates a local copy of those functions in `inference/io/base_hdf.py` (and also promotes them to the `inference/io` namespace, so that other samplers can use them without having to depend on epsie being installed.

Add dump/load state functions from epsie

---

bin/inference/pycbc_inference_plot_inj_recovery
bin/pycbc_create_injections
bin/workflows/pycbc_make_inference_inj_workflow
bin/workflows/pycbc_make_inference_plots_workflow
bin/workflows/pycbc_make_inference_workflow
pycbc/inject/inject.py
pycbc/workflow/core.py
pycbc/workflow/inference_followups.py
pycbc/workflow/jobsetup.py
pycbc/workflow/pegasus_workflow.py

This updates the `inference_inj` workflow for the new inference syntax (with the data in the config file), and to bring it in line with the syntax of the inference workflow. As before, the inj workflow supports either generating injections on its own (done by setting the `--ninjections` argument) or being given an injection (done by setting `--injection-file`). The PP test is now optional; it will only be done if the `executables` section includes `pp_summary_table`. The results of the PP test go in their own tab in the results page.
Examples:
* [injections generated from the inference config file](https://www.atlas.aei.uni-hannover.de/~work-cdcapano/scratch/prs/update_pp_workflow/py36_pp_quick_test6_output/html/)
* [using a provided injection …

Update pp workflow

---

bin/minifollowups/pycbc_page_coincinfo
bin/minifollowups/pycbc_page_snglinfo
pycbc/results/followup.py

Add in a link to results pages which links to a search on GraceDB for superevents 3s around a single or coinc time in snglinfo and coincinfo
Note that it is possible to include this as a gracedb api search within python, but requires grid proxy credentials, so is not useful when using --no-grid with pycbc_submit_dax. I couldn't get it to work within the workflow either (standalone worked fine, within workflow didn't work) - I can add in this as an attempt to search but if the link fails then it falls back to the search, but thought this was cleaner for now

Add in Gracedb search functionality to results page

---

pycbc/inference/models/data_utils.py

A check for psd_inverse_length was not qualified by detector name in `pycbc.models.data_utils.data_opts_from_config`, which resulted in the test always passing.
This PR fixes that.

Minor bugfix in data opts reading from config

---

pycbc/workflow/minifollowups.py

The template fitting part of the workflow allows an option to not do it at all (e.g. if using new_SNR). However, this was broken by recent changes in minifollowups. This fixes that. In particular `statfiles` being an empty list is a valid input, but should not create a command line call to the executable.
The context here is to try to stand-up a test workflow using a short amount of data, that can be run end-to-end as close to production workflows as possible. As the `FIT_BY` codes will not do useful things, we need to turn them off in this example.

Allow FIT_BY_XXX files to be bypassed

---

bin/workflows/pycbc_create_offline_search_workflow
bin/workflows/pycbc_make_coinc_search_workflow
pycbc/workflow/coincidence.py
pycbc/workflow/core.py
pycbc/workflow/minifollowups.py
pycbc/workflow/plotting.py
pycbc/workflow/psdfiles.py

I wanted to have a pass through the new search workflow, as I was noticing from much of the file-naming that in a number of cases tags are duplicated etc. There's also some places where lists are currently being used where the new workflow demands a single file (e.g. template bank and veto files)
I just want to make a pass through and clear this up before we start thinking about removing the old workflow. I'm going to do this in stages, and show the changes for everything up to generation of the FULL_DATA STATMAP file. Please let me know if you have any feedback about doing this as I want to also keep pushing on further down the workflow code.
@ahnitz There's a couple of minor changes in `workflow.core` along with this. IFOs supplied to an `Executable` are now sorted to avoid the `H1L1` …

New search workflow cleanup 1

---

bin/workflows/pycbc_create_offline_search_workflow
pycbc/workflow/coincidence.py
pycbc/workflow/core.py
pycbc/workflow/injection.py
pycbc/workflow/plotting.py

This continues where I left off in #3193 and basically does the same thing for the injection jobs. There's not a whole bunch here really, just a bit of tag cleanup. I am trying to ensure that for any executable that might be called for injections *and* for full_data, it is sent a tag called `injections` if running injections so you can set options specific to all injections, and not have to specify an option for every injection run.
For many plotting codes this is not needed if they *only* run on injection runs. There's also some changes in ALLINJ naming.

New search workflow cleanup 2

---

bin/pycbc_condition_strain

Avoid passing through single precision if double is requested. This avoids a confusing situation where, if the input data touches an unlocked segment with very high dynamic range, `resample_to_delta_t()` can produce an entirely corrupted output due to using a single-precision FFT.
Adds support for HDF output also when splitting output frames.
Some cleaup and better logging.

Improvements to pycbc_condition_strain

---

pycbc/results/scatter_histograms.py

Currently, there are two bugs in `pycbc_inference_plot_posterior` which can cause the limits in the 1D marginal plots to not be the same as the 2D plots. The first bug can also cause posteriors and values to not be plotted correctly when plotting posteriors from multiple files on single plot.
The first, and most serious bug, is that the [remove_common_offset](https://github.com/gwastro/pycbc/blob/master/pycbc/results/scatter_histograms.py#L753) function, which removes a common offset if both the min and max parameter values values are the same order of magnitude and exceed 1000, is applied separately to each file that's provided, and separately to the prior. This can cause the 1D marginal plots to not be correct. More worryingly, it can cause the posteriors and reported values to not be …

Bug: Turn off removing common offsets in plot posterior and correctly set 1D marginal plot limits

---

pycbc/events/stat.py

We currently have an issue where the HLV statistic file is using 30G of RAM. It seems a major part of the problem is that the `param_bin` information is cast to a python `int`. An `int` is apparently a 24-byte object, whereas in the current HDF file it's stored as a 1-byte integer. So we can reduce the memory usage there by not changing the dtype and just using the dtype from the input file.
We will still need to go further to manage memory better, and avoid doing the sort operation here. So a subsequent patch should enable the ability to provide a pre-sorted file in the same format as this code needs it. But for now getting this in is useful for being able to run this code!

Stop changing dtype for stat file

---

bin/workflows/pycbc_create_offline_search_workflow
pycbc/workflow/coincidence.py

Recent changes to clean up the workflow a little bit has exposed a small problem in the `fit_by_XXX` setup code. In particular, with the current code the directories are called:
`fit_by_template-FULL_DATA-H1  fit_over_param-FULL_DATA-H1
fit_by_template-FULL_DATA-L1  fit_over_param-FULL_DATA-L1
fit_by_template-FULL_DATA-V1  fit_over_param-FULL_DATA-V1
`
One directory for each file. This is because the output directory was never specified here, and the files are being put into a default directory name. So I just change the new code to specify this. I chose to put this in FULL_DATA, as it's a little weird that TRIGGER_MERGE and STATMAP files are in full_data, but these files, which sit in the middle, are not.

Move fit_by files to the same directory

---

bin/hdfcoinc/pycbc_multiifo_dtphase
pycbc/events/stat.py

Updates to multiifo_dtphase and stat.py to change the ordering in stored prior histograms and allow more efficient running of coinc_findtrigs
The new version of stat.py has been tested with equivalent histogram files with and without the new sorting (manually applied) and and example run of coinc_findtrigs run gives exactly the same outcome.
The output histogram of the new version of multiifo_dtphase has not yet been tested against these

Prior histogram efficiency

---

bin/hdfcoinc/pycbc_multiifo_page_foreground

Adding in pycbc_multiifo_page_foreground for getting foreground tables in multiifo workflow
pycbc_page_foreground was a bit too proscriptive to allow switches in a single script, so a new code is created - does not work on old-format combine_statmap files
Example output for normal use [here](https://ldas-jobs.ligo-wa.caltech.edu/~gdavies/testoutput/found_table_multiifo/H1L1V1-PAGE_FOREGROUND_HTML-multiifo_test.html) and using one round of hierarchical removal [here](https://ldas-jobs.ligo-wa.caltech.edu/~gdavies/testoutput/found_table_multiifo/H1L1V1-PAGE_FOREGROUND_HTML-multiifo_test_hr1.html). Too many hierarchical removals requested gives [this](https://ldas-jobs.ligo-wa.caltech.edu/~gdavies/testoutput/found_table_multiifo/H1L1V1-PAGE_FOREGROUND_HTML-multiifo_test_hr3.html)
When …

Add code for foreground loudest events table in multiifo format

---

pycbc/events/ranking.py

New stat scales both SNR and chisq by psd_var
Also change 'bchisq' where it appears and is actually reduced-bruce-chisq to 'brchisq' to remind us it is 'reduced'
Also put functions in more logical/chronological order

Change unused newsnr_sgchisq_psdvar function

---

bin/workflows/pycbc_create_offline_search_workflow

Add newly-made foreground table in to workflow (Forgot to include this in #3209)
Note that this will need changes to executables config to use new pycbc_multiifo_page_foreground executable
Intended outcome: provide loudest foreground events table in "open box results" summary page on results pages

make foreground table in workflow

---

pycbc/distributions/joint.py

@cdcapano @cmbiwer trying to follow the [example](https://pycbc.org/pycbc/latest/html/pycbc.distributions.html#module-pycbc.distributions.joint) for a JointDistribution with constraints, I ran into two errors, one trivial and one not:
1.  import needs to be `Uniform` not `uniform`
1. Since the example constraint function `mtotal_lt_30` is not vectorized, but evaluated internally over an array of amples for the pdf renormalization, it throws an
```
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
At first I thought the right fix would be to vectorize the example function, e.g.
```
def mtotal_lt_30(params):
return np.less(params["mass1"] + params["mass2"],30)
```
but as far as I know, the resulting JointDistribution object won't be …

JointDistribution: introduce loop for renormalization due to constraints, and improve documentation

---

pycbc/inference/models/gaussian_noise.py

This makes it so that you can substitute values taken from an injection file in an inference config file, when using a model that inherits from `BaseGaussianNoise`.
Currently, you can set `static_params` to be values pulled from the injection file (when using `BaseGaussianNoise`) by setting them to `FROM_INJECTION`. This generalizes that to allow anything to be set in the inference config file to parameters pulled from the injection file. It also allows functions of injection parameters to be used, by doing `FROM_INJECTION:ARG`. The syntax for `ARG` is the standard parameter syntax (if no `ARG` is provided, it will default to using whatever option is being set).
This is most useful for setting trigger times. For example, when doing an injection run, you can have in the `[data]` section: …

Allow for more flexible substitution from injections in config file

---

bin/hdfcoinc/pycbc_multiifo_dtphase

Some bins were outside of the ranges of phase difference and SNR ratio due to smoothing
This PR makes the phases wrap back into the 0-2pi range when smoothing and removes any bins above/below the SNR ratio allowed range

PTA histogram - wrap phase, remove extraneous snr ratio bins

---

bin/hdfcoinc/pycbc_page_foundmissed

Adding colorbar tick labels to foundmissed plots - this is currently hard-coded to give 5 labels
I have also done some tidying of the code having seen that quite a bit has been repeated in various if statements. The colorblind-friendly colour scheme of #3205 also hadn't been applied to the plots which did not have --gradient-far set
Examples:
Gradient FAR - Found on top
Gradient FAR - Missed on top
Set FAR - Found on Top
Set FAR - Missed on Top

Add colorbar labels to foundmissed plots. General tidy-up of the foundmissed script

---

bin/hdfcoinc/pycbc_page_coinc_snrchi
bin/workflows/pycbc_create_offline_search_workflow

Re-enable the coinc_snrchi plots in the multiifo workflow. Doing this requires adding a small amount of code to the executable to handle both old- and new-format input.

Coinc snrchi multiifo

---

docs/_include/inference_example_relative.sh
docs/inference/examples/relative.rst
examples/inference/relative/get.sh
examples/inference/relative/plot.sh
examples/inference/relative/relative.ini
examples/inference/relative/run.sh
pycbc/inference/models/__init__.py
pycbc/inference/models/relbin.py
tools/pycbc_test_suite.sh

This patch generalizes the relative likelihood model to be able to use any available frequency domain approximant, by switching the waveform generation from `spa_tmplt` to `get_fd_waveform_sequence`. This has been tested and confirmed to work for `TaylorF2`, `IMRPhenomD`, and `SEOBNRv4_ROM`.
To enable the use of different approximants, the fiducial waveform parameters required by the model are no longer provided explicitly to the `__init__` method. Instead these parameters are processed by `extra_args_from_config` into a single kwarg `fiducial_parameters`, using the same `{PARAM}_ref = {VALUE}` convention in the `[model]` section of the config file.
Other minor changes include:
- restructure the loglr calculation to more closely match that done by `MarginalizedPhaseGuassianNoise`
- …

Generalize relative model to all frequency domain approximants

---

docs/inference.rst

#3224 added a documentation page with example for the relative likelihood model, but did not add a link to the new page in `inference.rst`. This patch adds that link, and an example of the documentation with link included is here:
https://dfinstad.github.io/pycbc/latest/html/inference/examples/relative.html

Add link to relative model documentation page

---

pycbc/filter/matchedfilter.py
test/test_matchedfilter.py

stilde.delta_f and psd.delta_f were compared with the == operator.
This can produce false positives due to the finite precision of
the floating-point representation. Now, assert_almost_equal
takes care of this.
In addition, a bare except has been removed to catch the correct
exception that numpy.testing.assert_almost_equal throws.
Fixes #3226.

Improve float comparison in matchedfilter.py

---

bin/hdfcoinc/pycbc_page_ifar
bin/workflows/pycbc_create_offline_search_workflow

update pycbc_page_ifar to use new-style statmap files
NB. this does not work for combined statmap files at the moment as they do not have background event IFAR calculated
Some tidying of the file to get it to meet PEP8 requirements
Added page_ifar into the multiifo workflow (plus forgotten uncombined foreground tables)
Solves issue #3208

Multiifo page_ifar

---

bin/plotting/pycbc_ifar_catalog

If --truncate-threshold is not set, then tries to take log10 of None --> error
Move the 'or' statement so that this doesn't fail

ifar_catalog bug

---

bin/plotting/pycbc_plot_qscan

This PR adds the option to plot a waveform time-freq track on top of an omega scan in pycbc_plot_qscan. To avoid having to give too many new arguments, it takes the masses in the same format as the time_window (i.e. mass1,mass2). I wanted to do the same with the spins, but it fails if the first spin is negative (if someone knows how to fix that, I'll be happy to change it).
P.S: I have an example plot in my laptop but I don't see any way to attach it here. I can send it on slack if someone wants to see it.

Add option to plot waveform track on top of qscan

---

.travis.yml

Allow release builds to work by only pushing the 3.6 build to PyPi

Only deploy 3.6 version to pypi

---

bin/hdfcoinc/pycbc_fit_sngls_split_binned

As seen by @duncanmmacleod - if the number of triggers is low, then pycbc_fit_sngls_split_binned will fail
This is as there may be some templates with no triggers, in which case, we need to fall back to the original (slower) template duration calculation rather than reading it from the trigger fits file
The code now works in this case, but is slow, so the work in progress is to work out the trigger-to-template number ratio where we would expect this to happen, so that we don't do both procedures if we're likely to need this exception

split_binned histogram plots dealing with low numbers of triggers

---

bin/hdfcoinc/pycbc_page_snrratehist

snrratehist had some issues which come up when using with the new statistic
- X label was hard-coded to something incorrect (now more generic)
- Default values of x-min and bin-size were sensible for sum-of-SNRs ranking statistic, but not for others:
- x-min default changes from 8.0 to np.floor of the peak of the exclusive background histogram
- bin-size default changes from 0.1 to 1/100th of the statistic range
- Fill the background at the end (this was just personal preference for aesthetics)
- Clarify the involved IFOs in the title and caption
Example output (default values):
Previous output (default values):

Updates to snrratehist

---

bin/pycbc_condition_strain

Right now the split file name format is hardcoded to something like `H1-BASE_1234567890-12.gwf`. The resulting files are not directly usable by PyCBC Live, which expects `H1-BASE-1234567890-12.gwf`. This patch allows full control on the format from the command line by introducing the formatters `{start}` and `{duration}`.

pycbc_condition_strain: fix split file name

---

pycbc/inference/models/gaussian_noise.py
pycbc/inference/models/marginalized_gaussian_noise.py
pycbc/waveform/generator.py
pycbc/waveform/waveform.py

This adds an `ignore_failed_waveforms` option to the `GaussianNoise` and `MarginalizedGaussianNoise` models. If turned on, the model will catch errors raised by the waveform generator and assign that point likelihood = 0. Otherwise, the error will be raised. This allows one to still do PE even if a waveform model fails in a particular (and unknown a priori) part of parameter space.
To do this, I added a new exception `FailedWaveformError` to `waveform.py`. I thought about using `NoWaveformError`, but decided to keep that separate, since that indicates a zero waveform (like you would get if you flower is beyond the ringdown frequency). I created a new exception for `FailedWaveformError` rather than just catch `RuntimeError`s so that this can also be used with non-lalsimulation waveforms in …

Allow PE to continue if waveform fails

---

pycbc/strain/strain.py
pycbc/types/timeseries.py
test/test_chisq.py

I've run into an issue caused by the previous sample rate rounding we put it. For once of my problems I have a non-integer sample rate. This situation will happen again and again in the future. At the moment, if you try to do this, things will silently work, but you'll get unexpected results for some operations (like time slice). 
@titodalcanton I know we put this in for something related to pycbc live. Can you remind me what the issue was? I no longer think requiring an integer sample rate (or dt for that matter) is a good idea.
DO NOT MERGE UNTIL IMPLICATIONS ARE SORTED OUT

No longer round sample rate

---

pycbc/inference/models/data_utils.py

Sets `pad` to 0 if `inverse-psd-length` is not provided in data section.
Fixes #3248

Fix issue #3248

---

pycbc/io/live.py

PyCBC Live tries to report the git hash when uploading candidates,
but that is an empty string when using actual releases, so the
version info is lost in production setups. This patch improves
that and also logs the location of the code.

PyCBC Live: fix empty versions in uploads

---

pycbc/types/timeseries.py

`round()` is not defined for instances of `lal.LIGOTimeGPS`.

Add missing cast to float

---

pycbc/psd/analytical.py
pycbc/psd/estimate.py
pycbc/strain/strain.py

The strain module calls `psd.analytical.from_string()` with a float `length` in Python 3, which raises a warning. This patch fixes it and turns the warning into an error, consistently with other PSD modules. Another harmless case of non-floor division in the PSD module is fixed.

Fix warning when generating fake noise

---

bin/plotting/pycbc_plot_waveform
bin/pycbc_banksim
examples/overlap.py
pycbc/filter/matchedfilter.py
pycbc/filter/resample.py
pycbc/noise/reproduceable.py
pycbc/strain/strain.py
test/test_matchedfilter.py

As expected, #3277 revealed some cases of floats being used as integers. @SumeetKul found such a case in the `noise` module, which this patch should fix.
I took the chance to have a wider look at the repository and fix a few other cases where I suspect floor division should be used.

Use floor division where integers are expected

---

bin/pycbc_inspiral
examples/inspiral/run.sh
pycbc/events/eventmgr.py
pycbc/inference/io/__init__.py
pycbc/inference/io/base_hdf.py
pycbc/io/hdf.py

This adds basic checkpointing to pycbc inspiral using the cPickle module to save the EventManager to disk. 
A new option '--checkpoint-interval' is added to pycbc inspiral. If provided, you give the number of templates between checkpoints. These happen automatically, and are not triggered by condor atm. 
Some things to note
(1) XML format template banks don't work with this. I think there is a bug in numpy at the moment in regards to pickling of object dtypes (it should throw an error when you try to pickle instead it decides to segfault when you load from the pickle file). Only use HDF format files if you have checkpointing enabled. I have no plans to support XML format. 
(2) This patch does not include any updates for the workflow to handle these checkpoints for you, so you should only …

add checkpointing to pycbc inspiral

---

bin/workflows/pycbc_create_offline_search_workflow

Create XML files needed to allow gracedb uploads from the offline workflow

Add xml foreground into multiifo workflow

---

bin/hdfcoinc/pycbc_fit_sngls_split_binned
pycbc/events/stat.py

Change the single-ifo fit distribution to use a exp(-6 (newsnr - thresh)) below threshold
This is particularly an issue with high mass templates which are susceptible to glitches --> shallower distribution --> over-ranking these events
I've snuck in some useful but unimportant changes in fit_sngls_split_binned which were wanted before but flagged up when testing this

Add standard newsnr fitting below fit threshold

---

pycbc/inference/sampler/dynesty.py

This change enables the inference module to use the dynamic nested sampler provided (and actively developed) by JS in [`dynesty`](https://github.com/joshspeagle/dynesty).

Add support for dynesty's dynamic nested sampler

---

pycbc/events/stat.py

Use get_newsnr_sgveto_psdvar in exp_fit_sg_fgbg_norm_psdvar and exp_fit_sg_fgbg_norm_psdvar_bbh statistics
Note that 2ogc and 2ogcbbh named statistics still use get_newsnr_sgveto_psdvar_scaled and get_newsnr_sgveto_psdvar_scaled_threshold respectively

Use get_newsnr_sgveto_psdvar where appropriate

---

pycbc/types/timeseries.py
test/test_timeseries.py

@lpsinger Pointed out the current indexing will produce off by one errors. This patch redoes the indexing to avoid the time_slice method.

redo indexing in 'add into' method

---

requirements.txt

The current version of epsie (0.5) changes some syntax that is causing the inference travis test to break. I'm working on a proper fix, but until then, this pins the version of espie to the pervious version (0.4.1) so that travis can pass.

Pin to epsie 0.4.1 for now

---

pycbc/filter/matchedfilter.py

Resolved the error: ValueError: NumPy boolean array indexing assignment cannot assign 80 input values to the 79 output values where the mask is true that was occurring in pycbc_inspiral_skymax workflow.

Changed the way  an array element is replaced based on condition

---

pycbc/distributions/constraints.py
pycbc/distributions/joint.py

The changes in PR #3214 made initializing the `JointDistribution` class incredibly slow if any constraints are used.  A renormalization constant is estimated by evaluating the constraints over 1 million points when the distribution is initialized. Previously, this was done by applying the constraints to a vector of samples. In #3214, that was changed to looping over each point, evaluating the constraints one point at a time. This has made initializing the joint distribution go from taking less than a second, to several minutes, if not hours, if any constraints are used. This makes using constraints in PE jobs or when creating injections virtually impossible.
This patch fixes that by going back to evaluating the constraints on the vector of samples (see lines 122-124 of …

Undo renormalize loop in JointDistribution

---

bin/pycbc_live
pycbc/events/single.py
pycbc/fft/mkl.py
pycbc/filter/matchedfilter.py
pycbc/io/live.py
pycbc/strain/strain.py
pycbc/waveform/bank.py
pycbc/waveform/premerger.py
pycbc/waveform/waveform.py

This implements the following features to enable pre-merger detection with pycbc live
1) A new template called 'PreTaylorF2', where the 'f_final' argument is taken as the end of the waveform and the waveform is time-shifted from this point so the end is at zero.
2) Tracking of the inccurred time offset, which is propagated to the name of the coinc file and the coinc end time. I've left the other times alone as that might be better for understanding the event (i.e. the SNR is X up to that time). 
Only testing I've done so far is on 170817, which this produces trigger for as expected ~ 10 seconds before merger (which is exactly what I build a quick test bank for, so I wouldn't expect any other time).

add precognition to pycbc live

---

pycbc/workflow/pegasus_files/local-site-template.xml

There will shortly be changes to some LDG HTCondor configurations where jobs will no longer match to the local pool (even if the grid site is 'nogrid' and `+IS_GLIDEIN` is `False`) unless they also set `+flock_local = True` in their submit files.  This PR makes the necessary change. It should be safe to use even on sites that do not have that requirement, as they will ignore the setting of that optional condor variable.
@spxiwh @GarethDaviesGW This change will likely be needed during at least some of the upcoming offline runs, so in relatively short order it should be incorporated into a release.  But it can wait on any other changes that might be needed if there will be another point release before the production runs start.  Otherwise, we will probably need a point release just for …

Update pegasus template for 'local' site 

---

pycbc/inference/io/epsie.py

Adds `read_acceptance_ratio` and `read_acceptance_rate` methods to epsie files, and  aliases `read_acceptance_rate` with `read_acceptance_fraction` so that `pycbc_inference_plot_acceptance_rate` will work with epsie files. Example output of plot acceptance rate run on an epsie file after this patch [here](https://www.atlas.aei.uni-hannover.de/~work-cdcapano/scratch/epsie/H1L1-PLOT_ACCEPTANCE_RATE_AD1024_NT8_SW1_0-1126259200-400.png).

Add read_acceptance_ratio/fraction to epsie io

---

pycbc/io/hdf.py

read IFOs from coinc file in ForegroundTriggers rather than list of individual trigger files
This caused an issue, e.g. when using a H1L1 statmap file with H1, L1, V1 single-detector trigger files given on command line.
There are a couple of other places in the code which use `self.sngl_files.keys()` as the list of IFOs but I haven't changed these as I haven't seen issues with using them as they are

Change ForegroundTriggers IFO information source

---

bin/live/pycbc_live_combine_single_fits

One of the variables being looped over was in a different dimension than the others (fit file date rather than bin)
I hadn't noticed this as the number of bins had always been less than the number of days being analysed
Also prevents the same colour being used twice in plots given a large number of bins

Live combine fits missing bins bug

---

docs/index.rst
docs/inference.rst
docs/waveform_plugin.rst
examples/waveform/add_waveform.py
pycbc/waveform/__init__.py
pycbc/waveform/parameters.py
pycbc/waveform/plugin.py
pycbc/waveform/waveform.py
tools/docker_build_dist.sh

* This allows pycbc to properly find external packages which *advertise* a plugin for pycbc without relying on environment variables.
* An example plugin package is provided in https://github.com/gwastro/example-waveform-plugin
If the plugin is simply installed, pycbc will automatically pick it up and its waveform models will be available from PyCBC. I think this is the behavior we would like for external packages. The hook is the standard Python mechanism using the 'entrypoint' system of 'pkg_resources', which was explicitly designed for this purpose. 
* (this will eventually deprecated the older undocumented interface, but I'm not removing in this PR yet). "
It would be good if you all could sign off on the generic interface and merge this first. In the next PR, I'll add documentation …

add plugin handling for waveforms

---

bin/inference/pycbc_inference_plot_acl
pycbc/inference/burn_in.py
pycbc/inference/io/base_hdf.py
pycbc/inference/io/base_mcmc.py
pycbc/inference/io/base_multitemper.py
pycbc/inference/io/emcee.py
pycbc/inference/io/emcee_pt.py
pycbc/inference/io/epsie.py
pycbc/inference/sampler/base_mcmc.py
pycbc/inference/sampler/base_multitemper.py
pycbc/inference/sampler/emcee.py
pycbc/inference/sampler/emcee_pt.py
pycbc/inference/sampler/epsie.py

This separates ensemble MCMC (in which chains share information) methods from generic MCMC methods (in which chains are independent of each other) in the io, burn in, and sampler module. The primary purpose of this is to allow epsie (or any other future MCMC sampler) to use different burn in iterations and ACLs for different chains, resulting in a different number of effective samples being collected from different chains. This also lays ground work for implementing a transdimensional MCMC in the future.
This turned out to be way more work than I anticipated when I started it. I didn't realize how much ensemble MCMC-specific things were ingrained in the base MCMC classes. Hence the large patch. In terms of actual differences a user would notice, the output for emcee(_pt) files are largely …

Allow different burn-in iteration and ACL for independent MCMC chains

---

bin/hdfcoinc/pycbc_coinc_hdfinjfind

If an injection is vetoed in one detector, then its optimal SNR is still used for decisive SNR
This sets optimal_snr=0 in the given detector for any injection in vetoed times in the HDF injfind output
Compare new output:
https://ldas-jobs.ligo.caltech.edu/~gareth.davies/testoutput/decisive_opt_snr_vetos/H1L1V1-PLOT_FOUNDMISSED_ALL_MCHIRP_GRADM.png
To old output:
https://ligo.gravity.cf.ac.uk/~gareth.davies/o3/runs/hlv/c01/a22_initial/5._injections/H1L1V1-PLOT_FOUNDMISSED_ALL_MCHIRP_GRADM-1253317851-691791.png

Optimal SNR for vetoed injections

---

bin/inference/pycbc_inference_plot_samples

Updates `pycbc_inference_plot_samples` so that it will work with either emcee or epsie. Basically, changes "walkers" to "chains" in most places, but uses the correct kwarg (nwalkers or nchains) when retrieving samples. Tested with both [emcee pt](https://www.atlas.aei.uni-hannover.de/~work-cdcapano/scratch/prs/epsie_separate_acls/py37_gw150914_8perchain/4._samples/4.01_emcee_pt/) and [epsie](https://www.atlas.aei.uni-hannover.de/~work-cdcapano/scratch/prs/epsie_separate_acls/py37_gw150914_8perchain/4._samples/4.03_ad1024_nt8_sw1/).

Update plot samples to use chains or walkers

---

pycbc/inference/gelman_rubin.py

There is a float division of an array index in `gelman_rubin.py`. That causes in an error in python 3, since the index is converted to a float in the process. Fixes that by using integer division. Tested with emcee_pt, [here](https://www.atlas.aei.uni-hannover.de/~work-cdcapano/scratch/prs/epsie_separate_acls/plot_acls/gelman_rubin-gw150914_8perchain-emcee_pt.png). The gelman-rubin plotting code needs some other updates (like fixing the x-axis to account for thinning), but at least this will let it run without error.

Fix gelman rubin test for python 3

---

examples/inference/priors/gw150914_like.ini
pycbc/transforms.py
test/test_transforms.py

Adds a generic `SphericalToCartesian` transform and its inverse.
Currently, we have a class that does this specifically for `spin1` called `SphericalSpin1ToCartesianSpin1` (ditto for spin2). Those two classes are tied to parameters with names "spin1{X}". This makes that generic, so you can use a single transform for any spherical <-> cartesian transforms. This means you would now do:
```
[waveform_transforms-spin1x+spin1y+spin1z]
name = spherical_to_cartesian
x = spin1x
y = spin1y
z = spin1z
radial = spin1_a
azimuthal = spin1_azimuthal
polar = spin1_polar
```
And same for spin2.
I've left the `SphericalSpin(1|2)ToCartesianSpin(1|2)` classes in for now, but have added deprecation warnings to them saying they will be removed in a future update.
This still leaves in automatic transforms in …

Add spherical to cartesian transform

---

pycbc/waveform/parameters.py

Adds `srcmass1`, `srcmass2`, `srcmchirp`, `srcmtotal`, `delta_tc`, and `comoving_volume` to `waveform/parameters`. Main purpose is to register common labels for them, so you don't have to write out the latex on the command line every time you want to plot them.
Example:
```
pycbc_inference_plot_posterior \
--verbose \
--input-file H1L1V1-INFERENCE_150914_09H_50M_45UTC-5-1.hdf \
--thin-start 414 --thin-interval 39 \
--output-file ~/WWW/scratch/prs/new_param_labels/posterior_test.png \
--plot-scatter --plot-marginal --z-arg snr \
--parameters srcmass1 srcmass2 \
'mchirp_from_mass1_mass2(srcmass1, srcmass2):srcmchirp' \
'srcmass1+srcmass2:srcmtotal' delta_tc comoving_volume 
```
yields: [plot](https://www.atlas.aei.uni-hannover.de/~work-cdcapano/scratch/prs/new_param_labels/posterior_test.png …

Register some more parameter labels

---

docs/workflow/pycbc_make_inference_workflow.rst

Updates the documentation for the inference workflow. Test page [here](https://www.atlas.aei.uni-hannover.de/~work-cdcapano/scratch/prs/update_inference_workflow_docs/_gh-pages/latest/html/workflow/pycbc_make_inference_workflow.html)
This includes links to a couple of example results pages. Right now I'm just pointing to pages I have on atlas. I've uploaded these pages to [another repo on gwastro](https://github.com/gwastro/pycbc-inference-workflow-examples), but I haven't figured out how to display them as html pages yet. Once I do, I'll file another PR that updates the links.

Update inference workflow docs

---

docs/workflow/pycbc_make_inference_inj_workflow.rst
docs/workflow/pycbc_make_inference_workflow.rst
examples/workflow/inference/bbh_inj-dynesty/create_inj_workflow.sh
examples/workflow/inference/bbh_inj-dynesty/injections_config.ini

Adds some example config files and updates the instructions. Example shown is for 10 BBH using dynesty. Right now it links to a test results page on atlas, [here](https://www.atlas.aei.uni-hannover.de/~work-cdcapano/scratch/inference_workflow_docs/bbh_injections-dynesty/). Will update this in another PR.
Test page [here](https://www.atlas.aei.uni-hannover.de/~work-cdcapano/scratch/prs/update_inj_workflow_docs/_gh-pages/latest/html/workflow/pycbc_make_inference_inj_workflow.html)

Update inference inj workflow docs

---

pycbc/workflow/datafind.py

We want to be able to support a situation where the frame type varies with time. This patch implements this functionality in the `workflow` module, using the same syntax as for DQ flags. I've added a few sanity checks alongside this (e.g. we cannot have overlapping frame types).
I also did a bit of cleanup in the relevant block of code. I only implemented this in the "single_call_perifo" block, as I want to delete the "multi_call_perifo" block in the nearish future.
I will also be wanting to do the same for the `channel-name`, which is potentially a little more complicated.
I've tested that this does what is intended.

Allow frame types that change with time

---

bin/hdfcoinc/pycbc_calculate_psd
pycbc/workflow/core.py
pycbc/workflow/jobsetup.py
pycbc/workflow/minifollowups.py

This pull request continues from #3342. Here we want to solve the problem specifically of having a time-dependent `channel-name`, but in doing so add in some plumbing to allow this to be done in more general cases.
The idea here is that you want something like:
```
--channel-name CHANNEL_NAME_A[0:100000],CHANNEL_NAME_B[100000:200000],CHANNEL_NAME_C[200000:300000]
```
We put this into the config file, but we want the workflow generator to automatically figure this out, and send the appropriate channel name to the appropriate jobs.
To do this I've implemented a `time_dependent_option` class variable, similar to how file_options work. If you add `channel-name` into this list, the workflow generator will know to expect something like this and will automatically parse it.
This does require the …

Allow options that depend on time

---

pycbc/frame/frame.py

If dealing with a *lot* of frame files, but only reading a short amount of time, it makes sense to sieve the LALCache down before trying to read anything.
... This also helps if the frame-type changes as otherwise the code fails because the channel in some random earlier file doesn't match, even though you don't want to read that file at all!

Sieve times when frame reading

---

pycbc/waveform/waveform.py

Adds a function `imrphenomhm_length_in_time` to `waveform.py` that estimates the duration of Phenom waveforms that include sub-dominant harmonics. The estimate is calculated by multiplying the PhenomD estimate by max m/2, where max m is the largest m in the requested modes. If no modes are provided, it uses max m = 4, since (according to their papers), the highest m mode is the (4,4). This also updates the dictionary of filter length functions to have point to this function, so that `get_waveform_filter_length_in_time` will use it.
This also means that the calling `get_td_waveform` will now default to calling our internal `get_td_waveform_from_fd`, which avoids the lalsimulation issue of truncating higher modes too soon.

Add duration support for Phenom HM waveforms

---

pycbc/inference/io/__init__.py
pycbc/inference/io/dynesty.py
pycbc/inference/sampler/base.py
pycbc/inference/sampler/cpnest.py
pycbc/inference/sampler/dynesty.py
pycbc/inference/sampler/multinest.py
pycbc/io/hdf.py
pycbc/pool.py

This supersedes #3330 and #3316. 
This addes support for checkpointing the dynesty sampler when using a fixed number of live points. Checkpointing the Dynamic sampler is not currently enabled and will require the open PRs https://github.com/joshspeagle/dynesty/pull/192 and https://github.com/joshspeagle/dynesty/pull/188 for dynesty to be first merged and included in a release. 
```
[sampler]
maxcall = 5000 # number of calls before we can check if we need to checkpoint, optional set to 5000 * ncores if not set
checkpoint_time_interval = 1000 # seconds between checkpoints
```

add checkpointing for Dynesty

---

bin/pycbc_live

To store only n-loudest while writing live background. This can reduce storage while saving the background.

Write n-loudest in the background

---

bin/hdfcoinc/pycbc_multiifo_coinc_statmap_inj
bin/plotting/pycbc_ifar_catalog
bin/workflows/pycbc_create_offline_search_workflow
pycbc/events/coinc.py
pycbc/waveform/bank.py

Makes a function which detects whether using python 2 or python 3 and decides whether to use native hash (unsafe in python 3) or hashlib module (utilises int.to_bytes which is unavailable in python2)
Solves issue #3302
Note that I haven't been able to test using bank2hdf, as I haven't been able to get that to work even with the original function! However this works with Tito's test script

Offline hash handling

---

pycbc/workflow/core.py
pycbc/workflow/minifollowups.py
pycbc/workflow/plotting.py

There were some problems from #3344, which didn't arise earlier because filesystem problems here are making tests hard to complete. These fixes correctly ensure that time-dependent options get sent through for minifollowup jobs, and also allow the valid_segment to come through.
The latter problem means that the current master is actually broken for all-sky workflows.

Fix some issues with #3344

---

pycbc/distributions/angular.py
test/test_distributions.py

The angular distributions produce values in radians, but the bounds are in fractions of PI. We should consistently use radians so that min/max parameters can be given in the same units. This makes it a lot easier to do bounded sky location priors.

use radians consistently for setting angular bounds

---

pycbc/workflow/pegasus_files/nonfsio-site-template.xml

We are currently seeing severe issues on one of our clusters during the coincidence stage because the repeated, small, I/O on the HDF_TRIGGER_MERGE files becomes too much. It seems more efficient to have the input files staged to local disk before starting the job in this case (yes, I know that's a larger *total* I/O, but in one large block it seems faster).
This also might be useful for other jobs. So the idea here is to add a site "nonfsio". If you use config overrides and options to submit_dax you can ensure that any specific executable will always run in this mode and not use symlinked input files.
I don't know if there is an easier way to do this? I know I can make *all* jobs use copied inputs, but I don't think that's what I want. Some jobs do a tiny amount of I/O on quite large …

Add site to avoid NFS symlinks

---

examples/inference/single/single.ini
pycbc/boundaries.py
pycbc/distributions/joint.py
pycbc/inference/sampler/dynesty.py

This passes the pycbc boundary types (where applicable) to dynest. Only the two-sided reflective and the cyclic boundaries are supported as those are the only ones Dynesty has. So, notable, there is no one-sided reflective boundary. 
Example of how to write the boundary in the config file. Note that if you specify the boundary type, you also need to explicitly
set the min/max of the parameter as well. I am doing so here for inclination. The units are currently radians per PI, but that will change to PI in #3355, so be careful until that patch is applied. 
```
#btype-min-distance = reflected
#btype-max-distance = reflected
[prior-inclination]	[prior-inclination]
name = sin_angle	name = sin_angle
cyclic-inclination =
min-inclination = 0
max-inclination = 3.141592653
```

pass boundary types to dynesty

---

bin/inference/pycbc_inference
pycbc/inference/io/base_hdf.py
pycbc/inference/io/base_mcmc.py
pycbc/inference/io/base_sampler.py
pycbc/inference/sampler/base.py
pycbc/inference/sampler/base_mcmc.py

This makes it so that some history is preserved in the inference checkpoint file on each checkpoint. Right now, only the MCMC samplers make use of this, but nested samplers could pick up the functionality later. This can be used for comparing performance between samplers, and to diagnose issues (like growing ACTs).
On each checkpoint, `update_checkpoint_history` is called. This is a method of `BaseSamplerFile`. It writes the current time and the time since the last checkpoint or last startup (which ever happened last). It then calls `_update_sampler_history`. This doesn't do anything in `BaseSamplerFile`, but can be overridden to write-sampler specific things. This is overriden by `CommonMCMCMetadataIO` to write the number of iterations, effective number of samples, burn-in iteration, and …

Write checkpoint history

---

pycbc/inference/io/base_multitemper.py

Fixes a bug where complex datatypes were not being correctly loaded when reading samples from epsie. Currently, `read_raw_samples` is assuming that all data are floats. However, since epsie stores the complex log likelihood ratios, they were being forcibly cast to floats. This also caused a problem when trying to thin samples on disk.

Set correct dtype when reading epsie samples

---

pycbc/strain/gate.py

This adds the gate and in-paint function used by the IAS group to the gate module. It just takes a right index and left index. We probably will want to add another function that takes in times, but since that may require doing sub-sample shifting, I thought it might be better to add that as a separate function, which would call this function.
I've only tested that this works on a time series without failing. I haven't actually checked that it gives reasonable results.

Add gate and paint function

---

pycbc/distributions/joint.py

This further speeds up the joint distribution by allowing it work on an array of values. Since many (all?) of the distributions in the distributions module are not vectorized, you still can't do vectorized prior evaluation for most practical purposes, but this is a step in that direction.
My main reason for doing this was to speed up the rvs function when you have many constraints. Currently, this is quite slow, because it draws one point at a time, evaluating each as they go. In this patch, the rvs will draw a batch of points, then use the now vectorized `contains` function to evaluate them all at once. It will then keep the points that pass the constraints, and continue until it's acquired the requested size. On each loop it will also increase the size of the draws based on the previous …

Vectorize joint distribution

---

bin/inference/pycbc_inference
pycbc/inference/sampler/base_cube.py
pycbc/inference/sampler/dynesty.py
pycbc/inference/sampler/emcee.py
pycbc/inference/sampler/emcee_pt.py
pycbc/inference/sampler/epsie.py
pycbc/pool.py

This simplifies running under MPI with pycbc inference by removing the requirement for the --use-mpi and nprocesses options. You can no simply do
```
mpirun -np 5 pycbc_inference ....
```
With no extra options. It infers internally how many processes to use based on the mpi launch size. If you provide --use-mpi it will enforce that mpi is actually available and throw an error if not. Otherwise --use-mpi and --nproceses are optional in this case. A warning is raised if you provide them. In the future the --use-mpi option can then be removed entirely.

simplify running pycbc inference with mpi

---

bin/inference/pycbc_inference
pycbc/inference/sampler/base_cube.py
pycbc/inference/sampler/dynesty.py
pycbc/inference/sampler/emcee.py
pycbc/inference/sampler/emcee_pt.py
pycbc/inference/sampler/epsie.py
pycbc/inference/sampler/ultranest.py
pycbc/pool.py

This puts in place the minor changes needed to run ultranest with pycbc inference under MPI. 
Requires #3373

minor fixes to enable ultranest using MPI

---

pycbc/strain/gate.py
pycbc/types/frequencyseries.py
pycbc/types/timeseries.py

This should make it easier to select gate method in higher level codes in the future (i.e. pycbc inspiral / pycbc live).  This PR also addes a dummy to time/frequency series so that functions can be made generic of accepting a time or frequency series where possible. 
Depends on #3371 
'paint' method
'taper' method
'hard' method

update gate time series method to allow selection of gating type

---

pycbc/waveform/ringdown.py

The inference injection workflow currently does not work with ringdown injections with multiple modes because the different length of the lmn modes array causes a dimension mismatch. 
This updates the ringdown module to read a string containing the list as produced by the ConfigParser of the workflow when given as a string in the config file.

Update format_lmns in ringdown module.

---

pycbc/inference/models/base.py

This fixes a bug when using sampling parameters with MPI. When the parameters are loaded from the config file, they are initialized as a set, then converted to a list. However, `set` doesn't preserve order. This means that different slave nodes when running under MPI will think the sampler is giving it parameters in a different order than it is. This fixes this by sorting the sampling parameters (both when they are loaded, and when they are saved to the model's sampling_params attribute... just to be sure). This only would of effected emcee and emcee_pt, and only when running on MPI. Apparently this wasn't an issue in python 2.7, but is in 3.XX.

Make sure sampling parameters keep the same order

---

pycbc/workflow/core.py
pycbc/workflow/grb_utils.py
pycbc/workflow/injection.py
pycbc/workflow/psdfiles.py
pycbc/workflow/tmpltbank.py

So this carries on from #3360 with similar motivations (or at least playing around with #3360 lead to me needing to do this).
In short we use `resolve_url` to pull in inputs in a few cases, but this always needs extra commands after it to convert to a File object. I want to create a one-shot `resolve_url_to_file` function, that will return a File object with all necessary attributes/PFNs attached to it.
As an example, if an input is on CVMFS, and I want to run on OSG (let's say an injection file on CVMFS, or a template bank) the workflow generator will pull the file to the local site, and then it will be gsiftp-ed to the OSG sites in question. It would be better if the remote site can just get that via CVMFS (as happens with frame files, which are a bit of a special case, so not touched …

Consolidate resolve url

---

bin/pycbc_banksim_combine_banks

This PR is to fix an edge-case bug in pycbc_banksim_combine_banks. If the user splits the injections so many times that each BANKSIM file only contains a single injection, then the current method to find the maximum match across multiple banks fails with the error:
```
File "pycbc_banksim_combine_banks", line 58, in <module>
for i, j in enumerate(indices):
TypeError: 'numpy.int64' object is not iterable
```
To fix this we can check the dimensions of the `match` array and if it is only 1-dimensional we slightly alter how the `maxmatch` array is filled. If the `match` array is n-dimensional (for n > 1) then we do the same thing the code originally did.
___
The files used to test this edge case (both input and output) can be found at: …

Fixed edge-case bug in pycbc_banksim_combine_banks.

---

bin/hdfcoinc/pycbc_multiifo_add_statmap

This is wanted to be able to output times which are in any type of coincidence
This was previously doable by adding the segments from each type of coinc separately, but this makes things a bit easier

add_statmap to output combined segments of all types of coincidence

---

bin/pycbc_make_skymap

Adds the option to save the `.fits` and`.png` sky map files to a given path.
Also allows multiple instances of `pycbc_make_skymap` to be able to be run since each saves to a unique temporary directory. Before each would save to the same filename `0.fits` and had the potential to overwrite each other.

Add output directory choice for sky maps; Fixes #3383

---

bin/hdfcoinc/pycbc_coinc_findtrigs
bin/hdfcoinc/pycbc_multiifo_coinc_findtrigs
pycbc/events/stat.py

While running a search for lensed images we searched all of O2 with a single template using a single detector threshold of SNR=4. This produced roughly 1,000,000 single detector triggers in each detector with the single template.
This means that there were roughly 1,000,000,000,000 coincident triggers in the background to be tested. This obviously takes a long time.
However, when decimation is included we don't need the coincident statistics for most of these as they are removed by decimation. This script can be made more efficient by not calculating a lot of these.
To avoid calculating a lot of these discarded values we can:
1) Find all foreground coincidences and the background for timeslides that will always be kept after decimation.
2) Only keep the foreground triggers and the …

Adding optimisation for findtrigs

---

bin/hdfcoinc/pycbc_coinc_hdfinjfind

Fixing hdfinjfind, as the 'segments/coinc' group doesn't have any attributes so we can't copy them over.

Fix injfind

---

bin/pycbc_submit_dax

Change to pycbc_submit_dax to use resolve_url to allow cache file download from web pages behind authentication
Replaces the curl method, as if this is attempted with a password-protected file, then it will return the html of the login page and not fail.

update pycbc_submit_dax to deal with cache files behind authorisation

---

pycbc/inference/io/base_hdf.py
pycbc/inference/sampler/base_mcmc.py

This allows a file to be provided that will be used for the starting positions of an MCMC sampler. This is different than using an initial distribution in that the file specifies exactly the points to use, rather than just an initial distribution. It's mostly equivalent to providing a checkpoint file, but it doesn't cause the random sampler to be reset. The way this is done is you provide `start-file = file/path/start.hdf` in the `[sampler]` section of the config file. The start file is assumed to be an inference file with the same number of walkers/chains. The samples are pulled from the last iteration in that file.
This also a fixes a bug in the `copy` function in `base_hdf` that I came across while testing this.

Allow start file to be specified for mcmc samplers
