gwastro/pycbc

pycbc/dq.py
pycbc/inference/models/data_utils.py
pycbc/workflow/segment.py

Eric Sowell asked me about the following error:
```
Could not query flag, check name (DMT-ANALYSIS_READY) or times
File "<stdin>", line 1, in <module>
File "[some location]/python2.7/site-packages/pycbc/dq.py", line 226, in query_flag
raise e
ValueError: unknown url type: segments.ligo.org/dq/H1/DMT-ANALYSIS_READY
```
produced by this call:
```
dq.query_flag('H1','DMT-ANALYSIS_READY',[some GPS time],[some GPS time],source='dqsegdb')
```
After reproducing the error with the IGWN Conda env, I added the `https://` prefix to the server URL (`segments.ligo.org`), which fixes the error. I changed a few more instances with the idea that this is more general than the `dq` module. Anyone knows if `urllib` is requiring an explicit protocol prefix now?

Fix error from missing https:// prefix to segments.ligo.org

---

pycbc/inference/sampler/base_mcmc.py
pycbc/inference/sampler/base_multitemper.py

The ensemble samplers have a bug in the ACT that's printed to screen when the ACL is computed. They should report the acl times the file's `thinned_by` attribute (which is the thinning used when writing samples to file), but instead are printing the ACL times the file's `thin_interval` attribute (which is how many samples to skip to get a posterior). The latter is the ACL, so it's actually reporting the ACL squared rather than the ACT. This fixes that.
This bug actually affect anything, since the true ACT is calculated elsewhere (correctly), but it does make it confusing when looking at the messages being printed to screen while `pycbc_inference` is running.

Fix typo in ACT that's printed to screen

---

pycbc/fft/cufft.py

This patch is a hack to work around the following set of circumstances:
1. An executable is running in a CUDA-capable install of PyCBC (i.e., `pycuda` and `scikit-cuda` are both installed)
1. That executable is running on a machine that has a GPU, and the necessary drivers, so that the logic in `pycbc.__init__.py` defines `pycbc.HAVE_CUDA` to be `True`.
1. That job does not actually need a GPU, and has been submitted without requesting one, at least to HTCondor.  It has accordingly not been granted use of the GPU, even though there is one on the system.
1. The job (directly or indirectly) imports `pycbc.fft`, which is designed to build a list of available libraries that could provide FFT implementations.
Under these circumstances, there will be an unhandled exception, because the job …

Add try/except block around skcuda.fft import to ensure ImportError

---

pycbc/workflow/pegasus_files/nonfsio-site-template.xml

This adds the lines needed to the `nonfsio` site template so that jobs marked for that will not attempt to run on the grid, if submitted from a condor pool where such running is available.
The one remaining difference in condor configuration between the `nonfsio` site and the `local` site are that the latter also adds `getenv = True` to the condor submit files.  I would think we want the same behavior here, but I haven't added that change (yet).

Update nonfsio pegasus site template to prevent grid running

---

requirements.txt

This drops the official pegasus package in favor our custom cut down one always, even for python2. It works in python2 for running workflows and currently we are seeing issues with the full package building on newer OS's.

use pegasus with less requirements

---

pycbc/catalog/__init__.py

Allows the catalog interface to read whatever version frame that gwosc presents (assuming the channel name convention holds true). For the longer term, I've asked Jonah if the channel name can be put in the metadata. 
Enables this to work, since one frame is V1 and the other is V2
```
from pycbc.catalog.catalog import list_catalogs
from pycbc.catalog import Merger
sources = ["GW190412", "GW190814"]
ifos = ['H1', 'L1', 'V1']
for source in sources:
m = Merger(source, source='O3_Discovery_Papers')
data = {ifo: m.strain(ifo) for ifo in ifos}
psd = {ifo: data[ifo].psd(2) for ifo in ifos}
```

guess channel name from version

---

bin/hdfcoinc/pycbc_plot_throughput

If you allow a large variation in analysis times it would be interesting to compare the weighted distributions for these plots. This adds an option to do that.

add option to throughput plots to weight results by duration of job

---

bin/pycbc_make_skymap
pycbc/io/live.py

Added an optional argument to pycbc_make_skymap.
This argument is passed to pycbc_single_template and SingleCoincForGraceDB.
For SingleCoincForGraceDB to accept a high-frequency cutoff changes to pycbc/io/live.py were required. I think the place I put these changes at don't interfere with anything else. I also think that implementing the high-frequency cutoff the way done here will pass it to Baystar.

Created option to set a high-frequency cutoff in pycbc_make_skymap

---

pycbc/inference/models/data_utils.py

While doing a local build of the documentation under Python 3, I got the following exception:
```
2020-08-12 12:22:25,564 Reading Frames
XLAL Error - XLALFrStreamFileOpen (LALFrStream.c:128): No files in stream file cache
XLAL Error - XLALFrStreamFileOpen (LALFrStream.c:128): Invalid argument
XLAL Error - XLALFrStreamCacheOpen (LALFrStream.c:233): Internal function call failed: Invalid argument
File "somewhere/bin/pycbc_inference", line 128, in <module>
model = models.read_from_config(cp)
File "somewhere/lib/python3.7/site-packages/pycbc/inference/models/__init__.py", line 174, in read_from_config
return models[name].from_config(cp, **kwargs)
File "somewhere/lib/python3.7/site-packages/pycbc/inference/models/gaussian_noise.py", line 566, in from_config …
```

Fix exception handling in inference data utils module

---

bin/pycbc_make_skymap
pycbc/frame/frame.py

1) Don't hard code template flow. It was forced to 27Hz always!!! Instead set to provided low frequency cutoff
2) Don't hard code segment length, instead base on mass parameters given and f_low
3) Don't hard code the approximant, allow to be selected

improvements to pycbc_make_skymap

---

bin/hdfcoinc/pycbc_multiifo_sngls_findtrigs
bin/hdfcoinc/pycbc_multiifo_sngls_pastro
bin/live/pycbc_live_combine_single_fits
bin/minifollowups/pycbc_page_snglinfo
pycbc/events/coinc.py
pycbc/events/stat.py

Various changes for development of the multiifo singles search (this has been edited from when the PR was first put up)
Complete rework of `pycbc_multiifo_sngls_findtrigs`:
- not to use ReadByTemplate and behaves more efficiently
- Add ability to cut on SNR and reduced chisq before dealing with triggers (add other cut options?)
- Remove IFAR calculation
- Basically, this code now simply calculates the ranking statistic of triggers which meet the cuts above
New executable, `pycbc_multiifo_sngls_pastro`:
- Used after findtrigs statistic calculation
- Takes in triggers from full_data sngls_statmap files and calculate p_astro according to either callister or truncated_shelf methods
- It is possible to give multiple files here in order to analyse multiple chunks at the same time
- takes in …

MultiIFO workflow singles development

---

bin/hdfcoinc/pycbc_fit_sngls_by_template
bin/hdfcoinc/pycbc_fit_sngls_over_multiparam

@GarethDaviesGW @tdent I've gotten around to pushing upstream some changes I made locally for the high mass ratio search I did. Due to the large number of templates the fit code was pretty slow in default configuration.  
This patch
* Speeds up fit_by_template generally by switching to faster versions of the same calls
* speeds up fit_over_param by many orders of magnitude in the specific case of a single dimension

speed up trigger fitting 

---

pycbc/noise/gaussian.py

The lalsimulation noise generation now requires that the dc be zero'd out (instead of being implicitly ignored downstream). Otherwise it will produce an error when someone tries to generated noise based on a psd. Our reproduceable methods are unaffected.

zero out dc for lalsim method

---

bin/pycbc_make_skymap

Changes:
-Changed the error-codes on sys.exit to 1 instead of 0.
-Fixed a bug, where the wrong times were printed in error messages.
This function also redirects the stderr of the underlying `pycbc_single_template` code to a temporary file. This is difficult to find when debugging.

Changed the error-code when the code errors out.

---

bin/hdfcoinc/pycbc_coinc_mergetrigs

We have recently had several workflows that spend an inordinate amount of time in the `hdf_mergetrigs` jobs on full data.  In some cases they ran for 24 hours and got evicted. @titodalcanton noticed that these jobs were spending much more time writing some of the outputs than others, and that if he `condor_ssh'd` to the job, it was actually in the `R` state using 100% of the CPU, so it seemed that the time was spent in actual computation, and not file system issues.  On further investigation of an example file, if we ignore the datasets which correspond to statistics not actually calculated in a given workflow (e.g., bank chi-squared), then the greater the compression factor achieved, the longer it took to write that dataset, strongly suggesting that for datasets which were compressible …

Change gzip compression level from 9 to 6 in mergetrigs

---

pycbc/conversions.py

Adds a function to compute dimensionless spin given a pulsar's mass, radius, and rotation frequency. Just assumes the pulsar is a solid sphere when doing so. Example:
```
>>> from pycbc.conversions import spin_from_pulsar_freq
>>> spin_from_pulsar_freq(1.44, 11., 500.)
0.3975488979662235
```

Add spin from pulsar frequency to conversions

---

pycbc/conversions.py
pycbc/distributions/__init__.py
pycbc/distributions/fixedsamples.py
pycbc/inference/sampler/base_cube.py
pycbc/transforms.py
test/test_distributions.py

This adds a new distribution "FixedSamples" which allows for arbitrary and complicated distributions to be used within nested sampling in an approximate way. It is likely suitable for parameter estimation in many cases. Depends on #3315 
The idea is to draw a large number of points from any standard prior (even the arbitrary one) (say 10^6-10^9). These points can be transformed as one likes (using anything available for waveform transforms, including custom). The inverse CDF function is then done numerically by picking one of these points, so it can be used within nested sampling. This requires that a sufficient number of points is drawn from the prior for the parameters in question to adequately represent the space. 
Example configuration file. In this example instead of sampling in ra …

open up nested sampling to complicated / arbitrary distributions with fixed sample distribution

---

pycbc/waveform/spa_tmplt.py

Fix an instance of float value used as index (problem for python3). Also fixed index error in spa_tmplt for psds which are undefined at the nyquist (not normal use of this function, but other sources of PSDs don't provide a value here which can cause problems).

fixes to spa for python3

---

pycbc/io/live.py

The time offset was not properly applied everywhere and was showing up in the trigger/SNR plot, so this fixes it along with some minor code cleanup.
It would be nice to have a clearer, earlier distinction between "end time" and "merger time" in the code, such that the GraceDB interface code does not need to know about it.

PyCBC Live: fix a bug arising from early-warning test

---

pycbc/waveform/parameters.py
pycbc/waveform/waveform.py

This pull/merger request introduces 18 parametrized testingGR parameters into pycbc_inference. The parametrized TGR formalism is based on IMRPhenomD (and its successor) parametrization,  and introduces a fractional deviation for the waveform coefficients compared to its GR value. i.e. `p_nonGR = (1+delta p) * p_GR`. The GR value for those coefficients, p_GR, can be found in the IMRPhenomD [paper](https://arxiv.org/abs/1508.07253).
The `delta p` parameters introduced in this MR are `dchi0, dchi1, dchi2, dchi3, dchi4, dchi5, dchi5l, dchi6, dchi6l, dchi7`(post-Newtonian coefficients in inspiral region), `dbeta1, dbeta2, dbeta3`(intermediate region coefficients), and `dalpha1, dalpha2, dalpha3, dalpha4, dalpha5` (merger-ringdown region coefficients), see IMRPhenomD …

Adding testingGR parameters for pycbc_inference

---

pycbc/inference/models/__init__.py
pycbc/inference/models/gaussian_noise.py
pycbc/inference/models/marginalized_gaussian_noise.py
pycbc/waveform/generator.py

This adds a new model accessed by choosing 'marginalized_polarization'. It has one selectable option 'polarization_sampes' which sets how many integration points are used. It is hard coded to use a uniform in polarization prior from 0 to 2pi. 
In testing, the model seems to greatly improve convergence rate in at least some examples where the polarization angle and coa_phase had a complicated 2d histogram.

Add model with numerical marginalization of the polarization angle

---

pycbc/inference/sampler/dynesty.py

This fixes issue of not writing log_evidence and dlog_evidence to checkpoint and backup files. Now it writes it as attribute to the output file.

Writing checkpointing history to output files

---

pycbc/inference/models/__init__.py
pycbc/inference/models/brute_marg.py

Marginalize by simply calling the likelihood function multiple times. Sometimes useful for sampling.

brute force marginalization

---

pycbc/waveform/generator.py

This adds the capability to store the parameters of failed waveforms. It can be enabled through the base waveform generator and so is generic to anything that inherits from it. As an alternative it can also be enabled by environment variable 'PYCBC_RECORD_FAILED_WAVEFORMS'.

add option to save parameters of failing waveforms

---

tools/install_travis.sh

`https://git.ligo.org/ligo-cbc/pycbc-software` no longer exists, but it seems like somehow the build is using this location? May be wrong, let's see if this fixes the problems. ... At least we need to remove that reference so this patch is needed even if it doesn't fix the problem.

Fix Travis builds

---

pycbc/inference/io/dynesty.py

Fixes a few bugs introduced by PR #3376. First, when reading raw samples from a dynesty file, the current code tries to extract a posterior for all samples rather than just the fields requested. 
Second, and more egregious, is that the random shuffle that's done to extract the posterior means that repeated calls to `read_raw_samples` are not deterministic. This is a particular problem for `plot_posterior`. If you are plotting scatter points colored by SNR, two calls are made to `read_raw_samples`: one to get the samples and one to get the SNR. The random shuffle means that the SNRs returned will not correspond to the samples that were obtained in the first call.
This fixes that by introducing a seed argument. The random generator's seed is set to the given value just before the shuffle is …

Fix issues with extracting samples from dynesty file

---

bin/hdfcoinc/pycbc_coinc_hdfinjfind
bin/live/pycbc_live_combine_single_fits
bin/live/pycbc_live_single_trigger_fits

Allow date format to not be YYYY_MM_DD, but (e.g.) YYYY_M_D
fix issue which would break things if no triggers are found in the duration bin
Note that this does not affect the validity of reviews - it is mostly due to dealing with the O2 triggers

Fixes to live combine trigger fits

---

pycbc/libutils.py

This updates the PyCBC code that searches for compiled libraries to load via `ctypes`. It will now also look inside of `$VIRTUAL_ENV/lib`.  Hence if library code is installed into that directory of a virtual environment, it will be findable.
In particular, to get MKL support, it should now be sufficient to just `pip install mkl` inside the virtual environment, without needing to modify any paths inside of the activate script of the environment.
However, locations of that (or any other) library found along `LD_LIBRARY_PATH` or by calling `pkg-config` will still take precedence over this location, so users can override an installation in the virtual environment by appropriately setting either `LD_LIBRARY_PATH` or `PKG_CONFIG_PATH`.

Add VIRTUAL_ENV/lib to default ctypes search paths

---

pycbc/io/hdf.py

Added inbuilt function that searches through the triggers for positive time entries for each detector and returns a list of ifos used for each trigger separated by a comma. If the coinc file is in the old 2 detector format then it returns 'H1,L1'.

ForegroundTrigger in io/hdf now outputs ifos of triggers

---

companion.txt
docs/inference/examples/sampler_platter.rst
examples/inference/samplers/ptemcee_stub.ini
pycbc/inference/io/__init__.py
pycbc/inference/io/ptemcee.py
pycbc/inference/sampler/__init__.py
pycbc/inference/sampler/base_multitemper.py
pycbc/inference/sampler/ptemcee.py

Adds support for ptemcee.
Unfortunately, the released version of ptemcee (1.0.0) is incompatible with this, as I wrote it against ptemcee's current master. Given that there's hasn't been a release of ptemcee since 2015, and the last commit to it was in 2018, I don't think it'll be updated. So, to use this, you need to install from source.
Did a quick test on the normal distribution. Putting on hold until I have a chance to test on a GW.

Add support for ptemcee

---

pycbc/inject/inject.py

Fixes Issue #3427 
As described in there , `InjectionSet.write` fails if any of the injection parameters are strings. This can happen when writing an injection set that was loaded from another injection file. The reason is when the injections are loaded, any static arguments are expanded to fields. This is done using `numpy.repeat`. By default, numpy will store the python3 `str` as `U` type, but `h5py` doesn't know how to write that: if try to write the table back out, you'll get a `TypeError`. For example, say I have an injection file that has `approximant = IMRPhenomD` (as is the case in the example given in #3427). Since this is a static argument, it is stored in the injection file's `.attrs` as a `str`:
```
>>> injs = InjectionSet('injections.hdf')
>>> …
```

Allow injection set to write string datatypes

---

pycbc/events/ranking.py
pycbc/events/stat.py

I want to add the ability to threshold on psd_Var and chi-squared to the new statistic. The use case here is basically if one runs over "shouldn't-have-been-science-data" data. Autogating can get quiet eager in some stretches and remove massive fractions of some data stretches. Then you get triggers with ridiculous values of all statistics (e.g. huge SNR, huge chi-squared, huge PSD var). Unfortunately, these can also have decent new_snr, and decent coincident statistic.
Such triggers should never be considered for coincidence so adding a threshold.
I note that this again emphasizes the need to refactor the stat module and have this kind of thing as key-word arguments that could basically be used in any stat. In that vein I do the minimum to get this to work, and will shift this …

Add ability to threshold on psd_var and chisquared to new statistic

---

pycbc/inject/inject.py

Fixes an issue where injection files written in python 2 could not be read in python 3. The problem was both the file type and static params names are saved as unicode in python 2.7. In python 3 this results in them being returned as bytes instead of strings, which breaks string comparisons. Fixes this by casting to string after loading from file.
@titodalcanton I think this should fix the problem you found while testing #3471 .

Be able to read injection files written in python 2

---

pycbc/transforms.py

This adds an option to the `LambdaFromTOVFile` transform to turn off redshifting masses. This is needed if you want to use this transform with a prior that is defined in the source frame (since the masses are already redshifted). The default is to redshift, as before. To turn it off, you add `do-not-redshift-mass =` to the transform's section in the config file.
This also will check if the requested mass is larger than the maximum mass supported by the equation of state. If so, it will set lambda to 0, assuming that it is a black hole.

Add ability to turn off redshifting masses in TOV transforms

---

pycbc/inference/models/relbin.py

This patch makes two small modifications to the relative likelihood model:
- Checks the generated fiducial waveform for zeros at high frequencies, and excludes from the binning algorithm any that exist below the chosen high frequency cutoff. This prevents divide-by-zero errors in the likelihood calculation for higher-mass waveforms
- Adds an optional model arg `gammas` that defines the powerlaw indices used in calculating frequency bins.  These can then be set in the config file as a space-separated list, but will default to a sensible array of indices if none are supplied. Note that these should be supplied in units of 1/3, e.g.:
```
[model]
name = relative
gammas = -5 -3 -2 3
...
```

Minor improvements to relative likelihood model

---

pycbc/waveform/ringdown.py

Making the list of desired ringdown modes a string prevents issues with conflicting dimensions in the FieldArray of parameters.

Update ringdown format_lmns to accept whitespace-separated string.

---

bin/hdfcoinc/pycbc_multiifo_coinc_statmap
bin/hdfcoinc/pycbc_page_snrifar

If we have signals in a single detector, it causes significant little-dog background.
This change means we can remove these triggers manually (or a bad glitch, or whatever, just pointing to a time) from all backgrounds

Removal of a manual list of trigger times

---

bin/pycbc_make_skymap
examples/make_skymap/.gitignore
examples/make_skymap/GW150914.sh
examples/make_skymap/GW170817.sh

Restore the original use case where the frame files are automatically guessed,
which was broken by the addition of the --custom-frame-files option.
Improve the logging in case of failure of pycbc_single_template.
Remove an unused option.
Massive code cleanup.
Given the large change I will test this thoroughly and probably add a few examples, so marking as WIP.

pycbc_make_skymap: fix a bug, some improvements, and code cleanup

---

pycbc/distributions/joint.py

The ensure field array is a *very* slow function and should be avoided when possible to not bog down fast likelihoods where we don't have constraints.

avoid contains or conversions when not needed in joint dist

---

pycbc/waveform/multiband.py
pycbc/waveform/waveform.py

This adds a 'multiband' waveform approximant which can use a base approximant which supports 'f_ref' and 'f_lower' / 'f_final' to speed up waveform generation. The waveform is generated at different delta_f's within frequency bands and then stitched back together. 
Example,
```
get_fd_waveform(approximant='multiband', base_approximant='IMRPhenomPv3', 
mass1=1.4, mass2=1.4,
f_lower=20, f_ref=20, f_final=1000,
delta_f=1.0/1024, spin1x=0.5, spin1z=0.5,
bands='50', lengths='50', overlap=1)
```

add multiband waveform to speed up slow / long waveform approximants

---

bin/pycbc_optimal_snr

This is an attempt to make `pycbc_optimal_snr` support HDF injection sets. My initial hope was to seamlessly support all possible input/output cases (XML to XML, HDF to HDF, XML to HDF, HDF to XML) but I think just same-format support is sufficient.
At the moment, this is not quite working when trying to **write** HDF injections, due to issues with the approximant string (see discussion). It seems to work when writing XML files. I am opening it to gather opinions on the former case.
The different name of the coalescence time field makes the code slightly more complicated than needed; see the `get_gc_end_time()` function. It would be great if HDF injections could somehow understand `geocent_end_time` to mean `tc`, although it would also be ugly to special-case that in the `FieldArray` …

Support HDF injection files in pycbc_optimal_snr

---

pycbc/events/stat.py

the mchirp weighting got missed off in the coinc_lim_for_thresh stuff, which means that some background coincs were dismissed when they shouldn't have been

coinc_lim_for_thresh for BBH statistics

---

pycbc/waveform/ringdown.py

This corrects the order of arguments for the frequency domain ringdown waveform and ensures that the functions for the desired approximant are used.

Ringdown bugs

---

pycbc/distributions/constraints.py
pycbc/inference/models/gaussian_noise.py
pycbc/waveform/generator.py
pycbc/waveform/supernovae.py

This patch adds the core-collapse waveform model:
1. Added core bounce and post bounce waveform for core collapse supernovae. This uses a `.hdf` file containing principal component basis vectors to generate the waveforms. The principal components are generated using singular value decomposition of a catalog of numerical simulations. The waveform model is h = a_1 * x_1 + a_2 * x_2 + ... + a_n * x_n, where x_i are the principal component basis vectors and a_i are their coefficients. 
2. Added a constraint for the coefficients of the basis vectors that generate the core collapse waveform. The coefficients should be inside the two/three dimensional convex hull of the coefficients of the waveforms in a catalog.
3. For Bayesian inference, the coefficients are the variable parameters while the …

Core collapse supernovae 

---

bin/inference/pycbc_inference_plot_mcmc_history

Adds an executable to plot the checkpoint history stored in an MCMC inference file. Up to four different plots are possible, which are set with command-line toggles:
*  `plot-checkpoint-dt`: Plots the wall-clock time between checkpoints.
* `plot-act`: Plots ACT vs checkpoint iteration. For epsie, this will also plot the mean ACT over chains, and each chain vs iteration.
* `plot-effective-nsamples`: Plots the number of effective samples versus checkpoint iteration.
* `plot-nchains-burned-in`: Plots the number of chains that were burned in versus checkpoint iteration. For ensemble samplers, this is all or nothing.
Examples:
* [emcee pt](https://www.atlas.aei.uni-hannover.de/~work-cdcapano/scratch/prs/plot_mcmc_history/emcee_pt_test.png)
* …

MCMC history diagnostic plot

---

pycbc/inject/inject.py

This is a proposal for fixing #3395. Apparently the HDF injection code has trouble when the approximant field (or any other string field) is not static. The fix is based on the approach already used for handling static arguments.
I am not sure if this will break existing use cases, and I have not tested it with Python 2, but opening for consideration.

Fix error with approximant strings in HDF injections

---

pycbc/inference/sampler/dynesty.py

In this PR, I restore the functionality of writing logZ and dlogZ values at the 'finalize' step of dynesty sampler. It was lost in one of the earlier PR. It is a minor change.

Write logevidence and dloz at the 'finalize' step

---

bin/inference/pycbc_inference
pycbc/inference/io/base_hdf.py

Stores the config file used for pycbc inference to the output hdf file.
The config file is stored as a pickled String buffer to `config_file/{index}` in the hdf file. The `{index}` is an integer that keeps track of the write. If a job is restarted from a checkpoint, the config file will be stored as the last index + 1. This also allows you to track any changes that were made to the config file between restarts. (I suppose if I wanted to be super efficient I'd only store a diff on each, but since each config file is only a few hundred bytes, it's not worth it.)
A convenience method is added to the BaseInferenceFile to read the config file. By default it will load the last one saved, and will return it as a WorkflowConfigParser object. You can have it just return a string buffer though …

Write config file to inference file

---

pycbc/waveform/__init__.py
pycbc/waveform/waveform_modes.py

This is part 1 of 3 patches to replace #3456. This patch adds a module to the waveform package that will generate waveforms one mode at a time, without applying spherical harmonics. The convention I've used is that these functions return the real and imaginary parts of the complex hlm time series as a tuple. For the FD version, it will return the equivalent of the FFT of the real and imaginary parts of the complex hlm time series. That way we do not need to worry about handling complex -> complex FFTs.
Currently, this only works with the NRSurrogate (and so only the `get_td_waveform_modes` function actually does anything). The problem with the Phenom waveforms is they combine the +/-m modes together. There is a way to separate those by calling from two different phase and/or inclination …

Add waveform modes module

---

bin/inference/pycbc_inference_model_stats

Adds a script that will load samples from a file, recalculate the likelihood and prior for each point, then write it back out to a new file, along with any additional auxiliary statistics (e.g., SNR in each detector, max likelihood phase) that the model saves. Mostly useful for the nested samplers and emcee_pt/ptemcee, which do not store blob data, but can also be used to recalculate likelihood for a different model.
Depends on #3505.

Script to calculate stats, write to file

---

bin/hdfcoinc/pycbc_multiifo_add_statmap

The add statmap code is breaking when finding the most significant trigger for hierarchical removal if there are no triggers in a given detector combination.
In the dictionary comprehension it does argmax for each detector combo, if one is empty this produces an error.
This can be fixed by including an if statement in the comprehension to test that the array is non-zero in size.

Fix case where one detector combo has no foreground triggers

---

pycbc/io/hdf.py

When no --gating-veto-windows argument was given the following error arised:
`Traceback (most recent call last):
File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-v1.16.11/bin/pycbc_multiifo_coinc_findtrigs", line 113, in <module>
args.gating_veto_windows)
File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-v1.16.11/lib/python2.7/site-packages/pycbc/io/hdf.py", line 1012, in __init__
gating_veto = gating_veto_windows[self.ifo].split(',')
AttributeError: 'NoneType' object has no attribute 'split'`
This change should address the error

Address error when no gating veto argument was given

---

bin/minifollowups/pycbc_injection_minifollowup

We noticed that, in rare occasions, the single-template plots in the injection minifollowups are empty. This appears to be due to the fact that pycbc_injection_minifollowup compares the injection merger time to the science segments (instead of the analyzed segments) when setting up single-template plots. This pull request fixes the issue, and it also uses the injection merger time at the detector instead of the geocenter.

Fix empty plots in minifollowups

---

pycbc/vetoes/chisq.py
pycbc/waveform/bank.py

We've been tracking down a nasty issue in pycbc_inspiral recently. The symptom we saw was a BNS trigger with SNR ~ 12 and chisq ~ 1 per DOF. Except all the SNR was coming from a really nasty glitch *right* at the start of the waveform, for which we expect chisq to be large. Running this through `pycbc_single_template` found the expected large chisq.
We expected some problem in the chisq code, or in the GPU code, or in the new compressed waveforms, which meant it took us a long time to find the *actual* problem.
There's a bug in the sigmasq calculation for SPATmplt ... Or at least in the caching of it. We are not checking if the *lower* frequency has changed. So if the first template has a f_lower of 25Hz, all subsequent templates not using that f_lower will be affected.
I suspect this has …

Fix bug in pycbc_inspiral

---

bin/hdfcoinc/pycbc_plot_singles_timefreq
bin/plotting/pycbc_plot_qscan

Improvements to `pycbc_plot_singles_timefreq` and `pycbc_plot_qscan` after looking at recent minifollowup pages.
`pycbc_plot_singles_timefreq` changes:
* Remove the undocumented special case `--center-time -1` which is no longer used in the workflow.
* Restore the intended behavior of `--center-time`, i.e. the x-axis is now really centered at the given time. This makes it clearer when the plot intersects the boundary of a science segment.
* Describe the visual difference between externally-provided gates and autogates in the caption.
* Code cleanup.
`pycbc_plot_qscan` changes:
* Show the strain channel name (when available) in the plot and caption. In the minifollowups, this change makes it easier to see what detector a plot refers to.
* When plotting a chirp, plot it in all panels, and …

Minifollowup plot tweaks

---

bin/hdfcoinc/pycbc_coinc_mergetrigs

I noticed that `pycbc_coinc_mergetrigs` opens all input files in read/write mode, although it only needs to read them. Fixing that, and doing some other cleanup.

pycbc_coinc_mergetrigs: minor fix and cleanup

---

bin/hdfcoinc/pycbc_coinc_mergetrigs

@MPillas and I noticed that `HDF_TRIGGER_MERGE` files store duplicated live time segments (datasets `search/start_time` and `search/end_time`) when the inspiral jobs use bank splitting. This appears to be correctly taken into account by some of the codes reading `HDF_TRIGGER_MERGE` files (for example `pycbc_fit_sngls_by_template`), but not all (for example `pycbc_plot_throughput`). This patch deduplicates the segments right away when creating the merged triggers, so as to avoid confusion and errors downstream.

coinc_mergetrigs: deduplicate livetime segments

---

pycbc/workflow/injection.py

the default for LigolwAddExecutable is to _not_ store the output file, but for optimal_snr jobs the default _is_ to store these - this is the opposite of what is useful in most cases when the optimal_snr job is parallelised
The optimal_snr jobs in the parallelised case are not used individually anywhere, so intermediate_product is appropriate

update retention levels for opt_snr jobs in parallelised cases

---

examples/catalog/data.py
examples/catalog/stat.py
examples/catalog/what.py
pycbc/catalog/catalog.py

Add name used so pycbc.catalog can pick up the gwtc-2 sources. This also modifies some of the examples to demonstrate choosing the catalog.

update for gwtc-2 catalog

---

bin/inference/pycbc_inference_monitor
pycbc/workflow/core.py

This script monitors an inference output file. When that file updates, it generates a series of plots and makes a combined results page. See example here 
https://www.atlas.aei.uni-hannover.de/work/ahnitz/projects/tpage/results/html/checkpoints/1/
The plots generated are controlled by a config file. Multiple executables can be used as long as they use the the '--input-file' and '--output-file' options and multiple plots can be made for each by using subsections of their executable keyname. I.E. a second plot here could be made with a 'posterior-2' section. 
```
[workflow]
[results_page]
template-file = templates/orange.html
[executables]
results_page = ${which:pycbc_make_html_page}
posterior = ${which:pycbc_inference_plot_posterior}
[posterior]
[posterior-1]
z-arg = snr
```
The monitor is …

add script to monitor an inference job and generate updated plots and results page when it updates

---

pycbc/cosmology.py

The cosmology module uses an interpolator to speed up comoving volume to redshift transforms. Two interpolators are used; one for nearby (z < 1) and one for farway (z > 1). The nearby interpolator is run on the comoving volume values first. Any values outside of the range return nans. Then the faraway interpolator is run on the remaining. If there are any remaining nans after the second step, it's thrown to the astropy calculator.
The faraway should be run on the input comoving volume values, but due to a typo it is currently being given the output of the nearby interpolator... i.e., it's given a bunch of nans. Since it's given a bunch of nans, it just returns nans. Consequently, all comoving volumes with z > 1 are being passed to the astropy calculator, making the interpolator useless …

Fix bug in redshift from comoving volume interpolator

---

pyproject.toml
requirements.txt
setup.py

The issue reported in https://github.com/numpy/numpy/issues/16660 was fixed in https://github.com/numpy/numpy/pull/16666 and released as part of numpy 1.19.1, so pycbc should now be able to use those newer versions, and just avoid 1.19.0.

Unpin numpy, but avoid 1.19.0

---

bin/plotting/pycbc_plot_vt_ratio
pycbc/results/metadata.py

* Expand `--help` description to make it clear where the necessary files come from.
* Open the input files read-only.
* Replace assertion with a more appropriate argparse error.
* Add metadata to the output file as done in other plotting scripts.
* Add support for writing metadata to PDF images.
* Code cleanup.

Improve pycbc_plot_vt_ratio

---

bin/hdfcoinc/pycbc_page_snrchi

Updated the file `bin/hdfcoinc/pycbc_page_snrchi` to include χ2 in both the header and caption of the plot on the results page.
Example: https://ldas-jobs.gw.iucaa.in/~arthur.tolley/snrchi_test_page/

Results page plot changes

---

pycbc/pnutils.py

Modified the _get_imr_duration function inside 'pnutils' to include the approximant SPAtmplt (TaylorF2)
Thanks Tito for the help with git

Added SPAtmplt option in _get_imr_duration

---

pycbc/waveform/generator.py

This is part 2 of 3 patches to replace #3456. This adds a radiation and detector frame generators to generate waveforms one mode at a time. This can be used by a model (next patch) to numerically marginalize over phase.
The radiation frame generators are the same as the standard CBC TD and FD generators, it's just that they call `get_(t|f)d_waveform_modes` rather than `get_(t|f)d_waveform`.
The detector frame generator then generates the waveforms and returns a dictonary of detector names -> mode -> frequency domain versions of ulm and vlm. The ulm and vlm are the real and (-) imaginary parts of the complex waveform time series.
Since much of the functionality between this new detector frame generator, the polarization generator, and the standard generator are the same, I've create a new …

Add modes generator

---

pycbc/inference/models/brute_marg.py
pycbc/inference/models/marginalized_gaussian_noise.py

Changes the polarization marginalization model to store the maxL log likelihood ratio. Also has the brute force marginalization model use this instead of the marginalized log likelihood ratio, as it is currently.

Store max likelihood loglr in polarization and brute force model

---

bin/inference/pycbc_inference_extract_samples

When extracting posteriors, `pycbc_extract_samples` will do some checks on the metadata to make sure the two files can be merged. This check will even happen when a single file is given, in which case it's just checking values against itself.
An issue that arises is that if a one or more values are nans, `numpy.isclose` will by default return False. This causes extract samples to fail when working on some dynesty files, in which the dlogz is nan. This sometimes happens when constraints are used; I'm not certain why. In any event, this patch allows extract samples to still work in this case by telling `numpy.isclose` to treat two nans as being equal.

Allow extract samples to handles nans

---

bin/inference/pycbc_inference

Stops child nodes from printing logging warnings to stdout, so you don't get the same warning repeated a bunch of times when running `pycbc_inference` with MPI.

Silence warnings from child nodes in MPI

---

pycbc/detector.py

This adds two additional methods to the 'project_wave' method of the Detector class. These allow for more approximant ways to project the polarizations into the detector frame. The purpose is for testing different approximations in likelihoods and like-for-like cross comparisons. The two methods are (1) a basic apply constant factor for the polarizations (2) allow fp/fc to vary over time. Neither includes doppler corrections like the default 'lal' method does.
For reference (1) seems to be the dominant correction for signals of length several hours. I am seeing the mismatch between the result from the 'lal' method and the 'constant' decreased by an order of magnitude when applying only the time varying polarization corrections. 
I am not doing so now, but I may consider adding in another …

add method option to project wave to use alternate approximations

---

pycbc/inject/inject.py

This enables a 'detector_projection_method' option to set the option used in project wave. It can be done on an injection by injection basis as any other configuration coming from an hdf config file.

add option to set detector projection method in the injection file

---

.github/workflows/basic-tests.yml

Slightly change the logic in github actions so the upload to testpypi is on a commit to master, and an upload to pypi is on a tagged version.

pypi on tag, testpypi on master

---

pycbc/inference/models/gaussian_noise.py
pycbc/inference/models/relbin.py

This updates the relative model to allow it to handle changes in the antenna pattern as a function of time which can greatly affect the PE of very long duration sources, such as those observed by CE and ET. This includes only the polarization factor corrections and not the doppler shift. It is implemented only as a constant correction on the same scale as the frequency binning. Since it is applied in the frequency domain this should not be used with models with higher order modes or wherever there is signfiicant confusion about what time a particular frequency maps to.

allow relative model to be able to handle time changing antenna patterns

---

pycbc/waveform/ringdown.py

If only a single lmns identifier is given (e.g. lmns = 220), `pycbc_create_injections` casts this to a float. This was not recognised by format_lmns.
Now a float is cast to an integer, then to a string to correct this.

Allow for single float input in format_lmns.

---

pycbc/conversions.py

The lmn_from_other_lmn conversions were missing from the list. 
These conversions claim to accept floats, but only work with numpy arrays. Now both should work with giving the same output type as the input. 
However, if instead of a float, integers are given as input, the output will instead be changed to an array. 
Should that be dealt with also?

Add lmn_from_other_lmn conversions to list; fix bug

---

bin/pycbc_process_sngls
pycbc/io/hdf.py

`pycbc_process_sngls` can crash when called with `--store-bank-values`. It tries to call `SingleDetTriggers.get_column()` for every dataset in the bank file, however not all possible bank datasets are accessible as properties of `SingleDetTriggers`. In particular, the error I got happened because of the `approximant` dataset.
This PR adds a check to `pycbc_process_sngls` so that unsupported bank datasets just print a warning and are ignored, instead of producing an exception. In addition, it:
* Adds the `approximant` property to `SingleDetTriggers`, which seems useful to have.
* Postpones the creation of the output file to reduce the chance of creating bogus empty files in case of early errors.
* Carries over the `search/start_time` and `search/end_time` datasets, which makes it easier to …

pycbc_process_sngls: fix error when using `--store-bank-values`

---

bin/all_sky_search/pycbc_coinc_findtrigs
bin/all_sky_search/pycbc_fit_sngls_binned
bin/all_sky_search/pycbc_fit_sngls_by_template
bin/all_sky_search/pycbc_fit_sngls_split_binned
bin/all_sky_search/pycbc_sngls_findtrigs
bin/minifollowups/pycbc_page_snglinfo
bin/minifollowups/pycbc_sngl_minifollowup
bin/plotting/pycbc_plot_singles_vs_params
bin/plotting/pycbc_plot_trigrate
bin/pycbc_inspiral
bin/pycbc_inspiral_skymax
bin/pycbc_live
bin/pycbc_process_sngls
bin/workflow_comparisons/offline_search/pycbc_injection_set_comparison
examples/live/run.sh
examples/search/analysis.ini
examples/search/plotting.ini
pycbc/events/coinc.py
pycbc/events/eventmgr.py
pycbc/events/ranking.py
pycbc/events/stat.py
pycbc/io/hdf.py

`stat.py` has become a little bit difficult to work with due to the large amount of classes now being needed to implement even minor changes. I want to rework this according to the pasted image. So far I've implemented this basically as illustrated below, with only those classes. It's possible this could be compressed further, but perhaps this is better? Clearly this PR will not work alone as we will need to remove completely the old stat executables, and hook the new ones up to the renamed methods here. However, I think it's worth seeing first if this is how we want this to look. I think there are some design choices here (most of the questions in red/green in the image) which are not obviously clear.
There's also the question of how to handle singles. At the moment, as I am removing the …

Reorganizing stat.py

---

bin/plotting/pycbc_plot_singles_vs_params
pycbc/io/hdf.py

I left one FIXME in #3535. Here I try to resolve it. In particular I want pycbc_plot_singles_vs_params to be able to use the new `ranking.py` interface for ranking singles. This uses the `SingleDetTriggers` class, which cannot easily access this. To fix this I add a new `get_ranking` method, which calls directly to `ranking.py`. However, to ensure that `SingleDetTriggers` is in the format that `ranking.py` expects, I added a `__getitem__` method. This might be useful in other places this code is used as well (for e.g. @titodalcanton 's changes in pycbc_process_sngls).
This doesn't need any config changes, but does fix some edge cases where pycbc_plot_singles_vs_params would fail when it's help would claim it would succeed (which was also true before the changes in #3535).

Add getitem to singledettrigs

---

examples/live/.gitignore
examples/live/check_results.py
examples/live/generate_injections.py
examples/live/run.sh

This is a cleanup PR paving the way for less trivial upcoming changes to the PyCBC Live example/test. Most of the PR is just white space and formatting stuff which I did not want to mix with less trivial changes. However, I also noticed that each injection was being done twice (effectively halving its luminosity distance). I fixed that by actually doing a single injection at the right distance.

Cleanup PyCBC Live example

---

bin/pycbc_process_sngls

As discussed previously, this corrects the live time saved by `pycbc_process_sngls` in case a veto file is used. It also fixes a recently introduced variable name error.
Still needs test.

pycbc_process_sngls: subtract vetoed time from live time

---

examples/live/.gitignore
examples/live/generate_injections.py
examples/live/run.sh

Due to previous limitations of the HDF injection code, which have been addressed a while ago, the PyCBC Live example used to make two injections in two separate rounds, calling `pycbc_condition_strain` twice and slowing down the test. This is no longer necessary, the injections can be done in a single round.
Note that I am using `S32` as the dtype for the approximant field, which is a bit annoying. If I use `str`, the injection code is unable to read the approximant.
Fixes #3395.

Simplify injections in PyCBC Live's example

---

bin/pycbc_upload_xml_to_gracedb
pycbc/io/live.py

This tags each offline GraceDB upload with a PyCBC version string and install path, and the absolute path to the input file which provided the candidate. It also adds a `--log-message` option which can be used to add an extra message to the log (e.g. `--log-message 'Candidate from hyperbank search on HLV C01 data'`).
Example: https://gracedb-playground.ligo.org/events/T368754/view/

Add more info to offline GraceDB uploads

---

pycbc/detector.py

This adds a method to add a custom detector on the earth defined by its lat/lon and the orientation defined as the azimuthal angle of the y-arm (so 0 is y-arm pointing due north). The patch also makes lalsimulation optional for this module.

add method to add custom detector

---

bin/pycbc_create_injections

This allows one to set start / end times instead of a number of injections to draw. This is the most common scenario for search workflows and is sufficient to enable pycbc_create_injections to produce reasonable files for use with the offline analysis. There may be a couple distributions that should also be added for simplicity, but I think even there most things can be done with inline transforms, etc. 
Example config file and command line
```
[variable_params]
tc =
[static_params]
mass1 = 37
mass2 = 32
ra = 2.2
dec = -1.25
inclination = 2.5
coa_phase = 1.5
polarization = 1.75
distance = 100
f_ref = 20
f_lower = 18
approximant = IMRPhenomPv2
taper = start
[prior-tc]
name = uniform
min-tc = 180
max-tc = 200
```
```
pycbc_create_injections --verbose \
--config-files test.ini \ …
```

add options to pycbc_create_injections for use with offline search codes

---

examples/live/run.sh
pycbc/filter/resample.py
pycbc/inject/inject.py
pycbc/strain/strain.py
pycbc/types/timeseries.py

This consolidates some of the from_cli function in strain.py between the fake data and read-from-file data paths. I'm not sure anymore why there was so much duplication, but it seems like we can remove it now. One change to the path which will cause results to differ is that injections are done *after* resampling. This significantly improves the ability to inject long waveforms for CE / ET studies without memory becoming unmanageable.

simplify strain from cli, move injections after resample

---

pycbc/inference/models/__init__.py
pycbc/inference/models/gaussian_noise.py
pycbc/inference/models/marginalized_gaussian_noise.py

This is part 3 of 3 to replace #3456. This adds a model to numerical marginalize waveforms with sub-dominant modes over both phase and polarization. Similar to the polarization model, this is done by creating a grid of points in phase and in polarization. The loglr function generates the waveforms once, then cycles over the polarization and phase grid and applies the appropriate multiplicative factors. For higher mode waveforms, this requires generating the waveforms mode-by-mode, and so uses the FDomainDetFrameModesGenerator described in #3483 . 
At the moment this only works with the NRSurrogate waveforms. Extending support to other waveforms with sub-dominant modes will require some work on the lalsimulation side and/or the `waveform_modes` module (see #3482). This could be extended to …

Add numerical phimarg model

---

bin/all_sky_search/pycbc_stat_dtphase
pycbc/inference/models/single_template.py

As someone noted, I mixed up some of the inclination conventions. This was a mistake in single_template and the pycbc_dtphase code. In both, it doesn't really affect anything (other than causing the polarization angle to now be inconsistently define). I've tested both codes give the same results before / after. However, we should bring this in line to avoid confusion and further mistakes.
To be clear this wasn't an issue because the polarization angle in both cases was treated as a nuisance angle so you can transform from 'broken' to the 'fixed' convention by a rotation. If someone wanted to look at measuring the polarization angle, it would be inconsistent with the literature though.

fix inclination conventions

---

bin/pycbc_optimize_snr

Also includes the relevant arguments that are needed to customise the optimizers. Changed the default differential_evolution parameters from (100,200) to (50,100).
Within the compute_network_snr function, the addition was needed for the shgo optimizer.
The default optimizer is still differential_evolution, used the try & except but unsure if this is necessary.

Included an option to choose the scipy optimizer

---

bin/pycbc_live
pycbc/__init__.py
pycbc/frame/frame.py

`lal.GPSTimeNow()` does not return the fractional part, which is a bit inconvenient when monitoring the O(1 s) lag of the early-warning configuration of PyCBC Live. So here I am switching to Astropy to get the current GPS. This is probably not the most precise method (there are ongoing [issues](https://github.com/astropy/astropy/issues/6190) with GPS times in Astropy) and @duncanmmacleod suggested using GWPy as a more precise alternative. Opinions are welcome, given that GWPy would be an extra dependency and I do not think the Astropy precision issue is critical here.
This PR also simplifies the logging a bit by pre-inserting the MPI rank in the format string, so we do not have to carry it along every time.

PyCBC Live: use Astropy to get a more precise current GPS time

---

pycbc/waveform/waveform.py

Originally, to figure how the right flow to use for tapering fd injections, it would do an iterative search decrementing the flow by 1, this is bad once flow is small. This changes to a relative search which should be more broadly applicable.

use relative search for flow in get_td_waveform_from_fd

---

bin/inference/pycbc_inference_plot_mcmc_history
pycbc/workflow/inference_followups.py

Adds MCMC history plots as an optional diagnostic in the inference workflow. Adds caption to the plots for displaying on results page. Also adds markers to the plots to make them more legible when they are only 1 or fewer points. Example can be found in section 6, [here](https://www.atlas.aei.uni-hannover.de/~work-cdcapano/projects/pycbc_inference/gw150914_example/gw150914_test-emcee/).

MCMC history in workflow

---

pycbc/strain/strain.py

Previously, `pycbc_make_skymap` was unable to run if there was no FFTW module available. This fix allows the use of MKL instead.

Fixing bug with FFTW, using MKL if FFTW is not available

---

test/test_coinc_stat.py

This PR re-proposes the unit test for the coinc stat module that came with #3586, edited as suggested by @spxiwh. For now, this only tests the stats that do not rely on auxiliary files, but the test can be easily expanded to also create the necessary files to test the other stats.

Add basic unit test for coinc stat module

---

pycbc/types/config.py
pycbc/workflow/configuration.py

This moves the interpolating features added to ConfigParser to a separate class which can be called outside of a workflow context (and without partially pulling in a Pegasus dependency).  This also drops the glue.pipeline dependence within the core pycbc library (some old exes still remain).

Move interpolation into new parent class of WorkflowConfigParser

---

pycbc/detector.py

This adds the capability to expand the pycbc detector set with a config file. The config file can either be read using the 'load_detector_config' function manually (i.e. in a custom script), or it can be autoloaded using the environment variable "PYCBC_DETECTOR_CONFIG". 
I've written it in such a way that we can add other methods in the future for describing detectors. The thinking is that we may want different formats for things like space-based detectors. 
Example config file
```
[detector-r1]
method = earth_normal
longitude = -2.0840567691659397
latitude = 0.810795263791696
yangle = 4.084080696105957
```

add detectors with config file

---

pycbc/detector.py
test/test_detector.py

This allows custom detectors in pycbc to be transformed to an instance of the lal detector struct.
There are some things to note here. First, some of the fields if you look at the lal code are unused, and the 'midpoint' ones in particular are a bit misused. I've noted this in our documentation in case this changes. I think the intention was to eventually implement code that didn't assume a long arm length, however, that does not exist in lal at the moment (I've carefully read what the code is doing). 
Depends on #3597

generate lal detector type from pycbc detector

---

examples/live/check_results.py
examples/live/run.sh
pycbc/strain/strain.py
pycbc/types/timeseries.py

* set the amount of data to create to a multiple of 32 so that every file is the same size
* fix a rounding issue in time slice
* found edge case where the index was within floating point precision of an exact index value. This occured at exactly an integer start time which causes condition strain (and write_frame) to fail due to needing to output second boundary frame files. This case is also not what was intended by the rounding mode option to time slice, whereby you might ask for a time *in between* sample rates and that's not clear we want to round to the nearest (hence the option). However, if we give the exact right time for a given index value, we do want it to use that index. 
* fix issue in rounding of factor between internal raw data sample rate and the strain data 
* found edge …

fix plive test

---

pycbc/noise/reproduceable.py

The noise generation fails when you said to something that wasn't exactly a float. I just found a case also where this occurs due to a difference in float / int math between python2 / 3, so this needs to be explicit here.

make sure things are ints in noise generation that need to be

---

bin/pycbc_make_skymap

Passing the approximant argument into `bayestar-localize-coincs`.
BAYESTAR uses the `TaylorF2` waveform instead of `SPAtmplt` so I had to add an if statement there.

Adding the functionality of passing the approximants into BAYESTAR

---

pycbc/inference/sampler/dynesty.py

The rwalk2 method we use for dynesty will accept points if the new loglikelihood is the same or greater than the current max point. This may be causing issues with drawing bounding ellipsoids. This changes it to only accept if a new point has greater logl.

Only accept points that have larger logl in dynesty rwalk

---

bin/all_sky_search/pycbc_dtphase

Applies #3577 to `pycbc_dtphase`, makes `pycbc_dtphase` a bit more self-explanatory, and removes a couple unused imports.

pycbc_dtphase: fix inclination convention, UI improvements and cleanup

---

pycbc/events/stat.py

Previously, the search would break if doing a search which did not contain either H1 or L1, as the reference network was hardcoded to HL.
This PR means that a kwarg can be added for reference IFOs as `--statistic-keywords reference_ifos:H1,V1`
The default value is H1,L1, so previous behaviour is kept as default
output files have been tested and the files from default behaviour exactly matches the H1,L1 case, as well as with the code before this is implemented

add kwarg for IFOs in reference network

---

.github/workflows/basic-tests.yml
companion.txt
examples/live/run.sh
pycbc/filter/matchedfilter.py

Patch #3603 broke pycbc_live's ability to interface with Bayestar by making the SNR timeseries in the XML files 1 sample too short when it is obtained using the followup-ifo path.
Here I match how the followup SNR timeseries is sliced (which was wrong in two places before #3603, but somehow cancelling out), with the normal SNR timeseries (which was always correct).

Pycbc_live must make output that Bayestar can use

---

bin/pycbc_optimize_snr

Adding the necessary changes to pycbc_optimize_snr to allow for the usage of the `pyswarms` Particle Swarm Optimization optimizer.
The package is configured slightly different to scipy and so a few `if` statements are needed to ensure the right code is called. Currently this doesn't look too appealing so if there is a better way to potentially group these if statements under one umbrella then I would like to include that.
`pyswarms` isn't included in the installation of pycbc so instead of failing on the import there is a `try -> except` instead.
I'm thinking also of collecting the iteration arguments under the same argument, even if they have slightly different meanings.
Finally, if there are any formatting improvements that can be made I would be glad to hear them as well!

pycbc_optimize_snr: add support for particle swarm optimization

---

examples/live/.gitignore
examples/live/run.sh
pycbc/events/coinc.py
pycbc/events/stat.py

Reimplement `PhaseTDStatistic` based on the code that was in place before #3535, and modify the PyCBC Live test to use it. Some extra changes are needed to fix some errors related to a `from_cli()` method modifying some of the arguments and breaking further calls to the same function.
Closes #3580. Closes #3584.
I have not tested that the resulting values are actually correct or equivalent to the old code, though, so marking as WIP.

Reimplement PhaseTDStatistic

---

pycbc/inference/io/dynesty.py

@sum33it @cdcapano I encountered a case where the weight sum is nearly, but not quite 1, and where there are sufficient samples so that a point may want to access higher than this value in the distribution tail. This occurs because of numerical error in the sampler weights. The immediate problem is that this prevents resampling to an equal-weight distribution.

re-normalize the cumulative weights to 1 to avoid numerical issues when resampling weighted samples

---

bin/pycbc_upload_xml_to_gracedb

Add options in pycbc_upload_to_gracedb:
- to check if the event already exists in gracedb before uploading it (this becomes default behaviour)
- to not upload anything
- to choose to use a naming convention for the XML file https://dcc.ligo.org/LIGO-T050017/public

gracedb upload script - add options to make output without upload

---

pycbc/distributions/__init__.py
pycbc/inference/sampler/base_mcmc.py

These chages are intended to address the issue raised in #3619, where these imports no longer worked after #3589

Changing two broken imports for ConfigParser

---

examples/live/check_results.py
examples/live/generate_injections.py
examples/live/run.sh

* Fix the injection recovery check in PyCBC Live's test, which was effectively disabled.
* Inject the two signals at different sky locations, to make BAYESTAR's results more interesting.
* The injected right ascension and declination were given in degrees, while they take radians (not a problem per se, but it got me confused for a moment when I plotted BAYESTAR's results).
* Remove some duplication in the simulation parameters.

Various fixes to PyCBC Live's test

---

examples/live/check_results.py
pycbc/noise/reproduceable.py
test/test_noise.py

Timeseries with different epochs (+ 10s difference) before bugfix:
Timeseries with different epochs after bugfix:
(Bug found by me, fix as suggested by @spxiwh)

fix reproducible noise bug

---

bin/pycbc_inspinj2hdf

This PR adds support for legacy waveform strings in the `pycbc_inspinj2hdf` executable. In cases when no phase order is specificied in the waveform string, the default value of `-1` is used.

Add support for legacy waveform strings

---

pycbc/inference/burn_in.py
pycbc/inference/sampler/base_mcmc.py

There currently is a bug in pycbc inference, where, if you only use the nacl test, the sampler will exit as soon as it gets a non-zero ACL, regardless of whether the nacl test passed or not. The bug is a symptom of some of the convuluted logic used to determine when to exit when effective nsamples are requested. This patch fixes that bug, and also simplifies the logic a bit. Specifically, this does two things:
1. Currently, the nacl test will try to save its acls as the sampler's acls, to avoid calculating ACLs twice. The problem with this is the ACLs calculated by the nacl test are rarely the actual ACLs used (since we usually run with multiple burn in tests), so this doesn't save much. It also has significant effects on the number of effective samples, which in turn affects when the …

Simplify effective nsamples logic and don't try to use nacl ACLs

---

bin/pycbc_merge_inj_hdf

This PR creates an executable that is able to merge pycbc HDF5 injection files. 
This executable was added specifically to merge optimal_snr files, but will generically support any pycbc HDF5  injection file.

Executable to merge HDF5 injection files

---

bin/pycbc_upload_xml_to_gracedb

This warning kept coming up:
```
python2.7/site-packages/h5py/_hl/dataset.py:313: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
"Use dataset[()] instead.", H5pyDeprecationWarning)
```
it was annoying
This removes the deprecated bit

silence annoying warning messages in upload script

---

.github/workflows/basic-tests.yml
.github/workflows/distribution.yml

This PR is an attempt to start building PyCBC binary wheel files. It would be nice for many users not to have to build pycbc directly but to be able to install a pre-built binary. This is an attempt to create those binaries using the 'manylinux' container which is the standard for redistributable linux wheels.

try building wheels

---

bin/all_sky_search/pycbc_fit_sngls_over_multiparam
bin/minifollowups/pycbc_single_template_plot
pycbc/io/record.py
requirements.txt

Newer version of h5py return a dtype descriptor with metadata, this caused our functions for handling record arrays to fail when constructing compound types as the return product had an unexpected format. This patch attempts to coerce it to the required format for constructing a compound type with numpy. 
This should hopefully allows us to move forward with h5py and when we can drop python2.7 support enable us to use h5py > 3 as a base which has a number of useful improvements.

unpin h5py and fix issue in descriptor usage of compund types

---

bin/pycbc_make_skymap
pycbc/dq.py
pycbc/types/optparse.py

Adds an option to `pycbc_make_skymap` that queries the segment database and excludes detectors having missing or vetoed data during the requested time interval. The query is defined through the `detector:+flag,-veto` syntax already used elsewhere in PyCBC.

pycbc_make_skymap: ability to query segment database

---

examples/inference/relative/relative.ini
pycbc/inference/models/relbin.py

I've encountered dynamic range issues when trying to push ET + CE analyses. One reason for this is due to extending the CE analysis artifically down to 2 Hz where the PSD is very large. The current code does not allow setting different options per detector for the relative model. This patch attempts to do that.

try to make relative model independent of detector

---

pycbc/inject/inject.py

This fixes an issue for very long injections when using one of the non-lal injection methods. They assume a constant time shift, which may be OK, but only towards the end of the waveform. This sets the reference time for this calculation to the geocentric time of coalescence (provided by keyword argument from the injection code) rather then rely on an guess internally which will be inaccurate for long signals.

set reference time for injections, used for some projection methods

---

pycbc/inject/inject.py
pycbc/types/timeseries.py

Needed this for a project I was working on and thought it would be generally useful... this adds the ability to create arbitrary injections using a time series. You have to provide a filename containing the time series, a GPS time to inject into each detector, and a `ref_point` specifying what point in the time series corresponds to the GPS time. You can also apply a phase shift and amplitude scaling.
For example, this config file would generate glitch injections in H1 using the GW170817 glitch that was recovered by BayesWave, with random phase and amplitude:
```
[static_params]                                                                 
approximant = fromfile                                                          
filename = L-L1_CLEANED_HOFT_C02_T1700406_v3-1187008667-4096.gwf …
```

Add FromFile injection type

---

bin/inference/pycbc_inference_plot_posterior
pycbc/inference/option_utils.py

This patch adds a new option to add in plotting injection parameters which are separated clearly by time. Instead of giving up, we add an option which allows the code to pick a single injection which is closest in time to the posterior results to compare.

allow pycbc plot posterior to compare parameters with the nearest injection

---

pycbc/inference/models/marginalized_gaussian_noise.py

The `MarginalizedHMPolPhase` records the max likelihood phase as `maxl_phase`, but this isn't being included in the returned `current_stats` because the `_extra_stats` call it `max_phase`. This fixes that.

Properly record maxl phase in HM marginalized model

---

pycbc/waveform/plugin.py
pycbc/waveform/waveform.py

I've run into a case where I need to modify a waveform returned by fd waveform sequence. This is a good opportunity to enable the plugin interface to enable people to provide waveforms of this format externally.

add ability to set fd sequence with plugin

---

pycbc/detector.py

The detector model produces warnings about 'ragged' numpy arrays. This is in fact true when you provide a array for one argument say to 'atenna_pattern' but not the others. This is caused by packing values into a "array" where the rows are non-equal size. This is a shorthand to avoid bookkeeping and so this patch removes the warning message in the way suggested by numpy.

silence ragged warnings

---

pycbc/strain/strain.py

Note that the 'injection-scale-factor' option is advertised as both 'multiply injections by this factor' and 'divide injections by this factor' in the single-detector / multi-detector interfaces.  This has not been changed in this PR so far, but it is highly suspicious.
The two descriptions should not both be correct.  So which one ought to be changed?

fixes to help msgs for injection group

---

pycbc/workflow/minifollowups.py

This PR fixes an inconsistency with how tags were propagated to mini followup jobs as part of the coinc workflow. Currently, tags are only propagated for foreground follow up jobs: https://github.com/gwastro/pycbc/blob/f8f57150a96439c12720961796e47e53dce2b075/pycbc/workflow/minifollowups.py#L102-L103
This PR incorporates the same tagging code for the injection and single detector follow ups.

Support tagging for additional minifollowup jobs

---

pycbc/strain/strain.py
pycbc/types/optparse.py

#3057 forgot to include the `nargs='+'` kwargs, creating problems when the `--injection-f-ref` and `--injection-f-final` multidetector options are given a single parameter like `10`.
Fixes #3662.

Fix missing bits from #3057

---

pycbc/inference/io/base_hdf.py
pycbc/inference/models/gaussian_noise.py

Adds a couple of convenience functions, `read_data` and `read_psds` to the inference base hdf file class, to make it easier to load the data and PSDs into FrequencySeries (which I frequently find myself doing). Also makes it so that you can provide the data and psds dictionary to `BaseGaussianNoise.from_config`. If they are given, the data and PSDs will not be loaded from the frame files, which always takes a long time. Combining, you can now load the model using an inference result file by doing:
```
from pycbc.inference import (io, models)
fp = io.loadfile(inference_file, 'r')
data = fp.read_data()
psds = fp.read_psds()
cp = fp.read_config_file()
fp.close()
model = models.read_from_config(cp, data=data, psds=psds)
```
This is a step toward an executable to plot max likelihood waveforms, …

Make it easier to load data and models

---

setup.py

We should be in the habit of proactively declaring the python version supported so that incompatible version are not installed through pypi. Currently, this is 2.7, and >=3.6.

add intended python requirement

---

pycbc/conversions.py

In the conversions module, the lalsim function called in final_spin_from_initial is currently giving an error
"TypeError: in method 'SimIMREOBFinalMassSpin', argument 3 of type 'REAL8'"
This PR fixes the bug by ensuring the masses are floats.

Fix bug in final_spin_from_initial

---

pycbc/inference/models/base_data.py
pycbc/inference/models/gaussian_noise.py

When doing lots of inference jobs on fake data and with possibly many detectors, the output file set can be huge mostly due to the size of the data set stored internally. This allows one to skip that by adding the following option to the model
```
[model]
no-save-data = 
...
...
```

add option to make saving data optional in inference files

---

bin/inference/pycbc_inference_plot_posterior
pycbc/io/record.py

@cdcapano I found one more case that was a problem with field array. It could now (after the past patch) get into a loop due to how geattribute and getitem both refer to each other!. This resolves that so there can't be a loop when an attribute fails to be read, instead it will up-report the problem.

fix loop on failed attribute

---

pycbc/types/frequencyseries.py
pycbc/types/timeseries.py

Add method to just shorten a very common use case of plotting a time or frequency series. This just wraps the matplotlib function and passes any keywords you give it to the plot command. 
```
from pycbc.waveform import get_fd_waveform, get_td_waveform
hp, hc = get_td_waveform(approximant="SEOBNRv4", mass1=10,
mass2=10, f_lower=30, delta_t=1.0/4096)
pylab.figure()
hp.plot()
pylab.figure()
hp.to_frequencyseries().plot(label='test')
import pylab
pylab.legend()
pylab.xscale('log')
```
Produces

simple convenience plot method

---

pycbc/strain/strain.py

Continuing in the "things that don't work in LISA series". Two things are addressed here:
* The `sample-rate` option is hardcoded to an `int`. While I think that one could always just give `fake-strain-sample-rate` while there's no *actual* LISA data (and never need to resample) there might be used cases that need resampling with LISA. So I turn this to float, and let's see if anything breaks.
* An issue we've noticed, let's say we are using LISA's sample rate of 1 sample every 15 seconds. If one then requests a data duration that is *not* a multiple of 15, the code would return something, but it would not really be valid. In particular the `delta_t` of the returned timeseries is not quite what was requested. At the moment I address this by raising a failure if this happens. However, it …

Fix a couple more LISA problems

---

pycbc/dq.py
pycbc/io/__init__.py

The code that queries the segdb was a bit inconsistent in how it printed debug info when the query fails. This makes sure all debug info goes to stderr, and does it consistently regardless of whether a veto definer file is used or not.

Improve error logging when querying segdb

---

bin/pycbc_create_injections

The current description of pycbc_create_injections references using a 'distribution' section for each variable parameter. 
This should be a 'prior' section for each parameters, this PR reflects this change.
The description still refers to a 'distributions' module which I believe is what it is still called so no changes there.

pycbc_create_injections: Updating description from 'distribution' to 'prior'

---

pycbc/__init__.py
pycbc/inference/models/brute_marg.py
test/test_infmodel.py

Add test to compare some of the polarization marginalized models. This looks at the single template and the brute force + marginalized_pol models (in combination, not individually).

test pol marg models in unittest

---

bin/pycbc_live

Improving PyCBC Live arg `max/min-psd-abort-distance` helper message as per @titodalcanton request.
Added explanation for `max/min-psd-abort-distance` as follows:
> Safety BNS horizon distance (in Mpc) above/below which a detector's data is discarded.

Adding helper message for 'psd-abort-distance' used by PyCBC Live.

---

pycbc/mchirp_area_improved.py

[`calc_areas`](https://github.com/gwastro/pycbc/blob/master/pycbc/mchirp_area.py#L90) function of `mchirp_area.py` presented some repetitive behaviour for each of the CBC categories. Since this repetition makes it quite a long function, we defined a new function to compute the area in the chirp mass contour inside a m1m2 region, common to all CBC cases (`get_area`).
A sanity check was performed applying both codes to the same set of events and configuration: [run_file](https://github.com/veronica-villa/source_probabilities_estimation_pycbclive/blob/master/sanity_check.py), [sanity_check_results](https://github.com/veronica-villa/source_probabilities_estimation_pycbclive/blob/master/mchirp_area_improved_sanity_check.txt).

Improve of area calculation on mchirp_area.py

---

bin/pycbc_live

Trivial change to allow frame files with colons in channel names, as in `H1:H1:STRAIN`.

PyCBC Live: allow colons in channel names

---

pycbc/conversions.py

In the conversions module, there is a function that calls SimIMREOBGenerateQNMFreqV2fromFinal from lalsuite to get the frequency and damping time for a given (l,m) mode. That function only supports the modes (2,2), (2,1), (3,3), (4,4), (5,5). Currently, if a different mode is selected, the function returns the wrong values instead of raising an error.
This PR adds a check in the pycbc code to ensure that only supported modes are requested, and raise an error otherwise.

Raise error in conversions if unsupported (l,m)

---

bin/pycbc_make_skymap

This came as a request from admins at the Livingston cluster and @titodalcanton to reduce the queries on the standard segments server (https://segments.ligo.org), and instead to use the backup server (https://segments-backup.ligo.org) which has a higher bandwith. This change allows us to choose this server natively.

Add option for segment server when making sky maps

---

bin/all_sky_search/pycbc_coinc_hdfinjfind
bin/all_sky_search/pycbc_dtphase
pycbc/events/stat.py
pycbc/filter/matchedfilter.py
pycbc/frame/frame.py
pycbc/inference/io/dynesty.py
pycbc/types/array.py

This PR replaces all instances of `numpy.int` with the builtin `int`.
This resolves a deprecation warning from numpy 1.20, see
<https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated>.

Replace all references of numpy.int with int

---

bin/hwinj/pycbc_insert_frame_hwinj
pycbc/strain/strain.py

@SergeiOssokine reported some strange behaviour in the `hwinj` code where it would inject an injection at the wrong time.
This was diagnosed to be an issue in how pad-data is handled after the recent consolidation of code in the strain module. In particular at the moment if somebody uses any of the simulated data options, and does not explicitly set `pad-data` to 0, they will not get the correct amount of data as the padded data will be removed even though it was never added!
I'm proposing to fix this by correctly adding pad-data into the simulated options. I think this *is* needed as one might still try to high-pass filter this data (even if it isn't really adding anything to do that). 
I'm also a bit confused by having the default pad-data be 8. I guess here the sane default for …

Fix incorrect data generation for simulated noise

---

pycbc/dq.py
pycbc/frame/losc.py

This pulls in a hack I used for O2, but mainlines it in a nicer way. The idea is to allow for the analysis of the 170608 time in a more uniform way as the other runs. The key factor is that the Hanford data was released as a separate run name by GWOSC so we need to be able to retrieve this name.

handle 170608 in a nicer way

---

bin/plotting/pycbc_page_segplot
bin/plotting/pycbc_plot_gating

This PR resolves the issue noted in #3698 by removing use of a custom `mpld3` plugin that is no longer functional with the most recent version of `mpld3`. An example output plot is [uploaded here](https://github.com/gwastro/pycbc/files/6417353/H1L1-PAGE_SEGPLOT_SUMMARY-EXAMPLE.zip)
Note that not all of the original functionality is restored with this PR. This plot original supported an interactive feature where the user could hover over a specific segment to display information (such as the start and end times) for that segment and used a custom plugin to only zoom and move on the x-axis.

Restore interactive plotting

---

pycbc/libutils.py

This PR modifies the way that a `/dev/null` file object is used in `pycbc.libutils.pkg_config_libdirs` to ensure that said file object actually gets closed properly, the current usage doesn't close the file.
Note that this can all be simplified by using `subprocess.DEVNULL` just as soon as python2 support is dropped.

Make sure FNULL is closed properly in pycbc.libutils.pkg_config_libdirs

---

pycbc/types/array.py
pycbc/types/frequencyseries.py
pycbc/types/timeseries.py

The docstrings for these functions were a bit incomplete and slightly incorrect, so this PR updates them.
While doing that, I spotted a couple minor bugs which this PR also fixes:
* When reading a `FrequencySeries` from Numpy or ASCII files, its epoch was somehow set to the frequency of the first bin. This looks like an 8 year old (!!!) leftover copy-and-paste from `load_timeseries()`. Now the epoch is set to `None` instead.
* HDF files were not being open read-only in `load_array()` and `load_timeseries()`.
Finally, this PR allows one to read a `FrequencySeries` from an HDF dataset that does not have the `epoch` attribute, in which case the epoch is set to `None`.

Fixes to functions that load arrays, time and frequency series from files

---

examples/search/analysis.ini
pycbc/events/stat.py

The expfitfgbg statistic was somewhat hardcoded in the way it chose a single detector statistic, now any can be used in its construction.

allow more general single stat in coinc statistic

---

pycbc/mchirp_area_improved.py

Since the cosmology model which is currently being use for LVC production results differs from the default cosmology of the `pycbc.cosmology.redshift` function, we need to introduce the option to use it for source probabilities estimation. 
```
pycbc_default_cosmology = astropy.cosmology.FlatLambdaCDM(H0=67.74, Om0=0.3075)
lal_default_cosmology = astropy.cosmology.FlatLambdaCDM(H0=67.90, Om0=0.3065)
```

Add LAL cosmology option to mchirp_area_improved.py

---

pycbc/mchirp_area_improved.py

If the redshifted template chirp mass is smaller than the chirp mass of two objects with masses equal to the minimum mass, the chirp mass contour can lay outside the defined mass plane, and the areas (and probabilities) would be zero. To solve this, we add a condition  to assign a probability of 100% BNS to chirp masses below the minimum chirp mass threshold.

Add condition for mchirp less than min_mchirp

---

bin/all_sky_search/pycbc_fit_sngls_binned
bin/all_sky_search/pycbc_fit_sngls_by_template
bin/all_sky_search/pycbc_fit_sngls_split_binned
bin/minifollowups/pycbc_injection_minifollowup
bin/minifollowups/pycbc_page_snglinfo
bin/minifollowups/pycbc_sngl_minifollowup
examples/search/analysis.ini
examples/search/plotting.ini

@spxiwh Added a nice feature to allow sending options to single statistics, however, this was not used in the fitting codes. This udpate the fitting and minifollowup codes to all use this path so one can use a consistent single-detector statistic and also have minifollowups sort by that order.

Use single stat class everywhere

---

bin/pycbc_optimal_snr

While trying to use `pycbc_optimal_snr` code and using multiple cores I rediscovered this issue  https://github.com/gwastro/pycbc/issues/3693
The `inj` variable in `compute_optimal_snr` is a numpy.record class when HDF5 injection file is used and `setattr(inj, column, sval)` didn't work for it.
So, I have added in few lines to fix it and I have tested the proposed fix. You can find a wrapper script running the fixed `pycbc_optimal_snr` code here
`/home/koustav.chandra/projects/HM_search/fix_optimal_snr/optimal.sh` in Livingston cluster.
I have tested it on both XMLs and HDF5 injection file. The output generated is correct and you can find them in the same directory. They are named `optimal.xml` and `optimal.hdf`

Fix null optimal SNRs when reading HDF injections

---

docs/install.rst

Update https://pycbc.org/pycbc/latest/html/install.html#full-virtualenv-for-development-and-production install instructions to build pycbc using `pip install .` instead of `python setup.py install`, which was causing version conflicts.

Update install instructions: swap setup.py for pip install

---

pycbc/inject/inject.py

`pycbc_make_inference_inj_workflow` with injection hdf file seems to be broken. While creating workflow, it was giving following error:
`TypeError: No conversion path for dtype: dtype('<U12')`
This is a quick fix suggested by @cdcapano .

Fix for broken pycbc_make_inference_inj_workflow

---

bin/workflows/pycbc_make_bank_verifier_workflow

I just (re)noticed that the bank verificator web pages do not include the configuration file, as the coinc workflow pages do. This PR tries to fix this issue by pulling the relevant code from the coinc workflow script.
Test [here](https://ldas-jobs.ligo.caltech.edu/~tito.canton/pycbc/test_pr3732/results/3._workflow/3.01_configuration/) (without submitting the actual workflow).

Include config file in bank verificator results

---

pycbc/inject/inject.py
pycbc/waveform/bank.py

I found that injfilterrejector was actually not enabled correctly for hdf injections. This occurs because it wasn't storing the set of actually injected ids (rather the *entire* set of injections). This also include some code to speed up the selection of templates when using a tau0 window.

fix hdf injfilterrejector, speed up tau0 selection

---

bin/all_sky_search/pycbc_coinc_findtrigs

This adds two options to the coincidence code
```
---nprocesses
```
As it would seem, this adds the option to use multiple processes to analyze the data. It parallelizes at the per template level. 
It also adds 
```
--use-shared-memory
```
This allows the code to make use of shared memory for staging input data. At the moment, this just means copying the input trigger files to shared memory. It will be deleted at the end of the program. 
These two options combined are useful for dramatically reducing the load on a file system from multiple coincidence jobs that a running at the same time. The idea would be to use only a single (or a very small handful) of coincidence jobs per ifo-combo.

parallelize coinc code, use shared memory

---

pycbc/filter/matchedfilter.py
test/test_matchedfilter.py

This point has come up a few point with students looking into match, that I think this needs a proper fix:
The current match function only takes values at exact samples. This can cause a [small] systematic error if the peak of the match is between samples. This can cause some weird result plots and non-monotonic behaviour of the match as waveforms match at different time samples. I fix this by implementing the sbank solution of sub-sample interpolation for matches. I also link to somewhere where the [simple enough] math behind this is defined.

Add sub-sample interpolation into match function

---

docs/fft.rst
docs/index.rst
pycbc/fft/fftw.py
pycbc/fft/mkl.py
pycbc/fft/npfft.py
test/fft_base.py
test/test_fft_unthreaded.py

This patch addresses some issues found in FFT library in PyCBC. After including all FFT backends in the test suite a number of failures were noted (as described below), which have been tracked down and fixed. I also update the test code to automatically test class and function APIs for all available backends. Finally, I've added a documentation FFT page to illustrate how to use both interfaces. I have *not* yet looked at multi-threaded FFTs, which have been reported as an issue (in particular MKL multi-threaded FFTs not working).
Failures that have been fixed:
* ~~FFTW is segfaulting on the r2c FFTs when called through the class API.~~  (Fixed after resolving bugs in how plans are being called)
* ~~MKL gives incorrect results (I think incorrectly normalized) for the class-based API.~~ …

Bug fix in FFTW, more fully support numpy FFTs and  update FFT tests to cover properly

---

examples/live/check_results.py
pycbc/io/live.py

Most of the complexity in #3623 can be merged right now, even without switching to `ligo.lw`, so this PR does that. This will make the transition easier.

Prepare PyCBC Live for the switch from glue.ligolw to ligo.lw

---

bin/pycbc_compress_bank
pycbc/waveform/bank.py

The compress_bank code is currently not working in python3. This is because of a few python2-isms in the executable which need fixing, and an issue in the module code in waveform/bank.
The python2 fixes are trivial, the waveform/bank is the same "HDF doesn't understand how to write arrays of strings" problem. I think that use of the `h5py.string_dtype` is a neat way to resolve this, as then we continue to treat this as a `str` object in pycbc code, and HDF will encode this as needed when writing to the file. I have a feeling though that there might be numerous instances of code blocks with similar issues. I guess we will uncover them as we continue testing all the codes.
In this case I'm adding this to the unittests in #3742.

The Bank class stuff in waveform has some python3 issues

---

pycbc/libutils.py

I've been seeing some weird cases where `pip install mkl` followed by `import pycbc.fft.mkl` reports that mkl is not present in the environment. This appears to be due to how libutils is trying to find libraries, and the weirdness in how python does this, especially when conda, or venvs are in play.
The current system looks in LD_LIBRARY_PATH, pkg_config paths and an explicit path if a venv is being used. This doesn't work for conda, doesn't work if the user is doing something like spawning a venv from a conda env and doesn't work for the unittest environment (I'm not exactly sure what tox is doing!)
I tried some simple ways to patch around this, but it didn't seem to work. A more hacky solution, like the one below, does seem to work. I think we need to fix this problem because we do want …

Modify how libutils finds libraries

---

.github/workflows/mac-test.yml
examples/inspiral/clean.sh
examples/inspiral/run.sh
pycbc/fft/mkl.py
pycbc/fft/npfft.py
test/test_fft_mkl_threaded.py
test/test_fftw_pthreads.py
tox.ini

Continuing on from #3734, here I update the multi-threaded FFT tests to test MKL, FFTW+openmp and FFTW+pthreads (if available).
I've also revamped the inspiral test case to run on all possible backends (with 1 thread, and with 16 threads). (First time I've seen pycbc_inspiral run correctly with MKL threaded).
I have updated the MKL FFTs (through the function interface) to allow multi-threading and fixed an issue with the class-based API for numpy I added in #3734.
Doing this has raised some questions:
* The performance (which you can see from running the new inspiral test) of the different FFT backend options is not what I expect. I've changed the test to use compressed waveforms so it should now be FFT limited. FFTW multi-threaded is giving me the best performance (on ldas-pcdev1 on LHO …

FFT tests for multi-threading

---

pycbc/inference/sampler/dynesty.py
pycbc/pool.py

Currently, `choose_pool` will incorrectly set `pool.size = 1` if you use python multiprocessing instead of MPI and you have `mpi4py` installed in your environment. This is a serious problem if you are using dynesty: `pool.size` is used by dynesty to determine how many parallel proposal points to generate (it sets the sampler's `queue_size`; see [this function](https://github.com/joshspeagle/dynesty/blob/master/py/dynesty/sampler.py#L340)). If pool.size is 1, it will only ever generate one proposal point at a time, rather than a batch. The result is that the pool is setup, but then only one process in that pool is only used, making it no faster than just running on a single core. This fixes this by appropriately setting `pool.size` if `use_mpi` is False.
This also ensures that `queue_size` …

Fix bug that can break dynesty parallelization

---

bin/pycbc_submit_dax

Adding the -hours argument to grid-proxy-init in the case you do not have a RFC compliant proxy.  This prevents a failure mode where your workflow runs longer than 12 hours after you resubmit it and then all the jobs start to fail due to expired proxies.  276 hours is equal to the maximum standard proxy lifetime of 11.5 days that is created when you use ligo-proxy-init.

Update pycbc_submit_dax to fix early proxy expiration on ./start resubmissions.

---

pycbc/coordinates.py

Passing a spin vector that is exactly zero in cartesian components to `cartesian_to_spherical_polar` would cause a divide by zero error. This should probably just return zero components instead.

Avoid div by 0 error if magnitude is exactly 0

---

pycbc/tmpltbank/brute_force_methods.py

I'm adding a test workflow for template bank generation as part of the pegasus5 patch. This workflow caught an edge case bug where numerical precision issues can cause failures in the template bank code (e.g. a point on the parameter space boundary can fall over to the other side of the boundary, and break everything). There were already some catches for this, but in this place it was missing .... This code perhaps needs an overhaul, but this fix is, I think, a simple one (see for e.g. the lines underneath where the patch is applied).

Fix precision edge-case bug in geometric template bank code

---

pycbc/cosmology.py

As opposed to setting a cosmological volume, it would be better to set a population model explicitly and be able to transform from the resulting rate to distance horizon, etc. In this way we could use explicitly merger rate models as priors for example. 
This adds a few functions in this area along with an example function which can be used to set a rate distribution (following the stellar-formation rate). 
The key function is 'rate_from_redshift' which takes in a redshift and a 'rate_desnity' function. The rate density should take in a redshift and return the rate of occurances of something (might be merger rate, need not be though) per unit volume. The function then can integrate this over the comoving volume out to this redshift. The cosmological time dilation is also taken into …

add functions to get rate from redshift  or distance from rate

---

pycbc/distributions/angular.py
pycbc/distributions/bounded.py
pycbc/distributions/gaussian.py
pycbc/distributions/power_law.py
pycbc/distributions/uniform.py
pycbc/distributions/uniform_log.py

If we have a cdfinv, then we should just use it for the rvs function rather than duplicating code. 
@cdcapano One thing I didn't touch was the qnm.py distribution however I don't understand some of the things it is doing. Why is it dealing with constraints and renormalization? The join distirbution should do both those things? What is going on there?

simplify use of rvs

---

setup.py

Following instructions of https://pycbc.org/pycbc/latest/html/release.html
Do we still need the pycbc-config release?

prep for release

---

docs/release.rst
setup.py

Including removal of the pycbc-config instructions in the release instruction page

Set back to development

---

pycbc/distributions/bounded.py

@sum33it I missed a bug in #3744 whereby some codes we weren't testing relied on the return being an array rather than a dict. This showed up in the failure of the tutorials in the 1.18.2 release, but otherwise the testing did not fail (it occurs if you do some manual things in the PE which doesn't as commonly occur nowadays in when we run PE, such as setting the initial positions with mcmc).

rvs should return array

---

.github/workflows/tut-test.yml

This does the same test that the pycbc tutorials run themselves to ensure that any functionality used in the tutorials doesn't cause breakage there.

add test of pycbc tutorials to CI

---

pycbc/psd/__init__.py

Adds the ability to use the Hann window for inverse PSD truncation through the command line interface.

Add invpsd-trunc-method option to cli

---

pycbc/conversions.py

The function currently used in `conversions.py` for estimating final mass and spin from initial masses and spins uses the fits used by SEOBNRv4 (which is an aligned-spin approximant). This function does not work very well at estimating the final spin for precessing systems (final masses are largely the same). This patch adds the ability to use the NRSur7dq4 fit and/or the SEOBNRv4PHM fit, both of which come from lalsimulation. These both give much better estimates for the final spin for precessing systems. The default fit function is switched from SEOBNRv4 to SEOBNRv4PHM (the NRSur can be quite slow, requires the appropriate hdf files to be installed, and only works for q < 6).
Examples (note the difference in the final spin for the precessing system):
```
>>> from pycbc import …
```

Add fit functions from SEOBNRv4PHM and NRSur7dq4 for final mass and spin

---

pycbc/waveform/waveform.py

Currently, `pycbc_create_injections` does cannot support the mode array argument. This is because the argument needs to be provided as an array of tuples, which cannot be specified in a config file. This fixes that by allowing the waveform module to accept a space-separated string of integers indicating the modes to use, e.g., `'22 33 44'`.

Allow injection module to support mode array

---

bin/pycbc_inspiral
bin/pycbc_multi_inspiral
pycbc/inject/inject.py
pycbc/inject/injfilterrejector.py

This patch addresses a couple issues, one is a bug. 
1) I don't think the ids were used correclty (probably my fault originall) for injfliterrejector when comparing to the precalculated injection short version of the waveform. This makes it more explicit. 
2) This enables one to use the injfilterrejector multiple times (i.e. with multiple calls to the injection code) although still only if the same injection file is used.

fix to ids for HDF inj in injfilterrejector, allow multiple use

---

bin/all_sky_search/pycbc_coinc_mergetrigs

This allows pycbc_coinc_mergetrigs to handle the case where 'search/start_time' may be more than a single element. It is also backwards compatible to the case if it is a single element.

allow mergetrigs to handle inspiral files with multiple start/end times

---

bin/inference/pycbc_inference_plot_posterior
pycbc/inference/option_utils.py
pycbc/results/scatter_histograms.py

Some updates for plot posterior that I've been meaning to commit to master for awhile. Does the following:
* Adds the ability to plot the maximum likelihood point with argument `--plot-maxl`. If turned on, an `x` is added to the 2D marginals showing where the maxL point is.
* If `--use-kombine-kde` is turned on, will now call kombine's `optimized_kde` method. That uses Bayesian inference criteria to determine if there are multiple modes. It's slow, but can be useful for distributions that have more than one mode.
* Adds a `--kde-args` to the command line. These are passed through to the KDE. Needed for to limit the number of points given to kombine's KDE (more than a few thousand and it will crawl to a halt), but also can be used to modify what scipy's KDE uses for bandwidths.
* Adds the …

Updates to plot posterior

---

companion.txt

`setproctitle` can be useful when looking at a running instance of PyCBC Live with `htop`. This adds it to `companion.txt`.

Add setproctitle to companion.txt

---

examples/live/run.sh
pycbc/mchirp_area.py

As noted in #3807,  some required arguments for running `mchirp_area.py` were not added to the pycbc-live test script (`/examples/live/run.sh`). I added the required flag for the arguments to the module, and their latest values to the script.

Add required arguments to source classification

---

pycbc/frame/losc.py

The _get_channel function in the losc module returns the O1 channel name for O3 data, but the O3 release uses the same channel name as the O2 data. This PR updates the logic in the _get_channel function.
CAVEAT: double-checking the [GWOSC O1 documentation](https://www.gw-openscience.org/O1/), I found that the LOSC_STRAIN channel name in O1 was only used for the 4KHz data. Hence, as it is now, if using this function to get the channel name for GWOSC data, one would obtain 4KHz data for O1 but 16KHz for O2 and O3. I suggest changing the function to return the same sample rate for all observing runs, i.e. either returning `GWOSC-16KHZ_R1_STRAIN` for all three observing runs, or changing O2 & O3 to return `GWOSC-4KHZ_R1_STRAIN`
Let me know which option is preferred and I can update the PR …

Update GWOSC channel name for O3 data

---

pycbc/filter/resample.py
pycbc/strain/strain.py

This PR adds the option to lowpass strain data as part of `strain.from_cli`. The lowpass method is based on the lal lowpass function, and mirrors the method used for high passing as part of the current strain generation process. 
This PR was originally part of #3804, but is now a separate PR based on the suggestion of @titodalcanton.

Add lowpass filter option to strain generation

---

bin/pycbc_multi_inspiral

Having 'longitude' and 'latitude' as sky location variables in radians (but without that specified in help) was clearly somewhat of a pitfall.

remove unneeded 'longitude'/'latitude', help, formatting

---

pycbc/workflow/pegasus_workflow.py

This is one of the PRs needed for non-LDG users to use the standard shell script tools made when using the '--submit-now' options. 
The change is to only do the proxy checks if you request so in the profile information i.e. so the current behavior would be replicated by adding 
```
[pegasus_profile
pycbc|check_grid = 
```
to one's config files. Otherwise, no check is performed by default.

make grid tools / proxy checks optional in start script

---

pycbc/frame/losc.py

This is needed to query the segments from O3b
* used for searches
* used in PE to verify valid data is present (when using this option)

add time range that covers o3b to be able to query gwosc segments

---

bin/pycbc_inspiral

This would cause an error I think if all no templates were generated. That might happen in some injection cases with lots of filtering.

fix typo in pycbc_inspiral

---

bin/all_sky_search/pycbc_fit_sngls_over_multiparam

If using pycbc_fit_sngls_over_multiparam with a single parameter for smoothing, then the parameter output will be sorted on that parameter, rather than in template id order.
I think this is a fairly rare use case so the if statement isn't used normally. The parameter value isn't used downstream in the workflow so far as I know, so don't think this affects anything downstream
This fix prevents the sorting of the original parameter array to keep it in the original order

Fix sort error on param output if single parameter

---

pycbc/inference/models/gaussian_noise.py
pycbc/inference/models/marginalized_gaussian_noise.py

Try to relax the constraint that data from all detectors should have the same length. Work in progress
2021.11.08 Update: This module adds support to `gaussian_noise`, `marginalized_phase` and `marginalized_polarization` for analyzing different data segment lengths and/or sampling rates for different IFOs.
Future optimization: add support for more models, handle the case when some of the IFOs use the same settings (in that case I don't need to generate a waveform generator for each one of IFO

Fix analysis time

---

bin/pygrb/pycbc_make_grb_summary_page
tools/pycbc_test_suite.sh

This PR fixes the imports block in `pycbc_make_grb_summary_page` by removing all unused imports, and replacing ` from blah import *` with named imports.
This script can now be tested as part of `pycbc_test_suite.sh`.

Update imports in pycbc_make_grb_summary_page

---

bin/all_sky_search/pycbc_coinc_findtrigs

This is a speed-up to pycbc_coinc_findtrigs in the case where not all templates could even possibly produce a trigger. In other words, a template can be quickly skipped if there is zero triggers from a template in *any* of the required detectors. There is a path that could partly help with this before, but this patch pre-culls the set of templates which is much more efficient. 
This occurs for injection sets with heavy use of injection filtering, for example. In that case, the performance improvement can be quite large (orders of magnitude if the bank is large enough and each injection set is narrow).

only analyze templates which have triggers

---

bin/plotting/pycbc_plot_singles_timefreq
requirements.txt

Matplotlib's `pcolormesh()` no longer accepts the `vmin`/`vmax` kwargs when given a `norm` kwarg. Fixes #3869. It also fixes another deprecation warning related to the `shading` kwarg.
Edit: Version 1.0 of epsie is incompatible with pycbc, which is breaking the CI tests. So this also pins the version to 0.7.1 for now while this is being fixed.

Fix deprecated `pcolormesh()` call and pin epsie to 0.7.1 for now

---

pycbc/io/live.py
pycbc/io/record.py
pycbc/types/config.py

```
[…]/pycbc/.tox/py-unittest/lib/python3.7/site-packages/pycbc/io/record.py:48: DeprecationWarning: `np.typeDict` is a deprecated alias for `np.sctypeDict`.
numpy.typeDict.update(ligolw_types.ToNumPyType)
[…]/pycbc/.tox/py-unittest/lib/python3.7/site-packages/pycbc/io/record.py:124: DeprecationWarning: `np.typeDict` is a deprecated alias for `np.sctypeDict`.
else 'S%i' % _default_types_status['default_strlen']
[…]/pycbc/.tox/py-unittest/lib/python3.7/site-packages/pycbc/io/record.py:135: DeprecationWarning: `np.typeDict` is a deprecated alias for `np.sctypeDict`.
else 'S%i' % default_strlen
[…]/pycbc/.tox/py-unittest/lib/python3.7/site-packages/pycbc/types/config.py:97: DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be …
```

Fix three deprecation warnings coming from the tox tests

---

pycbc/filter/resample.py
test/test_resample.py

This should fix #3880 . The bug was introduced in a patch to speed up the underyling lfilter function. In one case, the return type was not as expected. I've updated the unitest as well to catch this specific case.

fix FIR zero filter for short length coefficients

---

bin/inference/pycbc_inference_plot_posterior
pycbc/inference/option_utils.py
pycbc/results/scatter_histograms.py

This adds a `--max-kde-samples` argument to `pycbc_inference_plot_posterior` so that the user can optionally limit the number of samples used for KDE construction. KDEs are used to make the 2D density plots and draw contours. If there are more than ~10000 samples in a file, this can be extremely slow if plotting more than a few parameters. Limiting the number can substantially speed up plotting without making any noticable changes in the plots. For example, in testing, I found that it takes ~4mins to plot six parameters using a posterior file with ~80000 samples. Adding `--max-kde-samples 5000` took only ~18s for the same plot.

Limit the number of samples used for KDEs in plot posterior

---

pycbc/types/config.py

This should re-enable use of multiline input in config parsers within inference workflows. The change to pegasus5 was accompanied by a change to using Pegasus style string formatting rather than condor. The pegasus style is supperior as it no longer requires us to worry about quoting to get things to be passed as we'd have wanted. The downside is that newlines get passed *exactly* as we've specified which breaks inference jobs that used that format. In general we can just auto-convert these to spaces and they should run again.

sanitize newlines in configparser input to spaces

---

bin/pycbc_submit_dax
pycbc/workflow/pegasus_workflow.py

The issue with the fact that this function requires a *list* and not a single argument was noted by @dethodav. I've also added in the fix so that cache file reuse works again with pycbc_submit_dax. The problem was that the _reuse.cache file wasn't being passed anything longer to all the subworkflows. This was explicitly done before and I think may have just been accidentally removed.

fix cache file reuse

---

bin/pycbc_create_injections

This PR targets the issue raised by #3893. I added the time-step between different new blocks to ensure the minimum separation between two injections.

Separating different blocks by time-step.

---

pycbc/catalog/__init__.py

When using `Merger(name).strain(detector)` and the strain data does not actually exist, the current code raises a rather vague error like this:
```
UnboundLocalError: local variable 'url' referenced before assignment
```
This PR makes the error clearer and cleans up the code slightly.

Improve error when strain data is not available

---

pycbc/workflow/minifollowups.py
pycbc/workflow/pegasus_workflow.py

This is one area I noticed as odd when I looked at the Pegasus 5 changes.
Given that our internal method of setting sub-workflow inter-dependencies had been removed, I'm skeptical that this line here should be required. In other words, if we could remove the inter-workflow dependencies and pycbc's older code for determining dependencies base don file useage, then Pegasus must be determining this internally now.  The inputs for the workflow are already being added to the dax object directly. If that's the case, and it is doing so correctly, then this dependency line should not be required. 
Assuming the tests don't reveal something and I haven't misunderstood some corner case, I suggest we remove this line to remove future confusion about how dependencies are resolved.

remove explicit subworkflow dependency

---

pycbc/types/timeseries.py

Avoid rounding down when the answer is supposed to be close to the expected integer.

avoid a few floating point precission issues

---

pycbc/workflow/jobsetup.py

@spxiwh This removes the couple instance where we explicitly set profile information in jobs setup. 
After the P5 changes, we lost the ability to override these with the config options. This occured because the code was removed which checked if a profile profile was set and only set a new one if a 'force' option was given. This allowed the config file to take precedence over things in the code. 
I'm not sure if we want that functionality back, but we absolutely do need the ability to set this information in the config file. By removing these lines, the config file is no longer ignored.

don't set profile within jobsetup

---

pycbc/population/fgmc_functions.py

Having `matplotlib.use('Agg')` in library code is not a good idea. As this library is loaded in many use cases, it will mean that matplotlib will likely be using the 'Agg' module when you don't want it to, and then when you are expecting to see plots in Jupyter, you do not see plots.
I think the way this is handled in the `fgmc_plots` module seems very nice. If this is not the best way to do this here, this could be put into the two plotting methods (with a note that it will do this in the function docs). In general though we leave it to executables to see things like this, where this solution is the right thing to do.
Similar with the rcParams.

Remove matplotlib.use('Agg') from library code

---

pycbc/waveform/bank.py

This PR modifies `TemplateBank.write_hdf` to allow using `.h5` and `.hdf5` file extensions for output files, since `.hdf` is ambiguous with HDF4 files.

Allow .h5 and .hdf5 extensions for TemplateBank output files

---

bin/all_sky_search/pycbc_add_statmap

As identified by #3913
If --max-hierarchical-removals N is given, the pycbc_add_statmap output currently outputs N datasets, up to foreground_h(N-1), but should have output N+1 outputs, as the first (foreground_h0) is when no HR has been done.
This moves the check whether max-hierarchical-removals has been reached to after the dataset has been output, the same place where the ifar threshold check is.
Tested and fixes the ifar_catalog error

move h_iterations check

---

bin/bank/pycbc_geom_aligned_bank
bin/pycbc_live
pycbc/workflow/configuration.py
pycbc/workflow/pegasus_sites.py

This PR replaces all instances of `distutils.spawn.find_executable` with [`shutil.which`](https://docs.python.org/3/library/shutil.html#shutil.which), distutils is [deprecated](https://www.python.org/dev/peps/pep-0632/).

Use shutil.which instead of distutils.spawn.find_executable

---

pycbc/types/array.py

This PR fixes the following warnings:
```pytb
/home/duncan/git/pycbc/pycbc/types/array.py:84: SyntaxWarning: "is" with a literal. Did you mean "=="?
if precision is 'single':
/home/duncan/git/pycbc/pycbc/types/array.py:89: SyntaxWarning: "is" with a literal. Did you mean "=="?
if precision is 'single':
/home/duncan/git/pycbc/pycbc/types/array.py:96: SyntaxWarning: "is" with a literal. Did you mean "=="?
if dtype.kind is 'c':
/home/duncan/git/pycbc/pycbc/types/array.py:862: SyntaxWarning: "is" with a literal. Did you mean "=="?
if self.kind is 'real' and other.kind is 'complex':
/home/duncan/git/pycbc/pycbc/types/array.py:862: SyntaxWarning: "is" with a literal. Did you mean "=="?
if self.kind is 'real' and other.kind is 'complex':
/home/duncan/git/pycbc/pycbc/types/array.py:1053: …
```

Fix all SyntaxWarnings comparing string literals

---

bin/pycbc_losc_segment_query
pycbc/io/ligolw.py
pycbc/io/live.py
pycbc/workflow/core.py

`pycbc_losc_segment_query` has a number of issues and I suspect it is not really used nowadays. However, it is still part of the `--help` sanity tests, and it fails on Python 3.10 due to its use of the abandoned `glue.segmentdb` module. This change removes the LIGOLW writing code from the script in favor of using the SegFile class. The script functionality is more or less preserved, apart from losing the comments in the LIGOLW tables. I also do some cleanup of the script, for example turning all [LOSC](https://www.losc.fr/) references to GWOSC. I think some additional cleanup/fixing is due but I did not spend further time on it, given that I am not sure how much this is really used nowadays.
As part of this change, I created another wrapper function in `pycbc.io.ligolw` to handle the …

Modernize `pycbc_losc_segment_query`

---

bin/pycbc_splitbank

It seems `pycbc_splitbank` no longer works due to underlying changes in the ligo.lw module, although I am not sure exactly what the full problem is (see #3921). This should at least fix the specific problem reported in #3921, but it would be good to do a few more tests wit different input XML files. I could probably also move some ligo.lw stuff away in favor of imports from pycbc.io.ligolw.
I also remove the `--write-compress` option to simplify the code and UI a bit, as I cannot think of a good case where we would *not* want to gzip the output bank.
I also dropped a `from glue import gpstime` import, which I bet is going to start failing soon.
Finally this also fixes #3814, which was previously closed without being fixed.

Fix issues in `pycbc_splitbank`

---

bin/all_sky_search/pycbc_add_statmap
pycbc/io/hdf.py

The pycbc_page_foreground output has an option to output in hdf format. I thought it best to match the 4-OGC output [here](https://github.com/gwastro/4-ogc/blob/master/search/4-OGC_small.hdf), as it isn't too different to what we already do
I think that we should try to align formats of released event information, and this could be the basis of future data releases

update page_foreground hdf output to match 4-ogc summary file

---

bin/pycbc_live
bin/pycbc_optimize_snr

`pycbc_optimize_snr` runs into trouble when executed in an environment where Python is built using Intel tools (e.g. under a Conda environment built using Intel oneAPI) and where FFTW is also present, and built with a different compiler. This leads to a segfault as soon as `pycbc_optimize_snr` tries to perform matched filtering, which either propagates to the process itself, or causes the process to hang indefinitely (probably due to the threads segfaulting) depending on what optimization algorithm is used.
This PR adds the processing scheme and FFT command-line options to `pycbc_optimize_snr`, and ensures that matched filtering is executed inside the appropriate context manager. I verified that this solves the problem with all three optimization algorithms, and the results are …

Let `pycbc_optimize_snr` understand scheme and FFT options

---

pycbc/io/record.py

As discussed in [#3921](https://github.com/gwastro/pycbc/issues/3921#issuecomment-1023359795), changes in ligo.lw mean tables have columns like process:process_id but corresponding row attributes are only the post-colon part, e.g. process_id. This caused an error when reading in from xml via `from_ligolw_table`.
I haven't been able to find any other places where this same issue will arise, hopefully it's only here.

Fix in from_ligolw_table

---

bin/pycbc_live
bin/pycbc_optimize_snr

This fixes:
* Some str-vs-bytes confusion (creating problems with GraceDB) caused by h5py 3.x.
* A leftover error from #3927.
* The stdout/stderr redirect, which is Bash-specific and does not work on one of my virtual machines.

Fix a few issues in `pycbc_optimize_snr`

---

examples/live/.gitignore
examples/live/run.sh

I found that this does not actually take a lot of time on my test machine, so why not. At the moment the SNR optimizer fails on one of the injections (see #3928) so I did not add any actual check that the SNR optimization is successful. However, if a LIGOLW file is generated, BAYESTAR will run on it, so we can spot cases where `pycbc_optimize_snr` breaks BAYESTAR.

Run SNR optimizer in PyCBC Live example/test

---

pycbc/io/live.py

In the past, the low-latency alert system required the noise PSD estimates associated with a candidate event to be uploaded to GraceDB as a separate LIGOLW file. As described in https://lscsoft.docs.ligo.org/ligo.skymap/interface.html and https://git.ligo.org/emfollow/gwcelery/-/merge_requests/850, we are now transitioning to the assumption that the noise PSDs are part of the original LIGOLW upload, and the second upload is no longer necessary.
This PR removes the code that does the separate PSD upload. It also reorganizes the operations that happen when a candidate is uploaded, so that the first operation is the upload, and the diagnostic plots are done as a second step.
Needs testing.

PyCBC Live: stop uploading PSDs to GraceDB as separate files

---

requirements.txt
setup.py

This is an attempt to address the immediate issue of Pegasus having a hard requirement on flask which no longer works due to #3942. In general, it's probably a good idea to keep our dependencies as lean as possible as well.
Assuming this passes tests, is there any reason we don't *just* depend on the API? Doe we actually need anything else for the PyCBC library directly?

Switch to minimal pegasus api requirement

---

requirements.txt

This is an attempt to go back to the standard dqsegdb which I had to fork temporarily to hack in python3 support. My understanding is the last release should support python3, so :crossed_fingers:

revert to standard dqsegdb

---

bin/bank/pycbc_geom_nonspinbank
pycbc/tmpltbank/bank_output_utils.py

`pycbc_geom_nonspinbank` currently fails to write the bank with this error:
```
[…]
2022-02-22 13:52:53,023 Writing output
File "/home/tito/.conda/envs/conda-test/bin/pycbc_geom_nonspinbank", line 384, in <module>
tmpltbank.output_sngl_inspiral_table(
File "/home/tito/.conda/envs/conda-test/lib/python3.9/site-packages/pycbc/tmpltbank/bank_output_utils.py", line 293, in output_sngl_inspiral_table
search_summary = return_search_summary(start_time, end_time,
TypeError: return_search_summary() got an unexpected keyword argument 'comment'
```
This fixes it.

Quasi-minimal fix for broken `pycbc_geom_nonspinbank`

---

.github/workflows/basic-tests.yml
.github/workflows/mac-test.yml
pycbc/conversions.py
pycbc/distributions/qnm.py
pycbc/distributions/uniform.py
pycbc/tmpltbank/calc_moments.py
test/test_distributions.py
test/test_skymax.py
test/test_tmpltbank.py
tox.ini

My goal here is to make `tox` run properly on mac (in particular ARM macs). I do this by moving to tox-conda for the most part.
There's also some warning fixes, and one failure in python3.9.7 where `None < 2` now raises an error rather than giving some output.
Finally, `numpy.seterr` was being used slightly incorrectly in some of the PE code, so that the original settings were not restored. This fixes that, and I add it to some of the tests where numpy warnings are expected.

Some fixes to test suite - focused on MACOS usage

---

pycbc/workflow/pegasus_workflow.py

In #3948 @PRAVEEN-mnl reported an issue where input files coming from CVMFS would cause a failure.
The underlying issue here is that a code block to say "make this available on any 'site'" didn't seem to work at all. CVMFS input files is the only place where that code block is exercised. I think the original issue was that `self._rc` should have been `self._tc`. However, due to other edits by Alex, this now needs a bit more poking to match those changes. This is still a pretty minor fix though to restore the desired behaviour (which is basically that any file that can be accessed from all sites, should be added to all sites in the replica catalog).
@PRAVEEN-mnl @tdent Can one of you verify that this solves the problem, and then approve so this can be merged?
Fixes #3948

Fix for CVMFS input issue

---

bin/pycbc_multi_inspiral
pycbc/events/coherent.py

As development on `pycbc_multi_inspiral` has progressed, the executable has gathered a lot of utility functions to do with trigger identification and coherent SNR calculation that would be better placed elsewhere. I suggest moving them to a coherent module.

Moving multi_inspiral utils to coherent module

---

bin/pycbc_create_injections
pycbc/distributions/__init__.py
pycbc/distributions/constraints.py
pycbc/distributions/utils.py
pycbc/inference/models/base.py
pycbc/inference/option_utils.py
pycbc/inference/sampler/base.py
pycbc/inference/sampler/base_mcmc.py
test/test_distributions.py

When generating samples from distributions with constraints imposed the constraints can't depend on any fixed parameters. Allowing for this will be useful for e.g. generating EM-bright populations.

Allow constraints to include fixed parameters

---

examples/search/executables.ini
examples/search/injections_minimal.ini
pycbc/workflow/injection.py

@tdent I guess you got fed up of waiting for me to do this (my bad), but I was working on this earlier today!
So here is my version of #3968, basically the same, but one or two things I prefer in here:
* I update the search example so this is tested in the automated CI tests.
* The new EXE class goes into injections.py. As it's only used here, I prefer this (jobsetup.py got overloaded, and does need some cleanup).
* create_node doesn't get options that it will never use. Note that as this only ever makes one job, all tags are sent to the Executable, and we don't need any job-level tag (that's how it knows which injection run it is).
* The relative_submit_dir thing is not relevant for a job that's only run once (not sure why that was being used before, but it's a pretty niche thing, but …

Make merge opt inj work

---

bin/pycbc_live

I am doing some experiments with different MPI implementations and also alternatives to MPI. This adds explicit log entries to time when we hit the MPI calls. It also cleans up some indentation a bit.

PyCBC Live: explicitly log MPI commits and gathers

---

bin/all_sky_search/pycbc_fit_sngls_over_multiparam

I wrote this up a while ago, but never actually made the PR in the end.
I found that sometimes the smoothing can be a bit over-aggressive, so I've added a couple of alternative methods to fit_sngls_over_multiparam:
- smooth_area, which is the same as the current implementation and is the default
- smooth_distance_weighted, which finds the templates within 3 of the unit area defined as normal, and the smooths them, weighted according to a normal distribution of width 1 (distance defined by --smoothing-width)
- n_loudest, which counts the triggers in the nearest templates to the template of interest and stops when you reach a threshold (currently hardcoded to 500). This basically takes into account the fact that we are doing this because of small number statistics, and says that we only …

add in some alternative smoothing methods

---

examples/search/injections_minimal.ini

Neither 'strip_injections' nor 'inj_cut' seem to be used in the current standard injection workflow. Remove their sections to avoid confusion

Remove unused sections from example ini

---

examples/search/analysis.ini
examples/search/gen.sh

The artefact for the results page wasn't being uploaded from the test search, but it also looked like it wasn't being put into the folder where it was expected to be.
This fixes the issue, but I'm not sure where the results page was being made originally

Results page artefact location

---

pycbc/distributions/utils.py

Currently `pycbc_inference` throws an error:
`AttributeError: module 'pycbc' has no attribute 'distributions'`
Fixing how distributions is imported in distributions/utils.py.

fix distributions import error

---

bin/pycbc_split_inspinj
bin/workflows/pycbc_make_bank_verifier_workflow

This PR also stops `pycbc_make_bank_verifier_workflow` from assuming the fixed list of ifos H1, L1, V1 .

similar to PR #3922 but for splitinj

---

examples/inference/single/run.sh
examples/inference/single/single.ini
pycbc/inference/io/base_hdf.py
pycbc/inference/sampler/dynesty.py

The recent PR to update pycbc to work with the latest Dynesty (1.2.0) API also turned off checkpointing. This was due to how the options were passed being ignored with the new method. This Patch should address the problem reported by @cnsetzer.

fix checkpointing after recent dynesty API change

---

docs/inference.rst
pycbc/inference/models/base.py
pycbc/waveform/generator.py

This removes the automatic transforms that happen in the CBC waveform generators in pycbc inference. Those transforms tried to automatically figure out what transforms were needed to go from some parameters (like spherical spin coordinates and mchirp, q) to parameters understood by the waveform generators. While this meant not having to include a waveform transforms section for spherical spin parameters, the silent and difficult to follow nature of these transforms makes it easy to make mistakes. It also goes against the general philosophy we have of making analysis settings explicit in the configuration file.
Just removing the automatic transforms can be dangerous for spin parameters, however. We typically specify the prior in spherical coordinates. Removing the automatic transforms will …

Remove automatic transforms from waveform generator

---

bin/inference/pycbc_inference_model_stats
pycbc/inference/io/__init__.py
pycbc/inference/io/base_hdf.py
pycbc/inference/models/marginalized_gaussian_noise.py
pycbc/inference/models/single_template.py
pycbc/inference/models/tools.py

Depends on #3996 
This adds a function to reconstruct the marginalized distance or polarization value of a model. The functionality is added to pycbc_inference_model_stats with an additional argument '--reconstruct-parameters'. 
A few fixes also in place to enable measure the phase for single / relative models.

Add function to reconstruct marginalized distance or polarization, feature added to script

---

examples/multi_inspiral/check_faceon_faceaway_trigs.py
examples/multi_inspiral/check_gw170817_trigs.py
examples/multi_inspiral/clean.sh
examples/multi_inspiral/faceon_faceaway.sh
examples/multi_inspiral/run.sh
pycbc/frame/frame.py
tools/pycbc_test_suite.sh

This adds an example for `pycbc_multi_inspiral` to test not only the executable, but also the implementation of the face-on/-away signal projection used in PyGRB searches. Relies on gwastro/pycbc-config#76 for inputs.

Adding test of pycbc_multi_inspiral face-on/-away

---

pycbc/inference/models/marginalized_gaussian_noise.py

There's a typo in the doc string for the marginalized phase gaussian noise model. It currently has that the log posterior is proportional to the modified Bessel function (I0). This is incorrect; the *posterior* is proportional to modified Bessel function, not the log of the posterior. This fixes this, and also a missing `\` before a `phi`.

Fix typo in marginalized phase docs

---

bin/workflows/pycbc_make_bank_verifier_workflow

Use the actual IFOs of interest in naming files, rather than 'HL'.

Generalizing ifos tag in pycbc_make_bank_verifier_workflow

---

pycbc/conversions.py
pycbc/detector.py
pycbc/inject/inject.py
pycbc/libutils.py
pycbc/noise/gaussian.py
pycbc/pnutils.py
pycbc/psd/analytical.py
pycbc/results/versioning.py
pycbc/tmpltbank/lambda_mapping.py
pycbc/waveform/spa_tmplt.py
pycbc/waveform/utils.py
pycbc/waveform/waveform.py
pycbc/waveform/waveform_modes.py

This aims to allow lalsimulation to be separated from some more basic PyCBC functionality. This PR should not reduce any existing functionality. 
Where possible, this just means that some functions will have fewer options if lalsimulation is not available (i.e. waveform generation, analytic psds). In other cases, if a function which requires lalsimulation is called (injections, some detector stuff, etc), I've tried to enable a useful error message. 
Noteably, I've added a helper function which may be useful for optional functionality in other cases. It allows one to import a module and not have to add extra try / expect statements everywhere for the common case where specific methods or functions need to call the module. 
one uses this as 
```
import pycbc.libutils
lalsim = …
```

allow lalsimulation to be missing, helper function for optional libraries

---

pycbc/workflow/injection.py
pycbc/workflow/jobsetup.py
pycbc/workflow/segment.py

This allows one to tell the search workflow that the vetos and or science segments are null and or always OK, respectively. For analyzing mock data, we often have no veto segments and the valid data should be assumed to be the same as the generated frame files.

allow assuming science segments are valid, no need to go to server

---

pycbc.spec
pycbc/scheme.py
pycbc/types/array.py
requirements.txt
setup.py

I've seen some issues recently where decorator is taken reasonably significant time to call the functions it is wrapping.
The easiest solution to this seems to be: don't use decorator. From reading around it seems like `functools.wraps` is more widely used. The syntax for this is a little different (and more like "normal" decorators), but after making this change I don't see any time spent within functools ... I actually don't see functools.wrap *at all* in the profile, which does make it easier to read the profile .. and I hope means it is still accurate!

Retire decorator

---

pycbc/inference/sampler/dynesty.py

@cnsetzer Reported that upon resuming from a checkpoint Dynesty 1.2 would limit to 1 core. I confirmed this was the case and it seems to be due to addition pool metadata that by default would be restored in 1.2. We need to add these to the "do not restore" list so that it uses the scratch made properties on restart.

fix pool properties upon resume for dynesty 1.2

---

pycbc/types/array_cpu.pyx

Another one in the vein of #4015.
In the callgraph in #4016 about 1% of the time is spent in the "kind" property within `abs_arg_max`. This is silly, as that is just checking "is this complex or not". I think the issue is that we have to do a call back to python from Cython. It seems that I get most of the 1% back by making the change below, but probably it's better to call directly into `abs_arg_max_complex` if you know the input is complex.

Attempt to speed up call to kind in array.pyx

---

bin/pycbc_dark_vs_bright_injections

This is to fix errors with pycbc_dark_vs_bright_injections when dealing with lsctables.
Also, it avoids hitting an error when they symmetric mass ratio is not set in the input xml table (by simply calculating it).

similar to PR #3922 and PR#3994 but for pycbc_dark_vs_bright_injections

---

bin/workflows/pycbc_make_bank_verifier_workflow
bin/workflows/pycbc_make_inference_inj_workflow
pycbc/inject/inject.py
pycbc/workflow/jobsetup.py
pycbc/workflow/pegasus_sites.py

This PR allows `pycbc_make_bank_verifier_workflow` to also exploit `pycbc_create_injections` rather than just `lalapps_insp_inj`.  Doing so required some cleaning up in `pycbc/workflow/jobsetup.py`, which in turn also brought a small update to `pycbc_make_inference_inj_workflow`.  Finally, `pycbc/inject/inject.py` needed some fixing to get `pycbc_create_injections` to write aligned spin injections to xml files without errors.

Verifier with pycbc injs

---

examples/live/check_results.py
examples/live/generate_injections.py
examples/live/make_singles_fits_file.py
examples/live/run.sh

Part of testing for https://github.com/gwastro/pycbc/pull/3984 is that we wanted to get the single-detector trigger into the live test
In this PR, we:
- Set the H1 and V1 strain generator to end 32s early
- Add another injection to inject an EM-bright signal into this (L1-only) time
- Make a single fits file (currently just manually filling the appropriate datasets to get something sensible)
- Add the singles to the test `run.sh` script
- Update the `check_results.py` script to know that there may be single-detector events (and call them 'found' rather than 'coinc')

Live singles in ci test

---

pycbc/filter/resample.py

So I've been looking at the call-graph for PyCBC Live (running in early warning configuration), and am going to be proposing some changes to make the "not doing matched-filtering" bits quicker. The decorator change #4011 was the first of these (and perhaps the most impactful), but there's other things that can be done.
One issue with Live is that it keeps reading data, and this process is not quick. This involves some repetitive operations that can be avoided. Recomputing the FIR filters in resample.py is an example of that. With a few-line change, we can use python3 built-in decorators to cache these, in the case that they don't need recomputing.

Cache FIR filters in resample.py

---

bin/pycbc_live

A check for if a single event had been uploaded as a coincident event already (and therefore not upload the singles) was requested - I think this should work, but am not sure on where the tests are kept at the moment

dont upload singles if coinc already uploaded

---

pycbc/distributions/joint.py

When calling the joint distribution's logpdf, it currently always returns an array. This causes an error when trying to write to the output file when a sampler that writes blob data (like emcee) is used. The logprior is in the blob data, which currently is an array of arrays. Consequently, hdf5 sees the logprior data type as a python object, which it doesn't know how to write.
The bug was introduced when we tried to speed up the joint distribution by not converting to field arrays using `_ensure_fieldarray`. That function did two things: determine if an atomic data type should be returned based on the input, and converted to field array.
To fix, this patch breaks the atomic determination into its own function, so it can be called without the speed hit you get from converting the input to …

Joint distribution does not respect input type

---

bin/bank/pycbc_brute_bank
bin/inference/pycbc_inference_plot_posterior
bin/inference/pycbc_inference_plot_prior
bin/inference/pycbc_validate_test_posterior
pycbc/distributions/joint.py
pycbc/distributions/utils.py
pycbc/inference/option_utils.py

@ahnitz Allow `pycbc_brute_bank` to use the `.ini` file, I have run bank generation using this PR for 10 mins, no problem, when this PR is in good shape, I will test it by entire template bank generation. I will also update/clean the read config function in this PR soon.

add .ini support in pycbc_brute_bank

---

bin/all_sky_search/pycbc_add_statmap
bin/all_sky_search/pycbc_apply_rerank
bin/all_sky_search/pycbc_coinc_statmap
bin/all_sky_search/pycbc_coinc_statmap_inj
bin/all_sky_search/pycbc_exclude_zerolag
pycbc/events/coinc.py
pycbc/events/significance.py
pycbc/events/trigger_fits.py
test/test_significance_module.py

We were wanting to use more than only the count-number-of-louder background method for the FAR calculations, e.g. extrapolating estimated number of louder noise events using an exponential fit to the ranking statistic
This PR separates off calculate_n_louder to be a bit more modular, allowing either the extrapolation or the counting method to be used. We can add in other methods later if wanted.
The only place I can see that still uses the previous code directly is in the apply_rerank code, which I don't know if this is still used or not, so if that can be retired, I will move the calculate_n_louder function from coinc.py to this module
There is also a testing module (primarily to help me practice writing unit tests)

Add a module for dealing with significance/FAR calculations

---

pycbc/events/significance.py

As pointed out by @spxiwh on #4004, the license was truncated incorrectly.

significance.py license fix

---

companion.txt
pycbc/inference/io/epsie.py
requirements.txt

Fixes the issue that was preventing pycbc from using epsie 1.0. Also moves espie to companion.txt. This fix will also get rid of all of those annoying randomgen warnings in the test logs.

Update to epsie 1.0 and make it an optional package

---

examples/inference/multisignal/get.sh
examples/inference/multisignal/single.ini
examples/inference/multisignal/single.sh
pycbc/inference/models/hierarchical.py
pycbc/inference/models/single_template.py
pycbc/inference/models/tools.py

This depends on #4032 and #4023 and adds multi signal support to the single template model. Similar to the gaussian noise model, at this time, it only supports the case of multiple instances of this model and not any mixed model cases.

add multi signal support to the single_template model

---

docs/workflow/initialization.rst
pycbc/results/versioning.py
pycbc/workflow/core.py
pycbc/workflow/pegasus_sites.py

We want to move to using condorIO (instead of gsiftp) for file transfers to OSG. This got stuck on pegasus not allowing it. With a small tweak to pegasus to disable this check (which I'll try and get in the next pegasus release), this now seems to work smoothly. Some small changes to work with the new docker image are also required.
I would like to merge this now as the OSG site currently doesn't work, but now it will work, if you work with a dev version og pegasus (which I can provide).

Some changes to OSG site to use condorIO

---

bin/all_sky_search/pycbc_sngls_findtrigs
pycbc/events/cuts.py
pycbc/events/stat.py

Separating out the updates to sngls_findtrigs from the offline singles PR, as it makes things a little easier to digest
- Update the sngls_findtrigs code to be more in line with coinc_findtrigs, and therefore more obvious to implement similar things to both codes
- The clustering was previously performed over all triggers, this is now done only on a per-template basis.
- The output files are then the same except for a couple of things:
- The order of triggers changes, as we move from trigger_id order to template_id order
- trigger_id is now a float64 rather than int64: no real reason why or why not to do this
- The attribute timeslide_interval is now given (always zero)

Sngls findtrigs update

---

examples/gw150914/audio.py

Python 3 now divides integers producing floats, so this to go back to integer division.

examples: make slice indices integers

---

pycbc/psd/__init__.py

`psd.from_cli` always tries to set the low frequency values of an analytic PSD to the value at the low frequency cutoff. This causes an IndexError if the low frequency cutoff is set to 0. This prevents being able to use analytic PSDs with the gated gaussian model, for which the PSD is always taken to 0Hz. Patch fixes this by only doing the setting if the low frequency cutoff is not zero.

PSD: don't try to set low frequency values if cutoff is 0Hz

---

examples/search/analysis.ini
examples/search/plotting.ini

Previous default behaviour (before #4053) was to remove against inclusive FAR at the combine statmap stage, so add this option in order to test HR in this stage going forwards

Make combine statmap options more like actual usage

---

bin/pycbc_live

- Move the optimize_snr setup to its own function
- allow singles to call it
- It is only called when no coincs have been uploaded
N.B. There's a bit of an oddity in the test case where the SNR is optimised for the single found at the same time as the coinc, however if this had been uploaded, the optimisation would not have been done. But I think this is okay to leave in

Live optimize singles

---

pycbc/events/single.py

Move fits file reading into the check_singles function, so that the fit parameters are updated rather than loaded once and static

Update live single fits to reload file each time

---

pycbc/fft/fftw.py
pycbc/libutils.py

From discussion in #4076. This should stop the reported segfaults by making DEEPBIND *not* the default, but only used when loading FFTW. I leave it to @josh-willis to explore whether we should always be loading libgomp to make thread settings.

Make DEEPBIND only used for FFTW

---

bin/bank/pycbc_aligned_bank_cat
bin/bank/pycbc_aligned_stoch_bank
bin/bank/pycbc_geom_aligned_bank
bin/bank/pycbc_geom_nonspinbank
docs/tmpltbank.rst
examples/tmpltbank/make_cache.sh
examples/tmpltbank/testAligned.sh
examples/tmpltbank/testAligned2.sh
examples/tmpltbank/testAligned3.sh
examples/tmpltbank/testNonspin2.sh
pycbc/io/ligolw.py
pycbc/tmpltbank/bank_output_utils.py
tools/pycbc_test_suite.sh

This fixes a few issues with the bank placement codes.
* Most importantly, this fixes #3932.
* Fixes the scripts in `examples/tmpltbank`, which no longer work due to CLI syntax changes over the years.
* Updates the documentation page, which was also outdated by the CLI syntax changes.
* Adds one of the examples to the test suite.
Thanks to @soumenroy for help in debugging these issues and providing the modern syntax for `pycbc_geom_aligned_bank`.

Fix broken bank placement code/documentation

---

bin/pycbc_live

PR #4075 introduced a regression in PyCBC Live's SNR optimization: it only uses the interferometers that originally produced the candidate, instead of all the interferometers with usable data. This reverts to the original behavior.
This PR also adds a docstring for `setup_optimize_snr()`, inverts the logic in `check_coincs()` (allowing us to drop one indentation level for most of the function) and includes some minor reformatting and f-string-izing.
I have an old branch with more aggressive refactoring of the SNR optimization, including changes to the files involved in the process. After this is merged, I will try to get that rebased and turned into a PR.

PyCBC Live: fix SNR opt regression + docstrings + code cleanup

---

pycbc/inference/models/single_template.py
pycbc/inference/models/tools.py
pycbc/types/timeseries.py

This patch allows one to demarginalize the coa_phase if it has been analytically marginalized over. I also add an option to 
'at_time' to allow for simple linear interpolation instead of nearest point. This smooths over some issues in the sample rate of the single template model (there are some obvious future improvements here as well).

add reconstruction of phase if it has been marginalized

---

bin/workflows/pycbc_make_uberbank_workflow
pycbc/workflow/core.py
pycbc/workflow/minifollowups.py
pycbc/workflow/pegasus_workflow.py

As per recent discussion in SLACK with Nathan, it seems there is an issue with most workflow generators (not the search workflow, as it explicitly does a `chdir` operation), when the `--output-dir` option is set.
It was intended that the workflow understand this, and use it when dumping outputs, but it used `output_dir` for sites.yml and output.map, but the dax file, the ini file, and the additional planner args (it using the old submit_dax) ended up in the cwd.
This puts the latter 3 also in the output_dir, not the CWD. I have tested this for Nathan's case, but would have to rely on the test case to test a bunch of different possible use cases.

Fix bug in workflow with --output-dir

---

bin/pycbc_live

Fixes a couple bugs introduced in #3984. I have tested that uploads work after this. We do need a way to try some kind of fake uploads in our test suite though.

PyCBC Live: fix bug in mechanism that prevents multiple uploads

---

setup.py

We really need a new release including #4079 as 2.0.4 is broken in many use cases.

Prepare for release

---

bin/hwinj/pycbc_generate_hwinj
requirements.txt

As reported in #4089, `pycbc_generate_hwinj` is not working on master. This should fix it, but I think it probably does pin us to the most recent ligo.lw version, so I updated that (I don't think that will affect anything).
I also note that this would already be broken with the current main of ligo.lw, so changes will be needed again when 1.8.2 / 1.9.0 comes out. 
I wouldn't be surprised if other executables are similarly broken, but as I was testing this anyway following up on #4089 it would be remiss of me not to push this upstream!

Fix generate_hwinj

---

docs/install_lalsuite.rst

This fixes #3974 by updating links to lalsuite in the install lalsuite documentation page to that recommended by @duncanmmacleod.

Fix lalsuite links

---

bin/pycbc_live
bin/pycbc_make_skymap
bin/pycbc_optimize_snr
pycbc/io/ligolw.py
pycbc/io/live.py
pycbc/types/frequencyseries.py
test/test_io_live.py

In a previous PR, @tdent proposed a better name for the `SingleCoincForGraceDB` class. I asked for that change to be made in a dedicated PR, so here it is.
This PR also moves some strictly LIGOLW-specific code (which is used by code that is more general than PyCBC Live) to `pycbc.io.ligolw`, fixes some docstrings, and does some minor code cleanup.
I am also thinking of renaming the `pycbc.io.live` module to `pycbc.io.gracedb`, as there is nothing really specific to PyCBC Live in it (in principle it could be used by `pycbc_upload_xml_to_gracedb` too). Feel free to object though.

Reorganize APIs related to GraceDB uploads

---

.github/workflows/build_venv.yml
.github/workflows/docker-build.yml
Dockerfile
docker/etc/docker-install.sh
tools/docker_build_dist.sh

We have an issue on the LDG clusters with the venv at the moment as the machines are shipped with python[ancient version] and python3.9. Building a venv with python3.8 means we then have to link to python libraries in CVMFS.
Easiest solution to this seems to be to bump both the venv and Docker to python3.9.
I also fix #4048 alongside this.

Update Docker and venv to python3.9

---

bin/pycbc_live
pycbc/psd/estimate.py
pycbc/types/optparse.py

One more patch to try to help with `pycbc_live` performance:
This one moves the FFTs in PSD estimation (done during inverse spectrum truncation), to the new `cached_fft` functions.
I also add an option to allow the PSD not to be recomputed every data block. For the early warning analysis, with 1 second blocks, this is especially relevant. I have set this such that if the data is "bad" the PSD must be recomputed as soon as it is "good" again. (It's still not entirely clear to me what data is used for PSD estimation, and if we should continue computing PSDs until we have X data blocks in the buffer, and then only recompute every Y data blocks).

Speed up psd computation for PyCBC Live

---

pycbc/events/coinc.py

While debugging an issue in some development cythonizing I noticed that the time differences being used in the phase-time statistic were sometimes of the order of thousands of seconds, not the O(0.1s) times we expect.
After some hour(s) of tracking this back, I think a serious bug was introduced to pycbc_live in #3535 (thankfully never used in production). The issue is in the new "to_shift" vector, which was added to rank_stat_coinc. This is *not* locked to the order of ifos in the "sngls_list" sent to the function, but is locked to the order of ifos in the `self.ifos` attribute of the class. Therefore, if the shifted ifo is the *first* ifo, this is wrong. The fix is very short, and I have checked that now the time differences are sane again. (Further motivation for a proper unit test as …

Fix serious bug(?) in PyCBC Live background estimate

---

pycbc/pool.py

This is hopefully a trivial patch, but adds the convenience feature that one can set inference jobs to simply take as many threads as are there by settings nprocesses to -1.

allow for pool size to match total threads automatically

---

pycbc/events/coinc.py
test/test_live_coinc_compare.py
test/validation_code/old_coinc.py
test/validation_code/old_stat.py

We are having difficulties in getting `pycbc_live` to keep up with data in real-time in its current configuration. There may be a few patches from me aimed at this (even if in some cases, we're only speeding up by 1/2%).
It does seem that the main process is becoming a problem in `pycbc_live`'s inability to keep up. One place that was non-negligible in a profile I ran was the RingBuffer used to store singles.
This does look like it is quite inefficient as the buffers are *replaced* (or resized if that is possible??) every time triggers are added (using numpy append). By using more memory, and tracking the slice of the buffer that is relevant, it is possible to greatly reduce the times we resize the buffer arrays.
At the moment this is causing failures, so I need to fix that, but @ahnitz …

Attempt to make faster MultiRingBuffer

---

bin/pycbc_live
pycbc/mchirp_area.py

Given the removal of MassGap as a source category in O4 we set the no-mass-gap option as the default behaviour of the code, resulting in a {p(BNS), p(NSBH), p(BBH)} output.

Make no-mass-gap default option for online source classification 

---

bin/all_sky_search/pycbc_coinc_findtrigs
pycbc/events/coinc.py
pycbc/events/eventmgr_cython.pyx
pycbc/events/stat.py
test/test_live_coinc_compare.py

I've been spending quite a bit of my free time in the last few weeks trying to optimize PyCBC Live so that it does better keeping up with data, and hopefully reduce latency when it is keeping up. 
One bottleneck we've noticed is the logsignalrate function. In the offline all-sky search this function is sent *many* triggers every call, and was optimized for that. However, in the online search it is called *many* more times with orders of magnitude fewer triggers. This requires some differences in how we optimize this code (while not impacting on the offline use case).
Cython seems the natural solution here. Cython is not slower when doing operations on arrays with small numbers of components, is just as fast when there's lots of components, and we can change `range` to `prange` if we want …

Cythonize logsignalrate

---

pycbc/events/coinc.py
pycbc/events/eventmgr_cython.pyx

Another pycbc_live optimization patch.
In this case I have rewritten the code for expiring old coincident triggers in cython. Not entirely sure why this helps, but it seems to provide a factor of about 4 speedup (when comparing after the buffer has accrued 12000s worth of triggers). My suspicion is that the C code is quicker because it does less work in the case that a trigger is not expired, which will be by far the most common outcome.

Use cython to expire pycbc live coinc buffer

---

examples/search/executables.ini
examples/search/submit.sh
pycbc/events/stat.py

This should solve issue #4116; basically doing as suggested, only saving the filenames and wrapping each call to open the file in a `with` statement (except one case which explicitly `close()`s the file)
I think this is good for the idq implementation as well, so hopefully @dethodav / @maxtrevor can comment on that
Testing running now, but the examples don't have iDQ in them so it won't test all parts of the changes

Stat class file closing

---

pycbc/events/coinc.py

@titodalcanton Reported memory issues with #4105 and a potential edge-case bug in #4127.
This should resolve the memory issues by initializing the size of the ring buffers to a much smaller size (8 instead of 128). The ring buffers will grow if needed, but they will now be using (within a factor of 2) the memory that they actually need.
This also patches the case that if a buffer expired *all* triggers the buffer size would be stuck at 0 and the code would crash. I believe this is the cause of #4127.
I think this should be good to go as is, but let me know if there are any requests!

Small update to Sngl Buffer changes

---

pycbc/events/coinc.py

Another patch designed to speed up the PyCBC Live main process: The operation whereby details about the single trigger from ifo 1 is repeated with the N triggers from ifo 2 using numpy.resize is slow. If we instead cache a suitable amount of memory (which will be completely negligible compared to memory usage elsewhere) this can be done much more quickly with a direct assignment.

Cache memory for trig_stat to avoid resize

---

pycbc/events/coinc.py
pycbc/events/eventmgr_cython.pyx
test/test_live_coinc_compare.py

Guess what? Another optimization patch for the PyCBC Live main function.
In this case we target the `ifar` function. This is not as impactful as some of the others (the function is about 6-8% of total runtime, and this speeds it up by about a factor of 2). But in terms of "we really want this to be as fast as possible", and "this patch doesn't change anything functionally", it's worth doing.

Cythonize main part of ifar function

---

pycbc/events/coinc.py
pycbc/events/eventmgr_cython.pyx

Another optimization patch. This moves a number of elements of `time_coincidence` into cython to speed up calls into this code from pycbc_live (probably this won't make any difference to the offline use case, but the online use case of "call this lots of times with reasonably small inputs" is impacted by this, which impacts latency for alerts).
This is passing the test case (when I uploaded this), and doesn't change anything functionally, it's just moving a bunch of stuff into cython.

Cythonization of time_coincidence

---

bin/inference/pycbc_inference
bin/inference/pycbc_inference_model_stats
docs/_include/inference_example_single_marg.sh
docs/inference/examples/single.rst
examples/inference/single/run_instant.sh
examples/inference/single/single_instant.ini
pycbc/inference/io/posterior.py
pycbc/inference/models/tools.py
pycbc/inference/sampler/__init__.py
pycbc/inference/sampler/base.py
pycbc/inference/sampler/dummy.py

Depends on #4093 
This adds a dummy sampler that enables pycbc inference to generate results without requiring the model to have any params that need to be sampled over. This is useful for most uses of the single_template model as all parameters can be effectively marginalized over. One can simply set the sampler to 'dummy' and give a 'num_samples' option. 
I've added an example config file + run script which demonstrates generating the GW170817 results for all parameters the single template model supports.

Generate skymaps without sampling / enable pycbc inference to run model with only reconstructed params

---

pycbc/events/coinc.py
pycbc/events/stat.py

This is now the final patch on my "optimize pycbc live's main process" development branch.
Hopefully this is straightforward: When dealing with relatively small arrays it is more efficient to use methods of arrays, rather than numpy functions (as then you don't have to figure out types, and decide what function to use). This changes the cases that are used most often, and are visible on a call graph.
There are then only a few functions (`searchsorted` for e.g.) which are still sped up by using `export NUMPY_EXPERIMENTAL_ARRAY_FUNCTION=0`, but I've done my best to minimize the effect of forgetting to set this (or when numpy disables it as promised in the future).

Methods preferred over top-level functions

---

pycbc/io/hdf.py

Foreground trigger dumps via HDF currently hard-code ifar (inclusive) and fap (inclusive) as necessary statmap input data - however, these are absent from injection results.

Allow foreground hdf trigger dumps without inclusive (I)FAR

---

bin/all_sky_search/pycbc_combine_statmap
pycbc/events/coinc.py
pycbc/events/eventmgr_cython.pyx

Yet another patch to speed up the PyCBC Live main process.
`cluster_over_time` is a contributing factor to the latency. Both the while/for loops and the repeated `argmax` calls are contributing. Here, I rewrite all of it in cython. The loops are just copies of the python code, I then just replaced `argmax` with a basic version of that in cython. Currently I do *not* delete the old code, and the offline code would use the python implementation by default. @ahnitz is there any reason not to just use the cython code everywhere? I'm concerned about the GPU use case (ie. why was there an option not to use `numpy.argmax` in the first place ... That only makes sense if this has been optimized for GPUs (?)). I don't think continuing to use the python code will impact the offline search, it's …

Implement cython version of cluster_over_time

---

pycbc/inference/models/gaussian_noise.py
pycbc/inference/models/marginalized_gaussian_noise.py
pycbc/inference/models/relbin_cpu.pyx
pycbc/inference/models/single_template.py
pycbc/inference/models/tools.py

I might consider this PR a bugfix. In running some simulations on the marginalized models and testing the accuracy of parameter reconstruction I noticed an inconsistency in how we were handling the phase. 
We were inconsistent in our inner products about the use of 'coa_phase' in various models. Some of these were less obvious than others as they occur in marginalized models where this would be unobservable except when trying to use the partial terms to do phase reconstruction (i.e the complex inner products). Sometimes we would conjugate the data and other times the signal when doing the complex inner products. Either is fine, but if we want to reconstruct the phase, this introduces a sign inconsistency that I was not accounting for. I think the right solution is to use a consistent …

set consistent phase convention for inference models / maybe bugfix? 

---

.github/workflows/inference-workflow.yml
.github/workflows/search-workflow.yml
.github/workflows/tmpltbank-workflow.yml
.github/workflows/workflow-tests.yml
examples/inspiral/run.sh
examples/multi_inspiral/faceon_faceaway.sh
examples/multi_inspiral/run.sh
examples/search/get.sh

Going through the log generated by the test suite is annoying because thousands and thousands of lines are just wget showing the progress of files being downloaded. This adds `-nv` to those wget calls, so they do not show the progress in the logs.

Reduce wget verbosity in tests

---

pycbc/events/cuts.py
test/test_cuts.py

Amend cuts module to allow multiple upper/lower cuts on the same parameter, also check and deal with duplicated cuts.
This is done by updating the cuts dictionaries to be keyed on parameter and the comparison function, rather than the parameter only.
Solves #4146

allow multiple cuts on same parameter

---

examples/inference/lisa_smbhb/lisa_smbhb_relbin.ini

@WuShichao @ConWea This change follows up on the change to the BBHX waveform interface to move to the LISA frame, by default. Now the example needs parameters specified in that frame, or it won't work!

Update to new coordinate frame

---

pycbc/events/coinc.py

@titodalcanton Here's a suggestion for cutting back on memory usage of the single-detector triggers. This just reworks when the resizes are done to be more aggressive than the previous patch, but not falling back to "resize every time". I think there's some more balancing that could be done here, but now the memory usage (of the single-detector buffers) should never be more than 66% more than it was originally.

Rework memory management of single-detector triggers

---

pycbc/waveform/plugin.py
pycbc/waveform/waveform.py

When a user provides a frequency domain (fd) waveform plugin and a waveform length estimator, PyCBC doesn't make a time domain (td) version for the waveform correctly. It seems because PyCBC calls the waveform plugin later than making the fd/td transformation for a waveform model.
This PR encapsulates the fd/td transformation in a function, and explicitly calls this function in the waveform plugin function when the user provides a waveform length estimation.

Fix a waveform plugin issue that missed the waveform length estimator

---

bin/plotting/pycbc_page_foundmissed

This MR addresses the case where the range of recovered injection FARs covers less than 5 orders of magnitude. This scenario can arise when a small number of injections are recovered (likely due to analyzing a small amount of time).  Rather than return an error, tick marks are now placed on every order of magnitude.

Change foundmissed tick step

---

.github/workflows/inference-workflow.yml
.github/workflows/search-workflow.yml
.github/workflows/tmpltbank-workflow.yml
.github/workflows/workflow-tests.yml
examples/search/executables.ini
pycbc/workflow/datafind.py
pycbc/workflow/pegasus_sites.py
pycbc/workflow/pegasus_workflow.py
requirements.txt
setup.py

Pegasus 5.0.3 has been released which contains a few important fixes for PyCBC:
* It is now possible to have a condorpool_symlink and condorpool_copy site, and they'll now work (with some tweaks to the site catalog to add new options).
* We now have the setup needed for OSG running. Note that we are waiting on a condor fix (currently slated for 10.1, but we've asked for it to go in 10.0), which can cause failures when copying files *back* from OSG if the file LFN includes a relative path (e.g. 140567/H1-INSPIRAL-BLAH.hdf).  However, for use-cases that don't use this (GRB, for e.g. probably doesn't want to use GPS time prefixes) we should be fully ready to use OSG "easily".
I am also requesting this be updated on the LDG machines, I suggest folks do so on local clusters as well because you …

Update to pegasus 5.0.3

---

bin/pycbc_banksim

Change in the help message about the template-file : the script can take an hdf template bank file as input, not only xml file

pycbc_banksim : fix the wrong help message

---

pycbc/neutron_stars/pg_isso_solver.py

Optimization and correct handling of corner cases.
Running the code for 10^5 values of dimensionless black hole spin and spin inclination 30 times and averaging the results, we obtained a speedup of 3 times (from 52s to 17s), which is the same reported on the attached plots (run for a single 10^5 points cycle on a different machine).
The high spin case (\chi=1) has also been fixed (see chi1.png).

Analytic Kerr ISCO calculation for EM-bright code

---

pycbc/__init__.py

Update logging to be in UTC - not being in UTC causes some weirdness for logs when spanning a daylight savings change.
This should probably be advertised more generally, so I will ask for "any objection" in the pycbc-code slack channel

Change logging to indicate UTC offset

---

bin/pycbc_live
bin/pycbc_make_skymap
bin/pycbc_optimize_snr
pycbc/events/coinc.py
pycbc/io/live.py
pycbc/population/live_pastro.py
pycbc/population/live_pastro_utils.py
test/test_io_live.py

To get a better estimate of per-event-type noise and signal densities, remove the current FAR trials factor and account for the triggered detectors in the horizon based sensitivity scaling.

Adding per-event-type live pastro

---

bin/all_sky_search/pycbc_coinc_hdfinjfind
bin/plotting/pycbc_ifar_catalog
bin/plotting/pycbc_page_foreground
bin/plotting/pycbc_page_foundmissed
bin/plotting/pycbc_page_ifar
bin/plotting/pycbc_page_snrifar
examples/search/plotting.ini
pycbc/__init__.py
pycbc/io/hdf.py

Some changes were required to allow search including single-detector events to have sensible results pages
These changes are compatible with #4050 
- hdfinjfind: add if statements as the pivot/fixed ifo doesn't make sense without timeshifts
- foundmissed plots: add maximum SNRs and minimum distances to the coloring schemes, as these are decisive in searches which include single-detector triggers
- ifar_catalog: events now may have _really_ low ifar, so using minimum ifar as a limit to the x-axis no longer makes sense
- page_foreground: changes are basically to remove the requirement to say coincs from the code
- page_ifar: change gets rid of the legacy files support
- page_snrifar: change fixes an issue where open-box values could be inferred from closed-box plot limits

Sngls results plotting

---

pycbc/inference/models/relbin.py

@ahnitz This PR fixes the `ZeroDivisionError` at low frequencies if there're zeros at the beginning of the reference waveform in the `Relative` model. I have tested this PR, it works.

fix ZeroDivisionError at low freq

---

pycbc/noise/reproduceable.py

A support for generating a time varying noise is added. With the help of an additional argument `scale` (default = 1.0), one can generate a time varying noise where total time can be broken into smaller equal chunks (time bins) and an array of scale values for each bin can be provided which act as the time varying function. Then time series generated from all the bins can be stacked together. The seed should be same for all the bins.
While generating the coloured noise, white noise is multiplied with the ASD. The `scale` argument is multiplicative factor to ASD. A more general frequency dependent function can be added in future.

Support for generating time varying noise 

---

bin/inference/pycbc_inference_model_stats
pycbc/inference/models/tools.py

This fixes two bugs in the the monte-carlo weights. They were being assigned from the wrong sample due to an index error and for some detectors with the wrong sign! This showed up in p-p testing, but surprisingly not so obvious in individual examples.
This also adds a function that determines what ifos to be enabled based on the observed SNR.

BUGFIX to sky marginalization, fixes to weights, helper function to turn off ifos

---

pycbc/io/live.py

Work in progress to upload a separate probability for MassGap to be included in the EM Bright properties file. Related to issue #4196.

Use mchirp_area to include a HasMassGap probability

---

examples/inference/single/single.ini
pycbc/inference/models/single_template.py
pycbc/inference/models/tools.py

this adds a function to determine what time ranges to use for each detector based on the observed SNR peak of a reference signal's SNR time series. This speeds up marginalization over sky location.

Add function to use only time around peaks for sky / time marginalization

---

bin/pycbc_multi_inspiral
examples/multi_inspiral/check_gw170817_trigs.py
examples/multi_inspiral/run.sh
pycbc/events/coherent.py
pycbc/events/eventmgr.py

This update is to be considered WIP, as is `pycbc_multi_inspiral` after all.  The idea is to bring to master work done by other developers who no longer work on this project, so that current developers can complete it before things get too outdated.
`pycbc_multi_inspiral` is *not* used to the best of my knowledge, aside from the mentioned ongoing development.
The PR comes with its single `pycbc_multi_inspiral` test with one sky point and one timeslide.

State-of-the-art of timeslides development in pycbc_multi_inspiral

---

bin/pycbc_banksim_skymax

Previously `pycbc_banksim_skymax` had small snippets that were redundant. Also, it was unable to recognise the waveform models of the template as they were in byte, and there was a PSD read error. So, I have updated it by taking the `pycbc_banksim` code as a reference.

Make pycbc_banksim_skymax compatible with python3.7+

---

bin/pycbc_live
bin/pycbc_optimize_snr
pycbc/conversions.py
pycbc/io/live.py
pycbc/psd/variation.py

To address #4212 pass the p_terr from CandidateForGraceDB to the snr max setup by treating it as an extra entry in coinc_results. This allows the snr max event to 'remember' p_terr from the initial event

Communicate p_terr to snr opt event

---

examples/inference/margtime/injection.ini
examples/inference/margtime/margtime_inj.ini
examples/inference/margtime/run_inj.sh
pycbc/inference/models/marginalized_gaussian_noise.py
pycbc/inference/models/tools.py

This adds a fix to the case where no valid sky locations are identified using the SNR based draws. If only a small fraction of guessed points are valid, it reverts to prior drawn values instead of potentially producing *zero* (which of course causes an error which this patch not avoids). 
This also adds a new software injection based example of the marginalized_time model. 
Depends on #4201 
@KoustavChandra This PR should hopefully address the issue you were seeing with the marginalized_time model. Please give it a try and let me know if it helps in a case you were seeing fail.

Add new marginalize time example and fixes for when few monte-carlo points are found

---

pycbc/inference/models/relbin.py

For LISA operations we are trying to run relative binning with a small value of the `epsilon` parameter, to ensure high accuracy. This results in the code taking *forever* (hours) to get going, so while I was waiting my hour I thought I'd profile the code, and all the time was spent in one location (the one revamped by this patch).
The complexity of the old code is O(M * N) where M is the length of the input waveform, and M is the number of bins you want to keep according to the code above. The new code is (I think) roughly O(M+N) (not 100% sure what searchsorted does, but I assume it's just a running search through M and N). I did test for some example inputs that the output of the function is identical, and it is, I'm also running a larger test now.
I do suspect there's a nicer numpy …

Reduce complexity of finding relative binning bins

---

docs/credit.rst

This is untested as I could not get the docs to build on my systems due to the BBHx issues. I guess I can look at the artifacts though.

Add second PyCBC Live paper to credit docs page

---

pycbc/events/coinc.py

@titodalcanton Has observed a condition in PyCBC Live where if one detector is down for a long time (days), the memory usage of PyCBC Live grows linearly. This seems to be because the condition for freeing memory in the single-detector trigger buffers is only activated when the `data` method is accessed. This method is only accessed when checking for coincidences against new triggers in the *other* detector. So if the other detector is never on, it never produces triggers, and this never gets called.
This refactors the class a little bit to move "clean up memory" into a separate method, and calls this from both the original location *and* when resizing the arrays in the `add` method. This would then ensure that memory is still freed if `data` is never being called, but hopefully avoiding …

Avoid memory leaks when one detector is down for a long time

---

requirements-igwn.txt

This PR patches the `requirements-igwn.txt` list to include `ciecplib[kerberos]`. This will enable automatic discovery and use of existing Kerberos TGTs for LIGO.ORG authentication.
This relates to the IGWN-internal ticket https://git.ligo.org/computing/helpdesk/-/issues/3216.

Install ciecplib[kerberos] for igwn

---

bin/bank/pycbc_brute_bank
pycbc/neutron_stars/pg_isso_solver.py

When calculating tau0 from the two compact object masses, the code used a fixed frequency of 15.0 Hz that prevented a uniform phase space coverage even with an arbitrarily large tau0-end (please see figures). It was also added tau0-end derivation from the lowest chirp mass, assuring total phase space coverage.

Fixed phase space coverage

---

bin/bank/pycbc_geom_aligned_bank
bin/pycbc_condition_strain
pycbc/io/ligolw.py
pycbc/psd/__init__.py
pycbc/psd/analytical.py
pycbc/psd/analytical_space.py
pycbc/strain/strain.py
pycbc/types/optparse.py

@ahnitz In this PR, I reimplement LISA TDI PSD for (X,Y,Z) and (A,E,T) channels, and sky/polarization averaged sensitivity curve from the LDC manual. This PR will allow PyCBC to simulate LISA noise. The signal injection is in the next PR.
Currently, I need to do 6 more things:

generate LISA TDI-1.5/2.0 noise in PyCBC

---

bin/plotting/pycbc_plot_gate_triggers

New things:
- I've added a --bin-duration argument so we can control the ammount of seconds represented by each bin (previously it was hardcoded as nbins=80 for every case).
- Now --snr-cut-type and --snr-cut-vals are two different arguments because I think it's more intuitive (same thing could apply to the --template-duration cut, but I haven't changed it yet)
The major problem I see is that the split_in_ifos function relies on the single trigger files to be named as "IFO-...", but it works at the moment with the existing naming system.

Adding script for plotting histograms of triggers near gates

---

requirements.txt

If an old version of rtd theme is somehow picked up, then the logo won't properly build. This updates the reqs so the correct minimum requirement is installed.

fix missing logo in docs page

---

bin/live/pycbc_live_plot_combined_single_fits

We noticed an error where the x-axis values were actually counting days since the zero point of GPS time, this resets zero to the first day (as reported in the x label)

Fix x-axis error in combined fits plotting

---

.github/workflows/basic-tests.yml
.github/workflows/distribution.yml
.github/workflows/tut-test.yml

I see this warning on one of the Actions pages:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-python@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
I think this PR does what is needed to fix it.

Update GitHub actions to fix Node.js 16 warning

---

requirements.txt
setup.py

As discussed in https://github.com/gwastro/pycbc/pull/4253 we want to avoid h5py 3.7.0 because of https://github.com/h5py/h5py/pull/2193 and https://github.com/h5py/h5py/issues/2189 .... Note that in the discussion there arrays of 1E5 - 1E6 are discussed. We might be closer to 1E7 - 1E8 in many cases ... and the performance impact there is extreme.
Alex, did I miss anywhere?

Avoid h5py 3.7.0

---

bin/pycbc_multi_inspiral

* Wrapping indexes around for coincs detector frame.
* Calling auto-chisquare on the SNR time series (with desired indices) and not on the array of SNRs of triggers.

Fixed indexing and autochisq argument in pycbc_multi_inspiral

---

bin/all_sky_search/pycbc_sngls_findtrigs
bin/pycbc_process_sngls
pycbc/events/coinc.py

Some codes use cluster_over_time repeatedly over many iterations, where logging is not necessarily appropriate for each clustering step, others use it in one pass-through
By moving the logging out of the function, we are able to be a bit more careful with how this is used; though I have left some logging in the function at debug level.
Any location where the function is used, I have added/altered logging.info as appropriate to keep original functionality unless it was overly verbose
(This was noted as an issue in #4259)

Move logging out of cluster_over_time function

---

bin/live/pycbc_live_single_trigger_fits

I noticed that the trigger fits were being affected by loud signals in the data more than I thought they would be - e.g. the 3-6s and 6-11.5s bins here: 
This adds the ability to remove all triggers within a window of the loudest trigger(s) in each bin. This largely suppresses the excess triggers

Add pruning to the live single trigger fits

---

.github/workflows/basic-tests.yml
.github/workflows/build_venv.yml
.github/workflows/distribution.yml
.github/workflows/docker-build.yml
.github/workflows/mac-test.yml
.github/workflows/search-workflow.yml
.github/workflows/tmpltbank-workflow.yml
.github/workflows/tut-test.yml
.github/workflows/workflow-tests.yml

Taking the advice here
https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre/67939898#67939898
At the moment, the test suite runs *for each commit*. That means if you identify a problem and push a new commit to a branch, you'll have to wait for the previous commit to finish its tests and free up resources to run. I don't think in general we want that behavior and it would tend to bottleneck running the test suite with actively developed PRs. 
This change to our runs of the test suite would mean that only a single set is run per PR (or tag / branch) at a time. The previous workflows from the prior commit are cancelled when a new commit appears.

only run one test suite per PR

---

setup.py

v2.1.0 starts the release line for PyCBC Live to start O4 with.

Change `setup.py` for 2.1.0 release

---

pycbc/frame/frame.py

FrSetMode was removed from lalframe, FrStreamSetMode seems to be equivalent
See https://git.ligo.org/lscsoft/lalsuite/-/merge_requests/1918/diffs

Recover from https://git.ligo.org/lscsoft/lalsuite/-/merge_requests/1909

---

.github/workflows/tut-test.yml

Apparently we overlooked the tutorial tests in #4243.

Enable tutorial tests for Python 3.11

---

pycbc/population/live_pastro.py
pycbc/population/live_pastro_utils.py

This will require changes / additional info in the .json config file for the live p astro calculation, eg 
```
"method": "template_param_bins_types_farlim",
...
"limit_snr": 12.0,
"limit_far": 3.17e-10
```
for a limiting FAR of (just over) 1/100yr and SNR of 12.

Truncate SNR/FAR for live pastro calcs

---

bin/pygrb/pycbc_grb_inj_finder

The trigger dictionary needs the trigger with index eid to be appended, not with index i (which is enumerating the injections)

Bug fix in pycbc_grb_inj_finder

---

pycbc/results/table_utils.py

The table generated by `pycbc_page_injtable` for found injections can't be displayed. I think it's due to an issue of formatting inconsistency. 
See for example [this line](https://github.com/gwastro/pycbc/blob/master/bin/plotting/pycbc_page_injtable#L49), we store numbers between quotation marks. Later it's converted to a numpy array, the data type is unicode not string (see the following). However `pycbc.results.table_utils.html_table` will assign 'string' to ctype for a string type numpy array and assign 'number' for all else formats. I think this causes an issue. The ctype in the google table template should be 'string' for those numbers in quotation marks otherwise the page can't be displayed.
Some codes for illustration
> In [1]: import numpy as np
> 
> In [2]: a = ['123']
> 
> In …

Fix an issue of pycbc_page_injtable

---

examples/inference/relmarg/get.sh
examples/inference/relmarg/reltime.ini
examples/inference/relmarg/run.sh
pycbc/inference/models/__init__.py
pycbc/inference/models/relbin.py
pycbc/inference/models/relbin_cpu.pyx
pycbc/inference/models/tools.py

This adds two new models of the heterodyne type. One is focused on 22-mode only optimizations, while the other is left more generic. An example is added for the latter (which inherits from the former). 
Depends on #4202

add two heterodyne / relative likelihood models dedicated to sky marginalization

---

pycbc/events/coinc.py

I think this implements what Alex suggests for #4270. I've also gone over how the code works here, and think that this is the correct solution (and is fair in that time-slides are treated the same as zero-lag as far as I can see).
I think that this should work with only `1*time_window`, but as we basically want the window to be "large enough that we only ever get 1 coinc in each time slide", and the safety window (https://github.com/gwastro/pycbc/blob/77e26d62994e253d3ae70937de6f0b6c5ec589b9/pycbc/events/coinc.py#L375) https://github.com/gwastro/pycbc/blob/master/pycbc/events/coinc.py#L375 is the full coinc_window *times 10* so I'd rather be safe and go to `2*time_window` to avoid any edge-edge cases.
This is not tested at all.

Proposed fix for 4270

---

bin/pycbc_live
pycbc/events/coinc.py
pycbc/filter/matchedfilter.py

Loud signals in PyCBC Live can saturate the 2-coincident IFAR and potentially saturate the p-value calculated for a followup detector, in the sense that the on-source SNR is louder than every off-source SNR. It would be useful to report this situation downstream, an immediate example being the P(astro) calculation. So this PR adds a flag that detects this occurrence and propagates the information downstream along with the IFAR and p-value themselves.
Note that most of the change is actually just code refactoring/cleanup and docstrings.
@ahnitz let me know if you think there is a better way to do this.

Flag cases when PyCBC Live's IFAR and/or followup p-values are saturated

---

pycbc/inference/models/tools.py

This is a small change to add an option to set the number of sky points used for the precalculation done when doing sky marginalization. It adds an optional argument 
```
marginalize_sky_initial_samples = 1e7
```

add option to set number of sky points in precalculation

---

pycbc/inference/models/relbin.py
pycbc/inference/models/tools.py

This somewhat simplifies the sky marginalization code and adds the option to precompute antenna factors. Likelihood functions have to access them if they want to use that, so  no changes are needed if they can't (or won't) do so. This has a 20-30% performance improvement as the antenna factor calculations were somewhat dominant. 
Depends on #4310

Allow precomputation of antenna factors for sky marginalization

---

bin/pycbc_losc_segment_query
docs/dataquality.rst
docs/inference/examples/gw150914.rst
docs/pycbc_condition_strain.rst
examples/gw150914/audio.py
examples/gw150914/gw150914_h1_snr.py
examples/inference/data/o1.ini
examples/inference/data/o2.ini
examples/inference/margtime/get.sh
examples/multi_inspiral/run.sh
pycbc/catalog/catalog.py
pycbc/dq.py
pycbc/frame/losc.py

One of the `curl` commands we used in the docs/examples was failing to properly download a frame file because of the redirect resulting from the domain change. This fixes that error, replaces gw-openscience.org with gwosc.org throughout the repository, and updates some leftover LOSC mentions to GWOSC.

Replace gw-openscience.org with gwosc.org

---

bin/pycbc_live
pycbc/io/live.py

Proposal of code changes to make the HasMassGap estimation optional (`--enable-embright-has-massgap`) and controllable (`--embright-massgap-max`). I think these options should be in the `pycbc_live` module since this calculation is different to the source classification. 
In case we do not want the mass gap max limit argument to be in `pycbc_live` it can be in `mchirp_area` as `--src-class-mass-gap-max`, but we would need a `--src-class-enable-mass-gap` set to False so the source classification is done without the MG category. 
I can also work in a `src_class_arguments.ini` file as the `p_astro` one.
PR related to the #4300 issue.

Modify HasMassGap to be optional and customizable

---

bin/bank/pycbc_aligned_stoch_bank
bin/bank/pycbc_bank_verification
pycbc/tmpltbank/partitioned_bank.py

A couple of place causing errors as it seems we can't make a list by using `[keys()]` or `array(keys())` any more

Can't generate array directly from dict keys object

---

bin/pycbc_live
pycbc/strain/strain.py

Autogating is currently used for the PyCBC Live full-bandwidth search, but it does not immediately work for the early-warning search due to the short amount of data available (1 s only).
We found that by applying autogating to the last 16 s of the internal strain circular buffer, insted of the new analysis chunk only, autogating works fairly well for the early-warning search too, without an apparent impact on latency (although we need to test this more). One reason for the effectiveness of this approach is that many O3 glitches are composed of a few short glitches in rapid succession, for a total duration of 1 s or longer. Such glitches are hard to gate properly using just 1 s of data, even when trying to use really short gates. Instead, by applying autogating to the last 16 s of the …

Make autogating work for the PyCBC Live early-warning search

---

docs/conf.py

The CI docs is failing with this message:
```
Failed to read intersphinx_mapping[http://docs.python.org/], ignored: SphinxWarning('The pre-Sphinx 1.0 \'intersphinx_mapping\' format is deprecated and will be removed in Sphinx 8. Update to the current format as described in the documentation. Hint: "intersphinx_mapping = {\'<name>\': (\'http://docs.python.org/\', None)}".https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html#confval-intersphinx_mapping')
```
This PR should fix it.

Fix Sphinx deprecation

---

companion.txt
pycbc/waveform/waveform.py
requirements.txt
setup.py

@ahnitz This PR uses the damping time of (2,2) QNM of ringdown from the injected signal to set `rwrap`, now the time-domain injection for SMBHB and SOBHB works fine:
(1) SMBHB (and its zoom-in)
(2) SOBHB:

more physical rwrap for LISA SMBHB/SOBHB injection

---

bin/all_sky_search/pycbc_coinc_findtrigs
bin/all_sky_search/pycbc_sngls_findtrigs
pycbc/events/cuts.py

When running analyses for https://arxiv.org/abs/2203.08545, we saw some times with furious autogating, which destroyed most of the PSD and so the instantaneous sensitive distance was measured to be huge, meaning the statistic blew up.
This cut allows us to discard any triggers at the findtrigs stage where the measured sensitive distance at the time is unphysical, e.g. 50 times the median sigma from triggers in the trigger_merge file.
The check for ReadByTemplate is because we also use the cuts module in the pycbc_live_single_trigger_fits code, but use a dictionary there

Allow cuts on a multiple of the median sigma value

---

pycbc/io/live.py

When PyCBC Live fails to create an event on GraceDB due to an occasional error, it logs the error and then happily carries on and tries to upload the various associated data products, as if no error happened. This is harmless, but it creates confusing log messages, so this PR fixes it.

Do not try uploading stuff if event creation failed

---

docs/conf.py

This implements the suggested fix noted here 
https://github.com/readthedocs/sphinx_rtd_theme/issues/1452
for the issue that jQuery is not loaded correctly. This breaks the search feature as noted in our slack.

workaround for search issue and rtd theme

---

pycbc/types/timeseries.py
test/test_timeseries.py

This mergers the at_time and at_times which had mixed functionality previously. Some vector functionality was only in at_time for example when at_times was added. This addresses that incongruity and so at_times now points to at_time.  And extrapolation fill value is also now possible to give. 
This also adds a unittest for this function.

Update at_time method to allow float / vector types and extrapolation

---

pycbc/distributions/joint.py

@WuShichao I noticed the 'contains' method was quite slow. The way you were retrieving the index was *very* brute force and I think unnecessarily slow. This fixes that. While it's not perfect, since we should directly support vectors, it is a lot better than searching for the index.

make contains method of joint slightly less slow

---

tox.ini

This attempts to resolve #4355 by pinning conda versions of the compiler packages. I don't know why this would be needed .... All I can think is that some of the github runners have conda installed, and have older versions of these, which are then picked up in our builds (on certain runners).

Ensure latest version of conda compiler packages

---

pycbc/scheme.py

In https://github.com/conda-forge/pycbc-feedstock/pull/74 it was suggested to use RTLD_GLOBAL for libgomp. Let's see if this works fine with the test suite (which should answer @josh-willis 's concerns).

Use RTLD_GLOBAL for libgomp

---

bin/pycbc_live
pycbc/strain/strain.py

I just noticed the following behavior in PyCBC Live:
```
2023-05-16T13:25:43.870-07:00 node1466 77 Analyzing from 1368303948.069336
2023-05-16T13:25:47.320-07:00 node1466 77 Recalculating H1 PSD, nan
2023-05-16T13:25:47.320-07:00 node1466 77 Filtering H1
```
Here the horizon distance turned out to be nan for whatever reason (probably h(t) being identically zero, and we are not being very strict with the state vector at the moment) but PyCBC Live happily went ahead and tried to do matched filtering on the data anyway. It turns out that the check for the horizon distance does not work correctly for the case where the distance is nan. This PR changes the logic so as to produce a correct result in this case, and moves the check away from `pycbc_live` and into the StrainBuffer class.

Fix edge case in PyCBC Live's check for horizon distance

---

pycbc/inference/models/relbin.py

This changes the time reference so that the reference and proposed signals in heterodyne likelihoods can be more easily compared on the fly. I also add a function to return the maximum second order relative difference. This is and indication of potential breakdown in the piece-wise linear approximation. This will hopefully make it easier to put together some diagnostics to check (or possibly refine on the fly) frequency bin choices.

Make reference and proposal waveforms comparable, add function to test breakdown of piece-wise apx

---

bin/live/pycbc_live_combine_single_fits
bin/live/pycbc_live_plot_combined_single_fits

Also use dates as xtick labels rather than "Days since X" in the plots, and align grid to date boundaries
I had a look at setting the plot to be horizontal between the start/end of each file, but it was impossible to see anything, so didn't make that change in the end

Live single-trigger combined fits date order bug

---

bin/all_sky_search/pycbc_fit_sngls_over_multiparam

Implementing @tdent's suggestion in #3585, I put in a way to pre-cut templates we are not interested in given the restrictions of each method of smoothing.
As a quick and dirty test, I ran before/after codes on the same bank (O3 hyperbank, 428725 templates) on CIT pcdev5, with the following timing results:
|   | `tophat_smoothing`  | `distance_weighted` |
| --- | --- | --- |
| Before this change | 57 mins | 178 mins |
| After this change | 12 mins | 150 mins |
| Fraction of original | 21% | 84% |
Note that:
- `n_closest` is unaffected by this change (by design)
- It is right that there are more savings for `tophat_smoothing` than `dist_weighted`, as this cuts at 1 in weighted distance, whereas `distance_weighted` cuts at 3 (i.e. 3 times the size)
- The `tophat_smoothing` outputs were …

Implement pre-cuts in fit_over_multiparam for efficiency

---

examples/search/submit.sh
pycbc/frame/__init__.py
pycbc/frame/frame.py
pycbc/workflow/datafind.py
requirements.txt

gwdatafind has a new API. The old one is deprecated and we need to migrate. As the old API doesn't support scitokens, we need to migrate now. Basic instructions are here https://gwdatafind.readthedocs.io/en/stable/intro/
There is still the concept of a persistent connection, but in our use cases we just call datafind once (or a few times) and then carry on, so I didn't bother with the complexity of using the new `session` kwarg. 
Because there is now no persistent connection, I removed the old `setup_datafind_server_connection` function. We do still want to be able to override the datafind server though, so that logic is moved to within the datafind_instance call.
This is code used by both LVK and non-LVK groups' workflows. The test cases will test non-LVK usage, I have tested this works …

Migrate to new gwdatafind API

---

examples/inference/lisa_smbhb_inj/run.sh
pycbc/fft/backend_cpu.py
pycbc/fft/fftw.py
pycbc/fft/mkl.py
tox.ini

Three changes. Two of which should reduce the frequency of the SegFault failures we've encountered a lot recently, one seems to make the CI tests avoid a segfault:
* To make the CI tests avoid a segfault, I ensure that libgomp is not first opened with RTLD_DEEPBIND. This seems to cause problems (in some environments). I don't know why. This seems to fix it.
* MKL becomes the preferred FFT backend over FFTW. MKL-breaking-FFTW segfaults won't occur if we aren't using FFTW.
* pthreads becomes the default FFTW threaded backend over openmp. openmp-related segfaults can't occur if we are using pthreads for threaded FFTW.
This then exposed a few extra things:
* The LISA example doesn't work with MKL because of https://github.com/gwastro/pycbc/issues/4395
* The MKL error catching code didn't work …

Try to fix CI tests

---

pycbc/__init__.py

When trying to run the PyCBC Live example I was encountering the error `OSError: libmkl_rt.so.2: cannot open shared object file: No such file or directory`. This was fixed by explicitly running `conda install mkl` in my environment (although I am still getting the same error running the pycbc live o4 production environment).
Copying the error catching found [here](https://github.com/gwastro/pycbc/blob/master/pycbc/fft/core.py#LL53C16-L53C39) (thank you to Ian) to the same check in `__init__.py` clears up this error.
I can provide more information if anyone would like to figure out why this error was happening, especially when using the pycbc live env on CIT.

Added an OSError exception to MKL check in __init__.py

---

examples/search/analysis.ini
examples/search/plotting.ini
pycbc/types/config.py
pycbc/workflow/core.py

After the discussion on #4363, a defaultvalues section seemed more sensible than specifically overriding certain options

Add a possibility for defaultvalues sections in config files

---

examples/search/plotting.ini
pycbc/workflow/core.py
pycbc/workflow/minifollowups.py
pycbc/workflow/plotting.py

`get_subsections` returns all subsections from the config files, but did so without consideration whether it is an IFO/IFO combination. This meant that if we add a config section for the IFO, it would be double-counted.
This change means that in most (all?) of the places this could be an issue, the IFO / IFO combination tags will be removed from the subsections before they are looped over.
I think this is a solution to #4381

Exclude IFO sections when looping through the get_subsections

---

pycbc/pnutils.py

The `fSEOBNRv5Peak` function is added in `pycbc.pnutils`  to compute the frequency of the peak amplitude in SEOBNRv5_ROM.

Adding SEOBNRv5Peak key and function in the final frequency cutoff 

---

tools/docker_build_dist.sh
tools/docker_build_prepssh.sh
tools/venv_transfer_commands.sh

The current CVMFS location for our venvs (and other IGWN software) /cvmfs/oasis.opensciencegrid.org/ligo has become very full, and after discussion with IGWN computing staff it was decided to set up a dedicated IGWN CVMFS server for software. Most things in here are directly managed by IGWN and so are easy to move, but PyCBC has kind of had it's own back-door to the old server.
This PR will move the PyCBC venvs to the new IGWN server. I have direct access to the machine hosting PyCBC content (and can control who accesses that machine (using SSH certificate)), so we do have the possibility (though I hope not to have to use it) to make changes if needed.
This does not [currently] affect the conda images, which are used more broadly within PyCBC and remain in …

Move PyCBC venvs to new IGWN CVMFS server

---

bin/pycbc_condition_strain

When using a large amount of data, FFTW fails, so allow the user to specify which FFT backend to use

Get FFT options in pycbc_condition_strain

---

bin/pycbc_optimize_snr

Allow PSO and differential evolution optimizers to use the candidate point in the initial array

Allow SNR optimizer to use candidate point in initial array

---

bin/pycbc_multi_inspiral
examples/multi_inspiral/run.sh

At the moment, `pycbc_multi_inspiral` can only search over a single sky position. However, it needs to search over a sky grid covering the GRB error box.
This pull request implements this change. `pycbc_multi_inspiral` now takes an hdf file containing two datasets, `latitude` and `longitude`. The command-line arguments `--ra` and `--dec` are thus removed. After matched-filtering is done, it loops over the sky positions and time slides to perform the coincident and coherent search.
It also fixes the output values of `latitude` and `longitude` which were not correctly written before (set to 0 for all triggers).
This plot below shows, when clustering is disabled, that we indeed get the same triggers when running `pycbc_multi_inspiral` only once over 2 sky points and running …

Allow pycbc_multi_inspiral to search over a sky grid

---

pycbc/psd/analytical.py
pycbc/psd/analytical_space.py

@ahnitz This PR adds the semi-analytical PSD for the AE channel with DWD confusion noise, confusion noise doesn't affect the T channel very much, below is the PSD comparison with Welch PSD measured from LDC Sangria, `5` and `0.1` means the foreground noise subtraction of X years observation:

add TDI AE PSD with confusion noise for LISA

---

bin/workflows/pycbc_make_offline_search_workflow

On the summary page, the snrifar / page_ifar plots are given for each detector combination, but the page_ifar plot for singles was never made.
So the workflow was grabbing the page_ifar plot from the last coincidence (HLV)

Prevent duplicates of the HLV page_ifar plot on the summary page

---

bin/hwinj/pycbc_generate_hwinj_from_xml
examples/detector/loc.py
pycbc/detector.py
test/test_detector.py
test/test_injection.py

This adds the high frequency corrections applicable when the wavelength becomes comparable to the FSR of the detector. 
The current implementation has a couple caveats which is that you can't use vectorized input when using this. Behavior is the same if you don't provide the new 'frequency' argument or if you set frequency to 0. Also, it only works if you use the pycbc methods to add a custom detector. Support for in-built lal detectors is not available atm. I don't think I'm going to add that either, or rather, I think a future PR should just make it so that the lal detectors go through the add_ground_detector api rather than separately as they are now. 
However, this should already help with testing and  implementation into PE, etc. 
So the todo list (not for this PR)
* allow …

add high frequency sky location dependent response for long detectors

---

.github/workflows/search-workflow.yml
examples/search/analysis.ini

@spxiwh @GarethCabournDavies 
There was a mistake in the example search configuration introduced in https://github.com/gwastro/pycbc/pull/4385
This caused the search workflow to suddenly take > 3x longer. This happened because timeslide-interval was in 'defaultvalues' for 'coinc'. The 'injinj' jobs were running timeslides! This means they'll produce a huge number of triggers for later stages due to the very large number of coincidences between different injections. 
I think the comments in #4420 related to performance are mostly due to this configuration error, although if it's not used, it's not a terrible thing to clean  up anyway.

mistake in example search config file

---

companion.txt

ligo.skymap v1.1.0 has a bug (https://github.com/lpsinger/ligo.skymap/pull/22) so it does not declare python versions correctly. This is fixed in v1.1.1 but python3.8 will pick up v1.1.0 unless it is explicitly avoided. It is possible that the pypi release can be fixed (by removing the source code from v1.1.0) to avoid this, but we'd want to avoid this release anyway, and there's a few PRs that want merging.

Avoid ligo.skymap v1.1.0

---

bin/pycbc_copy_output_map
bin/pycbc_stageout_failed_workflow

Rebased version of #3601 . This is a trivial fix from Connor M, and already reviewed, but never got merged.
.... Also including fix for the new ligo.skymap release, which has dropped python3.8 support.

Fix stageout

---

bin/pycbc_live
examples/live/check_results.py
examples/live/run.sh
pycbc/events/single.py

Make sure that the argument to enable single-detector events is set when setting options designed to control them. As well as the upload flag

Add argument verification for singles

---

bin/pycbc_multi_inspiral
examples/multi_inspiral/run.sh

Previously in pull request [#4380](https://github.com/gwastro/pycbc/pull/4380) (now merged), the `--ra` and `--dec` command-line arguments were renamed `--longitude` and `--latitude`.
However, this causes errors with the current workflow generator ([here](https://github.com/gwastro/pycbc/blob/a6d36d6707776425273cb1720a050a8a3b82f680/pycbc/workflow/matched_filter.py#L241)). 
Also `pycbc_multi_inspiral` uses the function `detector.Detector(ifo).time_delay_from_earth_center` which expects right ascension and declination as parameters.
This pull request fixes these issues by reverting the argument parser change to expect `--ra`and `--dec` again.

Rename --longitude and --latitude back to --ra and --dec

---

pycbc/workflow/datafind.py
pycbc/workflow/pegasus_sites.py

The LVK CVMFS server has moved from oasis to a LVK-hosted server. This means a few hooks need updating. I also want to be more generic, because basically if we get any URL starting CVMFS, we should treat it consistently. One CVMFS server is not different to others.
This was being handled correctly in `core.py` for files coming from the config files, but not for the special case of frame files. .... This resulted in me transmitting 2GB frame files to around 60000 jobs running on OSG, and bringing down an OSG submit machine (again!)
I've also updated the pointer to lalsuite-extra, although this may move again soon. The old link does symlink to the new, but this avoid the symlink.

CVMFS files have moved - Treat them properly

---

bin/all_sky_search/pycbc_add_statmap
bin/all_sky_search/pycbc_coinc_hdfinjfind
bin/all_sky_search/pycbc_coinc_statmap_inj
bin/all_sky_search/pycbc_sngls_statmap_inj
bin/workflows/pycbc_make_offline_search_workflow
examples/search/analysis.ini
examples/search/plotting.ini
pycbc/workflow/coincidence.py

Injections do not have inclusive IFAR / FAP calculated, so we can ignore the datasets.
Why?: 
- The injfull/fullinj coinc jobs uses a lot of computation and these are thrown away
- the coinc_statmap_inj jobs are a bottleneck which can spend a lot of time on fullinj/injfull without any value
Proposed solution:
- Don't run injfull/fullinj analyses (done through the workflow generator)
- output empty arays from the statmap jobs for inclusive IFAR/FAP to indicate that this wasn't calculated on purpose
Note that I think we _may_ be able to consolidate the statmap / statmap_inj jobs in the near future because of this change, but this isn't done here.

Purge fullinj / injfull analyses

---

pycbc/workflow/core.py

Use case:
- We are reusing a large bank / phase-time-amp files for many analyses
Problem:
- We don't want to copy the file into every run directory as it is wasting disk space, and removing the "single source of truth" by having multiple copies of the same information
Solution:
- Add an option in the `pegasus_profile` section for the executables to overwrite the retention level with the `pycbc|retention_level` flag, i.e.:
```
[pegasus_profile-bank2hdf]
pycbc|retention_level = do_not_keep
```
- Add an extra retention level into the choices which is 0, and therefore less than the `global_retention_threshold`, so the file is not retained ([this comparison](https://github.com/gwastro/pycbc/blob/433dfd81287dfa47683487aadd8095e6ea7e9b16/pycbc/workflow/core.py#L508) is False)
Testing:
- File is …

Add ability to overwrite file retention level for specific executables from config

---

bin/live/pycbc_live_combine_single_fits
bin/live/pycbc_live_plot_combined_single_fits

Rates plot was showing percentile values above the largest rate, which makes no sense
https://ldas-jobs.ligo.caltech.edu/~gareth.cabourndavies/pycbclive/combine_average_weighting/testing/H1-2023_07_14-2023_08_02-TRIGGER_FITS_COMBINED-counts-original.png
This fix changes to use the percentile of the _rate_ rather than counts, so that we get the correct value out
https://ldas-jobs.ligo.caltech.edu/~gareth.cabourndavies/pycbclive/combine_average_weighting/testing/H1-2023_07_14-2023_08_02-TRIGGER_FITS_COMBINED-counts.png
Change made to mean as well as conservative

Live single fits combined bug

---

bin/live/pycbc_live_combine_single_fits

Some cleanup I thought about when reviewing #4449. I broke the change down into a few commits to make checking easier if needed.

Live cleanup combine single fits

---

requirements.txt

When running `pegasus-plan` this script:
https://github.com/pegasus-isi/pegasus/blob/6b7e41d7ebfacca23d853890937e593a248e6a6a/packages/pegasus-python/src/Pegasus/cli/pegasus-preflight-check.py
will be run, and `pegasus-plan` will fail if any of its checks fail. Most commonly, we see cases where this fails because GitPython is missing.
Now, this is weird, because `pegasus-plan` lives in `/usr/bin` and `GitPython` is installed in the /usr/lib64/.../python3.6 PYTHONPATH. However, for reasons I don't understand pegasus uses the intermediate script https://github.com/pegasus-isi/pegasus/blob/master/bin/pegasus-python-wrapper before calling python codes. This will select your current environment version of pegasus, not /usr/bin/python, as one might expect.
Then if your environment doesn't have …

Add hidden pegasus dependencies

---

bin/pycbc_convertinjfiletohdf
pycbc/workflow/injection.py

I don't know if the file specification changed, or if someone changed from py2 to py3 without thinking, but this attribute is bytes in some of the examples we have been given

Run conversion on all hdf injection files, allowing LVK injection format hdf files to be used

---

pycbc/workflow/jobsetup.py

So that we can vary inspiral settings over different parts of the bank, we would like to use splitbank tags in the inspiral jobs and do this via config, in the config files, this would look something like:
```
[inspiral-bank0]
cluster-window = 0.5
[inspiral-bank1]
cluster-window = 1
```

pass splitbank tags to inspiral jobs

---

pycbc/workflow/dq.py

The PyCBCCalculateDQFlagExecutable output file was initialised with the workflow analysis times.
This meant that the outputs from each segment were all named the same as each other, so the run would not start.
This seems to fix things, but will wait for @maxtrevor to confirm that his run is working

Idq workflow times

---

examples/search/plotting.ini

For a search including single-detector events, the decisive SNR for whether a signal is detected is actually the maximum SNR
See e.g. [comment here](https://github.com/gwastro/pycbc/blob/4488619e969fd36142a9a4f9fe6bc93d15fbcb6b/bin/plotting/pycbc_page_foundmissed#L123)

Change decisive to network optimal snr in foundmissed

---

pycbc/workflow/dq.py

This bugfix is needed for the use of dq flags with multiple segments in the O4 production PyCBC offline search

Bugfix for multiple dqflag files

---

bin/pycbc_inspiral

pycbc_inspiral's --cluster-window option has a default of -1, but expects 0 to indicate no clustering in [this line](https://github.com/gwastro/pycbc/blob/1e360a077992d851c579d7fee3600ebe05dc07fe/bin/pycbc_inspiral#L397)
Updating to use 0 as default to fix this
Found by accident when I introduced a different bug in testing :wink:

default bug in cluster-window in pycbc_inspiral

---

bin/workflows/pycbc_make_offline_search_workflow

The offline search was erroring when it was trying to run exclude_zerolag without any other statmap files.
This adds some logic to allow that search configuration

Bugfix: allow two detectors exactly in offline search

---

pycbc/events/stat.py

Add in a statistic which uses both KDE and DQ reweighting
Checking with @tdent and @PRAVEEN-mnl that the KDE bit has been taken in properly, and with @maxtrevor that the DQ stuff has been brought in okay.
The summary is as follows:
- copy `__init__` from the DQ statistic, but add in the stuff needed for kde - `assign_kdes` basically, but needs to pass this through to the other class.
- inherit `logsignalrate` from the KDE statistic - Please confirm there is no DQ reweighting here
- inherit `lognoiserate` from the DQ statistic - Please confirm there is no KDE reweighting here

Add KDE/DQ statistic

---

docs/workflow/initialization.rst
pycbc/types/config.py

This patch stores the environment into the pycbc.types (and pycbc.workflow, which subclasses) ConfigParser object. The environment is stored directly into a new special section `os_env_vars`. This can then be directly accessed by using things like `${os_env_vars:GWDATAFIND_SERVER}`, as you would for any other section.
Motivation: Quoting Stuart """DAGMan getenv=true no longer works with HTCondor 10.4.0 and newer:
At the request of the Pegasus team recent version of Condor DAGMan, including the version installed on the LLO cluster on Aug 22 (LHO Aug 29; CIT Sep 5), no longer support "getenv=true" https://opensciencegrid.atlassian.net/browse/HTCONDOR-1580 """
This has bitten quite a few condor workflows, including PyCBC. (@ahnitz you should definitely be aware of this for when sugar/atlas …

Store and allow access to environment in ConfigParser

---

.github/workflows/basic-tests.yml
.github/workflows/distribution.yml
.github/workflows/mac-test.yml
.github/workflows/tut-test.yml

Python 3.7 reached end of life 2 months ago. This stops testing under it and changes the distribution action to use Python 3.8.

Stop testing on Python 3.7

---

bin/all_sky_search/pycbc_bin_trigger_rates_dq

This small fix makes the number of dq bins used configurable.
Not having this was not causing any errors, but when using binary dq flags, the bin that flagged data would be assigned to was dependent on the flag's active time. By setting the number of bins to 2 with a config setting, a binary dq flag should always result in flagged times getting assigned to bin 1, while unflagged times are assigned to bin 0.

Make number of dq bins used configurable

---

bin/all_sky_search/pycbc_bin_trigger_rates_dq

Previously the lower frequency bound was pulled from the template bank for each template. The lower frequency bound had a step function around mtotal = 100 msun causing some heavy bbh templates to be evaluated as having longer template durations than medium mass systems with a higher low frequency bound.

Make pycbc_bin_trigger_rates_dq use a uniform f_low

---

bin/all_sky_search/pycbc_bin_trigger_rates_dq

When I got rid of the hardcoded `percent_bin = 0.5 ` I did not remove a later reference to the percent_bins variable, which causes an error.
Previously the code had ` n_bins = 100 / percent_bin ` so I have replaced the remaining the reference to `percent_bin/100` to `1/n_bins`

Fixed bug created when making number of dq bins configurable

---

pycbc/events/coinc.py

We currently call `background_bin_from_string` with a set of 10 "bins" (for DQ purposes, @maxtrevor could explain more). Each of these 10 bins uses the SEOBNRv4 duration function. Currently every template will call the SEOBNRv4 generator 10 separate times, resulting in almost 10 million calls to the duration function. The SEOBNRv4 duration function also seems to be quite slow, leading to jobs taking O(4 hours) to complete, which normally would be almost instant.
While it would be better to somehow compute and store these durations, this is complicated as this duration is distinct from the actual template duration. It is, however, easy to rewrite this function so that we don't call the exact same function 10 times for every template. I can then live with these codes taking 10s of minutes. …

Speed up background_bin_from_string

---

test/test_tmpltbank.py

We've seen some failures where the test CI times out downloading this file. I tried downloading on the command line, and curl does hang for some seconds before starting this .... Presumably github is doing something to serve this to curl.
It seems easier to compress this file (much smaller) and then use that. `numpy.loadtxt` will deal with `.gz` files without issue. I've already added the `.gz` file to the place where those exist (outside of `pycbc`), so just swapping the test to use that.

Use compressed template bank test files

---

bin/plotting/pycbc_plot_dq_flag_likelihood
bin/workflows/pycbc_make_offline_search_workflow
pycbc/workflow/plotting.py

This commit adds a new executable for plotting the likelihood factor found from computing trigger rates during dq flags, and adds it to the offline workflow. This should be the last code change needed to support the use of dq flags in O4.

Plot trigger rates during dq flags

---

bin/plotting/pycbc_page_sensitivity

As events may be considered releasable at IFAR ~0.5 days, extend the default sig bins to cover this.
Also tweak the FAP bins a bit

Tweak default significance 'bins'

---

bin/plotting/pycbc_page_foreground
pycbc/io/hdf.py
pycbc/io/ligolw.py

Fixes this error reported by Sunil:
```
File "/home/sunil.choudhary/39_max/bin/pycbc_page_foreground", line 183, in <module>
fortrigs.to_coinc_xml_object(args.output_file)
File "/home/sunil.choudhary/39_max/lib/python3.9/site-packages/pycbc/io/hdf.py", line 861, in to_coinc_xml_object
proc_id = ligolw_process.register_to_xmldoc(outdoc, 'pycbc',
File "/home/sunil.choudhary/39_max/lib/python3.9/site-packages/ligo/lw/utils/process.py", line 100, in register_to_xmldoc
process = proctable.RowType.initialized(program = program, process_id = proctable.get_next_id(), **kwargs)
File "/home/sunil.choudhary/39_max/lib/python3.9/site-packages/ligo/lw/lsctables.py", line 586, in initialized
cvs_entry_time = lal.UTCToGPS(time.strptime(cvs_entry_time, "%Y-%m-%d …
```

Fix error in page_foreground and cleanup

---

bin/live/pycbc_live_combine_single_fits
bin/live/pycbc_live_single_trigger_fits

This addresses a couple issues with the single-detector trigger fitting code used by PyCBC Live.
First of all, the current code requires a manual specification of the template duration bins. If the specified bins do not cover the entire duration range of the templates, the search will crash as soon as a trigger is produced from one of the "misrepresented" templates. This PR adds an option to read the durations directly from the bank and calculate the bins accordingly on the fly, so that we no longer have to manually keep track of the durations (we do still need to tell the code if we switch to a different bank file path, but that is hopefully harder to forget).
Second, `pycbc_live_combine_single_fits` will currently refuse to combine a set of fit files done with different fitting …

Improvements to single-detector trigger fitting code for PyCBC Live

---

pycbc/events/stat.py

The mass weighting for the BBH statistic, and the KDE weighting in the KDE statistic were not being used in the rank_stat_single.
This is as the logsignalrate function, to which these were added, is appropriate for coinc events only as it is where the PhaseTD stuff is calculated.
The sensitive volume term is directly calculated in the rank_stat_single function for ExpFitFgBgNormStatistic, so that is okay
This does show how making the statistics a bit more modular will definitely help prevent oversights like this, but that is more invasive and a long-term project

rank_stat_single was not using KDE or BBH weighting - bugfix

---

bin/minifollowups/pycbc_injection_minifollowup
bin/minifollowups/pycbc_page_coincinfo
bin/minifollowups/pycbc_page_snglinfo
pycbc/workflow/minifollowups.py

The injection minifollowups currently show the closest event, this means that anything which had a trigger at the same time, but was discarded for some reason, is not obvious.
For example, this should help to diagnose why things are present in the SNR triggers plot, but not the reweighted SNR plot

Add details of closest triggers to the injection minifollowup

---

bin/workflows/pycbc_make_offline_search_workflow
pycbc/workflow/configuration.py
pycbc/workflow/core.py
pycbc/workflow/pegasus_workflow.py

We realised that the pegasus logging was getting a little out of hand in the `pycbc_make_offline_workflow code`. Here I fix this three ways:
- The log that was overbearing was specifically [this one](https://github.com/pegasus-isi/pegasus/blob/c5fa8830081ab4fc282a5dfe6a80f981b5b394e5/packages/pegasus-api/src/Pegasus/api/workflow.py#L1715) from pegasus, so I have added a line to grab the logger for this module, and set the logger level to be one level above the default pycbc logger (so, e.g., INFO would not be shown as default in this code)
- I also did the same trick for the scitokens warning [here](https://github.com/scitokens/scitokens/blob/4a7066527571230ca35b8bab9ffc9ea97f3da364/src/scitokens/scitokens.py#L656).
- I have reduced the level of [this …

Make logging better for pycbc_make_offline_workflow

---

bin/pycbc_live

By chance I discovered this bug when a candidate event came into the MDC while I was running things.
Bug:
`setup_optimize_snr` adds the command line commands used to run the snr optimization to an object so the snr optimization can be re-run at a later time (I think). If `run_snr_optimization` is not given to `pycbc_live` (you don't want snr optimization) then presumably you won't have set snr optimization options and therefore it can't add `snr_opt_options` to the command and will crash.
Fix:
- Set the `snr_opt_options` to None if `run_snr_optimization` isn't set
- Check whether the `snr_opt_options` is not None before trying to add it to command.
Just need to do a quick test to see if this actually fixes the issue.

[pycbc live] Don't add snr options to command if they don't exist

---

bin/all_sky_search/pycbc_bin_trigger_rates_dq
pycbc/io/hdf.py

Using this meant that I was able to actually complete a run of this code using realistic analysis files!
Basically use the mechanism described in https://github.com/gwastro/pycbc/pull/4510 to pre-mask the triggers before loading, also move some repetition of the same calculation out of the loops it was repeated in.
Some increased logging as well

Apply some needed efficiency savings to pycbc_bin_trigger_rates_dq

---

pycbc/io/record.py

Currently, if you import the record module in `pycbc.io`, it will cause numpy to start casting `float` and `int` to `float32` and `int32` respectively. The default in numpy is to cast `float` and `int` to 64 bit scalars. The cause of this is due to the numpy `scTypeDict` being updated with ligolw bindings in `record.py`. In ligolw, `float` is cast to `float32` and `int` to `int32`.  This patch fixes that by not including the `float` and `int` mappings from ligolw. This will cause single precision values to be cast to double when reading a ligolw xml file, but that should only result in some meaningless extra digits being added to values.

Don't overwrite default numpy bindings from liglow in record.io

---

pycbc/events/coinc.py
pycbc/pnutils.py

Allow SEOBNRvXROM durations to be used without having '_ROM' in the v5 approx name
Also simplify some calls to peak frequency etc

Rationalize some calls to waveform properties

---

bin/pycbc_inspiral
pycbc/psd/variation.py

sample rate of 2028 was hardcoded in the PSD var calculation. This was an issue if we wanted to use a different sample rate!

allow psd var sample rate to change as needed

---

bin/all_sky_search/pycbc_calculate_dqflag

The performance of DQ flags is much better if we don't have to pad them to start/end on integer seconds. Previously PyCBC only checked if the start of each second was flagged, with no support for better time resolution.

Read DQ flags with finer time resolution

---

bin/bank/pycbc_aligned_stoch_bank

The current version of `pycbc_aligned_stoch_bank` fails when using a variable upper frequency cutoff. This seems to be due to a minor typo in variable names (`m1` instead of `mass1`, etc). This PR fixes the typo and includes some minor cleanup as well.

Fix error in aligned_stoch_bank

---

bin/all_sky_search/pycbc_fit_sngls_split_binned
examples/search/plotting.ini

`pycbc_fit_sngls_split_binned` can be a real issue with memory usage. A recent example at production scale reported 200GB of RAM usage. If we decide that we can ignore triggers with single ranking less than (say) 5.5 this can be greatly reduced .... and if you want all the triggers, you can still use the 200GB!
This optimizes the memory usage based on how many triggers are needed. This is now based on `stat-threshold` *and* the new option `plot-lower-stat-limit`. If we could solve #4524 it would simplify the implementation here. I've tested this on a large example and the output plots are indistinguishable to me ... They wouldn't be if I'd messed up the new "idx_map" thing.

Optimize memory usage of pycbc_fit_sngls_split_binned

---

bin/minifollowups/pycbc_foreground_minifollowup
bin/minifollowups/pycbc_plot_trigger_timeseries

Up to now non-coinc ifos have been ignored in terms of actually plotting their triggers around an event. Also there was a strange bug which led to a yellow star actually being plotted for these ifos (I guess with the SNR value of the last trigger in the file, given that the ID passed was -1). Use the mean coinc time to determine triggers in window and don't try to plot any special coinc trigger.

Non-coinc ifos in minifollowup trig plots

---

bin/pygrb/pycbc_pygrb_plot_stats_distribution

Remove glue dependency and modify file to use hdf instead of xml for pygrb stats_dist.

Modify stats_dist to utilize hdf

---

docs/release.rst

I made this mistake: bad idea
Here I add an explicit warning on the release instruction page so that I am more careful about this in future

Add warning re failed builds on releases

---

pycbc/workflow/pegasus_sites.py

There's an issue with our recent CVMFS images, where the singularity image for OSG is not being correctly set. I'm not sure why the release images do not contain any of the git information (or `last_release`) now, when they used to. However, releases should explicitly use the *current* release.
I think this fixes it, but it can't really be tested unless I make a release and see!

Releases not pointing to correct singularity image

---

pycbc/live/snr_optimizer.py

We added the init population based on actual parameter values and randomized within bounds earlier it was 0-1 random variables. #4555

added scaling of initial pop in snr_optimizer

---

bin/plotting/pycbc_plot_singles_vs_params

`pycbc_plot_singles_vs_params` was broken by recent changes in matplotlib. The note about "behaviour of hexbin" here https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.8.1.html specifically broke thinks. My understanding is that before we set `mincnt = 0`, but that actually meant "minimum count is 1 trigger in that bin". Now it means "minimum count is 0 triggers in that bin", and the code fails if you try to take the maximum of 0 triggers.
I put in a version-dependent switch on the `mincnt` parameter to fix this. This resolved the problem in a single test case, I'm running a bunch more in a full workflow now.
.... It also took ages to debug this, because the code reads *way* more triggers than it needs to. I've implemented the HFile mask thing in this code as well. This …

Fix plot_singles and optimize memory

---

bin/minifollowups/pycbc_page_snglinfo
bin/minifollowups/pycbc_sngl_minifollowup
bin/workflows/pycbc_make_offline_search_workflow
pycbc/events/stat.py
pycbc/io/hdf.py
pycbc/workflow/minifollowups.py

When we have lots of things in the autogating vetoes, these can dominate the singles minifollowups.
This allows us to provide the gating vetoes to this job as elsewhere in order to remove them.
However they are still informative (e.g. we may have an autogated loud signal!). So we also have a minifollowup with `--vetoed-time-only` option.
The main changes here are:
- Add the gating vetoes options and implement
- Allow a `--vetoed-time-only` option
- Allow passing of both veto file and foreground-censor file, this is as we do not want foreground-censored things to show up in a 'vetoed time only' section
- Update the offline workflow to use this specification as appropriate

Use gating windows in sngl_minifollowup and allow 'triggers within vetoes' option

---

bin/workflows/pycbc_make_offline_search_workflow

After #4564, the offline workflow generator became super-verbose with nothing set.
This fixes it back to be info by default

Fix over-verbose offline workflow generator after init_logging change

---

bin/all_sky_search/pycbc_coinc_findtrigs

Numpy is imported simply as `import numpy` in `pycbc_coinc_findtrigs`. There is a single call of `np.array` which will cause a name error:
`NameError: name 'np' is not defined`.
This is a simple fix to replace `np.array` with `numpy.array`.

Fix bug with numpy import in pycbc_coinc_findtrigs

---

bin/minifollowups/pycbc_plot_trigger_timeseries

Looking at the plots of missed loud injections in results pages, it was confusing that things had triggers with `snr` but not with `newsnr_bells_and_whistles`
This adds back in the things which were removed as they had sngl-ranking of 1
Old output:
New output:
SNR for good measure:
I've also added a brief explanation to the caption about why there are some triggers with ranking 1

remove removal of downranked triggers

---

Dockerfile
docker/etc/docker-install.sh
docs/building_bundled_executables.rst
docs/install.rst
docs/install_lalsuite.rst
docs/workflow/pycbc_make_offline_search_workflow.rst
tools/cvmfs-default.local

Some places were missed in #4440
The basic method behind finding the changes needed was:
```git grep cvmfs | grep lalsimulation | grep openscience```
followed by
```
:%s:/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/lalsuite-extra/current/share/lalsimulation:/cvmfs/
software.igwn.org/pycbc/lalsuite-extra/current/share/lalsimulation:g
```
(VI command) in each file it was found in to make the change

update lalsimulation cvmfs path

---

bin/all_sky_search/pycbc_fit_sngls_split_binned

Previously only a few parameters were allowed to be used as binning / splitting parameters in `pycbc_fit_sngls_split_binned`; this change makes many more parameters available for use
This also makes the labelling a bit more straightforward
I'd like to look over this code and make it a lot nicer to work with at some point - mainly as this was written fairly early-on in my use of python so is quite badly written

split/bin parameters in pycbc_fit_sngls_split_binned

---

bin/all_sky_search/pycbc_coinc_findtrigs

When using `pycbc_coinc_findtrigs` with results from the PyCBC online search I found a bug when using two different integer typed objects in numpy's `intersect1d`. 
The Bug:
- `template_id`s for the live triggers are stored as unsigned integers of type uint64
- `numpy.arange` creates an array of integers which are of type int64
- When intersect1d is called on two objects of the same type it returns an object of the same type
- When intersect1d is called on two objects of different type (uint64 and int64) it returns an object of the type float64
This is a problem because the outputs of intersect1d are using to index an array and float values are not allowed for indexing.
I have enforced the type int64 on the output of the `numpy.uniq` function to match what should be produced by …

[bug] Enforcing int types in pycbc_coinc_findtrigs

---

companion.txt
examples/inference/samplers/epsie_stub.ini
examples/inference/samplers/nessai_stub.ini
examples/inference/samplers/run.sh
examples/inference/samplers/simp.ini
pycbc/inference/io/__init__.py
pycbc/inference/io/dynesty.py
pycbc/inference/io/nessai.py
pycbc/inference/sampler/__init__.py
pycbc/inference/sampler/nessai.py

This PR adds basic support for the nested sampler [nessai](https://github.com/mj-will/nessai) in pycbc inference.
This implementation is intended as a starting point that can be refined and improved upon, so there are some limitations (see below). Below I mention a few points that I think are important and/or may need some discussion/tweaks.
**Changes**
- Add `pycbc/inference/io/nessai.py` which includes two classes: the main interface and the nessai model object
- Add `pycbc/inference/sampler/nessai.py` (based on the equivalent for dynesty)
- Add `nessai` to the dictionary of samplers in `pycbc/inference/sampler/__init__.py`
**Config files**
I wanted to avoid needing to provide types for every single keyword argument nessai supports, so I opted to use `ast.literal_eval` to evaluate the …

Add support for nessai sampler in pycbc inference

---

bin/pycbc_make_skymap
bin/pycbc_optimize_snr
pycbc/io/live.py

Discussion in #4534 highlighted another case of matplotlib's backend being set deep into a module, which can lead to problems. This PR fixes that case by making sure the backend is set at the initialization of the executable scripts which use that module.

Do not set matplotlib's backend in internal modules

---

bin/all_sky_search/pycbc_add_statmap

The wrong IFO combo was being passed to the significance dictionary to decide the method used for calculating the FAR in each combination during hierarchical removal
This led to events using the exponential method of FAR calculation when they should have used the counting method, and having very extrapolated IFARs!

bug in choosing the far calculation method

---

examples/search/plotting.ini

#4549 allowed us to omit vetoed times from the singles minifollowup and separate them into vetoed vs not-vetoed times.
This change adds vetoed times minifollowup into the CI example

Use vetoed times followup in example

---

pycbc/frame/frame.py
pycbc/strain/strain.py

When using gwdatafind to query for a given frame type and channel name, the pycbc.frame module assumes that the frame type starts with the letter identifying the site (H, L, V etc). However it appears that this assumption is not always valid: for example, recent Virgo data seems to have changed the frame type to HoftOnline, making it impossible to use `query_and_read_frame()` to retrieve Virgo data.
This PR changes `query_and_read_frame()` so that the frame type (and therefore the `--frame-type` CLI option) is allowed to have a "S:" or "S?:" prefix, in which case S is taken as the site. For backward compatibility, this prefix can be omitted, in which case the site will be taken from the channel name instead. If that also does not start with the right prefix, the code prints a warning and …

Fix error querying Virgo frame type

---

bin/all_sky_search/pycbc_make_bayestar_skymap
bin/all_sky_search/pycbc_prepare_xml_for_gracedb
bin/all_sky_search/pycbc_upload_single_event_to_gracedb
pycbc/io/hdf.py
pycbc/io/live.py
pycbc/results/__init__.py
pycbc/results/snr.py

The PR #4438 was getting too long and complicated to review, and there was an obvious split in order to make this more simple.
Here I separate off the changes for new executables being used.
These are for:
- The creation of the XML for the specific event to be uploaded 
- The script for uploading the single event
- A wrapper script around bayestar
The first two of these are basically a split of the existing 'upload many events from this XML' script so that the files can be prepared in advance, and then uploaded later.
The wrapper around bayestar is so that we can specify the output filename and use them in the workflow
The changes to existing files are mainly so that we can reuse existing code without repetition, and a minor change so that the XML uploads from offline match the convention …

Scripts for dealing with preparation of offline gracedb upload files

---

bin/pycbc_make_sky_grid

This PR adds the code that generates the sky grid that will be used by `pycbc_multi_inspiral`. 
The sky grid is circular and the points are placed following the method described in Section V of https://arxiv.org/abs/1410.6042.
The grid is first generated centered on the North pole, then rotated to the center of the localization error region. The output of the code is an hdf file with two datasets : `ra` and `dec`, corresponding to the sky points `pycbc_multi_inspiral`will loop over.

Add the code to generate the sky grid that will be used by pycbc_multi_inspiral

---

bin/live/pycbc_live_plot_single_trigger_fits
bin/live/pycbc_live_single_trigger_fits

We noticed that fit plots weren't being made; this was as there were no triggers produced.
To show that nothing is broken, we should make an empty plot stating that there are no triggers

Live: produce empty trigger fit plot for detectors with no triggers

---

setup.py
tox.ini

Looking at https://github.com/gwastro/pycbc/pull/3997, it seems like `M2Crypto` was added to the conda environment due to being a transitive dependency ([via `ciecplib`](https://github.com/gwastro/pycbc/pull/3997#issuecomment-1092842815)). Since `ciecplib` has removed its dependency to `M2Crypto` on version `0.7.0` [(src)](https://github.com/duncanmmacleod/ciecplib/blob/5ee4a251b347c41ede9f77060c72df4f8c34b6b9/debian/changelog#L4), this PR attempts to bump the minimum required version for `ciecplib` and remove the `M2Crypto` dependency.

Remove M2Crypto dependency

---

pycbc/live/snr_optimizer.py

When an option is not given at all getattr on the args object gives None, but we don't want to translate that into "--option-name None" on the subprocess command line.

fix thinko in option parsing for defaults

---

bin/live/pycbc_live_plot_combined_single_fits
bin/live/pycbc_live_plot_single_trigger_fits

The main functional changes proposed here are:
1. The addition of the `--x-lim-lower` and `--y-lim-lower` options to `pycbc_live_plot_single_trigger_fits`, which I think are useful to precisely compare distributions and fits between different days.
2. A simplification of the coloring scheme of the duration bins, now based purely on the bin index (which I think makes more sense - also note that the `bin_proportion()` function had a small bug). With log bins there is no visual change from this, but less code.
3. The legend in the single fit plots, which is usually quite long, is moved out of the way.
4. (In progress) A fix for the visualization bug that seems to happen when there are days with no triggers.
The rest is my usual round of cleanup and minor QoL improvements to logging and CLI.

Improvements to single fit plots

---

bin/minifollowups/pycbc_foreground_minifollowup
bin/minifollowups/pycbc_injection_minifollowup
bin/minifollowups/pycbc_sngl_minifollowup
bin/minifollowups/pycbc_upload_prep_minifollowup
bin/workflows/pycbc_make_offline_search_workflow
pycbc/workflow/minifollowups.py
pycbc/workflow/psd.py

The PR #4438 was getting too long and complicated to review, and there was an obvious split in order to make this more simple.
Here I separate off the changes to the workflow to allow the new executables (in #4534) to be called in a minifollowup.
The basic outline of this PR is that a new minifollowup is created (optional), which makes the files to upload and outputs to an 'upload_files' directory in the main output directory of the search.
The main change is the code `pycbc_upload_prep_minifollowup`; this defines a minifollowup which prepares files for upload to gracedb, including:
- an XML file, including PSD and SNR timeseries
- the `.fits` file from running bayestar (well the wrapper around it)
- the skymap plot from this fits file
- a plot of the SNR timeseries of all active …

Workflow changes needed to manage offline gracedb upload prep

---

bin/pycbc_convertinjfiletohdf

After introducing the LVK format for injections, there are three kinds of injection files right now:  `*.xml`, `*.hdf` with LVK format and `*.hdf` with PyCBC format (which is generated from `pycbc_create_injections`). 
This PR adds an operation to deal with PyCBC format: don't do anything and just make an copy. 
I slightly change the order of the `if...else...` in the last few lines, as the current logic appears clearer for me. 
I tested this PR with a PyCBC format injection file, and it indeed got copied and seems to work fine.

fix for injection file created from pycbc_create_injections

---

docs/frame.rst

The frame documentation gives read_frame example without start/end times, whereas the search query above it uses these times.
Its not actually clear what happens without the options given, as I would have thought it would read the whole file, but if there are multiple frames within the file, only the first seems to be read, unless the start/end time are given.

Slight tweak to example in frame documentation

---

.github/workflows/basic-tests.yml
.github/workflows/distribution.yml
.github/workflows/inference-workflow.yml
.github/workflows/search-workflow.yml
.github/workflows/tmpltbank-workflow.yml
.github/workflows/workflow-tests.yml

Hi, version 4 of upload-artifact and download-artifact were recently released.
Staying on old version is not viable long term because GitHub will sooner or later drop support for the old versions of node that these depend on.
Since migration to v4 is not as straightfoward as bumping the version number, I'm helping all astropy-related packages byt manually performing the necessary changes.

MNT: upgrade upload/download-artifact GitHub actions

---

bin/inference/pycbc_inference
bin/inference/pycbc_inference_extract_samples
bin/inference/pycbc_inference_model_stats
bin/inference/pycbc_inference_monitor
bin/inference/pycbc_inference_plot_acceptance_rate
bin/inference/pycbc_inference_plot_acf
bin/inference/pycbc_inference_plot_acl
bin/inference/pycbc_inference_plot_dynesty_run
bin/inference/pycbc_inference_plot_dynesty_traceplot
bin/inference/pycbc_inference_plot_gelman_rubin
bin/inference/pycbc_inference_plot_geweke
bin/inference/pycbc_inference_plot_inj_recovery
bin/inference/pycbc_inference_plot_movie
bin/inference/pycbc_inference_plot_posterior
bin/inference/pycbc_inference_plot_pp
bin/inference/pycbc_inference_plot_prior
bin/inference/pycbc_inference_plot_samples
bin/inference/pycbc_inference_pp_table_summary
bin/inference/pycbc_inference_table_summary

Prompted by trying to debug an inference run and following the changes made in https://github.com/gwastro/pycbc/pull/4576, standardize the logging in `bin/inference` to use the new `pycbc.add_common_pycbc_options` function.
I've only changed executables that already had a `verbose` option.

Standardize logging in bin/inference

---

bin/pygrb/pycbc_pygrb_plot_injs_results

This is a separate PR to fix a specific bug when generating plots of injection sky-errors in the new PyGRB workflow. There is some preliminary discussion in #4443. 
This comes down to a tricky naming issue. Injection trigger files now contain the injection information AND the associated found triggers. In the `load_sky_error_data` function, this file is referred to as `input_file_handle`. Separately, the trigger file containing background triggers is used for other calculations. This one is referred to as `trig_data`. Previously the function was trying to compare data from two different types of trigger files (i.e. comparing found injections to background triggers). This went undetected until now because in early tests, one of these arrays ended up being empty. I believe this was because …

PyGRB: Sky-error plot fix

---

pycbc/_version.py
pycbc/_version_helper.py
tools/pycbc_test_suite.sh

I noticed that `pycbc_inspiral --version` fails with the following error:
```
File "/cvmfs/software.igwn.org/conda/envs/igwn-py311/bin/pycbc_inspiral", line 214, in <module>
opt = parser.parse_args()
^^^^^^^^^^^^^^^^^^^
File "/cvmfs/software.igwn.org/conda/envs/igwn-py311-20240206/lib/python3.11/argparse.py", line 1869, in parse_args
args, argv = self.parse_known_args(args, namespace)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/cvmfs/software.igwn.org/conda/envs/igwn-py311-20240206/lib/python3.11/argparse.py", line 1902, in parse_known_args
namespace, args = self._parse_known_args(args, namespace)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/cvmfs/software.igwn.org/conda/envs/igwn-py311-20240206/lib/python3.11/argparse.py", line 2114, in …
```

Fix broken --version option

---

bin/live/pycbc_live_combine_single_fits

Differen t bin edges should cause the code to skip the file, here we add a check for the size of the array(s) to ensure the elementwise operation won't error.

Bug: Live combine fits, different bin edge sizes causes an error

---

bin/pycbc_live

LOD = localization-only detectors
* Do not initialize single-detector FAR estimators for LOD
* Only use triggering detectors for PSD var statistic
* Ignore LOD in rank > 0 processes
* Correct the GraceDB annotation to explain which detectors contributed to the FAR and list the LOD
* Only list triggering detectors in background dump filename
* Code reformatting
I decided to leave the LOD in the name of the main output files, because to me that prefix indicates which interferometers are in principle represented in that file, and in fact the PSDs of the LOD are stored in it.

Improve how pycbc_live handles localization-only detectors

---

bin/all_sky_search/pycbc_fit_sngls_over_multiparam

Older code that this is copied from had the option of reading fit smoothing parameter values from an input fit file, rather than from the template bank (or calculating on the fly).  This is no longer done so remove the (useless) option and references to it in help for other options

Clean up options and help for fit over multiparam

---

bin/pycbc_optimize_snr

Fix issue in non-default settings for some options that Max complained about

SNR optimizer option types

---

bin/inference/pycbc_inference_model_stats
companion.txt
docs/inference/examples/sampler_platter.rst
examples/inference/samplers/run.sh
examples/inference/samplers/snowline_stub.ini
pycbc/inference/io/__init__.py
pycbc/inference/io/snowline.py
pycbc/inference/sampler/__init__.py
pycbc/inference/sampler/snowline.py
pycbc/pool.py

The snowline sampler (https://github.com/JohannesBuchner/snowline) is for unimodal distributions but may be good for some cases where we have very high SNR signals. (or want a quick initial estimate).

Add pycbc support for the snowline sampler

---

pycbc/workflow/pegasus_workflow.py

Change the selector profile to `execution.site` from `execution_site`.
See: https://pegasus.isi.edu/documentation/reference-guide/configuration.html

Fix Pegasus selector profile key

---

bin/workflows/pycbc_make_offline_search_workflow

Added a the option stop-after under [workflow] where you can supply the options ['inspiral', 'hdf_trigger_merge', 'statmap'] for the time being to only do the workflow up until the specified job.
This is useful for clusters such as OSG where inspiral jobs can be parallelized to one core jobs and be parallelized over many nodes. Single processing is not ideal on OSG so this option is useful for these types of clusters.
This does not take into account injection inspiral jobs. 
Also, when using these options, make sure to change the file-retention level in [workflow] such that your files do not get deleted when the workflow finishes running.

Allow option for workflow to end at inspiral jobs

---

pycbc/types/timeseries.py

We've been following up some failures [in LVK readiness replay tests] where PyCBC has been producing outputs that Bayestar cannot ingest. This comes from the `pycbc_optimize_snr` code and is because SNR timeseries being output are not centered around the trigger times. Seems to happen mostly for followup ifos, where the SNR is small.
We tracked this down to a BUG in timeseries.time_slice. Specifically we do:
```
_numpy.isclose(start_idx, round(start_idx))
```
to check if the start_idx being computed is close enough to the number above (ie. start_idx = 56.9999). In that case, we don't want to round down, and instead just assume that 56.9999 is 57. *HOWEVER* if the idxes are large enough, this can give some strange output. For example:
```
>>> numpy.isclose(42998.58, 42999)
True
```
The …

BUGFIX in timeseries.time_slice rounding

---

pycbc/psd/analytical_space.py

@WuShichao I removed all for loops from the space PSD functions to avoid unnecessary time costs. There are still duplicate lines though, not sure if you want to optimize them further.

avoid using for loop in space psds; fix typo

---

bin/live/pycbc_live_combine_single_fits
bin/live/pycbc_live_plot_combined_single_fits
pycbc/events/single.py

We noticed some plotting issues with when there are zero-live-time days for singles fit plots.
This PR:
- removes invalid values from the `mean` count and fit coefficient calculation inputs, so that the count does not become infinite. This would effect results where we use the `mean` value - at the moment we use `conservative` so it doesn't matter
- adds markers to the plot, so that we can see information where there is a day on its own
- Allows the labels to be in scientific format below 1e-3, so that we don't simply state zero for the mean and conservative values of these
The cumulative effect of these can be seen in the before / after comparison below:
Before:
After:

Update how live fitting deals with invalid values

---

pycbc/inject/inject.py

When working with the InjectionSet class in a notebook it is somewhat annoying that you can't rerun it without running into file handling issues. This occurs because it keeps an open connection to the file. If you want to say rewrite the injection file or have a separate write handle, this can be incompatible. We don't actually use the file handle for anything, so I've removed the property and put in a close at the end of initialization.

don't keep file open within injectionset

---

tox.ini

@ahnitz This PR specified a branch 2 weeks ago for BBHx. 
**Note:
`BBHx` updates its Python requirement to be >=3.12 due to some updates in Michael Katz's other LISA packages, but PyCBC's CI tests are for older versions of Python.**

specify an older branch of BBHx in tox.ini

---

pycbc/inference/io/base_hdf.py

This fixes a bug introduced in previous PR of mine. I missed that the file handler was being closed in a place. It no longer exists, so we need to take this line out.

file handler no longer exists, so will fail if closed

---

.codeclimate.yml

We previously used the beta channel of pylint, before it was fully supported in codeclimate. No reason to do this now, and the beta channel seems to fail. This PR will still report codeclimate failures, but digging deeper seems to suggest that this is working. A PR rebased to this after this is merged will be the real test.
@ahnitz can you merge this.

Fixing codeclimate failures (hopefully)

---

bin/all_sky_search/pycbc_upload_single_event_to_gracedb

Uploading an event without supplying `--labels` causes an error.
Though we probably will want labels added, this is still a bug

Bugfix: allow nothing to be given in --labels

---

bin/all_sky_search/pycbc_fit_sngls_over_multiparam

Update `pycbc_fit_sngls_over_multiparam` to take in multiple --template-fit-file inputs
This will be useful for e.g. if we generate `pycbc_fit_sngls_by_template` for part of the data, e.g. a day, and then want to smooth over many days at once, we could do this in a rolling window in the live search
- Firstly, read in the files and concatenate datasets together: `template_id`, median_sigma`, `count_above_thresh`, `count_in_template` and `fit_coeff`.
- While doing this, check that all the attributes which should match (`ifo`, `sngl_stat`, `fit_threshold`), do. Otherwise, RuntimeError
- For each of `nabove`, `ntotal` and `invalphan`, smooth identical template_ids over files before doing the smoothing over parameters as before. This works as these datasets are linearly added for smoothing.
- …

Allow pycbc_fit_sngls_over_multiparam to take in multiple files

---

pycbc/waveform/waveform.py
test/test_waveform.py

`pycbc.waveform.get_fd_waveform_sequence` requires `sample_points` to be a pycbc `Array`  instead of a numpy array. Since `get_fd_waveform` and `get_td_waveform` do not demand any inputs to be pycbc custom types (probably because most/all inputs are floats), it makes sense to add a check for `sample_points` being a numpy array and converting to an `Array` if that is the case. This PR does exactly that.

Check if sample_points is a pycbc Array and convert if not

---

bin/pycbc_live
examples/live/run.sh
pycbc/filter/matchedfilter.py
pycbc/strain/strain.py
pycbc/waveform/bank.py

This should fix at least some of the issues identified in #4643, at least avoiding a crash when similar problems occur.
Specifically, this does the following:
* Add a `--pvalue-lookback-time` CLI option that controls how much time we need to do the followup p-value and SNR time series calculation. The option defaults to 150 s, so no change in CLI is needed here and no functional change is expected.
* Redesign the logic around the `--max-length` CLI option, which was previously confusing and I think unnecessary. Now the length passed to `StrainBuffer` is *exactly* what given via `--max-length` (not twice that, or something calculated via other means). There is also a check to make sure the value is sensible when `pycbc_live` is starting (this addresses one of my early comments in #4643). …

Fix IndexError in PyCBC Live's followup code

---

bin/live/pycbc_live_supervise_single_significance_fits

Typo in the supervision script
This change affects the live search
None

Typo in live significance fits supervision script

---

setup.py

This PR patches `setup.py` to dynamically discover the NumPy include path, rather than hardcoding.
Fixes #4698.
This change affects: everything
This change changes: the build
This change will: require a new release
The current build is broken when using numpy 2.0.0 release candidates.
Patch `setup.py` to use `numpy.get_include()`.
Fixes #4698 
Local testing

Fix numpy include path

---

bin/plotting/pycbc_plot_bank_corner
pycbc/results/scatter_histograms.py
pycbc/tmpltbank/bank_conversions.py

Added a fits-file option to the `pycbc_plot_bank_corner` code so that we can use it to plot fit coefficient, number of templates per bin, etc. in a nice format
This is a new feature.
This change affects plotting, for possible use with the offline and live codes, and provides a minor bugfix for an edge case in a seldom-used module
This change has been proposed using the [contribution guidelines](https://github.com/gwastro/pycbc/blob/master/CONTRIBUTING.md)
As we are intending to use template fits which automatically update in pycbc live, we should make diagnostic plots whenever the file is updated.
- Added a fits-file option to pycbc_plot_bank_corner
- Added the fits file into the default title
- As this makes it quite long, I've added the --title option to the code to choose something …

Add option to plot fits in bank corner plot

---

pycbc/distributions/joint.py

This change should have no adverse affect on functionality

fix contains method of joint distribution

---

bin/bank/pycbc_brute_bank

This saves the minimal match chosen to the output template bank. This is useful for comparing banks after the fact.

save minimal match to brute bank

---

bin/pycbc_make_banksim

A few minor bugfixes that are required in the `banksim` workflow's postprocessing scripts to ensure compatibility with latest versions of `ligo`, `matplotlib` and `python`.
This change affects: the banksim workflow
This change changes: result presentation / plotting
This change will: re-enable current functionality
To ensure compatibility of banksim postprocessing with updated Python 3.9+ and matplotlib 3+.
- handle the encoding of bank file names, as they are being written as UTF8.
- call the `get_table` method inside of `ligo.lw.Table`
- update argument for call to create histogram with `matplotlib.pyplot.hist`
Fixes #4700

Minor bugfixes in the `banksim` workflow's postprocessing 

---

pycbc/inference/models/gaussian_noise.py
pycbc/waveform/generator.py

This PR adds support for using detector-frame waveforms (e.g. those produced by `get_fd_det_waveform`) in the inference module.
**Summary of changes**
- Add a new generator class, `FDomainDirectDetFrameGenerator` 
- Add the `det_frame_waveform` option to the `GaussianNoise` class to which enables the use of the new generator.
I considered automatically determining if a waveform is implemented in the detector frame or not, but I wasn't sure if a waveform could support both, so opted for a boolean instead. I can change this if it is preferred. I'm happy to rename the class/variables.
**Example**
My use-case for this is for performing inference in LISA with BBHx, so I've tested this with a modified version of the existing SMBH injection example. Here's the result:
I can also add this version …

Support detector frame waveforms for inference

---

pycbc/scheme.py

Fixing a (Freudian?) typo I caught.  It's processing scheme rather than precessing scheme.

Typo fix: precessing -> processing

---

bin/all_sky_search/pycbc_make_bayestar_skymap
pycbc/workflow/minifollowups.py

When generating bayestar skymaps in the upload prep minifollowup, the approximant used was not the same as in the rest of the workflow, this caused issues.
Here we use the standard approximant interface used by other codes in order to work out the appropriate waveform.
This change affects: the offline search
This change changes: result presentation / plotting, scientific output
This change will: require a new release on the v23 release branch so that it can be used for o4 LVK results
The correct approximant was not being used for the bayestar subprocess, this means …

Use approximant parsing argument for make_bayestar

---

bin/pygrb/pycbc_pygrb_efficiency

`extract_basic_trig_properties` wants 5 arguments but it only had 4 in `pycbc_pygrb_efficiency`.

Correct call to extract_basic_trig_properties in pycbc_pygrb_efficiency

---

bin/pygrb/pycbc_grb_inj_combiner
bin/pygrb/pycbc_make_offline_grb_workflow

These changes affect PyGRB.
This PR removes a check on the injection set name that can cause empty results from `pycbc_grb_inj_combiner`. It is up to the user to provide valid inputs to the executable, and placing a filename constraint is unnecessary.

Remove PyGRB injection set name check

---

.github/workflows/distribution.yml
.github/workflows/inference-workflow.yml
.github/workflows/mac-test.yml
.github/workflows/search-workflow.yml
.github/workflows/tmpltbank-workflow.yml
.github/workflows/workflow-tests.yml
bin/minifollowups/pycbc_page_coincinfo
bin/plotting/pycbc_page_coinc_snrchi
bin/plotting/pycbc_page_snrchi
bin/plotting/pycbc_plot_hist
pycbc/io/hdf.py
pycbc/results/versioning.py

THIS WILL BE MERGED ONTO THE v23 RELEASE BRANCH. A SEPARATE PR WILL BE SETUP FOR MERGING THIS
ONTO THE MAIN BRANCH.
We have noticed that many plotting jobs are using a lot of memory. As LDG clusters are now enforcing memory usage more closely, we are having issues getting jobs finished. 6 jobs in particular were identified as offenders:
plot_hist
plot_coinc_snrchi
plot_snrchi
page_foreground
sngls_statmap
merge_page_coincinfo
This patch addresses 5 of them (not sngls_statmap, which is not plotting in any case). 4 of these will also be an issue on the main branch (plot_hist should already be less memory intensive there). Of these 4, 1 is a trivial patch to move across, but others will need reworking to match up with Gareth's changes in #4545. The change to hdf.py also needs Alex to look …

V23 BRANCH: Optimize plotting job memory usage

---

bin/pygrb/pycbc_pygrb_page_tables

This PR cleans up `pycbc_pygrb_page_tables`:
- empty lines, whitespaces, indentation, redundant backslashes, etc.;
- output files are no longer all required, but the user needs to specify enough output file paths when providing a found-missed injections file and enough output file paths when dealing with loudest onsource/offsource; there are checks in place for all this and these have made other checks further down in the code redundant;
- the `do-injections` flagged is removed: just check whether the user provided a `found_missed_file`;

Clean up of pycbc_pygrb_page_tables

---

bin/workflows/pycbc_make_inference_inj_workflow
pycbc/workflow/injection.py
pycbc/workflow/jobsetup.py

The problem: `pycbc_create_injections` takes the `--config-files` option, but `setup_injection_workflow` assumes a single configuration file is passed to `pycbc_create_injections` jobs with the `config-file=...` option.  This is a general limitation (and, specifically, PyGRB would gladly avoid this).
This PR allows `setup_injection_workflow` to also accept and handle multiple files under `config-files`.
The motivation to modify `setup_injection_workflow` is to not break the existing behaviour and syntax, but to expand it (i.e., users can rely on `config-file=...` and `config-files=...` passing one or multiple files).  The cleaner solution would be to modify the `PycbcCreateInjectionsExecutable` class so that `def create_node(self, config_file=None, ...)` works as `def create_node(self, …

Allowing config-files when setting up pycbc_create_injections injection job

---

bin/live/pycbc_live_plot_combined_single_significance_fits

The `pycbc_live_plot_combined_significance_fits` code had a bug where it would sometimes cut off the final datapoint, this fixes the bug
This change affects: the live search
This changes: plotting
The combined significance fits plots did not always show the latest datapoint, we wanted to fix this. This basically comes from the fact that the start / end points of the fits files are not exactly on a date boundary.
We use the datapoints themselves to decide the xlim, rather than the ticks which can move compared to the datapoints
By adding some padding to the end of …

Fix combined plots xlim bug

---

bin/all_sky_search/pycbc_sngls_findtrigs

sngls_statmap is taking a lot of memory, part of that is the lack of real cuts being applied to sngls_findtrigs
There is no scientific benefit to keeping anything below the stat-threshold being used in pycbc_sngls_statmap, so this way we can cut things out that we won't use later as early as possible
This is an efficiency update
This change changes:  result presentation / plotting, scientific output (a little bit)
sngls_statmap has very high memory use - this is mainly due to sngls_findtrigs not getting rid of anything
Implement a --minimum-stat …

V23_RELEASE_BRANCH Implement minimum statistic storage in sngls_findtrigs

---

bin/pycbc_multi_inspiral
examples/multi_inspiral/faceon_faceaway.sh
examples/multi_inspiral/run.sh

This is a: bug fix and adds a minor new feature
It only affects `pycbc_multi_inspiral`
This change fixes a bug in the comparison procedure between left and right projected coherent SNRs.  The cut on coherent SNR must be applied **after** the point-by-point comparisons of left/right SNRs and not prior to it to the two SNRs individually.  This ensures that arrays of equal lengths are compared.
This PR also renames an option and adds `--version`.

Fix bug in left-right SNR comparison in pycbc_multi_inspiral

---

bin/pycbc_multi_inspiral

Cleanup of the sky grid and antenna pattern calculations in `pycbc_multi_inspiral`.
This is a code cleanup and minor bugfix.
No changes to results or scientific output are expected.
No functionality or API should be broken by this.
`pycbc_multi_inspiral` implements a very long algorithm right now, including many branches and multiple long loops. Looking through it, I noticed that the code handling the sky grid CLI and calculating the antenna pattern is more complicated than necessary, uses more variables than needed, and pollutes the namespace with several temporary variables. There is also a check for simultaneous usage of `--sky-grid`, `--ra` and `--dec` which is not entirely correct, for example it will miss the cases where `--sky-grid` and `--ra` are both …

Cleanup sky stuff in multi_inspiral

---

bin/pycbc_multi_inspiral
pycbc/results/pygrb_postprocessing_utils.py

- Passing options from `pycbc_multi_inspiral` command line to the methods that calculate null SNR, cut in null SNR, and calculate reweighted SNR.
- Renaming `n_ifo` as `ifo_idx` to avoid confusion with the already existing `nifo`.
- Grouping together the definitions of auxiliary variables.

Options and cuts in pycbc_multi_inspiral

---

pycbc/psd/analytical_space.py
test/test_coordinates_space.py

Force `tdi` to be `str` just like other places in the code. Otherwise, PyCBC Inference will read it as a number. that will cause error.
This change affects: inference
Fix issues encountered in PE.
Adding `strt()` to all `tdi` input.

add str() to all tdi

---

bin/pygrb/pycbc_make_offline_grb_workflow
bin/pygrb/pycbc_pygrb_efficiency
bin/pygrb/pycbc_pygrb_minifollowups
bin/pygrb/pycbc_pygrb_page_tables
bin/pygrb/pycbc_pygrb_plot_chisq_veto
bin/pygrb/pycbc_pygrb_plot_coh_ifosnr
bin/pygrb/pycbc_pygrb_plot_injs_results
bin/pygrb/pycbc_pygrb_plot_null_stats
bin/pygrb/pycbc_pygrb_plot_skygrid
bin/pygrb/pycbc_pygrb_plot_snr_timeseries
bin/pygrb/pycbc_pygrb_plot_stats_distribution
pycbc/results/pygrb_postprocessing_utils.py
pycbc/workflow/grb_utils.py

This is a new feature in the PyGRB post-processing which enables and applies the cut in reweighted SNR, something that `pycbc_multi_inspiral` does not apply, preserving all reweighted SNR information until the end of the filtering stage.
This change affects: PyGRB, post-processing only.
This change changes: result presentation / plotting, scientific output
The option to cut in reweighted SNR existed but was never used.
* General options to define null SNR, reweighted SNR, and SNR cuts are placed in separate "add_to_parser" methods.
* Codes using those options call the specific "add_to_parser" methods they need.
* The cut in reweighted SNR was implemented.  HDF input is parsed and the reweighted SNR is used to determine what information to keep.  This does not assume that network and IFO …

Reweighted SNR cut enabled in PyGRB post-processing

---

bin/pycbc_multi_inspiral
pycbc/events/coherent.py

This PR flags in a clearer way where the request of a minimum SNR in at least 2 detectors happens in the PyGRB search.
It also avoids introducing a redundant dictionary.

Commenting single IFO cut in PyGRB

---

bin/pygrb/pycbc_pygrb_plot_null_stats
pycbc/events/coherent.py
pycbc/results/pygrb_postprocessing_utils.py

This is a: bug fix with some minor cleanup in style.
This change affects: the PyGRB search
This change corrects scientific output
This change was tested by running a full PyGRB workflow.
The null SNR cut used by `pycbc_multi_inspiral` implemented a discontinuous threshold reported in Eq, (12) [here](https://arxiv.org/pdf/1410.6042).  The correct formula for a continuous threshold is reported in Eq. (4.73) of [this](https://orca.cardiff.ac.uk/id/eprint/128124/) PhD thesis.
While correcting the code to reflect the correct null SNR cut, I also cleaned up `pycbc_pygrb_plot_null_stats` for line length, indentation, etc.
A full PyGRB workflow (in its current form) was run.  I am attaching a plot before the fix and one after the fix.  Injections are no longer ending in the vetoed region.  The …

Fixing null cut in pycbc_multi_inspiral

---

.github/workflows/basic-tests.yml
tools/install_travis.sh

git has introduced a post-hook ban for security, but it seems to break git-lfs
This is the workaround until that is fixed
This is a fudge
This change affect continuous integration
Fix as suggested by the failure message
https://github.com/git-lfs/git-lfs/issues/5749
Testing is through the CI

disable git lfs post-clone hook checks for lalsuite-extra

---

.github/workflows/basic-tests.yml
pycbc/waveform/parameters.py
pycbc/waveform/waveform.py
tools/install_travis.sh

There are some important options for generating XPHM, which we need to support in the v23 release branch. There is a related PR (#4728), which tries to deal with the more general case, though there are concerns about lalsimulation's naming and how to predict that.
For now, I hardcode the necessary values, and leave a more general discussion for the main branch. 
For the wider audience: BE CAREFUL WITH PHENOMXPHM! There is a rare failure mode where it will produce `inf`s (or other garbage) for long waveforms. This appears to be a bug with the multi-banding, which is on by default.
I have tested this on one of these failure modes via a HDF input file, with the new option (avoiding multi-banding) I get sane output, without I get infs.

Allow PhenomXPHM options in laldict for v23 release branch

---

bin/all_sky_search/pycbc_make_bayestar_skymap
bin/all_sky_search/pycbc_upload_single_event_to_gracedb
pycbc/psd/variation.py
pycbc/workflow/minifollowups.py
setup.py

This is a list of cherry-picks, and updating release number, for the 2.3.7 release.

More changes for v2.3.7 release

---

bin/pygrb/pycbc_grb_inj_finder

This change affects: PyGRB.
This change changes: result presentation / plotting, scientific output.
The PyGRB workflows were showing inconsistent injection results in the output pages:
1. Network power chi-squares looked erratic
2. Differences between injection and recovery times were scattered all over the analysis time (for both injection sets used; the axes are in seconds)
3. Recovered chirp mass values were incompatible with the injected values.
[Here](https://ldas-jobs.ligo.caltech.edu/~francesco.pannarale/LVC/GRB170728A_may2024_test2/) is a webpage with these, but I will not keep it much longer at this point.
`pycbc_grb_inj_finder` was sorting timing information, extracting indices with `argsort` based on such sorted array and using them on other two arrays that …

Sort all quantities consistently in grb_inj_finder

---

bin/plotting/pycbc_page_coinc_snrchi
pycbc/io/hdf.py

The `pycbc_page_coinc_snrchi` code was using a lot of memory - this fixes that
This also fixes the memory usage of `get_snglfile_array_dict` in `ForegroundTriggers`
This is an efficiency update, with a minor bugfix involved as well
This change could change result presentation / plotting, but it doesn't outwith the bugfix
This change, follows style guidelines (See e.g. [PEP8](https://peps.python.org/pep-0008/)), has been proposed using the [contribution guidelines](https://github.com/gwastro/pycbc/blob/master/CONTRIBUTING.md)
The `pycbc_page_coinc_snrchi` code was using a lot of memory
This also fixes the memory usage of `get_snglfile_array_dict` in `ForegroundTriggers`, as used by `pycbc_page_foreground`
There was a minor bug in …

Efficiency savings for pycbc_page_coinc_snrchi, and ForegroundTriggers get_snglfile_array_dict

---

pycbc/distributions/external.py

@WuShichao There is a bug in the external from fun distribution in how it retrieves the parameter name. 
At the same time, the config file format was overly complicated. I've simplified this. so that one can do 
[prior-final_mass]
name = external_func_fromfile
file_path = spin.txt
column_index = 1
The change is backwards compatible. 
@WuShichao Can you please verify and review? Also add it to your todo list to put in a unittest for this class.

fix cdfinv of external text file distribution when multiple are  used in a joint distribution

---

pycbc/strain/strain.py
test/test_strain.py

Update `pycbc.strain.strain.execute_cached_fft` so that the epoch of the output frequency/time series is set to match that of the input rather than being zero.
This change affects any code that makes use of `execute_cached_fft` or functions/classes that call it. This includes `pycbc.filter` and `pycbc.psd` given this, it could impact a large part of the codebase.
This change will: fix an existing bug
This fixes a bug in `pycbc.strain.strain.execute_cached_fft`
* Specify the `_epoch` attribute of the …

Fix epoch in cached fft

---

bin/pycbc_inspiral
bin/pycbc_multi_inspiral
bin/pygrb/pycbc_pygrb_plot_chisq_veto
examples/gw150914/PyCBCInspiral.ipynb
pycbc/events/eventmgr.py
pycbc/vetoes/autochisq.py
test/test_autochisq.py

Unlike other chi-squared values methods, autochisq.values() computes the number of degrees of freedom but does not return it.  This PR makes the situation even across the values methods of the various chi-squares.
This change affects: PyGRB (autochi-square plots can now be generated) and `pycbc_inspiral` (coincident searches) but the degrees of freedom are dumped to `_` so nothing meaningful is modified.
A full PyGRB workflow with the generation of autochi-square plots was successfully carried out.

Enabling output of dof from autochisq.values()

---

.github/workflows/basic-tests.yml
tools/install_travis.sh

This change affects continuous integration
This change has been proposed using the [contribution guidelines](https://github.com/gwastro/pycbc/blob/master/CONTRIBUTING.md)
Revert the changes in #4755 
https://github.com/gwastro/pycbc/pull/4755
https://github.com/git-lfs/git-lfs/issues/5749
Tests are in the CI

Revert Git lfs clone protection workaround

---

bin/workflows/pycbc_make_inference_inj_workflow
bin/workflows/pycbc_make_psd_estimation_workflow
bin/workflows/pycbc_make_sbank_workflow
bin/workflows/pycbc_make_uberbank_workflow
docs/resources/sbank_example1.ini
docs/resources/sbank_example2.ini
docs/resources/uberbank_example1.ini
examples/faith/pegasus_workflow_conf.ini
examples/tmpltbank/bank_workflow_test/test_uberbank.ini

Add the versioning page to a few workflows whihc did not save the information
This is a fix to add version information
This change affects the bank generation workflows
Fix #2058
Add the make_versioning_page to the psd_estimation, sbank and uberbank workflows
Will run the appropriate workflows next, just getting this PR in first

Versioning page in workflows

---

bin/pygrb/pycbc_make_offline_grb_workflow
pycbc/workflow/grb_utils.py
pycbc/workflow/segment.py

This is a: new feature for consistency with injections times within PyGRB.
This change affects: PyGRB.
This change changes: the workflow generator to avoid "wasting" injections.
This change: was tested in a full PyGRB workflow run.
When setting up the coherent search, the user must specify a max-duration and a min-duration of the search and provides a trigger time (and a time window for the possible search which generally extends for max-duration seconds before and after the trigger time).  The workflow generator then determines how to place the analysis time around the trigger time to maximise the coincident time with the detectors in the network specified by the user.  It is only at this point that it becomes clear when in time the injections can be allowed to happen: if a prior for the …

PyGRB now establishes the tc prior for injections at workflow time

---

bin/pygrb/pycbc_pygrb_grb_info_table
bin/pygrb/pycbc_pygrb_page_tables
pycbc/workflow/matched_filter.py

This PR simply uses radians for right ascension and declination throughout PyGRB.  Displaying them in degrees in the summary table on the results webpage is preserved.  This cleanup fixes the single IFO vs coherent IFO diagnostic plots.
This change changes: result presentation / plotting
The injections in plots such as
with 2 IFOs or
with 3 IFOs look wrong, but otherwise the behaviour of injections looks good.  The PR ensures that R.A. and declination are handled consistently throughout the workflow, so that the resulting plots are now correspondingly
and
The updated plots were produced rerunning the entire workflow from injection production onwards (injection filtering, post-processing).

Handle RA and dec in radians in pygrb

---

bin/all_sky_search/pycbc_sngls_findtrigs
bin/all_sky_search/pycbc_sngls_statmap
pycbc/events/significance.py

This change adds decimation into the `pycbc_sngls_findtrigs` code
This is a new feature/efficiency change
This changes result presentation / plotting, and has slight effects on scientific output (these should be negligible)
This change follows style guidelines and has been proposed using the contribution guidelines
We saw that the sngls_statmap job was using a lot of memory - part of this was as the sngls_findtrigs jobs were saving _everything_, even when the events had no chance of being real, or included in the significance fitting.
Events are decimated below certain thresholds in the sngls_findtrigs code. This is done by using successive factors and statistic thresholds, and only keeping events with statistic below the threshold if the …

Add decimation to sngls_findtrigs

---

bin/minifollowups/pycbc_injection_minifollowup

pycbc_injection_minifollowup has already been fixed on master to cut according to end time and use a premask for SingleDetTriggers, but not on the v23 release branch - this implements those changes here
This isnt such a problem with small(er) injection files, but can be with larger ones, which is why we have only just seen the issue
This is an efficiency update
See efficiency testing below
Use HFile.select() function to efficiently cut down the triggers in the injection minifollowup
Kind of the opposite of #4761 !
Efficiency tested by using `time …

V23 RELEASE BRANCH: Efficiency savings in pycbc_injection_minifollowup

---

bin/live/pycbc_live_plot_combined_single_significance_fits

Add a log-counts option to the pycbc live significance fits plotting.
Plots [with](https://ldas-jobs.ligo.caltech.edu/~gareth.cabourndavies/testoutput/various_tests/live_plot_combined_ylog/H1-TRIGGER-FITS-counts_NEW.png) and [without](https://ldas-jobs.ligo.caltech.edu/~gareth.cabourndavies/testoutput/various_tests/live_plot_combined_ylog/H1-TRIGGER-FITS-counts_OLD.png) the flag
This change affects the live search
This change changes result presentation / plotting

Add log counts option to live combined significance plot

---

bin/all_sky_search/pycbc_sngls_statmap
bin/plotting/pycbc_page_ifar
bin/plotting/pycbc_page_sensitivity
bin/plotting/pycbc_page_snrifar
bin/plotting/pycbc_page_snrratehist
bin/pycbc_live
bin/pycbc_upload_xml_to_gracedb
pycbc/events/coinc.py
pycbc/events/significance.py
pycbc/io/hdf.py
pycbc/population/live_pastro.py
test/test_significance_module.py

Use the pycbc conversions sec_to_year function throughout so that there is a single source of truth for the conversion of seconds and years, and we dont call into lal for YRJUL_SI so much
Solve #2885
Whenever the previous constant was being used, use the conversion function instead

Use pycbc conversions as single source of truth for converting seconds and years

---

companion.txt

With #4243, we had to fork awkde to fix a bug preventing its usage on Python 3.11. The fix has now been merged in awkde's master branch, so we can now drop my fork.
This is a minor simplification of PyCBC's dependencies, with no functional changes.
I prefer to avoid PyCBC depending on my forks of other people's repositories.

Go back to getting awkde from the original developer

---

bin/bank/pycbc_brute_bank
pycbc/pool.py

This is a: efficiency update
This change affects: the pycbc_brute_bank
This change changes: this only add a multiprocessing feature to the existing pycbc_brute_bank and wouldn't change any other exisiting results
This change would simply follow the unit tests designed for pycbc_brute_bank (if there is any)
This change will not break current functionality, not require additional dependencies, not require a new release
When a waveform generation is slow, the bottleneck for pycbc_brute_bank is the waveform generation speed. So I parallelize the waveform generation. This PR doesn't affect any match computation.
I added a parallelization for waveform generation in pycbc_brute_bank
None
Tested with "--num_cores = 96" and it works fine.
ACKNOWLEGMENT: with significant techinical support from …

add multiprocessing to pycbc_brute_bank

---

bin/live/pycbc_live_collate_triggers

This script is used to convert a large number of PyCBC Live trigger output files to a hdf trigger merge file.
This change affects: the live search
Using template fits in the PyCBC Live search (#4527) requires template fits to be made separate to using them. One of the requirements to make these files is a hdf trigger merge. This code produces that trigger merge file.
The PyCBC Live search outputs a trigger file every stride (8s for Live, 1s for Early Warning) containing any triggers found within the previous stride. This code takes a number of options to be given these trigger files and will then collate them into a single hdf object: from a list of trigger files, from a directory containing subdirectories containing trigger …

Script to create hdf trigger merge files from PyCBC Live output trigger files

---

bin/bank/pycbc_brute_bank
pycbc/pool.py

https://github.com/gwastro/pycbc/pull/4803 has a memory leakage bug because, as far as I understand, `atexit` makes a reference to the multiprocessing pool so it doesn't completely terminate after each call. This PR add a method to close the pool and remove the reference. I did a test with what failed before, the memory leakage doesn't occur again.

fix a memory leakage bug in pycbc_brute_bank

---

bin/pygrb/pycbc_grb_trig_cluster

This PR enables taking into account short timeslides when clustering triggers in PyGRB.  Prior to this, the clustering does not fail but it ignores what slide triggers belong to.
This is a: bug fix (in the sense that the code could run doing things incorrectly, but we were aware this enhancement had to be done and it was not a surprise).
A loop over timeslides was added, ensuring that triggers from different slides are kept separate.
The plotting scripts also need to plot information from a single slide (typically the zero-lag, i.e., unslid data): this is handled by https://github.com/gwastro/pycbc/pull/4809.
The number of slides performed, ensuring independent background events, was set in …

PyGRB trigger clustering with short timeslides

---

examples/search/analysis.ini

Minor bug in CI analysis.ini. This isnt a problem for the codes to run, more if someone is copying the config for their own use

Use singles FAR calculation properly in the example search

---

bin/pycbc_live
pycbc/events/coinc.py
pycbc/events/single.py
pycbc/events/stat.py
test/test_live_coinc_compare.py

Statistic files will be changed by a supervisor script in live for future uses. This PR adds the ability to check the sha1 hashes of the file and compare it to a stored copy so that if the file has changed, it can be reloaded.
In this usage, the file in the command line arguments would be overwritten (or a symlink which is updated), and then the statistic would refresh at an appropriate rate.
This change affects the live search; Offline code is touched but not affected
We want to be able to use a proper ranking statistic in …

Add mechanism for re-loading the statistic files in live

---

pycbc/types/timeseries.py

In a previous update scipy removed interp2d. Per the guide, we moved to rectbivariatespline, however, this meant that the default changed from linear to cubic interpolation. This isn't ideal for qtransform plots due to the fact that it results in negative values. These show up as "snow" when plotting the amplitude in results pages for example. e.g. 
This was repoted by @yi-fan-wang and others.

qtransform interpolation should be linear to avoid negative values

---

.github/workflows/basic-tests.yml

In #4716 python 3.8 was dropped, but I forgot to update the check on which python version actually servers to deploy the documentation. This changes it to use the latest (python3.12) documentation build instead.

don't forget to actually deploy the documentation

---

docs/_include/inference_example_lisa_smbhb_inj.sh
docs/_include/inference_example_lisa_smbhb_ldc.sh
docs/inference/examples/lisa_smbhb_inj_pe.rst
docs/inference/examples/lisa_smbhb_ldc_pe.rst
tox.ini

This is a: plugin update
This change affects: inference, LISA-related
This change changes: documentation, result presentation / plotting, scientific output
This change will: almost no changes
Supports the latest BBHx version.

support python3.12 now, so use bbhx master

---

pycbc/io/hdf.py

Add fletcher32 checksums by default to hdf5 datasets
This change affects everywhere that hdf5 file objects are used
This will check whether data has been corrupted in any way during 
Add a wrapper around the h5py Group object which does two things:
- Reimplements the `create_group` function so that it points to this wrapper
- adds the fletcher32 keyword to the `create_dataset` method
Add an inheritence to this wrapper to the HFile class, so that these are used in the file generally
#1525 - (I was sorting issues in order, oldest first)
Run fit_sngls_over_multiparam …

Add checksums to hdf5 datasets datasets

---

bin/pycbc_live

Allow debug logging in pycbc live. To get debug logging, we want args.verbose to use 'count', as in the 'common_options' interface.

Update pycbc_live to allow debug logging

---

bin/pycbc_live
pycbc/events/coinc.py
pycbc/events/single.py

#4816 leads to an error if `--statistic-refresh-rate` is not used. The error causes the refresh threads to crash, but this is not detected in the CI tests, which only check the final results.
This is mostly a bug fix but includes a few minor improvements and simplifications.
This change affects the live search.
The core of the error is this message (possibly mangled due to multithreading, sorry):
```
File "…/lib/python3.9/site-packages/pycbc/events/coinc.py", line 1427, in refresh_statistic
if since_stat_refresh > self.statistic_refresh_rate:
TypeError: '>' not supported between instances of 'float' and 'NoneType'
```
Adds a check for None, cleans up a few logging messages, improves an argparse help string, uses simpler timing functions.
Improves #4816.
Error discovered by staring at the …

PyCBC Live: fix errors from stat refresh code when not being used

---

pycbc/types/timeseries.py
test/test_timeseries.py

#4351 introduced a subtle bug which started affecting the SNR calculation in PyCBC Live's followup-detector code. The issue was never noticed because it triggered no failures in the Live example, and was never cherry-picked into the 2.1 release branch. We only started seeing it recently, when we started running our extensive MDC tests from the master branch. The bug crashes the code that serializes the p_astro results into a JSON string.
This is a bug fix which affects the online search and potentially other things (anything that uses `TimeSeries.at_time()`). This changes the scientific output (which previously could not exist) and should not require anything else.
We recently started testing the master branch on our extensive MDC, and immediately saw this error whenever an event was …

Fix subtle bug when using `LIGOTimeGPS` with `TimeSeries.at_time()`

---

bin/pycbc_live

Cleanup of `pycbc_live` to use more f-strings and apply some `black`-style formatting. No change in functionality expected.

Use more f-strings in `pycbc_live`

---

.github/workflows/distribution.yml
pycbc/inference/sampler/emcee_pt.py
pyproject.toml
requirements.txt
setup.py

Tests are failing, e.g. #4824.
This is an attempt to get the test running again.
That can't just be cherry-picked onto the branch due to conflicts

Try to copy #4789 for v23_release_branch

---

bin/minifollowups/pycbc_page_coincinfo
bin/minifollowups/pycbc_page_injinfo
bin/minifollowups/pycbc_page_snglinfo
examples/search/plotting.ini
pycbc/results/dq.py
pycbc/results/static/css/pycbc/orange.css
pycbc/results/table_utils.py

Added a few features to the minifollowup (coincinfo, snglinfo, injinfo) tables:
- Added chi_eff and chi_p to injinfo
- Allowing the user to specify a maximum number of columns in the table (as these are starting to get long!), and therefore adding row names
- Using proper sngl_ranking in the pycbc_page_coincinfo table
- Silencing some warnings in snglinfo regarding using single-entry arrays instead of floats
This is an enhancement to an existing feature
This change affects the offline search minifollowups.
Some of the functionality is used in inference, but the use-cases there are unaffected
This change changes result presentation
This change follows style guidelines (See e.g. [PEP8](https://peps.python.org/pep-0008/)), has been proposed using the [contribution …

Various improvements to minifollowup tables

---

bin/live/pycbc_live_supervise_collated_trigger_fits
bin/plotting/pycbc_plot_bank_corner
pycbc/results/scatter_histograms.py

Improvements are needed for the fits plotting.
This allows log ranges to be used for all parameters including the colorbar parameter, and also adds the IFO to the title of the plot when it is called by the live supervisor
This change affects: plotting from the live search
Before these changes, we would have to use log(param) in the --parameters argument. This leads to unwieldy labels and non-intuitive axis tick values
- Add two options to pycbc_plot_bank_corner for log parameters and log-colormap
- check that the log-parameters are sensible
- Modify the logic for …

pycbc_plot_bank_corner improvements for live

---

pycbc/types/config.py

This is a: bug fix,
This change affects: config file, inference
This change changes: nothing
This change will: Nothing
Replace deprecated ConfigParser `readfp` with `read_file`:
https://github.com/python/cpython/pull/92503
https://issues.apache.org/jira/browse/SVN-4899
Replace deprecated ConfigParser `readfp` with `read_file` in `__deepcopy__`.
https://github.com/gwastro/pycbc/pull/4688

remove readfp (Python 3.12 removes it), use read_file instead

---

pycbc/__init__.py

When `pycbc` is used with some multiprocessing package such as `dask`, importing `pycbc` will set the multiprocessing context repeatedly. The `RuntimeError: context has already been set` will occur. This fix will check the context before setting it, to make sure it will only be set once.
```
File "/Users/yumengxu/miniforge3/envs/pycbc_context_error/lib/python3.11/site-packages/pycbc/__init__.py", line 174, in <module>
multiprocessing.set_start_method('fork')
File "/Users/yumengxu/miniforge3/envs/pycbc_context_error/lib/python3.11/multiprocessing/context.py", line 247, in set_start_method
raise RuntimeError('context has already been set')
RuntimeError: context has already been set
```
OS: MacOS 14.2.1
Create a temporary env
```bash
conda create -n pycbc_context_error pycbc prefect 
conda …
```

Add check before setting multiprocessing context to prevent the RuntimeError

---

tox.ini

Fixes a recent CI failure noted by @maxtrevor in #4850.
This is (kind of) a bug fix. This change affects mostly the Tox tests.
Running `pytest` under Tox requires to install BBHx, which needs to link against LAPACK when building its wheel. LAPACK is typically installed via Conda (specified in `tox.ini`) and its shared libraries end up in the temporary Conda env created by Tox.
For some reason which I have not figured out, this used to work fine until a few days ago, when the linker started not being able to find `liblapacke` anymore. As far as I can see, nothing is explicitly telling the linker where to look for the LAPACK shared libraries, so I am not sure how it could work before 🤷.
So this PR explicitly tells the linker to look for shared libraries inside the Conda env, by setting …

Make sure BBHx knows how to link locally-installed LAPACK

---

pycbc/conversions.py

This pull request adds 3 new function. 
1. The first function returns the delta_lambda_tilde parameter given in this paper https://journals.aps.org/prd/pdf/10.1103/PhysRevD.91.043002 as equation 15. 
2. The second and third functions are conversions for lambda1 and lambda2 parameter by using delta_lambda_tilde and lambda_tilde functions.

Adding delta_lambda_tilde and conversions

---

pycbc/waveform/.ipynb_checkpoints/Untitled-checkpoint.ipynb
pycbc/waveform/generator.py

Correction to the "generate" function of FDomainDetFrameTwoPolNoRespGenerator - possible correction is to replace "apply_fd_time_shift" by "apply_fseries_time_shift" in the generate function of FDomainDetFrameTwoPolNoRespGenerator. 
Marginalized_time model uses FDomainDetFrameTwoPolNoRespGenerator to generate the waveform. The "generate" function of FDomainDetFrameTwoPolNoRespGenerator uses "apply_fd_time_shift" for the time domain approximant to shift it by an amount tshift(1/df - abs(hp.epoch)). The goal of this step is to shift the merger at the boundary. But if we follow the source code of "apply_fd_time_shift" then it will be clear that it will shift the waveform by (shifttime - hp.epoch) amount.
Here shiftime = tshift and hp.epoch is negative, so (shifttime - hp.epoch) = (tshift - …

changed_apply_fd_time_shift_to_apply_fseries_time_shift_in_FDomainDetFrameTwoPolNoRespGenerator

---

bin/pygrb/pycbc_pygrb_page_tables

This change clearly separates the usage of injections, onsource, and offsource as input for `pycbc_pygrb_page_tables`.  The user may specify only one of these inputs.  This ensures that these specific onsource and offsource results are kept separate in the workflow and the onsource tables do not end in the closed box as additional files.
This is a: clean up of a post-processing code, but also a bug fix for the pygrb tables because it prevents onsource results from appearing in the closed box.
<!--- What codes will this affect? (delete as apropriate)
This change changes: result presentation
Before the change, the onsource loudest event was in the [closed box](https://ldas-jobs.ligo.caltech.edu/~francesco.pannarale/LVC/pygrb_jun2024_1/4._loudest_offsource_events/) …

Input file handling in pycbc_pygrb_page_tables

---

bin/pycbc_multi_inspiral
pycbc/tmpltbank/sky_grid.py

Calculating the coherent network SNR (`pycbc_multi_inspiral`) requires a grid of points in the sky. This adds a module and class to manage such grids in a more centralized way.
This is mostly refactoring existing code into a new module. This change affects PyGRB but does not change any output.
`pycbc_multi_inspiral` is a very long script at this point, and `pycbc_make_sky_grid` might also become very long as we implement various algorithms for placing sky grids available in the literature. Centralizing the management of sky grids, including reading/writing them from/to files, seems beneficial.
I added a pycbc.tmpltbank.sky_grid module which currently contains a `SkyGrid` class, with methods to read and write sky grids from HDF5 files, calculate the antenna patterns and time delays over …

Add a module and class for handling sky grids for `pycbc_multi_inspiral`

---

companion.txt

This reverts a temporary measure added in #4863 due to CI tests failing because of PyPMC. With #4863 we started depending on a custom branch of PyPMC to work around an error, and I think the underlying issue has now been addressed in PyPMC.
Fixes #4861.

Revert temporary dependence on PyPMC fork

---

.github/workflows/basic-tests.yml
.github/workflows/build_venv.yml
.github/workflows/distribution.yml
.github/workflows/docker-build.yml
.github/workflows/inference-workflow.yml
.github/workflows/mac-test.yml
.github/workflows/search-workflow.yml
.github/workflows/tmpltbank-workflow.yml
.github/workflows/tut-test.yml
.github/workflows/workflow-tests.yml

As stated in #4865, a github workflow tool seems to have a security risk. dependabot doesn't seem capable of rebasing itself, so I open a new PR here with the same change.

Update GitHub actions to use modern versions

---

pycbc/psd/read.py

This is a reopened version of an accidentally closed pull request.
I am working with the strain sensitivity curves for Cosmic Explorer, which are available [here](https://dcc.cosmicexplorer.org/CE-T2000017/public). When I read the data files using the pycbc.psd.read.from_txt function with df=0.1, low_freq_cutoff=5.1, and length=4000, I observed that the resulting curves appear flat, as shown in the attached plot.
After examining the issue, I found that this issue does not occur with different values for low_freq_cutoff. The problem arises due to floating point arithmetic. Specifically, the value of low_freq_cutoff is 5.1 and delta_f is 0.1, so kmin should ideally be 51. However, in Python, the calculation 5.1 / 0.1 yields 50.99999999999999, and since the code uses the int function, kmin …

psd read changes

---

pycbc/io/hdf.py

Creating a dataset in HFile using a numpy scalar would pass this check as it has a dtype attribute, which isn't what we need here
This change changes nothing
This change has been proposed using the [contribution guidelines](https://github.com/gwastro/pycbc/blob/master/CONTRIBUTING.md)
Bug fix
This was causing problems in #4866
None

Fix numpy scalar edge case bug

---

bin/live/pycbc_live_supervise_collated_trigger_fits

We discovered a bug where if an ifo had no data for an entire day, it would cause an error in the daily supervised fitting. This fixes that bug.
This affects only the PyCBC Live search, not offline.

Bugfix for live fits

---

bin/pycbc_source_probability_offline

Fix a from_cli bug and remove mass gap related options and code, as mass gap classification does not need to be supported for offline calculation
This change affects: the offline search
This change changes: ability to produce a scientific result vs no result
This change: follows style guidelines (See e.g. [PEP8](https://peps.python.org/pep-0008/))
Bug fix
Offline source probability code fails to run as it was not updated for a module change
Try to make it run
To be tested by local install and attempting to run offline source probability
The author of this pull request confirms they will adhere to the [code of conduct](https://github.com/gwastro/pycbc/blob/master/CODE_OF_CONDUCT.md)

Update offline source probability for change to mchirp area

---

pycbc/workflow/grb_utils.py

Small cleanup of `setup_pygrb_minifollowups`
This change will: remove an unused variable (`trig_time`) and make the trigger file (`trigger_file`) a mandatory argument of `setup_pygrb_minifollowups`. 
This is the first PR to breakdown the workflow changes that produce a [PyGRB results page](https://ldas-jobs.ligo.caltech.edu/~francesco.pannarale/LVC/pygrb_aug2024_4/) with injections, exclusion distances, open box, followups of missed injections, offsource and onsource triggers, timeslides, etc.
See link above to the most recent results webpage.

setup_pygrb_minifollowups cleaner

---

pycbc/workflow/grb_utils.py

This is the second of the PRs promised in https://github.com/gwastro/pycbc/pull/4872.
It brings the PyGRB workflow utilities up to date with the output produced `pycbc_pygrb_efficiency`.  Specifically, this script now generates a json file with exclusion distances, which the (post processing) workflow generator needs to catch and handle appropriately.  The json file is intended to be used by the executable introduce in https://github.com/gwastro/pycbc/pull/4756 to display exclusion distances in a table.
This change changes: presentation of scientific output
This change will come to full circle with another PR to invoke and display the generation of the exclusion distances table.
This is the 2nd PR of a series opened by https://github.com/gwastro/pycbc/pull/4872 …

Enable handling of all pycbc_pygrb_efficiency in workflow

---

bin/pygrb/pycbc_pygrb_pp_workflow
pycbc/workflow/grb_utils.py

This PR expands the scope of `make_info_table` so it can add jobs to the workflow for `pygrb_exclusion_dist_table` as well as `pygrb_grb_info_table`.
This is a: a new feature for PyGRB workflow generation.
This change allows to expand presentation of scientific output in PyGRB webpages
This change is the 3rd PR of a series started with https://github.com/gwastro/pycbc/pull/4872.
As for the previous two PRs an example of a complete webpage is [here](https://ldas-jobs.ligo.caltech.edu/~francesco.pannarale/LVC/pygrb_aug2024_4/), but the full webpage will be reproducible only once all workflow changes are on master.

Function to setup pygrb_grb_info_table jobs

---

pycbc/workflow/grb_utils.py

This PR improves how jobs are added to the PyGRB workflow to create tables with "quiet-found" and "missed-found injections".  The function is (hopefully) cleaner and it handles its inputs more appropriately.
This is an improvement of an existing feature.
This change changes: result presentation
This change is the 4th PR of a series started with https://github.com/gwastro/pycbc/pull/4872.  It should be the last one for `grb_utils.py`.
As for the previous 3 PRs, a complete webpage example is available [here](https://ldas-jobs.ligo.caltech.edu/~francesco.pannarale/LVC/pygrb_aug2024_4/), but the full webpage will be reproducible only once all workflow changes are on master.

Improved pygrb missed/quiet injection tables job handler

---

bin/pycbc_multi_inspiral
pycbc/workflow/grb_utils.py

This PR follows up on comments received in, e.g., https://github.com/gwastro/pycbc/pull/4877.
It simply removes the other calls to `resolve_url_to_file` in `grb_utils.py` and some remaining commented lines of code.  It also fixes a typo in a comment in `pycbc_multi_inspiral`.
It was tested in producing [this webpage](https://ldas-jobs.ligo.caltech.edu/~francesco.pannarale/LVC/pygrb_sep2024_1/).

Further grb utils cleanup

---

bin/pygrb/pycbc_pygrb_efficiency

Fix bug introduce in PR #4812.
The previous PR for `pygrb_efficiency` soften a check by using `nansum(...)`.  However, in 2 out of 3 places `not nansum(...)` was used.
This change changes: plotting and scientific output (exclusion distances)
This change was tested in https://ldas-jobs.ligo.caltech.edu/~francesco.pannarale/LVC/pygrb_sep2024_2/5._exclusion_distances.

Fix nansum check in pygrb_efficiency

---

bin/pygrb/pycbc_pygrb_plot_skygrid

This is an aesthetic change to the PyGRB sky grid plot.
This change changes: result plotting
This change will: make sure that the sky grid plot is not trimmed, show grid lines on the plot, and provide it with a caption.
https://github.com/gwastro/pycbc/issues/4784.
https://ldas-jobs.ligo.caltech.edu/~francesco.pannarale/LVC/pygrb_sep2024_2/

Fix pygrb skygrid plot

---

bin/pygrb/pycbc_pygrb_page_tables

Fix bug when checking user choices for input files.
This change changes: result presentation
The `--offsource-file` option was set to `required=True` (as it should be), but then only one out of `--offsource-file`, `--onsource-file` and `--found-missed-file` was allowed to be passed, so the user could not process the onsource or the found/missed injections.
The test is now ensuring that `--onsource-file` and `--found-missed-file` are not simultaneously given by the user.
The change was tried in a full (re)post-post processing of [this box](https://ldas-jobs.ligo.caltech.edu/~francesco.pannarale/LVC/pygrb_aug2024_4/) giving [this new webpage](https://ldas-jobs.ligo.caltech.edu/~francesco.pannarale/LVC/pygrb_sep2024_1/).

Fixing bug in input files check

---

bin/all_sky_search/pycbc_calculate_psd
bin/inference/pycbc_inference_plot_movie
bin/pycbc_inspiral
bin/pycbc_optimal_snr
pycbc/__init__.py
pycbc/inference/models/brute_marg.py
pycbc/pool.py

This change affects library useage of pycbc within a setting where the multiprocessing start context is already set. We currently *force* a setting of "fork" which doesn't work in some cases and may not be what someone wants for all uses. 
Any executable and library code which relies on multiprocessing. In these cases, the correction recommended by @xkzl is used. 
This change will ideally have no effect on current usage. 
Error reported in https://github.com/gwastro/pycbc/issues/4853

Don't force global multiprocessing start method

---

examples/make_skymap/simulated_data.sh

This modifies one of the examples of `pycbc_make_skymap` to make it clear that random seeds for fake noise must be set explicitly.
This is a documentation enhancement.
This change affects one of the examples of `pycbc_make_skymap`.
When simulating noise on multiple detectors via `--fake-strain`, it is important to set different random seeds in different detectors, otherwise you will get the same noise realization in all detectors, which is usually *not* how you want to simulate noise!
The example of `pycbc_make_skymap` that uses simulated noise was not setting the seed explicitly, therefore implicitly using the same seed for all detectors. The resulting skymap *looks* correct visually, but this can lead to weird results when doing large simulations and checking the results statistically. …

Set random seeds for fake noise in make_skymap example

---

bin/pygrb/pycbc_pygrb_efficiency

This PR allows the user to choose which output files (if any) `pygrb_efficiency` must produce.
This is adds flexibility to an existing post-processing script.
This change changes: the ability to specifiy what plots and tables `pygrb_efficiency` must create.
There is no need for post-processing scripts to produce all the output they can possibly produce.  The user may or may not need all outputs when calling a script.
`pygrb_efficiency` can produce three outputs so the lines to produce them are now encapsulated in three `if`s.
Additionally, the code makes sure that all input files necessary to produce the requested output files are passed.
All plots in sections 5 and 6.02 of [this webpage](https://ldas-jobs.ligo.caltech.edu/~francesco.pannarale/LVC/pygrb_sep2024_2 …

Do not force pygrb_efficiency to produce all output: let the user decide

---

.github/workflows/basic-tests.yml
.github/workflows/build_venv.yml
.github/workflows/distribution.yml
.github/workflows/docker-build.yml
.github/workflows/inference-workflow.yml
.github/workflows/mac-test.yml
.github/workflows/search-workflow.yml
.github/workflows/tmpltbank-workflow.yml
.github/workflows/tut-test.yml
.github/workflows/workflow-tests.yml
bin/pycbc_source_probability_offline
companion.txt
setup.py

Adding some additional patches for the v238 branch.

Changes for v2.3.8

---

pycbc/detector.py
test/test_detector.py

* Adds in the ability to set the altitude angles for custom detectors
* Simplify detector class, use lal only for its detector location information rather than the response value itself. This makes it easier to provide consistent metadata between custom and lal-builtin detectors
* Simplify the add detector on the earth function (use matrix multiplication operator, make the rotations clearer / more obvious / start rotations from simpler form of the basic arm response)
Todo
* update unittest to include both  use of custom detector and crosscheck response matrix calculation against builtin lal value

add in altitude support and simplify adding detector function

---

bin/pygrb/pycbc_pygrb_pp_workflow

This PR is a continuation of the work started in https://github.com/gwastro/pycbc/pull/4891.
- The `labels_in_files_metadata` function introduced in the previous PR has an additional argument for the run directory path.
- All input files (found triggers, injections results, template bank) are converted to `File` instances.
- Some minor cleanup is carried out: the definition of the `out_dirs_dict` dictionary is moved and the repeated operation of determining the variable `inj_sets` is performed only once.
This brings master closer to producing a full results webpage as in [this example](https://ldas-jobs.ligo.caltech.edu/~francesco.pannarale/LVC/pygrb_sep2024_3/6._open_box/).
This change affects: PyGRB.
This change changes: result presentation / plotting.
As for the previous PR, the …

File instances for all PyGRB postprocessing input

---

docs/conf.py

The CI is failing again. Looking over the logs, Sphinx suggests that we just remove the line removed here (https://github.com/gwastro/pycbc/actions/runs/11219860463/job/31186751487?pr=4899).

Fix [hopefully] documentation failure

---

bin/pygrb/pycbc_pygrb_pp_workflow

This PR is the 4th PR in a series opened by https://github.com/gwastro/pycbc/pull/4891.
It allows PyGRB results webpages to display tables for
1. "quiet-found" and "missed-found" injections
2. the loudest off-source triggers
3. and the loudest on-source trigger.
It allows sets up and runs sub-workflows for the "minifollowups" of
1. the N loudest "quiet-found" injections
2. the M loudest off-source triggers
3. and the loudest on-source trigger.
Results of the minifollowups are gathered and displayed in the results webpage.
Finally, the PR also enables producing and displaying the reweighted and coherent SNR timeseries for the whole data set, onsource included, in the open box.
This is an additional feature for the webpage produced by a PyGRB analysis
This change …

Tables and minifollowups in PyGRB

---

bin/pygrb/pycbc_pygrb_pp_workflow
pycbc/workflow/grb_utils.py

This PR is the 5th PR in a series opened by https://github.com/gwastro/pycbc/pull/4891.
It allows PyGRB results webpages to display tables with exclusion distances and the search efficiency plots (for each injections set and based on the offsource trials and the onsource).  The onsource tables and plots are place in the open box section and not visible in the closed box.
This is an additional feature for the webpage produced by a PyGRB analysis.
This change changes: result presentation / plotting of scientific output.
This brings master closer to producing a full results webpage as in [this example](https://ldas-jobs.ligo.caltech.edu/~francesco.pannarale/LVC/pygrb_sep2024_3/).
For each injection set, `pygrb_efficiency` is called to generate the "detection …

Efficiency plots and exclusion distance tables in PyGRB webpages

---

pycbc/waveform/plugin.py

This is a new feature added for estimating the end frequency of any custom waveform model
This feature will affect plugin.py for waveform 
This change changes: documentation, scientific output
This change will: break current functionality, require a new release
Custom waveform approximants may or may not have a frequency-domain version. To make any time-domain waveform useful for searches or parameter estimation, get_fd_waveform_from_td is used. For an accurate time-to-frequency …

Add an estimator for end frequency of the any custom waveform model  

---

bin/pygrb/pycbc_pygrb_efficiency
bin/pygrb/pycbc_pygrb_results_workflow

- Require one `pygrb_efficiency` subsection in the config file for each injection set, i.e. `[injections]` subsection.
- Insert a line that was accidentally removed
- Lower the high end limit of the x axis in `pygrb_efficiency` plots.
This is a: bug fix.  Prior to this fix, `pygrb_efficiency` was using a single value of lower/upper distance values, regardless of the injection set.
This change changes: result presentation plotting and scientific output
This change was tested by rerunning the results generation of a GRB analysis [here](https://ldas-jobs.ligo.caltech.edu/~francesco.pannarale/LVC/pygrb_oct2024_1/5._exclusion_distances/).  Note that the [previous version](https://ldas-jobs.ligo.caltech.edu/~francesco.pannarale/LVC/pygrb_sep2024_3/5._exclusion_distance …

Enforce pygrb_efficiency subsections

---

examples/live/check_results.py
pycbc/io/gracedb.py

This fixes #4912.
I explictly convert the PSD to double precision before the division, as soon numpy 2.x is not doing it automatically anymore. 
I also add another check of the XML files to make sure that the PSDs in there are valid.

Fix problem on pycbc live due to numpy 2 

---

bin/all_sky_search/pycbc_coinc_statmap

Prasia found a bug in pycbc_coinc_statmap if no foreground events have been found,
this fixes that
This change affects: the offline search
This change changes: nothing
This change: has been proposed using the [contribution guidelines](https://github.com/gwastro/pycbc/blob/master/CONTRIBUTING.md)
Fix bug for a legitimate use-case in the offline search
A variable was being used later in the code which was only set in the case that there was some foreground
This sets the variable and ensures that it is usable later
https://github.com/gwastro/pycbc/issues/4907
To be tested with downstream codes

Make coinc_statmap work in the case that no foreground is present

---

pycbc/workflow/grb_utils.py

We do not need this line of code anymore since `--num-trials` is now passed via config files
This change will: fix `pycbc_make_offline_grb_workflow` which is presently showing the following error:
```
File "/home/sebastian.gomezlopez/.conda/envs/pygrb_prod/bin/pycbc_make_offline_grb_workflow", line 442, in <module>
_workflow.setup_pygrb_pp_workflow(wflow, pp_dir, seg_dir,
File "/home/sebastian.gomezlopez/.conda/envs/pygrb_prod/lib/python3.9/site-packages/pycbc/workflow/grb_utils …
```

Removing old line preventing PyGRB workflows from starting

---

.github/workflows/distribution.yml
.github/workflows/mac-test.yml
pycbc/events/triggers.py

The injection param fetching has an obvious bug in a branch which I am guessing has never been used .. see the change
This change affects: plotting utility code currently not used in offline search
This change changes: result presentation / plotting
This change will: not have any effect other than improving ability to retrieve injection params
Works to retrieve the `injections/tc` dataset.

Fix bug in fetching injection group param

---

pycbc/detector.py

This change affects the function: `pycbc.detector.get_available_detectors()`
This change changes: output of the above function
This change will likely not affect any other functions
The output of `get_available_detectors()` was a list of LAL detectors repeated twice in addition to the detectors added by the user. This was happening because of the addition of LAL detectors once in lines 193-207 as follows in `pycbc/detector.py` file
```
for pref, name in get_available_lal_detectors():
lalsim = pycbc.libutils.import_optional('lalsimulation')
lal_det = lalsim.DetectorPrefixToLALDetector(pref).frDetector
add_detector_on_earth(pref,
lal_det.vertexLongitudeRadians,
lal_det.vertexLatitudeRadians,
height=lal_det.vertexElevation,
xangle=lal_det.xArmAzimuthRadians, …
```

editing get_available_detectors() to avoid repetition

---

bin/pycbc_multi_inspiral
bin/pygrb/pycbc_make_offline_grb_workflow
bin/pygrb/pycbc_pygrb_minifollowups
pycbc/results/pygrb_postprocessing_utils.py
pycbc/workflow/grb_utils.py
pycbc/workflow/jobsetup.py

This is the first PR of a series that will enable PyGRB to handle an xml veto file when producing final results (plots, p-values, tables, etc.)
This is a: a new feature in PyGRB.  As an aside, some utilities and scripts will be streamlined.
This change will probably break current functionalities at the moment.  If the standard automated test running `--help` on all scripts fails on PyGRB plotting scripts, I will add some workarounds to avoid this.  If needed, these will likely be empty functions: the plotting scripts will be progressively renovated in PRs following this one.
PyGRB in its current version is not using data vetoes.
- PyGRB used to handle veto definer files "collating" CAT1, …

Preparing for veto file handling in PyGRB

---

pycbc/events/simd_threshold_ccode.cpp
test/test_threshold.py

Fix incorrect results from the OpenMP threshold code on Intel Macs. Fixes #4828.
This is a bug fix which should not change any result (apart from fixing the buggy situations).
See the explanation in #4828 for details, but the essence is that the thresholding code was broken on Intel Macs when using OpenMP.
The problematic code is moved inside an ordered OpenMP directive.
I also did some cleanup of `test_threshold.py`.
#4828
Testing done on an Intel Mac using the `test_threshold.py` unit test.
N/A

Fix OpenMP threshold code on Intel Macs

---

bin/inference/pycbc_inference_extract_samples

`pycbc_inference_extract_samples` is supposed to be able to combine files. However, this functionality is currently broken because it tries to enforce that the `run_start_time` and `run_end_time` that is stored in the input files be the same. This patch fixes that by adding `run_start_time` and `run_end_time` to the list of file attrs that are ignored when combining files.

Fix issue preventing extract samples from combining files

---

bin/pygrb/pycbc_pygrb_plot_skygrid
bin/pygrb/pycbc_pygrb_results_workflow
pycbc/results/pygrb_postprocessing_utils.py
pycbc/workflow/jobsetup.py

This PR is the second in the series started in PR #4929.
If this change breaks the standard automated test running `--help` for PyGRB plotting scripts, I will add some workarounds to avoid this.  If needed, these will likely be empty functions: the plotting scripts will be progressively renovated in the whole series of PRs.
Prior to these PRs, PyGRB was not using data vetoes.
- The results workflow generator for PyGRB is now passing segments files and the vdf to all results scripts
- The utility functions involved in loading …

Passing vetoes to scripts in pygrb results sub workflow

---

bin/pycbc_make_skymap

Fixes a crash in `pycbc_make_skymap` triggered by using simulated strain and a detector that is not H1, L1 or V1.
This is a bug fix which affects only `pycbc_make_skymap`.
A student reported that adding KAGRA to our example produces this error:
```
File "/home/tito/virtualenvs/pycbc/bin/pycbc_make_skymap", line 574, in <module>
main(opt.trig_time, opt.mass1, opt.mass2,
File "/home/tito/virtualenvs/pycbc/bin/pycbc_make_skymap", line 111, in main
frame_types[ifo] = default_frame_type(mean_trig_time, ifo)
File "/home/tito/virtualenvs/pycbc/bin/pycbc_make_skymap", line 56, in default_frame_type
raise ValueError('Detector {} not supported at time {}'.format(ifo, time))
ValueError: Detector K1 not supported at time 1272790260.0
```
The logic that determines …

Fix logic for determining frame type in `pycbc_make_skymap`

---

pycbc/results/scatter_histograms.py

This is a bugfix to the `create_multidim_plot` function in `scatter_histograms.py`. Specifying `--plot-maxl` does not plot the expected maximum likelihood point when used in conjunction with `--plot-scatter` in multidimensional plots. Currently, `plot-maxl` selects the index of the max likelihood sample before `plot-scatter` sorts the samples by their z argument. When both options are specified, the selected maxL index will generally not correspond to the maxL sample in the newly sorted array.
This PR moves the indexing selection for `plot-maxl` after the samples are sorted by `plot-scatter`. This should have no effect if using either option separately with codes using `create_multidim_plot` (e.g. `pycbc_inference_plot_posterior`), but should now correctly plot the maxL sample if both are …

Fix bug when plotting maximum likelihood point in `create_multidim_plot`

---

bin/pygrb/pycbc_pygrb_minifollowups
bin/pygrb/pycbc_pygrb_page_tables
pycbc/results/pygrb_postprocessing_utils.py

This PR is the third in the series started in PR #4929.
If this change breaks the standard automated test running `--help` for PyGRB plotting scripts, I will add some workarounds to avoid this.  If needed, these will likely be empty functions: the plotting scripts will be progressively renovated in the whole series of PRs.
Now that the workflow generator passes around the veto definer file, the mini followups need to handle it use it.  In checking `pycbc_pygrb_minifollowups` I noticed that it is better to enforce the correct timesmlide is …

Handling vetoes and timeslides in pygrb mini followups

---

bin/pygrb/pycbc_pygrb_plot_null_stats
pycbc/results/pygrb_postprocessing_utils.py

This PR is the fourth in the series started in PR #4929.
Should this change break the standard automated test running `--help` for PyGRB plotting scripts, I will add some workarounds to avoid this.  If needed, these will likely be empty functions: the plotting scripts will be progressively renovated in the whole series of PRs.
Now that the workflow generator passes the veto definer file to the jobs where needed, its usage in the PyGRB results scripts is possible.
- Enable using veto and segments files in `pycbc_pygrb_plot_null_stats`.
- The …

Introducing syntax for vetoing injections in PyGRB and final version of `pycbc_pygrb_plot_null_stats`

---

.github/workflows/basic-tests.yml
.github/workflows/mac-test.yml
test/validation_code/old_coinc.py
tox.ini

This change affects: continuous integration
This change changes: continuous integration
This change will: n/a
Fixes #4939
This PR fixes #4939 by updating the CI/tox configuration for macOS.
Fixes #4939 
Closes #4944

Fix mac tests with conda

---

bin/bank/pycbc_brute_bank

This is a: new feature 
This change affects: pycbc_brute_bank script
Template bank generation using pycbc_brute_bank is computationally intensive for very long-duration signals, primarily due to the match calculations. The computation time can be reduced by generating frequency-domain signals at lower frequencies specifically for the match calculations.
N/A
N/A

Add a feature to generate frequency domain waveforms at reduced frequencies

---

bin/pygrb/pycbc_pygrb_plot_chisq_veto
bin/pygrb/pycbc_pygrb_plot_coh_ifosnr

This PR is the fifth in the series started in PR #4929.  Much like PR #4947 did with `pycbc_pygrb_plot_null_stats`, this PR provides a version of `pycbc_pygrb_plot_chisq_veto` and `pycbc_pygrb_plot_coh_ifosnr` that uses veto and segments files, as well as the utilities introduced recently to streamline the PyGRB results scripts.
Should this change break the standard automated test running `--help` for PyGRB plotting scripts, I will add some workarounds to avoid this.  If needed, these will likely be empty functions: the plotting scripts …

Final version of `pycbc_pygrb_plot_chisq_veto` and `pycbc_pygrb_plot_coh_ifosnr`

---

pycbc/events/single.py
pycbc/io/gracedb.py

Update the chisquared uploaded to gracedb to be reduced, and save the ranking statistic value
This change affects the live search
We noticed that the chisquared for singles was not the reduced chisquared - I tracked it down to where I'd missed that I was using the same trigger set for statistic calculation as I was for the upload, which is not what is done for coincs, this is now set back to the un-modified set of triggers.
We also realised that the ranking statistic isnt being saved - I have added this to the gracedb upload/xml …

Fix a couple of output/upload value issues in pycbc live

---

bin/pygrb/pycbc_pygrb_plot_snr_timeseries
pycbc/workflow/grb_utils.py

This PR is the sixth in the series started in PR #4929.  Much like PRs #4947 and #4950, this PR provides a version of `pycbc_pygrb_plot_snr_timeseries` that uses veto and segments files, as well as the utilities introduced recently to streamline the PyGRB results scripts.  Additionally, `pycbc_pygrb_plot_snr_timeseries` now has an option to activate plotting the onsource (by default the onsource is not shown) and this is handled in its dedicated workflow generator function.
Should this change break the standard automated test running …

Final version of `pycbc_pygrb_plot_snr_timeseries`

---

bin/pygrb/pycbc_pygrb_plot_stats_distribution

This PR is the seventh in the series started in PR #4929.  Much like PRs #4947, #4950, and #4955, this PR provides a version of `pycbc_pygrb_plot_stats_distributions` that uses veto and segments files, as well as the utilities introduced recently to streamline the PyGRB results scripts.
Should this change break the standard automated test running `--help` for PyGRB plotting scripts, I will add some workarounds to avoid this.  If needed, these will likely be empty functions: the plotting scripts will be progressively renovated in the whole …

Final version of pycbc_pygrb_plot_stats_distribution vetoes

---

bin/pycbc_multi_inspiral

This PR is refering to #4956 and is converting indexes of triggers of the `pycbc_multi_inspiral` script from `np.uint32` to `np.int32`.
I was trying to run some workflows with `PyGRB` with numpy 2.x and it gave me an `Overflow Error`. Apparently it's because of numpy version, they have change the promotion rules with python scalars (explained [here](https://numpy.org/neps/nep-0050-scalar-promotion.html#nep50)). WIth @titodalcanton, we decided to convert manually the indexes of triggers into `np.int32` to avoid this `Overflow Error`.  
It will make every script that use the `pycbc_multi_inspiral` script works if you are working with numpy 2.x. 
I change this line of the code in order to maintain the code working correctly with further version of numpy. 
I've also put the `time_delay_idx` …

Converting indexes of triggers into np.int32 because of numpy 2.x

---

bin/pygrb/pycbc_pygrb_plot_injs_results

This PR is the eighth in the series started in PR #4929.  Much like PRs #4947, #4950, #4955, and #4958, this PR provides a version of `pycbc_pygrb_plot_injs_results` that uses veto and segments files, as well as the utilities introduced recently to streamline the PyGRB results scripts.
Should this change break the standard automated test running `--help` for PyGRB plotting scripts, I will add some workarounds to avoid this.  If needed, these will likely be empty functions: the plotting scripts will be progressively renovated in the whole …

Final version of pycbc_pygrb_plot_injs_results

---

bin/pycbc_make_skymap

Current version of pycbc_make_skymap doesn't support usage of O4 strain. Generation of fake strain is also only available through `--fake-strain` using simulated ASDs stored within PyCBC and not external/custom ASD. 
- This change enables usage of local ASD files as input for fake strain generation
- This change allows reading O4 strain at CIT if one wants to generate injections on real-time data
I wanted to use `pycbc_make_skymap` to investigate impact of transient noise on GW sky localisation during O4b for Virgo, but this required the proposed changes to be made.
- Argument `--fake-strain-from-file` to compute fake strain based on custom ASD file as input, which is already available in `pycbc_single_template`
- Input file for ASD should be a two column file, line per line: FREQUENCY …

Adding --fake-strain-from-file and channel names/frame types for O4 data

---

bin/pycbc_multi_inspiral
bin/pygrb/pycbc_pygrb_grb_info_table
pycbc/types/optparse.py

This allows PyGRB users to do `--ra 12deg` or `--ra 2rad`, thus clearing confusion on the units and removing the need to convert from degrees to radians. It also improves the external trigger summary table in a couple ways.
This is a new feature and restyling of result presentation.
This change affects mainly PyGRB.
This is backwards compatible, but it will print a warning if `--ra` and `--dec` are used without units.
While doing some test PyGRB runs, @Thomas-JACQUOT and I ran into some confusion about which angular units we are supposed to use. `pycbc_multi_inspiral`, `pycbc_pygrb_grb_info_table` and the workflow config now consistently take radians as input args. However, results are typically presented in degrees. More importantly, radians are seldom used in the astro community, so the …

Allow units for `--ra` and `--dec`, improve external trigger info table

---

pycbc/types/config.py

This PR adds a check for repeated options in configuration files used for inference jobs. Previously, if an option was repeated across multiple configuration files, the latest instance would overwrite earlier ones without raising an error. Now, the code detects repeated options and raises an error.

Fixing overlaping sections bug

---

pycbc/results/table_utils.py

HTML tables in result web pages are broken with Numpy 2. This should fix it.
This is a bug fix.
This bug involves anything that makes HTML tables of data (this includes at least the all-sky offline search and PyGRB) but the fix not impact anything.
The problem is described in #4968, but to summarize, HTML tables show up empty under Numpy 2 because the data array in JavaScript ends up being filled with strings like `'np.float64(7.1)'` instead of proper numbers like `7.1`.
I added an explicit conversion of Numpy's float and integer types to Python native floats and ints respectively, before they are passed to the template that renders them into JavaScript values.
Fixes #4968.
I used the following code:
```python
import numpy as np
from pycbc.results import html_table
th = ['int', 'float', …
```

Fix HTML table display on Numpy 2

---

examples/live/make_singles_significance_fits.py
pycbc/events/single.py
pycbc/io/gracedb.py
setup.py

This commit increments the version number of the v27 release branch to v2.7.1.
It cherry-picks https://github.com/gwastro/pycbc/pull/4953 and https://github.com/gwastro/pycbc/pull/4971 to address bugs affecting the PyCBC Live search

V271 bugfixes

---

.github/workflows/distribution.yml
.github/workflows/mac-test.yml
setup.py

This cherry picks https://github.com/gwastro/pycbc/commit/f1606419b64d53bb12ab45c9bbef6f3611dbdfe8 onto the v2.7 release branch so that Mac OS wheels build

Cherry-pick Mac OS fix onto v2.7 branch

---

bin/pygrb/pycbc_pygrb_plot_injs_results

This PR fixes a bug in https://github.com/gwastro/pycbc/pull/4960 with a module path and it corrects the background.  PyGRB background is the collection of max reweighted SNRs, where maximisation is done over each trial.  The previous version was gathering all reweighted SNRs and not carrying out this maximisation.
It is the ninth PR in the series started in PR https://github.com/gwastro/pycbc/pull/4929.
This is a: 2 bug fixes.
This change changes: result presentation / plotting, scientific output

Corrected background and module path in pygrb_plot_injs_results

---

pyproject.toml

PyPI will begin enforcing PEP 625 which requires that source package names use lower case letters. Ensuring these requirements was implemented in setuptools but in a new enough version that not all our environments seem to have it by default. I've updated our pyproject.toml to ensure we have a recent enough version. 
This may need to be cherry picked into any branches that are making future releases also.

update setuptools build minimum

---

pycbc/distributions/__init__.py
pycbc/distributions/sky_location.py
test/test_distributions.py

Add a class HealpixSky to `pycbc/pycbc/distributions/sky_location.py` that allow one to sample the distribution given by a HEALPix sky map by using the rejection sampling method.
This change follows style guidelines (See e.g. [PEP8](https://peps.python.org/pep-0008/)) and includes running `black` to reformat `sky_location.py`.
This change adds a new feature to the distributions module, mainly for use in PyGRB.
Versions of PyGRB used for past analyses approximated the uncertainty in the GRB sky location with circular patches, or using "IPN boxes". In many cases, the uncertainties actually are not circular at all. This is typically the case for IPN localizations, which can resemble thin rings over large patches of the sky. Nowadays, most GRBs have their sky location uncertainties …

add a distribution to draw sky locations from a HEALPix map

---

bin/all_sky_search/pycbc_add_statmap
bin/all_sky_search/pycbc_coinc_statmap
bin/all_sky_search/pycbc_coinc_statmap_inj
bin/all_sky_search/pycbc_exclude_zerolag
bin/all_sky_search/pycbc_sngls_statmap
bin/all_sky_search/pycbc_sngls_statmap_inj
pycbc/events/significance.py
test/test_significance_module.py

The significance fits information gets discarded and there is not way to get it back - this change saves the fit coefficient, its approximate error and the rate of triggers above threshold as attributes in the statmap output files
This is an information loss bug fix
This change changes: output which can be used for later review / plotting
We want to be able to get the FAR calculation extrapolation values for review etc.
We can reverse-engineer fit coefficient and count above threshold using e.g. the FAR / stat values above the threshold, but not …

Save statmap significance fits information

---

bin/all_sky_search/pycbc_fit_sngls_over_multiparam

Add in a few efficiency savings for `pycbc_fit_sngls_over_multiparam`
This is an efficiency update
This change affects the offline search, the live search
This change changes nothing for the output
I was looking at `pycbc_fit_sngls_over_multiparam` thinking it would be a good place to learn / implement some GPU efficiency, but then we (mainly Ian) saw that there were some huge efficiency savings that could be made fairly quickly
Biggest saving: 
- Move one instance where an array is indexed to re-sort to outside of a loop
Additional savings: 
- Pre-allocate memory for a list where we …

Some efficiency savings for pycbc_fit_sngls_over_multiparam

---

pycbc/waveform/decompress_cpu.py
test/test_skymax.py

This is an attempt at fixing #4990.
I am assuming `compute_max_snr_over_sky_loc_stat()` wants the input arrays to be in single precision for speed/memory considerations.
In my local tests, this will still fail because the results differ from the expected values by 1e-6 or less, so we may have to update the reference values.

Try to fix test_skymax on Numpy 2

---

bin/pycbc_make_sky_grid

This allows the `deg` and `rad` suffixes to be used in `pycbc_make_sky_grid`.
This is a new feature.
This change affects mostly PyGRB at this time.
This change will not break functionality.
I forgot to do this in #4965. Fixes #4986.
Trivial change. I took the opportunity to also reformat the code in a separate commit.
#4965 and #4986.
None.
N/A

Allow RA/dec unit suffix in make_sky_grid

---

pycbc/distributions/sky_location.py

This PR aims to allow `FisherSky` class to have angle unit suffix rad deg
This is a new feature, which make the  `FisherSky` class able to deal with angle unit suffixes
This change will: change nothing in other parts of the code, it adds only a new feature for the `FisherSky` class.
@titodalcanton, @pannarale and I wanted to change the `[prior-ra+dec]` section of `GRBXXXX.ini` files in order to be more clear (see discussion [here](https://git.ligo.org/ligo-cbc/pycbc-config/-/merge_requests/414#note_1224603)). To do so, it needs to change the `FisherSky` class to make it able to deal with angle unit suffixes (just as @titodalcanton did [here](https://github.com/gwastro/pycbc/pull/4965))

Allowing the FisherSky class to have angle unit suffix rad deg

---

pycbc/distributions/sky_location.py

This PR is allowing 0 values for `sigma` in the `FisherSky` class. The `FisherSky` class follows a `numpy.random.rayleigh` distribution which allows 0 values for `sigma` (see this [comment](https://git.ligo.org/ligo-cbc/pycbc-config/-/merge_requests/414#note_1228331))
This change affects: PyGRB 
This change will: allow to use `FisherSky` distribution for GRBs that has a `sky_error` equals to 0.
I want to do this PR in order to use PyGRB with GRBs that has a `sky_error` equals to 0 and uses `FisherSky` class as a prior for the right ascension and the declination.

Making the check on sigma for FisherSky class more relax (allowing 0 value)

---

pycbc/inference/models/gated_gaussian_noise.py
pycbc/inference/models/gaussian_noise.py
pycbc/inference/models/marginalized_gaussian_noise.py
pycbc/inference/models/relbin.py
test/test_infmodel.py

The `Relative` model (and models that inherit from it) do not catch failed waveform errors like the GaussianNoise models do. This adds that functionality to those models.
To avoid repeating code, and to standardize catching these errors, I created a decorator `catch_waveform_error` that can be added to any method that will call a waveform generator. The decorator will catch any `NoWaveformError`, `FailedWaveformError`, and `RuntimeError`. It will then call the class's `_nowaveform_handler` method (for the latter two errors this will only happen if the class's `ignore_failed_waveforms` attribute is set to True). In order for this to work, I had to rename some of the class's `_nowaveform_loglr` and `_nowaveform_logl` to `_nowaveform_handler`.
All models that previously caught these errors …

Add waveform error handling to Relbin (and other models)

---

pycbc/workflow/core.py

The `Executable` constructor documentation is a bit out of date and this PR is intended to fix it.
This is simply a documentation change.

Improve Executable constructor doc

---

bin/pycbc_make_sky_grid
bin/pygrb/pycbc_make_offline_grb_workflow
pycbc/workflow/grb_utils.py
pycbc/workflow/jobsetup.py
pycbc/workflow/matched_filter.py

`pycbc_multi_inspiral` can loop over several search sky points and `pycbc_make_sky_grid` can generate such grid.  This PR sets up a job for the latter and passes the grid around to the former, within a PyGRB workflow.
The appropriate workflow .py files and the workflow generator are upgraded accordingly. 
https://github.com/gwastro/pycbc/pull/4988
Coming up...

Generate and use search sky-grids in pygrb worflows

---

pycbc/waveform/waveform_modes.py

Generalize time-domain waveform modes generation via `lalsimulation``
This change affects: No existing code, this is a new feature
This change changes: CBC waveform modes generation
There are many approximants implemented in `lalsimulation` that allow for generation of individual spherical harmonic modes of gravitational radiation. We want to interface them through the `waveform.get_td_waveform_modes` interface, which currently works for a small number of approximants.
* Added a function to generate waveform modes for many time-domain …

Generalize time-domain waveform modes generation via lalsim

---

bin/pygrb/pycbc_pygrb_page_tables

One line fix to correctly call the pycbc hdf file interface.

pygrb_page_tables fix

---

companion.txt
pycbc/distributions/sky_location.py

Followup of #4848 that implements a more efficient approach for HealpixSky.
This is an efficiency update.
This change affects the distributions module.
This change adds a dependency on mhealpy. I am open to discussion if others prefer not to make it an explicit dependency. Edit: the mhealpy dependency has been made optional as suggested below.
The initial implementation of HealpixSky worked well, but it had a couple drawbacks:
* It used rejection sampling, which is not always efficient (this depends on the actual morphology of the specific skymap).
* It required a couple extra parameters to make rejection sampling efficient, making its use a bit less easy than ideal.
The new algorithm works as follows. We first choose a random pixel of the skymap based on its contained probability. Then …

Make HealpixSky easier to use and more efficient

---

pycbc/pool.py

Pass keyword arguments passed to `choose_pool` to the pool constructor. This enables additional configuration of the pool.
This change affects:  `pycbc_bruke_bank`, inference. However, since `choose_pool` is never called with any keyword arguments, things are functionally the same.
This change changes: configuration
This change: has appropriate unit tests, follows style guidelines (See e.g. [PEP8](https://peps.python.org/pep-0008/))
This change is backwards compatible
This enables specifying e.g. `initalizer` and `initargs` when creating a pool. Both the default [`multiprocessing` library](https://docs.python.org/3/library/multiprocessing.html#module-multiprocessing.pool) and [`schwimmbad`](https://schwimmbad.readthedocs.io/en/latest/api.html#schwimmbad.MultiPool) …

Pass kwargs to pool constructor in `choose_pool`

---

pycbc/workflow/configuration.py

stashcp doesn't work now while using files over osdf. pelican is needed to access files from osdf. 
This change affects: the offline search, inference, PyGRB workflows involving osdf files
This change changes: access over osdf files.
This change will require pelican (https://docs.pelicanplatform.org/install). It also needs a release to run offline workflow.

Fix issue of using bank or files via osdf

---

pycbc/waveform/decompress_cupy.py
pycbc/waveform/waveform.py

For the CuPy backend, we need the decompress module translated; this is that translation
This change affects the offline search, as I don't think any others (use compressed waveforms)
This change will require additional dependencies (CuPy in the new backend)
This is effectively a copy of the decompress_cuda module, but using cupy rather than pycuda
#4952 
Comparison of waveforms with/without compression and from CPU/CuPy:

Add decompress module for prototype cupy backend

---

pycbc/scheme.py

This PR adds support for using multiple GPUs via MPI with the cupy backend. It is a follow-on to https://github.com/gwastro/pycbc/pull/4952
This change affects: in theory, any code that uses cupy schemes but, since the cupy scheme is relatively new, I don't believe it is being used it production 
This change changes: GPU support
This change: 
- does not have unit tests as I don't think we can test multi-GPU support in the CI.
- follows style guidelines (See e.g. [PEP8](https://peps.python.org/pep-0008/))
- has been proposed using the [contribution guidelines](https://github.com/gwastro/pycbc/blob/master/CONTRIBUTING.md)
This change will: N/A
The current cupy scheme is limited to a single GPU but using multiple GPUs when they are available can further accelerate …

Add multi-gpu support for cupy scheme

---

pycbc/workflow/core.py

This is a bug fix (in order to fix issue #5004)
This change affects PyGRB's workflows
This change was proposed by @duncanmmacleod in #5004 [in this comment](https://github.com/gwastro/pycbc/issues/5004#issuecomment-2587640490).  
This is the linked issue : #5004 
This change was tested by submitting a PyGRB workflow that succeed to start.

Patching segmentlists in `pycbc.workflow` module

---

pycbc/psd/__init__.py
pycbc/psd/analytical.py
pycbc/psd/read.py

Minor fixes to docstrings and error messages in the PSD module. The only functional change is that an exception is now raised in a place where it should have been, but was not. Apart from that, no functional change here.

Minor PSD module fixes

---

bin/pycbc_make_sky_grid
bin/pygrb/pycbc_pygrb_grb_info_table
pycbc/types/optparse.py

This PR simply expands the docstrings of pycbc.types.angle_as_radians, pycbc_pygrb_grb_info_table, and pycbc_make_sky_grid.

3 docstrings related to pycbc.types.angle_as_radians

---

bin/pycbc_make_banksim
bin/pycbc_make_faithsim
test/bankvetotest.py
test/test_array.py
test/test_array_lal.py
test/test_autochisq.py
test/test_chisq.py
test/test_correlate.py
test/test_frequencyseries.py
test/test_matchedfilter.py
test/test_pnutils.py
test/test_resample.py
test/test_schemes.py
test/test_timeseries.py
tools/timing/arr_perf.py
tools/timing/fft_perf.py
tools/timing/match_perf.py
tools/timing/wav_perf.py

In an attempt to remove "from xxx import *"-style imports from more places, I've used `git grep import | grep "*" | grep -v css| grep -v __init__` to find any places where this is used.
I then commented out the import, ran the tests to find what needs importing and getting that explicitly (not the most sophisticated, but seems to have worked).
After this change there is now 1 place which uses "from xxx import *", which is the versioning module, and I think that is valid.
The changes are mainly in the test suite - I've tried as much as possible to get tests to now pass, using cpu and cuda schemes, as these were what was catered for before!
I'd like to have other schemes / backends working, and some cuda tests fail, but that is for another PR
This is a code quality change
This change …

Efficient imports

---

bin/pygrb/pycbc_pygrb_results_workflow

PyGRB webpages often had gaps that could be fixed by running the `pycbc_make_html_page` job by hand, after a full workflow was completed.  This was a sign of incorrect dependencies in the workflow (i.e., `pycbc_make_html_page` was being called too early).
To fix this, this PR simply moves the call to `make_results_web_page` further down in the `pycbc_pygrb_results_workflow` workflow generator, so that the job dependencies are correct: **all** nodes that will give jobs that produce plots, tables, etc. are now in the collection of dependencies passed to `make_results_web_page`, so `pycbc_make_html_page` runs after those jobs.
I produced [this](https://ldas-jobs.ligo.caltech.edu/~francesco.pannarale/LVC/pygrb_tutorial/) results webpage from a …

Ensure pygrb webpage is generated after all results files are produced

---

bin/pygrb/pycbc_pygrb_page_tables

This PR enables the production of tables, within PyGRB, when the table needs to be empty.
This change changes: result presentation
The current version of `pycbc_pygrb_page_tables` (designed to handle missed/vetoed injections and loudest events) will not work when there is no injection/trigger to be displayed.
This PR fixes this issue.  The script no longer assumes there are injections to be displayed; further, it checks whether there is an onsource trigger to be reported: if there is not, the h5 file will be empty, where as the html file will say "There are no events" in the first column and report "-" in the remaining columns, to leave a human readable message.
The functioning of this can be checked in sections 3.01, 3.03, and 6 of …

Handling empty table in PyGRB

---

bin/pygrb/pycbc_pygrb_page_tables
pycbc/results/pygrb_postprocessing_utils.py

When recently running a light PyGRB workflow, the results webpage was not displaying the loudest onsource trigger information even though the workflow had found one.  Additionally, the follow up of the trigger did not happen.
There are 2 changes in the PR.
1. The call to load the onsource data in page_tables was asking for all timeslides (`slide_id="all"`), but the onsource is in zero-lag data so it now uses `slide_id=0`.  This fixes the issue reported in the motivation.
2. Digging through the code for the source of the issue, I spotted an `if/elif` structure that was heavily relying on lengths of arrays.  I changed it in order to make it more robust.  I should note that now this relies on the words "search" and "missed" possibily being in the hdf5 keys: if the keys structure were to …

More robust pygrb_page_tables

---

pycbc/workflow/pegasus_sites.py

We have recently conducted an exercise where we examined in detail an OSG PyCBC workflow, and identified all of the failure modes, highlighting some fail modes, including a few on our end. The discussion is here https://git.ligo.org/computing/helpdesk/-/issues/7042  It's probably behind the LVK paywall, but I don't there's anything confidential here so could probably share as needed.
There's some reasonably minor changes coming out of this for production workflows, but largely this adds in extra debugging in the log files to make debugging OSG workflows easier in the future. In particular:
* We remove `HAS_LIGO_FRAMES`. It's not set in many places, and we don't need it. Having this present will *massively* reduce the potential to run on OSG.
* Changing all `+ValueForCondor` settings to …

Updating pegasus_sites configuration

---

bin/pycbc_banksim_combine_banks

This fixes a missing `numpy` import to the `pycbc_banksim_combine_banks`.

Added import to banksim_combine_banks

---

.github/workflows/basic-tests.yml
.github/workflows/distribution.yml
.github/workflows/mac-test.yml
Dockerfile
bin/all_sky_search/pycbc_add_statmap
bin/all_sky_search/pycbc_coinc_findtrigs
bin/all_sky_search/pycbc_coinc_statmap
bin/all_sky_search/pycbc_coinc_statmap_inj
bin/all_sky_search/pycbc_exclude_zerolag
bin/all_sky_search/pycbc_sngls_statmap
bin/all_sky_search/pycbc_sngls_statmap_inj
docs/conf.py
pycbc/events/significance.py
pycbc/workflow/pegasus_sites.py
requirements.txt
setup.py
test/test_significance_module.py
test/validation_code/old_coinc.py
tox.ini

Not yet ready to be merged, but I'll log the changes for the v239 release here. I expect some compatibility issues will require some other patches to be added, but will let the test suite tell me.
I think GWOSC is down right now, so we may have to wait for that to be fixed.

V239 changes

---

bin/pygrb/pycbc_make_offline_grb_workflow
pycbc/workflow/jobsetup.py

This change changes: PyGRB workflow generation.
This PR contains 2 separate bugfixes uncovered while testing the code on single detector GRB runs using O4a data.
1. In the context of handling Veto definer files, `pycbc_make_offline_grb_workflow` checks for veto segments present in the onsource timewindow, i.e. around the GRB trigger, and throws an error if that's the case to avoid submitting jobs and  end up wasting CPU hours.
Currently lines [252-264](https://github.com/gwastro/pycbc/blob/a83736d49ffdf21b4fe3c6630e1067ff207981d6/bin/pygrb/pycbc_make_offline_grb_workflow#L252) lack an if statement to avoid operating with an empty list, when `avail_segs` has no elements. 
2. Single detector runs were not tested in the past. However by recently …

PyGRB: minor fixes to workflow generator 

---

docs/_include/inference_example_lisa_smbhb_inj.sh
requirements.txt
tox.ini

The CI is currently failing. I see two separate issues causing failures:
* lalsuite's FFT functions are segfaulting (@duncanmmacleod for info, as it really shouldn't do that). It seems that the issue is mixing MKL-compiled lower-level binaries. In particular the main difference between a functional run, and a failing CI run is:
```
< libblas                   3.9.0           28_h59b9bed_openblas    conda-forge
< libcblas                  3.9.0           28_he106b2a_openblas    conda-forge
---
> libblas                   3.9.0            16_linux64_mkl    conda-forge
> libcblas                  3.9.0            16_linux64_mkl    conda-forge
99,100c99,100
< liblapack                 3.9.0           28_h7ac8fdf_openblas    conda-forge
< liblapacke                3.9.0 …
```

Fix CI failures

---

bin/all_sky_search/pycbc_add_statmap
requirements.txt
tox.ini

Don't hard-code 'stat' as the zerolag (foreground) clustering quantity for add statmap.  Useful to investigate other choices eg ifar / ifar_exc 
This is a: feature enhancement
This change changes: scientific output (with a non-default option)
This change will: not break anything hopefully
In a recent tuning investigation I wanted to compare the effect of clustering with ifar vs 'stat'
One extra option
Works when run by hand on some exclude_zerolag files

Choice of clustering in pycbc_add_statmap

---

bin/plotting/pycbc_page_fars_vs_stat
bin/workflows/pycbc_make_offline_search_workflow
examples/search/executables.ini
examples/search/plotting.ini
pycbc/workflow/plotting.py

Incorporating the output of  `pycbc_page_fars_vs_stat` plot in the pycbc results page. This plot would be visible in the summary page and under the background triggers page.
This is a: new feature which adds an additional plot to the summary page. 
The far vs stat plots in the summary pages is crucial to validate the ranking of events during a offline run. 
Adds a new job in the `pycbc_make_offline_search_workflow` which is defined in the `workflow/plotting.py`.  Config changes in the mini-search to keep the changes consistent with this PR.
The v2.3.10 …

Fars_vs_stat plot in results page

---

pycbc/events/significance.py
pycbc/events/stat.py

When testing live with the new ranking statistic, we were getting a lot of weird FARs - this is due to getting stat values which were nan, and these were considered louder than everything else in the count_n_louder.
This change affects the live search, and touches code of the offline search, but shouldn't affect anything
We combat this problem in three ways, which should prevent it occurring as much as possible:
1. If median sigma from fits files for any benchmark-network detector is NaN, then we ignore it. As a result, e.g. NaNs …

Avoid nan values in network volume term - MASTER VERSION

---

.github/workflows/basic-tests.yml
bin/plotting/pycbc_plot_singles_vs_params
bin/pycbc_multi_inspiral
bin/pygrb/pycbc_make_offline_grb_workflow
pycbc/events/significance.py
pycbc/events/stat.py
pycbc/waveform/decompress_cpu.py
pycbc/workflow/jobsetup.py
requirements.txt
test/test_skymax.py
tox.ini

When testing live with the new ranking statistic, we were getting a lot of weird FARs - this is due to getting stat values which were nan, and these were considered louder than everything else in the count_n_louder.
This change affects the live search, and touches code of the offline search, but shouldn't affect anything
We combat this problem in three ways, which should prevent it occurring as much as possible:
1. If median sigma from fits files for any benchmark-network detector is NaN, then we ignore it. As a result, e.g. NaNs …

Avoid nan values in network volume term

---

pycbc/conversions.py

Added small check to ensure the spin magnitude in the remnant mass calulation is positive. Just in case somebody puts negative magnitudes...

Added check on spin magnitude

---

bin/workflows/pycbc_make_offline_search_workflow

This patch makes a few tweaks to the result pages.
* The summary page has become a bit overrun with statistic plots. With the new plot added by Tom, I think it makes sense to move the FAR vs Rank and Cumulative number vs IFAR plots to the relevant subsections. Now *only* the new plot is shown to summarize the behaviour of the statistic.
* The above point also fixes the issue that the new plot was duplicated num-ifo times on the summary page.
* The new plot was not displaying correctly in section 5 (because it was being linked to the wrong subsection). This is fixed here and it should now appear in the top of section 5.

Reorganize FAR/stat plots on summary page

---

pycbc/events/stat.py

This patch adds a `statistic_correction` "statistic keyword" in `stat.py`. This option will add a constant factor to *all* returned statistic values.
The immediate problem this patch sets out to fix is this plot (from https://inspirehep.net/literature/2053424)
This shows the desired behaviour using the state of the art statistic as of a few years ago. In particular HL doubles lie above other things.
When adding the new KDE term we see this relative behaviour change and H/L singles lie above the doubles line, causing singles to be weighted *more* than HL doubles when combining. Using this option we can downrank singles relative to doubles (and add appropriate factors when considering 3-ifo behaviour).
However, the patch is broader than that, it could be used (for e.g.) to try to make `0` …

Add statistic correction option

---

.github/workflows/bank-compress-workflow.yml
bin/plotting/pycbc_page_fars_vs_stat
bin/plotting/pycbc_plot_bank_compression
bin/plotting/pycbc_plot_singles_vs_params
bin/pycbc_compress_bank
bin/pycbc_hdf5_splitbank
bin/pycbc_inspiral
bin/workflows/pycbc_make_bank_compression_workflow
bin/workflows/pycbc_make_offline_search_workflow
examples/search/executables.ini
examples/search/plotting.ini
examples/tmpltbank/compress_workflow/compress.ini
examples/tmpltbank/compress_workflow/executables.ini
examples/tmpltbank/compress_workflow/gen.sh
pycbc/events/stat.py
pycbc/waveform/bank.py
pycbc/waveform/compress.py
pycbc/workflow/jobsetup.py
pycbc/workflow/pegasus_files/pegasus-properties.conf
pycbc/workflow/pegasus_sites.py
pycbc/workflow/plotting.py
pycbc/workflow/tmpltbank.py
pycbc/workflow/versioning.py
requirements.txt
setup.py

We have a few tweaks that are needed for the v2.3 release branch. I'll track these here, not yet ready for merging.

Changes for v2.3.10

---

pycbc/inference/models/marginalized_gaussian_noise.py

I think an index `idx` is missing to save the polarization that gives the maximum likelihood in the polarization marginalization model

fix a bug to save model current stats for maxL polarization

---

bin/workflows/pycbc_make_offline_search_workflow
pycbc/workflow/plotting.py
pycbc/workflow/versioning.py

I was doing the work from #5062 separately to Ian, and thought I'd apply the same logic/fixes to different parts of the results pages:
- the DQ, most of the singles and the workflow/(version and throughput) pages were all in "expand all", So I have fixed this by adding the command to make wells
- Added some things to the DQ summary page
- In the workflow section, dax, input_map, output_map and planning are all empty. I'm not sure how to add these, so am commenting out for now, but adding a FIXME (I will add an issue as well)
- I have tried to consolidate the injection and sensitivity pages, which were making the same plots multiple times.
This is a mix of bug fixes and new features
This change changes result presentation / plotting
This change …

Offline results page tidyup

---

pycbc/workflow/core.py

cache files in the workflow generators were not being got from repos in the same way that we could before. This fixes that
This is a bug fix / new implementation of an old feature
This change affects: the offline search, inference, PyGRB
Workflow generates when using a file on gitlab

Resolve_url for the cache file

---

pycbc/workflow/dq.py

The all-sky workflow code is setup so that the `workflow-ifos` section of the config should be the *only* place that decides what ifos are active. If (for example) that section lists h1 and v1, then sections labelled `l1` elsewhere in the config file should be ignored ... They should also not break anything (ie. having `l1` sections should be fine, they just won't be used). This then means that if I want to swap to a L1 V1 analysis I just turn L1 on and remove h1 from `workflow-ifos`.
At the moment the iDQ workflow code breaks this, by searching for section names (and not checking if they are actually being used). The fix is trivial, just do an "AND" operation, with `workflow-ifos` when iDQ figures out which ifos are present. This still allows the functionality that if there is not a …

iDQ workflow code shouldn't look for ifos that aren't there

---

pycbc/inference/models/marginalized_gaussian_noise.py

The marginalized time model currently projects the signal onto the detector with the polarization fixed to zero. This causes issues for parameter estimation when polarization is measurable. This pull request introduces a polarization factor to the projection to address this limitation.

Polarization problem with marginalized time model

---

.github/workflows/bank-compress-workflow.yml
.github/workflows/inference-workflow.yml
.github/workflows/search-workflow.yml
.github/workflows/tmpltbank-workflow.yml
.github/workflows/workflow-tests.yml
docker/etc/docker-install.sh
tools/docker_build_dist.sh

Years ago we forced pip < 22.0 due to a regression (#3925). We can probably drop this now.

Relax pip<22.0 constraint

---

.github/workflows/build_venv.yml
.github/workflows/docker-build.yml
Dockerfile
docker/etc/docker-install.sh
docker/etc/push_image.sh
tools/docker_build_prepssh.sh

While working on #5089, I found the Docker and CVMFS stuff a bit hard to follow and redundant, so here I try to clean in up a bit.
This is mostly a cleanup of the Docker image and publication on CVMFS with no expected functional changes.
Mainly to simplify the upcoming PR that will upgrade the Python version shipped in the Docker image and in the CVMFS virtualenvs.
First, I noticed that the CI jobs that build the Docker image and the CVMFS venv currently run the "setup Python" block. This does not seem necessary though, since everything in both jobs happens inside containers anyway. So I removed the "setup Python" stuff.
Second, I cleaned up the Dockerfile, mostly to break down long chains of commands into separate lines, to make further changes easier to review.
Third, I removed a couple …

Cleanup stuff that handles the Docker image and CVMFS release

---

bin/pygrb/pycbc_pygrb_efficiency
bin/pygrb/pycbc_pygrb_page_tables
bin/pygrb/pycbc_pygrb_plot_injs_results
pycbc/results/pygrb_postprocessing_utils.py

This change changes: plotting.
This change will: address several problems with `pygrb_postprocessing_utils`  that propagate to several pygrb plotting scripts, and additional changes to make `pycbc_pygrb_efficiency` and 'pycbc_pygrb_page_tables', `pycbc_pygrb_plot_injs_results`  for the no found injections case.
This changes were at first done in stages and stacked together to make a test workflow finish.
- First changes to `pygrb_postprocessing_utils` were addressed to fix problems in `pycbc_pygrb_inj_finder`
```
Finding injections: |          | 0/1 files (  0%) [00:00 | ETA ?], excluded=0, found=0, missed=0
Finding injections: |          | 0/1 files (  0%) [00:05 | ETA ?], excluded=0, found=0, missed=5
Finding injections: |##########| 1/1 …
```

PyGRB: fixing the no found injections case.

---

Dockerfile
docker/etc/docker-install.sh

Followup of #5091 and prelude to (a simpler version of) #5089.
In a bunch of places we are explicitly calling `python3.9` which complicates upgrading the version. This sets the system-wide Python version to `python3.9` right after installing it, so it is safe to just call `python` afterwards.
I also noticed that the Docker image contained about 800 Mb of pip cache, so this clears the cache at the end of the installs.

Docker: set default Python version early, use it more; purge pip cache

---

pycbc/io/hdf.py

This is an improvement to remove the side effects of a function
This change shouldn't change any results, only increase the memory usage.
This change follows style guidelines (See e.g. [PEP8](https://peps.python.org/pep-0008/)), has been proposed using the [contribution guidelines](https://github.com/gwastro/pycbc/blob/master/CONTRIBUTING.md). 
There is no unittest for it at the moment
I'm trying to add trigger cuts in this PR（https://github.com/gwastro/pycbc/pull/5090）, but then realize the chisq related trigger cutting function would change my single trigger dictionary because of this funciton that I'm changing. I changed to avoid directly editing the input to remove the side effect. The downside would be costing more memory as I created a new array to save the reduced chisq, but I …

Avoid directly editing function's arguments

---

.github/workflows/distribution.yml

We use the pypa/gh-action-pypi-publish to publish releases on PyPI. We use the master branch of that action, but this has been [discouraged years ago](https://github.com/pypa/gh-action-pypi-publish/tree/release/v1?tab=readme-ov-file#-master-branch-sunset-) (there is a prominent message hidden deep into the GitHub Actions pages, but it is hard to see unless you intentionally peek into those). This updates it to directly use the hash of the latest v1 tag as of today. Using the hash directly is another recommendation I have seen recently in a few places.

Update PyPI publish action to latest release

---

pycbc/workflow/pegasus_sites.py

In #5033 I converted the release flag from a string (either `'True'` or `'False'`) to an actual bool. However, I forgot to update a place that actually uses the release flag to figure out the path to the Singularity/Apptainer image. This fixes it.

Fix usage of release flag in Pegasus sites code

---

.github/workflows/distribution.yml
pycbc/workflow/pegasus_sites.py
setup.py

This cherry-picks #5097 (minor update of distribution tools) and #5098 (important bugfix) into the PyGRB release branch, and prepares for 2.8.1.

Pick cherries for v2.8.1

---

.github/workflows/basic-tests.yml

Edit the basic CI tests to download the LAL auxiliary data (currently only the files for SEOBNRv4_ROM) from Zenodo rather than git.ligo.org, and use a GitHub cache for it. While the speed gain is negligible, hopefully this reduces the load on git.ligo.org and helps make the CI tests more robust against web site outages.

Get LAL aux data from Zenodo and cache it

---

Dockerfile
tools/docker_build_dist.sh

Security support for Python 3.9 is ending later this year. I would like to move the CVMFS virtualenvs and Docker images to a more recent and supported Python version.

Upgrade Docker image and CVMFS virtualenv to newer Python

---

bin/all_sky_search/pycbc_fit_sngls_by_template

This change wouldn't affect anything if you don't use trigger cuts in the trigger fitting, .i.e., it's backward compatible. But offline search, live search, PyGRB, and any other pipeline that depends on trigger fitting could use this new feature.
This change follows style guidelines (See e.g. [PEP8](https://peps.python.org/pep-0008/)), has been proposed using the [contribution guidelines](https://github.com/gwastro/pycbc/blob/master/CONTRIBUTING.md). I'll try to add some unittests, but they don't exist at the moment
This change won't change any current pipelines, as it has backward compatibility.
We made some trigger cutting in the single trigger fitting and the coincidence job in 3-OGC and 4-OGC with an argument called …

add trigger cuts in trigger fit

---

bin/pycbc_multi_inspiral
pycbc/vetoes/autochisq.py
pycbc/vetoes/bank_chisq.py

`pycbc_multi_inspiral` is way too verbose when running with realistic production settings. This converts many `logging.info()` calls to `logging.debug()`, so that `--verbose` only shows a single message per (template, segment) combination, which I think is good enough to get a sense of the progress. The current verbosity can be restored with `--verbose 2` when actually testing things.
I also inverted the logic in the auto chi^2 and bank chi^2 codes to return early when there is nothing to do, removing one indentation level.

Make pycbc_multi_inspiral way less verbose

---

pycbc/workflow/segment.py

This PR fixes an error encountered when generating PyGRB workflows with an offsource that is not symmetric around the trigger time.
This change changes: it fixes a workflow generator error.
The error encountered is
```
2025-04-16T09:13:54.792-07:00 INFO : Leaving matched-filtering setup module.
File "/cvmfs/software.igwn.org/pycbc/x86_64_rhel_8/virtualenv/pycbc-v2.8.2/bin/pycbc_make_offline_grb_workflow", line 474, in <module>
_workflow.setup_pygrb_pp_workflow(wflow, pp_dir, seg_dir,
File "/cvmfs/software.igwn.org/pycbc/x86_64_rhel_8/virtualenv/pycbc-v2.8.2/lib/python3.9/site-packages/pycbc/workflow/grb_utils.py", line 352, in setup_pygrb_pp_workflow
node, out_file = job_instance.create_node(trig_file, …
```

Ensure that the PyGRB offsource segmentlist contains ints

---

pycbc/filter/resample.py

Make resampling more efficient by changing the recursion settings.
This is a: efficiency update
This change changes: code used for scientific output (but doesn't change output)
We've seen some issues with the recursive resampling used in the `lfilter` function. While there are some optimizations that could be done to the code as it was written, I'm not understanding the logic behind what it does.
In particular, why does it split the code into two uneven (1:127) pieces. Because it does this recursively it means that the sizes in play are wildly varying and the code is called *a lot*. Current data lengths require two levels of recursion, so in general we run on blocks around a few thousand seconds in length. While …

Change recursion parameter in resample

---

bin/pycbc_multi_inspiral

`pycbc_multi_inspiral` treats the case with 2 interferometers as a coincident search, rather than a coherent search.  With the assumption of a left/right circularly polarised signal, this should not be the case.  See https://inspirehep.net/literature/1323266, Section V A.
This is a: new feature.
This change is supported by the CI tests in PyCBC.
Anywhere `pycbc_multi_inspiral` separated the 1 IFO, the 2 IFO and more than 2 IFO cases, I simply reduced the branches to 1 IFO vs more than 1 IFO.
Tests with full runs are in progress.

PyGRB: handling the 2 IFO case with the coherent search methods

---

pycbc/workflow/configuration.py

The authentication method used by git.ligo.org changed recently. This breaks downloading files from repositories on git.ligo.org via `pycbc.workflow.resolve_url()`. Here is one way to fix it.
This is a new feature required by an LVK infrastructure change.
This change affects all workflows that use `resolve_url()`, in particular the offline all-sky and PyGRB searches.
This change changes basic workflow infrastructure.
We have historically relied on `ciecplib` to download files from repositoried hosted on git.ligo.org via Shibboleth authentication. Due to changes recently made to git.ligo.org, and outside our control, this does not work anymore. The recommended approach now is to use a GitLab Personal Access Token which each user has to get, store somewhere, and give to each HTTP request …

Workaround for git.ligo.org authentication change

---

bin/pycbc_multi_inspiral
bin/pygrb/pycbc_grb_trig_combiner
pycbc/pnutils.py
pycbc/results/pygrb_postprocessing_utils.py

- This PR fixes a bug in the PyGRB post-processing: when auto-gating occurs, the `gating` entry of results files should not be treated as a numpy array pertaining to the triggers found.  This was never encountered before because auto-gating was never triggered in the tests we ran so far.
- This PR also makes sure that the coincident SNR cut is applied in the single IFO case applies, in line with what happens when 2 or more IFOs are available for the analysis.  This keeps the amount of data under control, and is the strategy adopted previously with PyGRB+coh_PTF.
- Finally, this PR fixes two comments: one for syntax and one missing an input parameter description.
With the first of these changes, I was able to produce plots …

PyGRB single IFO case fixes

---

pycbc/results/scatter_histograms.py

This change will: break current functionality, require additional dependencies, require a new release, other (please describe)
The most recent matplotlib release May 8th, dropped the ability to pass None as a facecolor to indicated that it should not be visible. Instead it requires passing the literal string 'none'.

updated for depcreated fillcolor value

---

pycbc/inference/models/gated_gaussian_noise.py
test/test_infmodel.py

PR #5117 introduced a bug into the `GatedGaussianNoise` model. When the waveforms are generated in the `GatedGaussianNoise.loglikelihood` function `get_waveforms` should be called, but that was accidentally changed to `get_gated_waveforms`. The unit tests introduced in that PR didn't catch this as they only tested the `GatedGaussianMargPol` and `Hierarchical` models.
This patch fixes the bug by reverting the the line back to `get_waveforms`. It also introduces unit tests that should prevent this in the future. The new unit tests manually call the unmarginalized model's loglikelihoods over the same polarization samples the marg pol model uses, integrates it, and checks that that yields the same result as the marginalized model. The test is applied to both the gated models and the ungated …

Fix bug in GatedGaussian and add MargPol unit tests

---

bin/all_sky_search/pycbc_distribute_background_bins
bin/pygrb/pycbc_grb_trig_cluster
bin/pygrb/pycbc_grb_trig_combiner
pycbc/events/coinc.py
test/validation_code/old_coinc.py

Replaces deprecated `numpy.in1d()` calls with `numpy.isin()` to resolve deprecation warnings while maintaining identical functionality.
This change affects: Any code using numpy array comparisons
This change changes: Internal array comparison implementation
This change will: maintain current functionality while removing deprecation warnings
NumPy has deprecated `in1d()` in favor of `isin()` since version 1.13.0. This change:
- Removes annoying deprecation warnings during runtime
- Future-proofs the code against eventual removal of …

Resolve warnings of NumPy library

---

pycbc/workflow/configuration.py

`resolve_url()` does not seem to work for OSDF URLs. This should fix it.
This is a bug fix.
This change affects offline workflows.
#5001 changed the way we resolve `osdf://` URLs to use `pelican object get <source> <destination>`. However, the code there actually calls `pelican object\ get <source> <destination>`, i.e. "object get" is given as a single argument made of two words separated by a space, which `pelican` does not like:
```
Error: unknown command "object get" for "pelican"
Run 'pelican --help' for usage.
```
This replaces the "object get" arg with two args "object" and "get". I also noticed that the OSDF branch of the code returned immediately after calling `pelican`, which is not what the other branches do, so I removed the return as well.
#5001
None so far, be back shortly. …

Fix incorrect OSDF URL resolution

---

pycbc/inference/models/tools.py

The error described in the PR https://github.com/gwastro/pycbc/pull/5106 was persistent since the function has another return. This PR is assigning zero values to logw_partial when demarginalization returns early without assigning any values due to lack of snr peaks.

Error in demarginalization 

---

pycbc/workflow/configuration.py

Equivalent of #5135, but I didn't realise this was on master as well, I thought it was only the v23 release branch, this is also needed on v28 release branch
We noticed that files under git-lfs did not work with the reworked resolve_url
Adding `&lfs=true` seems to make the gitlab download helper work for lfs files _as well as_ non-lfs files still working
Tested by using resolve_url to download both lfs and non-lfs files

Add lfs resolution to resolve_url gitlab helper

---

bin/pygrb/pycbc_make_offline_grb_workflow

Adding input-dist variable in check of the workflow section for the generation of the sky grid
This change affects PyGRB
This change changes PyGRB's workflow generation
In order to use the new implementation of the skygrid generator (#5085) we need to make this check of the workflow section more flexible with a new check with the variable `input-dist`.

Make the generation of the skygrid in `pycbc_make_offline_grb_workflow` more flexible

---

bin/pycbc_banksim_combine_banks
bin/pycbc_banksim_match_combine

np.unicode_ has been deprecated, so we should use np.str_ instead
This change affects banks
This change fixes scientific output
This change has been proposed using the [contribution guidelines](https://github.com/gwastro/pycbc/blob/master/CONTRIBUTING.md)

np.unicode_ deprecated

---

bin/inference/pycbc_inference_create_calibration_config
examples/inference/calibration_configuration_files/download_calibration_uncertainty_files_o1_o2_o3.sh
examples/inference/calibration_configuration_files/generate_calibration_config.sh
pycbc/strain/recalibrate.py

To incorporate calibration uncertainties in PE runs, one need to provide a calibration configuration files to `pycbc_inference` code. Although, the support for the calibration config file exist, we still do not have a way to generate these config files, within PyCBC infrastructure. In this PR, I include the full infrastructure to generate the config files for PE runs for any GPS time from the publicly available calibration envelopes provided by [LIGO-Virgo](https://dcc.ligo.org/T2100313/public).

Adding functionalities to create calibration config files

---

bin/pycbc_multi_inspiral

`pycbc_multi_inspiral` is unnecessarily un-normalizing the SNRs in preparation for the chi^2 calculations.
This is an efficiency update.
This change should not affect any result, just code speed.
In #5148, @spxiwh realized that `pycbc_multi_inspiral` is spending a relatively large amount of time doing array divisions. Indeed, in the inner loop over sky points, the SNRs are un-normalized before being passed to the chi^2 calculations, *even when those calculations are disabled*. This is not a huge problem compared to other inefficiencies, but of the various optimizations discussed in #5148, this is the most straightforward one by far.
On a close inspection of the chi^2 codes, I realized that the corresponding `value()` methods have really no reason to take the …

Avoid unnecessary SNR (re)normalization in `multi_inspiral`

---

pycbc/inference/models/gated_gaussian_noise.py

This PR fixes a one-line bug in the `multi_loglikelihood` method of `GatedGaussianNoise` class. I think this is critical as otherwise two waveforms with different lengths can't be summed in the next line. 
In particular, this PR wouldn't affect the previous ringdown black hole spectroscopy runs, as ringdown analysis only uses `hierarchical` model, not `multi_signal`.

fix a bug in the mutli loglikelihood method of the gated gaussian noise class

---

bin/pycbc_multi_inspiral

In the presence of loud injections (and perhaps glitches) and with large sky grids, `multi_inspiral` spends most of its time doing chi^2 calculations. This reduces that.
This is an efficiency update.
This addresses the first thing I described in #5148, namely the fact that some `multi_inspiral` jobs can take many hours just doing repeated power chi^2 calculations in the critical loop over time slides and sky points. As the calculation is a single-detector operation, it does not depend on time slide or sky position, so its result be cached for reuse in the following iterations.
I introduce a cache for the power chi^2 values and DoF. Every time a new chi^2 calculation is required, I check which time samples had their chi^2 calculated before, and I only call the …

`multi_inspiral`: avoid repeated power chi^2 calculations in the critical loop

---

pycbc/detector/ground.py
pycbc/inference/models/gated_gaussian_noise.py
pycbc/inference/models/marginalized_gaussian_noise.py
pycbc/waveform/generator.py
test/test_detector.py

This PR adds the ability to sample the coalescence time parameter `tc` in the detector frame. Currently, `tc` is sampled in the geocentric frame and converted to detector frames to calculate likelihoods. The changes here preserve this behavior by default, but add the ability to sample in one of the detectors specified in the inference configuration.
This is a new feature. This change mainly affects inference when using `FDomainDetFrameGenerator`. Any code that uses the `generate` method to generate waveforms in the detector frame can also make use of this. Current functionality (generating using `tc` in geocentric frame) is preserved by default.
This change is being made as a potential improvement to convergence when conducting PE, especially when implementing sky location and time …

Add functionality to sample coalescence time in detector frame

---

bin/pygrb/pycbc_make_offline_grb_workflow
bin/pygrb/pycbc_pygrb_results_workflow
pycbc/workflow/grb_utils.py
pycbc/workflow/pegasus_workflow.py
pycbc/workflow/plotting.py

PyGRB workflows often produce results webpages that are missing the minifollowup plots. This should hopefully fix that.
This is a bug fix.
This change changes result presentation / plotting.
This change will require a new release.
Results webpages from recent PyGRB workflows have empty minifollowup sections. So far we have handled this manually by rerunning the results_page job, but this is obviously undesirable.
Inspecting one of the DAX file reveals that the results_page job has no explicit dependency on any of the minifollowup jobs, so it should not be a surprise that whether the minifollowups content shows up is just a matter of chance.
I made the `SubWorkflow` instances that are responsible for the minifollowups be explicit parents of the results_page job, …

PyGRB: mark minifollowup subworkflows as parents of results_page jobs

---

bin/pycbc_hdf5_splitbank

`pycbc_hdf5_splitbank` distributes templates unevenly across the banks, sometimes causing the last bank to be much larger than the previous ones.
This is an efficiency update.
This change targets the efficiency of the offline all-sky search and PyGRB, but not the results.
As part of optimizing PyGRB workflows, I noticed that one of the no-injection jobs systematically takes ~10 times longer than the other jobs. I tracked this down to a bug (or feature?) in how the bank is split by `pycbc_hdf5_splitbank`. The number of templates to assign to each bank is truncated to an integer before assigning the templates. This causes most output banks to systematically contain less templates than they should, and all the remaining templates are lumped into the final output bank. In my tests, most …

Improve HDF bank splitter

---

.github/workflows/bank-compress-workflow.yml
.github/workflows/basic-tests.yml
.github/workflows/distribution.yml
.github/workflows/inference-workflow.yml
.github/workflows/mac-test.yml
.github/workflows/search-workflow.yml
.github/workflows/tmpltbank-workflow.yml
.github/workflows/tut-test.yml
.github/workflows/workflow-tests.yml
setup.py

This drops support for python 3.9 and 3.10
No changes to analysis code, but the testing will no longer be run for 3.9 and 3.10. 
Python 3.9 and 3.10 are past normal support guidelines for scientific python. While maintaining broader compatibility is fine, we are increasingly hitting library deprecations and having to write code to support simultaneous versions. 
- [./ ] The author of this pull request confirms they will adhere to the [code of conduct](https://github.com/gwastro/pycbc/blob/master/CODE_OF_CONDUCT.md)

first pass to drop 3.9 and 3.10 support

---

requirements.txt

CI jobs are failing as dynesty 3.0 has had some major changes to the API, breaking our interface with it
This is a: bug fix, new feature, efficiency update, other (please describe)
This change affects: inference
This change changes: documentation
This change will: restore current functionality
pin dynesty to <3.0

Pin dynesty to. <3.0 until the API interface can be updated

---

pycbc/coordinates/space.py
pycbc/cosmology.py
pycbc/events/coinc.py
pycbc/inference/models/relbin.py
pycbc/io/ligolw.py
pycbc/waveform/waveform.py

This fixes a few of the deprecation warnings in #5179
This is a: deprecation fix
This change changes: documentation, result presentation / plotting, scientific output
Things are deprecated; if we don't remove them now, they will be failures
Generally, this is just going through the suggested fixes for the deprecations.
I'm not sure on one or two places:
- in `pycbc/coordinates/space.py`, could this ever actually be an array, is it only a single-value array in the tests? This is also a warning in …

Deprecation fixes
