- pycbc/events/coinc.py
Add a function to calculate the duration of coincident data for an array of timeslide offsets.
> Duration staging

- bin/hdfcoinc/pycbc_coinc_findtrigs
- bin/hdfcoinc/pycbc_coinc_hdfinjfind
- bin/hdfcoinc/pycbc_coinc_statmap
- bin/hdfcoinc/pycbc_coinc_statmap_inj
- bin/hdfcoinc/pycbc_make_hdf_coinc_workflow
- bin/hdfcoinc/pycbc_page_foreground
- bin/hdfcoinc/pycbc_page_sensitivity
- bin/hdfcoinc/pycbc_page_snrifar
- bin/pycbc_make_coinc_workflow
- pycbc/events/coinc.py
- pycbc/events/veto.py
- pycbc/workflow/coincidence.py
- pycbc/workflow/core.py
- pycbc/workflow/ini_files/example_hdf_post.ini
- setup.py
These set of patches add the calculation of FAP/FAR for injections where their own triggers are included in their backgrounds. It also updates the sensitivity plotting code, etc to plot both values. 
They also update both pycbc_make_coinc_workflow, and pycbc_make_hdf_conc_workflow, along with the example ini files for hdf post processing.
> injection 'little dog' background estimation

- bin/hdfcoinc/pycbc_make_hdf_coinc_workflow
- bin/hdfcoinc/pycbc_page_coinc_snrchi
- bin/hdfcoinc/pycbc_page_foundmissed
- bin/hdfcoinc/pycbc_page_sensitivity
- pycbc/results/plot.py
- pycbc/results/render.py
- pycbc/results/templates/files/file_default.html
- pycbc/workflow/core.py
- pycbc/workflow/ini_files/example_hdf_post.ini
- pycbc/workflow/plotting.py
Add basic web page generation to the hdf workflow using Chris's pycbc_make_html_page
> Folder webpage

- bin/hdfcoinc/pycbc_page_coinc_snrchi
- bin/hdfcoinc/pycbc_page_sensitivity
- pycbc/results/plot.py
- pycbc/results/render.py
- pycbc/results/templates/files/file_default.html
- pycbc/sensitivity.py
refactor pycbc_page_sensitivity
add some better documentation, docstrings, argparse help
Note, this is built upon https://github.com/ligo-cbc/pycbc/pull/3
(If that is merged, the patch list below will be a lot smaller)
> Sensitivity staging

- bin/hdfcoinc/pycbc_make_hdf_coinc_workflow
- bin/hdfcoinc/pycbc_page_coinc_snrchi
- bin/hdfcoinc/pycbc_page_foundmissed
- bin/hdfcoinc/pycbc_page_sensitivity
- bin/hdfcoinc/pycbc_plot_singles_vs_params
- pycbc/results/plot.py
- pycbc/results/render.py
- pycbc/results/templates/files/file_default.html
- pycbc/workflow/core.py
- pycbc/workflow/ini_files/example_hdf_post.ini
- pycbc/workflow/plotting.py
This adds Tito's pycbc_plot_singles_vs_params to the hdf only workflow and updates the example ini file. 
Built upon,
https://github.com/ligo-cbc/pycbc/pull/8
> Integrate plot singles

- bin/pygrb/pygrb_make_offline_workflow
- bin/pygrb/pygrb_make_summary_page
- examples/workflow/pygrb/main.ini
- examples/workflow/pygrb/postprocessing.ini
- examples/workflow/pygrb/pygrb_make_offline_workflow
- examples/workflow/pygrb/run_pygrb.sh
- pycbc/workflow/jobsetup.py
- pycbc/workflow/legacy_ihope.py
- pycbc/workflow/postprocessing_cohptf.py
- setup.py
This is my first attempt at taking part in the "Fork & Pull" method. I'm doing it here so I can't break anything important. These are some commits regarding the post processing and summary page generation for the PyGRB workflow.
> Pygrb dev commits

- bin/pycbc_aligned_stoch_bank
- bin/pycbc_geom_aligned_bank
- docs/tmpltbank.rst
- pycbc/tmpltbank/coord_utils.py
- pycbc/tmpltbank/em_progenitors.py
- pycbc/tmpltbank/option_utils.py
Worked on all items in the todo list on https://bugs.ligo.org/redmine/issues/2134
> Changes to EM bright template bank tools following merge to master request.

- pycbc/io/sqlite.py
- pycbc/workflow/jobsetup.py
- pycbc/workflow/matched_filter.py
- pycbc/workflow/tmpltbank.py
Cosmetic clean up of sqlite.py and jobsetup utils to help bring their scores up a bit higher on landscape.io
> more cosmetic cleanups

- bin/pycbc_compute_durations
- pycbc/events/veto.py
- pycbc/results/render.py
- pycbc/workflow/jobsetup.py
- pycbc/workflow/segment.py
* fromsegmentxml: make segment times of type lal.LIGOTimeGPS
* fromsegmentxml: fix apparently wrong logic for handling the id != None case (please check!)
* fromsegmentxml: cleanup code and arg names conflicting with Python keywords
* segments_to_file: fix potential ValueError due to multiple LIGOTimeGPS types
> Fix issues with segment handling

- pycbc/io/sqlite.py
- pycbc/workflow/jobsetup.py
- pycbc/workflow/matched_filter.py
- pycbc/workflow/tmpltbank.py
It looks like I broke the link-to-job when I added multiple job tiling sizes. This patch fixes that mistake. 
Here is a comparison of current master (with this patch) on the last reviewed ini file
https://atlas1.atlas.aei.uni-hannover.de/~ahnitz/ahope_review/pycbc_review/s6d/twoweek_pycbc_tmpltbank4/970012743-971622087/
Here is the review run. 
https://sugar-jobs.phy.syr.edu/~cbiwer/ahope_review/pycbc_review/s6d/twoweek_inspiral_nochisq/970012743-971622087/
I believe they are now within expected variance for different different architecture, etc.
> fix compatibility mode

- bin/pycbc_make_html_page
This pull requests allows `pycbc_make_html_page` to unzip files.
If a file is unzipped `pycbc_make_html_page` preserves the subdir structure that existed in the zip file.
It does not transfer the original zipped file to the html output location.
> The pycbc_make_html_page executable will now unzip files.

- pycbc/results/templates/concrete.html
Adds a `</div>` to close the `row` class. And indents everything in the `row` for readability.
> Add missing </div> and fix indentation in html template.

- pycbc/workflow/core.py
- pycbc/workflow/segment.py
Fixes from landscape page:
* Removed unused imports in `core.py` and `segments.py`.
* Fixed indentation in `segments.py`.
> Landscaping fixes

- pycbc/tmpltbank/lattice_utils.py
- pycbc/tmpltbank/option_utils.py
- test/test_tmpltbank.py
This fixes AnStar functionality in the tmpltbank module. I also update the test suite. I will merge this once I hear back from Karl that a changed lattice is expected.
I also remove a debugging statement that somehow ended up on master.
> Implement Karl's AnStar patch and update test suite

- bin/hdfcoinc/pycbc_make_hdf_coinc_workflow
First pass of reorganizing the hdf plots into more sensible folder locations.
> move plots to more sensible folder locations

- setup.py
Try again to remove the daily workflow
> remove daily from setup.py

- bin/hdfcoinc/pycbc_calculate_psd
- bin/hdfcoinc/pycbc_make_hdf_coinc_workflow
- bin/hdfcoinc/pycbc_plot_psd_file
- pycbc/psd/__init__.py
- pycbc/strain.py
- pycbc/workflow/core.py
- pycbc/workflow/jobsetup.py
- setup.py
Add basic spectrum plot. The filled in region is the 5 and 95th percentiles of the psds in a run.
requires #93
> basic spectrum plot

- pycbc/__init__.py
- pycbc/scheme.py
Add a check for the MKL library and give a more useful error message when it fails to find it.
> check for mkl library on instantiation

- bin/hdfcoinc/pycbc_calculate_psd
- bin/hdfcoinc/pycbc_make_hdf_coinc_workflow
- bin/hdfcoinc/pycbc_plot_psd_file
- bin/hdfcoinc/pycbc_plot_range
- pycbc/workflow/coincidence.py
- pycbc/workflow/ini_files/example_hdf_bns.ini
- pycbc/workflow/plotting.py
Include generation of the inspiral psds along with a spectrum and range plot in the hdf workflow. Plots are still fairly basic at the moment.
Example result here. 
https://sugar-jobs.phy.syr.edu/~ahnitz/projects/polish/r6/gw/html/detector_sensitivity/
> Detector sensitivity

- pycbc/results/render.py
- pycbc/results/static/css/pycbc/orange.css
- pycbc/results/templates/files/file_default.html
- pycbc/results/templates/files/file_pre.html
- pycbc/results/templates/orange.html
- pycbc/results/templates/wells/two_column.html
This PR:
* Adds numbering to the navbar, the well in `orange.html` and the Addition Files section.
* Caption is now a button.
* Some HTML cosmetics to `orange.html`.
* Removes accordion from pre-format HTML template.
EDIT: An example: https://sugar-jobs.phy.syr.edu/~cbiwer/tmp/html_version_2/coincident_triggers/
> Htmlclean dev

- bin/mvsc/pycbc_mvsc_dag
- bin/mvsc/pycbc_mvsc_get_features
Included min_weights and distance_power options for signal weighting
> pycbc_mvsc_get features with more weight options

- bin/hdfcoinc/pycbc_make_hdf_coinc_workflow
- bin/hdfcoinc/pycbc_page_foundmissed
- pycbc/workflow/ini_files/example_hdf_bns.ini
- pycbc/workflow/plotting.py
Update the top-level summary to include a foundmissed plot and a sensitivity plot. Also update the example ini file. 
Example here,
https://sugar-jobs.phy.syr.edu/~ahnitz/projects/polish/r13/gw/html/
> Results page

- bin/hdfcoinc/pycbc_make_hdf_coinc_workflow
Add back the section numbers, but do it in the workflow generator. 
Example Here,
https://sugar-jobs.phy.syr.edu/~ahnitz/projects/polish/r15/gw/html/
> do section numbering and order in workflow

- bin/hdfcoinc/pycbc_coinc_hdfinjfind
- bin/hdfcoinc/pycbc_make_hdf_coinc_workflow
- bin/hdfcoinc/pycbc_page_sensitivity
- pycbc/workflow/ini_files/example_hdf_bns.ini
Add the option to make a vt plot with pycbc_page_sensitivity. I've also updated the example focused bns ini file to reflect this. 
Example result page here. 
https://atlas1.atlas.aei.uni-hannover.de/~ahnitz/LSC/projects/bns_er7/full/reference/gw3/html/
> add vt plot 

- bin/pycbc_faithsim
Importing OPENCL faithsim calculation to fail.
I talk to Ian and he said to remove the OPENCL import
which worked.
> Removed OPENCL import

- bin/hdfcoinc/pycbc_page_coinc_snrchi
.. with background, also fix legend placement - addresses #144
> page_coinc_snrchi: make injection chisq choice consistent 

- bin/hdfcoinc/pycbc_page_sensitivity
- pycbc/sensitivity.py
> fix monte carlo sensitivity calculation for chirp distance distributions

- pycbc/workflow/segment.py
Options are 
segments-method = ALL_SINGLE_IFO_TIME
or
segments-method = COINC_TIME
> add segments-method to analyze all single ifo time or coinc time

- bin/hdfcoinc/pycbc_coinc_findtrigs
- bin/pycbc_make_coinc_workflow
- pycbc/events/events.py
- pycbc/psd/__init__.py
- pycbc/vetoes/autochisq.py
I'm trying to clean up my local git with respect to master after ER7. Here are 4 patches that I want to merge now. They are:
* Add the second parameter "n" to the newSNR calculation ... This one is *much* more useful than the q parameter, as you can downweight the high SNR events, n only affects the low SNR curvature. Making this something like 12/7. helps to remove the affect of high SNR events creeping across the new SNR contours.
* Pycbc_coinc_findtrigs will fail if no triggers are in the *second* ifo for any template. This fixes that.
* There is an incorrect veto name in pycbc_make_coinc_workflow, this will be fixed when moving to the shared interface, but for now, this fixes things.
* The bug fix for reverse auto-chisq. (People can revert this if they want to reproduce the previous …
> ER7 run branch

- pycbc/frame.py
- pycbc/strain.py
Add the option to get frame files through an internal datafind query. You provide the option frame-type instead of frame-cache or frame-files.
> add option to get frame from datafind

- bin/pycbc_splitbank
This lets one fix the bank chunks across different workflow runs.
> splitbank: enable setting random seed, minor fixes

- bin/hdfcoinc/pycbc_plot_singles_timefreq
- pycbc/pnutils.py
- setup.py
Examples at https://atlas1.atlas.aei.uni-hannover.de/~tito/LSC/er7/er7_full_uberbank2_chi2var3_dq_2/spaghetti
> Add utility for plotting triggers in time-frequency plane

- bin/hdfcoinc/pycbc_plot_range
The range plot was broken such that it would mix up which star/end times matched which ranges. 
Broken plot.
https://sugar-jobs.phy.syr.edu/~ahnitz/projects/mbins/t5/gw/html/H1L1-PLOT_RANGE-962582415-604800.png
Fixed.
https://sugar-jobs.phy.syr.edu/~ahnitz/projects/mbins/t5/gw/psds/test.png
> fix range plot

- .travis.yml
- pycbc/frame.py
- tools/install_travis.sh
- tools/run_travis.sh
A couple changes to Travis:
* Cache the dependency installation
* Run a zeroth-order runnability check on several important executables
Note that I had to move a glue import into the function using it due to an implicit dependency on M2Crypto.
> Travis improvements

- bin/pycbc_inspiral
- pycbc/events/events.py
- pycbc/events/simd_threshold.py
- pycbc/events/threshold_cpu.py
- pycbc/filter/matchedfilter.py
- pycbc/filter/simd_correlate.py
Reverts ligo-cbc/pycbc#166
I've noticed some strange results, and I'm generating this as a convenience to check if the issues were introduced here.
> Revert "Cpuopt"

- bin/pycbc_inspiral
- pycbc/events/events.py
- pycbc/events/simd_threshold.py
- pycbc/events/threshold_cpu.py
- pycbc/filter/matchedfilter.py
- pycbc/filter/simd_correlate.py
> Revert "Revert "Cpuopt""

- pycbc/workflow/core.py
- pycbc/workflow/pegasus_files/basic_pegasus.conf
This adds two separate features relevant to remote workflows
* The ability to merge entries in a cache file to an in-dax transformation catalog (requires Pegasus 4.5.2)
* The ability for executables to be specified as gsiftp: URLs
> Remote workflow

- pycbc/events/threshold_cuda.py
Now that we allow clustering over template-dependant windows we don't know the window length when the CUDAThresholdCluster object is constructed.  This patch moves the impacted code from the constructor to the threshold_and_cluster method, which already accepted a window argument.  Fortunately it looks like someone already anticipated this as get_tkernel caches its results :)
> Move window dependance out of constructor

- pycbc/events/coinc.py
- pycbc/io/hdf.py
Add a function to the StatmapData type to save as a coincidence files. I will later use this when parsing coincidence files into multiple subbins.
> add coinc save function

- pycbc/workflow/ini_files/example_hdf_bns.ini
This updates the example config with one that I have used to test the plotting codes.
> update example hdf config file

- bin/hdfcoinc/pycbc_distribute_background_bins
- bin/hdfcoinc/pycbc_plot_bank_bins
- pycbc/workflow/plotting.py
Tom, 
Here is the commit that didn't seem to be pushed. It fixes the bank issues I think you saw.
> fixes to bank plot

- bin/hdfcoinc/pycbc_coinc_hdfinjfind
- bin/hdfcoinc/pycbc_coinc_statmap
- bin/hdfcoinc/pycbc_coinc_statmap_inj
- bin/hdfcoinc/pycbc_page_banktriggerrate
- bin/hdfcoinc/pycbc_page_coinc_snrchi
- bin/hdfcoinc/pycbc_page_foundmissed
- bin/hdfcoinc/pycbc_page_ifar
- bin/hdfcoinc/pycbc_page_snrifar
- pycbc/events/coinc.py
- pycbc/io/hdf.py
Sometimes when running with a small bank for testing, you may end up with no foreground triggers, or no injection triggers. The code should handle this case gracefully.
The following patch fixes issues I found when trying to do this. I also remove some debugging lines in a few places. Example output page to follow.
> Fixes to handle no foreground/injection triggers

- tools/static/build_static_executables.sh
- tools/static/hooks/hook-pycbc.py
This removes a restriction I had in place for testing and generalizes the test done in hook-pycbc to determine files to include.
> Remove restriction used for testing, generalize dependency test

- docs/uberbank_verify.rst
- examples/banksim/nsbh_below50.ini
addressing https://github.com/ligo-cbc/pycbc/issues/280
> first version of bank verification documentation file

- bin/pycbc_submit_dax
Fixes https://github.com/ligo-cbc/pycbc/issues/292
> fixed short option parsing

- bin/pycbc_coinc_time
Just altered a few of the help messages in pycbc_coinc_time to make them clearer
> altered help messages in pycbc_coinc_time

- bin/hdfcoinc/pycbc_make_hdf_coinc_workflow
- bin/hdfcoinc/pycbc_page_sensitivity
- bin/hdfcoinc/pycbc_plot_hist
- pycbc/workflow/plotting.py
This allows one to specific plots for the wells in foundmissed and search sensitivity pages. VT now also uses scientific notation for its y-axis, and the histograms will actually respect the x-max argument.
> allow web pages for foundmissed/search sensitvity, minor plot fixes

- bin/hdfcoinc/pycbc_page_recovery
- setup.py
As it says.  The actual code has now been tested ..
> pycbc_page_recovery: fix bugs, use no eval, add to setup.py

- pycbc/workflow/segment.py
This fixes issue #317 by moving workflow.segment over to the urllib2 module. I've tested this locally, but Duncan it would be good to test also on your end.
> Move workflow.segment over to urllib2

- pycbc/workflow/core.py
This adds a function, resolve_url that accepts any of
* http://
* https://
* file://
* plain file names
and returns a local filename, downloading if necessary.  This will be needed to resolve https://github.com/ligo-cbc/pycbc/issues/306 and https://github.com/ligo-cbc/pycbc/issues/311
> Added method to resolve URLs to local filenames

- pycbc/psd/read.py
> fix off by df issue with psd read

- docs/workflow/pycbc_bns_hdf_config_walkthrough.rst
- docs/workflow/pycbc_make_coinc_workflow.rst
- docs/workflow/pycbc_make_psd_estimation_workflow.rst
- docs/workflow/pycbc_make_sngl_workflow.rst
- docs/workflow/pygrb.rst
- pycbc/workflow/configuration.py
This passes the ini files through resolve_url() to pull down any specified as http(s).  It also removes --installed-config-files and renames --local-config-files to --config-files.
> Issue 311. Resolve URLs to ini files, unify config file arguments.

- bin/hdfcoinc/pycbc_average_psd
- bin/hdfcoinc/pycbc_make_psd_estimation_workflow
- pycbc/workflow/psd.py
- setup.py
Add ability to save average PSDs in GSTLAL XML format, and include that in the PSD estimation workflow.
> Generate XML PSDs

- docs/build_gh_pages.rst
- docs/install.rst
- docs/workflow/pygrb.rst
Also removed circular reference to install instructions from PyGRB documents.
> Added instructions for installing HDF5 1.8.12 in a virtual environment

- bin/pygrb/pygrb_make_offline_workflow
- examples/workflow/pygrb/ER8/er8_injections.ini
- examples/workflow/pygrb/ER8/er8_main_offline.ini
- examples/workflow/pygrb/ER8/er8_main_online.ini
- examples/workflow/pygrb/ER8/er8_postprocessing.ini
- pycbc/workflow/jobsetup.py
- pycbc/workflow/postprocessing_cohptf.py
- pycbc/workflow/splittable.py
These commits fix a single dependency issue in post processing, fix the box opening script generation, fixing an issue with tags not being passed to jobs after a previous change to splittable tag handling, and adding some ER8-like example files.
> PyGRB-related bug fixes

- bin/pycbc_banksim
instead of take psd file directly add psd.from_cli
> banksim modified to take psd-file directly

- bin/pycbc_banksim
- bin/pycbc_make_banksim
adding functionality to do asymmetric mchirp_windows in both pycbc_banksim and pycbc_make_banksim
> Banksim asym mchirp window

- bin/hdfcoinc/pycbc_combine_statmap
- bin/hdfcoinc/pycbc_distribute_background_bins
- bin/hdfcoinc/pycbc_make_hdf_coinc_workflow
- bin/minifollowups/pycbc_page_coincinfo
- pycbc/events/coinc.py
- pycbc/workflow/coincidence.py
Here is an example,
https://sugar-jobs.phy.syr.edu/~ahnitz/projects/bigdog_rerun/duncan/gw3/html/7._result/
Depends on #357
> Add utc time and links to detchar summary page from coincident tables

- bin/hdfcoinc/pycbc_combine_statmap
- bin/hdfcoinc/pycbc_distribute_background_bins
- bin/hdfcoinc/pycbc_make_hdf_coinc_workflow
- bin/minifollowups/pycbc_page_coincinfo
- pycbc/events/coinc.py
- pycbc/workflow/coincidence.py
1) cluster based on IFAR, then NewSNR
2) make minifollowups for each background bin
3) count from 1, not 0 on result page
Results running, now. I'll post a link when I have it.
> Various improvements to the search result web page

- bin/pycbc_banksim
needs to import pycbc.strain for psd estimation
> added import pycbc.strain

- install_pycbc.sh
This includes a patch to work around bug in matplotlib-sphinxext and modifies the script so that it asks the user where MKL is installed (since atlas has a different install path to sugar).
> Improvements to install script

- bin/minifollowups/pycbc_page_coincinfo
Ok, I apparently did not fix the case of no trigger being present within pycbc coincinfo. This hopefully rectifies that.
> fix case where no triggers found in pycbc coininfo

- bin/minifollowups/pycbc_single_template_plot
Without the exit the next line throws an error
> Exit after determining there are no triggers

- bin/hdfcoinc/pycbc_make_coinc_search_workflow
- bin/hdfcoinc/pycbc_make_psd_estimation_workflow
- docs/workflow/pycbc_make_psd_estimation_workflow.rst
- pycbc/results/__init__.py
- pycbc/results/layout.py
- pycbc/workflow/segment.py
* move layout utilities to separate module and document them a bit better
* add a result page for the PSD estimation workflow.
Untested at the moment, except to say that the workflow generator runs, and that the output folder / file layout looks right. I'll post back if/when I get a workflow to run.
Please take a look anyway, if you have time, in case something can be spotted wrong early.
> psd estimation results page

- bin/hdfcoinc/pycbc_make_psd_estimation_workflow
This adds the psd files themselves as downloadable links in the psd results page.
> symlink to hdf psd files

- setup.py
- tools/install_travis.sh
> Revert "Specify exact versions of all dependancies"

- bin/hdfcoinc/pycbc_page_coinc_snrchi
- bin/pycbc_single_template
> Plot fixes

- install_pycbc.sh
I've tested this but not to completion, it would be great if somebody could give it a full try before merging.
> install_pycbc.sh: log everything to a file

- bin/pycbc_single_template
pycbc single template uses the wrong segment and this can lead to errors estimating its PSD.
> fix pycbc_single template

- bin/hdfcoinc/pycbc_make_coinc_search_workflow
- bin/hdfcoinc/pycbc_page_injtable
- pycbc/workflow/plotting.py
Adds a table of the missed injections, similar to the current found injections. Also put them in the injection subpage's respective wells.
> Injtable minor improvements

- bin/hdfcoinc/pycbc_coinc_statmap_inj
- pycbc/events/coinc.py
Tito, 
This should address the issues we were having this morning with the statmap_inj jobs not finishing.
> speed up statmap_inj so it doesn't stall out the workflow

- bin/hdfcoinc/pycbc_make_coinc_search_workflow
- bin/hdfcoinc/pycbc_page_injtable
- pycbc/workflow/plotting.py
> Revert "Injtable minor improvements"

- docs/install.rst
This one's a bit of a Ronseal.
> Add gracedb to install instructions

- bin/hdfcoinc/pycbc_make_coinc_search_workflow
> Revert "change dir before making workflow"

- bin/hdfcoinc/pycbc_make_coinc_search_workflow
- bin/hdfcoinc/pycbc_plot_singles_timefreq
- bin/minifollowups/pycbc_foreground_minifollowup
- bin/minifollowups/pycbc_injection_minifollowup
- bin/minifollowups/pycbc_page_injinfo
- bin/minifollowups/pycbc_plot_trigger_timeseries
- pycbc/workflow/minifollowups.py
- setup.py
Example result here,
https://sugar-jobs.phy.syr.edu/~ahnitz/projects/bigdog_rerun/plots/gw20/html/5._injections/5.2_followup-1INJ/
> add basic missed injection followup to workflow

- bin/hdfcoinc/pycbc_plot_singles_timefreq
* Add figure metadata
* Add ability to highlight a specific trigger ID (--interesting-trig)
* Enable setting origin of time axis (--center-time)
* Also show triggers coalescing past the time range of the plot
> Improvements to inspiral time-frequency plots

- bin/hdfcoinc/pycbc_page_coinc_snrchi
Add the choice of what is plotted for the color in the coinc snrchi plots
* effective distance
* mchirp
* eta
* weighted spin
> add more colorbar options to coinc snrchi

- pycbc/workflow/legacy_ihope.py
Hi Francesco,
This bug was accidentally introduced in the last pull request. It meant the bank veto argument was never passed to coh_PTF_inspiral!
Andrew
> Fixing bug in bank veto argument

- bin/hdfcoinc/pycbc_coinc_hdfinjfind
- bin/hdfcoinc/pycbc_make_coinc_search_workflow
- bin/hdfcoinc/pycbc_page_foundmissed
- bin/pycbc_optimal_snr
- pycbc/workflow/injection.py
- tools/run_travis.sh
Work in progress to enable calculating optimal SNRs of injections in the workflow.
> Enable optimal SNR calculation in workflow

- bin/hdfcoinc/pycbc_make_coinc_search_workflow
- bin/hdfcoinc/pycbc_page_injtable
- pycbc/workflow/plotting.py
See example here,
https://atlas1.atlas.aei.uni-hannover.de/~ahnitz/LSC/ahnitz/O1/plot_testing/gaussian/found_bns.html
> add more information to the full found injection table

- pycbc/filter/matchedfilter.py
use the old clustering methods. do not merge. wip
> use old clustering methods

- bin/hwinj/pycbc_generate_hwinj
Add units to ``pycbc_generate_hwinj`` help messages.
> Add units to pycbc_generate_hwinj help messages

- bin/pygrb/pycbc_make_offline_grb_workflow
- docs/workflow/pygrb.rst
- pycbc/workflow/segment.py
The first of these commits adds a bit more info on the possibility of single IFO running to the error messages the segment module gives if it finds there isn't enough data for a multi-IFO coherent search.
The second updates the doc page for PyGRB, which can be viewed here:
https://ldas-jobs.ligo.caltech.edu/~andrew.williamson/pygrb/pygrb_docs/workflow/pygrb.html
> Updating user info for PyGRB 

- bin/minifollowups/pycbc_foreground_minifollowup
- bin/minifollowups/pycbc_injection_minifollowup
- bin/minifollowups/pycbc_page_injinfo
- bin/minifollowups/pycbc_sngl_minifollowup
- bin/pycbc_single_template
- pycbc/workflow/minifollowups.py
* Use MultiDetOptionAction within minifollowup workflow generator
* Fix naming of injections so the missed ones start from 1, not blank
* Remove statmap input option from pycbc_single_template and corresponding workflow setup
> Mini cleanup

- bin/pycbc_optimal_snr
Adds a `--cores` argument which defaults to 1.
> Split calculation of optimal SNR over multiple cores

- bin/minifollowups/pycbc_page_coincinfo
- bin/minifollowups/pycbc_page_snglinfo
- pycbc/io/hdf.py
- pycbc/results/followup.py
- pycbc/results/table.py
for test result see the first event here : 
https://atlas3.atlas.aei.uni-hannover.de/~tdent/LSC/er8/tuning/er8b_6bins/7._result/7.3_bulk/ 
Most changes relative to the existing state are motivated by greater consistency with published notation
> Pretty formatting for single and coinc info, fix FAP units

- bin/hdfcoinc/pycbc_make_coinc_search_workflow
- bin/hdfcoinc/pycbc_plot_gating
- pycbc/strain.py
- pycbc/workflow/plotting.py
- setup.py
- tools/run_travis.sh
Example: https://sugar-jobs.phy.syr.edu/~tito/gated_times.html
Needs to be integrated into the workflow, opening for comments.
> Add script for plotting gated times

- bin/pygrb/pycbc_make_grb_summary_page
- bin/pygrb/pycbc_make_offline_grb_workflow
- pycbc/workflow/postprocessing_cohptf.py
Hi Steve,
These are fixes for running without injections, and for placing the results pages in a consistent place (with _CLOSED and _OPEN folder suffixes).
Andrew
> PyGRB injection and result page bugfixes

- bin/pycbc_submit_dax
Apparently [ is more portable than [[
http://stackoverflow.com/questions/669452/is-preferable-over-in-bash-scripts
> Fix the shell script tests in pycbc_submit_dax

- pycbc/waveform/waveform.py
- pycbc/workflow/core.py
- pycbc/workflow/pegasus_workflow.py
- pycbc/workflow/segment.py
This removes the verbatim_executable option and just decides for you if the executable will need to be transferred.
> Execute now fix

- bin/hdfcoinc/pycbc_page_foundmissed
- bin/hdfcoinc/pycbc_page_recovery
This will require an ini file change for f/m jobs, but I think it must be changed anyway so that we can check our injection distance limits.  Otherwise making the parameter names consistent with plot_singles_vs_params.
> Plot tweaks

- pycbc/workflow/plotting.py
I'm not sure this is the right solution, but it might help with #505.
> plot jobs set priority 100

- pycbc/workflow/core.py
There was a typo in #546 that needs fixing
> Fix typo in #546

- tools/run_travis.sh
Please let's wait for tests before merging. Anything I should add?
> Add more executables to travis tests

- bin/minifollowups/pycbc_foreground_minifollowup
- bin/minifollowups/pycbc_injection_minifollowup
- pycbc/workflow/minifollowups.py
**At the moment our workflow generator is broken, use the release**
#546 is causing some failures with the minifollowup plots. After discussion with Alex we think this is the fault of the minifollowups setup. The fix is below for Alex to test:
> Fix how minifups set their ifo property

- bin/pycbc_upload_xml_to_gracedb
> Upload PSDs to GraceDB

- bin/pycbc_upload_xml_to_gracedb
The really important commit is the last one that truncates frequencies below the low frequency cutoff and restores the dynamic range factor.
> pycbc_upload_xml_to_gracedb cleanup

- bin/pycbc_randomize_inj_dist_by_optsnr
- setup.py
Script that reads the optimal SNR from an xml file and re-draws injection distances based on the optimal snr.
Histograms here https://www.atlas.aei.uni-hannover.de/~miriam.cabero/LSC/tests/edit_xml/
> New program to re-weight injections by optimal SNR

- bin/pygrb/pycbc_make_offline_grb_workflow
- pycbc/workflow/segment.py
This commit is intended to fix #563
> Moving GRB segment plot calls to workflow script

- bin/hdfcoinc/pycbc_combine_statmap
- bin/hdfcoinc/pycbc_distribute_background_bins
- bin/hdfcoinc/pycbc_make_coinc_search_workflow
- bin/hdfcoinc/pycbc_page_coinc_snrchi
- bin/hdfcoinc/pycbc_page_foreground
- bin/hdfcoinc/pycbc_page_injtable
- bin/hdfcoinc/pycbc_page_segplot
- bin/hdfcoinc/pycbc_page_segtable
- bin/hdfcoinc/pycbc_page_vetotable
- bin/hdfcoinc/pycbc_plot_gating
- bin/hdfcoinc/pycbc_plot_psd_file
- bin/hdfcoinc/pycbc_plot_singles_timefreq
- bin/hdfcoinc/pycbc_plot_singles_vs_params
- bin/minifollowups/pycbc_plot_trigger_timeseries
- bin/pycbc_make_html_page
- bin/pycbc_optimal_snr
- bin/pycbc_submit_dax
- pycbc/results/layout.py
- pycbc/results/versioning.py
- pycbc/workflow/segment.py
This pull requests adds a new section to the results page to store data about the workflow.
> Add workflow section to results page with metadata for review

- pycbc/workflow/core.py
Addresses https://github.com/ligo-cbc/pycbc/issues/579
I've also cleaned up the URL handling a bit.
There's one subtlety to this change.  In the current code
* http URLs are marked "local"
* gsiftp URLs are marked "nonlocal"
* Executables needed at workflow-generation time such as segment_query are expected to be local.
In order to treat all non-file URLs uniformly they all have to be nonlocal.  The change at line 444 allows for this.
I have tested this by generating and starting a workflow with file URLs and another with gsiftp URLs and verified that in both cases the workflow generated correctly and ran to the point where inspiral jobs started running.
> Allow executables to come from a http URL as well as a gsiftp URL

- bin/hdfcoinc/pycbc_make_coinc_search_workflow
- pycbc/workflow/segment.py
Obsoletes https://github.com/ligo-cbc/pycbc/pull/580
> Fix the items in the available segments table

- pycbc/workflow/pegasus_files/comet-site-template.xml
Addresses https://github.com/ligo-cbc/pycbc/issues/578
> Site template for SDSC/Comet

- pycbc/workflow/coincidence.py
- pycbc/workflow/segment.py
* Remove no longer needed lines for proxy checking
* Better parse the background bin command lines so that whitespace doesn't end up getting counted as  a bin
> segment proxy fix, and background bin command line parsing fix

- tools/static/cant_be_built
- tools/static/needs_full_build
In preparing the v1.2.6 bundles I found a few new programs that needed special handling.
> Configuration for programs added recently

- bin/hdfcoinc/pycbc_coinc_findtrigs
- bin/hdfcoinc/pycbc_coinc_mergetrigs
- bin/hdfcoinc/pycbc_coinc_statmap
- pycbc/io/hdf.py
Do better compression on hdf intermediate files.
> Compress intermediate HDF5 files to save disk space

- bin/hdfcoinc/pycbc_page_snrifar
- bin/hdfcoinc/pycbc_page_snrratehist
- setup.py
Update snr ifar plots
* add trials factor option
* add non-cumulative plot option
* go from two sided to one side sigma shading
> Fixes to plots showing histograms of rate vs signal significance

- bin/hdfcoinc/pycbc_page_snrifar
I tested by artifially removing the right key.
Example output
http://sugar-jobs.phy.syr.edu/~ahnitz/nffar.png
http://sugar-jobs.phy.syr.edu/~ahnitz/nfcum.png
> allow for no foreground triggers

- bin/hdfcoinc/pycbc_make_coinc_search_workflow
- bin/pycbc_submit_dax
- pycbc/workflow/coincidence.py
Fixes https://github.com/ligo-cbc/pycbc/issues/590 and https://github.com/ligo-cbc/pycbc/issues/606
> Result page cleanup

- tools/static/needs_full_build
I'll add to this commit if there are further changes needed for bundling 1.3.0
> pycbc_page_snrratehist needs full build

- bin/hdfcoinc/pycbc_make_coinc_search_workflow
- bin/hdfcoinc/pycbc_page_snrifar
- bin/hdfcoinc/pycbc_page_snrratehist
- pycbc/workflow/plotting.py
This implements the pull request in https://github.com/ligo-cbc/pycbc/pull/615 but adds a couple of catches for edge cases where there are no triggers in the data due to small test runs.
> add more significance plots to result pages

- pycbc/results/legacy_grb.py
Hi Steve,
This fixes the segment plots so they show correctly for the few edge-case single IFO runs.
Cheers,
Andrew
> Fixing bug in GRB segment plots for edge cases

- bin/minifollowups/pycbc_page_injinfo
Caught a wrong index in the followup tables.
> Fixed typo in minifollowup table

- bin/pygrb/pycbc_make_offline_grb_workflow
- pycbc/results/legacy_grb.py
The code will exit gracefully in the event of there being no science segments, and will make the segments plot to show this.
> PyGRB segment plots now always made

- docs/workflow/pycbc_make_coinc_search_workflow.rst
Addresses https://github.com/ligo-cbc/pycbc/issues/560
It is possible this will need further changes, depending on the resolution of the subdax staging problem.  However, these instructions are sufficient to run a workflow up to the minifollowup stage.
> Add documentation for running under OSG

- bin/hdfcoinc/pycbc_coinc_hdfinjfind
- bin/hdfcoinc/pycbc_page_coinc_snrchi
- bin/hdfcoinc/pycbc_page_foundmissed
Redshift recording and plotting are needed for the Rates injections sets
> Willinj - add redshift to injection finding and plotting and clean up some variable names

- bin/hdfcoinc/pycbc_plot_singles_timefreq
Examples:
https://atlas1.atlas.aei.uni-hannover.de/~tito/LSC/o1/H1_1136171240.png
https://atlas1.atlas.aei.uni-hannover.de/~tito/LSC/o1/H1_1136632103.png
> Display gates in plot_singles_timefreq

- bin/hdfcoinc/pycbc_foreground_censor
This should coalesce the segments before union-ing or adding them together.
> Segments must be coalesced before adding/union

- docs/release.rst
This documents the procedure for building bundled executables.
> Static release docs

- bin/hdfcoinc/pycbc_page_vetotable
> Remove unused import in pycbc_page_vetotable

- pycbc/filter/matchedfilter.py
As I discussed with Alex at Hannover, I want to start merging the zero-padding functionality onto master. This will be done in stages. First a set of patches that are just updates/bug fixes that are on that branch but not really related to zero padding.
This one is needed to [try to] fix the hierarchical matched-filtering path, that was broken by optimisation changes to the main matched-filter path. This just moves some stuff around and is tested to run fine for the normal case. The hierarchical matched-filtering path still needs some work, we need to come back to that.
> Update arguments for heirarchical mfilter

- bin/hdfcoinc/pycbc_page_ifar
> Add coalesce to segmentlists in pycbc_page_ifar

- bin/pygrb/pycbc_make_offline_grb_workflow
- pycbc/workflow/core.py
- pycbc/workflow/segment.py
Hi @spxiwh 
I've tested this change, designed to fix #725 
If you could look over this and check this is acceptable that would be great.
Cheers,
Andrew
> Generate PyGRB workflow with new segment treatment

- pycbc/waveform/bank.py
Add an alternate filterbank class that dynamically figures out the right filter length size for each template, assuming it has a length estimator.
> add alternate filterbank class

- pycbc/filter/resample.py
- test/test_resample.py
Add an explicity fir lowpass / highpass filter. Speed up application of the filtering by switching to an FFT approach. This duplicates the functionality of the scipy.lfilter function.
> more filtering

- docs/release.rst
Added notes and removed some incorrect code.
> Changes to the instructions for Creating Releases of PyCBC.

- bin/hdfcoinc/pycbc_page_sensitivity
Made a fix to the caption that is simpler and better worded.
> Ian's caption suggestion

- pycbc/strain.py
Speed up autogating by working on a downsampled version of the strain, padding it to a power-of-2 length and avoiding copies of long arrays. On my laptop this gets autogating to under 10 s (a big part of which is resampling) from several tens of seconds.
For a before/after check, compare the full_data of these runs:
* https://www.atlas.aei.uni-hannover.de/~tito/LSC/o1/imbh/o1-imbh-chunk123-c02-phenomd-2/
* https://www.atlas.aei.uni-hannover.de/~tito/LSC/o1/imbh/speedup_autogating_test/
Note that the list of gates will not be identical because of the downsampled strain. I verified that the few gates not present in both runs are relatively weak glitches which probably are around the autogating threshold.
> Faster autogating

- pycbc/workflow/pegasus_files/osg-site-template.xml
Added a line in the OSG site catalog to use the XSEDE sites.
> Inserted the line to add XSEDE sites to the OSG site catalog

- pycbc/strain.py
* Do not require the input time series to span an integer number of PSD estimation segments. The previous behavior was effectively constraining the length of a job in an unclear way.
* Remove tapered portion of input time series from PSD estimation.
* Add a docstring to detect_loud_glitches().
Need to test, please hold on merging.
> Improve autogating PSD estimation and documentation

- bin/pycbc_inspiral
- pycbc/waveform/bank.py
- pycbc/waveform/waveform.py
Simpler way to add in the variable flow. This matches I think the implementation that Ian wrote for lalinspiral. 
Test workflow will appear
https://www.atlas.aei.uni-hannover.de/~ahnitz/LSC/ahnitz/projects/code_testing/q1/flow/html
> Variable flow

- pycbc/types/array.py
- pycbc/types/array_cpu.py
- pycbc/types/array_cuda.py
- test/test_array.py
Hi Alex,
We spoke at the APS meeting about speeding up some of the precessing chi-squared calculation where a reasonably large number of "multiply array by constant and add a second array" operations are done. You suggested that this could be sped up using weave.
The following patch does this, although there are some questions in the pull request about things that I don't yet understand. I also include a test suite in test_array.py for this new function.
Here is a call graph of the precessing search benchmark run before doing this operation (so multiply and add operations are done using numpy arithmetic like a = b*c + d.)
https://www.atlas.aei.uni-hannover.de/~spxiwh/LSC/aLIGO/O1/precessing/benchmarks/full_data_afteropt1.png
Note the time in __mul__ and __add__ within the chisq.values …
> Add multiply_and_add method

- build_bundle_env.sh
- docs/release.rst
Script for building bundle env and updated instruction for building pycbc bundles
> Updated documentation for creating bundles

- bin/pygrb/pycbc_make_grb_summary_page
- pycbc/results/legacy_grb.py
Hi @sfairhur ,
These are a few minor tweaks to the result page we've spoken about recently. For an example see
[here](https://geo2.arcca.cf.ac.uk/~c1239174/LVC/ER8/pygrb/GRB150919A/GRB150919A_CLOSED_FVCRZH8I/summary.html).
Andrew
> Making small changes to the PyGRB result page.

- pycbc/filter/matchedfilter.py
More precessing code ... some actual code now though!
This is the MatchedFilterSkyMaxControl class (and associated functions) that does the majority of the precessing matched filtering. It's modelled off of the original class, but in many places two filters are needed, and there is some precession-specific stuff.
> Add MatchedFilterSkyMaxControl class

- pycbc/vetoes/chisq.py
Precessing stuff again.
This is the SingleDetSkyMaxPowerChisq class. This is still not ideal, and unequal-power bins approach *might* be better. But like this, the chisq takes about 20-30% of full runtime, so not too terrible! With a lower SNR threshold this will get worse though.
> Add SingleDetSkyMaxPowerChisq class

- pycbc/filter/matchedfilter.py
- pycbc/types/frequencyseries.py
As discussed in chat. Edit the check delta_f = delta_f routine to use nose.tools "almost equal" function.
> Check delta_f *almost* equal

- tools/einsteinathome/progress.c
- fixed stupid typo in command-line parsing
- added 'help' usage messga ('-h')
- added 'copy' feature ('-c')
- finish parsing on SIGTERM (on Linux)
> E@H: fixes and improvements to progress.c

- bin/inference/pycbc_mcmc
- examples/inference/inference.ini
- examples/inference/run_pycbc_mcmc.sh
- setup.py
This PR is not ready to merge.
Adds an executable to perform the MCMC.
> Add initial version of MCMC executable

- bin/pygrb/pycbc_make_offline_grb_workflow
- pycbc/workflow/grb_utils.py
- pycbc/workflow/jobsetup.py
- pycbc/workflow/legacy_ihope.py
Hi @sfairhur ,
This change will allow the workflow to retreive IPN sky box files from the GitLab repo at runtime if the urls are given in the arguments:
[workflow-inspiral]
ipn-search-points = <search-points-url>
[workflow-injections]
ipn-sim-points = <sim-points-url>
The search points are then passed to `lalapps_coh_PTF_inspiral --sky-positions-file <search-points-file>`
The sim points are passed to `lalapps_inspinj --ipn-file <sim-points-file>`
Cheers,
Andrew
> Adding IPN sky boxes to PyGRB workflow

- pycbc/waveform/compress.py
- pycbc/waveform/waveform.py
At code to get waveforms at discrete sets of frequency points and to attempt reconstruct it. Warning, that the reconstruction code does not work in all cases at this point.
> Generate waveforms at unequally sampled frequencies

- pycbc/waveform/bank.py
This depends on #836. Must be merged after that.
Here are precessing search changes to the bank module:
* Add a FilterBankSkyMax class
* Ensure that ttotal and template_duration take *some* value in cases that they are not known to avoid the XML output code barfing ... This isn't needed for the precessing code, but should be considered a general-case bugfix.
> Precessing changes to the bank module

- pycbc/io/record.py
This adds a ``_virtualfields`` attribute to FieldArray to keep track of properties that are added that act on fields. A ``add_virtualfields`` method is also added, which is basically just a wrapper of add_properties. A fields property is added which returns the names of actual fields and field names. This is checked by ``__contains__``, making interaction with FieldArrays more like dictionaries.
Also, this temporarily comments out the dict comprehension for 2.6 compatibility.
> Add virtual fields to FieldArray and make 'in' check for field names

- pycbc/waveform/bank.py
- pycbc/workflow/jobsetup.py
I forgot to add the change where skymax gets added to jobsetup.py
> Adding skymax to jobsetup.py

- bin/hdfcoinc/pycbc_plot_psd_file
- bin/inference/pycbc_make_inference_workflow
- bin/inference/pycbc_mcmc
- pycbc/io/mcmc.py
Adds a plot of the PSD to the MCMC page, eg.: https://sugar-jobs.phy.syr.edu/~cbiwer/tmp/tmp_workflow_5/
> Add PSD to MCMC output page

- pycbc/workflow/mcmcfollowups.py
Does as title says.
Example page is here: https://sugar-jobs.phy.syr.edu/~cbiwer/tmp/tmp_workflow_6/
With #885 the single-parameter posterior plots will look nicer but this PR does not depend on it.
> Add posterior plot for single parameter to output MCMC HTML page

- examples/inference/inference.ini
Updates the MCMC example for the recent changes to the time shifting and multi-parameter priors.
> Update example config file inference.ini.

- pycbc/frame.py
Split off a separate function in the frame reading to turn a set of locations into a frame cache file.
> modularize frame reading 

- pycbc/frame.py
Add a class which acts a buffer of frame information. It can be populated by a list of frame files.
> add DataBuffer class

- pycbc/inference/prior.py
This PR adds a Gaussian prior distribution.
An example:
```
from pycbc.inference import Guassian
g = Gaussian(variable_args=["mass1", "mass2"],
low=[-numpy.inf, 30],
high=[numpy.inf, 40],
mean=[5, 35],
var=[1, 1])
print g.rvs(size=500000)
```
> Add a gaussian prior distribution

- pycbc/inference/prior.py
> Force __call__ = logpdf for Gaussian distribution

- pycbc/__init__.py
- pycbc/scheme.py
Reverts ligo-cbc/pycbc#927
check_output is not supported in python 2.7
> Revert "Increase speed of GPU code"

- pycbc/__init__.py
- pycbc/scheme.py
New pull request that uses popen for python 2.6 compatibility
> Improve speed of GPU code

- pycbc/inference/sampler.py
> Switch to ASCII character in docstring

- pycbc/workflow/inference_followups.py
Fix to inference workflow from #940.
> Change --variable-args to --parameters.

- bin/inference/pycbc_inference
- pycbc/io/inference_hdf.py
Puts the bit of code that reads the distributions from the inference configuration file into a function.
> Put distribution reading in a function

- bin/inference/pycbc_inference_plot_samples
> Fix call to read_samples_from_walkers to use the index of the walker

- pycbc/workflow/plotting.py
As title says. And add the line
```
tags = [] if tags == None else tags
```
> Change tags=[] to tags=None in pycbc.workflow.plotting

- bin/inference/pycbc_inference
- bin/inference/pycbc_inference_plot_acf
- bin/inference/pycbc_inference_plot_acl
- bin/inference/pycbc_inference_plot_samples
- pycbc/inference/option_utils.py
- pycbc/io/inference_hdf.py
> Rename InferenceFile.read_samples_from_walkers to InferenceFile.read_samples

- pycbc/strain.py
Add an option to strain.py to generate a fake strain from a given ASD file.
> Strain input psd

- bin/inference/pycbc_inference_plot_acl
> Remove latex_to_html call in pycbc_inference_plot_acl

- pycbc/filter/autocorrelation.py
> Use pycbc.filter.correlate instead of numpy.correlate in ACF

- pycbc/fft/fft_callback.py
- pycbc/io/record.py
- pycbc/results/metadata.py
- pycbc/tmpltbank/bank_output_utils.py
- pycbc/workflow/coincidence.py
- pycbc/workflow/configuration.py
- pycbc/workflow/core.py
- pycbc/workflow/gatefiles.py
- pycbc/workflow/grb_utils.py
- pycbc/workflow/injection.py
- pycbc/workflow/jobsetup.py
- pycbc/workflow/legacy_ihope.py
- pycbc/workflow/matched_filter.py
- pycbc/workflow/postprocessing_cohptf.py
- pycbc/workflow/psdfiles.py
- pycbc/workflow/segment.py
- pycbc/workflow/splittable.py
- pycbc/workflow/tmpltbank.py
- test/fft_base.py
- tools/static/runtime-scipy.py
This pull request automatically fixes all occurrences of the following issue:
Issue type: [Avoid mutable default arguments](https://www.quantifiedcode.com/app/issue_class/3P0qV6OB)
Issue details: [https://www.quantifiedcode.com/app/project/gh:ligo-cbc:pycbc?groups=code_patterns/%3A3P0qV6OB](https://www.quantifiedcode.com/app/project/gh:ligo-cbc:pycbc?groups=code_patterns/%3A3P0qV6OB)
To adjust the commit message or the actual code changes, just [rebase](https://git-scm.com/docs/git-rebase) or [cherry-pick](https://git-scm.com/docs/git-cherry-pick) the commits.
For questions or feedback reach out to cody@quantifiedcode.com.
Legal note: We won't claim any copyrights on the code changes.
Cheers,
[Cody - Your code quality bot](https://www.quantifiedcode.com/cody)
> Fix "Avoid mutable default arguments" issue

- pycbc/inference/likelihood.py
- pycbc/inference/prior.py
- pycbc/io/record.py
This pull request automatically fixes all occurrences of the following issue:
Issue type: [Consider an iterator instead of materializing the list](https://www.quantifiedcode.com/app/issue_class/53lnAzfW)
Issue details: [https://www.quantifiedcode.com/app/project/gh:ligo-cbc:pycbc?groups=code_patterns/%3A53lnAzfW](https://www.quantifiedcode.com/app/project/gh:ligo-cbc:pycbc?groups=code_patterns/%3A53lnAzfW)
To adjust the commit message or the actual code changes, just [rebase](https://git-scm.com/docs/git-rebase) or [cherry-pick](https://git-scm.com/docs/git-cherry-pick) the commits.
For questions or feedback reach out to cody@quantifiedcode.com.
Legal note: We won't claim any copyrights on the code changes.
Cheers,
[Cody - Your code quality bot](https://www.quantifiedcode.com/cody)
> Fix "Consider an iterator instead of materializing the list" issue

- docs/workflow/pycbc_make_inference_workflow.rst
Add an example of an ini file for ringdown parameter estimation
> Add ringdown configuration file to inference documentation

- docs/workflow/pycbc_make_inference_workflow.rst
> Update inference workflow example for GW150914.

- bin/hdfcoinc/pycbc_coinc_findtrigs
- pycbc/events/stat.py
Also, add some basic documentation to the classes!
> move statistic classes from pycbc_coinc_findtrigs into the library

- bin/pycbc_geom_aligned_bank
- bin/workflows/pycbc_create_sbank_workflow
- pycbc/workflow/core.py
- pycbc/workflow/pegasus_workflow.py
A few more template-bank related workflow changes.
* Fix missing file_input_options in pycbc_geom_aligned_bank
* Add functionality for changing tags in Executables (basically designed as a start to trying to limit the number of unique Executable classes that are used for the same actual executable).
* Limit the number of Executables in sbank workflows so that some of the dashboard plots are actually readable.
> More tmpltbank workflow changes

- pycbc/frame.py
This updates the online frame reading class, based on what I leanred from ER9.
1) option for faster cache update by guessing the next frame file name 
2) fix bug in updating the status cache
3) Allow signed int for the status buffer 
4) fix bug in the null advance function to increment the next frame file requested
> update the online frame freading class

- pycbc/strain.py
* add some options to abort based on the PSD changing rapidly
* properly pass the timeout options to the frame reading code
> update strain conditioning

- pycbc/waveform/bank.py
This fixes some formatting issues in pycbc/waveform/bank.py and adds a few documentation strings.
> bank cleanup

- bin/inference/pycbc_inference
- pycbc/inference/sampler.py
- pycbc/io/inference_hdf.py
This pull request is to write the natural logarithm of the likelihood in the result hdf files from pycbc_inference. The likelihood can then be used to compute the Bayes factor or as a sanity check in suspicious PE runs.
> Write ln(likelihood) in inference result files

- docs/resources/uberbank_example1.ini
- docs/tmpltbank.rst
Configuration tuned for a bank equivalent to the O1 uberbank (slightly smaller, similar effectualness).
> Update example config file for uberbank workflow

- tools/install_travis.sh
Needed to make #1067 pass its tests.
> Bump Travis lalsuite to include Leo's swig PSD fixes

- pycbc/waveform/utils.py
- pycbc/workflow/core.py
Fixing a couple of errors I stumbled upon. One triggers when trying to load a segment XML file with empty segment summary table. The other is a typo in an error message :)
> Fix segfile and taper errors

- pycbc/psd/analytical.py
This patch provides access to a wider range of LALSimulation PSDs, including, for example, `XLALSimNoisePSDaLIGOLateHighSensitivityP1200087`.
> Support more LALSimulation PSDs, including sampled ones

- install_pycbc.sh
The checksums on the ROM data need updating, so comment this out for the moment.
> Fix the issues with the install script so that it works with the current code base

- pycbc/waveform/generator.py
> Add pregenerator function for mchirp q to mass1 mass2.

- pycbc/waveform/compress.py
When a compressed bank is loaded, there is the option to put off loading the sample frequencies, amplitude, and phases from file until they are actually needed. The problem with this is if the hdf file is closed in the meantime, you'll get an error when you try to access any of these attributes. This patch fixes this by storing the file names and group location of the data sets when initializing the compressed waveform class. If the file is closed when trying to access these arrays, the file will be temporarily opened in order to get the data.
@soumide1102 @duncan-brown This patch may cause merge conflicts with your patch to allow for two different frequency vectors. Making that patch work with this should be pretty straight forward though.
Putting on hold as I created this off the branch …
> Decompress from closed files

- pycbc/waveform/bank.py
Make sure the sigma cache is two-way associative. Does not affect the offline search, but the online search constantly changes the psd and templates go in and out of memory. The cache can be fooled if another template has made an association with the same (re-used) id.
> fix caching again

- bin/pygrb/pycbc_make_offline_grb_workflow
- pycbc/workflow/grb_utils.py
- pycbc/workflow/jobsetup.py
This is a small change to improve the way the code handles IPN sky points, fixing a small bug. Previously, if you didn't feed in a sim points file for injections it wouldn't like it, even if you weren't doing injections.
> Improving handling of IPN sky points files

- pycbc/io/live.py
This adds a class to create the needed xml file for gracedb upload for pycbc live and prepare the submission, including tagging as a hardware injection and uploading the relevant PSD.
> add gracedb submit class

- pycbc/strain.py
* Add the explicit choice of what defines valid analysis time. (HOFT_OK + SCIENCE_INTENT , etc). 
* Add stub for a dq status channel alongside the current status channel.
> add explicit analysis flags options

- pycbc/filter/matchedfilter.py
- pycbc/filter/matchedfilter_cpu.py
- pycbc/types/array.py
- pycbc/types/array_cpu.py
- test/test_array.py
- test/test_frequencyseries.py
- test/test_timeseries.py
This adds some inline versions of the inner product (for real types) and makes some tweaks to the batch correlation class to improve the performance on multiple cores. Also, add required data types to the pycbc allowed types. This is needed for status information which is stored as integers (of various types).
> performance tweaks of the batch correlate and inner product functions. 

- pycbc/inference/distributions.py
Removes properties already set by ``_BoundedDist`` in the ``Gaussian`` distribution.
> Use self.params and self.bounds from _BoundedDist for Gaussian.

- bin/hdfcoinc/pycbc_page_foreground
- bin/hdfcoinc/pycbc_page_snrifar
- bin/hdfcoinc/pycbc_plot_throughput
- pycbc/events/stat.py
also a couple of improvements to plot throughput a la PEP8 and removing unneeded imports
> Fix fitstat

- pycbc/workflow/datafind.py
The error messages for the case where segments were expected but frames corresponding to them were not found on the cluster were confusing.
> Segment errmsg

- pycbc/events/stat.py
Reverts ligo-cbc/pycbc#1155 (it introduced bugs as detected posthumously by landscape)
> Revert "Fix fitstat"

- pycbc/events/stat.py
* Makes the stat class a bit more legible code wise
* Allows some of the dtypes to be queried by higher level codes
> add dtypes to stat classes

- pycbc/events/coinc.py
* Add the classed required for pycbc live to calculate its rolling background
> add the coinc class

- pycbc/pnutils.py
Add the hybrid energy from https://arxiv.org/pdf/1602.03134.pdf to pnutils and compute the velocity and the frequency of the hybrid MECO
> Function to get the frequency of the hybrid MECO

- README.md
- docs/workflow/pycbc_make_inference_workflow.rst
Corrected a typo in the simple configuration file for parameter estimation. Gave recommendations for environment variables used in pycbc_make_inference_workflow.
> Documentation correction for pycbc_make_inference_workflow

- bin/hdfcoinc/pycbc_page_snrifar
> handle case where sigma labels would be below recorded background

- docs/install_lalsuite.rst
- setup.py
Also update install instructions to point to GitHub lalsuite.
> Tag for 1.5.6 release

- bin/hwinj/pycbc_generate_hwinj
- examples/cal/foton_filter_esd_saturation/pycbc_check_pcal_saturation.sh
A request from John, whose trying to generate the injections now.
> Use multi-IFO options for hardware injection generation executable

- bin/hdfcoinc/pycbc_fit_sngls_binned
- bin/hdfcoinc/pycbc_fit_sngls_by_template
- bin/hdfcoinc/pycbc_fit_sngls_over_param
- bin/pycbc_fit_sngl_trigs
- pycbc/events/coinc.py
- pycbc/pnutils.py
- pycbc/waveform/waveform.py
- pycbc/workflow/coincidence.py
Addresses issue #1273 
These changes are likely required to use the template duration (or some other quantity stored in trigger files) as noise distribution parameter for the background fitting stat
> Durationstuff

- pycbc/waveform/parameters.py
- pycbc/waveform/spa_tmplt.py
- pycbc/waveform/waveform.py
- tools/install_travis.sh
This include @sturani's functionality from https://github.com/ligo-cbc/pycbc/pull/1174 and also updates the travis build to use a version of lalsuite that has the new changes.
> Compatibility with new lalsimulation waveform interface

- bin/hdfcoinc/pycbc_coinc_mergetrigs
`pycbc_coinc_mergetrigs` calls `data = h5py.File(filename, 'r')`. If this fails, it will now print the name of the offending file.
> pycbc_coinc_mergetrigs should report which open failed

- docs/inference.rst
also added OMP_NUM_THREADS=1 before calling pycbc_inference
> update inferece doc with PSD_INVERSE_LENGTH

- bin/plotting/pycbc_plot_waveform
> Added caption and corrected labels of waveform plotting code

- bin/inference/pycbc_inference_plot_acceptance_rate
> Add thin-end option to plot_acceptance_rate

- bin/pycbc_single_template
Fixes #1311, removes some unused imports and marks an arg required.
> Improve edge case handling in pycbc_single_template

- pycbc/waveform/waveform.py
Fix function when using numrel_data in new lalsimulation waveform interface
> fix numrel_data LALDict entry in waveform

- .landscape.yml
I think landscape is failing with an error parsing the [valid] landscape config file. It seems to run when turning off the test documention option ... So let's see if this works on origin as a pull request.
> This might fix landscape

- bin/hwinj/pycbc_generate_hwinj
- bin/inference/pycbc_inference
- bin/pycbc_multi_inspiral
- pycbc/events/events.py
- pycbc/psd/__init__.py
- pycbc/strain.py
This commit fixed some code incompatibilities and allowed `pycbc_multi_inspiral` to run to completion (in its state a few months back). Additional changes may need to be made after recent pycbc development, so consider this a jumping off point.
DO NOT MERGE!
> Getting pycbc_multi_inspiral to run to completion

- bin/hdfcoinc/pycbc_fit_sngls_binned
> more help for human beings to understand binned histogram

- docs/frame.rst
Adds an example to the documentation how to write a frame file.
> Add frame writing example.

- docs/install.rst
> Use dqsegdb from official repo

- README.md
The badge won't display properly without this anymore.
> Update pypi badge to https.

- pycbc/vetoes/chisq.py
This doesn't cause a problem for the regular workflows, but the caching needs to be a bit more careful for pycbc live as the psds are continually regenerated.
> sanitize chisq bin caching

- pycbc/waveform/bank.py
This merges the functionality from the pycbc_live_dev branch back into master to enable pycbc live to work with variable flow banks.
> update live bank to allow variable flow

- bin/inference/pycbc_inference_plot_prior
As title says. Workflow hasn't been run in awhile and this is to get @stevereyes01 on his way.
EDIT: has -> hasn't
> Update to new location of distributions dict in pycbc_plot_inference_prior

- bin/inference/pycbc_inference
- pycbc/io/inference_hdf.py
> Write command line to InferenceFile

- bin/pygrb/pycbc_make_offline_grb_workflow
- pycbc/workflow/grb_utils.py
- pycbc/workflow/jobsetup.py
These changes enable autogating in the PyGRB workflow.
> Enabling autogating in PyGRB

- pycbc/io/live.py
Add the snr upload capability requested by Leo and implemented by Tito.
Also add option to create sngl trigger upload instances
> add snr upload capability

- pycbc/frame.py
- pycbc/strain.py
This adds support for the dq vector in pycbc live and moves the hardware injection check into the strain class.
> add dq vector support

- bin/hdfcoinc/pycbc_coinc_findtrigs
- bin/hdfcoinc/pycbc_fit_sngls_binned
- bin/hdfcoinc/pycbc_fit_sngls_by_template
- bin/hdfcoinc/pycbc_page_snrifar
I think this works and does what the title says, will test on Hunters files to make sure.
> allow fit sngls by template to accept multiple veto files

- pycbc/events/coinc.py
- pycbc/events/single.py
* Moves argument handling to from_cli / insert arg type convention for background estimation in pycbc live
* Add simple class for single detector triggers
Depends on #1406
> Unify background argument handling in pycbc live 

- pycbc/waveform/waveform.py
Update the pycbc sequence interface for the new lalsimulation format. Consolidate where the dictionary parameters are checked.
> fix sequence interface

- bin/pycbc_inspiral_skymax
- pycbc/waveform/bank.py
Some minor fixes to make the precessing inspiral executable work with the current bank classes and the new sigmasq caching.
> Some fixes to the precessing inspiral's bank class

- docs/workflow/pycbc_make_coinc_search_workflow.rst
Fixes https://github.com/ligo-cbc/pycbc/issues/1424
> Update osg instructions

- docs/building_bundled_executables.rst
- docs/index.rst
- docs/install.rst
- docs/using_pyinstaller_binaries.rst
- docs/workflow/pycbc_make_coinc_search_workflow.rst
And rename the files to have better names.
> Add the E@H install instructions to the index

- bin/pycbc_inspiral
- pycbc/vetoes/sgchisq.py
This splits off just the changes to add the sine-Gaussian chisq to pycbc_inspiral.
> add sine-Gaussian chisq class, update pycbc_inspiral

- bin/pycbc_inspiral
- pycbc/vetoes/sgchisq.py
This adds more comments to the sine-gaussian chisq class, and renames the variable they save to to sg_chisq, which makes more sense that lat_chisq.
> more comments on sgchisq class

- bin/hdfcoinc/pycbc_fit_sngls_binned
- bin/hdfcoinc/pycbc_fit_sngls_by_template
- bin/hdfcoinc/pycbc_plot_singles_vs_params
- pycbc/events/events.py
- pycbc/events/stat.py
- pycbc/io/hdf.py
providing code for reference. Have a look and comment.
> chisq of sine gaussians

- bin/pycbc_submit_dax
Use the new ``-p`` option to make a long-lived RFC compliant proxy.
> Make an rfc compliant proxy

- bin/pycbc_condition_strain
> Fixing bug in pycbc_condition_strain

- tools/run_travis.sh
And one last test of Travis on the main repo before I declare success...
> Enable fixed prog and send stderr of find to /dev/null

- tools/einsteinathome/pycbc_build_eah.sh
> E@H build: fix FFTW compilation

- examples/filter/pass.py
A student found this bug in the examples. Here's a fix.
> fix bug in documentation example

- docs/gw150914.rst
- docs/index.rst
- examples/gw150914/gw150914_h1_snr.py
- examples/gw150914/gw150914_shape.py
Add some simple singal processing examples with GW150914 to our examples page.
> add gw150914 examples to the documentation page

- tools/einsteinathome/pycbc_build_eah.sh
- tools/install_travis.sh
Fixes:
```
--2017-04-07 17:03:40--  https://www.lsc-group.phys.uwm.edu/daswg/download/software/source/metaio-8.3.0.tar.gz
Resolving www.lsc-group.phys.uwm.edu (www.lsc-group.phys.uwm.edu)... 129.89.61.49
Connecting to www.lsc-group.phys.uwm.edu (www.lsc-group.phys.uwm.edu)|129.89.61.49|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-04-07 17:03:40 ERROR 404: Not Found.
```
> Switch from daswg to software.ligo.org

- bin/inference/pycbc_inference_plot_prior
As title says.
@n-wbrown This should fix your issue.
> Fix namespace conflict in pycbc_inference_plot_prior

- .travis.yml
- tools/docker_build_dist.sh
- tools/einsteinathome/pycbc_build_eah.sh
This also fixes a bug with the deployment that is breaking Travis on master.
> Add mkl libraries to Travis bundle

- tools/docker_build_dist.sh
Travis is complaining that there is too much output from rsync, so suppress it with ``-q``.
> Suppress output from scp and rsync

- pycbc/types/array.py
- pycbc/types/frequencyseries.py
- pycbc/types/timeseries.py
I'm removing the error that prevents using the step size. It seems to now work in pycuda, so no reason to block it. 
Fixes #1542
> support step in slicing

- docs/inference.rst
- docs/workflow/pycbc_make_inference_workflow.rst
Updates ``inclination`` prior in documentation examples.
> Update prior in documentation

- bin/workflows/pycbc_make_inference_workflow
- docs/workflow/pycbc_make_inference_workflow.rst
Need to update documentation still.
> Add pycbc_make_html_page to inference workflow.

- tools/einsteinathome/pycbc_build_eah.sh
> E@H build: use v11 ROM data from Albert for testing application

- pycbc/distributions/__init__.py
- pycbc/distributions/power_law.py
Also keeps ``UniformRadius`` for convenience.
Can set number of dimensions in configuration file with:
```
[prior-var]
name = uniform_power_law
dim = 3
min-var = 0
max-var = 1
```
> Make a more general UniformPowerLaw distribution.

- pycbc/results/static/css/pycbc/orange.css
- pycbc/results/templates/wells/two_column.html
Makes it so you can link a specific point on the page. Looks like this is what was being asked in Issue #1499 and since I was updating the Inference pages anyways did this.
Eg.: https://sugwg-jobs.phy.syr.edu/~cbiwer/tmp/inference_workflow/r10/4._samples/#A13
> Add internal hyperlinks to titles in wells on HTML pages

- pycbc/inference/sampler_emcee.py
Fixes #1625 
This adds a private class to turn a method of an instance into a callable (function-like) object. This is needed as the exiting method *only* works if the pool object has not yet been invoked, as classes are no longer updated after that point. Also, instance-methods *cannot* be pickled on their own, so we have to avoid actually storing them. 
@cmbiwer This works for the test script you pointed to, but please try for yourself to verify.
> add callable class to avoid pickle and pool issues

- bin/inference/pycbc_inference_plot_gelman_rubin
- pycbc/inference/gelman_rubin.py
- setup.py
Adds a module ``pycbc.inference.gelman_rubin`` to calculate convergence.
Adds a plotting script for it as well:
```
pycbc_inference_plot_gelman_rubin --input-file test.hdf --thin-start 0 --thin-interval 1 --thin-end 39999 --output-file ~/public_html/tmp/gelman_rubin_old.png --parameters mchirp --segment-start 50 --segment-end 30000 --segment-step 1000 --hline 1.1
```
gives: https://sugwg-jobs.phy.syr.edu/~cbiwer/tmp/gelman_rubin_old.png
> Gelman-Rubin convergence

- bin/inference/pycbc_inference_plot_gelman_rubin
Pass ``samples_group`` to ``InferenceFile.read_samples`` so that ``likelihood_stats`` can be plotted.
> Pass samples group in gelman-rubin executable.

- tools/einsteinathome/pycbc_build_eah.sh
Use wget_opts also for the 'wget' in--blessed-lalsuite
> E@H build: fix --blessed-lalsuite

- pycbc/types/frequencyseries.py
Equivalent function exists in `pycbc.io.live`.
> Remove pylal import

- pycbc/frame/__init__.py
- pycbc/frame/frame.py
- pycbc/frame/losc.py
- setup.py
This adds some functions to help us read and retrieve losc data files, and is well towards allowing us to use this in the workflow. The followup codes that take a frame-type option should be able to use this now.
> allow us to read losc gwf files

- pycbc/io/record.py
Currently, FieldArray uses `numpy.recarray.__getitem__` to retrieve indices and fields (that are not virtual fields or functions of fields) from an array. Apparently recarray uses a view in this function to internally cast the array as an instance of the FieldArray. This trigger's `FieldArray.__array_finalize__`, which has gotten slow since the introduction of function libraries. This internally casting is unnecessary for single fields, however.
This patch speeds up simple getitem operations by casting the array to a basic `ndarray` before using `__getitem__`. Only if the returned data type has fields and the array length is > 1 will the output be cast back to a FieldArray. This speeds up operations like `table['mass1'][10]` by a couple orders of magnitude: on my laptop this went from …
> Optimize field retrieval in FieldArray

- bin/minifollowups/pycbc_foreground_minifollowup
@ahnitz Same as previous issues here ... We just never hit the case of 0-triggers with this code recently. Easy fix.
> FIx in foreground minifup

- pycbc/conversions.py
These lines were probably accidentally deleted in all the renaming/merging.
> Fix primary/secondary xi conversions.

- pycbc/distributions/bounded.py
> Use given section name not 'prior' in bounded_from_config function.

- pycbc/transforms.py
> Give transforms in pycbc.transforms a name attribute for mapping to a str

- pycbc/distributions/boundaries.py
> Add a __repr__ to Bounds.

- bin/inference/pycbc_inference
- pycbc/inference/likelihood.py
- pycbc/inference/sampler_base.py
- pycbc/inference/sampler_emcee.py
- pycbc/inference/sampler_kombine.py
- pycbc/io/inference_hdf.py
As title says so you can pick up a run from the position it left off. Only for the kombine sampler. Raises a ``NotImplementedError`` for the emcee samplers.
It could be a small, concise project for someone whose getting into the inference code to implement this for emcee as well.
> pycbc_inference allow user to set initial positions from an InferenceFile

- pycbc/inference/prior.py
Adds a simple rejection sampling algorithm for ``PriorEvaluator.rvs`` to get random values from parameter space.
Example:
```
import numpy
from pycbc.inference import distributions
from pycbc.inference import prior
from pycbc.io import record
def mtotal_lt_30(params):
return True if params["mass1"] + params["mass2"] < 30 else False
mass_lim = (2, 50)
parameters = ["mass1", "mass2"]
uniform_prior = distributions.Uniform(mass1=mass_lim, mass2=mass_lim)
prior_eval = prior.PriorEvaluator(parameters, uniform_prior,
constraints=[mtotal_lt_30])
print prior_eval.rvs(20)
prior_eval = prior.PriorEvaluator(parameters, uniform_prior)
print prior_eval.rvs(20)
```
> Add rejection sampling to PriorEvaluator.

- pycbc/inference/sampler_base.py
> Ensure that write float to HDF file for likelihood_stats.

- bin/hdfcoinc/pycbc_coinc_findtrigs
- bin/hdfcoinc/pycbc_fit_sngls_binned
- bin/hdfcoinc/pycbc_fit_sngls_by_template
- bin/hdfcoinc/pycbc_fit_sngls_over_param
- pycbc/events/stat.py
- pycbc/events/trigger_fits.py
Should not change any existing functionality.  Enabling SEOBNRv2 duration function for backward compatibility
> refactoring and adding approximant option for duration

- pycbc/waveform/generator.py
From: https://landscape.io/github/ligo-cbc/pycbc/1860/diff
> Remove unused imports in generator.py

- pycbc/filter/qtransform.py
1.) Added Q-tiling mechanism.
2.) Simplified q-transform mechanism and its associated functions.
> Qtransform Dev

- pycbc/filter/qtransform.py
1.) Addition of loudest Q-plane interpolation function (defined as Q-plane with maximum normalized Q-tile energy)
2.) Addition of Q-plane spectrogram plotting function.
> Q-plane interpolation and Q-plane spectrogram plotting mechanisms

- pycbc/inference/likelihood.py
- pycbc/waveform/generator.py
Replaces lines with Python 2.7 syntax.
> Replace FIXME for Python 2.6/2.7 conflicts

- bin/inference/pycbc_inference_plot_movie
> Allow pycbc_inference_plot_movie to use transforms.py

- pycbc/types/frequencyseries.py
- pycbc/types/timeseries.py
Add sample rate to FrequencySeries, along with duration. Add delta_f to time series as well. I've noticed people tend to recalculate these a lot, so why not help out with that by including it as a property.
> add some helper properties for delta_f, sample_rate to Time/Freq series.

- pycbc/filter/qtransform.py
This fixes some some range issues in the interpolation, and also removes some unneeded calls to to_frequencyseries. Previously, the qplane function would *always* return 1 second of data which is not the intended result. Also, allow this to work with the latest numpy by not using floats as indices. 
Assigning to Andy, until Hunter accepts his invite to be a collaborator.
> small fixes in the qtransform routines

- pycbc/distributions/angular.py
As title says. ``CosAngle`` inherits it.
> Set norm for SinAngle with bounds of the class.

- pycbc/types/frequencyseries.py
Add a few more helper properties.
> add a few more helper properties to FrequencySeries

- pycbc/future.py
Fix "undefined variable" in future.py
> Fix in future.py

- pycbc/results/templates/wells/two_column.html
This fixes #1742 by implementing the fix described there. Please read #1742 for more background. I have verified that this fixes the problem with the current jinja2, and am waiting for a full bank verificator to complete to show a web-page (but I could see the problem in intermediate files, and it is not there with this fix in place).
Assigning to @cmbiwer and @duncan-brown as this is needed for next release and not sure if @cmbiwer is following PRs right now.
> FIx two_column template

- bin/pycbc_live
- pycbc/io/live.py
Keeping this open throughout ER11, will add commits as errors show up.
> pycbc_live: fix more errors from ER11

- bin/pycbc_live
- pycbc/frame/frame.py
- pycbc/io/live.py
- pycbc/strain.py
> pycbc_live: misc improvements during ER11

- pycbc/results/legacy_grb.py
- pycbc/workflow/segment.py
These changes address Landscape issues that I only became aware of after https://github.com/ligo-cbc/pycbc/pull/1730 was pushed, so I apologise for that. See https://github.com/ligo-cbc/pycbc/pull/1730#issuecomment-307548693.
> Addressing landscape issues

- pycbc/io/live.py
Landscape says "remove this". I obey.
> Remove unused import

- .travis.yml
- tools/docker_build_dist.sh
Add a Debian virtual environment build and push to CVMFS
> Add build for Debian virtual environment

- bin/pycbc_ringinj
> Add option in pycbc_ringinj to taper time-domain ringdown

- .travis.yml
- tools/docker_build_dist.sh
Reverts ligo-cbc/pycbc#1756
@duncan-brown I am reverting as this is causing the current master build to fail. Please see 
https://s3.amazonaws.com/archive.travis-ci.org/jobs/252296078/log.txt?X-Amz-Expires=30&X-Amz-Date=20170711T081804Z&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAJRYRXRSVGNKPKO5A/20170711/us-east-1/s3/aws4_request&X-Amz-SignedHeaders=host&X-Amz-Signature=33440760b6414cd8953515812ebde3efa5802f8f024eb460fef0e5d335b5b877
Anything obvious here?
> Revert "Add build for Debian virtual environment"

- .travis.yml
- tools/docker_build_dist.sh
- tools/test_coinc_search_workflow.sh
> Revert "Revert "Add build for Debian virtual environment""

- pycbc/types/timeseries.py
This is basically what we do internally in pycbc, but wrapped in a method. I've also set up so it removes the corrupted regions by default.
> add convenience whitening method

- pycbc/filter/qtransform.py
- pycbc/types/timeseries.py
This removes a bunch of cruft from the qtransform module and notably fixes a mistake in applying overwhitening where not needed. A convenience method on time series is also added.
> simplify the qtransform module a bit, add convenience method

- pycbc/workflow/segment.py
- tools/test_coinc_search_workflow.sh
Fixed one more file using urllib2 that I had missed in https://github.com/ligo-cbc/pycbc/pull/1780
> Change urllib2 to use resolve_url

- bin/inference/pycbc_inference_plot_posterior
This PR partially addresses issue #1715
> Check for plotting options in pycbc_inference_plot_posterior

- pycbc/waveform/ringdown.py
To weight the h_plus and h_cross amplitudes based on inclination.
> Add spherical harmonics to ringdown waveforms

- bin/pycbc_ringinj
> Add inclination to pycbc_ringinj

- pycbc/waveform/parameters.py
- pycbc/waveform/waveform.py
As per Riccardo's request on https://bugs.ligo.org/redmine/issues/5614 I added the additional tidal parameters that are taken as inputs to the new TEOBv2 and TEOBv4 models @spxiwh
> Added additional wf parameters for tidal EOB with dynamic tides

- pycbc/types/timeseries.py
As title says, not much more than that. useful when dealing with lots of padding remove / changing.
> add convenience method to remove x seconds from either side of array

- pycbc/inference/likelihood.py
Meant to include this in #1818. Test page is [here](https://www.atlas.aei.uni-hannover.de/~cdcapano/LSC/scratch/testdocs/latest/html/pycbc.inference.html#pycbc.inference.likelihood.GaussianLikelihood).
> Align equations in GaussianLikelihood doc

- bin/hdfcoinc/pycbc_page_recovery
- bin/hdfcoinc/pycbc_template_recovery_hist
- pycbc/events/triggers.py
- setup.py
Do some improvements on the parameter recovery plot and first work towards getting injection-restricted rate results, i.e. plot to look at the distribution of templates a given inj run is recovered in
> Recovery hist

- bin/hdfcoinc/pycbc_page_sensitivity
Needed to extract VT for a uniform 1-2 Msun distribution from standard O2 injection set.
> sensitivity plot: add max component mass binning and fix MC volume bug

- bin/hdfcoinc/pycbc_coinc_statmap
- bin/hdfcoinc/pycbc_page_foreground
- bin/hdfcoinc/pycbc_page_snrifar
- bin/hdfcoinc/pycbc_page_snrratehist
- bin/workflows/pycbc_make_coinc_search_workflow
- pycbc/workflow/plotting.py
This pull requests adds hierarchical removal to the workflow and results pages.
The main open box page shows the results of all hierarchical removals (per @ahnitz request) since that is the final result.
Sec 7.01 will show no removals and be labelled **No Event Removal**
Sec 7.02 through 7.02 + ``max-hierarchical-removal`` will show each stage of hierarchical removal and will be labelled **Hierarchical Removal Level N**.
> Add hierarchical removal to the workflow and results pages

- bin/hdfcoinc/pycbc_page_ifar
- bin/hdfcoinc/pycbc_page_snrifar
- bin/hdfcoinc/pycbc_page_snrratehist
Make the placement, font, and size of the legends in section 7 of the results page consistent.
> Clean up the location, size, and font of legends

- bin/hdfcoinc/pycbc_page_snrifar
This fixes an error in https://github.com/ligo-cbc/pycbc/pull/1877
@stevereyes01 please review the code changes, but do not merge. I will merge once it is tested.
> Add a buffer to ymax to make space for the legend

- docs/index.rst
There's no title so searches show a weird one.
> add title to documentation landing

- bin/hdfcoinc/pycbc_plot_singles_timefreq
Example plot with veto segments: https://www.atlas.aei.uni-hannover.de/~tito/LSC/o2/H1-PLOT_SINGLES_TIMEFREQ_2-1184112018-1105200.png
> plot_singles_timefreq: plot veto segments, fix gate plotting and caption

- pycbc/calibration/__init__.py
- pycbc/calibration/recalibrate.py
- setup.py
Includes a Recalibrate class to adjust strain data according to time-varying calibration parameters.
> Add calibration subpackage

- .travis.yml
- requirements.txt
- tools/docker_build_dist.sh
- tools/einsteinathome/pycbc_build_eah.sh
- tools/install_travis.sh
This pull request fixes the build issues described in https://github.com/ligo-cbc/pycbc/issues/1758
> Update build system to use Debian 14 on Travis

- .travis.yml
- tools/docker_build_dist.sh
This switches the build for the LDG virtual container to use the LIGO EL7 container rather than our own EL7 container (similar to Debian Jessie).
> Switch LDG virtual env build to LIGO container

- setup.py
Start a new post-O2 release series.
> Set for 1.8.0 release

- pycbc/conversions.py
This adds the conversion from lambda to quadrupole.
> add iloveq conversion

- bin/pycbc_banksim_skymax
- setup.py
Depends on #1897, please don't merge first!
This codes adds a`skymax` version of pycbc_banksim, similar to the `skymax` version of pycbc_inspiral. This code can slot directly into pycbc_bank_verificator and can do either "precessing" or "generic" banksims.
> New banksim skymax code

- pycbc/filter/resample.py
- pycbc/types/timeseries.py
Adds highpass / lowpass / generic filt FIR functions to time series.
> add fir convenience functions

- README.md
- pycbc/waveform/nltides.py
- pycbc/waveform/waveform.py
This adds a model with a simple model for NL tides from the Essick, et al. paper. It was coded up a while ago, but should merger before I forget.
> add nl tides modification to phase

- pycbc/noise/reproduceable.py
Fix patch that broke using analytic models (and some variations of provided PSDs depending on low frequency content).
> fix nans in noise generator

- pycbc/catalog/catalog.py
import pylab, pycbc.catalog
m = Merger("GW170817")
ts = m.strain("L1")
ts = ts.whiten(4, 4)
a = ts.time_slice(m.time - 30, m.time + 2)
t, f, p = a.qtransform(.01, 1, frange=(30, 500), qrange=(110, 110))
pylab.pcolormesh(t, f, p**0.5)
pylab.yscale('log')
pylab.show()
> add gw170817 to catalog update to losc urls which work on azure

- tools/einsteinathome/pycbc_build_eah.sh
- It gets increasingly difficult to work with the system's
Python (and pip) that's linked with a pretty ancient version of
libssl.  So build an own Python with a newer openssl version.
- pyOpenSSL was probably pinned to version 0.13 by requirements of
Pegasus, which are now obsolete, so is the pinning
- If pyssl_from=tarball, pyOpenSSL 0.13 and matching openssl-1.01p
will be installed. Otherwise openssl-1.0.2l will be compiled and
the latest available versiomn of pyOpenSSL will b einstalled (via
pip).
- Python compilation: rehash to make sure to use the newly built
versions of python and pip, check for dbhas early as if it's
missing, something must have gone wrong already during Pythoni
compilation / installation
> E@H: compile own Python on Debian 4

- pycbc/filter/qtransform.py
- pycbc/types/timeseries.py
Simplify the qtransform code, allow option for log sampling of the frequency space. Also allow ability to return the natural frequency sample rate.
> Simplify, add log spacing image interpolation

- pycbc/inference/sampler_emcee.py
This fixes a bug introduced in PR #1967. The way the `_read_fields` in `EmceePTSampler` currently works, it will try to use an index array for both walkers and temperatures. This causes an error because you can only do index selecting on at most one axis in h5py. This patch fixes this by loading all temperatures in to memory if more than one temperature is needed, then down selecting in memory. In addition, an explicit `reshape` call is made now to make sure the returned array is 3 dimensional if `flatten` is False.
> Fix bug reading samples from emcee pt

- pycbc/inject/inject.py
Right now ``InjectionSet`` assumes the injection data is top-level. This PR makes it so the injections can be read if they are in a HDF group, eg. ``mass1`` parameter data can be in ``fp["injections"]["mass1"][:]`` now instead of always in ``fp["mass1"][:]``.
> Allow HDF group of HDF injection file to be changed in InjectionSet

- bin/inference/pycbc_inference_plot_inj_intervals
- setup.py
Adds an executable that plots fraction of injections recovered in credible interval vs credible interval.
Depends on #1988. Leave as on hold for now.
> Add intervals plot for inference injection run

- pycbc/inference/sampler_mcmc.py
PR #1960 introduced a couple of bugs that are causing Travis to fail (these probably weren't picked up by Travis in that PR due to a bug in the testing scripts at the time the PR was created). The error was that p0 returns an array with shape (1, n parameters), but the call to the likelihood evaluator in the run method expects an (n parameters,) shape array. This relates back to BaseMCMC defining multiple walkers. That should be fixed long term by re-arranging the base sampler classes. For now, I fix this by just re-defining p0 in the MCMC sampler.
The second issue was that calls to likelihood evaluator were expecting it to always return blob data. However, if the likelihood class is called with return_meta set to False (as it is in `test_inference.py`, no blob data will be returned). …
> Fix a couple of bugs in mcmc sampler

- examples/filter/chisq.py
- examples/filter/snr.py
I can't reproduce yet the SPhinx failure, but this is a possibility (and should probably be fixed anyway). Want to test it on Travis.
> Fix label warning in Sphinx

- tools/einsteinathome/pycbc_build_eah.sh
- tools/install_travis.sh
This points to the last commit of lalsuite-archive on git.ligo.org.
> Update lalsuite to enable merging #1941

- pycbc/catalog/catalog.py
> Typo fix in catalog

- tools/docker_build_dist.sh
- tools/einsteinathome/pycbc_build_eah.sh
- tools/install_travis.sh
Stupid mistake.
While I am at it, how about also updating the lalsuite hash for Docker images?
> Fix error in Travis lalsuite update, update lalsuite for Docker images

- pycbc/workflow/core.py
Time module is now not used following the change to store `parsed` configuration files
> Remove now unused import

- setup.py
Pull request needed to prepare the release. Please approve this request (unless I've messed up), but let me merge this when ready to make the release.
> Prepare for release

- setup.py
Returns to development mode, when the release is finalised.
> Set back to development

- bin/hdfcoinc/pycbc_page_sensitivity
Test plots at https://www.atlas.aei.uni-hannover.de/~tdent/LSC/tests/page_sensitivity/H1L1-PLOT_SENSITIVITY_ALL_MCHIRP_ALLINJ-1134450017-1202400.png 
to compare with 
https://www.atlas.aei.uni-hannover.de/~tdent/LSC/o1/analysis/o2_untuned/a8/6._search_sensitivity/
> page_sensitivity: reworking of data handling to take multiple inj files

- setup.py
Duncan Macleod has requested a release to include the psd window feature he contributed.
> Set version for 1.9.2 release

- pycbc/types/timeseries.py
* Add method to get intersection of two time series
* Add and 'add' method that uses this as well.
> Add functions to find intersection of time series

- bin/hdfcoinc/pycbc_fit_sngls_over_multiparam
- pycbc/events/trigger_fits.py
- setup.py
Adds a new executable that allows one to specific the parameters and the smoothing width. A n-dimensional squashed sphere is constructed around each template and currently the average of the fitting values within the sphere is assigned to the template.
> Add new fitting executable

- pycbc/inference/likelihood.py
This adds a likelihood class that analytically marginalizes over coalescence phase. This can be used with aligned-spin, dominant-mode-only waveforms (or, generally, any signal model that can be written like `h(f) ~ A(f) exp[i (Psi(f) + phi)]`, where `phi` is the nuisance parameter to be marginalized over.
Marking as work in progress right now because I haven't tested this yet.
> Add marginalized phase likelihood

- docs/docker.rst
Add a short description on how to use docker to run a jupyter-notebook instance.
> add doc on running jupyter within docker

- CONTRIBUTING.md
This PR adds `CONTRIBUTING.md`, a contribution guide for PYCBC, this is stolen wholesale from gwastro/gwin.
> Added contributions guide

- docs/install.rst
- requirements.txt
- tools/docker_build_dist.sh
- tools/install_travis.sh
Travis is currently failing. This seems to be due to the egg name we are giving sphinxcontrib-programoutput. There is no reason to give this command, so just remove it and things seem to work again.
I don't 100% understand what's going on here, CVMFS is involved somewhere, but this resolves the problem.
> Fix a build issue in Travis

- docs/install.rst
- requirements.txt
- tools/docker_build_dist.sh
- tools/install_travis.sh
Let's see if we can use the official sphinxcontrib-programoutput, which seems to have been resurrected sometime last year.
> Use official sphinxcontrib-programoutput again

- pycbc/waveform/utils.py
- pycbc/waveform/waveform.py
This is still a work in progress.
> add fd approximants for td ones 

- bin/pygrb/pycbc_make_grb_summary_page
- bin/pygrb/pycbc_make_offline_grb_workflow
- pycbc/results/legacy_grb.py
- pycbc/workflow/grb_utils.py
- pycbc/workflow/jobsetup.py
- pycbc/workflow/matched_filter.py
- pycbc/workflow/segment.py
These changes are to bring O2-related tweaks to the `pygrb` pipeline onto master. In particular:
* improve the behaviour when running with 'long' timeslides and fix a few result page bugs related to this
* improve integration of the gating of data into the workflow
This code was used to produce results for GW170817
These changes are made in conjunction with gwastro/pycbc-pylal#45
> Pygrb o2 dev

- bin/pygrb/pycbc_make_offline_grb_workflow
- pycbc/results/legacy_grb.py
This change is intended to address #2150.
I've successfully generated a `pygrb` workflow with the `pygrb_o2_dev` branch (#2143) with this commit cherry-picked onto it.
> Fix pyplot import issue in legacy_grb.py

- README.md
- docs/index.rst
- docs/install.rst
https://www.atlas.aei.uni-hannover.de/~ahnitz/LSC/_gh-pages/latest/html/install.html
> add some simple install instructions

- pycbc/waveform/waveform.py
fixes #2195  reported by Salvo
> Wrong parameter name in waveform.py

- bin/plotting/pycbc_plot_waveform
- bin/pycbc_single_template
This should have been added before, but our followup codes should be able to use the coa_phase parameter.
> Add coa phase

- pycbc/results/scatter_histograms.py
adds a size option to create_multidim_plot
that gets passed to matplotlib scatter
> scatter_histograms.py: adding size option

- docs/install_lalsuite.rst
The ssh method does not work for everybody, so mentioning the https option also.
> https url for lalsuite

- bin/inference/pycbc_inference
- pycbc/pool.py
I think this may be what is needed to shut down the mpi pool more gracefully.
> allow graceful exit

- pycbc/conversions.py
- pycbc/detector.py
Allows one to inject optimally oriented signals by adding existing optimal detector code to conversions.py file.
> Add optimal detector functionality to conversions

- pycbc/types/array_cpu.pyx
- setup.py
This moves some of the hand written array operations over to cython (I'm going through the things that I had already written up to this point).
> add in array_cpu stuff

- docs/install_lalsuite.rst
This should hopefully resolve the issues presented in #2228.
> fix up lalsuite install docs

- pycbc/waveform/parameters.py
Somehow this slipped under the radar.
> Add chi_p to waveform.parameters

- pycbc/conversions.py
- test/test_conversions.py
Comes up often, so added convenience functions (and tests).
Also fixes some PEP-8 issues in conversions.py.
> Add chi_p and chi_eff from spherical conversions

- examples/psd/estimate.py
- pycbc/distributions/__init__.py
- pycbc/distributions/bounded.py
- pycbc/tmpltbank/brute_force_methods.py
- pycbc/tmpltbank/calc_moments.py
- pycbc/tmpltbank/coord_utils.py
- pycbc/tmpltbank/lambda_mapping.py
- pycbc/types/array.py
- pycbc/types/frequencyseries.py
- pycbc/types/timeseries.py
- pycbc/workflow/configuration.py
- test/test_distributions.py
- test/test_injection.py
- test/test_tmpltbank.py
* test distribution works in p3
* test injection works in p3
* test tmplt bank only partially works (more work needed here)
> add support for injection / distribution tests, start on p3 tmpltbank test

- setup.py
> Set for 1.12.2 release

- pycbc/conversions.py
Workaround for issues with matplotlib drawing contours on log plots.
> Add a helper function for log histograms

- pycbc/conversions.py
- pycbc/pnutils.py
- pycbc/waveform/nltides.py
This patch corrects the application of the Fourier phase shift for the effect of nonlinear tides from p-g mode coupling in neutron stars
> Correct SPA waveform for nonlinear tides from pg modes

- docs/credit.rst
This is the new page that I propose for the citation requirements. I suggest that we ask everyone to cite the DOI from the software, then cite additional papers depending on what they actually use PyCBC for.
I you think this is reasonable, @spxiwh please can you add the citations for the bank code?
> Update the citations requirements for PyCBC

- bin/pycbc_submit_dax
- tools/test_coinc_search_workflow.sh
This fixes the issues in https://github.com/gwastro/pycbc/issues/2289 by:
1. Removing the `set +e` that had crept into the code during debugging https://github.com/gwastro/pycbc/commit/8a843b03692665ca47411dfe8bb7a86ee86591b4
2. Correcting to overrides for segments and data to use LOSC data.
3. Adding a `--no-grid` option to `pycbc_submit_dax` that allows it to tell pegasus not to check for a valid grid proxy and `GLOBUS_LOCATION`.
> Fix Travis workflow test

- bin/pycbc_live
- pycbc/filter/matchedfilter.py
- pycbc/io/live.py
- pycbc/types/timeseries.py
- test/test_io_live.py
Fixes #2249 and further simplifies and documents the GraceDB/BAYESTAR interface.
Testing.
> PyCBC Live: fix SNR series error for triggers straggling the chunk boundary

- bin/pycbc_live
Added an option to give the path to the JSON file. Added a check for excess latency which also sets the status to critical.
If you think this is sufficient, I can also remove the separate nagios_monitor script.
Not tested yet.
> Update JSON status from within pycbc_live

- bin/pycbc_submit_dax
- tools/test_coinc_search_workflow.sh
and re-enable the workflow test in travis.
> Disable check for grid proxy in pycbc_submit_dax

- bin/pycbc_losc_segment_query
- bin/pycbc_submit_dax
- setup.py
- tools/docker_build_dist.sh
- tools/test_coinc_search_workflow.sh
Cherry-pick Duncan's changes to travis scripts to avoid need for LSC authentication; bump version to v1.11.10
> Travis lsc auth fixes

- setup.py
- tools/test_coinc_search_workflow.sh
Trying again to fix travis build issues...
> More travis fixes

- pycbc/workflow/configuration.py
When accessing files from `git.ligo.org` or `code.pycbc.phy.syr.edu` if the user hasn't authenticated, the code prints a helpful error message. However, the code to do this can fail in some pretty interesting ways if the input (`r.content`) is a binary file (for example a gzipped injection file). This patch follows a "python cookbook":
https://www.safaribooksonline.com/library/view/python-cookbook-2nd/0596007973/ch01s12.html
to check whether we have binary. If you do have binary, you don't have an authentication problem, so don't run the BeautifulSoup command.
@duncan-brown This probably shouldn't be checking `code.pycbc.phy.syr.edu` any more, as I'm assuming this is now not `ligo.org` authenticated!
> Don't BeautifulSoup binary

- pycbc/workflow/configuration.py
- setup.py
Cherry-pick patch from #2307 and increment version for release.
> Beaut soup fix

- pycbc/waveform/waveform.py
See issue https://github.com/gwastro/pycbc/issues/2314
> add rwrap arg to get_td_waveform_from_fd

- bin/pycbc_submit_dax
Fix for issue https://github.com/gwastro/pycbc/issues/2318
> pycbc_submit_dax: fix duplicate option

- companion.txt
The ligo.gracedb package should be included in the CVFMS bundles.
> Add gracedb to companion.txt for CVMFS builds

- bin/hdfcoinc/pycbc_coinc_mergetrigs
Trivial fix in error message in `pycbc_coinc_mergetrigs`
> Fix error message in coinc_mergetrigs

- tools/einsteinathome/pycbc_build_eah.sh
Fixes #2330 as discussed there
> Dont use old matplotlib

- bin/pycbc_live
* Writing the status JSON file sometimes causes I/O errors, this ignores them
* Consistently name output directories as YYYY_MM_DD
> Minor PyCBC Live fixes

- pycbc/detector.py
This is what the function actually produces, so I am changing the docstring:
> Fix incorrect docstring

- bin/workflows/pycbc_offline
This PR adds the pycbc_offline executable. In the current iteration, this generates the workflow up to the trigger merge jobs, both for data and injections for 3 detectors. The optimal_snr jobs are also working with the correct config files.
> Adding the pycbc offline executable

- examples/gw150914/audio.py
- examples/gw150914/gw150914_h1_snr.py
- examples/gw150914/gw150914_shape.py
- pycbc/catalog/catalog.py
This handles the catalog and the in built documentation links.
> update some losc links to gwosc links

- pycbc/events/stat.py
Adding a function for the NewSNR statistic, for any number of detectors.
> Adding coinc_multiifo function to NewSNR statistic

- pycbc/events/coinc.py
@tapaimarton I'm proposing this as a simplified mulit info coinc function. At the moment, it *does* assume that additional detectors beyond two are fixed to one of them. That assumption could be broken, but I think testing this first might be a good idea.
> add multiifo coinc function

- pycbc/events/stat.py
Changed the multiifo newsnr statistic to @tdent 's suggestion.
> Changed multi ifo coinc statistic

- bin/inference/pycbc_inference
- docs/conf_std.py
- pycbc/inference/__init__.py
- pycbc/inference/burn_in.py
- pycbc/inference/io/__init__.py
- pycbc/inference/io/base_hdf.py
- pycbc/inference/io/base_mcmc.py
- pycbc/inference/io/base_multitemper.py
- pycbc/inference/models/__init__.py
- pycbc/inference/models/base.py
- pycbc/inference/models/base_data.py
- pycbc/inference/models/gaussian_noise.py
- pycbc/inference/models/marginalized_gaussian_noise.py
- pycbc/inference/option_utils.py
- pycbc/inference/sampler/__init__.py
- pycbc/inference/sampler/base.py
- pycbc/inference/sampler/emcee.py
- pycbc/inference/sampler/emcee_pt.py
- pycbc/strain/calibration.py
Fixes a bunch of issues picked up by codacy.
> Address codacy issues on inference dev

- .travis.yml
- Dockerfile
- pycbc/workflow/datafind.py
- pycbc/workflow/pegasus_files/orangegrid-site-template.xml
See discussion at https://github.com/gwastro/pycbc/pull/2382
> Fixes to allow workflows to be run on OrangeGrid

- bin/plotting/pycbc_plot_trigrate
Code to plot a kde-smoothed rate of single ifo triggers vs time with various cuts and/or binnings
> add plot_trigrate

- examples/gw150914/gw150914_shape.py
Change the normalization of the whitening to match the 'whiten' method, which also seems better motivated.
> remove delta_f from example

- bin/pycbc_submit_dax
Alex broke `./status`. This should fix it.
> Fix typo in #2384

- bin/hdfcoinc/pycbc_fit_sngls_over_multiparam
- bin/hdfcoinc/pycbc_fit_sngls_over_param
- bin/hdfcoinc/pycbc_page_recovery
- pycbc/events/trigger_fits.py
- pycbc/events/triggers.py
(also update fit_sngls_param and fit_sngls_multiparam instructions as a result)
> add tau_0 and tau_3 as options into trigger_fits.get_param

- bin/pycbc_live
- pycbc/io/live.py
- test/test_io_live.py
* Fix a silly sign error which prevented the lag check from working.
* Write channel names into event XML files, so they show up in GraceDB.
* Tag some log messages with their interferometer.
> A couple fixes/improvements to PyCBC Live from ER13

- bin/hdfcoinc/pycbc_multiifo_coinc_findtrigs
- bin/hdfcoinc/pycbc_multiifo_coinc_statmap
- pycbc/io/hdf.py
- pycbc/workflow/coincidence.py
This PR adds the statmap code to the multiifo workflow. In the current version, for each detector combination the statmap code is run, using only that particular detector combination for background. The end result is a statmap file for each detector combination. Note that the multiifo_coinc_findtrigs code had to be changed too, I had to store the detector list in the hdf file. I ran a test, the workflow fully ran to it's current endpoint. (in order to run, the executable has to be added in the executables.ini).
> Adding statmap executalbe to the multiifo workflow.

- bin/workflows/pycbc_create_offline_search_workflow
- pycbc/workflow/coincidence.py
This PR adds the injinj, injfull and fullinj coinc jobs to the workflow. The workflow generates, but the jobs are not included when ran with map reuse. Might be a config issue. Please comment if I did something obvious wrong.
> Multiifo inj coinc

- bin/hdfcoinc/pycbc_combine_statmap
- bin/hdfcoinc/pycbc_multiifo_combine_statmap
- pycbc/events/coinc.py
- pycbc/io/hdf.py
Largely bookkeeping at this stage, but this will have the new multi-ifo ranking statistic and other features
File showing diff between multi-ifo combine statmap and combine statmap codes:
[combine_statmap_diff.txt](https://github.com/gwastro/pycbc/files/2802176/combine_statmap_diff.txt)
Updated after 8e07683:
[combine_statmap_diff_2.txt](https://github.com/gwastro/pycbc/files/2821054/combine_statmap_diff_2.txt)
This is already at a stage where it is a large percentage of the file, so the diff may not be particularly useful
> adding multiifo combine statmap script

- bin/hdfcoinc/pycbc_coinc_statmap_inj
- bin/hdfcoinc/pycbc_multiifo_coinc_statmap_inj
- bin/workflows/pycbc_create_offline_search_workflow
- pycbc/workflow/coincidence.py
This PR adds statmap for the multiifo injection coinc files.
> Multiifo inj statmap

- bin/pycbc_optimal_snr
Hi Alex,
Thought I should introduce myself, I'm Connor McIsaac. I'm a first year PhD student at the University of Portsmouth, my supervisor is Ian Harry.
When looking at the code today I was confused by this piece of code, by talking to Ian I found out that it is there for historical reasons and can be removed.
> Removed the key word return_found, as it is no longer used

- bin/pycbc_process_sngls
- pycbc/events/coinc.py
- pycbc/events/stat.py
- pycbc/io/hdf.py
Labelled 'work in progress' as it hasn't yet been tested for a full range of ranking stats. 
Also I'm not sure if the vetoing and cutting and clustering filters are correct and/or all play nicely with each other - this may need some thought.  Initial tests seem reasonable as compared to applying cuts while plotting (in the pycbc_plot_singles_vs_params script)
> Add script to do basic operations and reranking of single trigger files

- setup.py
> Prepping for release

- bin/pycbc_live
as requested by @titodalcanton
> Making p-value livetime a required option

- bin/hdfcoinc/pycbc_multiifo_combine_statmap
Fix combine statmap typo, and save forground_veto data
> fix pycbc_multiifo_combine_statmap

- pycbc/filter/matchedfilter.py
> Fix wrong call to is_extent_valid()

- bin/hdfcoinc/pycbc_multiifo_combine_statmap
- bin/pycbc_live
- pycbc/events/single.py
Investigating and fixing errors with SNR time series etc.
> Fix various errors in PyCBC Live

- pycbc/inference/sampler/emcee_pt.py
Adding feature to read an hdf file storing beta values for the emcee_pt sampler from the config file.
> Add back ability to provide beta values to emcee_pt from external file

- bin/hdfcoinc/pycbc_plot_singles_vs_params
- bin/pycbc_inspiral
- pycbc/events/events.py
- pycbc/events/stat.py
- pycbc/io/hdf.py
- pycbc/psd/__init__.py
- pycbc/psd/variation.py
Between commits the ranking statistic plumbing was changed to make it easier to switch between ranking statistics. This pull request (thanks Ian) allows the psd variation code to work in this new scheme.
> Psd Variation with new stat plumbing

- bin/hdfcoinc/pycbc_fit_sngls_over_multiparam
- bin/hdfcoinc/pycbc_fit_sngls_over_param
propagate analysis time through the fit functions
Also noticed that some of the dataset naming (count_in_template vs count_total) was inconsistent - these datasets are not yet used so it is safe to change without affecting downstream
> propagate analysis time

- bin/hdfcoinc/pycbc_foreground_censor
- bin/hdfcoinc/pycbc_multiifo_coinc_statmap
- bin/hdfcoinc/pycbc_multiifo_combine_statmap
- bin/workflows/pycbc_create_offline_search_workflow
updateing foreground censor to workflow for multiifo use and adding it to the workflow
> Foreground censor multiifodev

- bin/pycbc_multi_inspiral
- bin/pygrb/pycbc_make_offline_grb_workflow
- pycbc/events/events.py
- pycbc/filter/matchedfilter.py
- pycbc/workflow/core.py
- pycbc/workflow/jobsetup.py
- pycbc/workflow/matched_filter.py
#2476 is currently unmergeable because of conflicts with it and master. Here I clean up the history of that branch, and merge everything into one commit from master (with one fix on top of that). This should be the same as #2476, but actually mergeable, and Iain will still be credited with authoring this code. I'll plan to merge this if the tests pass, so any further changes should be a new pull request from a new branch rebased with origin/master.
@idorrington92 the problem here is that you have not been rebasing when updating against master. This page (there are many others) gives an idea of the difference between rebasing and merging:
https://www.atlassian.com/git/tutorials/merging-vs-rebasing
as we automatically collapse patches when adding to origin, this *requires* that PRs be …
> PyGRB Rewrite

- pycbc/waveform/ringdown.py
To analyze the ringdown with a generic damped sinusoid superposition, one might want not to have the spherical harmonics. If no inclination is given to the generic approximant, the spherical harmonics will be set to one (i.e., not taken into account), but one can still activate them by just giving an inclination.
Furthermore, the Kerr approximant should not have a default inclination to 0., as one could then easily forget to give an inclination and the resulting ringdown would be suboptimal. Instead, I made the inclination a required argument for the Kerr approximant.
> Spher_harms mandatory in Kerr and optional in generic ringdowns

- docs/inference.rst
Points to GWOSC frames and Channel names
(also some white space from my text editor sorry)
> update gw150914 inf example to point to gwosc

- bin/pycbc_live
Should protect from things like #2587 and #2604. Also fixes a minor glitch in the Icinga messages.
> Handle cases where master and worker nodes disagree on ifo status

- docs/workflow/pycbc_make_inference_inj_workflow.rst
- examples/workflow/inference_inj/inference.ini
- examples/workflow/inference_inj/run_pycbc_make_inference_inj_workflow.sh
- examples/workflow/inference_inj/workflow_config.ini
Fixed the documentation for pycbc_make_inference_inj_workflow
> Pycbc inference injection workflow documentation fix

- bin/pycbc_inspiral
- bin/pycbc_inspiral_skymax
- pycbc/events/eventmgr.py
- pycbc/vetoes/sgchisq.py
> allow keep_loudest to access the single trigger stat choices

- bin/pycbc_live
Should fix #2609. Also add some docstrings and switch from `numpy.log(1 + x)` to `numpy.log1p(x)`.
> Live: check outcome of followup p-value calculation before using it

- bin/hdfcoinc/pycbc_coinc_hdfinjfind
- bin/hdfcoinc/pycbc_page_foundmissed
- bin/workflows/pycbc_create_offline_search_workflow
In a similar vein to #2569, here I add the injection plots to the workflow. As most are failing, most are commented out. As the `pycbc_page_foundmissed` code has already been patched to work with the new output I changed a few things around to include that code. Here's what this outputs:
https://ldas-jobs.ligo.caltech.edu/~spxiwh/LVC/aLIGO/O3/devel/offline_multiifo/run9
Two items still to be done:
* I haven't yet added the ALLINJ plots
* Something is wrong with the "Injected [decisive] chirp distance"
As the plotting code is used in the standard workflow I'll need to resolve the second issue before being able to merge this. But the rest can be looked over now.
> Starting to add injection plots

- pycbc/events/coinc_rate.py
introduction of a coinc_rate module to include the estimation of noise coincidence rates from single trigger rates
> multiifo coinc rate module

- pycbc/inject/injfilterrejector.py
This just added the options for the multi ifo version, and makes a dictionary from running the old injfilterrejector on each ifo.
> Added injfilterrejector for multi ifo. 

- pycbc/inference/models/base.py
Currently the lines
```
if not cp.has_section('sampling_params'):
raise ValueError("no sampling_params section found in config file")
```
in `from_config` in `models/base.py` is not letting the user know that a `sampling_params` section has not been provided, ie. nothing is printed to the err file.
This PR fixes this so that a warning is printed if `sampling_params` is not being used, so that the user is aware of that.
> Warning message if sampling_params is not provided

- bin/hdfcoinc/pycbc_fit_sngls_split_binned
splitting triggers into templates within certain boundary values and then binning and fitting as performed in pycbc_fit_sngls_binned
> add in tiled plots pycbc_fit_sngls_split_binned

- bin/hdfcoinc/pycbc_page_segplot
- pycbc/workflow/plotting.py
This PR modifies the pycbc_page_segplot for multi-ifo use and implements it into the workflow.
> Multiifoplotsegments

- bin/hdfcoinc/pycbc_page_segtable
- pycbc/workflow/plotting.py
Implement the multi-ifo changes of pycbc_page_segtable into the multi-ifo workflow.
> Multiifosegtable

- bin/hdfcoinc/pycbc_multiifo_coinc_findtrigs
This was the commit that apparently I forgot to merge. Somewhat critical for the multi-ifo code to actually work!
> fixes to multi-ifo version

- pycbc/distributions/angular.py
- pycbc/distributions/gaussian.py
- pycbc/distributions/masses.py
- pycbc/distributions/power_law.py
- pycbc/distributions/sky_location.py
- pycbc/distributions/uniform.py
- pycbc/distributions/uniform_log.py
- pycbc/inference/io/__init__.py
- pycbc/inference/io/multinest.py
- pycbc/inference/sampler/__init__.py
- pycbc/inference/sampler/multinest.py
This will add support for the multinest sampler.
> Add support for multinest

- pycbc/inference/io/__init__.py
- pycbc/inference/io/cpnest.py
- pycbc/inference/io/posterior.py
- pycbc/inference/sampler/__init__.py
- pycbc/inference/sampler/cpnest.py
- requirements.txt
Work in Progress....
Including new samplers in PyCBC Inference.
> WIP: Add support for CPNest 

- bin/hdfcoinc/pycbc_plot_psd_file
- bin/workflows/pycbc_make_inference_workflow
- pycbc/workflow/inference_followups.py
- pycbc/workflow/plotting.py
This cleans up and makes several fixes to `pycbc_make_inference_workflow` so that it works. Duplicated code is removed, imports are updated to be more consistent with `pycbc_make_inference_inj_workflow`, and several function calls are fixed that were failing due to incorrect or outdated arguments.
A simple test run with these changes produced [this output](https://sugwg-jobs.phy.syr.edu/secure/daniel.finstad/inference_workflow_test/).
> Fix inference workflow

- bin/pycbc_live
Allows us to periodically save the coinc background and hence make plots like this:
> Live: add ability to output background

- pycbc/waveform/generator.py
This PR updates an absolute sibling import to a relative import (the only one I could find).
> Updated sibling import to relative

- bin/bank/pycbc_bank_verification
- bin/hdfcoinc/pycbc_get_loudest_params
- bin/hdfcoinc/pycbc_stat_dtphase
- bin/hdfcoinc/pycbc_template_recovery_hist
- bin/plotting/pycbc_plot_trigrate
- bin/population/pycbc_population_plots
- bin/pycbc_banksim
- bin/pycbc_banksim_skymax
- bin/pycbc_coinc_time
- bin/pycbc_faithsim
- bin/pycbc_fit_sngl_trigs
- bin/pycbc_get_ffinal
- bin/pycbc_randomize_inj_dist_by_optsnr
- bin/pycbc_submit_dax
- bin/pygrb/pycbc_make_grb_summary_page
- examples/catalog/what.py
- examples/distributions/list_distributions.py
- examples/inference/list_parameters.py
- examples/overlap.py
- examples/waveform/what_waveform.py
- examples/workflow/data_checker/daily_test.py
- examples/workflow/dayhopecheck/dayhopecheck.py
- tools/benchmarking/absolute_times.py
- tools/static/runtime-scipy.py
- tools/timing/arr_perf.py
- tools/timing/banksim/banksim.py
- tools/timing/fft_perf.py
- tools/timing/match_perf.py
- tools/timing/wav_perf.py
This PR attempts to update all usage of `print` as a python statement to function calls, as required for running on python>=3.
> Updated print statement usage to function calls

- bin/hdfcoinc/pycbc_multiifo_coinc_findtrigs
- pycbc/events/coinc.py
Also lots of work on comments and readability, remove variable names that shadow other names etc
> Multiifo coinc : discard 'extra' coincs from too-closely-spaced triggers

- bin/hdfcoinc/pycbc_page_recovery
- bin/hdfcoinc/pycbc_template_recovery_hist
- pycbc/events/triggers.py
Recovery plot was only working for 2-ifo case, update for multi-ifo.
> Fix injection accuracy plotting for multi-ifo format

- bin/hdfcoinc/pycbc_coinc_findtrigs
- bin/hdfcoinc/pycbc_multiifo_coinc_findtrigs
Apply some cleanups from the 2-ifo code to multi-ifo and vice versa. Also don't fail if the user doesn't specify a decimation option.
> Multi coinc

- pycbc/events/eventmgr.py
Fixed bug where the network event id number was not being incremented for each template analysed
> pygrb event id bug fix

- bin/pycbc_multi_inspiral
Fixed bug where command line options were being used in function definitions.
> Multi inspiral bug

- bin/hdfcoinc/pycbc_coinc_hdfinjfind
- bin/hdfcoinc/pycbc_page_sensitivity
- bin/workflows/pycbc_create_offline_search_workflow
Quick fix to make sensitivity plot to work.
> Multiifo sensitivity plot

- bin/minifollowups/pycbc_injection_minifollowup
- pycbc/io/hdf.py
A recent patch has broken the injection minifollowups because of changes in how the "mask" attribute is stored. This patch fixes the problems. It has been tested to work in the old offline search workflow.
> Fixes because of recent optimization changes in io/hdf.py

- bin/hdfcoinc/pycbc_plot_range_vs_mtot
- bin/hwinj/pycbc_generate_hwinj_from_xml
- bin/plotting/pycbc_plot_vt_ratio
- bin/pycbc_get_ffinal
- bin/workflows/pycbc_make_uberbank_workflow
- pycbc/detector.py
- pycbc/events/stat.py
- pycbc/frame/losc.py
- pycbc/strain/strain.py
- test/test_tmpltbank.py
Some more assorted python3 fixes. The weird whitespace changes are removing tabs (which python3 refuses to mix with spaces). Then there's an important integer division in strain.py (without which the code does run, but does weird things!). Then some more dict and str and comparison-with-None fixes.
> Python 3 fixes [2]

- bin/hdfcoinc/pycbc_foreground_censor
Requires #2773  + A future PR that adds back the combined foreground_veto that isn't keyed by ifo.
> fix foreground censor script

- pycbc/inference/io/cpnest.py
- pycbc/inference/io/posterior.py
This is a minor but necessary change to write posterior files.
> Fixing issue of PosteriorFile Class inheritance to CPNestFile class

- bin/hdfcoinc/pycbc_multiifo_combine_statmap
`multiifo_combine_statmap` was not performing checks for if the statmap files inputs were `statmap_inj` files for injections
> changes required to combine_statmap to deal with injection statmap files

- bin/hdfcoinc/pycbc_multiifo_combine_statmap
reverses overzealous deletions from #2815
> dont get rid of segments bit of combine statmap

- bin/pycbc_multi_inspiral
- pycbc/events/eventmgr.py
Changes to multi inspiral to make it cluster at the end of the matched filtering. Requires changes earlier in code to make it not cluster in the matched filtering step. Made a new function to cluster based on a network SNR statistic.
> pygrb clustering

- pycbc/inference/sampler/cpnest.py
I have added a log_prior function and new_point function to CPNest model class
> Fixing potential Issue with priors in CPNest sampler

- bin/hdfcoinc/pycbc_apply_rerank
- bin/hdfcoinc/pycbc_followup_file
- bin/hdfcoinc/pycbc_rerank_passthrough
- bin/workflows/pycbc_create_offline_search_workflow
- bin/workflows/pycbc_make_coinc_search_workflow
- pycbc/frame/store.py
- pycbc/psd/estimate.py
- pycbc/workflow/coincidence.py
This PR provides the workflow support to re-rank candidates using a follow-up script.
> workflow components to apply follow-up of background / zerolag and rerank

- bin/hdfcoinc/pycbc_page_foundmissed
> add support for 2-ifo case in fm plot

- bin/hdfcoinc/pycbc_multiifo_add_statmap
- bin/workflows/pycbc_create_offline_search_workflow
- pycbc/io/hdf.py
- pycbc/workflow/coincidence.py
Make modifications to add_statmap to allow for injection inputs
works by including coinc_statmap files from full_data as an extra input `--background-files`
These are then used for the background
some small changes to add_statmap also included, and an option to output the ifo_combination
This is not yet within the workflow
EDIT: this is now included in the workflow
> Add statmap inj

- bin/pygrb/pycbc_grb_inj_combiner
- bin/pygrb/pycbc_grb_inj_finder
- bin/pygrb/pycbc_grb_trig_cluster
- bin/pygrb/pycbc_grb_trig_combiner
- requirements.txt
- setup.py
This PR adds new executables for the PyGRB workflow to go with @idorrington92's new `pycbc_multi_inspiral` code
- `pycbc_grb_trig_combiner`
- `pycbc_grb_trig_cluster`
> Added new post-processing scripts for PyGRB

- pycbc/workflow/coincidence.py
the cluster window setting is automatically copied over from the ini file section anyway, don't need to set it via explicit extra workflow code.
> multiifo statmap setup: don't set up cluster window twice

- bin/pygrb/pycbc_pygrb_plot_chisq_veto
- bin/pygrb/pycbc_pygrb_plot_coh_ifosnr
- bin/pygrb/pycbc_pygrb_plot_skygrid
- bin/pygrb/pycbc_pygrb_plot_snr_timeseries
- pycbc/results/__init__.py
- pycbc/results/pygrb_plotting_utils.py
This should fix the problems found in https://github.com/gwastro/pycbc/pull/2837 while reinserting the pygrb results utils upimport.
> Solves issue raised in PR #2837

- examples/workflow/inference/inference.ini
- examples/workflow/inference/inj_workflow_config.ini
A bug fixed in the config files for pycbc_make_inference_inj_workflow by adding the waveform transforms.
> Fixed the config files for pycbc_make_inference_inj_workflow

- bin/hdfcoinc/pycbc_page_foundmissed
i'm having a hard time seeing little red crosses etc. when f/m plots are displayed on the result pages.
> slightly bump size of symbols

- bin/workflows/pycbc_make_inference_inj_workflow
Fixes a bug where a variable is not being set when no injections file is given.
> Fix inference_inj_workflow bug

- bin/workflows/pycbc_create_offline_search_workflow
Fix bug which meant that all sensitivity plots were being labelled and saved as the same type of injection
Add in instructions in workflow to include allinj sensitivity plots and front summary page
Fixes #2853
> Sensitivity plots fix

- pycbc/inference/io/__init__.py
- pycbc/inference/io/base_nested_sampler.py
- pycbc/inference/io/cpnest.py
- pycbc/inference/io/dynesty.py
- pycbc/inference/sampler/__init__.py
- pycbc/inference/sampler/dynesty.py
- requirements.txt
Adding supprt for dynamic nested sampling package: dynesty.
https://github.com/joshspeagle/dynesty
This is work in progress.
> Adding support for dynesty sampler.

- bin/plotting/pycbc_plot_qscan
* More CLI help
* Add reference to Q-transform
* Fix bug preventing single time window plots
* Enable choosing colormap
> Various fixes to pycbc_plot_qscan

- bin/hdfcoinc/pycbc_page_foreground
- bin/hdfcoinc/pycbc_page_injtable
- bin/hdfcoinc/pycbc_page_segtable
- bin/hdfcoinc/pycbc_page_vetotable
- bin/plotting/pycbc_banksim_table_point_injs
- pycbc/results/__init__.py
- pycbc/results/table_utils.py
'table' being used as both module and function name causes problems and stops workflow
> rename table function and table module to prevent clashes

- pycbc/workflow/core.py
- pycbc/workflow/plotting.py
Some tags were being passed as empty strings, this meant that files were being created with names containing `-_`, and `__`
This removes them from the tags
> Tag empty string removal

- bin/hdfcoinc/pycbc_multiifo_exclude_zerolag
- bin/workflows/pycbc_create_offline_search_workflow
This should have been done in #2872 but was missed out
> Exclude zerolag not dealing with DictArray properly

- bin/hdfcoinc/pycbc_multiifo_add_statmap
FAP was being calculated incorrectly as the time was not being converted into years
> add_statmap fap calculation

- pycbc/strain/strain.py
> Fix bug in PyCBC Live autogating

- bin/hdfcoinc/pycbc_page_coinc_snrchi
Plot was broken because some chisq values were zero or negative (?) 
Fix and do a bit of tweaking of symbol sizes and transparency, test output here
> fix inj snrchisq plot

- pycbc/events/ranking.py
This adds the boiler plate functions needed to apply rescaling in larger statistics.
> add sngl framework needed for psd rescaling

- bin/hdfcoinc/pycbc_multiifo_add_statmap
few cleanups on formatting, help msgs etc.
> remove unused import, variables etc.

- bin/hdfcoinc/pycbc_multiifo_add_statmap
Hierarchical removal changes were not tested against injection style add_statmap - some keyes were not present in injection statmaps, so this fixes these
> add injection_style checks to add statmap

- bin/hdfcoinc/pycbc_multiifo_add_statmap
ensuring that what should be integers are integers
FAP was not being recalculated
> Add statmap causing some issues downstream

- pycbc/inject/inject.py
> Fix Python 2ism in writing injection files

- bin/pycbc_live
Fixes #2991
Not tested, but this should do the trick!
> Fix python3-ism in 2991

- setup.py
Set `setup.py` back to development code.
> Set back to release

- bin/workflows/pycbc_create_offline_search_workflow
Add in the line in the workflow to create background followup page (similar to fg followup)
This is as has been done in pycbc_make_coinc_search_workflow
> Add background coinc pages to multiifo workflow

- pycbc/conversions.py
Conversion functions that take the frequency and damping time of a particular QNM and return the frequency and damping time of a new desired QNM. If the provided QNM frequency and damping time correspond to a negative mass or a BH spin > 0.9996, it returns NAN
> Obtain QNM params from other QNM

- bin/hdfcoinc/pycbc_calculate_psd
- pycbc/__init__.py
- pycbc/fft/fft_callback.py
- pycbc/scheme.py
- pyproject.toml
- setup.py
- tools/benchmarking/profiling_utils.sh
Depends on #2946 
* Removes variables in __init__.py only required for weave
* Remove use of functions that only set up weave
> further cleanup of __init__.py

- MANIFEST.in
- requirements.txt
- setup.py
Ian thinks this might be the problem, but it seems we can't reproduce this short of a full release.
> Try to fix pip build problem

- setup.py
Set for release so we can put out the bug fix to pycbc inference
> set for release

- pycbc/types/timeseries.py
Add method to TimeSeries to gate at a specific time. This is a simple helper method.
> add helper gate method

- bin/pycbc_live
- pycbc/filter/matchedfilter.py
Reverts gwastro/pycbc#2720; see #3074.
> Revert "allow pycbc live to accept multiple triggers each chunk from each template"

- bin/plotting/pycbc_ifar_catalog
- bin/workflows/pycbc_create_offline_search_workflow
- pycbc/workflow/plotting.py
Adding in global IFAR plot to summary pages
Tested for closed and open boxes, two ifo statmap and multiifo combined statmap
PR #3076 is required in order to produce correct results when hierarchical removal number is not given
Solves issue #2962
> Global ifar plot

- bin/plotting/pycbc_plot_waveform
Fixed the pycbc_plot_waveform overlapping subplots label problem. 
Also changed the caption as no insets are displayed
> Fixed the overlapping label problem

- bin/hdfcoinc/pycbc_page_snrifar
Fixed the overlapping secondary y-ticks issue and forced to display the secondary y-label
> Fixing label issue in pycbc_page_snrifar

- pycbc/cosmology.py
The functions `distance_from_comoving_volume` and `redshift_from_comoving_volume` are relatively slow. A single call can take O(10ms). When using this functions in a PE run (as you would if you want to use a prior uniform in comoving volume), this can make the waveform transforms be slower than even waveform generation, making it the dominant cost in the analysis. This fixes this by adding an interpolator that is similar to what is used for the distance to redshift function. The first time either of these functions is called with a standard cosmology, the interpolator is setup. The initial setup take O(10s). However, all successive calls are very fast, O(10us).
Since the initial call is slow, using interpolation is optional (with default is set to True). So, if you're just calling the …
> Add interpolation for comoving volume

- bin/inference/pycbc_inference_extract_samples
- pycbc/inference/io/__init__.py
- pycbc/inference/io/base_hdf.py
This allows `pycbc_inference_extract_samples` to combine posteriors from multiple input files. If multiple files are provided, it will just write the samples group, with the samples obtained from each file concatenated together. It also enforces that all all static params are the same between the combined files, as well as any attribute saved to the `samples` group (such as the `lognl`).
This also improves python 3 support by converting strings stored in the top level attrs from bytes to strings. If a file was created with python 2, values stored in the top-level attrs will be saved as unicode, which python 3 interprets as bytes. By converting them to strings, the output file will be the same regardless of if it was written in python 2 or 3 (which saves everything as strings). 
Example: …
> Allow extract samples to combine files; improve py3 support

- bin/bank/pycbc_brute_bank
This updates the pycbc_brute_bank script to one we've used for some projects. 
1) Adds a kde step to help speed up drawing points
2) fill bank in regions of tau0 which are then stepped through incrementally (with overlapping regions). 
3) various changes to minimize memory useage.
> update brute force bank

- bin/pycbc_live
Should fix broken sky localizations for single-detector triggers.
Testing.
> PyCBC Live: fix reported times for single-detector triggers

- docs/_include/inference_sampler.sh
- docs/inference.rst
- docs/inference/examples/sampler_platter.rst
- examples/inference/samplers/cpnest_tub.ini
- examples/inference/samplers/dynesty_stub.ini
- examples/inference/samplers/emcee_pt_stub.ini
- examples/inference/samplers/emcee_stub.ini
- examples/inference/samplers/epsie_stub.ini
- examples/inference/samplers/multinest_tub.ini
- examples/inference/samplers/run.sh
- examples/inference/samplers/simp.ini
- examples/inference/samplers/ultranest_stub.ini
- tools/pycbc_test_suite.sh
Example showing how this looks coming soon.
> add sampler platter to docs

- pycbc/workflow/inference_followups.py
PR #3154 added the ability to write all parameters to a posterior using a wildcard `*`. This changes the way you specify what posterior parameters are written in the inference workflow config file to make use of that.
Previously, there was a separate workflow section where you had to list every parameter to write to the posterior file. This gets rid of that, in favor of just using the `parameters` option in the `extract_posterior` section. In other words, instead of this:
```
[workflow-posterior_params]
; parameters on the right are read from the samples file
; parameters on the left are what they will be named in the posterior file
mass1 = srcmass1
mass2 = srcmass2
spin1_a =
spin1_azimuthal =
spin1_polar =
spin2_a =
spin2_azimuthal =
spin2_polar =
chi_eff = …
```
> Don't have a separate section for posterior parameters

- bin/hdfcoinc/pycbc_page_injtable
- bin/workflows/pycbc_create_offline_search_workflow
Add found injtable to workflow
Also provide correction to injtable code to leave cell blank if value is not applicable
> Add found Injtable to workflow

- bin/plotting/pycbc_banksim_plot_fitting_factors
- bin/pycbc_banksim_match_combine
* Error due to string conversions in Python 3
* FF plot too small with modern matplotlib
> Fix issues with banksim code

- bin/hdfcoinc/pycbc_multiifo_coinc_findtrigs
- bin/hdfcoinc/pycbc_multiifo_sngls_findtrigs
- pycbc/events/stat.py
- pycbc/io/hdf.py
Starting to add offline singles functionality:
This first commit will almost definitely cause codeclimate to complain due to repeated code between this and coinc_findtrigs and coinc_statmap. I'll sort this when I can
The initial IFAR calculation method is bad (count number louder in foreground), and will never be larger than the chunk size. So hopefully will get an improved version in  - this is just to get the code into a shared space
> Start to add in codes for inclusion of offline singles

- pycbc/workflow/coincidence.py
I missed a line in the last PR.
> New search workflow cleanup 3

- pycbc/events/stat.py
> missed change to int8 comparison

- bin/hdfcoinc/pycbc_page_foundmissed
Made the found-missed plot colourblind friendly.
> Made the pycbc_page_found_missed colourblind friendly.

- pycbc/events/stat.py
Renormalise PTA histogram to a PDF when reading
Take account of expected noise in PTA histogram in ExpFitSGFgBgNormNewStatistic
(also renaming some statistics)
> changes to PTA histogram normalisation

- bin/hdfcoinc/pycbc_multiifo_dtphase
dynamically choose the datatype depending on number of IFOs
Error if max possible tdiff is less than (approx) Earth diameter travel time
> multiifo_dtphase time size

- pycbc/types/timeseries.py
- test/test_timeseries.py
This should address #3243. 
This makes the check on start time check for reasonable floating point differences and ensures that rounding differences don't cause a function failure.
> make add into more robust

- examples/live/check_results.py
- examples/live/run.sh
* Force the test bank to a known realization
* Add basic sanity check of the results
Fixes #3259.
> Improve PyCBC Live unit test

- bin/hdfcoinc/pycbc_plot_multiifo_dtphase
Plotting script to create a corner plot for the histogram files output from pycbc_multiifo_dtphase
(Initially added to see if we can steal some stuff from it for use in main analysis)
> Add dtphase plots

- pycbc/waveform/bank.py
This may address #3263 for the case of pycbc live. I'm still worried about offline though, so I'll think about that too.
> avoid hash for pycbc live

- bin/pycbc_live
- bin/pycbc_optimize_snr
- pycbc/io/live.py
Needed for public early-warning test.
> Expose GraceDB search tag as a PyCBC Live option

- pycbc/waveform/bank.py
Added statements to enable FilterBankSkyMax code to use low-frequency cutoff of the bank itself.
> Fixed start frequency of FilterBankSkyMax

- bin/pycbc_make_skymap
The functionality which can load local frame files is recommended by Tito. Also, Fergus agrees with it. In addition to this functionality, some extra safe chacks are added such as checking if the channel names are correct, and the trigger time is in the time interval of the local frame files.
> pycbc_make_skymap: enable to load local frame files

- setup.py
Release given the workflow bugfix in #3313
> prep for release 1.16.3

- pyproject.toml
- requirements.txt
- setup.py
> Avoid numpy 1.19

- examples/inference/data/o1.ini
- examples/inference/data/o2.ini
- examples/inference/models/marginalized_phase.ini
- examples/inference/priors/bbh-uniform_comoving_volume.ini
- examples/inference/samplers/dynesty.ini
- examples/inference/samplers/emcee_pt-srcmasses_comoving_volume.ini
- examples/workflow/inference/gw150914_gw170814-dynesty/create_workflow.sh
- examples/workflow/inference/gw150914_gw170814-dynesty/events.ini
- examples/workflow/inference/gw150914_gw170814-dynesty/workflow_config.ini
- examples/workflow/inference/gw150914_gw170814-emcee_pt/create_workflow.sh
- examples/workflow/inference/gw150914_gw170814-emcee_pt/events.ini
- examples/workflow/inference/gw150914_gw170814-emcee_pt/workflow_config.ini
Adds several example configuration files for pycbc inference. Also includes config files and run scripts for the inference workflow.
> Add inference config files

- bin/hdfcoinc/pycbc_coinc_hdfinjfind
As requested in #2955, this checks whether the attribute-hanging group exists (in the case of combine_statmap) or not (multiifo_statmap) and gets the relevant attributes according to this
> get hdfinjfind to work on multiifo_statmap files

- pycbc/inference/sampler/ultranest.py
- pycbc/io/hdf.py
* output logl along with samples for our standard plotting
* add support for cyclic parameters with ultranest
> update support for ultranest

- bin/hdfcoinc/pycbc_fit_sngls_binned
New argument to allow pycbc_fit_sngls_binned to generate trigger plots with irregular bin spacing in template duration.
> Irregular bins

- pycbc/detector.py
Correction in values of time
Correction in the calculation of position
> Changes in arm length value

- pycbc/types/array.py
Resetting the memory of the Array after the roll is applied, rather then before.
> Reset _saved in roll-function.

- setup.py
Requesting review from many people in european/more east timezones in order to get a quick review
> Prep for release v1.16.6

- setup.py
To incorporate #3403, #3402, #3399, and #3398 into a release.
First step of [these instructions](https://pycbc.org/pycbc/latest/html/release.html)
> Prep for release

- bin/pycbc_single_template
Added a hard high-frequency cutoff to pycbc_single_tempalte.
> Added high-frequency cutoff to pycbc_single_template.

- bin/pycbc_make_skymap
For certain purposes it might be useful to process multiple custom frames when using pycbc_make_skymap. I therefore added the ability for the code to handle a list of multiple frames per interferometer.
> Added ability to accept multiple frame files to pycbc_make_skymap.

- setup.py
Attempt to add in fix recommend in #3054
> patch to hack macs to work

- pycbc/inference/io/base_nested_sampler.py
- pycbc/inference/io/dynesty.py
- pycbc/inference/io/posterior.py
- pycbc/inference/sampler/dynesty.py
This PR addresses two issues:
i) Added an option to write nested samples in file.
ii) Fix the issue of 'not writing into backup file'.
> Dynesty: add nested samples and write to backup file

- bin/pycbc_live
- pycbc/frame/frame.py
* Use `setproctitle` to label each process with a useful string (helps debugging with `htop`)
* Reduce the time between attempts to read new frame files to 0.1 s
* Skip the CPU core check if SNR optimization is disabled
> Various little improvements to PyCBC Live

- pycbc/inference/models/brute_marg.py
Adds maxL phase, maxL loglr, plus all the additional stats from the underlying model at the maxL point to the brute force marginalization model's stats. The extra stats are only accessible by epsie and emcee, but it's also useful for making plots of the maxL waveform.
> Add maxl stats to brute force marginalization model

- bin/bank/pycbc_geom_aligned_bank
`--filter-points` option was not working due to wrong parameters used.
Corrected to use masses and aligned spins.
Tested working OK on py3.5
> Fix filter points option

- pycbc/io/hdf.py
For `[fit_by_template]`, support for `newsnr_sgveto_psdvar_threshold` is added to `sngl-stat =`.
> Added support for threshold

- bin/hdfcoinc/pycbc_fit_sngls_by_template
- bin/hdfcoinc/pycbc_multiifo_coinc_findtrigs
- pycbc/io/hdf.py
Implement an additional veto for the triggers near the gates to reduce the ammount of potential glitches in the area and improve the sensitivity of the search.
> Additional gating veto

- bin/hdfcoinc/pycbc_fit_sngls_split_binned
Add gating veto to pycbc_fit_sngls_split_binned
> Add gating veto to split hist trigger plots

- bin/inference/pycbc_inference_plot_dynesty_run
- bin/inference/pycbc_inference_plot_dynesty_traceplot
- pycbc/inference/sampler/dynesty.py
Adding few debugging plots for dynesty runs such as evolution of evidence, nlive points, likelihood with log volume. It makes use of the pre defined dynesty plotting functions.
> Adding dynesty diagnostic plots

- pycbc/workflow/inference_followups.py
This PR gives support for the dynesty debugging plots in `pycbc_make_inference_inj_workflow` and `pycbc_make_inference_workflow`.
> Add support for dynesty debugging plots in workflow

- bin/pycbc_inspiral_skymax
Updated the `pycbc_inspiral_skymax` to support the psd-variation statistics and finalize-events-template-rate.
> Added PSD Var and Finalize-events-template-rate

- pycbc/detector.py
@ahnitz I have created a new pull request here. Please let me know if this is fine.
> modified antenna pattern function definition to include non tensor polarizations

- pycbc/io/hdf.py
Mchirp and mtot are averaged from the singles to get values in the coinc table - I assume that this is in case we don't require exact match in the future.
This mean used the wrong number of ifos as the denominator; the number of operating rather than involved IFOs
This fixes the bug
> fix bug for mean mchirp m_tot in coinc inspiral table

- bin/all_sky_search/pycbc_coinc_hdfinjfind
- bin/minifollowups/pycbc_foreground_minifollowup
- bin/minifollowups/pycbc_page_coincinfo
- bin/plotting/pycbc_page_coinc_snrchi
- bin/plotting/pycbc_page_injtable
- bin/plotting/pycbc_page_recovery
Continuing on with pulling stuff from #3535, here's a few more executables. Here I deal with executables that were able to support *either* new or old style inputs. Here I just delete support for the old-style (and in one case add support that was missing for optimal SNRs).
These were all the codes I found that supported both formats, possibly there are others that I'm missing?
> More removal of old coinc code

- pycbc/waveform/ringdown.py
Introduce deviation parameters for the Kerr ringdown approximant
> Add deviations factors to ringdown

- bin/pycbc_make_skymap
- pycbc/detector.py
Corrections of two minor bugs.
Add a line to remove the temporary directories created by pycbc_make_skymap.
Changed a line in detector.py in the function project_wave() to avoid a Domain error when calculating the default reference_time.
> correction of minor bugs in make_skymap and detector.py

- .github/workflows/docker-build.yml
- Dockerfile
- docker/etc/docker-install.sh
- docker/etc/docker_commit.sh
- docker/etc/push_image.sh
It's going to take some work and trial+error before this works, but let's start here.
... For now this is starting on pull_request just so I can test it. I can change this to only do anything on release, or on all pushes to master like the old code. Building the mpi stuff for pycbc_inference takes ages!
> Add docker build to github actions

- .github/workflows/basic-tests.yml
- .github/workflows/build_venv.yml
- tools/docker_build_and_test.sh
- tools/docker_build_dist.sh
- tools/docker_build_prepssh.sh
- tools/test_coinc_search_workflow.sh
This adds the final part of Travis - the CVMFS virtualenv - into github actions. It will run on all push events, but will only be sent to CVMFS when a release. On Travis this would send to sugar, but I don't have credentials to do that, but if Duncan wants this, I can work to help him get it working again!
> Add venv build to github actions

- bin/all_sky_search/pycbc_coinc_hdfinjfind
- bin/hwinj/pycbc_generate_hwinj
- bin/minifollowups/pycbc_injection_minifollowup
- bin/minifollowups/pycbc_page_injinfo
- bin/plotting/pycbc_page_coinc_snrchi
- bin/plotting/pycbc_page_foundmissed
- bin/plotting/pycbc_page_injtable
- bin/plotting/pycbc_page_sensitivity
- bin/pycbc_inspinj2hdf
- bin/pycbc_optimal_snr
- bin/pycbc_single_template
- bin/workflows/pycbc_make_coinc_search_workflow
- examples/search/analysis.ini
- examples/search/executables.ini
- pycbc/detector.py
- pycbc/inject/injfilterrejector.py
- pycbc/workflow/core.py
- pycbc/workflow/injection.py
- pycbc/workflow/jobsetup.py
Also includes some random removals of two-ifo remannt code and removal of assuming an eff_dist column. 
Testing not yet done. I'm opening the PR for comments and to trigger the test suite.
> add support for injection finding using hdf format

- pycbc/waveform/waveform.py
Closes https://github.com/gwastro/pycbc/issues/3591
> Add SEOBNRv4HM_ROM to dictionary of filter time lengths

- setup.py
@hoyc1  Pointed this out, so here is a PR to update the python compatibility metadata
> update python compatibility metadata

- requirements.txt
This will allow Condor jobs running in a singularity container to communicate using HTChirp https://pypi.org/project/htchirp/
> Add HTChirp to PyCBC

- pycbc/vetoes/chisq.py
Wanted to clarify where the '2p-2' thing comes from ...
> fix bug in limited size dict, minor comments

- pycbc/types/array.py
Makes debugging a bit easier and removes some code duplication.
> More informative error messages in `array.py`

- bin/all_sky_search/pycbc_add_statmap
@GarethDaviesGW This fixes a few python3 issues that come up, and also an indentation bug.
> python3 fixes + bugfix in pycbc_add_statmap

- bin/all_sky_search/pycbc_fit_sngls_split_binned
Change variable name from old `sngl_stat` to new `sngl_ranking` in labels
> sngl stat to sngl_ranking in labels

- bin/pycbc_multi_inspiral
> Remove/comment out non-implemented options

- pycbc/strain/strain.py
This should resolve the issue I brought up in #3751 to fix gating in pycbc_multi_inspiral.
> Added the gating method option to the multi detector strain option group

- pycbc/transforms.py
This change is to fix the issue in #3762.
> Some transforms have same params in inputs/outputs

- bin/hdfcoinc/pycbc_page_foreground
- pycbc/io/hdf.py
This is very similar to #3767, but specifically for the v1.16  branch
There are a couple of minor content changes compared to that PR, as the output now gives the trigger information for every column in the trigger_merge file (as appropriate), as well as the template duration
> page_foreground output to hdf summary file

- pycbc/inference/models/__init__.py
- pycbc/inference/models/gated_gaussian_noise.py
- pycbc/inference/models/gaussian_noise.py
- pycbc/strain/gate.py
Co-authored-by: Collin Capano <collin.capano@aei.mpg.de>
Co-authored-by: Shilpa Kastha <shilpa.kastha@aei.mpg.de>
> Add gated Gaussian noise model, using inpainting for the gated times.

- pycbc/inference/models/__init__.py
- pycbc/inference/models/gated_gaussian_noise.py
Adds a version of the `GatedGaussian` that numerically marginalizes over polarization. Requires #3712 and #3713.
> Add gated gaussian model with marginalized polarization

- pycbc/types/timeseries.py
It would be handy to have a method of time series to do the resampling directly. This would enable the following kind of use
```
hp2 = hp.resample(1.0/2048)
```
> add a resample method to time series

- pycbc/filter/resample.py
- test/test_resample.py
> reduce memory of lfilter

- bin/inference/pycbc_inference
> fix mpi for ultranest  

- Dockerfile
See if this change fixes the Docker build problems...
> Do not install OSG 3.6

- pycbc/catalog/catalog.py
This is a minor change to add GWTC-3 confident events to `pycbc.catalog`.
> Adding GWTC-3 catalog

- .github/workflows/inference-workflow.yml
- bin/workflows/pycbc_make_inference_workflow
- examples/inference/single/single.ini
- examples/search/check_job.py
- examples/workflow/inference/small_test/gen.sh
- examples/workflow/inference/small_test/single.ini
- examples/workflow/inference/small_test/workflow.ini
- pycbc/workflow/core.py
In keeping with trying to have more of our workflows run in the CI, here is a minimal workflow for running pycbc inference. 
Depends on #3830
> add minimal inference workflow test

- pycbc/catalog/catalog.py
This is again a minor edit to update the GWTC catalogs list in `pycbc.catalog`
> Updated GWTC catalogs

- .github/workflows/search-workflow.yml
- bin/pycbc_submit_dax
- examples/search/executables.ini
- examples/search/gen.sh
- examples/search/submit.sh
- pycbc/workflow/pegasus_sites.py
- pycbc/workflow/pegasus_workflow.py
One thing I'm not sure about is the placement in the submit_now function as this is something that really should be in the core.py vesion. There's some confusion in the pegasus_workflow.py module overall. (i.e. a couple other places that implicitly assume stuff from core.py.....).
> add options to set submit and local site dirs

- examples/catalog/data.py
- examples/catalog/stat.py
- examples/dataquality/hwinj.py
- examples/dataquality/on.py
- examples/filter/chisq.py
- examples/filter/pass.py
- examples/filter/snr.py
- examples/gw150914/gw150914_h1_snr.py
- examples/gw150914/gw150914_shape.py
- examples/noise/frequency.py
- examples/noise/timeseries.py
- examples/psd/analytic.py
- examples/psd/estimate.py
- examples/psd/read.py
- examples/waveform/add_waveform.py
- examples/waveform/plot_detwaveform.py
- examples/waveform/plot_fd_td.py
- examples/waveform/plot_freq.py
- examples/waveform/plot_phase.py
- examples/waveform/plot_waveform.py
* Fixes #3845.
* Switches a few examples to use waveform approximants that do not require extra data files, or are more up to date.
* Improves a couple docstrings.
> Various improvements to example scripts

- bin/all_sky_search/pycbc_coinc_findtrigs
- examples/search/analysis.ini
Helps to fix #3876 , using @tdent 's suggested syntax
> Allow decimation thresholds in any order and with negative values

- bin/pycbc_optimize_snr
> Don't hardcode event ID format

- bin/workflows/pycbc_make_inference_inj_workflow
The recent changes related to pegasus 5 upgrades break the pycbc_make_inference_inj_workflow. Try to fix it. Work in progress.
> Fix pycbc_make_inference_inj_workflow

- pycbc/frame/frame.py
> Make a common PyCBC Live error more informative

- .github/workflows/inference-workflow.yml
- .github/workflows/search-workflow.yml
- .github/workflows/tmpltbank-workflow.yml
- .github/workflows/workflow-tests.yml
- docker/etc/docker-install.sh
- tools/docker_build_dist.sh
Trying to work around this problem: https://github.com/pypa/pip/issues/10851.
> Workaround for pip 22.0.x issue

- docs/psd.rst
- pycbc/psd/analytical.py
This is a minimal update to the documentation regarding analytical PSDs from `LALsimulation`, addressing the issue raised in https://github.com/gwastro/pycbc/issues/3938.
> PSD docs update

- bin/pycbc_merge_inj_hdf
Minor fix to deal with dict keys() no longer being a sequence.
> Fix for py3 dict keys

- pycbc/events/stat.py
> Patching ptf stat for older hdf hist files

- bin/minifollowups/pycbc_page_snglinfo
pycbc_sngl_minifollowup already does this.
> Allow default ranking stat as in sngl minifollowup

- bin/pycbc_live
- pycbc/detector.py
- pycbc/events/coinc.py
- pycbc/filter/matchedfilter.py
- pycbc/results/str_utils.py
- pycbc/waveform/bank.py
* Improve the documentation of the `--max-triggers-in-batch`, `--increment` and `--sync` arguments.
* Improve some logging messages, in particular correct the estimated memory used by `CoincExpireBuffer` objects.
> PyCBC Live doc and logging improvements

- bin/pycbc_optimal_snr
As we probably won't need to specify the 'columns' in future, use default correct dataset names derived from ifos.
> Allow for ifos option with default hdf dataset names

- pycbc/workflow/grb_utils.py
Also included a new argument to allow for different probability
coverage. Default is the same as old hardcoded value of 90%.
> More detailed description for GRB sky error func

- bin/pycbc_split_inspinj
- bin/workflows/pycbc_make_bank_verifier_workflow
- docs/install.rst
- pycbc/distributions/utils.py
- pycbc/frame/frame.py
- pycbc/inference/sampler/dynesty.py
- pycbc/noise/reproduceable.py
- pycbc/strain/strain.py
- pycbc/types/frequencyseries.py
- pycbc/types/timeseries.py
- pycbc/workflow/configuration.py
- requirements.txt
- setup.py
This PR closes #3995 by reimplmenting the guts of `pycbc.workflow.resolve_url` with a calls to `ciecplib`, which handles ECP authentication.
> Update ECP-authenticated HTTPS requests

- pycbc/cosmology.py
- requirements.txt
This attempts to implement a fix recommended by @duncanmmacleod in #4019 to fix a noted incompatibility with the upcoming astropy 5.1 release.
> fix astropy 5.1rc1 incompatibility

- pycbc/filter/matchedfilter_cpu.pyx
- tools/timing/correlate_perf.py
@spxiwh I was reminded in your PR that I had tested a parallel batch correlate at some point. Here's what I had tried in case it is useful to you.
> parallel batch correlate

- docs/inference.rst
- docs/inference/examples/hierarchical.rst
- examples/inference/hierarchical/data.ini
- examples/inference/hierarchical/dynesty.ini
- examples/inference/hierarchical/emcee.ini
- examples/inference/hierarchical/event1_inj.ini
- examples/inference/hierarchical/event2_inj.ini
- examples/inference/hierarchical/make_injections.sh
- examples/inference/hierarchical/model-event1_relbin.ini
- examples/inference/hierarchical/model-event2_gaussian.ini
- examples/inference/hierarchical/model-event2_margphase.ini
- examples/inference/hierarchical/model-event2_relbin.ini
- examples/inference/hierarchical/model.ini
- examples/inference/hierarchical/prior.ini
- examples/inference/hierarchical/run.sh
- examples/inference/hierarchical/run_test.sh
- pycbc/inference/io/base_hdf.py
- pycbc/inference/models/__init__.py
- pycbc/inference/models/base.py
- pycbc/inference/models/base_data.py
- pycbc/inference/models/brute_marg.py
- pycbc/inference/models/gated_gaussian_noise.py
- pycbc/inference/models/gaussian_noise.py
- pycbc/inference/models/hierarchical.py
- pycbc/inference/models/marginalized_gaussian_noise.py
- pycbc/inference/models/relbin.py
- pycbc/inference/models/single_template.py
- tools/pycbc_test_suite.sh
Adds a class for hierarchical models. Work in progress.
> Add a Hierarchical model to inference

- bin/pycbc_upload_xml_to_gracedb
- examples/live/run.sh
- pycbc/filter/resample.py
- pycbc/io/live.py
- pycbc/results/__init__.py
- pycbc/results/psd.py
In the offline event XML upload script, we want to include the PSD in the standard XML file to pass on to gracedb
Additional change needed to fix what looks like a change in the CreateREAL8FrequencySeries function in lal
~~I'm currently hitting an error with uploading, but think that's authentication rather than any change here~~ Fixed
> Add PSD to the initial XML document

- bin/all_sky_search/pycbc_add_statmap
- bin/all_sky_search/pycbc_coinc_statmap
Adding in the possibility to do hierarchical removal against exclusive IFAR in the add_statmap code
While fixing this, a couple of errors in the implementation of the significance module for the add_statmap code were found (Not flagged due to not using HR in the tests), these have been fixed
> Add statmap hierarchical removal against exclusive

- examples/inference/multisignal/rel.ini
- examples/inference/multisignal/rel.sh
- pycbc/inference/models/relbin.py
- pycbc/inference/models/relbin_cpu.pyx
- pycbc/types/array_cpu.pyx
This is a work in progress of adding in the features needed for the multi-signal relative model.
> multi-signal relative model 

- bin/live/pycbc_live_combine_single_fits
- Allowed the option to specify the percentile used for conservative fits
- Update to allow the non-use of the plotting option (previously broken)
- Making the plots look a bit nicer (grid, proper x limits)
> updates to live combined single-trigger fits (inc plotting)

- bin/pycbc_live
"Nothing should be uploaded to gracedb without the --enable-gracedb-upload option." (IW Harry, 13 Aug 2022)
> Rationalize upload options

- bin/pycbc_live
No functional change here, this mostly reformats the code in LiveEventManager to reduce the number of arguments and variables that have to be passed around.
> PyCBC Live: LiveEventManager cleanup

- bin/bank/pycbc_brute_bank
@ahnitz Fix for waveform_transforms not defined issue.
> fix waveform_transforms not defined issue

- bin/all_sky_search/pycbc_sngls_findtrigs
- bin/all_sky_search/pycbc_sngls_statmap
- bin/all_sky_search/pycbc_sngls_statmap_inj
- pycbc/events/significance.py
Adding two file which convert findtrigs output --> IFAR
Exclude_zerolag and add_statmap can be used with these as inputs without modification to those codes
> add statmap files for use with single-detector triggers

- pycbc/waveform/waveform_modes.py
> Set required parameters to td_required in td modes function

- docs/inference/examples/lisa_smbhb.rst
@ahnitz In this PR, I add a second link for BBHx to make it more visible.
> small update for LISA PE doc

- bin/pycbc_faithsim
- bin/pycbc_make_faithsim
Changes in `pycbc_make_faithsim` & `pycbc_faithsim` to use them with python3
> Template bank project : changes in faithsim codes 

- pycbc/conversions.py
We probably want to approximate the NS as a solid sphere (2/5), and not a spherical shell (2/3)
> Use solid sphere moment of inertia

- bin/pycbc_make_skymap
- bin/pycbc_optimize_snr
- bin/pycbc_upload_xml_to_gracedb
- pycbc/io/live.py
`createEvent()` becomes `create_event()`.
> Minor GraceDB API change

- companion.txt
Forgot to include this in #4178.
> Minimum required ligo-gracedb version

- bin/pycbc_get_ffinal
- bin/pycbc_inj_cut
- bin/pycbc_optimal_snr
- bin/pycbc_randomize_inj_dist_by_optsnr
- bin/pycbc_split_inspinj
- pycbc/inject/inject.py
- pycbc/results/pygrb_postprocessing_utils.py
- pycbc/types/frequencyseries.py
- pycbc/workflow/datafind.py
Fixing some seldom used code for a fairly old API change.
> Fix for LIGOLW API change (gz → compress)

- bin/pycbc_banksim
- bin/workflows/pycbc_make_bank_verifier_workflow
Add a way to read the approximant from an injection file in hdf format in the `pycbc_banksim` script
Fix the .`segs ` issue and write the properties of the input bank like : https://github.com/gwastro/pycbc/blob/07715891b47c77bb126803e94ca7acc1abaad91a/pycbc/workflow/psdfiles.py#L123
> Banksim jobs 

- bin/all_sky_search/pycbc_coinc_findtrigs
- bin/all_sky_search/pycbc_sngls_findtrigs
- bin/live/pycbc_live_combine_single_fits
- bin/live/pycbc_live_plot_combined_single_fits
- bin/live/pycbc_live_plot_single_trigger_fits
- bin/live/pycbc_live_single_trigger_fits
- pycbc/events/cuts.py
given updated stat and cuts modules, updates the live singles fitting code to actually use these modules rather than do its own thing the same
Some minor (one-line) changes to other codes, as the cuts module is called multiple times in this code, but once in others meaning that it spams the logging here without the change
> cleanup of pycbc live single trigger fits codes

- bin/workflows/pycbc_make_coinc_search_workflow
Add the command used to generate the workflow to its own page (rather than remaining in the metadata of other files only)
> Results page generation command

- pycbc/io/live.py
Another iteration of renaming / reorganizing lists of ifos, addressing https://github.com/gwastro/pycbc/issues/4189
> fix corner case in live event followup

- bin/plotting/pycbc_plot_vt_ratio
- examples/inference/single/single.ini
- pycbc/inference/models/single_template.py
- pycbc/inference/models/tools.py
- requirements.txt
Help messages for numerator/denominator, rename file handles
> Make it clear which VT is which, embiggen labels

- companion.txt
- pycbc/io/live.py
Addressing requests from Low Latency chairs
> add PASTRO_READY label

- docs/inference/examples/lisa_smbhb.rst
- examples/inference/lisa_smbhb/get.sh
- pycbc/psd/analytical_space.py
@ahnitz This PR fixes two minor issues in the LISA example and function Doc:
> Lisa fix doc

- docs/inference/examples/gw150914.rst
@ahnitz I noticed that the links in GW150914 example need to be updated.
> update GWOSC data links

- bin/live/pycbc_live_plot_single_trigger_fits
Fix bug in pycbc_live_plot_single_trigger_fits
> fix bug where --y-lim-upper was not actually used

- examples/gw150914/gw150914_shape.py
@ahnitz This minor fix is for GW150914 bandpass example.
> fix bandpass example in doc

- bin/pycbc_live
Pycbc live has _lots_ of too-long lines. This fixes or improves a few of them
> PEP8 / formatting

- bin/pycbc_single_template
This PR corrects a line of python2-ish code
> make sure array index is an integer

- bin/live/pycbc_live_single_trigger_fits
Bug where the `--cluster` option has no effect as the change is not propagated any further
> Live single trigger fits clustering Bugfix

- pycbc/psd/analytical_space.py
@ahnitz This PR fixes issues reported by Xisco @frcojimenez:
> fix small issues with LISA sensitivity curve

- bin/bank/pycbc_aligned_bank_cat
- bin/bank/pycbc_aligned_stoch_bank
- bin/bank/pycbc_geom_nonspinbank
- pycbc/tmpltbank/bank_output_utils.py
- pycbc/tmpltbank/option_utils.py
- Add a bank output to hdf option for some codes
- Add a wrapper to the bank output function to use hdf or xml as appropriate
> Allow (some more) banks to output to hdf

- companion.txt
- pycbc/waveform/waveform.py
- requirements.txt
- setup.py
> Revert "more physical rwrap for LISA SMBHB/SOBHB injection"

- companion.txt
- pycbc/waveform/waveform.py
- requirements.txt
- setup.py
@ahnitz This PR is a follow-up fix for https://github.com/gwastro/pycbc/pull/4322
> more physical rwrap for LISA SMBHB/SOBHB injection (follow-up fix)

- pycbc/io/hdf.py
Bug found by @PRAVEEN-mnl, where the time was not correct in the page_foreground hdf outputs, this was as the dtype was being set to be a float32 (I don't know why I thought this was a good idea before), but that isn't suitable for gps times
> page_foreground bugfix

- bin/plotting/pycbc_plot_vt_ratio
Up to now user could only provide one injection file on each side of the comparison.
> vt_ratio: enable comparisons with multiple files

- pycbc/waveform/spa_tmplt.py
> Allow f_final as well as f_upper, a bit more PEP8

- pycbc/inference/models/hierarchical.py
This enables people to make plots with z-arg snr again with hierarchical based likelihoods. For the regular hierarchical it adds the lognl from each submodel (assumption of independent noise). For multisignal, it picks one (assumption of identical noise). These assumptions match the models, so I think this is correct. It also is run in a try/except in cases where a submodel for its own purposes can't produce a lognl. 
@WuShichao This should enable you to plot with SNR for your tests. Please give it a try! (requires running the inference with this patch included)
> add lognl for hierarchical models to output files

- .github/workflows/basic-tests.yml
- .github/workflows/inference-workflow.yml
- .github/workflows/search-workflow.yml
- .github/workflows/tmpltbank-workflow.yml
- .github/workflows/tut-test.yml
- .github/workflows/workflow-tests.yml
- tools/einsteinathome/pycbc_etch64_compile-usr-local.sh
- tools/install_travis.sh
https://github.com/actions/runner-images/issues/6894 recommends we do this to try to reduce failures when using apt-get within the github CI runners.
> Try to deal with flaky failures when apt-getting

- pycbc/inference/models/relbin.py
- pycbc/inference/models/relbin_cpu.pyx
This adds in several missing marginalization combinations for the relative model. These include pol + earth rotation and pol + time + earth rotation.
> add in several missing marginalization combinations

- pycbc/types/config.py
> Remove default sections from get_subsections

- bin/pygrb/pycbc_grb_inj_finder
retain single ifo injection information and store in hdf output file
> Upgrades to pycbc_grb_inj_finder

- bin/pycbc_optimal_snr
It is tested and work as expected.
> Simple bugfix for optimal snr

- docs/inference/examples/lisa_smbhb_ldc_pe.rst
- examples/inference/lisa_smbhb_inj/injection_smbhb.ini
- examples/inference/lisa_smbhb_inj/lisa_smbhb_relbin.ini
- examples/inference/lisa_smbhb_ldc/lisa_smbhb_relbin.ini
@ahnitz @spxiwh @ConWea This PR updates the doc a little bit, preparing for the upcoming code https://github.com/gwastro/pycbc/pull/4289 and https://github.com/gwastro/BBHX-waveform-model/tree/multiband I have tested those 2 examples in the LISA doc, almost the same as the current results in the doc (This also suggests the latest code in https://github.com/gwastro/pycbc/pull/4289 and https://github.com/gwastro/BBHX-waveform-model/tree/multiband will not affect SMBHB PE):
(1) LDC example
(2) Injection example
> update two LISA docs

- .github/workflows/basic-tests.yml
- bin/inference/pycbc_inference_model_stats
- docs/_include/inference_example_lisa_smbhb_inj.sh
- docs/_include/inference_example_lisa_smbhb_ldc.sh
- docs/_include/inference_example_margtime.sh
- docs/_include/inference_example_relative.sh
- docs/_include/inference_example_single.sh
- docs/_include/inference_example_single_marg.sh
- docs/_include/inference_sampler.sh
- docs/_include/injection_smbhb.ini
- docs/conf.py
- examples/inference/lisa_smbhb_inj/run.sh
- examples/inference/lisa_smbhb_ldc/run.sh
- examples/inference/margtime/run.sh
- examples/inference/margtime/run_inj.sh
- examples/inference/relative/run.sh
- examples/inference/relmarg/run.sh
- examples/inference/samplers/run.sh
- examples/inference/single/run.sh
- examples/inference/single/run_instant.sh
- pycbc/inference/models/tools.py
This is a WIP PR to see if we can make the CI faster
Trying so far
* run unittest same time as checking help messages 
* run search / inference tests together
* explicitly run multiple scripts at a time which are needed to generate the docs page
> make ci faster

- requirements-igwn.txt
Need a version that supports scitokens
> dqsegdb2 update

- pycbc/pnutils.py
- pycbc/waveform/waveform.py
This allows SEOBNRv5_ROM to convert to time domain, thereby injection with it.
> Add time length estimator for SEOBNRv5_ROM

- pycbc/events/coinc.py
Does what it says in the title
> Allow background binning by seobnrv5 duration

- bin/all_sky_search/pycbc_template_kde_calc
- bin/all_sky_search/pycbc_template_kde_max
The script produces a output file which have same format as template kde files but this takes maximum of KDEs from 2 or more files.
> Add script to take maximum over 2 or more KDEs 

- bin/all_sky_search/pycbc_bin_trigger_rates_dq
Change for consistency with other functions
> Change f-low to f-lower

- bin/minifollowups/pycbc_plot_trigger_timeseries
- pycbc/workflow/minifollowups.py
Allow all rankings from `pycbc/events/ranking` in `pycbc_plot_trigger_timeseries`
> Trigger timeseries ranking

- pycbc/pnutils.py
> Refactor get_inspiral_tf, add SEOBNRv5 and IMRPhenom support

- bin/plotting/pycbc_plot_dq_flag_likelihood
Addresses https://github.com/gwastro/pycbc/issues/4484
> Dq plotting

- pycbc/events/eventmgr.py
I have not bothered to add a context manager as the class is used only here.
> Close the file after writing events.

- examples/inference/lisa_smbhb_ldc/get.sh
@spxiwh Please check it. This PR fixes the curl issue.
> Update get.sh in LISA LDC doc example

- bin/pycbc_multi_inspiral
- bin/pygrb/pycbc_pygrb_grb_info_table
- bin/pygrb/pycbc_pygrb_plot_coh_ifosnr
- bin/pygrb/pycbc_pygrb_plot_injs_results
- bin/pygrb/pycbc_pygrb_plot_skygrid
- bin/pygrb/pycbc_pygrb_pp_workflow
- pycbc/conversions.py
- pycbc/workflow/matched_filter.py
A couple bugs have appeared in the new PyGRB workflow.
The first appears in the remnant mass calculation for NSBH injections. There was an issue with some tricky indexing that was a straightforward fix (note that the same sort of call is done in the same function).
The second involved `fp` and `fc` being calculated within one branch of an if statement, but the output is needed elsewhere. Moving it outside of the conditional statement resolves the issue.
> PyGRB bugfixes/corrections

- bin/all_sky_search/pycbc_calculate_dqflag
- bin/all_sky_search/pycbc_fit_sngls_split_binned
- bin/minifollowups/pycbc_foreground_minifollowup
- bin/minifollowups/pycbc_plot_trigger_timeseries
- examples/inference/lisa_smbhb_ldc/get.sh
There are already-reviewed commits that need merging onto the v23 release branch. Last call if anyone wants to add anything else, please comment the number below.
Please let me merge this so that the commits don't get squashed!
> Cherry pick things onto v23 release branch

- setup.py
Bump release number before making v2.3.1 release.
> Bump release number

- bin/plotting/pycbc_plot_singles_vs_params
- pycbc/workflow/pegasus_sites.py
- setup.py
Merging two patches from the main branch onto the v23 release branch, and bumping release number to allow for v2.3.2 release to be made.
> Release branch additions

- pycbc/fft/mkl.py
This prototypes some fixes suggested by intel for the large size FFT issues we had seen.
> fixes to mkl for large sizes

- pycbc/psd/__init__.py
- pycbc/psd/estimate.py
@ahnitz This PR fixes the PSD length inconsistency issue.
> Fix psd len issue

- bin/minifollowups/pycbc_foreground_minifollowup
- bin/minifollowups/pycbc_injection_minifollowup
- bin/minifollowups/pycbc_sngl_minifollowup
- bin/minifollowups/pycbc_upload_prep_minifollowup
- bin/workflows/pycbc_make_offline_search_workflow
- pycbc/workflow/minifollowups.py
- pycbc/workflow/psd.py
- setup.py
- tools/venv_transfer_commands.sh
Adding two more patches to the next v2.3 release
> Releasing v2.3.5

- bin/all_sky_search/pycbc_bin_trigger_rates_dq
- bin/plotting/pycbc_page_dq_table
- bin/plotting/pycbc_page_template_bin_table
- bin/plotting/pycbc_plot_dq_flag_likelihood
- bin/workflows/pycbc_make_offline_search_workflow
- pycbc/workflow/plotting.py
This MR adds some tables of information to the DQ results pages, as requested by LVK reviewers
> Added tables to dq results pages

- .github/workflows/basic-tests.yml
- .github/workflows/distribution.yml
- .github/workflows/inference-workflow.yml
- .github/workflows/search-workflow.yml
- .github/workflows/tmpltbank-workflow.yml
- .github/workflows/workflow-tests.yml
> Revert "MNT: upgrade upload/download-artifact GitHub actions"

- bin/all_sky_search/pycbc_bin_trigger_rates_dq
- bin/all_sky_search/pycbc_prepare_xml_for_gracedb
- bin/plotting/pycbc_page_dq_table
- bin/plotting/pycbc_page_template_bin_table
- bin/plotting/pycbc_plot_dq_flag_likelihood
- bin/pycbc_convertinjfiletohdf
- bin/workflows/pycbc_make_offline_search_workflow
- pycbc/_version.py
- pycbc/_version_helper.py
- pycbc/workflow/plotting.py
- setup.py
- tools/pycbc_test_suite.sh
Add 4 commits below to create the v2.3.6 release.
> V236 release

- tox.ini
* specify an older branch of BBHx in tox.ini
* Update tox.ini
> specify an older branch of BBHx in tox.ini (#4672)

- pycbc/types/frequencyseries.py
Bug fix for saving .xml format
Line added at #407
> frequencyseries.py modified to fix the bug while saving file in .xml format

- pycbc/results/psd.py
- tox.ini
Rather than a hard coded minimum use the minimum value we are going to plot.  Also put the calculation of the asd we are plotting on a single line rather than splitting over 2.
> Properly fix ASD plot minimum value

- pycbc/inference/sampler/nessai.py
Update the nessai interface to allow the user to set the `output` option in an ini file. If not specified, the code falls back to the path to the checkpoint file rather than the CWD.
@HumphreyWang hopefully this addresses the issue you were having.
> Allow the user to specify the output directory for nessai

- bin/all_sky_search/pycbc_fit_sngls_split_binned
- bin/live/pycbc_live_combine_single_significance_fits
- bin/live/pycbc_live_plot_combined_single_significance_fits
- bin/live/pycbc_live_plot_single_significance_fits
- bin/live/pycbc_live_single_significance_fits
- bin/plotting/pycbc_plot_multiifo_dtphase
- bin/workflow_comparisons/offline_search/pycbc_plot_vt_ratio_vs_ifar
Updating where my name is given with my old surname
This is a: minor annoyance
This change affects: the offline search
This change changes: comments
This change: has been proposed using the [contribution guidelines](https://github.com/gwastro/pycbc/blob/master/CONTRIBUTING.md)
I realised today that as it is three years since my name changed, I should probably update any outdated cases
I ran `sed -i s/"Gareth S. Davies/Gareth S. Cabourn Davies/g" bin/*/*`
> Update my surname in comments

- .github/workflows/distribution.yml
- .github/workflows/mac-test.yml
This is a: bug fix, new feature, efficiency update, other (please describe)
This change changes: documentation, result presentation / plotting, scientific output
This change will: break current functionality, require additional dependencies, require a new release, other (please describe)
> use macos 12

- examples/inference/lisa_smbhb_ldc/lisa_smbhb_relbin.ini
This change affects: Set TDI version for the upcoming BBHx plugin update.
This change changes: documentation,
> set TDI version in LDC example

- bin/pygrb/pycbc_pygrb_page_tables
Sorted ifos event_ids by the network one, allowing to display the correct result.
> Page tables bug fix

- bin/pygrb/pycbc_grb_inj_finder
- bin/pygrb/pycbc_pygrb_plot_coh_ifosnr
- bin/pygrb/pycbc_pygrb_plot_snr_timeseries
This PR modifies three executables
* `pycbc_grb_inj_finder` is where the first bug is.
* `pycbc_pygrb_plot_coh_ifosnr` is where the second bug is.
* `pycbc_pygrb_plot_snr_timeseries` has code-climate like changes (white spaces, line length, unused imports) and an improved docstring.
The bug fixes:
1. `pycbc_grb_inj_finder` looks for injections in results files coming from processing various combinations of split bank files and split injections files.  Within each of these files, the `event_id` is unique, but in gathering found injections in a new, combined file, these `event_id`s cannot be simply copied over because their uniqueness is not guaranteed.  A simple example, is one in which 2 injections with `event_id`=0 from 2 different files need to be kept.  To fix bug, a new `event_id` is …
> Fix 2 bugs with event_id of injections

- bin/pygrb/pycbc_pygrb_minifollowups
- bin/pygrb/pycbc_pygrb_plot_coh_ifosnr
This is mostly making sure indentations and line lengths are correct in `pycbc_pygrb_plot_coh_ifosnr` and `pycbc_pygrb_minifollowups`.  In the latter case, I also removed unnecessary variables and options.
The scripts were successfully tested within a full PyGRB workflow run.
> Cosmetics for pycbc_pygrb_plot_coh_ifosnr and pycbc_pygrb_minifollowups

- bin/minifollowups/pycbc_upload_prep_minifollowup
- pycbc/workflow/minifollowups.py
This is a user experience enhancement
During testing for (e.g. #4769), there isnt much about the progress of the upload_prep minifollowup - add it!
Adding logging lines
Code still runs, more logging produced
> Add more logging to the upload_prep minifollowup

- bin/live/pycbc_live_collated_dq_trigger_rates
- bin/live/pycbc_live_combine_dq_trigger_rates
I forgot to include this in https://github.com/gwastro/pycbc/pull/4866 after Gareth fixed the bug with https://github.com/gwastro/pycbc/pull/4879
> Use HFile for outputs

- bin/all_sky_search/pycbc_coinc_findtrigs
Solution as suggested by Yifan
closes #5014
> coinc_findtrigs index issue

- bin/pygrb/pycbc_grb_inj_finder
- bin/pygrb/pycbc_grb_trig_cluster
- bin/pygrb/pycbc_grb_trig_combiner
- pycbc/psd/read.py
Random cleanup of legacy logging messages in PyGRB code, and fix an incorrect docstring in the PSD module.
> Logging cleanup and docstring fixes

- pycbc/results/pygrb_postprocessing_utils.py
This change changes:  scientific output
This change will: break current functionality, require additional dependencies, require a new release, other (please describe)
Currently, empty veto definer files are affecting postprocessing on the PyGRB side.
Will update this once we understand the problem better
> PyGRB: Veto fix #2

- requirements.txt
- tox.ini
* Try finding source of error
* Is it *just* this script?
* Revert "Is it *just* this script?"
This reverts commit 858cbf8326f4f90dc134ae78a112923a89009e4d.
* Try avoiding mkl blas
* Avoid failing sphinx
* Revert lalsuite pin
> Fix CI failures (#5051)

- requirements.txt
CI failures again - looks like this happened just after a release of sphinx (8.2.1), so I tried excluding that release.
After suggestions below, I have pinned to < 8.2.0 and added a FIXME
> Sphinx version CI fix

- bin/pycbc_multi_inspiral
- bin/pygrb/pycbc_grb_inj_finder
- bin/pygrb/pycbc_make_offline_grb_workflow
- bin/pygrb/pycbc_pygrb_efficiency
- bin/pygrb/pycbc_pygrb_grb_info_table
- bin/pygrb/pycbc_pygrb_minifollowups
- bin/pygrb/pycbc_pygrb_page_tables
- bin/pygrb/pycbc_pygrb_plot_chisq_veto
- bin/pygrb/pycbc_pygrb_plot_coh_ifosnr
- bin/pygrb/pycbc_pygrb_plot_injs_results
- bin/pygrb/pycbc_pygrb_plot_skygrid
- bin/pygrb/pycbc_pygrb_plot_snr_timeseries
- bin/pygrb/pycbc_pygrb_plot_stats_distribution
- pycbc/events/coherent.py
- pycbc/results/pygrb_postprocessing_utils.py
- pycbc/workflow/grb_utils.py
Simply cleaning up some of the PyGRB files by using `flake8` and following up on all its output.  Mostly whitespaces, indentations, and line lengths.
> flake8 on some PyGRB results code files

- .github/workflows/basic-tests.yml
- Dockerfile
- bin/pygrb/pycbc_pygrb_efficiency
- bin/pygrb/pycbc_pygrb_plot_injs_results
- pycbc/results/pygrb_postprocessing_utils.py
* Workaround for incompatibility between Pegasus and stashcp (#5031)
* Get LAL aux data from Zenodo and cache it (#5099)
* Fix PyGRB postproc in a corner case (#5102)
> Cherry-picks for v2.8.2

- pycbc/conversions.py
This PR adds a waveform transform that applies hypertriangulation to a set of indistinguishable parameters. The code is based on a scheme by Buscicchio et al. (https://doi.org/10.1103/PhysRevD.100.084041) to prevent label-switching when doing PE.
This is a new feature. Changes are applied to `pycbc.conversions` to add the transform itself and to allow for calls during inference or I/O.
Label switching can occur when performing Bayesian PE with a set of indistinguishable parameters. If the N parameters are unlabeled, there will be N! modes in the posterior, which can greatly slow down convergence for high numbers of parameters. A simple example of this is primary/secondary mass in CBC systems, which can be remedied by enforcing $m_1 \geq m_2$ via the existing `primary_mass` and …
> Add waveform transform to apply hypertriangle map

- bin/pycbc_multi_inspiral
- bin/pygrb/pycbc_grb_trig_combiner
- examples/multi_inspiral/check_gw170817_trigs.py
- examples/multi_inspiral/clean.sh
- examples/multi_inspiral/faceon_faceaway.sh
- examples/multi_inspiral/gw170817_h.sh
- examples/multi_inspiral/gw170817_hl.sh
- examples/multi_inspiral/gw170817_hlv.sh
- pycbc/filter/resample.py
- pycbc/pnutils.py
- pycbc/results/pygrb_postprocessing_utils.py
- pycbc/results/scatter_histograms.py
- pycbc/vetoes/autochisq.py
- pycbc/vetoes/bank_chisq.py
- pycbc/workflow/configuration.py
- pycbc/workflow/segment.py
- setup.py
- tools/pycbc_test_suite.sh
* #5107
* #5108
* #5113 
* #5114
* #5115
* #5118
* #5119
> Cherry-pick for v2.8.3

- bin/pycbc_multi_inspiral
- bin/pygrb/pycbc_make_offline_grb_workflow
- bin/pygrb/pycbc_pygrb_plot_chisq_veto
- pycbc/events/coherent.py
- pycbc/events/eventmgr.py
- pycbc/workflow/grb_utils.py
This PR collects small improvements made in response to comments/questions by PyGRB reviewers.
This change affects: PyGRB.
At the moment of writing this changes modifies: docstrings, captions, comments in code files, and avoids operations that are not needed.
> PyGRB improvements suggested by reviewers

- bin/pygrb/pycbc_make_offline_grb_workflow
- bin/pygrb/pycbc_pygrb_plot_skygrid
- bin/pygrb/pycbc_pygrb_results_workflow
- pycbc/workflow/grb_utils.py
This is a new version of `pycbc_pygrb_plot_skygrid` script that will include sky grid over input distribution of the GRB and over the antenna pattern of each detector.
This change affects PyGRB
This change changes result presentation / plotting.
This PR is useful for results presentation for PyGRB and for the better understanding of the sky grid with respect to the input sky location of the GRB.
The code is able now to plot the sky grid over the input distribution of the GRB sky location and over the antenna pattern of each detector that was on at this time.
This change has been tested with several cases and results can be find in this [link](https://ldas-jobs.ligo.caltech.edu/~thomas.jacquot/Plot_Sky_Grid/) and will be tested in a PyGRB workflow soon. (Test workflow here : …
> Upgrade of `pycbc_pygrb_plot_skygrid` script

- .github/workflows/basic-tests.yml
- .github/workflows/distribution.yml
- .github/workflows/mac-test.yml
- .github/workflows/tut-test.yml
- pycbc/distributions/angular.py
- pycbc/distributions/arbitrary.py
- pycbc/distributions/bounded.py
- pycbc/distributions/joint.py
- pycbc/distributions/uniform.py
- pycbc/distributions/uniform_log.py
- pycbc/inference/io/__init__.py
- pycbc/inference/io/base_hdf.py
- pycbc/inference/io/base_mcmc.py
- pycbc/inference/io/dynesty.py
- pycbc/inference/models/__init__.py
- pycbc/inference/models/base.py
- pycbc/inference/sampler/base_mcmc.py
- pycbc/inject/inject.py
- pycbc/results/str_utils.py
- pycbc/tmpltbank/bank_output_utils.py
- pycbc/tmpltbank/coord_utils.py
- pycbc/waveform/bank.py
- pycbc/waveform/generator.py
- pycbc/waveform/parameters.py
- pycbc/waveform/waveform.py
- pycbc/waveform/waveform_modes.py
- setup.py
> Add python 3.13
