- bin/hdfcoinc/pycbc_coinc_findtrigs
- bin/hdfcoinc/pycbc_coinc_hdfinjfind
- bin/hdfcoinc/pycbc_coinc_statmap
- bin/hdfcoinc/pycbc_coinc_statmap_inj
This set of patches stores the single detector analyzed segments that are used in the find coinc code and propagates that through. This is useful for analyzing the timeslide information.
Built on https://github.com/ligo-cbc/pycbc/pull/3 
(the patches corresponding to that will disappear automatically if that is merged)
> Statmap segment staging

- bin/hdfcoinc/pycbc_make_hdf_coinc_workflow
- pycbc/workflow/configuration.py
Make injections optional. Currently, if you don't include an injections section the injection setup function will fail. Now, it will return an empty list.
> allow injections to be skipped by not including injection sections

- bin/pycbc_inspiral
- pycbc/events/events.py
This extends the current functionality of the --injection-window option to keep only those triggers near an injection, even where there are multiple injections / segments and the slice operation itself cannot be changed. This is implemented as a final cleanup step, like the newsnr cut.
> remove triggers not near injections

- pycbc/inject.py
- pycbc/waveform/fctmplt.py
- pycbc/waveform/spa_tmplt.py
- pycbc/waveform/waveform.py
This starts to remove lalinspiral as a requirement for PyCBC by replacing the chirp time function and hiding the remaining imports. 
* One issue remains and that is the NR injection code is from lalinspiral.
If we can find a replacement for that or drop support, then lalinspiral can be removed as a requirement entirely. In any case, all imports are now hidden, so if lalinspiral is not installed and lalinspiral functionality is not called, then the code will function as expected.
> Lalinspiral staging

- bin/pycbc_inspiral
- pycbc/events/events.py
This adds options in pycbc_inspiral to keep the loudest X number of triggers every Y seconds. This reduces the storage requirements of PyCBC when used in conjunction with #19. Initially, this is simply a storage improvement. If it turns out to work generally then it implies some further performance optimizations that could be used in conjunction with the heirarchical inspiral search. 
BNS run with 4 injection sets (injection every 130 s)
Original: 16 GB 
Keep Loudest 100 triggers every 2 seconds -> 1.5 GB for single inspiral triggers 
Sensitivity for the BNS search under these settings was unchanged. Although, I expected that as I found 100 by plotting the number of nearby triggers louder than the trigger found in coincidence for each significant injection. I think conservative settings …
> add option to keep loudest X triggers every Y seconds

- bin/pycbc_inspiral
- pycbc/vetoes/bank_chisq.py
The most recent patch to add correct DOF for bank chisq also made bank chisq mandatory. These commits fix that.
> allow bank chisq to not be used

- bin/hdfcoinc/pycbc_plot_background_coincs
- setup.py
This adds a very basic plot script for coinc background triggers. It should be easily extendable for more axis paramters, but initially only those in the statmap hdf files are supported. Inspired by Tito's plot script for single detector triggers. All plots exclude zerolag coincident triggers. 
Example plot.
> add plot script for background coinc triggers

- bin/hdfcoinc/pycbc_page_snrchi
Make NewSNR contours thinner and labeled, fix an issue with hexagon edges, make extremal triggers more visible and remove unused imports.
Before:
After:
> Make single SNR-chi² plot more readable

- pycbc/events/events.py
- pycbc/events/threshold_cuda.py
Catch invalid cluster window length (see https://github.com/ligo-cbc/pycbc/issues/31). Also remove the slow unused version of the clustering function and rename the optimized version actually in use.
> pycbc.events: fixes to clustering code

- pycbc/workflow/jobsetup.py
The class PycbcSqliteSimplifyExecutable class generated a warning message if num_inputs is greater than 20, but it does not import logging, so the module fails with
NameError: global name 'logging' is not defined
> added import of logging module so the wanrning message on line 879 works

- bin/hdfcoinc/pycbc_coinc_hdfinjfind
- bin/hdfcoinc/pycbc_page_snrchi
- bin/hdfcoinc/pycbc_plot_singles_vs_params
- pycbc/events/veto.py
This adds the option to select segments by ifo and segment name when finding indices of some time vector. This also updates all the calling executables.
This is the first of several incremental changes, that will make pull request #10 a lot easier to implement. A future feature, not implemented here, will expose this functionality through the command line so all the relevant pycbc executables can take standard segment xml files (which may contain multiple segment lists) and process only the set of segments they need correctly.
> add option to select segments by ifo/segment_name to the indices_within/outside functions

- pycbc/types/array.py
- pycbc/types/frequencyseries.py
- pycbc/types/timeseries.py
Add the ability to save and load pycbc types to hdf files using the 'save' method or the load_* methods.
> save/load array, timeseries, frequencyseries to hdf

- bin/pycbc_inspiral
- pycbc/__init__.py
This patch allows one to start a pycbc_inspiral process in non-verbose mode, but later turn verbosity on/off by sending the process a SIGUSR1 signal (kill -USR1 pid). This allows one to debug long-running jobs directly in production. I can use this also in banksims, bank generators etc if people think it is useful.
> Enable toggling verbose mode via SIGUSR1

- pycbc/filter/zpk.py
- pycbc/results/render.py
- pycbc/workflow/splittable.py
- tools/timing/match_perf.py
4 commits:
* First fixes a bug where `errString` should have been `err_string`.
* Second removes a reimport of `math.log`.
* Third indents `pycbc.results.render` to 4 spaces instead of 3.
* Fourth removes an unused `scipy.signal` import in the zero-pole-gain filter module.
> Cosmetic fixes

- bin/pycbc_submit_dax
This fixes pycbc_submit_dax after the last change, which accidentally left the old option parsing within the script. Also moves up the logging and error checking of the script back to the top so all lines are caught.
> fix pycbc_submit_dax

- pycbc/tmpltbank/bank_output_utils.py
Populates the IFO column when `output_sngl_inspiral_table` is called by tmplate bank placement code.
> Add IFO to process table in output_sngl_inspiral_table function

- bin/hdfcoinc/pycbc_coinc_statmap_inj
This adds an option to skip calculating a separate background when the injection trigger is too quiet for it to stick above background (say combined NewSNR < 8). This can be used in conjuction with existing loudest-keep-value, where only coincs above some value are kept for injection timeslides. Also some minor improvement to the help messages.
> cost savings in pycbc_coinc_statmap_inj

- pycbc/workflow/datafind.py
Cast glue.datafind cache segments to integer (both the sec and nsec portions separately). In the case where there are missing frames and the user has requested to update the analyzed times, this causes failures as the segments cannot be converted to LIGOTimeGPS format.
> ensure datafind returns integer segments

- bin/hdfcoinc/pycbc_coinc_findtrigs
This makes the template bank parameters (mass1, mass2, spin1z, spin2z) visible within pycbc_coinc_findtrigs, so they can now be used by ranking statistic classes.
> expose template bank parameters in pycbc_coinc_findtrigs

- bin/hdfcoinc/pycbc_coinc_findtrigs
- bin/hdfcoinc/pycbc_coinc_hdfinjfind
- bin/hdfcoinc/pycbc_page_snrchi
- bin/hdfcoinc/pycbc_plot_singles_vs_params
This adds support to the following executables for a segment-name options which selects the segment list from the given veto file. It is optional, and if not given, all segments in the file are assumed to be used (as was assumed by the codes previously). 
- pycbc_coinc_findtrigs
- pycbc_coinc_hdfinjfind
- pycbc_plot_singles_vs_params
- pycbc_page_snrchi
These are all the codes which explicitly took a segment xml file in the hdf coinc workflow. 
Notes: 
- Forked from #37
> add support to pycbc executables for segment-name option

- bin/hdfcoinc/pycbc_make_hdf_coinc_workflow
This completes my earlier commit, getting the config file to show in HTML report pages. Alex, I'm not sure my handling of the file is the way it's supposed to be, but I couldn't find a better functionality in pycbc.workflow. Anyway, it seems to do the job.
> Place parsed ini file in results directory

- bin/hdfcoinc/pycbc_page_coinc_snrchi
This patch (if I've done this right) fixes an issue I've seen where pycbc_page_coinc_snrchi fails with:
File "/.auto/home/spxiwh/lscsoft_git/executables_master/lib/python2.7/site-packages/PyCBC-8d7236-py2.7.egg/EGG-INFO/scripts/pycbc_page_coinc_snrchi", line 38, in <module>
snr = f['snr'][:][tid]
IndexError: unsupported iterator index
I don't understand why others haven't hit this problem though! Is it a debian or dependancy version problem?
> Pycbc_page_coinc_snrchi fails for me

- bin/pycbc_submit_dax
- bin/pycbc_submit_dax_stampede
Not having a local-directory option and having to set TMPDIR is a *real* pain. TMPDIR is used for other things (for e.g. the scipy compilation directory), and I don't want to *have* to have that the same as the pegasus submit directory. Not to mention that I am repeatedly forgetting to set this and having dags fail.
This patch adds the option to specify a --local-dir option, which can be used for clusters like ARCCA and vulcan, where TMPDIR is not set by default. In the case that the option is not given the code will behave as before (--tmpdir="" to mktemp is equivalent to --tmpdir=${TMPDIR} .. and if ${TMPDIR} is not set, *that* will default to /tmp)
..... Is there a reason this is written in bash? This is *Py*CBC not *Bash*CBC ... We chose python because it is easier to code and read …
> Add local directory option to pycbc_submit_dax

- setup.py
Add mpld3 to dependencies. This uses the dependency links to pull mpld3 from my fork which I have prepared to be installable. This should work temporarily until mpld3 proper uploads their next release. 
Please let me know if this works for you.
> add mpld3 to dependencies

- pycbc/results/templates/concrete.html
- setup.py
Add pycbc-pylal as an install depency to pycbc. This should make it so python setup.py install will download pycbc-pylal and auto install it. At the moment, this sets it to pull the master version. If a tag is available, perhaps we should point to that?
> add pycbc-pyla and pycbc-glue as dependence

- setup.py
Add cuda to an extra requires sections. This doesn't do much at the moment, but in the future you'll be able to do 
pip install pycbc[cuda] 
To get all your cuda dependencies satisfied.
> add cuda requirements to extra package cuda

- pycbc/workflow/legacy_ihope.py
Use Tito's int_gps_time_to_str function for lalapps_{tmpltbank/inspiral} so that we can run the review ini files with those executables as well.
> use int_gps_time_to_str for legacy inspiral/tmpltbank

- docs/formats/hdf_format.rst
- docs/index.rst
This starts to add some documentation of the HDF format files used in the PyCBC workflow. Added here are only two of them.
* Single trigger format (pycbc_inspiral)
* Combined single trigger format (pycbc_coinc_mergtrigs)
> Add some basic documentation of hdf formats

- bin/hdfcoinc/pycbc_coinc_statmap_inj
- bin/hdfcoinc/pycbc_make_hdf_coinc_workflow
- bin/pycbc_make_coinc_workflow
- pycbc/workflow/coincidence.py
- pycbc/workflow/plotting.py
- pycbc/workflow/segment.py
The segment setup functions used by the hdf workflow now return the list of segment names that should be used. Executable that apply vetoes now get the segment name to use from the workflow.
> Pass segment name to executables can apply vetoes

- bin/hdfcoinc/pycbc_page_sensitivity
Add option to use whatever the ranking statistic is as the x-axis in pycbc_page_sensitvity.
This can be turned on by 
--sig-type stat
> add ability to plot ranking statistic in x-axis 

- docs/install.rst
- docs/install_lalsuite.rst
- docs/resources/build_new_lalsuite.sh
Update the references to glue/pylal to refer to pycbc-glue/pycbc-pylal and point to their github pages. Also update the list of dependencies to reflect the current requirements.
> update dependencies and references to glue/pylal in pycbc install instructions

- pycbc/results/plot.py
Add version metadata by default to figures saved with save_fig_with_metadata. 
They will now have a 'version' key that contains the verbose version message.
> add version metadata to figures

- bin/pycbc_make_html_page
- bin/pycbc_write_results_page
- pycbc/results/__init__.py
- pycbc/results/render.py
- pycbc/results/templates/files/file_default.html
- pycbc/results/versioning.py
Here is a patch to add a versioning tab to the new html pages. An example of this is here:
https://galahad.aei.mpg.de/~spxiwh/LVC/ER7/analyses/BBH_alignedspin/run7/
... There are also changes in pycbc_write_results_page, and I have also tested that that still works.
This html infrastructure produces some nice pages, but it was rather opaque to me to see how to do this simple case of just adding small blocks of text. I really don't know how to go about reproducing section II on the new output pages! Is there any advice for coding these pages, or any pointers I should see .... Am I on completely the wrong road with this patch?
An example output is here:
https://galahad.aei.mpg.de/~spxiwh/LVC/ER7/analyses/BBH_alignedspin/run7/Versioning/
(We have a large number of executables that do *not* …
> Add versioning tab to html page

- bin/hdfcoinc/pycbc_calculate_psd
- bin/hdfcoinc/pycbc_make_hdf_coinc_workflow
- pycbc/psd/__init__.py
- pycbc/strain.py
- pycbc/workflow/core.py
- pycbc/workflow/jobsetup.py
- setup.py
(Depends on commits that will be included in other pull requests, so not ready for approval yet)
#88 
Add a stand-a-long executable (pycbc_calculate_psd, better name?) that calculates all of the psds that are internally made within a run. It re-uses the same data conditioning/psd estimation codes as pycbc_inspiral. 
The input to the code, along with the standard conditioning options, is a segment file containing a set of gps start/end times. 
The output is a single HDF file, that contains every PSD in the run, in the following format. 
f[IFO/PSDS/NUM],
where NUM is an integer that identifies the PSD. Each PSD can be read in by the load_frequencyseries function directly. 
I'll also advocate we consider at some future point to add this to standard set of workflow jobs. The only concern …
> stand-a-lone executable to calculate all the inspiral psds from a run

- bin/hdfcoinc/pycbc_make_hdf_coinc_workflow
- bin/pycbc_make_html_page
- pycbc/results/plot.py
- pycbc/results/render.py
- pycbc/results/templates/files/file_pre.html
- pycbc/results/versioning.py
- pycbc/workflow/core.py
This PR moves the call to the `versioning` module from `pycbc_make_html_page` to the workflow generator. It has been implemented in `pycbc_make_hdf_workflow`.
It is envoked by passing the path to the output dir and a `ConfigParser` object for the workflow (so that it can get all the executables).
This PR also puts meta-data in those html files to use the `render-template=render_text` so that it uses a render function that is for preformatted html/text files. Includes a `title` as well. I added the `render_text` function in `render.py` and I added a `file_pre.html` file template to do this.
A test of the HDF workflow generator versioning is here: https://sugar-jobs.phy.syr.edu/~cbiwer/tmp/html_version/versioning/
> Move versioning from html generator to workflow generator

- pycbc/results/__init__.py
- pycbc/results/metadata.py
- pycbc/results/versioning.py
The generic escaping of characters broke the mpld3 plots. This reverts that, but applies the escaping where it was needed, directly to the versioning output. I've renamed the module to metadata.py to reflect better what it does while I was at it.
> mpld3 plots broken

- pycbc/results/versioning.py
The most reason change to import process calling from pycbc.workflow.core made it so standard functions required Pegasus.DAX3, which I don't think we want to require for all uses of PyCBC, such as running from a laptop. This moves the imported to where it is needed.
> can't use pycbc with pegasus.dax3!

- bin/hdfcoinc/pycbc_coinc_statmap
- bin/hdfcoinc/pycbc_foreground_censor
- bin/hdfcoinc/pycbc_make_hdf_coinc_workflow
- bin/hdfcoinc/pycbc_page_snrifar
- pycbc/events/veto.py
- pycbc/workflow/coincidence.py
- setup.py
Veto triggers from the single detector plots that are near to a zerolag trigger. This is done by creating a segment list from the times used to veto zerolag times within the statmap code. As such, once controls the window by setting the veto-window option in the [statmap] section. I hope this will make the plots suitable for closed box viewing. 
Example here:
https://sugar-jobs.phy.syr.edu/~ahnitz/projects/polish/r7/gw/html/single_triggers/
> censor single trigger plots from zerolag 

- bin/pycbc_make_coinc_workflow
Looks like make_coinc_workflow was broken by recent changes. This fixes it ...... Shouldn't the automatic tests catch SyntaxErrors?
> Fix make_coinc_workflow

- pycbc/results/static/css/fancybox/2.1.5/jquery.fancybox.css
- pycbc/results/static/js/fancybox/2.1.5/fancybox-orange.js
- pycbc/results/static/js/fancybox/2.1.5/jquery.fancybox.js
- pycbc/results/static/js/jquery/1.10.2/jquery.mousewheel-3.0.6.pack.js
- pycbc/results/templates/files/file_default.html
- pycbc/results/templates/orange.html
This PR adds the fancybox css and js to the `static/` subdirs. And adds in fancybox to be used with the orange html template.
See example here: https://sugar-jobs.phy.syr.edu/~cbiwer/tmp/html_version_2/coincident_triggers/
> Use fancybox in orange template

- bin/hdfcoinc/pycbc_coinc_findtrigs
- bin/hdfcoinc/pycbc_page_coinc_snrchi
- bin/hdfcoinc/pycbc_page_injtable
- bin/hdfcoinc/pycbc_page_snrchi
These are the changes needed to run combined new SNR in a workflow. For ER7 I ran the traditional chisq with 16 bins .... although I definitely see better performance at shorter duration with fewer bins, and better performance at longer duration with more bins .... Maybe there is some way to automatically choose the number of bins based on some minimal spacing [in the time domain?] between the bins??
The auto-chisquared parameters are:
autochi-number-points = 100
autochi-stride = 4
autochi-reverse-template =
autochi-two-phase =
**NOTE**: This is *not* max-valued as in ER6, which makes getting the DOF easy.
You also need to supply:
ranking-statistic = combnewsnr
to pycbc_coinc_findtrigs.
Finally the chi-squared plotting codes add a command line option to choose which chi-squared to plot. …
> Combined new snr

- bin/hdfcoinc/pycbc_coinc_bank2hdf
- bin/hdfcoinc/pycbc_coinc_findtrigs
- bin/hdfcoinc/pycbc_coinc_hdfinjfind
- bin/hdfcoinc/pycbc_coinc_mergetrigs
- bin/hdfcoinc/pycbc_coinc_statmap_inj
- bin/hdfcoinc/pycbc_coinc_trig2hdf
- bin/hdfcoinc/pycbc_make_hdf_coinc_workflow
- bin/hdfcoinc/pycbc_page_foundmissed
- bin/hdfcoinc/pycbc_page_segments
- bin/hdfcoinc/pycbc_page_sensitivity
- bin/hdfcoinc/pycbc_page_snrchi
- bin/hdfcoinc/pycbc_page_snrifar
- pycbc/results/templates/wells/two_column.html
- pycbc/workflow/ini_files/example_hdf_bns.ini
- pycbc/workflow/plotting.py
Update to the hdf workflow generator to include some basic well  setups (plots that show up outside of the accordions).
* allow selection of plot subsections by excluding or requiring a substring
* Add a more traditional foundmissed plot style
* Make snrifar plot a bit more like the bigdog one
* Add a closed box option for the snrifar plot that doesn't show foreground
* add version options to many scripts
* fill in a few missing captions
Example here,
https://sugar-jobs.phy.syr.edu/~ahnitz/projects/polish/r11/gw/html/
Note, that this does require a few config file changes for the plots to show up in the right locations. If left unchanged, I believe old ini files will still work, but they won't include a few of the plot wells.
> Results page

- bin/pycbc_make_html_page
- pycbc/results/static/css/pycbc/orange.css
- pycbc/results/templates/orange.html
- pycbc/results/templates/wells/sitemap.html
- pycbc/results/templates/wells/two_column.html
This PR:
* Removes numbering in navbar. This can be done by the workflow generator.
* Adds a sitemap page at `/sitemap`. The link to the sitemap is in the `<footer>` tag.
* Title are bigger and some more padding.
An example of this PR is here: https://sugar-jobs.phy.syr.edu/~cbiwer/tmp/html_version_2/
> Add sitemap to orange.html and remove numbering in navbar

- pycbc/results/templates/orange.html
- pycbc/results/templates/wells/two_column.html
This PR adds an expand/collapse all as the title states.
It also fixes the padding in the template `well.html`.
An example of the button is here: https://sugar-jobs.phy.syr.edu/~cbiwer/tmp/html_version_2/coincident_triggers/
> Add expand/collapse all button

- pycbc/events/veto.py
Hopefully, this will help reduce some memory consumption when using indices_within_times and the start/end times given are overlapping.
> coalesce start/end times before doing indices_within_times function

- pycbc/opt.py
Disable use of 'getconf' to find out cache information and such on a Mac, since it doesn't work.
> Disable getconf on MacOS

- pycbc/waveform/waveform.py
This should fix the broken FD approximants.
> use out memory for get_fd_waveform within get_waveform_filter

- bin/hdfcoinc/pycbc_make_hdf_coinc_workflow
- bin/hdfcoinc/pycbc_page_segtable
- bin/pycbc_make_html_page
- pycbc/opt.py
- pycbc/results/render.py
- pycbc/results/templates/files/file_default.html
- pycbc/results/templates/orange.html
- pycbc/results/templates/wells/two_column.html
- pycbc/workflow/configuration.py
- pycbc/workflow/ini_files/example_hdf_bns.ini
- pycbc/workflow/plotting.py
- pycbc/workflow/segment.py
- setup.py
This PR adds a HTML table to the summary pages that shows segment information.
The executable that creates the table is called `pycbc_page_segtable` and takes a list of segment files, a list of segment names, and the output filename as options.
Displayed in the table is the name (read from the `segment_definer` table), and the amount of time in each IFO and in H1L1 time. If there is anything in the `comments` column for that segment then it shows up in the comments. We should populate the `comments` columns with useful descriptions, that will require some tweaks to `toSegmentXml`.
Also in this PR HTML do not use iframes anymore, instead they are read directly see changes to `file_default.html'.
And there are now checks to see if the file exists before rendering it.
An example of the …
> Add segment table

- pycbc/sensitivity.py
There is a syntax error in pycbc/sensitivity.py .... 
I *think* I see what is trying to be done here, only the line break character, or brackets, is missing. However, I don't see any reason why this shouldn't be two lines. Fix attached.
Did the auto-build tests miss this?
> Fix syntax error

- .travis.yml
- tools/install_travis.sh
- tools/run_travis.sh
* Install dependencies in a separate dir, not inside PyCBC
* Reorganize .travis script
* Avoid building unneeded lalsuite components
* Silence some unneeded verbosity in log
* Enable actual unit tests (only successful ones for now)
> Attempt at improving travis testing

- bin/hdfcoinc/pycbc_make_hdf_coinc_workflow
- bin/hdfcoinc/pycbc_page_segplot
- bin/hdfcoinc/pycbc_page_segtable
- bin/pycbc_make_html_page
- pycbc/events/veto.py
- pycbc/future.py
- pycbc/results/metadata.py
- pycbc/results/mpld3_utils.py
- pycbc/results/render.py
- pycbc/results/templates/files/file_default.html
- pycbc/results/templates/orange.html
- pycbc/results/templates/wells/two_column.html
- pycbc/workflow/ini_files/example_hdf_bns.ini
- pycbc/workflow/plotting.py
- setup.py
This PR:
* If a file is rendered in the `well.html` for `orange.html`, then it is not added to the additional files section.
* Added `get_segment_definer_comments` to `pycbc.events.veto`, this function returns a dict of the comments in the segment definer table.
* Adds an executable `pycbc_page_segplot` that plots segments for each IFO.
* Adds veto table to summary page.
* Adds HTMLParser from Python 2.7 to `pycbc.future`. This was needed because the 2.6 version does not handle `<script>` tags.
Can see an example of segment tables and plots on summary page here: https://sugar-jobs.phy.syr.edu/~cbiwer/tmp/html_version_13/
> remove duplicate files and add segments plot on summary page

- bin/pycbc_aligned_stoch_bank
- bin/pycbc_geom_aligned_2dstack
- bin/pycbc_geom_aligned_bank
- bin/pycbc_geom_nonspinbank
- pycbc/__init__.py
- pycbc/tmpltbank/option_utils.py
- pycbc/types/optparse.py
Hi Ian, this fixes failures in tmpltbank unit tests. While I was at it, I went around and did some cleanup which is now possible thanks to argparse:
* Made some of the required options actually required. This also leads to shorter explicit checks.
* Introduced checks for correct ranges of some numerical arguments.
* Moved --min-match and --output-file options to a common insert_*() style function for all bank scripts.
* Fixed a case where an invalid option combination was caught, but not reported.
I tested this by running one of the pycbc_geom_nonspinbank examples and the output is unchanged.
> Template banks: fix failing unit test, clean up option parsing.

- pycbc/events/simd_threshold.py
This is a workaround that disables vectorization (though not OpenMP parallelization) in the CPU thresholding/time clustering routine.
There does not appear to be an actual bug in the code; rather, on at least `gcc 4.7.2`, this is triggered when `-O2` or higher optimization is given. The problem disappears by the time we get to `gcc 4.9.2`. Basic workarounds (declaring the problematic variable `volatile`, or converting `for` loops to `while` loops) do not fix the issue.  It will perhaps be revisited at a later date, as time allows.
> Cpuopt workaround

- bin/hdfcoinc/pycbc_make_hdf_coinc_workflow
- bin/hdfcoinc/pycbc_page_foreground
- pycbc/io/hdf.py
- pycbc/workflow/ini_files/example_hdf_bns.ini
- pycbc/workflow/plotting.py
At the face-to-face it was requested by the PE group that we upload the loudest N events to gracedb after box opening. The first step in doing this is to allow the ability to write foreground triggers in XML format.
This patch addresses that by allowing pycbc_page_foreground to be able to write in XML or HD5 format. I have verified that an example HDF5 output is unchanged by this patch. This also allows the single-detector files to be read in and some additional data produced to html in this. Single-detector trigger files are mandatory for XML writing, but currently optional for html.
This is implemented by adding a new class in io/hdf.py to handle the set of files comprising our coincident output.
The next step will be to add this to the workflow generator and then to add a post-box …
> Allow pycbc_page_foreground to write in xml format

- bin/pycbc_inspiral
- pycbc/opt.py
- pycbc/weave.py
This adds two features to pycbc_inspiral inspired by recent testing on Stampede:
* Processor affinity
* Per-process caches for scipy.weave
Affinity is controllable by two new flags, --cpu-affinity which takes a list of processor ids and --cpu-affinity-from-env which takes the name of an environment variable, which should contain a list of processor ids.  The second is needed to use pycbc_inspiral with pegasus-mpi-cluster.
The per-process cache is enabled by setting --per-process-cache, which will append /(current pid) to the existing cache directory.  This will incur a performance penalty as each process will have to recompile the kernels, but it avoids a potential race condition that can cause one or more processes to fail.
> Remote workflows

- bin/hdfcoinc/pycbc_page_coinc_snrchi
- bin/hdfcoinc/pycbc_page_snrchi
- pycbc/io/hdf.py
This commit allows for plotting any of the three chisqs (or combinations thereof) in the two chisq plotting codes. It also includes some cosmetic fixes to ensure that the axis limits are sane and to put the chisq type in the file metadata for the webpage.
Here's an example of this plotting *all* the chisqs (our webserver still seems to have problems, be patient):
https://galahad.aei.mpg.de/~spxiwh/LVC/ER7/analyses/BBH_alignedspin/run17/3._single_triggers/
I'm not sure if io/hdf.py is the right place for the chisq choices code block. Any suggestions for a better home, or is this okay?
(With all 3 chisqs the L1 performance actually seems quite good for these short duration templates! We need to figure out how to better discriminate in H1 though).
> Allowing more chisq choices in plotting codes

- bin/hdfcoinc/pycbc_page_ifar
- setup.py
This PR adds an executable that makes the old-style IFAR plots. This PR does not add it into the HDF workflow generator.
An example plot I made with this exe: https://sugar-jobs.phy.syr.edu/~cbiwer/tmp/ifar.png
This plot was made on sugar using the following command line:
```
pycbc_page_ifar --trigger-file /home/laura.nuttall/cbc/pycbc_er7_take2/er7_cat12_inj_only/full_data/H1L1-STATMAP_FULL_DATA_FULL_CUMULATIVE_CAT_12H-1117400416-928800.hdf --output-file ~/public_html/tmp/ifar.png --decimation-factor 10000
```
> Add IFAR plot exe to pycbc

- pycbc/workflow/segment.py
Tom,
Here is the patch to add back the analyze coinc time only option. I'll let you and Ian decide if this is an ok state to merge to this function, even if it isn't perfect.
> add segments-method to analyze all single ifo time or coinc time

- pycbc/pnutils.py
point pnutils function that finds time-frequency inspiral track to use pycbc.waveform.spa_tmplt version of the chirp time function rather than lalinspiral (deprecated). For reference, they implement the same algorithm.
> remove lalinspiral from pnutils

- bin/hdfcoinc/pycbc_plot_singles_vs_params
- pycbc/io/hdf.py
There is a misnamed variable 'filter_func' that is causing pycbc_plot_singles to fail in current workflows.
> fix misnamed variable in pycbc_plot_singles_vs_params

- pycbc/workflow/summaryplots.py
This PR adds a `import logging` to the `summaryplots` module. It was missing before but didn't fail in the workflow generator because `logging` was being imported elsewhere.
> Add logging import to summaryplots module

- pycbc/results/templates/files/file_default.html
This PR makes it so the ini files are displayed on the summary pages as text.
An example: https://sugar-jobs.phy.syr.edu/~cbiwer/tmp/html_version_14/0._configuration/
> Fix ini file condition in template

- bin/hdfcoinc/pycbc_make_hdf_coinc_workflow
This PR makes it so that on the Configuration summary page for the HDF workflow the ini file is shown in the well.
You no longer have to click an accordion.
An example: https://sugar-jobs.phy.syr.edu/~cbiwer/tmp/html_version_16/0._configuration/
> Display ini file in well on summary page

- bin/hdfcoinc/pycbc_coinc_findtrigs
- bin/hdfcoinc/pycbc_foreground_censor
- bin/hdfcoinc/pycbc_make_hdf_coinc_workflow
This rolls up a 3 changes related to censoring closed box results from possible signals.
I had done a test run that included a single injection in the foreground. This is trivial to do in case anyone is interested in testing that yourself. Just add
[inspiral-full_data]
injection-file=/path/to/injection/file/with/single/injection
to your ini file and make sure to remove '--filter-inj-only', etc. 
For reference, I had chosen initially chosen a time for the injection that just happened to be a time that was CAT3 vetoed in only one of the detectors. This had some unpleasant side effects that I address here. Namely, that it was quite obvious that the background was affected by the injection. 
1. Apply the censored veto file to the individual found missed injections.
This was already done for …
> analyze triggers only from coincident time after cat2/3 vetoes

- bin/pycbc_make_html_page
This PR includes the python line to copy the permission bits for a directory.
This is relevant because in some workflow generators (ie. `pycbc_make_hdf_workflow`) the results section has been `chmod 700` so that others cannot view it. This keeps "things inside the box" and when you want the box opened, all you should have to do is `chmod 777`.
An example is here: https://sugar-jobs.phy.syr.edu/~cbiwer/tmp/html_version_15/
Section 3 was `chmod 700` to not be viewable same as the `pycbc_make_hdf_workflow`.
> Preserve directory permissions in pycbc_make_html_page

- bin/hdfcoinc/pycbc_make_hdf_coinc_workflow
- pycbc/workflow/ini_files/example_hdf_bns.ini
- pycbc/workflow/plotting.py
This PR adds nodes for the `pycbc_page_ifar` plotting exe to the HDF workflow.
In the workflow it adds a IFAR node for each background level (123H, 12H, 1H).
The plots are stored in the Results tab of the summary page, ie. they are behind a `chmod 700` directory with the other "closed box" plots.
> add IFAR plotting nodes to HDF workflow

- bin/hdfcoinc/pycbc_make_hdf_coinc_workflow
- bin/hdfcoinc/pycbc_page_segtable
This PR replaces the table on the summary page created with `pycbc_page_segtable` that only showed the cumulative amount of background level 1H, 12H, 123H time.
The table is replaced with one that shows the "and" of times when triggers were produced and the different background levels. This is better because it shows the amount of time that actually overlapped with the search.
Can see an example here: https://sugar-jobs.phy.syr.edu/~cbiwer/tmp/html_version_17/
The '&' (and) operation is handled by `pycbc_page_segtable` in this PR. The user can specify `SEG_NAME1&SEG_NAME2` on the command line to take the and.
An example command line on sugar is:
```
cd /home/cbiwer/projects/pycbc_test_tmplt_dev
pycbc_page_segtable --segment-files veto2_test/segments/H1L1-WORKFLOW_SEGMENT_SUMMARY.xml …
```
> Show the and of times triggers were produced and background levels

- docs/workflow/datafind.rst
- pycbc/workflow/datafind.py
Josh, I'm not sure who to assign this to with Alex on thesis-writing duty. As this was requested by Cardiff folk maybe we can assign to one of them? For now I am assigning you.
This was a feature request from the Cardiff folk at the recent face-to-face. Specifically, you can now specify a backup datafind server for PyCBC workflows. The primary server is used for frames in the case that it finds all the frames it expects to, the backup server is only used if frames are missing on the local server. The backup server is only asked for gsiftp urls (though we could change this if there is a use-case for that) and the frame files will be *copied* to the local machine.
This allows us to run analyses when a specific local file server or node goes down (for that you need to be using the …
> Add ability to specify backup gsiftp datafind server

- bin/pycbc_upload_xml_to_gracedb
- pycbc/io/hdf.py
- setup.py
This adds a script to upload coinc XML files to gracedb. The process would then be: workflow runs as normal and produces a summary XML file. This XML file is only uploaded, by hand, with this script once the box is opened.
This also adds some small modifications to populate more fully the resulting coinc XML file before uploading it. The previously missing event_id (line 400) was a bug, and without it coinc XML files written in this way were invalid!
> Add script to upload events to gracedb

- bin/hdfcoinc/pycbc_coinc_statmap
- bin/hdfcoinc/pycbc_coinc_statmap_inj
- pycbc/events/coinc.py
- pycbc/io/hdf.py
Consolidate functionality that was duplicated in both pycbc_coinc_statmap and pycbc_coinc_statmap_inj into pycbc/events/coinc.py. This adds a generic dictionary array class as well that I've put into io/hdf.py. At some point when we have time, we might want to see if it makes sense to consolidate some of these classes, but at the moment, I can see reasons for each. Also, I added a speed up / minor memory reduction in the clustering algorithm.
> Statmap reorg

- bin/hdfcoinc/pycbc_page_snrifar
Remove the 6 sigma line from the snrifar plot. It is basically useless, and often is outside the plot boundaries. This also gives more room in the color gradient to see the other lines better.
> don't plot to 6 sigma in snrifar plot, not very useful

- pycbc/workflow/pegasus_files/xsede_site_template.xml
This patch adds an additional argument to pegasus-mpi-cluster which tells it to retry each job it is managing up to three times.  In the case of transient failures this can avoid the overhead of rerunning the PMC job itself.
(Note that the argument name in the commit message is wrong, it is correct in the patch itself)
> Add --tries 3 to the arguments passed to pegasus-mpi-cluster

- pycbc/__init__.py
Scipy.weave caches based on the code and not additional arguments such as flags or support code.  This can lead to kernels not being properly updated.  This patch adds the git hash to the PYTHONCOMPILED path to ensure that the kernels match the current pycbc version.
> Append the git hash to the weave cache path

- bin/hdfcoinc/pycbc_make_hdf_coinc_workflow
Call to the versioning module was deleted from HDF workflow. This puts it back in.
> Add versioning back into HDF workflow.

- bin/hdfcoinc/pycbc_page_foreground
- bin/hdfcoinc/pycbc_page_foundmissed
- pycbc/workflow/ini_files/example_hdf_bns.ini
1. Add option to pycbc_page_foundmissed to plot the missed injections on top
2. modify the example bns ini file to include this plot in the summary page
3. display the reduced chisq in the foreground table
> minor plot tweaks

- pycbc/strain.py
As reported by Chris, the frame-type option is currently broken. This patch fixes it, so now you can provide a frame type to pycbc_inspiral in lieu of frame files and it will figure out where they are on its own.
> fix frame-type option

- bin/pycbc_inspiral
- pycbc/events/threshold_cpu.py
- pycbc/events/threshold_cuda.py
- pycbc/fft/cufft.py
- pycbc/fft/fft_callback.py
- pycbc/filter/matchedfilter.py
- pycbc/filter/matchedfilter_cpu.py
- pycbc/filter/matchedfilter_cuda.py
- pycbc/vetoes/chisq.py
- pycbc/vetoes/chisq_cuda.py
Josh, Larne, 
If possible I would like you both to take a look at this. I've done the basic changes to add in GPU classes for the correlator, thresholder nad fft'er. Given that at the moment master's version of GPU support is broken, I think we should push this soon and leave complete validation for later. I have at least checked that the results don't look like garbage (snrs / chisq looks like sane values).
I've also included some format cleanup and rearangement that was needed to add GPU support. The key change was that you must only pass pycbc types. If you want something else within the class, do the type conversion it its init. 
Callback support not yet enabled. After having to implemented it, I think the class structure is quite nice and will actually make doing the callbacks a bit …
> add basic version of class interface for gpu correlate, threshold, fft

- bin/pycbc_single_template
- setup.py
This adds a single template version of pycbc inspiral. It doesn't save anything nor produce any result plots at this point, but is available as base so it can be modified to do so in the near future. 
Here is an example 
```
pycbc_single_template \
--approximant SPAtmplt \
--mass1 1.4 \
--mass2 1.4 \
--low-frequency-cutoff 40 \
--sample-rate 4096 \
--chisq-bins 64 \
--psd-estimation median \
--psd-segment-length 16 \
--psd-segment-stride 8 \
--gps-start-time 100000000 \
--gps-end-time   100002016 \
--strain-high-pass 30 \
--pad-data 8 \
--channel-name H1:FAKE-STRAIN \
--fake-strain iLIGOModel \
--fake-strain-seed=1 \
--segment-length 512 \
--segment-start-pad 64 \
--segment-end-pad 16 \
--processing-scheme cpu:16 \
--fftw-measure-level 0 \
--output test.hdf \
--verbose
> add example single template version of pycbc inspiral

- bin/hdfcoinc/pycbc_coinc_statmap
- bin/hdfcoinc/pycbc_coinc_statmap_inj
- bin/hdfcoinc/pycbc_page_snrifar
- pycbc/events/coinc.py
Hi Tom,
I wanted to bring to your attention another change I'd like to get it, which should (I think) bring the algorithm for assigning IFAR and FAP in agreement with your presentation. 
An example result page after this change is here.
https://sugar-jobs.phy.syr.edu/~ahnitz/projects/test_inj/t6v7/gw/html/7._result/
And from master
https://sugar-jobs.phy.syr.edu/~ahnitz/projects/test_inj/t6/gw/html/7._result/
The main changes
Calculate the number of louder background triggers more correctly, instead of using an interpolate. Allow the number to be 0.
Add 1 to the n louder number when calculating IFAR, we could put your estimate FAR here, but I'm keeping the changes as small as possible first.
> don't interpolate n louder background, add 1 for IFAR

- bin/hwinj/pycbc_generate_hwinj
- bin/hwinj/pycbc_plot_hwinj
- docs/hwinj.rst
- setup.py
This PR adds two executables and docs for them.
The first executable ``pycbc_generate_hwinj`` takes waveform parameters on the command line and outputs a ``sim_inspiral``/``sngl_inspiral`` XML file with the parameters and single-column ASCII files with the generated waveforms. The layout of this script is a modern re-creation of ``lalapps_coinj`` for aLIGO data:
* Generate the waveform using the parameters given on the command line.
* Generate a PSD that will be used for calculating sigma squared.
* Apply the antenna pattern for each detector.
* Calculate sigma squared for each detector using the waveform and the PSD. We do this to determine the network SNR.
* Rescale the waveform to the desired network SNR.
* Write an XML file with the waveform parameters and single-column ASCII files …
> Add script and doc to generate single-column ASCII files that can be used by awgstream

- pycbc/results/versioning.py
The function get_code_version_numbers tries to parse the output of programs' --version argument into a string for the result pages. Currently the function relies on line breaks being in certain predefined areas. However, argparse will sometimes add it's own linebreaks in if a line is too long, which breaks get_code_version_numbers. For example, in my test, the hash after ID was put on it's own line by argparse, which caused an IndexError at line 181. This patch fixes this by doing away with line breaks, and just looking for the relevant arguments in the --version string.
This is Ian's code, but since he is on vacation, assigning to Chris.
> fix versioning to deal with line breaks

- bin/hdfcoinc/pycbc_page_foundmissed
This change sorts the found injections so that the quieter injections are always on top of the loudly found ones.
Original
https://sugar-jobs.phy.syr.edu/~ahnitz/projects/plots/t1/gw/html/H1L1-PLOT_FOUNDMISSED_SUMMARY_ALLINJ-962582415-604800.png
New
https://sugar-jobs.phy.syr.edu/~ahnitz/projects/plots/t2/gw/html/H1L1-PLOT_FOUNDMISSED_SUMMARY_ALLINJ-962582415-604800.png
> Sort found in foundmissed plots by FAR 

- bin/hwinj/pycbc_generate_hwinj
- bin/hwinj/pycbc_generate_hwinj_from_inspinj
- bin/hwinj/pycbc_generate_hwinj_from_xml
- docs/hwinj.rst
- setup.py
This PR:
* Fixes a typo in the error message of ``pycbc_generate_hwinj``.
* Adds an executable that reads LIGOLW XML file with a ``sim_inspiral`` table and write single-column ASCII files for ``awgstream`` to use. Executable is in ``bin/hwinj/pycbc_generate_hwinj_from_inspinj``.
* Adds documentation. Direct link to new hardware injection documentation page is here: https://github.com/cmbiwer/pycbc/blob/hwinj5_dev/docs/hwinj.rst
> Add executable for creating single-column ASCII files from sim_inspiral table. More docs.

- bin/hdfcoinc/pycbc_page_segplot
This PR adds the IFO to the plotting area on segplot, eg. https://sugar-jobs.phy.syr.edu/~cbiwer/tmp/t.html has "L1 Segments" and "H1 Segments" on it now.
> Add IFO to segplot

- pycbc/tmpltbank/lattice_utils.py
LALPulsar flag constants have been renamed a few times recently, which broke PyCBC (currently broken with the latest lalsuite master). Karl suggested simply setting the flags to 0 to get the default behavior instead.
> tmpltbank: use default flags for An^* lattice

- bin/hdfcoinc/pycbc_page_sensitivity
If there are no injections found the sensitivity plots currently fail as the ylabel never gets set, this adds initializer so the code completes.
> handle edge case where ylabel is undefined as no injections are found

- bin/hdfcoinc/pycbc_distribute_mass_bins
This adds a script to split a set of hdf files containing the coincident foreground and background triggers based on massed bins. The output is a single file for each mass bin. This is what will set the syntax for choosing bins, so I wanted to break this commit out separately. 
A command line might look like
pycbc_distribute_mass_bins \
--coinc-files coinc1.hdf coinc2.hdf coinc3.hdf ....\
--mass-bins total-2 mchirp-6 mchirp-8 \
--output-files bin1.hdf bin2.hdf bin3.hdf
Where the coinc*.hdf files are first merged before splitting into mass bins. Here they may come from different parts of the bank, or different times, etc. 
Each bin is defined as a nested set in order, so in this case, the first bin is taken from the templates which total mass less than 2,  of the remaining templates the …
> add executable to split coinc files based on mass bins

- bin/hdfcoinc/pycbc_coinc_statmap
- bin/hdfcoinc/pycbc_coinc_statmap_inj
- pycbc/io/hdf.py
This is a small patch to convert the units of combined_far in our XML coinc output files to Hz. Note that our conversion between seconds and years is slightly unclear as described in #217, this should be fixed.
> Convert FAR to units of Hz when dumping to XML

- bin/hdfcoinc/pycbc_make_hdf_coinc_workflow
- bin/hdfcoinc/pycbc_strip_injections
- pycbc/workflow/injection.py
- setup.py
I'm dusting off some old code I had tried a while back, but it still seems to work. This adds a executable that removes injections that are outside coincident time or are quiet in one detector. I've also added this to the workflow as an optional feature. The workflow still uses the full injection file for all purposes except filtering.
To enable only analyzing coincident injections.
[workflow-injections]
strip-injections=
I think this is a bit more experimental, but it seems to work for me, is the option to ignore injections that are further away than a fixed effective chirp distance. You can enable it my specifying it as an executable option for now.
[strip_injections]
max-effective-chirp-distance=110 ; A number I found was safe for s6 sensitivity (~SNR of 3.5)
I was able to get just …
> add option to ignore quiet or non-coincident injection

- bin/hdfcoinc/pycbc_calculate_psd
This adds back the option checking to pycbc_calculate_psd that we safely apply from pycbc_inspiral.
> add back some command line sanity checking to pycbc_calculate_psd

- pycbc/psd/read.py
This should allow pycbc_inspiral to use its own psd output files. The fix is to check for if the flow is exactly within the file and if so, start the interpolation from that point and not the prior one.
> handle corner case, where the flow is exactly in the psd file

- .gitignore
This file is now automatically generated from one of two templates, so git should ignore it.
> ignore the docs makefile

- bin/hdfcoinc/pycbc_calculate_psd
Running with pyinstaller the FrequencySeries could not be pickled for return, because of a problem pickling the member LIGOTimeGPS.  The works around the problem by returning only the components that are needed.
> Modify return type to work around pyinstaller incompatibility

- bin/hdfcoinc/pycbc_plot_singles_vs_params
This adds the command line to the metadata of ``pycbc_plot_singles_vs_params`` so that it appears on the summary pages.
> Add command line to metadata of pycbc_plot_singles_vs_params

- pycbc/waveform/spa_tmplt.py
- test/test_spatmplt.py
- test/test_waveform.py
- tools/run_travis.sh
This checks something off I've intended to do for a while, which is to source the PN constants for the SPAtmplt from lalsimulation. This request also adds the unit test for it to the standard travis build. It checks for a variety of waveform parameters that the spatmplt approximant matches the taylorf2 waveform with the same settings.
> use lalsimulation for spatmplt pn constants, add spatmplt unittest to travis

- docs/hwinj.rst
The text correctly says to taper the ``SpinTaylorT4`` waveform at the start and end. And the example command does this. However the line that shows the command line options names is incorrect. This PR fixes a typo in the hardware injection documentation.
> Fix typo in example for hardware injection doc.

- bin/hdfcoinc/pycbc_combine_statmap
- pycbc/events/coinc.py
- setup.py
This add a script to combine multiple statmap output files (say coming from different mass bins) by clustering for the loudest foreground trigger by IFAR and then dividing all IFARs in the foreground or background (if there are background triggers) by the trials factor. The trials factor is taken to be the number of input files. 
The idea is that this is used in conjuction with #222
> add file to combine statmap output files with a trials factor

- bin/hdfcoinc/pycbc_coinc_statmap
- bin/hdfcoinc/pycbc_combine_statmap
- bin/hdfcoinc/pycbc_distribute_background_bins
- bin/hdfcoinc/pycbc_make_hdf_coinc_workflow
- bin/hdfcoinc/pycbc_page_ifar
- bin/hdfcoinc/pycbc_page_snrifar
- bin/hdfcoinc/pycbc_plot_bank_bins
- pycbc/events/coinc.py
- pycbc/events/veto.py
- pycbc/workflow/coincidence.py
- pycbc/workflow/plotting.py
- setup.py
This rolls up #223  and #222 and adds basic mass bins into the workflow. They can be controlled by setting. 
```
[workflow-coincidence]
background-bins = LOW-mchirp-3.48 HIGH-mchirp-6.3
[combine_statmap]
cluster-window = CLUSTER_WINDOW ; Time window to cluster the triggers from the mass bins
```
Please let me know ASAP if you guys think this is a sensible way to present the results and if there should be modifications to other plots/ new plots to be able to understand a mass binned search.
> add mass bins to workflow

- docs/index.rst
- docs/install.rst
- docs/release.rst
This pull request contains several fixed to the documentation:
* Deal with the pip bug that causes a (harmless) error if Cython is pulled in by hd5 by telling the user to install Cython before they get to the PyCBC install. This deals with the issue https://github.com/ligo-cbc/pycbc/issues/157
* Added documentation on how to build a release and publish it to PyPI
* Removed links to my GitHub repo from the examples and put in a generic username
* Added instructions to pip install the dqsegdb tools. At the moment this needs to be done from my GitHub fork because of some issues that prevent Ryan's dqsegdb from being compatible with PyPI. I will work with Ryan to fix these.
* Added some additional links to GitHub documentation on the fork and pull model that we use, including an explicit link …
> Updates to PyCBC install instructions based on feedback from Steve

- pycbc/vetoes/chisq.py
Hi Ian, I found these two changes are needed to run in ER8.
One change enables using Tom's formula for the number of chi^2 bins, which requires calling pycbc.pnutils.get_freq().
The other change is what you suggested for getting the workflow generation to complete. Without this change, pycbc_make_hdf_coinc_workflow hangs forever during the creation of the matched filter jobs. I haven't discovered why that happens, but this change fixes it. Do you think we can merge this, or could it have some negative side effects?
> Enable calling pnutils to determine the number of chi^2 bins

- pycbc/scheme.py
- tools/tests/thread_change.py
This pull request adds explicit calls to the OpenMP function `omp_set_num_threads()` within the `__enter__` and `__exit__` special methods of `CPUScheme`. It should allow (at least where `libgomp` is present) the toggling of the number of threads multiple times within an executable, and also fix issues where a multithreaded library is loaded before a scheme is entered, causing the number of threads of that scheme instance to be ignored.
It would be nice to find a more portable way to do this, that does not depend on `libgomp` (which is `gcc` specific), but at the moment we also explicitly assume `libgomp` in our weave code also.
> Test threads

- bin/hdfcoinc/pycbc_plot_bank_bins
pycbc_plot_bank_bins is missing an import. Given the trivialness of this, and the fact that workflows are broken without it, I will merge this after sanity checks complete. (You can clearly see numpy being used on line 25)
> Code must import numpy

- bin/hdfcoinc/pycbc_make_hdf_coinc_workflow
- pycbc/workflow/ini_files/example_hdf_bns.ini
This PR removes a list that has the veto segment names hardcoded. And it adds a missing executable to the example ini file.
> Remove hardcoded table of veto segment names and add missing executable to example ini file

- pycbc/tmpltbank/coord_utils.py
- pycbc/tmpltbank/option_utils.py
- Better user info output
- Allow remnant mass to be >=0 rather than >0
@spxiwh
> Small fixes to EM-bright related parts of the template bank code

- pycbc/inject.py
This PR tapers software injections in ``InjectionSet.apply`` before the call to ``project_wave``.
This way the call to LALSimulation inside ``project_wave`` that offsets the waveforms doesn't have to interpolation across a step since its already been tapered.
Image of waveform tapering with this PR: https://sugar-jobs.phy.syr.edu/~cbiwer/tmp/inject_fix_2_tapering_start.png
> In InjectionSet.apply taper before project_wave

- pycbc/workflow/configuration.py
As mentioned in #250 there is a problem if using [inspiral&tmpltbank] and substitution with variables defined within these "&" sections. This fixes this by swapping the order so that we resolve the multiple section check before completing values.
> Split sections before filling in substitutions

- docs/build_gh_pages.rst
This fixes an error in the documentation for making gh pages.
> fixed spelling of nojeckyll file

- tools/static/build_static_executables.sh
- tools/static/hooks/hook-pycbc.py
This adds a new script under tools/static to run pyinstaller over all available programs.  In addition hooks/hook-pycbc has been modified to
* add a few additional hidden dependancies to all programs
* include mkl for pycbc_inspiral only
* include the html files and other assets for pycbc_make_html_page
We could probably save a little disk space by customizing the hidden dependancies on a per-executable basis, but at the moment I'm not sure that's worth the effort.
> Script to pyinstall all programs, some restrictions on what gets bundled

- pycbc/strain.py
This comments out temporarily the changing of the analyzed slice when there is a single injection in a segment.
Using the "injection-window" option still will only save triggers nearby to an injection however, but it will happen at the end of the program after clustering and veto calculations. 
Related to, 
#246
> disable injection window analyze slice shrinking

- bin/hdfcoinc/pycbc_make_hdf_coinc_workflow
- bin/hdfcoinc/pycbc_page_vetotable
- pycbc/workflow/ini_files/example_hdf_bns.ini
- pycbc/workflow/plotting.py
- setup.py
This PR adds the veto definer table to the summary pages. See for example: https://sugar-jobs.phy.syr.edu/~cbiwer/pycbc_test_workflow/mf_test/1._analysis_time/1.2_veto_definer/
> add veto definer table to summary pages

- pycbc/workflow/jobsetup.py
There is an edge-case bug in jobsetup.py that will cause the setup code to fail if the length of a data segment is exactly equal to the data that the job wants to read in. In this particular ER8 example there is a 2064 second long data stretch raising this failure. This causes a divide-by-zero error at line 429, which can be avoided by catching this special case and setting the job_time_shift (which will never be used as there is only one job for this segment) to 0.
> Fix an edge-case bug in jobsetup.py

- bin/pycbc_make_html_page
- pycbc/workflow/plotting.py
This allows the location of the top-level template in pycbc_make_html_page to be specified relative to the installation directory, as with the other assets.  If a full path is provided it will be used, otherwise the template will be found under pycbc.results.__path__.  In addition this changes the workflow generator to pass a relative location.
I have confirmed that with these changes it is possible to run a full workflow with executables built by pyinstaller.
> Allow the location of the top-level template to be relative

- bin/hdfcoinc/pycbc_page_coinc_snrchi
- bin/hdfcoinc/pycbc_page_sensitivity
In pycbc_page_sensitivity, default to the current LALSimulation spin
convention, but let the user change it. In pycbc_page_coinc_snrchi,
fill in the caption and command line in figure metadata. Minor fixes
to the same scripts are also included.
> Improve coincident SNR/chi^2 and sensitivity plots

- bin/hdfcoinc/pycbc_make_hdf_coinc_workflow
- pycbc/workflow/__init__.py
- pycbc/workflow/minifollowups.py
This adds a skeleton module for minifollowups to ``pycbc.workflow``.
Note that the module will not run unless ``[workflow-minifollowups]`` is in the ini file, if it is not, then it will just exit the module and continue with the workflow generation. This section has not been added to the example ini files because there still is more work to do.
I provide an example of how to add an executable to the module.
https://github.com/ligo-cbc/pycbc/compare/ligo-cbc:master...cmbiwer:mf_pr?expand=1#diff-6d5d67ddd622a3b42cb10c895f203f90R62 - Create a class for creating nodes for the executable
https://github.com/ligo-cbc/pycbc/compare/ligo-cbc:master...cmbiwer:mf_pr?expand=1#diff-6d5d67ddd622a3b42cb10c895f203f90R50 - Then create an instance and create a node for the n-th loudest job.
At the end you …
> Add minifollowups module to pycbc.workflow

- bin/hwinj/pycbc_generate_hwinj
This PR casts the PSD as double precision in ``pycbc_generate_hwinj``. PSD is used in calculating sigma and the waveform is generated as a ``complex128``; this makes them compatible.
> Cast PSD as double in pycbc_generate_hwinj

- bin/pycbc_coinc_time
- setup.py
This adds a script to calculate the coincident time for the offline PyCBC search. 
Here is an example command line. It accounts for filter padding and vetoes as given by the veto definer. It is based on direct queries to the dqsegdb. 
pycbc_coinc_time \
--science-names  H1:DMT-ANALYSIS_READY:1 L1:DMT-ANALYSIS_READY:1 \
--gps-start-time 1124349317 \
--gps-end-time   1125990017 \
--segment-server segments.ligo.org \
--analysis-start-pad 120 \
--analysis-end-pad 24 \
--science-veto-levels 1 \
--trigger-veto-levels 12H \
--minimum-segment-length 2064 \
--veto-definer H1L1V1-ER8_CBC_OFFLINE.xml \
--verbose
> add script to calculate coincident time for the offline pycbc search

- bin/hdfcoinc/pycbc_distribute_background_bins
- pycbc/events/coinc.py
This allows distribute_background_bins to bin in SEOBNRv2Peak. It also changes the syntax of the bin argument to use colons instead of '-', in case a parameter is added that can have negative values. Tested and seems to work, although the syntax change will mean config files will have to change.
> Add ability to bin coincs using SEOBNRv2Peak

- bin/hwinj/pycbc_generate_hwinj
This PR adds an optional keyword arg to ``psd.from_cli`` called ``sample_rate``. And this PR allows ``pycbc_generate_hwinj`` to use this optional argument.
I received an error ``ValueError: Incorrect choice of segmentation parameters`` and noticed that the ``sample_rate`` var that is calculated is slightly off, eg. it was setting ``sample_rate`` to 16379Hz instead of 16384Hz.
For example:
```
>>> N=4011                                # length of h(t) time series in samples
>>> sample_rate=16384                     # sampling rate of time series
>>> delta_f = 1.0 / ( N ) * sample_rate   # calculate frequency step
>>> ((N/2 +1) -1) * 2 * delta_f           # calculate sampling rate like in psd.from_cli
16379.915233108952
```
I have witnessed this when ``N`` is not an integer multiple of the …
> Add optional sample_rate arg to psd.from_cli function

- docs/hwinj.rst
Adds PSD options (``--psd-estimation``, ``--psd-segment-length``, ``--psd-segment-stride``) to the example ``pycbc_generate_hwinj`` command.
> Add PSD options to hwinj documentation.

- bin/pycbc_coinc_time
The current time estimate could include segments that hang off the requested time, as the segment query function returns all segments that intersect the requested time.
> make sure we restrict segments to those within the requested gps times

- bin/hwinj/pycbc_generate_hwinj
- docs/hwinj.rst
This PR gives ``pycbc_generate_hwinj`` both a ``--psd-low-frequency-cutoff`` and a ``--waveform-low-frequency-cutoff``.
The ``--psd-low-frequency-cutoff`` option is the start frequency for generating the PSD that is used in calculating SNR. The waveform used in the SNR calculation is also started at this frequency.
The ``--waveform-low-frequency-cutoff`` option is the start frequency for generating the waveform that gets saved to the ASCII file.
This PR also updates the hwinj doc page with the new options.
> add low frequency option for waveform generation and SNR calculation in hwinj

- pycbc/workflow/core.py
We need to be able to fetch executables via https as well as gsiftp (and might need other schemes in the future).
> Allow for URL schemes other than gsiftp

- bin/hwinj/pycbc_generate_hwinj
- docs/hwinj.rst
This PR depends on #299.
This PR changes ``pycbc_generate_hwinj`` over to the multi-IFO option groups so that you can read in data for each IFO, eg. set ``--channel-name H1:${CHANNEL_NAME_H} L1:${CHANNEL_NAME_L}``, etc.
> switch pycbc_generate_hwinj over to multi-IFO option groups

- examples/cal/foton_filter_esd_saturation/pycbc_check_esd_saturation.sh
- examples/cal/foton_filter_esd_saturation/pycbc_foton_filter
- pycbc/filter/fotonfilter.py
This PR adds an example to the ``cal/`` dir that filters a single-column ASCII file that contains h(t) to get ETMY DAC counts.
Example command:
```
sh pycbc_check_esd_saturation.sh --data-file ~/src/pycbc_foton_dev/examples/cal/foton_filter_INJ_BLIND/hwinj/H1-HWINJ_CBC-1126257409-13.txt --gps-start-time 1126256416 --gps-end-time 1126256417 --ifo H1 --frame-type H1_R --sample-rate 16384 --calcs-filter-file /home/${USER}/src/calsvn/h1_archive/H1CALCS.txt --sus-filter-file /home/${USER}/src/calsvn/h1_archive/H1SUSETMY.txt
```
> add example to cal dir to test ETMY DAC saturation

- bin/hwinj/pycbc_generate_hwinj
- bin/hwinj/pycbc_insert_frame_hwinj
- docs/hwinj.rst
- setup.py
This PR:
* Adds an executable ``pycbc_insert_frame_hwinj`` that inserts the single-column ASCII file for hardware injections into frame data so that it can be recovered by ``pycbc_inspiral``.
* Updates the hardware injection documentation so that it has examples on how to use ``pycbc_inspiral`` to recover the injection from the XML file or the ASCII file.
* Changes waveform generation low frequency cutoff for SNR calculation to be the same as the PSD to save time.
> add examples for recovering hardware injections to doc

- bin/hwinj/pycbc_generate_hwinj
This PR gets the number of sample points from waveform low freq cutoff in ``pycbc_generate_hwinj``.
> Get number of sample points from waveform low freq cutoff

- examples/cal/foton_filter_esd_saturation/README.rst
- examples/cal/foton_filter_esd_saturation/gwpy_plot_hwinj
- examples/cal/foton_filter_esd_saturation/pycbc_check_esd_saturation.sh
This PR adds a README.rst file for the ESD saturation example in ``examples/cal/foton_filter_esd_saturation/``.
EDIT: Example of rendered doc page is https://github.com/cmbiwer/pycbc/blob/foton_doc_dev_2/examples/cal/foton_filter_esd_saturation/README.rst
> Add documentation for ESD saturation example

- examples/workflow/data_checker/daily_er8.ini
- examples/workflow/data_checker/daily_test.py
- examples/workflow/data_checker/run_daily_test.sh
This updates the data_checker example so that it can run on ER8 data (also adding an ER8 ini file).
Currently this points to a local veto-definer file, but I can update this once the ER8 veto definer is up and running.
Most of the changes to the script itself are needed because it seems I can no longer copy the segment list returned by the segment generation function.
> Changes to make data_checker example work in ER8

- pycbc/types/frequencyseries.py
Add the ability to write XML format frequency series when saving a PSD. This has been tested with the bank generation codes (ie. the PSD module) and verified to work with sBank (although sBank demands that we do *not* prepend the data with 0s). To resolve #313 this now needs to be tied into pycbc_average_psd, maybe @titodalcanton can take this on, or provide me an example for testing? Basically I think all is needed is to convert to FrequencySeries and then use the built in .save function of the class instead of rewriting this in the executable.
For some reason an instrument is required when writing these files. I think this is meaningless in general as we might be writing some design PSD, or some multi-ifo PSD, and I do *not* think this quantity is relevant (nor the f0 value in the …
> Add XML option when outputting FrequencySeries

- bin/hwinj/pycbc_generate_hwinj
- bin/hwinj/pycbc_generate_hwinj_from_xml
This PR:
* Fixes the issue John V. was having where ``pycbc_generate_hwinj_from_xml`` will generate all waveforms at a GPS time into the same file. Instead now it checks for the ``simulation_id`` column and will only inject one waveform per file. Wasn't a problem with ``lalapps_inspinj`` since ``lalapps_inspinj`` spaces injections out in time.
* Corrects the value of chirp mass stored in the XML table. This didn't have an affect on the waveform generation since ``mass1`` and ``mass2`` are used. For a double check, here is before PR h(t) plot https://ldas-jobs.ligo-wa.caltech.edu/~cbiwer/hwinj_check/hwinj1_patch/H1-TIMESERIES_HWINJ_ORIG_CBC_2.png and after PR h(t) plot https://ldas-jobs.ligo-wa.caltech.edu/~cbiwer/hwinj_check/hwinj1_patch/H1-TIMESERIES_HWINJ_CBC_2.png ... they are the …
> Restrict output files of pycbc_generate_hwinj_from_xml to one waveform per file

- pycbc/psd/__init__.py
- pycbc/psd/estimate.py
Hi Alex,
I identified two places where PSD<flow is set to 0. First when using an analytical PSD or PSD from file, and second when using inverse-psd-length. I didn't really see why the inverse-psd-length sets these value to 0 after shortening the PSD length so I just removed it (although the inverted PSD values < flow are still taking values of 0 before truncating the PSD length , and that is meaningful).
Does this look okay to you? I've tested the returned PSD for these use cases and it does what is expected.
> Do not set PSD < flow = 0

- pycbc/workflow/core.py
- pycbc/workflow/segment.py
This calls reolve_url in make_external_call, which allows executables be be specified as URLs.  
get_command_line strips the protocol out of the PFN on assumption that if there is one its file:, so this path also adds an additional parameter to bypass that.
> Issue #306, support remote executables at workflow-generation time.

- pycbc/workflow/core.py
Each run of the workflow generator will leave parsed ini files in parsed_(seconds since the epoch).ini and a symlink will be created to the latest one.
> Issue #305. Write to timestamped parsed files, create symlinks to latest

- bin/hdfcoinc/pycbc_make_hdf_coinc_workflow
- bin/minifollowups/pycbc_page_coincinfo
- bin/minifollowups/pycbc_plot_trigger_timeseries
- bin/minifollowups/pycbc_single_template_plot
- bin/pycbc_single_template
- pycbc/frame.py
- pycbc/results/table.py
- pycbc/workflow/minifollowups.py
- pycbc/workflow/plotting.py
- setup.py
This adds followup plots for the top X foreground events. It's at the point that I think it is worth recommitting to master. 
The following features are implemented
* trigger time series plots
* snr/chisq plots (created from a pycbc_inspiral based single template followup code)
* tables with the easiest to extrac coinc / single trigger information. 
If need be I can split this into separate pull requests for each script, followed by the changes to the workflow. 
Example page using the latest code.
https://sugar-jobs.phy.syr.edu/~ahnitz/projects/bigdog_rerun/plots/gw12/html/7._result/
> add minifollowups v1

- bin/hdfcoinc/pycbc_coinc_statmap
- bin/hdfcoinc/pycbc_coinc_statmap_inj
This should address the issue in #340. Specifically the dtype of empty arrays is important if they are going to be numpy.concatenate[d] later. I'm about to add a second part to this to also do this in statmap_inj, is there anywhere else where this should be done?
@stevereyes01 can you verify that this works for you? You will need to rerun parts of your workflow to test this, you do *not* need to rerun inspiral jobs, but I would rerun everything after that.
> Dtype of empty arrays should be correct

- pycbc/workflow/tmpltbank.py
This is a lightweight interim fix allowing template banks to be loaded remotely.  This uses the same mechanism as remote executables, loading the remote file at workflow-generation time.  The longer-term solution is to re-engineer the File class as described in https://github.com/ligo-cbc/pycbc/issues/297 .
I have verified that this produces the correct dax with both local files and http URLs.
> Support remote pregenerated banks.

- examples/cal/foton_filter_esd_saturation/pycbc_foton_filter
- pycbc/filter/fotonfilter.py
This is a more robust way to get the gain from a gain-only filter module using the foton python package.
> Use iir2z to get the gain of a gain-only foton module

- .travis.yml
- tools/install_travis.sh
- tools/run_travis.sh
* Use travis_retry for downloads and don't hardcode the SWIG mirror
* Run lalsimulation unit tests after building lalsuite
* Add banksim and faithsim executables to tests
> A few improvements to Travis testing

- pycbc/filter/fotonfilter.py
When I cleaned up the conflict from PR #352 I forgot to add back this import.
> Add missing import to fotonfilter

- bin/hdfcoinc/pycbc_make_hdf_coinc_workflow
- pycbc/workflow/__init__.py
- pycbc/workflow/gatefiles.py
- pycbc/workflow/jobsetup.py
- pycbc/workflow/legacy_ihope.py
- pycbc/workflow/matched_filter.py
- pycbc/workflow/psd.py
This adds a new section to the workflow
```
[workflow-gating]
gating-method = PREGENERATED_FILE
gating-pregenerated-file-h1 = (file or URL)
gating-pregenerated-file-l1 = (file or URL)
```
I've confirmed that
* This section is optional, no error is caused by omitting it
* Each ifo is optional, in the unlikely case where we only having gating files for one
* Remote URLs work
* When provided, the files are added to workflow and the --gating-file argument is added to full data and injection jobs
> Add gating files at the workflow level, allow them to be URLs

- bin/hdfcoinc/pycbc_make_hdf_coinc_workflow
- pycbc/workflow/__init__.py
- pycbc/workflow/jobsetup.py
- pycbc/workflow/plotting.py
- pycbc/workflow/psdfiles.py
- pycbc/workflow/tmpltbank.py
This adds a new section to the workflow
```
[workflow-psd]
psd-method = PREGENERATED_FILE
psd-pregenerated-file = (file or URL)
```
Any file specified here will be passed to the template jobs as well as to plot_psd with the --psd-file argument.  I have verified this results in a correct DAX and that the plotting command works when run by hand.
> Add a section at the workflow level for pregenerated PSDs.

- pycbc/workflow/minifollowups.py
- tools/static/hooks/hook-pycbc.py
This fixes two minor unrelated problems
* pycbc_single_template needs the MKL libraries
* The output to pycbc_page_coincinfo was specified as  "html" instead of "png", causing it to fail with "unsupported format."
> Small bug fixes

- bin/hdfcoinc/pycbc_coinc_statmap
- bin/minifollowups/pycbc_page_coincinfo
- bin/minifollowups/pycbc_plot_trigger_timeseries
- bin/pycbc_single_template
Programs built by pyinstaller run as if given the -S flag
```
[lppekows@sugar-dev3 ~]$ python -S
Python 2.6.6 (r266:84292, Nov 21 2013, 12:39:37) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-3)] on linux2
>>> exit()
File "<stdin>", line 1, in <module>
NameError: name 'exit' is not defined
```
so these programs could appear to have failed to condor.
> exit() -> sys.exit() for pyinstaller

- pycbc/workflow/plotting.py
If the ini file doesn't contain a workflow-psd section the plotting code is passed an empty FileList, which was resulting in a call to pycbc_plot_psd_file with an empty --psd-file argument, resulting in a runtime error.  I have confirmed (by checking the DAX) that this patch does the right thing both when the section is present and missing.
> Fix for case where workflow doesn't have a psd section

- pycbc/workflow/configuration.py
Here's my attempt to fix the issue Duncan reports in #375. @duncan-brown can you let me know if this solves the issue and merge if it does. This shouldn't cause any problems as it would only get raised if a ValueError was about to be encountered anyway!
> Allow commas in value when parsing config object

- bin/hdfcoinc/pycbc_make_coinc_search_workflow
- pycbc/workflow/analysislogging.py
- pycbc/workflow/segment.py
This patch adds the analysislogging module into pycbc_make_coinc_search_workflow. I've tested that this generates the appropriate file at runtime. This should resolve #370, although the still outstanding #127 made this more difficult than it should have been. Once v1.2.0 is released we should spend some time on code clean up tasks.
> Add analysislogging into make_coinc_search_workflow

- bin/hdfcoinc/pycbc_make_coinc_search_workflow
- bin/hdfcoinc/pycbc_merge_psds
- pycbc/workflow/plotting.py
- pycbc/workflow/psd.py
- setup.py
This splits the psd generation into multiple jobs. Current ini files should have the standard behavior. To activate, add the following to the configuration file. 
[workflow-psd]
parallelization-factor = XX
> split psd generation into multiple jobs

- bin/pycbc_dark_vs_bright_injections
- pycbc/workflow/injection.py
- pycbc/workflow/jobsetup.py
- setup.py
This one is for @spxiwh and @a-r-williamson.
PyGRB targets potentially "EM bright" signals only.  Injections to assess the its sensitivity must be performed accordingly.
* Adding the bin/pycbc_dark_vs_bright_injections script: this takes an xml table with injections as an input and separates the injections into potentially EM bright and dim, outputing them in two distinct files.
* Using the new tool bin/pycbc_dark_vs_bright_injections directly in the workflow in order to allow PyGRB to inject SGRB-relevant signals only before the jittering takes place.
> Using SGRB-related injections only in PyGRB

- pycbc/workflow/core.py
Fix for https://github.com/ligo-cbc/pycbc/issues/386 .  I've confirmed that this doesn't break working code and have tested the failure mode by asking for a non-existent ini file and verified that it attempts the download several times.
> Retry failed downloads a few times to protect against transient network errors

- bin/pycbc_inspiral
I noticed in a benchmark that the sigmasq cache was being invalidated by having a different psd reference for each segment. This fixes that so they should have the same reference if they are the same  psd. The issue was that .astype(float32) was called, which created a separate psd instance.
> move psd float conversion to avoid cache invalidation

- bin/hdfcoinc/pycbc_plot_Nth_loudest_coinc_omicron.py
This executable has been modified to generate SEOBNRv2 waveforms for plotting f(t) of a given signal, which is a better representation of the templates used in the offline coincident search and includes spin effects. The f(t) trace is plotted up to the point of maximum amplitude of h(t). Previously the code generated an analytic 3.5 PN waveform that only calculated up to f_ISCO.
Tested on same commands as old executable and it seems to work fine.
> modified inspiral + omicron follow-up plots to use SEOBNRv2 for waveform generation

- pycbc/workflow/core.py
- pycbc/workflow/pegasus_workflow.py
- pycbc/workflow/psd.py
This is still being tested, do not merge this please until I can finish testing this.
This patch addresses #266 by adding methods to add multi-ifo format options directly to pycbc.workflow. I had stated in #266 that this was not possible due to a pegasus bug. That bug appears to have been fixed in the version of pegasus we are currently using (but of course this will not work with the older version)!
Basically, previously a job with multi ifo options would look something like this:
```
<job id="ID0000003" name="average_psd-H1L1_ID8">
<argument>--input-files <file name="H1-CALCULATE_PSD-1123858817-1358905.hdf"/> <file name="L1-CALCULATE_PSD-1123858817-1358905.hdf"/> --detector-avg-file <file name="H1L1-AVERAGE_PSD-1123858817-1358905.txt"/> --time-avg-file …
```
> Multi ifo methods in pycbc.workflow

- docs/workflow/pycbc_make_psd_estimation_workflow.rst
I was following through the instructions here: http://ligo-cbc.github.io/pycbc/latest/html/workflow/pycbc_make_psd_estimation_workflow.html. In general it seemed easy to follow through, but the veto-definer pointed to a file local to atlas. Here is a short fix to point to the git repo.
> Point docs to ER8 veto-definer

- bin/hdfcoinc/pycbc_plot_range
When only one combination of masses/approximant is used, shorten the legend and put masses and approximant on figure title. When more combinations are used, fix an error and keep the old intended behavior (still not quite readable, but at least it works). Plots now look like this:
https://atlas1.atlas.aei.uni-hannover.de/~tito/LSC/newrange1.png
https://atlas1.atlas.aei.uni-hannover.de/~tito/LSC/newrange2.png
> Improve and fix pycbc_plot_range

- bin/hdfcoinc/pycbc_page_ifar
The limits of which timeslides to include in the ifar plot were wrong and in general allowed it to try to look for timeslides where none could exist.
> fix limits on pycbc_page_ifar search for timeslides

- bin/pycbc_make_html_page
This fixes https://github.com/ligo-cbc/pycbc/issues/419 
I've tested it by resetting the permissions on an existing /static directory to be user-only, running the new code and verifying that the permissions were set correctly.
> Make sure permissions on the /static directory are OK

- pycbc/workflow/injection.py
This adds a call to resolve_url.  I tested with multiple injection files and confirmed that the pregenerated files were downloaded and the DAX was correctly built.
This fixes https://github.com/ligo-cbc/pycbc/issues/418
> Allow pregenerated injections files to be remote

- pycbc/workflow/core.py
- pycbc/workflow/psd.py
This applies  temporary fix to the multiifo argument so that they can be used in the current pegasus version. The hope if that future pegasus versions might have a way to respect whitespace, but currently they do not. Also included is a change to the argument so it does not preprend a ('--') which is consistent with the other argument handlers. This also allows giving short options ('-').
> multiifo args temporary fix

- bin/hdfcoinc/pycbc_make_coinc_search_workflow
- bin/hdfcoinc/pycbc_page_injtable
- bin/minifollowups/pycbc_foreground_minifollowup
- bin/minifollowups/pycbc_page_coincinfo
- bin/minifollowups/pycbc_plot_trigger_timeseries
- bin/minifollowups/pycbc_single_template_plot
- bin/pycbc_single_template
- pycbc/workflow/core.py
- pycbc/workflow/minifollowups.py
- pycbc/workflow/pegasus_workflow.py
- pycbc/workflow/plotting.py
- setup.py
Depends on #424 
Move the foreground followup code into a subdax, and remove some of the special arguments originally required by each plotting code to read from statmap files, as they can now get the information on the command line. This should allow for more plots to be added without requiring to reach be able to read whatever special file type we would like to run mini followups on, and for these plotting codes to be used for other followups (injections, background, etc). 
This also moves the combined minifollowups that were below the main results to a sub-page, as currently making a self-contained sub-page is much easier to do for  sub-dax. 
Here is an example output. 
https://sugar-jobs.phy.syr.edu/~ahnitz/projects/bigdog_rerun/plots/gw15/html/
> move foreground mini followups into a subdax

- pycbc/io/hdf.py
Currently the end_time_ns column in the sngl_inspiral is not set. The fix is a simple one, and has been tested and verified to work. (This is the same thing as is done in the coinc table).
> Set end_time of sngl_inspiral correctly

- bin/minifollowups/pycbc_single_template_plot
- tools/run_travis.sh
Add ability to plot HDF file generated by manually supplying template
parameters, show center time on the plot, add log-y option and minor
fixes. Also add single-template executables to Travis tests.
> Improve pycbc_single_template_plot

- pycbc/strain.py
This patch introduces a poor-man transient search which looks for spikes in the whitened strain time series. The resulting list of times is turned into gating information which is then applied to the strain, and optionally saved. This should free us from depending on Omicron and also enable us to test the effect of gating on injections (and ultimately to tune gating parameters) in a straightforward way.
This is still crude and a work in progress. I'm testing it and there's room for making the FFTs faster and exposing more parameters to the CLI.
> Implement automatic gating in strain module

- bin/hdfcoinc/pycbc_make_coinc_search_workflow
Change directory in the workflow before creating the workflow objects so that the parsed configuration files get placed in the output directory and not the cwd.
> change dir before making workflow

- pycbc/workflow/postprocessing_cohptf.py
Hi Ian,
This is just a small bug fix I ran into when comparing different approximants by running multiple tuning injection sets. This is tested end-to-end.
> PyGRB: Change to allow multiple tuning injection sets

- bin/hdfcoinc/pycbc_merge_psds
pycbc_merge_psds currently stores the wrong value in the end_time group. It actually writes the start time there and the end time is anyway miscalculated.
This fixes this by taking the correct end times from the input combine psds files.
BTW, Alex, I am concerned by file pointer management here. At no point are .close() operations ever performed, and every file is actually opened a second time when calling pycbc.types.load_frequencyseries. Could this cause problems if a large number of files are read in?
I also notice that some PSDs appear duplicated in this merged file. Is this intentional? I am using Sam's ER8b run on sugar as my example and test case.
> Set correct end time in merge_psds

- pycbc/workflow/psd.py
This was patched before my removing duplicate psds in the calculate psd exe, but that doesn't quite work if you are pre splitting the bank. You can still end up with boundaries where the same psd will get calculated.
> remove duplicate psds

- bin/hdfcoinc/pycbc_plot_singles_timefreq
- bin/minifollowups/pycbc_foreground_minifollowup
- pycbc/workflow/minifollowups.py
This depends on #427 as it is hard to add new plots without it.
Example result page
https://sugar-jobs.phy.syr.edu/~ahnitz/projects/bigdog_rerun/plots/gw16/html/7._result/7.1_full/
Should not break current ini files, but will not show up without changes. I'll propose the needed configuration change if this patch is accepted.
> Add pycbc_plot_singles_timefreq to foreground minifollowups

- bin/pygrb/pycbc_make_offline_grb_workflow
- examples/workflow/pygrb/ER8/er8_injections_offline.ini
- examples/workflow/pygrb/ER8/er8_injections_online.ini
- examples/workflow/pygrb/ER8/er8_main_offline.ini
- examples/workflow/pygrb/ER8/er8_main_online.ini
- pycbc/workflow/legacy_ihope.py
- pycbc/workflow/segment.py
These commits will allow the pygrb workflow generator to fall back to a single IFO search if there isn't enough data for a coherent search. All that is required for this to happen is to include the option 'allow-single-ifo-search' in the [workflow] section of the configuration file. If this isn't given, the code will exit in the case of insufficient coherent data, which was the previous behaviour.
Since this functionality was designed with the online search in mind, where a single set of static config files are desired, the LegacyCohPTFInspiralExecutable class will check for any options that have been passed to it that aren't compatible with single IFO running. These include face-on/-away options and short timeslide options. It will also add the --do-sngl-chi-tests argument if there is …
> PyGRB: Single IFO running

- bin/pycbc_make_faithsim
This is the minimal change to pycbc_make_faithsim that allows the scr…ipt pycbc_faithsim_collect_results to work while jobs are still running or some of them have failed.
I have tested it and it works.
> Minimal change to collect faithsim results whilst running

- bin/pycbc_dark_vs_bright_injections
- pycbc/workflow/jobsetup.py
@sfairhur This solves the issue you raised (#436) and also allows dark/bright injections to be separated by interpreting the spin components in the sim_inspiral table in two different frame conventions:
(1) L=(0,0,1) [default], where L is the orbital angular momentum direction
(2) N=(0,0,1) [activated by the --frame-axis-view flag], where N is the line of site direction
> Solving issue #436 and allowing for two frame conventions in pycbc_dark_vs_bright_injections

- bin/hdfcoinc/pycbc_make_coinc_search_workflow
- bin/minifollowups/pycbc_page_snglinfo
- bin/minifollowups/pycbc_sngl_minifollowup
- pycbc/io/hdf.py
- pycbc/workflow/minifollowups.py
- setup.py
This patch adds followup of the loudest single detector triggers to the workflow. This is still very much a first-stage cut at this, but I think getting this in early let's people think about, and add, information that is missing.
Currently this uses open-box triggers (does not use foreground censor) and therefore is written only to the open box page. This can maybe be changed if people want to, some of the stuff that would be needed to do this is kind of in place already. I also leave some of the stuff in place that will be needed to do the single_trigger plots, even though currently that is unused.
@ahnitz if you want to test this on your end to make sure everything is working fine, that would be good!
My example page is here:
https://galahad.aei.mpg.de/~spxiwh/LVC/ER8/analyses/uberbank/ …
> Add sngls minifup to workflow

- bin/hdfcoinc/pycbc_make_coinc_search_workflow
- bin/minifollowups/pycbc_page_snglinfo
- bin/minifollowups/pycbc_sngl_minifollowup
- pycbc/io/hdf.py
- pycbc/workflow/minifollowups.py
This converts the single trigger minifollowups into closed-box plots by using the foreground censor veto file. This has been tested:
https://sugar-jobs.phy.syr.edu/~spxiwh/aLIGO/O1/o1_sep26-oct08/with_minifups/run1
and seems to work as intended.
As an aside, I was, of course, using the re-use cache file functionality when doing this. This included some of Soumi's followup dax files in the input.map. The planner failed completely when trying to plan Soumi's dax files that had been copied over. Probably we should not reuse these sub-dax files? If that is the case then should/can we stop them appearing in the output.map files?
> Closed box sngl minifollowups

- bin/minifollowups/pycbc_plot_trigger_timeseries
pycbc.events returns an array for the newsnr if there is more than one event, but a number otherwise:
https://github.com/ligo-cbc/pycbc/blob/master/pycbc/events/events.py#L178
pycbc_plot_trigger_timeseries always assumes that this is an array. This adds a try/except to handle the case where there is only one.
> handle case where newsnr returns a number

- pycbc/workflow/core.py
Addresses https://github.com/ligo-cbc/pycbc/issues/326 .  This adds a directory argument to resolve_url, if not supplied the current working directory will be used.  It also handles file://localhost URLs by passing all file: urls to urllib2.
I have tested this by generating workflows with all of
* https://
* file:///path/to/file
* file://localhost/path/to/file
and verified that all cases were handled correctly.
> Issue #326, add a target directory and more general file urls to resolve_url

- bin/hdfcoinc/pycbc_make_coinc_search_workflow
- bin/minifollowups/pycbc_injection_minifollowup
- bin/pycbc_single_template
- pycbc/workflow/minifollowups.py
The presentation of these plots still needs improvement. But this patch adds in SNR timeseries to the minifups page, and adding a new code block in minifollowups.py to interact with this code not using the statmap file.
An example of this is here:
https://sugar-jobs.phy.syr.edu/~spxiwh/aLIGO/O1/o1_sep26-oct08/with_minifups/run3/5._injections/5.10_followup-BBH01_INJ/
> Adding SNR timeseries to minifups page

- bin/minifollowups/pycbc_injection_minifollowup
- bin/minifollowups/pycbc_single_template_plot
- pycbc/workflow/minifollowups.py
This edits the title of the injection SNR/chi2 time series plots by making the title clearer and adding a caption. The caption includes masses and spins of the template that was used.
Example here:
https://sugar-jobs.phy.syr.edu/~spxiwh/aLIGO/O1/o1_sep26-oct08/with_minifups/run4/5._injections/5.10_followup-BBH01_INJ/
> Improve presentation of injection minifollowup SNR/chi2 time series

- bin/minifollowups/pycbc_sngl_minifollowup
- pycbc/workflow/minifollowups.py
Another change to add SNR/chisq plots to the sngl minifollowups.
Alex: Note that I declare the intermediate HDF files as do not store. The reason for this is that web directories were starting to hit 50GB because of all these files lying around in the web directory.
Example:
https://sugar-jobs.phy.syr.edu/~spxiwh/aLIGO/O1/o1_sep26-oct08/with_minifups/run5/3._single_triggers/3.5_sngl_H1/
> More updates to minifups

- bin/hdfcoinc/pycbc_get_loudest_params
This script will find the loudest SNR or newSNR trigger in a single IFO trigger file, extract the parameters of the trigger/template, and write them to HDF and/or stdout.
The --print-params flag causes the information to be printed to stdout. 
Providing the --output-file option will write the information to the indicated HDF file.
Example call:
pycbc_get_loudest_params \
--single-ifo-trigs H1-HDF_TRIGGER_MERGE_BBH02_INJ-1127271617-1027800.hdf \
--tmpltbank-file H1L1-BANK2HDF-1127271617-1027800.hdf \
--ifo H1 \
--print-params \
--central-time 1127734738 \
--ranking-statistic snr \
--output-file test.hdf
Example output includes the HDF file and the following to stdout:
end_time [1127734738.2734375]
eta [0.042950626]
chisq [22.281233]
mass1 [66.810371]
mass2 [3.1461709]
mchirp …
> Print trigger params

- bin/pycbc_faithsim
This is not strictly O1 critical but is needed for the IMRPhenomD waveform review and Nat wants to use it too.
Default is None so it should be backwards compatible.
I have tested it and it works.
> added filter_high_frequency_cutoff to faithsim

- bin/minifollowups/pycbc_injection_minifollowup
- bin/minifollowups/pycbc_page_injinfo
- bin/pycbc_single_template
- pycbc/workflow/minifollowups.py
This adds optimal SNR to the injection minifollwups and sorts by decisive optimal SNR the missed injections. Example here:
https://sugar-jobs.phy.syr.edu/~spxiwh/aLIGO/O1/o1_sep26-oct08/with_minifups/run7/5._injections/5.2_followup-BBH02_INJ/
Also fixed:
* Removed print statement in pycbc_single_template
* Fixed edge case bug where very small spins could be printed in the .sub file as --spin2x 0.4356E-6 and cause the parser to fail.
> Implement optimal SNR in inj followups

- tools/static/build_dag.sh
- tools/static/build_one.sh
- tools/static/needs_full_build
This adds a script which generates a dag and a sub file, which performs the pyinstaller bundling in parallel.  It sets
```
export PYINSTALLER_CONFIG_DIR=/usr1/${USER}/`hostname`/${BASHPID}
```
which ensures that the pyinstaller cache is unique even if jobs end up on the same node, to prevent corruption of the intermediate stripped and compressed libraries (this also means the cache isn't actually caching and total compute cost will be larger, but throughput will be much higher).
> Parallel build

- bin/hdfcoinc/pycbc_calculate_psd
- pycbc/__init__.py
Adds function to set a per process cache directory when using multiprocessing. Should be called within your mapped function as,
pycbc.multiprocess_cache_dir()
> use a per process weave cache directory

- tools/static/cant_be_built
- tools/static/hooks/hook-pycbc.py
- tools/static/needs_full_build
This patch incorporates some changes that were needed to build 1.2.2
* Include html assets in all programs (no reason not to, they're small)
* mark a few programs as needing a full build (these completed successfully when run with --help, but failed at later imports)
> Add html assets to everything, mark a few programs that need full builds

- bin/pygrb/pycbc_make_grb_summary_page
This change allows the box to be opened by running the "open_the_box.sh" script that is generated in the post_processing folder of a run.
> Fix for PyGRB box opening

- pycbc/workflow/plotting.py
We use strings with ampersands which can upset the shell.
> quote the names of segments

- bin/pycbc_optimal_snr
As we were discussing on Mattermost, the pycbc_optimal_snr code was using a *lot* of memory. Here I fix this by only storing one PSD per process. As the injections are time sorted this should mean that no PSD are calculated more than once (per core). It also seems that the different cores do injections sufficiently separated in time that they are not using the same PSDs as each other.
I also note that the generation of SEOBNR is *much* slower than PSD recalculation.
I'm adding the 1.2.4 milestone for this. I have tested this in a workflow, but an independent check would also be good!
> Optimize optimal snr

- pycbc/strain.py
* Enable controlling the amount of whitened strain corrupted by
ringing from the command line.
* Taper the strain before whitening it to reduce ringing.
* Downsample the whitened strain before using it.
* Use shorter PSD estimation length and inverse truncation.
* Minor fixes.
Before merging, I'd like to test this by repeating Miriam's run and comparing.
> Reduce potential issues with autogating

- bin/hdfcoinc/pycbc_page_foundmissed
Commit e7bf4ce90d855adefa191c195c8fa3d506687c57 effectively removed the ability to use optimal SNRs, this reenables them.
> pycbc_page_foundmissed: fix missing distance choices

- pycbc/workflow/core.py
This changes the behaviour of jobs when using ifo_list=['H1','L1','V1'] so that options in [executable-H1], [executable-L1], [executable-V1] and executable-H1L1V1 are picked up. (The last may not be meaningful, and may be removed in the future).
This is needed for the O1 GRB runs and should be considered for the 1.2.5 release.
> Use ifo_list and string as section tags

- bin/pygrb/pycbc_make_grb_summary_page
- bin/pygrb/pycbc_make_offline_grb_workflow
- pycbc/results/legacy_grb.py
- pycbc/workflow/legacy_ihope.py
- pycbc/workflow/postprocessing_cohptf.py
- pycbc/workflow/segment.py
A segment availability plot is now generated at run-time and will show the offsource segment in the context of all search IFOs' science segments. If no workflow is generated due to lack of data this is also shown on this plot.
If we have sufficient science data, the plot is passed through to the results page, which has been cleaned up slightly.
> Adding segment plot to and cleaning up result page

- bin/hdfcoinc/pycbc_calculate_psd
Per the description, this is a short-term workaround until https://github.com/ligo-cbc/pycbc/issues/501 can be resolved properly.  I've tested this by building a static executable and running a job that had failed on the command line on a head node.  It appeared to work; one process was busy for a while, the weave cache was populated, and then all four processes became busy.
> Short-term kludge to avoid race condition in weave

- pycbc/strain.py
* Add autogating options to multidetector strain option group.
* Do not save externally-supplied gates falling outside of the
strain data segment actually loaded.
> Two gating-related fixes

- tools/static/build_one.sh
Addresses https://github.com/ligo-cbc/pycbc/issues/502
I had thought this was just a matter of rearranging import statements, but in fact something more subtle is going on.  In some programs, for example pycbc_plot_gating, all the imports are correctly at the top of the program but something down the tree of imports is pulling in cython_blas, printing the error if it's not available, but then catching the exception and continuing.  Finding the root cause may require substantial  digging.
As a simpler fix I've modified the build script to check for the error message.  This will catch every instance of this problem that I've seen.  I've tested it by removing pycbc_plot_gating from the needs_full_build list and confirming that the build script fails with the "missing dependancies" message, …
> Check for case where --help works but cython_blas is missing

- bin/hdfcoinc/pycbc_calculate_psd
- pycbc/events/veto.py
Addresses #533.
I briefly tested this manually both with an empty and full segment file. I'm only assuming though that an empty PSD HDF file will be ok downstream in the workflow. Duncan, do you have a workflow exhibiting the initial issue to test?
> pycbc_calculate_psd: handle no-op jobs gracefully

- bin/hdfcoinc/pycbc_plot_singles_timefreq
Avoid cases where a bunch of loud triggers hidden past the end of the
plot cause no triggers to show up in the actual plot.
> Better trigger selection in plot_singles_timefreq

- pycbc/__init__.py
- pycbc/events/events.py
- pycbc/events/simd_threshold.py
- pycbc/events/threshold_cpu.py
- pycbc/fft/fftw_pruned.py
- pycbc/filter/matchedfilter_cpu.py
- pycbc/filter/simd_correlate.py
- pycbc/vetoes/chisq_cpu.py
- pycbc/waveform/spa_tmplt_cpu.py
- pycbc/workflow/pegasus_files/nebraska-site-template.xml
Addresses https://github.com/ligo-cbc/pycbc/issues/569
This adds -mno-avx2 to all weave calls, which was found to be necessary in order to run on at least some OSG sites.  This has been tested in a full workflow with inspiral jobs sent to UNL, started on sugar-dev2 in /home/lppekows/projects/osg/nebraska-test-003 (I would link to the Pegasus dashboard page, but for some reason jobs I submit from dev2 are not seen by dashboard).
> Add -mno-avx2 to weave to enable running on OSG

- bin/hdfcoinc/pycbc_calculate_psd
- bin/pycbc_optimal_snr
Addresses https://github.com/ligo-cbc/pycbc/issues/501
This runs the first instance outside Pool.map in order to force the generation of the weave cache to be single-threaded.  This is the same short-term fix that was used in pycbc_calculate_psd.
> Short-term kludge to avoid race condition in weave for pycbc_optimal_snr

- pycbc/results/legacy_grb.py
Hi Duncan,
In the hope of rendering #576 unnecessary, can you check if this fixes the issue? We have tried in python by hand on CIT and this allows the import without error. It also follows the import of matplotlib you do within your bank bin plotting code.
Cheers,
Andrew
> Setting matplotlib backend

- pycbc/workflow/plotting.py
The veto definer file is passed to ```pycbc_page_vetotable``` as a bare string. This fixes it so that it is a ```File()``` object and appears correctly in the DAX.
> Veto definer file should have a PFN

- bin/hdfcoinc/pycbc_make_coinc_search_workflow
The recent changes re-organization of the results pages in https://github.com/ligo-cbc/pycbc/pull/575 has left the Analysis Time summary page without a plot, since all the files are in sub-sections. This isn't wrong, but the blank page may make people think that something is up. This adds a couple of sections to the summary page.
> Make an analysis time summary page

- pycbc/workflow/pegasus_files/comet-site-template.xml
GLIDEIN_ResourceName is UCSDT2.  This causes the Requirements expression
in the site template to fail.
Switching to GLIDEIN_Site.  We probably ought to do this for Nebraska
and OrangeGrid too, but we'll get those when we add more sites.
@lppekows @duncan-brown
> For some upstream reason, the GLIDEIN_Site for Comet is UCSD but the

- pycbc/workflow/pegasus_files/osg-site-template.xml
This site template is for workflows that can run at any OSG site (i.e.,
the input files are read from gsiftp://red-gridftp.unl.edu).  Note the
requirements are set to prevent these jobs from running on Sugar.
Jobs submitted to this Pegasus 'site' will actually run on any site
where LIGO is enabled.  So, if this is used right now, the jobs will
run on a combination of OrangeGrid, Comet, and Nebraska (hoping
to add GLOW soon).
If desired, we could add:
```
<profile namespace="condor" key="+DESIRED_Sites">&quot;UCSD,Nebraska,GLOW&quot;</profile>
```
to whitelist specific sites.  This may be desirable to avoid sites like OrangeGrid where the data has already been prestaged.
@lppekows @duncan-brown
> Create a generic OSG site template.

- bin/pycbc_submit_dax
- tools/static/bundle_pycbc_submit_dax.sh
Addresses https://github.com/ligo-cbc/pycbc/issues/589
This patch modifies pycbc_submit_dax in a way that has no effect when run from a local installation.  It also adds a program that uses these hooks to create a self-contained executable by embedding a base64-encoded tar file of the necessary runtime files.
I have tested 
* from within a virtual environment using the version installed with a standard "python setup install"
* outside a virtual environment using the bundled version
and both worked.
> Allow pycbc_submit_dax to be bundled into a self-contained executable

- requirements.txt
This corrects minor problems in the requirements.txt file.  With these changes pip install -r requirements.txt works correctly.
> Remove conflicting M2Crypto, correct mpld

- pycbc/workflow/pegasus_files/osg-site-template.xml
This allows PyCBC to work at OSG sites with a fixed PATH variable.
@lppekows @duncan-brown
> Take globus-url-copy from CVMFS.

- pycbc/workflow/pegasus_files/osg-site-template.xml
Take CA certs from the central location to prevent site-level differences.
@lppekows @duncan-brown
> Use CVMFS version of CA certs on generic sites.

- bin/hdfcoinc/pycbc_page_snrifar
This removes the grid from the non-cumulative plot, and it makes the foreground marker a command-line option (default is triangle).
> Minor updates to non-cumulative plot

- pycbc/workflow/pegasus_files/comet-site-template.xml
- pycbc/workflow/pegasus_files/nebraska-site-template.xml
- pycbc/workflow/pegasus_files/orange-grid-site-template.xml
- pycbc/workflow/pegasus_files/osg-site-template.xml
- pycbc/workflow/pegasus_files/osg-testing-site-template.xml
This patch
* Updates gcc to 4.9.3
* Removes WEAVE_FLAGS, since 4.9.3 includes the full toolchain and -mno-avxe2 isn't needed anymore
* sets X509_CERT_DIR on sites that need it
> Various updates to site catalogs

- bin/pycbc_single_template
There is an edge-case bug in pycbc_single_template when using the window option and within window of the start/end of the analysable segment. Basically the code needs to check if it is at the start or end and then shrink the window as necessary. Otherwise start and end idx can become invalid and this can cause a failure either in this exe *or* in the plot exe.
I would like to get this into a production release as I want to use this in production runs.
Using the window option prevents these jobs having any memory-related problems. This is tested in ongoing chunk5 runs.
> Bug-fix pycbc_single_template --window option

- pycbc/events/events.py
- pycbc/io/hdf.py
thinca uses the string `sngl_inspiral<-->sngl_inspiral coincidences`. Deviating from this convention causes issues with some tools.
> Match coinc definer descriptions to thinca strings

- bin/hdfcoinc/pycbc_calculate_psd
- bin/hdfcoinc/pycbc_merge_psds
Some codes in LALSuite (e.g., BAYESTAR) need this constant, but do not depend on LALInference.
Note that this will cause problems if `pycbc.DYN_RANGE_FACTOR` is ever changed.
This patch is untested. A pycbc expert will need to run it.
> Save dynamic range factor in HDF5 PSD files

- bin/hdfcoinc/pycbc_page_snrratehist
Currently, the snr histogram plot sets the x-limits based on the foreground, even if --closed box is turned on.  This patch also gets rid of that annoying black dot in the middle of the foreground squares.
> Fix closed box snrhist so it doesn't accidently open the box

- bin/hwinj/pycbc_insert_frame_hwinj
This PR adds the ``--low-frequency-cutoff`` so that the code works with fake strain options. Originally the code was only used for inserting the injection into frame data.
> Add --low-frequency-cutoff to pycbc_insert_frame_hwinj

- pycbc/workflow/legacy_ihope.py
- pycbc/workflow/postprocessing_cohptf.py
Hi Steve,
This change allows for the --short-slide option to be given to the trig_combiner code in GRB workflows. I have tested on single and 2 IFO data and it works correctly in both instances.
Cheers,
Andrew
> Adding short slide info to GRB post processing

- examples/cal/foton_filter_esd_saturation/README.rst
- examples/cal/foton_filter_esd_saturation/pycbc_check_esd_saturation.sh
- examples/cal/foton_filter_esd_saturation/pycbc_check_pcal_saturation.sh
- examples/cal/foton_filter_esd_saturation/run_pcal_saturation_example.sh
There is already an example for calculating the number of counts a hardware injection will create at the ESD so that we can check for ESD saturations.
Now we have moved the hardware injection infrastructure over to PCALX. So this PR adds another example for checking the number of counts from the PCAL inverse actuation filter.
There is a script ``run_pcal_saturation_example.sh`` that shows how to do the example.
> Add PCAL saturation example

- bin/hdfcoinc/pycbc_page_snrratehist
The last sigma region just sets it's left boundary based on 1 less. This isn't right if the last boundary is more than 1 higher than the previous one. 
Before 
https://sugar-jobs.phy.syr.edu/~ahnitz/projects/code_testing/test0.png
After
https://sugar-jobs.phy.syr.edu/~ahnitz/projects/code_testing/test0v2.png
> fix bug in setting the left edge of sigma shadings

- bin/pycbc_dark_vs_bright_injections
- pycbc/workflow/splittable.py
Hi Steve,
Here is the code change to set an upper bound on the number of injections that are passed out from the em-bright cuts, with the argument --max-keep.
Andrew
> Adding ability to limit number of bright injs

- pycbc/workflow/pegasus_files/stampede-site-template.xml
Addresses https://github.com/ligo-cbc/pycbc/issues/634 .
This does not set PATH or LD_LIBRARY_PATH for gcc.  In previous tests on Stampede the default installation of gcc worked, but should that no longer be the case other versions are available.
> Stampede site catalog set up for glidein

- bin/minifollowups/pycbc_injection_minifollowup
- pycbc/strain.py
Here's the change needed to add inverted injections into the minifollowups. I do this using the already-existing "inj-scale-factor" argument to inject.py, which, if set to -1, injects the signal inverted in the time domain.
(This needs also ini file change)
> Add ability to invert injections in minifollowups

- pycbc/workflow/legacy_ihope.py
- pycbc/workflow/postprocessing_cohptf.py
This change stops injection sets with similar tags being combined by pylal_cbc_cohptf_injcombiner. Before this change, if we had 3 injection sets with tags 'nsns30inj', 'nsnsnospins30inj', and 'nsns100mpc30inj', injections from all of these would be included in the found/missed files that should only include 'nsns30inj' injections.
Now we pass the full tag (less the compulsory 'inj' suffix) and this fixes the issue when combined with ligo-cbc/pycbc-pylal#20
> Stop conflation of inj sets with similar tags in GRB workflow

- pycbc/results/render.py
Workflow failed on veto-definer file because it had ``VETO`` in the name but does not contain a ``segment`` table.
This PR removes the hardcoding check of the filename and uses a try-except statement to see if the XML file has a segment table.
> Remove hardcoded parsing of filename when rendering an segment XML file

- bin/pycbc_inj_cut
The changes change the name of a couple of options and make the output-missed file optional
> changes to inj_cut to make it easier to incorporate into the pipeline

- docs/index.rst
- docs/upload_to_gracedb.rst
This adds the documentation page that demonstrates how to run the upload_to_gracedb command.
http://galahad.aei.mpg.de/~spxiwh/pycbc_docs_test/upload_to_gracedb.html
> Adding gracedb upload docs page

- bin/hdfcoinc/pycbc_make_coinc_search_workflow
- bin/hdfcoinc/pycbc_page_ifar
Here are the code changes that were needed to make the changes to section IV (ie. page ifar) here:
https://atlas1.atlas.aei.uni-hannover.de/~spxiwh/LSC/aLIGO/O1/analyses/chunk5/o1-analysis5_pt8_invinjs/
as I showed on the call yesterday.
@tdent wanted to look at the changes to pycbc_page_ifar and suggest improvements to the comment.
There is also a potential issue that without the config file changes that I have, open box plots will appear in section 4. Should we change the behaviour so that pycbc_page_ifar requires a --open-box argument to show open-box results instead of doing this by default?
> Page ifar changes

- bin/pygrb/pycbc_make_offline_grb_workflow
Hi Steve,
pycbc_make_offline_grb_workflow has a missing import of sys. When the GRB doesn't fall within any science segments the code should produce the segments plot then exit gracefully via sys.exit().
Cheers,
Andrew
> Adding missing import of sys to PyGRB

- bin/hdfcoinc/pycbc_make_coinc_search_workflow
Whatever caused my run to not have the typo Steve reported also caused me to miss the fact that the open box ifar plots were not appearing in the well in 7.01. This is now fixed and tested:
https://galahad.aei.mpg.de/~spxiwh/LVC/aLIGO/O1/analyses/o1-analysis5_pt10_invinjs_mk3/7._open_box_result/7.01_significance/
> Restore open box ifar plots

- docs/workflow/pycbc_make_coinc_search_workflow.rst
This adds the --remote-staging-site flag  (https://github.com/ligo-cbc/pycbc/pull/655), and cleans up a few other points.
> Update OSG instructions

- bin/minifollowups/pycbc_injection_minifollowup
- bin/pycbc_single_template
- pycbc/inject.py
- pycbc/pnutils.py
- pycbc/strain.py
- pycbc/waveform/waveform.py
- pycbc/workflow/minifollowups.py
Our minifollowup plots of precessing injections are currently broken when using the injection parameters because the precessing injection is filtered against an aligned-spin template with similar parameters to the injection. (They are also broken to a smaller degree in the case of an aligned-spin injection with a different approximant to the template bank).
This fixes this by allowing the pycbc_single_template code to take a use-params-of-closest-injection option, which filters against the actual injection that went into the data. This requires some restructuring of the injection module, but no changes to functionality other than being able to regenerate injection waveforms .... There is also the possibility to extend this to store the injected waveforms to avoid regeneration, but I don't …
> Make pycbc_single_template be able to use the closest injection as filter

- pycbc/results/render.py
Currently ``pycbc_make_html_page`` will fail if there is a non-LIGOLW XML file in the results dir.
This patch makes the try-except statement more general to allow this case to be ignored.
> Fix so that pycbc_make_html_page will not fail if there are non-LIGOLW XML files

- bin/hdfcoinc/pycbc_coinc_statmap
- pycbc/events/coinc.py
Handle the corner case in the function which determines how many triggers are louder than the current value. Currently it would try to access the [-1]  position if the zerolag trigger is quieter than all the background. This isn't likely, but I've been able to force it to happen.
> handle corner case where foreground is quieter than background

- pycbc/io/hdf.py
This PR makes group an option for the ``ForegroundTriggers`` class in the ``pycbc.io.hdf`` module.
The reason is that this class has a nice LIGOLW XML file writing function that I'd like to use to write the ``background_exc`` triggers in the HDF files to LIGOLW XML files.
> Make group an option for ForegroundTriggers

- bin/minifollowups/pycbc_foreground_minifollowup
- bin/minifollowups/pycbc_injection_minifollowup
Make sure the paths are converted to absolute paths. This appears to have already been done in the sngls_minifollowup, but was not in place for the injections or foreground.
> convert argument input to absolute path in minifollowups

- bin/pycbc_submit_dax
Addresses https://github.com/ligo-cbc/pycbc/issues/664
This makes
```
pegasus.data.configuration=nonsharedfs
```
the default, and allows the user to override this setting by either specifying the `pegasus.data.configuration` property directly or giving the `--enable-shared-filesystem` option.  I have tested the various combinations and verified that they work.  I have also verified that using this setting doesn't cause any problems
* [shared filesystem with autogating, for reference](https://sugar-dev3.phy.syr.edu/pegasus/u/lppekows/r/54/w?wf_uuid=f960f184-7971-40dc-9080-a41a369f9f1b)
* [nonshared filesystem with autogating](https://sugar-dev3.phy.syr.edu/pegasus/u/lppekows/r/55/w?wf_uuid=bfe92f2f-a17c-47f4-b6c2-fd5a3b21e25d)
* [shared filesystem with omicron gates, for …
> Make nonsharedfs the default

- pycbc/results/legacy_grb.py
This small change stops a key error being raised when some (but not all) of the IFOs in workflow.ifos don't have science segments around the GRB time.
> Fixing issue for single IFO segments

- pycbc/frame.py
- pycbc/types/array.py
Allows ``frame.py`` to read channels that are ``UNIT4``.
This is needed to read ODC channels.
> Add UNIT4 time series to frame reading.

- bin/hdfcoinc/pycbc_plot_gating
This catches the edge case where there are gating files (so `len(gate_data) > 0`) but those files have no gates in the analysis time.
> Handle case where there are gating files but no gates

- bin/hdfcoinc/pycbc_stat_dtphase
Sorry, forgot to include this elsewhere. Small change to allow setting a seed value in pycbc_stat_dtphase.
> add seed value option

- bin/pycbc_banksim
As discussed on list yesterday, we need to swap the multiplication order to fix the banksim now the the Fplus and Fcross are numpy.floats.
This works fine for me.
> Change order of multiplication

- bin/pycbc_optimal_snr
* Ignore waveform errors only when explicitly requested
* When using time-varying PSDs, handle overlapping PSDs correctly
I tested both changes with a couple dedicated injections but now I'm running in on a full inj set from one of my runs. Please hold on merging until that's finished too.
> Fix two issues in pycbc_optimal_snr

- bin/pycbc_splitbank
This adds the option to provide a frequency cutoff (such as SEOBNRv2Peak) to be used a sorting of a template bank before splitting.
> add frequency cutoff as a possible sorting of a template bank

- bin/hdfcoinc/pycbc_page_sensitivity
Either not setting `--min-dist` or setting it to 0 caused `--max-dist` to be ignored.
Note that we should change the search config files after this goes to production: the current setting `--max-dist 300`, if honored, would be too small.
> pycbc_page_sensitivity: fix behavior of y range options

- bin/hdfcoinc/pycbc_page_segtable
Right now ``pycbc_page_segtable`` H1L1 column is incorrect. It takes the AND of H1 and L1 columns.
What it should do is add the two columns and coalesce the ``segmentlist``. This PR does that.
An example of it can be found here: https://sugar-jobs.phy.syr.edu/~cbiwer/segtable.html
> pycbc_page_segtable fixed H1L1 column

- install_pycbc.sh
I tested out this ``install_pycbc.sh`` script.
It will SVN co the LAL data repo but it doesn't assign the correct path in the ``activate`` executable. So if you run a workflow and use ROMs, the workflow fails.
I had to manually append ``share/lalsimulation`` to the end of ``LAL_DATA_PATH`` in ``activate``.
This PR should fix that.
> Use correct LAL_DATA_PATH if you choose to install it.

- bin/hdfcoinc/pycbc_page_segtable
In #687 I accidentally removed the logic for checking if you should not take the AND of two ``segmentlist``.
So what happens right now is that if ``pycbc_page_segtable`` does not have an & in the ``--segment-name`` option then it takes the AND of the segment with an empty ``segmentlist``. That result is 0. This PR fixes that.
Here's a test of the veto table (A4): https://sugar-jobs.phy.syr.edu/~cbiwer/segtable_2.html
Here's a test of the segment table (A3): https://sugar-jobs.phy.syr.edu/~cbiwer/segtable_3.html
> Fix pycbc_page_segtable for when there is no & in the segment name

- bin/hdfcoinc/pycbc_plot_hist
This PR adds optional command line options ``--bank-file`` and ``--background-bins`` to ``pycbc_plot_hist`` so that we can plot the single-detector histograms for each background bin.
A different PR will add this to the workflow so that we can see the single-detector histograms for each background bin on the html pages.
An example of the plot is here: https://sugar-jobs.phy.syr.edu/~cbiwer/tmp.png
I tested the case without these options and everything works as expected.
Also I added comments to this code because there were none.
> Add options to plot single-detector histograms for each background bin.

- bin/hdfcoinc/pycbc_make_coinc_search_workflow
- bin/hdfcoinc/pycbc_plot_hist
- pycbc/results/plot.py
- pycbc/workflow/plotting.py
This PR adds single-detector histograms for each background bin to the summary pages, an example is here: https://sugar-jobs.phy.syr.edu/~cbiwer/hwinj_run_workflow/test_pr/3._single_triggers/3.02_H1_trigger_histograms/
Example of config file to get those plots is:
```
[plot_hist-bkg_newsnr]
x-max = ${plot_hist-summ_newsnr|x-max}
x-min = ${plot_hist-summ_newsnr|x-min}
x-var = ${plot_hist-summ_newsnr|x-var}
background-bins = ${workflow-coincidence|background-bins}
[plot_hist-bkg_snr]
x-max = ${plot_hist-summ_snr|x-max}
x-min = ${plot_hist-summ_snr|x-min}
x-var = ${plot_hist-summ_snr|x-var}
background-bins = ${workflow-coincidence|background-bins}
```
Things in this PR:
* Adds ``bank_file`` as an option to ``make_single_hist``.
* Add overflow bins to ``pycbc_plot_hist`` background bins …
> Add single-detector histograms to workflow for background bins

- bin/pycbc_submit_dax
- bin/sngl/run_daily_pycbc_export_censored_trigs
- bin/sngl/run_daily_pycbc_make_coinc_search_workflow
- pycbc/workflow/pegasus_files/local-site-template.xml
This PR is dependent on #698.
This PR:
* Adds ``acounting_group_user`` to the local site map for pegasus.
* Adds ``--accounting-group-user`` to ``pycbc_submit_dax``.
* Sets the account group user in the daily script, this requires a LIGO.ORG name (no password needed). I've left my LIGO.ORG in, this could just be a command line option to the run script in a future PR.
> Add --acounting-group-user to pycbc_submit_dax for daily runs

- bin/sngl/run_daily_pycbc_export_censored_trigs
- bin/sngl/run_daily_pycbc_make_coinc_search_workflow
This PR allows the user to put the date on the command line to easily rerun the daily search. If no date is on the command line, then it will get the current date.
The date on the command line should be in the form ``MM/DD/YYYY`` where ``M`` is month, ``D`` is day, and ``Y`` is year.
> Allow daily scripts to get date from command line for easy reruns

- pycbc/types/timeseries.py
This patch adds two helper functions to the timeseries class to prepend and append zeros. We will use these when zero-padding data later, but the functionality should be clear.
> Add some helper functions to append/prepend zeros

- pycbc/workflow/core.py
There is an edge-case bug in the split-lists functionality in workflow.core that can cause the code to look at indexes that don't exist (ie <0 or > numfiles). The fix is a simple one (continue if it does this), but I'm not sure who to assign to look at this, so I will assign it to myself, and push once sanity checks complete unless anyone has any complaints.
> Fix in splitlists in core.py

- pycbc/psd/estimate.py
Estimate.py can suffer from float underflow in some edge cases. Basically new_n is a float that is almost an int. However
```
numpy.arange(0,10.0000001)
```
and
```
numpy.arange(0,9.99999999)
```
do not give the same thing. By adding 1.000001 and then casting back to int we ensure
```
numpy.arange(0,10)
```
which gives the correct behaviour (include the Nyquist point, but *not* an extra point).
This has been tested in inspiral jobs from the test workflow.
> FIx potential underflow in estimate.py

- bin/hdfcoinc/pycbc_page_foundmissed
The optimal snr bug went undetected partially because the f/m plot could not display all y-values and so omitted the points at snr=0.  This includes an option to show (or try to show) all y-values.
> page_foundmissed: enable plotting of all distance/snr values

- bin/hdfcoinc/pycbc_calculate_psd
- bin/pycbc_inspiral
- bin/pycbc_single_template
- pycbc/psd/__init__.py
- pycbc/psd/estimate.py
- pycbc/strain.py
Here is step two of merging the functionality from the zero-padding branch. Specifically here we rework how the PSD structuring is performed in pycbc_inspiral, removing associate_psd, and replacing it with some new functions in the PSD module.
The basic ideas of this change:
* Allow pycbc_inspiral to run even if the data length is not some specific multiple of the PSD length
* Make the PSD estimation and the segmentation for analysis independent. (Now analysis segments just pick the best PSD, but no knowledge of the segmentation is used when generating PSDs).
* With the --psd-num-segments option we can ensure that inspiral jobs use the same data length for PSD estimation even when the amount of data they read in is variable.
* Remove PSD-related code from the top-level executable
PSDs …
> Psd structure work

- bin/pycbc_banksim
* The lack of tapering of very short time-domain signals can produce
artificially small fitting factors. This patch does the tapering as
specified in the taper column of sim_inspiral tables.
* For approximants available both in time and frequency domains with the
same name (e.g. IMRPhenomD), use the frequency domain version.
* Remove a couple unused imports and minor fix to --help.
> Fixes to pycbc_banksim

- bin/sngl/pycbc_export_censored_trigs
- bin/sngl/run_daily_pycbc_export_censored_trigs
1. In bin/sngl/pycbc_export_censored triggers : Added clustering to censored triggers before picking up triggers about min-stat (if one is parsed in the command line)
2. In  bin/sngl/run_daily_pycbc_export_censored_trigs : Removed the condition of picking 1000000 loudest triggers to be written to xml file. Specified a cluster window = 16secs.
> Daily pages export censored trigs

- pycbc/workflow/core.py
- pycbc/workflow/pegasus_workflow.py
- pycbc/workflow/segment.py
The minimum segment length option in the workflow is currently broken as it will try to duplicate a pegasus PFN. The fix seemed trivial but did eventually involve adding a small function in pegasus_workflow.py to expose correctly the pegasus hasPFN function. This is tested and does what it should do now.
> Fix min-segment-length option in segment module

- bin/pycbc_inspiral
- pycbc/psd/__init__.py
The recent removal of associate_psds broke pycbc_inspiral in the case that an injection job is a no-op job because no injections are present in the analysis window. These jobs really shouldn't be in the workflow, but this is still a simple fix. Tested and works.
A slightly more serious problem was in my arithmetic to compute num_psd_measurements, which caused there to be less PSD measurements than jobs (a reminder to Alex that we agreed that the *minimum* overlap between PSDs would be 50%). In the limit of a very short segment, *and* when doing zero-padding this could cause a segment to overlap no PSDs at all! The fix fixes this and is tested.
> Fixes for recent PSD changes

- bin/hdfcoinc/pycbc_make_coinc_search_workflow
- bin/minifollowups/pycbc_foreground_minifollowup
- bin/minifollowups/pycbc_injection_minifollowup
- bin/minifollowups/pycbc_sngl_minifollowup
- bin/pycbc_single_template
- pycbc/workflow/minifollowups.py
This was a pre-existing edge-case bug. It was previously possible, in the case of a science segment *slightly* longer than the minimum (say 2100s long, which means two analysis jobs, with data times almost overlapping) that pycbc_single_template would take the *other* data time overlapping the trigger time, and not the one that was actually used.
Making this problem worse is the fact that job segmentation now depends (or will soon depend, if I haven't yet opened that as a PR) on the values chosen for trig-start-time and trig-end-time (esp. when zero padding).
Therefore pycbc_single_template should also look at the analysed times when figuring out data to read in and use the data and analysed times matching the original inspiral job. This is not such a large change in pycbc_single_template …
> Single template fix

- bin/hdfcoinc/pycbc_page_ifar
Right now ``pycbc_page_ifar`` will fail if there are no plots to point when it tries to set the axes. This PR skips that step if there are no points to plot.
> Only fix axes if there are points to plot.

- bin/hdfcoinc/pycbc_distribute_background_bins
- bin/hdfcoinc/pycbc_make_coinc_search_workflow
- bin/hdfcoinc/pycbc_plot_bank_bins
- pycbc/events/coinc.py
- pycbc/pnutils.py
- pycbc/workflow/coincidence.py
Allow template duration as a parameter, which also requires that various jobs get an argument for the low frequency cutoff to calculate the duration. 
Also generalize the background bins syntax to allow less-than and greater-than bin conditions.
> changes for binning by template duration (also whitespace, sorry)

- pycbc/strain.py
- pycbc/workflow/jobsetup.py
Here are the changes needed to do zero-padding. This basically comes in 3 parts:
* First the code needed to actually do zero-padding, this requires tapering the first and last second of data read in (after removing pad-data) to 0 and then, when creating analysis segments, if asked to construct a segment using times before "0" or after "len(data)" it will append or prepend zeroes allowing the full data-set to be analysed.
* Second the code needed to construct strain segments is altered so that strain segments outside of the data length can be constructed if zero-padding is enabled. This is done by using the trig-start/trig-end options. The code will only do zero-padding if the use-zero-padding option is enabled *and* the trig-start or trig-end time is set such that zero-padding is needed …
> Zero-padding changes

- pycbc/waveform/waveform.py
Use the formula for SEOBNRv2 ROMs instead. Needed for plots and
background binning based on template duration.
> Workaround for missing IMRPhenomD template duration

- pycbc/results/legacy_grb.py
Hi Steve,
This change gets the PyGRB result page to display the 50% exclusion distances. I have tested this [here](https://geo2.arcca.cf.ac.uk/~c1239174/LVC/ER8/pygrb/GRB150906944/GRB150906944_CLOSED/summary.html).
Cheers,
Andrew
> Adds in table for 50% exclusion distances in PyGRB

- pycbc/types/array.py
If you use roll multiple times of the same size it will mistakenly cache the views and not do what you want after the first time.
> fix bug in roll, reset memoize of views

- bin/hdfcoinc/pycbc_page_sensitivity
- pycbc/sensitivity.py
Legend lower left often led to the data being more or less invisible, eg 
https://www.atlas.aei.uni-hannover.de/~tdent/LSC/o1/IMBH/sensitivity_plots/SENSITIVITY_ALLINJ_MCHIRP_VOLUME_TITOPHENOM2.png 
'Best' may not be best, but at least give matplotlib a chance ..
Also a more comprehensible hard-coded Julian year formula.
> dont put the legend on top of the curves..

- pycbc/workflow/datafind.py
Previously the check matched the whole URL. This changes it to
match the segment instead, regardless of URL/file name. This is
necessary e.g. on Atlas, where multiple frame locations can be
returned with different paths.
> Make removal of duplicate entries in frame caches more robust

- bin/hdfcoinc/pycbc_plot_singles_timefreq
- pycbc/pnutils.py
Enable using different approximants (currently TaylorF2 and SEOBNRv2_ROM_DoubleSpin) to compute the inspiral time-frequency curves. This improves the plot by taking into account spins and physical termination frequencies.
> plot_singles_timefreq: enable SEOBNRv2 inspiral tracks

- bin/pycbc_single_template
Hi Tito, here's the bugfix for single template. Basically before patch the start_time could be *less* than the trig_time and then sidx at line 278 would be negative and then [sidx:eidx] was basically unpredictable.
The patch ensures that if trig-start/end is given then start/end is equal to this value. I also added a check on sidx < 0 to make sure that if this happens again the code fails here and not in the plotting code later!
This is tested on your example, both with analysis segments, and with a manual gps-start/end.
> Bugfix for single template

- bin/minifollowups/pycbc_single_template_plot
These two lines should fix an error if the plotting code tries to plot outside of the beginning or the end bounds of a time segment. The plotting code attempts to plot some time window around the injection, but doesn't consider the bounds well. so if you're too close to the boundaries just let the left or right end of the window equal those bounds.
> Out of bounds if windowing is too close to the end points

- bin/hwinj/pycbc_generate_hwinj
- bin/hwinj/pycbc_generate_hwinj_from_xml
- pycbc/detector.py
This PR does the following:
* Changes the naming convention of the output files to match ``tinj`` (the hardware injection scheduling program). Right now the files have to be renamed and it would be best to eliminate this step. Once ``tinj`` has been deprecated we can revert back.
* In the executable ``pycbc_generate_hwinj`` it changes from using the command line options to the lines in the ``SimInspiral`` row. Ie. in the diff you see ``opts.taper`` go to ``sim.taper``, ``opts.geocentric_end_time`` go to ``sim.geocent_end_time``, ``opts.ra`` go to ``sim.longitude``, etc. There is no problem here but its better practice.
* Fixes the effective distance that is stored in the ``SimInspiral`` table, should've had a square root instead of a factor of 2. For those following this, this did not …
> Use tinj naming convention and use SimInspiral instance for derivative calculations

- bin/hdfcoinc/pycbc_coinc_findtrigs
Allow decimation factor to be used with loudest-keep-value so you can set a determined threshold and only decimate below that.
> allow decimation factor and loudest keep value to be used together

- pycbc/workflow/coincidence.py
- pycbc/workflow/core.py
- pycbc/workflow/jobsetup.py
- pycbc/workflow/legacy_ihope.py
- pycbc/workflow/psd.py
The merged files contain all info necessary to proceed with the rest of the pipeline, so dont store the individula inspiral files by default.  This should make NFS happier not to have to deal with 100000's of files ad infinitum.
> workflow: set unmerged inspiral and psd files as non critical

- pycbc/inject.py
- pycbc/waveform/waveform.py
- test/test_waveform.py
This patch allows PyCBC to use the NR_hdf5 approximant in lalsimulation. This simply requires passing the numrel_data kwarg through to lalsimulation. If using get_td_waveform directly, you need to set this if trying to use NR_hdf5.
I also remove the code in inject.py to use the old NR infrastructure (the code is broken anyway ... I actually think the getswigrow functions don't work at all!).
I test this doesn't break anything by using the test_waveform code. As some waveforms don't seem to work I had to edit that script to.
> Support for NR injections in lalsimulation

- bin/hdfcoinc/pycbc_page_sensitivity
The caption as originally written states for the sensitive X vs Significance plot that the darker lines are for dogs out, but in fact it should be a darker line for dogs in (hence the smaller sensitive distance). The lighter lines are said to be for dogs in, but in fact it means they should be for dogs out (hence the larger sensitive distance).
> PyCBC Page Sensitivity has wrong captions

- docs/install.rst
- install_pycbc.sh
This PR adds ``pip install nose>=1.0.0`` to the ``install_pycbc.sh`` script. This is a requirement for installing the HDF5 tar.
Both Swetha and I have encountered this problem already.
This PR updates the install docs with the same line as well.
> Update install script to check for nose before HDF5 install

- pycbc/workflow/configuration.py
Rearranged parts of the code pycbc/pycbc/workflow.configuration.py so that sections like [inspiral&tmplt] get split into [inspiral] and [tmplt] first and then the code does any config-overrides. When the reverse was done, the code gave an error for the case when a config-override is specified for one of the sections, say [inspiral] only. In that case the code stops, because [inspiral] and [tmplt] are merged when it tries to do the override, and therefore thinks that an option has been given twice. Splitting the sections first serves the purpose of a config-override in the required section without the other section intervening.
> Fix to avoid request memory config override to give an error

- pycbc/workflow/pegasus_files/pegasus-properties.conf
Inserted Replica Selection options to pegasus properties file. This will try file URLs first, then XrootD for OSG, then gridftp, then anything else that can be found.
> Inserted replica selection options to default pegasus properties file

- bin/pygrb/pycbc_make_offline_grb_workflow
- pycbc/workflow/legacy_ihope.py
Hi Steve,
This is the change to have PyGRB treat the analysable part of the data in the same way as coh_PTF_inspiral does. This includes the 1 second safety buffer, which is back in coh_PTF with a clearer explanation of what it is for. The pipeline is now consistent when using analyse-segment-end.
Andrew
> Ensure signals are injected into the analysed seg

- bin/hwinj/pycbc_generate_hwinj
The examples for the NR injection infrastructure include using the generate_hwinj code to add an injection to frame data:
https://www.lsc-group.phys.uwm.edu/ligovirgo/cbcnote/Waveforms/NR/InjectionInfrastructure
However, on master, this will produce an invalid injection XML file as the numrel_data column will not be populated. This simple patch adds a command-line option to set this, which defaults to the standard empty string value when not given.
If we are still doing HW injections in O2 we really should consider NR injections! This will ensure that valid XML files are produced if doing that.
> Adding numrel_data argument for hwinj code

- pycbc/workflow/legacy_ihope.py
- pycbc/workflow/postprocessing_cohptf.py
Before this change the post processing was hard coded to expect the
middle of each segment was being analysed. Now, whatever the valid
analysis segment is, it is correctly passed to
pylal_cbc_cohptf_trig_combiner jobs.
See: ligo-cbc/pycbc-pylal#26
> Passes the valid analysis segment to the pp code

- tools/static/hooks/hook-pycbc.py
These libraries allow MKL to be used in bundles, although it is necessary to specify `--fft-backends mkl` to force MKL use.
This will need to be cherry-picked onto the 1.3 branch for the 1.3.8 release.
> Adds two libraries needed to use MKL in bundles

- bin/pygrb/pycbc_make_offline_grb_workflow
- pycbc/workflow/segment.py
The minimum amounts of data before and after the onsource differ
depending on whether --analyse-segment-end is used. This change adds the
calculation of these quantities to the workflow. They can be removed
from the config files.
> Calculating data requirements at runtime

- bin/pygrb/pycbc_make_offline_grb_workflow
The FileList `datafind_veto_files` was not initialised in the case of `lalapps_coh_PTF_inspiral` not being the inspiral executable, leading to an error at line 165.
> Fixes bug when not using lalapps_coh_PTF_inspiral

- pycbc/waveform/utils.py
This adds a function to waveform.utils that will apply a time shift to a frequency series. The function takes in a time to shift the waveform to, and adds a shift equal to the difference between the shift time and the epoch of the frequency series. The shift can optionally be applied in place, or to a copy.
> Add a function to waveform utils to shift an fd waveform in time

- pycbc/waveform/utils.py
The last commit of apply_td_shifts caused it to return an Array instead of a FrequencySeries if a copy was made. This fixes that by using the kludge Alex suggested.
> Fix to last commit of apply_td_shifts

- pycbc/waveform/__init__.py
- pycbc/waveform/generator.py
This patch adds generator.py to pycbc/waveform. This module provides classes for repeatedly generating waveforms in which some of the parameters are fixed. All of the generator classes have a "generate" function which takes a series of numerical values. This values are assumed to correspond to a list of parameters which are set on initialization. An underlying generator function is called with the appropriate arguments and a waveform returned. In this manner, pe codes can use these classes for likelihood evaluation while being agnostic to the details of the waveform generation.
Right now there are 4 classes. The BaseGenerator class, which takes in as its first argument the generator function. The TDomainCBCGenerator and FDomainCBCGenerator inherit from this, fixing the generator function …
> Add waveform generation module to waveform

- install_pycbc.sh
Changes "te" to "the" when it asks for the options about the pip cache.
> Fix typo in install script promt.

- pycbc/__init__.py
- pycbc/events/events.py
- pycbc/events/simd_threshold.py
- pycbc/events/threshold_cpu.py
- pycbc/fft/fftw_pruned.py
- pycbc/filter/matchedfilter_cpu.py
- pycbc/filter/simd_correlate.py
- pycbc/libutils.py
- pycbc/opt.py
- pycbc/vetoes/chisq_cpu.py
- pycbc/waveform/spa_tmplt_cpu.py
- pycbc/weave.py
- tools/einsteinathome/check_GW150914_detection.py
- tools/einsteinathome/fstab.c
- tools/einsteinathome/progress.c
- tools/static/hooks/hook-pycbc.py
- tools/static/hooks/hook-scipy.weave.py
Push the changes for running PyCBC_inspiral on Einstein@Home upstream.
This adds a directory tools/einsteinathome to the source, containing a bit of code useful for Einstein@Home.
The behavior of pycbc_inspiral under normal circumstances is unchanged as long as the environment variables PROJECT_DIR, NO_PKGCONFIG, NO_GETCONF, LEVEL2_CACHE_SIZE, INITIAL_LOG_LEVEL and WEAVE_FLAGS are not set and the command-line option --fixed-weave-cache is not given. If set, the behavior is modified in the way described in the individual commit messages.
> Einsteinathome upstream

- pycbc/inference/__init__.py
- pycbc/inference/likelihood.py
- pycbc/waveform/generator.py
- setup.py
This adds an "inference" module to pycbc, which contains likelihood.py. This file stores classes for estimating likelihood for parameter estimation. Currently, there are two classes, a _BaseLikelihoodEvaluator and a GaussianLikelihood, which inherits from _Base. The base class sets up the general structure, which is to have a data attribute, a waveform_generator attribute, etc. GaussianLikelihood adds a log_likelihood function to this which computes the standard likelihood for Gaussian noise. No marginalization is done, nor is there any PSD fitting. When we want likelihood evaluators that do more fancy things like PSD fitting and/or some internal marginalization (e.g., phase), the intent is these can be added as new classes that inherit from the _Base class and add their own loglikelihood …
> Add inference module

- docs/release.rst
For building the pycbc bundles, there are some steps that have to be done on both sugar-dev2 and sugar-dev3 and some which should be done in either of them. This commit is about adding a few comments before steps to point out specifically where they have to be done. Also some typos have been fixed.
> Added comments and fixed typos in the pycbc bundles instructions

- requirements.txt
Added the dqsegdb and ligo-gracedb dependencies to the requirements.txt file. Without these, jobs running the executables pycbc_coinc_time and pycbc_upload_xml_to_gracedb fail while building the bundle executables, so that the dqsegdb and ligo-gracedb tools have to be installed in the bundle environment if those jobs are to be run. Including those two options in the requirements.txt file would let the dependencies to be automatically included.
> Added dqsegdb and ligo-gracedb dependencies

- pycbc/inference/likelihood.py
This adds a ``__call__`` routine to the BaseLikelihoodEvaluator that calls the loglikelihood function. This makes it so that the an instance of the likelihood class can be called like a function, which (I think) should make it pickle-able, so it'll play nice with kombine's Sampler.
> Make likelihood evaluator callable

- docs/release.rst
- Added steps to cd into the pycbc-software directory and git add the new bundles sub-directory before pushing it to the git repo
- added comments to the explanation for failed jobs while bundling and ways to fix them 
- fixed typo in commands. (all occurrences of pycbc_software --> to pycbc-software)
> Added steps before pushing bundles to the git repo, added comments for handling failed jobs in bundle building, fixed typos

- pycbc/types/array_cuda.py
This is a fix to the kernel name which collides with the function name "norm" and returns an error for GPU normalization.
> Fix to collision between kernel name and function name "norm"

- pycbc/waveform/generator.py
Removes generator_function class instance from FDomainCBCGenerator and TDomainCBCGenerator. Instead, get_fd_waveform and get_td_waveform are used directly in the __init__ for each class. This seems to allow instances of these classes to be pickle-able.
> Make FDomain and TDomain CBCGenerators pickle-able

- pycbc/fft/fftw.py
This is https://github.com/ligo-cbc/pycbc/pull/751 with the comment fixed.
> Set the default measure level to zero

- install_pycbc.sh
I fixed the part of the code that asked for the LAL Reduce Order Model (ROM) data twice when you want to install the LAL Reduce Order Model (ROM) data in a new location.
> Fix for ROM data asking twice

- bin/hdfcoinc/pycbc_page_sensitivity
- bin/hdfcoinc/pycbc_plot_singles_timefreq
also change the sensitivity caption location back to 'bottom left' as it's the least worst default location
> tweak to prevent the timefreq code from plotting vast numbers of gates

- pycbc/workflow/minifollowups.py
Changes ```is``` to ```in``` in comments.
> Fix typo in minifollowup comments

- setup.py
This increments the dev version to 1.5.dev0. For people's reference, this needs to always be beyond the latest release number. (1.4.dev0 < 1.4.0).
> increment dev version 

- bin/hdfcoinc/pycbc_coinc_findtrigs
- bin/hdfcoinc/pycbc_stat_dtphase
This simplifies the file format and the generation of the phase / time / correlation code. It also removes some of the manual settings related to number of bins etc, and replaces them with choices based on expected errors, etc. 
The format no longer stores ratio and magnitude, and instead stores the individual SNRs directly. This removes one of the failure modes for compensating for unequal detector sensitivity. It also makes it clearer how to do the smoothing of the distribution along this axis. 
Another axis for the ratio of detector sensitivity is instead added to simplify the interpretation. 
The code now can be run much faster and produce a viable file, in large part due to the introduction of the smoothing of values across the dimensions. 
The following runs in ~20 minutes on a head …
> simplify phase, time, amp correlation code

- pycbc/inference/__init__.py
- pycbc/inference/sampler.py
- setup.py
This PR adds a module to handle using different samplers. At the moment it has a handler class for kombine.
Also adds kombine to ```setup.py``` install.
> Add handler for MCMC samplers.

- pycbc/inference/__init__.py
- pycbc/inference/likelihood.py
- pycbc/inference/prior.py
- pycbc/inference/sampler.py
- pycbc/waveform/generator.py
- setup.py
This PR adds the functionality to calculate a prior to the likelihood evaluators. If no prior is given during initialization, then its no different than what was already implemented.
This is just a rudimentary implementation so that the samplers (kombine or emcee) can work with the ```pycbc.inference``` modules.
The prior returns ```-numpy.inf``` if the parameters are invalid. If parameters are invalid it does not bother generating a waveform and just returns the value.
EDIT: The prior can be a callable class or a function.
> Add prior to likelihood evaluator.

- pycbc/filter/matchedfilter.py
Aesthetic changes coming from precessing branch:
* Fix whitespace and line wrapping issues
* A personal bugbear: Kwargs *must* be declared as kwargs and should not pretend to be args! This makes changing functions dangerous as then kwargs and args get confused when called like this elsewhere!
* Allow the h_norm kwarg to be passed through matched_filter function.
> Aesthetic changes to matched_filter function

- pycbc/events/events.py
Also from precessing branch.
I had an odd compilation issue, where the findchirp_cluster_over_window function refused to compile for me under weave when running in the context of the precessing search. Declaring curr_ind explicitly and setting it made the code compile and run correctly, and doesn't hurt anything, so I'd like to get this on master even if I don't understand why it's needed!
> Fixes bizarre compilation issue

- pycbc/events/events.py
More precessing stuff. This fix adds a short function to threshold on a *real* SNR timeseries. This is needed as the precessing SNR is already maximized over phase. Undoubtedly this is not the best way to do this, but it is not a major time concern when doing CPU precessing search, so I did not bother to optimize further.
> Add function for thresholding a real SNR timeseries

- pycbc/psd/__init__.py
In #824 @josh-willis reports that there are float-valued indices floating around in the psd module. The psd_data_len operation should be integer arithmetic. I think the solution is just to force the 3 input quantities to be integers when declared. To my knowledge PyCBC does not support non-integer sample-rate or data lengths, so by declaring these as ints up front should solve the problem.
@josh-willis does this solve the problem for you?
> Fix float issue in psd module

- bin/hdfcoinc/pycbc_coinc_bank2hdf
- pycbc/events/events.py
- pycbc/io/hdf.py
I'm starting to merge functionality from the precessing branch back to master. The first of these commits is to add the support for storing precessing bank parameters (the other 4 spins and inclination angle) into the template bank. Currently this is done also for non-precessing searches. I don't think this is a problem, as the new columns will not be read by downstream codes unless altered to do so, and so don't really add any sort of memory/storage burden.
The property "u_val" is also added for triggers *only in the case of precession*. This, along with coa_phase, is used to reconstruct the specific h(t) from h+ and hx.
> Add support for precessing bank params

- pycbc/results/legacy_grb.py
Sometimes, in cases where we have no data, the produced segment plot was not including the time of the GRB and was therefore uninformative. This change ensures the plot will be centred on the GRB time ([example](https://geo2.arcca.cf.ac.uk/~c1239174/LVC/O1/pygrb/GRB151229A/GRB151229A_segments.png)).
> Ensuring the GRB time is centred on plot

- pycbc/psd/__init__.py
Commit #837 broke the code in the case that psd_num_segments is not given (which is still the standard behaviour, although we should be giving this in pycbc_inspiral.) The fix is reasonably simple, don't cast to int until checking that num_segments is not None.
As this breaks standard workflows I will commit shortly unless there are comments/issues.
> Code broken if PSD num_segments is None

- pycbc/waveform/__init__.py
- pycbc/waveform/generator.py
- pycbc/waveform/ringdown.py
- pycbc/waveform/utils.py
Module that generates frequency domain damped sinusoids for ringdown searches, and new class in generator.py.
Right now the ringdown module only incorporates the fundamental quasi-normal mode, and it takes the frequency and the damping time as input parameters (amplitude, phase, and starting time can also be given, but they are set to 1, 0, and 0 by default).
> Ringdown module 

- bin/plotting/pycbc_plot_waveform
- setup.py
Add a code to make plots of template waveforms. This requires a new function in waveform.py to return h+ and hx (which I'll post a PR for soon). An example output is this particularly bad example of a NSBH SpinTaylorF2 waveform:
http://galahad.aei.mpg.de/~spxiwh/H1-PLOT_WAVEFORM_P1_0-1126051217-220400.png
which seems to suggest that SpinTaylorF2 has similar issues to IMRPhenomP ... but more on that soon.
> Add new plot_waveform code

- bin/inference/pycbc_mcmc_plot_acceptance_rate
- bin/inference/pycbc_mcmc_plot_acf
- bin/inference/pycbc_mcmc_plot_corner
- bin/inference/pycbc_mcmc_plot_samples
- setup.py
This PR replaces #838.
This PR adds 4 executables to ```bin/inference```, they are:
* ```pycbc_mcmc_plot_acceptance_rate```: plots fraction of samples accepted at each iteration
* ```pycbc_mcmc_plot_acf```: plots autocorrelation function for a parameter
* ```pycbc_mcmc_plot_corner```: plots posteriors as a corner plot
* ```pycbc_mcmc_plot_samples```: plots all samples for a parameter
> Add some MCMC plotting executables

- requirements.txt
@ahnitz ,
I have uploaded [v0.9.6 of pycbc-pylal](https://pypi.python.org/pypi/pycbc-pylal/0.9.6) to PyPI, and tested by pip installing on a number of different machines, so can we increment the version listed in the requirements file?
Thanks
> Increment pycbc-pylal requirement to latest 0.9.6

- pycbc/workflow/postprocessing_cohptf.py
@sfairhur ,
This change allows the `open_the_box.sh` script to be written whether using the nonlocal static binaries or not.
Andrew
> Pygrb pp static fix

- pycbc/vetoes/autochisq.py
- pycbc/vetoes/bank_chisq.py
More precessing stuff, this one should be trivial.
Add stubs for the precessing auto and bank chi-squareds. This just raises NotImplemented Errors now, but we can at least hook them up in inspiral_skymax.
> Add stubs for precessing auto and bank chisqs

- tools/static/cant_be_built
- tools/static/hooks/hook-pycbc.py
- tools/static/needs_full_build
Hi @spxiwh 
This commit is to fix a few issues I had in bundling v1.4, particularly adding the *.dat file(s) that live in pycbc/tmpltbank/ns_sequences into the bundling so that a bundled binary of `pycbc_dark_vs_bright_injections` will run.
> Adding the dark v bright data files to build

- bin/inference/pycbc_make_inference_workflow
- bin/inference/pycbc_mcmc_plot_samples
- pycbc/workflow/mcmcfollowups.py
- setup.py
This PR adds an executable ```bin/inference/pycbc_make_inference_workflow``` that is similar to ```pycbc_foreground_minifollowups```, in order to run a sub-workflow for parameter estimation.
It also adds a ```pycbc.workflow.mcmcfollowups``` module that handles setting up the plotting jobs and has a function ```setup_foreground_inference``` that can be used in another workflow generator (eg. ```pycbc_make_coinc_search_workflow```) to run the inference workflow as a sub-workflow.
This PR only adds this code, it does not add it to the coincidence search yet.
An example workflow configuration file would have the sections:
```
[workflow-inference]
num-events = ${workflow-minifollowups|num-events}
data-seconds-before-trigger = 30
data-seconds-after-trigger = 2
```
Where the data seconds options …
> Add script for making inference workflow.

- bin/inference/pycbc_mcmc_plot_acceptance_rate
- bin/inference/pycbc_mcmc_plot_acf
- bin/inference/pycbc_mcmc_plot_corner
- bin/inference/pycbc_mcmc_plot_samples
This PR adds meta-data information (caption, title, command line) to the MCMC plots for the HTML pages.
Page will look like: https://sugar-jobs.phy.syr.edu/~cbiwer/tmp/tmp_workflow_2/
> Add meta-data to MCMC plots.

- bin/minifollowups/pycbc_foreground_minifollowup
- bin/minifollowups/pycbc_injection_minifollowup
- bin/minifollowups/pycbc_sngl_minifollowup
- bin/pycbc_single_template
- pycbc/workflow/minifollowups.py
Here are the changes to minifollowups from the precessing search. Specifically:
* Hook up the plot_waveform code (for aligned-spin searches too!) to give template waveform plots on the sngl minifollowups pages.
* Add support for precessing filters in pycbc_single_template
* Hook up functionality throughout the 3 minifollowups generators.
Here is a result page with all this present:
https://galahad.aei.mpg.de/~spxiwh/LVC/aLIGO/O1/analyses/precessing/NSBH/smallrun_run2/
(Yes, one of the chisq values is recorded as negative for *one* trigger. I don't know why yet, but it's nothing to do with this code!)
> Precessing search changes to minifollowups

- pycbc/waveform/waveform.py
These are the changes to the waveform module needed for the precessing search:
* We add a two-polarization waveform generation routine, allowing a template to return both h+ and hx (using the same ideas and methods as the single-polarization call)
* We add in length estimates for IMRPhenomPv2 and SpinTaylorF2. Currently this is not great (as it uses an aligned-spin estimator), but can be improved in the future.
* We add a fall-back hack for SpinTaylorF2, such that if the system is aligned-spin, *and* spin2z is non-zero the approximant will fall back to TaylorF2. This allows us to have a template bank containing aligned-spin spin2!=0 waveforms and precessing spin2=0 waveforms with the [Spin]TaylorF2 approximant.
> Waveform module changes for precessing search

- pycbc/io/__init__.py
- pycbc/io/record.py
This mergers a slightly stripped down version of Collin's record array subtype. In subsequent patches, I think that some other classes in io/ and the template bank classes can subtype from this.
> add record type to pycbc.io

- tools/static/build_dag.sh
@lppekows I tried to generate and submit the dag for building static binaries and this failed. It turned out to be due to missing quotation marks around the executable path after `prog=` for the two `ligolw` executables the shell script adds to the dag.
I've tested this and have 100% success submitting the dag on `sugar-dev3` with a [proposed v1.4.1 branch](a-r-williamson/pycbc/tree/v1.4). There are some failures running this from master due to some recent additions (MCMC executables, for example).
> Fixing bug in the dag generator

- pycbc/events/threshold_cuda.py
This pull request does two things:
1. Fixes a bug in the CUDA clustering
1. Changes the CUDA clustering algorithm to match the CPU (at present)
Longer term, it is worth investigating whether we can just do the second stage of clustering (over the maxima in each window) on the CPU always, so that we may use the same code.  That would require a performance study.
> Fix gpu clustering

- bin/inference/pycbc_mcmc
- examples/inference/inference.ini
- pycbc/inference/prior.py
This PR replaces #847. It adds a function in ```inference.prior``` that takes the inference configuration file and returns an instance of the distribution class.
> Add helper function for reading distribution from config file.

- pycbc/events/events.py
- pycbc/waveform/bank.py
- pycbc/waveform/spa_tmplt.py
- pycbc/waveform/waveform.py
This makes the minimal changes required to allow one to use a template bank that stores values in an hdf file. This is compatible with the hdf format produced by pycbc_coinc_bank2hdf. 
Requires #854 before examination and merge.
> allow hdf format template bank files

- bin/pycbc_inspiral_skymax
- pycbc/events/events.py
- pycbc/filter/matchedfilter.py
- pycbc/vetoes/autochisq.py
- pycbc/vetoes/bank_chisq.py
- pycbc/waveform/bank.py
- setup.py
I think this is the last patch from the precessing development branch.
Here we add the pycbc_inspiral_skymax front-end code. It has exactly the same CLI as pycbc_inspiral and repeats a lot of the operations (so a lot of code duplication here), but I wasn't sure exactly how to split this off.
There is also some additional minor fixes to other modules resulting from merging latest pycbc_inspiral changes into pycbc_inspiral_skymax. I also added a bit more information in the output files.
> Add precessing inspiral code

- pycbc/workflow/pegasus_files/pegasus-properties.conf
This updates the location of the xrootd server at UNL from `srm.unl.edu` to `xrootd-local.unl.edu`.  The corresponding changes to the cache file in the pycbc-config repo have already been made.
> Update location of xrootd server

- install_pycbc.sh
pycbc_submit_dax is a shell script so needs special handling.  The script to this is already available, this patch just adds a call to that script to the installer.
> Add pycbc_submit_dax to the set of bundles

- pycbc/io/__init__.py
- pycbc/io/mcmc.py
This adds a class that extends ``h5py.File`` for handling the output of the MCMC samplers.
I think we want some kind of handler for the IO as we're beginning to add post-processing scripts that re-do a lot of the same things (eg. thinning), this at least provides a start.
* Adds functions for writing a file and reading the samples from the file. Has options for thinning the samples.
* The label is more of a finesse thing, it should be a latex string like ``$t_\mathrm{c}$`` so our plots look nicer. If its not given, its just the parameters name.
Should this be in ``pycbc.io.hdf``? I feel like that module more specifically handles triggers from the coincidence pipeline.
> Add class for handling MCMC samplers output file

- bin/inference/pycbc_make_inference_workflow
- bin/inference/pycbc_mcmc
- bin/inference/pycbc_mcmc_table_summary
- pycbc/io/mcmc.py
- pycbc/workflow/mcmcfollowups.py
- setup.py
This PR requires #849 and #862.
This PR:
* It adds a table to the HTML page for the MCMC workflow that has the quantiles for each variable args.
* Removes unpacking of ``sampler.run_mcmc`` and ``sampler.burn_in``.
* Implements ``pycbc.io.mcmc.MCMCFile`` in ``pycbc_mcmc`` and ``pycbc_mcmc_table_summary``.
Example page is here: https://sugar-jobs.phy.syr.edu/~cbiwer/tmp/tmp_workflow_3/
> Adds table of posterior values for MCMC HTML page

- docs/release.rst
- install_pycbc.sh
This fixes a problem with the build instructions https://github.com/ligo-cbc/pycbc/issues/876 and also includes the necessary ``ligolw`` tools as bundles.
> Update bundle install and instructions

- bin/inference/pycbc_mcmc
- pycbc/inference/prior.py
On hold because it depends on #864.
This PR:
* Moves the ``from_config`` function for reading distributions from configuration file to a class function of ``Uniform``.
* Allows multi-parameter prior distributions in MCMC executable.
The way to specify a multi-parameter prior distribution in the inference configuration file is to use a ``+`` symbol in the subsection name, eg.
```
[prior-tc]
name = uniform
min-tc = 5.0
max-tc = 31.0
[prior-mass1+mass2]
name = uniform
min-mass1 = 1.0
max-mass1 = 10.0
min-mass2 = 1.0
max-mass2 = 10.0
```
So in the example above, there are two distribution instances created. One for ``tc``, and one for ``mass1`` and ``mass2``.
Whenever a new distribution gets added, there can be a class function that initializes the distribution from the configuration file.
Is …
> Allow MCMC executable to use multi-parameter prior distributions

- pycbc/waveform/compress.py
- pycbc/waveform/utils.py
This adds functions to compute the amplitude and phase of an fd waveform, and a decompression function for fd waveforms. If linear interpolation is desired, some C++ code is invoked using weave; otherwise, scipy's interp1d is used. In testing, I found the linear interpolation to be about twice as fast as the DoubleSpin ROMs. I've tested a few different systems and the interpolated waveforms all give overlaps > 99.5% with the original ROM waveform. A test script can be found here:
https://www.atlas.aei.uni-hannover.de/~cdcapano/public_scratch/test_compression.py
(I thought about adding this script to the test directory, but since it doesn't actually perform unit tests, I'm not sure if it belongs there).
This patch also adds a function to compute frequency from a time-domain waveform.
> Add decompression algorithm to waveform/compress.py

- install_pycbc.sh
@soumide1102 & @duncan-brown ,
With this version of the script I've had success building on both dev2 and dev3. The changes here add lines to build a static `lalapps_coh_PTF_inspiral`, avoid an error when trying to install dqsegdb, and avoid the issue in #858. Can you let me know if there are any problems with this?
Thanks
> Update install script

- pycbc/io/hdf.py
mask_to_n_loudest_clustered_events() does not work correctly if the mask
is a bool array, such as when a filter function has been used before.
This patch makes it work in both cases.
> Fix error in SingleDetTriggers clustering

- bin/inference/pycbc_mcmc_plot_prior
- pycbc/inference/prior.py
- pycbc/io/mcmc.py
- setup.py
This PR just adds an executable that plots the PDF of the distributions from the ``pycbc.inference.prior`` module.
Depends on #849 and #862.
Example plot is here: https://sugar-jobs.phy.syr.edu/~cbiwer/tmp/prior_test.png
> Add executable to plot the prior PDF

- bin/hdfcoinc/pycbc_make_psd_estimation_workflow
PSD estimation workflow is currently broken by some of the recent changes to the segment APIs. This patch gets it to a state where it works and produces results again. However the segment functions are not completely straightforward to me. I tried to apply the same changes that I think went into `pycbc_make_coinc_search_workflow`. Ian/Alex, could you take a look and see if you spot some obviously wrong usage?
There are two additional issues that I want to address next (parallelization of calculate_psd jobs and size of summary page) but I'll deal with those in separate commits.
> Fix broken PSD estimation workflow

- pycbc/workflow/__init__.py
- pycbc/workflow/configuration.py
- pycbc/workflow/core.py
This patch makes it possible to use WorkflowConfigParser without needing Pegasus installed (issue #883). To do this, ``resolve_url`` is moved from ``worklfow.core`` to ``workflow.configuration``, and all imports except for ``workflow.configuration`` in ``workflow.__init__.py`` are encased in a try/except block. I setup a test workflow on atlas to make sure this doesn't break anything else. The dax is running now; dashboard will be here:
https://atlas8.atlas.local/pegasus/u/cdcapano/r/31/w?wf_uuid=ecf7a6b7-8d8b-4110-950c-878b817ecee0
> Allow WorkflowConfigParser to be used without Pegasus

- pycbc/results/static/css/fancybox/2.1.5/jquery.fancybox.css
- pycbc/results/static/js/fancybox/2.1.5/fancybox-orange.js
Somewhere along the line it looks like a nuisance was introduced to the HTML pages. Whenever an image is clicked the HTML page would reset at the top, most likely from some conflicting css. This PR fixes that so that the page remains in place.
Example page: https://sugar-jobs.phy.syr.edu/~cbiwer/tmp/tmp_workflow_5e/
> Fix fancybox overflow

- bin/inference/pycbc_mcmc_plot_corner
This changes the appearance of the corner plot if you only want to plot 1 variable parameter (ie. you only get a histogram instead of 2-D plots plus histograms).
In this PR:
* The plot is larger
* More x-axis tick marks
* Plots all samples
Example plot is: https://sugar-jobs.phy.syr.edu/~cbiwer/tmp/post.png
> Reformat MCMC corner plot if only 1 parameter is being plotted

- bin/inference/pycbc_mcmc
- pycbc/waveform/ringdown.py
This adds approximant names for the two ringdown generation functions currently in waveform.ringdown. They are "FdQNM" and "TdQNM". It also fixes a bug when allocating the array size for the output waveforms; the output was saving an extra sample at the end. Finally, I changed "Amp" to "amp", to be consistent with other waveform parameter names, which are all lower case.
> Add ringdown approximant names and fix some bugs

- bin/inference/pycbc_mcmc
- pycbc/inference/likelihood.py
- pycbc/waveform/generator.py
- pycbc/waveform/utils.py
There is a bug in the way FDomainDetFrameGenerator applies the coalescence time in ``pycbc_mcmc``. Currently, tc is used by apply_fd_timeshift, which takes the difference between it and the start of the FD waveform (the epoch) to figure out what to shift the waveform by. Thus you currently specify tc as an offset from the segment start time in pycbc_mcmc. However, tc is also needed for the detector's response function, as it is used to calculate the sidereal time. This means that with the current setup, the sidereal time will be wrong, as it'll always be with a few 1000 seconds after Jan 6, 1980 00:00UTC.
This patch fixes this by adding an epoch attribute to the waveform generator. This ensures that the appropriate time offset is applied to the waveform by apply_fd_timeshift, and that the …
> Fix tc bug and cache frequencies for applying time shifts

- bin/inference/pycbc_mcmc
- examples/inference/ringdown_example.ini
- examples/inference/run_ringdown_example.sh
This patch adds support to pycbc_mcmc for using frequency-domain QNMs as the waveform model. For this, it just has to know about the ringdown approximants.
This patch also adds an example config file and script to run the mcmc using the frequency domain QNM on a BBH injection in Gaussian noise.
> Add ringdown support to pycbc_mcmc

- pycbc/waveform/generator.py
The patch that added the epoch to the waveform generator broke multi-threading in pycbc_mcmc, as lal.LIGOTimeGPS appears not to be packaged correctly when sent out to slave nodes. This fixes this by storing the epoch in the waveform generator as a float. I tested this with pycbc_mcmc using 4 processors.
> Fix how epoch stored so can be used in multithreading

- bin/plotting/pycbc_plot_waveform
- pycbc/waveform/waveform.py
Some fixes to plot_waveform. Specifically:
* Allow the code to handle approximant strings, like in uberbank workflow
* Allow the code to be able to use SPAtmplt (by falling back on TaylorF2)
* Make TaylorF2 actually work as a filter waveform (by adding length_in_time)
* Remove some duplicated end_frequency and time_lengths from waveform.py
Example of this running:
https://galahad.aei.mpg.de/~spxiwh/LVC/aLIGO/O1/analyses/zero_padding/chunk3/smallrun_test4/
> Plot waveform fixes

- bin/inference/pycbc_mcmc_table_summary
- pycbc/results/__init__.py
- pycbc/results/str_utils.py
This patch adds a module to pycbc/results that will format numbers with appropriate number of sig figs and, if desired, using scientific notation. The patch adds this to pycbc_mcmc_table_summary so that small values can be printed. Here is an example output before the patch:
https://www.atlas.aei.uni-hannover.de/~cdcapano/LSC/projects/pycbc_inference/ringdown/quick_run/ringdown_example-summary.html
Note that the amplitude column and some taus appear as 0. Here is after the patch:
https://www.atlas.aei.uni-hannover.de/~cdcapano/LSC/projects/pycbc_inference/ringdown/quick_run/ringdown_example-sigfigs.html
You can now see the amplitude and taus. This patch uses MathJax to display LaTeX in an html page.
Note: GPS times should be fully printed... this might require another command-line option …
> Add str_utils to results, and have mcmc table summary use

- bin/hwinj/pycbc_insert_frame_hwinj
Makes it so that any IFO name can be used. The IFO name is only used for naming the frame channel so there's no reason to restrict it to H1 and L1 only.
> Do not require H1 or L1 as IFO name in frame insertion script.

- bin/inference/pycbc_mcmc
- bin/inference/pycbc_mcmc_plot_corner
- bin/inference/pycbc_mcmc_table_summary
- pycbc/inference/sampler.py
- pycbc/io/mcmc.py
This PR:
* Saves number of burn in samples to MCMC file in attributes.
* ``MCMCFile.write`` now takes the sampler class and handles get all information from the sampler class.
* Default for ``thin_start`` set to ``None``. This will automatically choose to start plotting after the number of burn in samples.
> Save number of burn in samples in MCMC file and make default to not plot burn in samples

- bin/inference/pycbc_mcmc_plot_acceptance_rate
- bin/inference/pycbc_mcmc_plot_acf
- bin/inference/pycbc_mcmc_plot_samples
This PR:
* Adds ``--thin-start`` and ``--thin-interval`` to ``pycbc_mcmc_plot_acf``, ``pycbc_mcmc_plot_acceptance_rate``, and ``pycbc_mcmc_plot_samples``.
* Pass those command line arguments when reading samples from the ``MCMCFile``.
This will make it so these codes skip the burn in samples; the other MCMC plotting codes already have these options. Changing ``--thin-start`` tells the code to start reading samples at that iteration in the MCMC and ``--thin-interval`` says to take every i-th sample from the chain after ``--thin-start``. To read all samples, you use ``--thin-start 0 --thin-interval 1``.
> Add --thin-start and --thin-interval to MCMC plotting codes

- bin/inference/pycbc_mcmc_plot_acf
- bin/inference/pycbc_mcmc_plot_corner
- bin/inference/pycbc_mcmc_plot_samples
- bin/inference/pycbc_mcmc_table_summary
- pycbc/io/mcmc.py
Sets the default in MCMC plotting codes to plot all ``variables_args`` stored in the HDF input file.
Adds a function ``MCMCFile.read_variable_args`` to do this.
Now ``pycbc_mcmc_plot_samples``, ``pycbc_mcmc_plot_acf``, ``pycbc_mcmc_plot_corner``, and ``pycbc_mcmc_table_summary`` minimally need ``--input-file`` and ``--output-file`` to run.
Note that the other plotting executable ``pycbc_mcmc_plot_acceptance_rate`` does not use the ``variable_args`` attribute.
> Set default in MCMC plotting codes to plot all parameters

- bin/inference/pycbc_mcmc
- pycbc/inference/sampler.py
- pycbc/io/mcmc.py
This PR:
* ``pycbc_mcmc`` dumps the MCMC chain to the output file after a certain number of iterations. Number of iterations is given on the command line with ``--checkpoint-interval``. If ``--checkpoint-interval`` is not given, then it will write samples to file once its finished.
* Seperate out ``MCMCFile.write`` out into smaller functions that get called at different points in ``pycbc_mcmc``, eg. ``MCMCFile.write_psds``, ``MCMCFile.write_samples``, ``MCMC_write_sampler_attrs``, etc. Instead of one write function that handled all of these.
At line 243 of ``pycbc_mcmc`` it writes zeros of length ``--niterations`` to the output file as placeholder. Then as ``pycbc_mcmc`` runs, it fills in the chunks. In the ``MCMCFile.attrs`` it saves a ``niterations`` that is the number of iterations …
> Allow pycbc_mcmc to dump MCMC chain to output file after certain number of iterations

- pycbc/tmpltbank/bank_output_utils.py
The values should be of the form `process:process_id:0`, not `sngl_inspiral:process_id:0`. Perhaps a copy-paste error?
I noticed that pycbc coinc files that I have lying around had `sngl_inspiral` tables whose `process_id` columns have values like `sngl_inspiral:process_id:0`. All other coinc files that I have seen use the form `process:process_id:0` (so that they work as keys to the `process` table).
I'm not familiar enough with pycbc data flow to know where this gets set, but I found this likely typo by grepping through the source tree.
> Fix typo in sngl_inspiral process_id column

- bin/inference/pycbc_mcmc_plot_acf
- pycbc/filter/autocorrelation.py
This PR:
* Adds a ``pycbc.filter.autocorrelation`` module that has functions for calculating ACL/ACF.
ACL is the integrated ACL, ie.: 1 + 2 sum ACF(k)
Adds some extra features like in ``LALInferenceComputeMaxAutoCorrLen`` (https://github.com/lscsoft/lalsuite/blob/e79c77830cf04cb4957731654ad3123688636fe8/lalinference/src/LALInferenceProposal.c#L3740):
* A ``k`` parameter that tells calculation to not go past a certain index, useful for avoiding edge effects of ACF.
* A ``m`` parameter that sets a stopping condition.
Example is:
```
import numpy
from pycbc.filter.autocorrelation import calculate_acf, calculate_acl
data = numpy.array([numpy.random.uniform() for i in range(10000)])
for i in range(40,70,1):
data[i] += (i-40)
#for i in range(50,60,1):
#s = 2
#fs …
```
> Function to figure out ACL

- bin/inference/pycbc_inference
- bin/inference/pycbc_inference_plot_acceptance_rate
- bin/inference/pycbc_inference_plot_acf
- bin/inference/pycbc_inference_plot_posterior
- bin/inference/pycbc_inference_plot_prior
- bin/inference/pycbc_inference_plot_samples
- pycbc/frame.py
- pycbc/workflow/inference_followups.py
Fixes a copy-paste error in the shebang line.
Also fixes some typos in ``inference_followups`` and ``frame``.
Removes an old unused import in ``pycbc_inference``.
> Fix shebang line in inference excutables

- bin/inference/pycbc_inference
- pycbc/io/inference_hdf.py
Does as title says.
Also adds a commit to use the ``likelihood_evaluators`` dict in the module.
> Do not overwrite labels if calling ``InferenceFile.write_samples`` multiple times

- bin/inference/pycbc_make_inference_workflow
This PR:
* Makes it so the user can specify ``--statmap-file``, ``--single-detector-files``, and ``--bank-file`` or ``--ifos`` and ``--gps-end-time``.
* If the user doesn't give the workflow input file options,  then the coinc table is not added to the output HTML page.
Tested both possible command lines with scripts on sugar in: ``/home/cbiwer/projects/pycbc_mcmc_workflow_test/test8/run_pycbc_make_inference_workflow*.sh``
EDIT: Realized shortly afterwards that ``--ifos`` is completely unnecessary so I removed it. Please take a look now.
> Allow inference workflow generator to use command line to find analysis times

- bin/inference/pycbc_inference_plot_prior
- pycbc/io/inference_hdf.py
- pycbc/results/str_utils.py
This PR:
* Changes ``pycbc_inference_plot_prior``. Now it can plot more dimensions by using the ``corner.corner`` module. Each point is weight by the PDF.
* Moves LaTeX HTML function to ``str_utils``.
Example plot: https://sugar-jobs.phy.syr.edu/~cbiwer/tmp/tmp.png
Shows coalescence time and mass 2 as gaussian distributions. Mass 1 is a uniform distribution.
> Allow pycbc_inference_plot_prior to work for more dimensions

- pycbc/__init__.py
- pycbc/scheme.py
The PyCBC ``__init__`` module calls ``nvidia-smi`` to see if the CUDA driver is installed. This can take a long time to return on large GPU machines, and so I replaced it with a call to ``lsmod`` to directly check for the driver.
The second patch changes the default mode from ``SCHED_YIELD`` to ``SCHED_BLOCKING_SYNC`` which should decrease CPU load and increase speed on large GPU systems. @soumide1102 is testing this.
> Increase speed of GPU code

- bin/inference/pycbc_inference
- bin/inference/pycbc_inference_plot_acf
- bin/inference/pycbc_inference_plot_posterior
- bin/inference/pycbc_inference_plot_samples
- bin/inference/pycbc_inference_table_summary
- pycbc/filter/autocorrelation.py
- pycbc/io/inference_hdf.py
This PR:
* Calculates the maximum ACL at the end of ``pycbc_inference`` and stores it as ``InferenceFile.acl``.
* Changes ``InferenceFile.read_samples_from_walker`` so that default interval to use for thinning is the ACL. This means all plotting code will default to using the ACL. Can use ``--thin-interval 1`` on plotting executables to plot all samples.
* If the input data to ``calculate_acl`` has a variance of 0, it will return ``numpy.inf``.
* Makes class attributes for things in ``InferenceFile.attrs``.
> Calculate ACL at end of pycbc_inference and store it in InferenceFile

- bin/inference/pycbc_inference_plot_prior
- bin/inference/pycbc_make_inference_workflow
- pycbc/results/str_utils.py
- pycbc/workflow/inference_followups.py
This PR:
* Adds ``pycbc_inference_plot_prior`` to inference workflow.
* Rename posterior workflow helper function in ``pycbc.workflow.inference_followups`` since now there's more than one executables that makes a corner plot.
* Can specify a list of sections to plot with ``pycbc_inference_plot_prior`` using ``--sections`` now.
Prior files appear in the "Additional Files" section of the HTML by design. I don't think that we need to put them in the well. They'll be one plot for each seperate distribution listed in the configuration file.
An example page is here: https://sugar-jobs.phy.syr.edu/~cbiwer/tmp/tmp_workflow_9/
> Add prior plots to workflow

- bin/inference/pycbc_inference_plot_acceptance_rate
- bin/inference/pycbc_inference_plot_acf
- bin/inference/pycbc_inference_plot_posterior
- bin/inference/pycbc_inference_plot_samples
Sets the inference plotting executables ``--thin-interval`` default to ``None`` so that changes from #926 to use ``InferenceFile.acl`` as default will be used. Right now its set the default is set to 1 which means plot every sample.
> Change --thin-interval defaults to None in inference plotting executables

- pycbc/workflow/jobsetup.py
Rework how the analysis segment lengths are calculated. This adds a min-analysis-length to go along with min-analysis-segments, to supply a definitive minimum (or maximum) data length to allow the job to use.
Alex points out that this should probably be sanity checked against the options being send to pycbc_inspiral to check that the minimum length is valid (or even calculate the length directly from the options).
> Rework analysis-segments lengths

- bin/inference/pycbc_inference
The checkpoint addition to pycbc_inference caused it to not write the burn-in points to the output hdf files. This means that when plots/summary are created, valid points are being skipped since by default, thin_start is set to skip the number of burn in iterations. This patch fixes this by adding the burn-in back to the output.
> Add burn in points back to output files

- pycbc/io/record.py
- pycbc/waveform/__init__.py
- pycbc/waveform/bank.py
- pycbc/waveform/parameters.py
- pycbc/waveform/waveform.py
This adds a base class _FieldArrayWithDefaults and WaveformArray to record.py. WaveformArray is an instance of FieldArray with some common default fields and methods defined. A subset of these fields can be set up on initialization using the names keyword argument. The names can include default fields, virtual fields, methods, and/or functions of these. If a virtual field or method is included in the names, the underlying source code is analyzed so that all the necessary fields are included for the virtual field or method to work. See the doc string for WaveformArray for examples.
I intend to use this in the inference plotting codes, to make plotting different parameters easier. (Pull request to follow this one.)
> Add FieldArrayWithDefaults and WaveformArray to record.py

- bin/inference/pycbc_inference_plot_acf
- bin/inference/pycbc_inference_plot_acl
- bin/inference/pycbc_inference_plot_posterior
- bin/inference/pycbc_inference_plot_samples
- bin/inference/pycbc_inference_table_summary
- pycbc/inference/option_utils.py
- pycbc/io/inference_hdf.py
These patches update `io/inference_hdf.py` so that it loads samples as instances of `WaveformArray`. This makes it easy to plot/summarize functions of the variable args, along with derived parameters of the variable, such as chirp mass. It also makes use of the new parameters module, so automatically get labels of unrecognized parameters. This change to `inference_hdf` necessitates updates to the programs that load the samples. Since these programs make use of some common command line options --- namely, `input-file, `parameters` (which replaces the old `variable-args`), `thin-start`, and `thin-interval` --- I also created an `option_utils` module in inference that stores and loads these options.
As before, you need only provide an input-file and an output-file to plot the basic …
> Inference with WaveformArray

- bin/inference/pycbc_inference
In PR #938 I thought the burn-in points were not being included in the sample points, because the length of the sample chains in the output file was the same as the number of iterations (instead of niterations + number of burn in). However, it turns out the burn-in points were included; it was the last points of the chain that was not being included. That patch also introduced a bug that causes inference to fail when using checkpointing.
This patch fixes this by writing an empty array equal to the size of the niterations + burn in right after the burnin, along with the burn-in points.
This patch also fixes a bug introduced in #940. Currently the code crashes when trying to write the acl at the end.
Finally, this adds a patch that will cause the code to try to find a label in …
> Fix couple of bugs in inference

- bin/inference/pycbc_inference_table_summary
This patch tries to make the display of GPS times more legible in table summary. This is done by in two ways. First, the number of sig. figs to show is now based on the range in quantiles, rather than always just show 1/100th each value (although, if only one quantile is requested, it will default to 1/100). Second, for values > 1, scientific notation is only used if the value is > 1e10.
> Fix display of GPS times in table summary

- bin/inference/pycbc_inference
- pycbc/io/inference_hdf.py
As title says. Moves the bit added to ``pycbc_inference`` to ``read_label_from_config`` which means ``wfparams`` will also be picked up for the prior plotting executables.
> Use read_label_from_config in pycbc_inference

- pycbc/strain.py
In some cases it is useful to produce "fake-strain" with no noise at all. For example testing pycbc_inspiral, or for generating zero-noise frame files of injections to be used in lalinference.
This patch is being used to generate frame files for this purpose, so it would be good to get this on master soon.
> Zero noise

- bin/inference/pycbc_inference_plot_samples
- pycbc/inference/option_utils.py
- pycbc/io/inference_hdf.py
Adds a ``--thin-end`` option which defaults to using ``InferenceFile.nierations``.
This is convenient if you're running a long run and want to plot the results while its running. Without this you would get a large number of samples at position (0,0,0,...).
It includes #951. So once that's merged I imagine this will need to be rebased.
EDIT: Also giving ``--thin-start 0 --thin-interval 1 --thin-end -1`` plots all samples in the file.
> Adds a --thin-end option

- bin/inference/pycbc_inference_plot_posterior
Adds median and lower+upper quantiles text in posterior plots above 1-D histograms.
Example: https://sugar-jobs.phy.syr.edu/~cbiwer/tmp/pr_posterior.png
> Add quantitles text as option for posterior plot.

- pycbc/inference/prior.py
This adds priors `UniformAngle`, `SinAngle`, `CosAngle`, `UniformSolidAngle`, and `UniformSky` to `inference/prior`. These allow for appropriate sky-loctation priors, and also make it easier to specify angular priors in config files. The priors are:
- `UniformAngle`: same as `Uniform`, but bounds are limited to `[0,2*pi)`. When initializing, you specify the bounds as factors of pi, rather than radians. If no bounds are specified will default to `[0,2*pi)`.
- `SinAngle`: similar to UniformAngle, but points are sine distributed between 0 and pi; see the doc string for math.
- `CosAngle`: same as `SinAngle`, but points are sine distributed between `-pi/2` and `pi/2` (which is equivalent to being cosine distributed between `[0,pi)`).
- `UniformSolidAngle`: creates a prior that is uniform in …
> Add priors for anglular parameters

- bin/pycbc_make_sngl_workflow
- pycbc/workflow/jobsetup.py
- pycbc/workflow/pegasus_workflow.py
- pycbc/workflow/segment.py
I'm starting to move over the template bank generators over to PyCBC workflow and change Tito's .sh script into one uber-workflow (with some changes to sBank and the geom bank to be discussed).
First step is some prep. work. Firstly the LigolwaddExecutable is old and should not use different options to `__init__` than the standard ones (specifically ifo is now ifos).
Also I found a bug in pegasus_workflow. If one supplies:
```
node.add_opt('--some-integer', 0)
```
it will translate it to
```
--some-integer
```
because 0 will fail the "is true" test. Fix is to test for "is option not None".
> Minor fixes in prep. for larger tmpltbank changes

- pycbc/waveform/waveform.py
The SEOBNR final frequency function doesn't seem to work properly. For some waveforms it seems to end far earlier than the model naturally does, and causes truncation within the ligo band of the waveform. This truncation causes the background to increase significantly. 
(current master)
https://www.atlas.aei.uni-hannover.de/~ahnitz/LSC/ahnitz/projects/dynamic_flow/analysis3/output/local-site-scratch/html/H1L1-PLOT_SNRIFAR_FULL_DATA_FULL_CUMULATIVE_CAT_12H_FULL_DATA_FULL_BIN_2_CLOSED-1128299417-1083600.png
(patch)
https://www.atlas.aei.uni-hannover.de/~ahnitz/LSC/ahnitz/projects/dynamic_flow/revert2/output/local-site-scratch/work/main_ID0000001/H1L1-PLOT_SNRIFAR_FULL_DATA_FULL_CUMULATIVE_CAT_12H_FULL_DATA_FULL_BIN_2_CLOSED-1128299417-1083600.png
For now, the only solution I have is to …
> comment out seobnr final frequency

- pycbc/waveform/waveform.py
The get_two_pol_waveform_filter can in some cases return a waveform with a different precision to that specified in the output vectors. This is fixed by doing the same thing as in the single-polarization get_waveform_filter function.
> Ensure correct precision of output in get_two_pol_waveform_filter

- docs/workflow.rst
- docs/workflow/initialization.rst
- pycbc/workflow/configuration.py
- pycbc/workflow/core.py
- pycbc/workflow/pegasus_workflow.py
In preparation for moving the template bank generation codes to using pycbc.workflow I want to add some features to the workflow module. Some of these are things we've discussed previously, but some things are new. I think I can summarize the changes into 3 points:
* Support for tag-subsections. Ie. you can now supply `[inspiral-h1-bnsinj]` (or `[inspiral-bnsinj-h1]`) to give options only to jobs with the bnsinj *and* h1 tags. This should work for any number of tags, but duplication is still forbidden (so a value in `[inspiral-h1-bnsinj]` does *not* override a value in `[inspiral]`. If an option is present in both--or if an option is present twice in *any* set of subsections a code reads from--the code will fail. Therefore it is better not to nest these too deep!).
* Support for options …
> Add features to PyCBC's workflow module

- bin/inference/pycbc_inference_plot_acf
- bin/inference/pycbc_inference_plot_posterior
- bin/inference/pycbc_inference_plot_prior
- bin/inference/pycbc_inference_plot_samples
- bin/inference/pycbc_inference_table_summary
- pycbc/io/inference_hdf.py
- pycbc/results/str_utils.py
This patch removes the `latex_to_html` function in the inference plotting programs. The intent is to just use the MathJax CDN. This patch also fixes a bug in format_value that prevented it from printing negative values. Example output of a test run is here:
https://www.atlas.aei.uni-hannover.de/~cdcapano/LSC/projects/pycbc_inference/cbc/variable_angles/summary-all_ti800.html
> Remove latex_to_html function

- docs/workflow/pycbc_make_inference_workflow.rst
- pycbc/inference/prior.py
This patch changes how bounds are specified in config files for distributions that inherit from `_BoundedDist` (namely, `Uniform` and `UniformAngle`). Instead of specifying separate `min-{param}` and `max-{param}` lines, the parameter is just set equal to a comma separated value. For example,
```
[prior-mass1]
name = uniform
min-mass1 = 10.
max-mass1 = 80.
```
becomes:
```
[prior-mass1]
name = uniform
mass1 = 10., 80.
```
The `tag` argument in `from_config` is renamed to `variable_args`, to make it explicit that this needs to list the variable args.
The doc file is also updated. The variables `ra`, `dec`, and `polarization` are also changed to variable args in the documentation to show how to specify uniform sky locations and how to use `uniform_angle`.
Note: for the Gaussian prior, …
> Specify min/max as comma separated values in config file

- pycbc/workflow/__init__.py
Currently the PyCBC workflow module is broken.
The issue is that the timeslides module is removed but `__init__.py` still tries to import it.
Now this *should* have been caught by sanity checks, but there is currently a hack in the workflow module's init file to allow it to run inference stuff without pegasus present. Can/should the hack be removed?
> Fix broken workflow module

- pycbc/types/frequencyseries.py
- pycbc/types/timeseries.py
So I was using ``TimeSeries.to_frequencyseries`` and ``FrequencySeries.to_timeseries`` and it wasn't working for a time series of length 100000 and ``delta_t`` set to 1, eg.:
```
import numpy
from pycbc.types.timeseries import TimeSeries
ts = TimeSeries(numpy.random.random(100000), delta_t=1.0)
ts.to_frequencyseries()
```
Gives the sort of nonsensical error:
```
ValueError: The value of delta_f (1e-05) would be undersampled. Maximum delta_f is 1e-05.
```
A bit of debugging shows:
```
tlen  = int(1.0 / self.delta_f / delta_t)
```
Is rounding down so ``tlen`` is set incorrectly to 99999 instead of 100000. I imagine this just from the arithmetic. Since:
```
In [1]: 1.0 / (1.0/100000) / 1.0
Out[1]: 99999.999999999985
```
This PR changes setting ``tlen`` so if you don't supply a ``delta_t`` …
> Skip division when calculating tlen in to_frequencyseries and to_timeseries

- bin/inference/pycbc_inference
This PR adds ``--psd-start-time`` and ``--psd-end-time`` options to ``pycbc_inference``. If these options are used then these will replace ``--gps-start-time`` and ``--gps-end-time`` for estimating the PSD.
> Allow pycbc_inference to use different start and end time for PSD estimation

- bin/inference/pycbc_inference
- pycbc/waveform/generator.py
- pycbc/waveform/ringdown.py
- pycbc/waveform/waveform.py
**Wait for Request #4430 in LALSimulation**
This adds the functions `get_td/fd_lm` to generate one lm ringdown with n overtones, and `get_td/fd_lm_allmodes` to generate a multi-mode ringdown with all the lmn selected, based on the modes available in SEOBNRv2. To compute the higher modes it requires the function `XLALSimIMREOBGenerateQNMFreqV2fromFinal` in LALSimulation, which has been added and is in progress of being reviewed and merged. 
The way of dealing with the input parameters has also been re-organized.
Also, in waveform.py, split the function `props` into two functions: `get_obj_attrs` to read the template object, and `props` to combine that with the rest of arguments. This way, `get_obj_attrs` can be called from the ringdown module without interfering with the default arguments.
> Add multimode ringdown approximants to ringdown module

- bin/inference/pycbc_inference_plot_acl
- pycbc/filter/autocorrelation.py
On hold because it depends on #966. It will most likely need to be rebased when #966 is merged.
So this PR:
* Moves ``*=2`` multiplication out of loop in ``calculate_acl`` and only have one logical statement in the loop.
* Adds ``unbiased`` option so that you can choose either ``n-k`` or ``n`` normalization for the autocovariance function. Default is to normalize by ``n`` which doesn't need to compute the variance, this makes ``calculate_acf`` significantly faster (maybe this was the point of confusion before?).
Tested it out here: https://sugar-jobs.phy.syr.edu/~cbiwer/tmp/tmp_acl.png
On a single parameter with 100000 iterations and 500 walkers, it calculated the ACLs in about 55 seconds:
```
2016-07-07 16:30:05,442 : Calculating autocorrelation length
2016-07-07 16:31:00,908 : Plotting …
```
> Use different normalization when calculating ACL

- bin/pycbc_aligned_bank_cat
- bin/pycbc_geom_aligned_2dstack
- bin/pycbc_geom_aligned_bank
This patch updates pycbc_geom_aligned_bank to generate a workflow using pycbc.workflow.
Currently this code builds a glue workflow internally given command line argument to pycbc_geom_aligned_bank. I decided to preserve this behaviour in this case, although it's a little weird. This at least means that no changes are needed when running this code. One just submits with pycbc_submit_dax and not condor_submit_dag.
I've also preserved the old code in case anyone cannot figure out pegasus. I'm not sure whether this is the right thing to do and this can be removed if desired.
> Move geom-bank over to PyCBC workflow

- bin/workflows/pycbc_create_sbank_workflow
- setup.py
This is the new PyCBC workflow generator code to allow one to generate "sbank" workflows. Note that with recent changes to sbank this workflow is a little different in structure to the existing one. The basic idea of this is to avoid the issue where sbank is run highly parallelized and ends up double covering everywhere, and also to avoid the issue where sbank can get "stuck" if one job starts to take forever. I'm going to try and assign this to Steve P to look over. An example of it running can be found in vulcan under:
/home/spxiwh/aLIGO/O2/template_banks/test_new_gener/sbank_only
> Create PyCBC sbank workflow generator

- pycbc/inference/prior.py
- pycbc/io/inference_hdf.py
- pycbc/results/render.py
- pycbc/sensitivity.py
- pycbc/strain.py
- pycbc/tmpltbank/option_utils.py
- pycbc/types/frequencyseries.py
- pycbc/types/timeseries.py
- pycbc/workflow/datafind.py
- pycbc/workflow/inference_followups.py
- test/test_frequencyseries.py
- test/test_timeseries.py
This pull request automatically fixes all occurrences of the following issue:
Issue type: [Use `is` or `is not` to compare with `None`](https://www.quantifiedcode.com/app/issue_class/3IY8CZ0v)
Issue details: [https://www.quantifiedcode.com/app/project/gh:ligo-cbc:pycbc?groups=code_patterns/%3A3IY8CZ0v](https://www.quantifiedcode.com/app/project/gh:ligo-cbc:pycbc?groups=code_patterns/%3A3IY8CZ0v)
To adjust the commit message or the actual code changes, just [rebase](https://git-scm.com/docs/git-rebase) or [cherry-pick](https://git-scm.com/docs/git-cherry-pick) the commits.
For questions or feedback reach out to cody@quantifiedcode.com.
Legal note: We won't claim any copyrights on the code changes.
Cheers,
[Cody - Your code quality bot](https://www.quantifiedcode.com/cody)
> Fix "Use `is` or `is not` to compare with `None`" issue

- docs/index.rst
- docs/inference.rst
Adds a docs page for the inference modules. There's the example BBH software injection from Collin as an example on how to run ``pycbc_inference``. With a bit about the output file.
Example of rendered page is here: https://sugar-jobs.phy.syr.edu/~cbiwer/_build/html/inference.html
> Add inference docs page.

- bin/minifollowups/pycbc_foreground_minifollowup
- bin/minifollowups/pycbc_injection_minifollowup
- bin/minifollowups/pycbc_sngl_minifollowup
since non-precessing runs don't need info about extra precessing fields, don't require it
> making minifollowup jobs precession-proof

- bin/pycbc_aligned_bank_cat
- bin/pycbc_geom_aligned_2dstack
- bin/pycbc_geom_aligned_bank
- pycbc/tmpltbank/coord_utils.py
This change is in preparation for forthcoming changes to add a make_uberbank_workflow. There are two parts of this:
* We move all the temporary text files produced by geom_bank to a single HDF file. This greatly simplifies file management and makes it easier to extract information from the output.
* A number of operations in coord_utils are now done using numpy.dot instead of for loops. Originally these were not a problem because long numpy arrays would be used and the for loop was not a slow down. However, we then moved to using smaller arrays in some parts and I didn't check that this had become a problem. This produces close to an order of magnitude speed up for the 2dstack jobs in the example I am testing on.
> Geom_bank updates

- pycbc/__init__.py
- pycbc/weave.py
This should fix a really annoying longstanding issue with using PyCBC within multiprocessing or even multiple programs on the same machine. If you had the same code being compiled at the same time, the code cache could be corrupted. This adds a file lock to the code compile functionality by monkey-patching scipy.weave.
> add file locking to weave to avoid multiprocessing headaches

- pycbc/waveform/waveform.py
Switches from SEOBNRv2 chirp time to the new SimIMRPhenomDChirpTime for IMRPhenomD and IMRPhenomPv2 approximants.
I also noticed that SpinTaylorF2 was using the SEOBNRv2 chirp time and I switched that to the regular SPA chirp time. Ian, I suspect this may be related to your precessing bank study, so please let me know if I should revert this. If there's a reason to use SEOBNRv2 chirp time for STF2, let's add a clear comment there.
> Changes to chirp time functions in waveform module

- bin/pycbc_geom_aligned_bank
- bin/pycbc_submit_dax
- bin/workflows/pycbc_create_sbank_workflow
- bin/workflows/pycbc_create_uberbank_workflow
- pycbc/workflow/core.py
- setup.py
Hi all,
This is the rest of the changes to implement an uberbank workflow in pegasus. To summarize: This, coupled with #986 #976 and #973, implements the following changes:
GEOM BANK
* The geometric bank workflow is moved over from glue.pipeline to pycbc.workflow. (#973)
* The geometric bank workflow is edited to use HDF files (and many less files) for internal data products (output is still XML in standard format) (#986)
* The geometric bank codes are optimized with some numpy-isation (#986)
* Support for running the geom bank as a sub-workflow is added (here)
* The general structure of the geom_bank workflow, and scientific input choices, are unchanged. One should still be able to reproduce previous output with the new code.
SBANK
* A new sbank workflow generator is created using …
> Uberbank workflow

- bin/hdfcoinc/pycbc_page_sensitivity
- pycbc/sensitivity.py
When plotting distance on the y-axis, and the error is larger than the estimate, you get nan's in the error array and the error interval disappears. This patch catches those cases and makes the error as large as possible while remaining physically meaningful. See [before](https://www.atlas.aei.uni-hannover.de/~juan.bustillo/LSC/o1/imbh/injection_runs/o1-imbh-chunk123-c02-phenomd_50_300_R_HM/H1L1-PLOT_SENSITIVITY_SUMMARY_MTOTAL_ALLINJ-1126051217-3331800.png) and [after](https://www.atlas.aei.uni-hannover.de/~tito/LSC/o1/imbh/juans_allinj_debug.png).
The patch also includes a couple fixes to `--help` and removes an unused calculation.
> Fix glitch in sensitivity plots with huge errorbar

- bin/inference/pycbc_inference
Currently, pycbc_inference reads the static_args from the configuration file and either converts them to floats or leaves them as strings. However, the ringdown approximant with higher modes expects a list of strings as argument for the number of modes desired. This patch adds the option (in pycbc_inference) to check if one of the strings in the static_args is a list and converts it to a list of strings.
> Allow pycbc_inference to take a list from config file and keep it as a list

- bin/pycbc_compress_bank
- pycbc/waveform/bank.py
- pycbc/waveform/compress.py
- pycbc/waveform/utils.py
- setup.py
This patch adds `pycbc_compress_bank`, as well as updates some things in the compress module. This is an update from PR #882. In addition to the changes in that PR, this one introduces a precision argument. When compressing the bank, you now provide a desired precision. In the compress function, the code will use the sample points to do an initial compression. It then checks that 1-overlap of the decompressed waveform is less than the desired precision. If not, it will add points, one at a time, until the condition is met. Note that when this is done, no PSD is used; however, for sufficiently small precision (I used 0.001 here), this shouldn't matter.
I've tested this on the first 100 templates in the O1 bank, by running an independent script that loads the compressed waveforms from disk, …
> Add bank compression executable

- pycbc/filter/matchedfilter.py
- pycbc/types/array.py
Reorganize the matched filter live class to calculate signal based vetos *after* the triggers are recorded from the entire bank (or rather from a single MPI process). This limits the number of points to calculate drastically when coupled with an option to only record the loudest X triggers.
> updated matched filter class

- bin/pycbc_compress_bank
- pycbc/waveform/compress.py
This patch adds a `CompressedWaveform` class to `compress.py` to store the information needed to decompress the waveform, and methods to read/write compressed waveforms to an hdf file. The patch also adds more documentation to the methods in `compress.py`.
> Add CompressedWaveform class

- pycbc/weave.py
At least with the PyInstaller (v.2.1) directory bundles that are built for Einstein@Home the compilation locking doesn't work, as the path that gets passed as _module_dir_ doesn't exist in the bundle.
I suspect that the same will happen with other PyCBC PyInstaller bundles built with the same version of PyInstaller.
The attached patch fixes this by creating the missing directories. (it also augments the introductory log message to include the actual path).
> Workround for locking problem with PyInstaller (directory) bundles

- bin/inference/pycbc_inference_plot_posterior
The module corner doesn't have ```matplotlib.use('Agg')```.
Therefore pycbc_inference_plot_posterior fails when being run in a cluster because the corner module is imported before matplotlib.
Importing corner after the ```.use('Agg')``` and pyplot fixes this error.
> Import corner after pyplot

- pycbc/io/inference_hdf.py
In my last run of pycbc_inference, I got an error when running pycbc_inference_plot_posterior because the thin-interval was a float instead of an integer. This patch defines the thin-interval as an integer to be able to plot the posterior.
> Force the thin interval to be an integer

- bin/pycbc_compress_bank
- pycbc/waveform/compress.py
- pycbc/waveform/utils.py
This patch allows the bank compress code to store and decompress waveforms using single precision. Concurrently, what previously was referred to as "precision" (the minimum mismatch allowed between compressed waveforms and their full counterparts) has been renamed to "tolerance".
This patch also speeds up the decompression C code using the trick of computing the output waveform based on what the last step was, similar to what is done in `apply_fd_time_shift`. On my laptop it takes 1-2ms to decompress waveforms to a frequency resolution of 1/256.
I tested the mismatch with both the single and double precision on the first 100 templates in the O1 bank. Results look good; here is the single precision test:
https://www.atlas.aei.uni-hannover.de/~cdcapano/LSC/projects/bank_compression/class_tes …
> Allow compression to use single precision and speed up decompression code

- bin/inference/pycbc_inference
- pycbc/inference/sampler.py
This patch does two things:
1. Sometimes, for as yet still unclear reasons, kombine can return "blob" as a fourth argument after burn in. This causes the sampler wrapping in pycbc/inference/sampler.py to crash. This fixes this by checking for the number of arguments returned, discarding the blob if it was returned.
2. Adds a seed argument to `pycbc_inference`. This makes the start positions of the walkers reproducible from run-to-run.
> Add seed to inference and catch blob

- bin/pycbc_ringinj
- pycbc/inject.py
- pycbc/strain.py
- pycbc/waveform/ringdown.py
- setup.py
Currently most of my ringdown parameter estimation runs are not reproducible because I had to hack pycbc_inference to perform ringdown injections. This script is a ringdown version of lalapps_inspinj, and the first step to make ringdown injections compatible with the master version of pycbc_inference. 
pycbc_ringinj takes the parameters of the injection as input, checks that all the required arguments are there (which are approximant dependent) and writes an hdf5 file with the parameters of the injection.
When this script is reviewed and merged, I will make the necessary changes in inject.py and strain.py to read this kind of files.
> Script to create ringdown injections

- bin/pycbc_inspiral
- pycbc/events/events.py
- pycbc/inject.py
- pycbc/strain.py
Return the minimal version of injections set when you apply injections. This fixes a bug that was introduced by the template thinning into the single template code (as it was expecting a different object).
> fix the injection thinning

- tools/static/runtime-tkinter.py
Some (recent) PyCBC requirement apparently pulls in tkinter, which fails when the "TCL directory" and "TK directory" don't exist. I don't know which these refer to in normal runs; in PyInstaller bundles these are directories "tcl" and "tk" below the "bundle" directory. The proposed patch adds a PyInstaller runtime-hook that creates these directories if needed, to avoid such failure of "bundled" applications.
> added PyInstaller runtime-hook to crate tcl&tk directories for tkinter

- bin/pycbc_ringinj
- pycbc/waveform/generator.py
- pycbc/waveform/ringdown.py
Currently the final mass and the final spin are 'Mfinal' and 'Sfinal' in the ringdown module. This is an issue for pycbc_inference because when reading the ini file it converts those names to 'mfinal' and 'sfinal', not finding therefore the priors for 'Mfinal' and 'Sfinal'.
This PR changes the names of the parameters to 'mtotal_f' and 's_f', following the convention that there should be no capital letters.
> Change name of parameters Mfinal and Sfinal in ringdown

- bin/hdfcoinc/pycbc_plot_singles_timefreq
- bin/plotting/pycbc_plot_waveform
- bin/pycbc_compress_bank
- bin/pycbc_inspiral
- bin/pycbc_inspiral_skymax
- bin/pycbc_multi_inspiral
- bin/pycbc_single_template
- pycbc/io/record.py
- pycbc/waveform/bank.py
This patch makes some changes to the way the `TemplateBank` class loads and stores triggers. The most notable thing is that approximant parsing has changed. The patch does away with the parse_option; instead, the eval features built into FieldArray's `__getitem__` are used. This allows for more complicated compound experessions to be used (in case we end up using more than two approximants), and for a cleaner, more user-friendly syntax on the command line. The details:
Currently, the table attribute of `TemplateBank` stores the parameters of the templates as a `FieldArray`. FieldArrays allow numpy functions on fields in the array to be passed as indices, as if those functions were a field. For example, if you have a field array `foo` with two fields, `mass1` and `mass2`, then …
> Change TemplateBank's approximant parsing, save approximants to file, and add support for compressed waveforms.

- bin/hdfcoinc/pycbc_coinc_bank2hdf
- bin/pycbc_compress_bank
- pycbc/io/record.py
- pycbc/waveform/bank.py
This patch updates `pycbc_coinc_bank2hdf` and `pycbc_compress_bank` to make use of `TemplateBank`'s new `write_to_hdf` function. 
`bank2hdf` has also been changed so that it makes use of `TemplateBank`'s new ability to only load specific parameters. Rather than hard code specific columns and parameter names, the list of columns to load from the xml file and what to call them in the output hdf file is now a command line option. There is a default list provided, currently set to mass1, mass2, spin(1|2)(x|y|z), and inclination. This means fewer/more parameters can be added in a workflow just using the ini file.
There is one minor change to `TemplateBank.write_to_hdf` so that it returns the file handler to the hdf file it wrote to; `compress_bank` makes use of this for writing compressed …
> Update bank2hdf, compress bank to use new write hdf function

- test/test_frame.py
- test/test_injection.py
- tools/run_travis.sh
Frame test works on my laptop. In inj test, LALSimulation was whining about the missing order string and the peak time tolerance was a bit tight (unless TaylorT4 has a new bug). Let's see if we can enable those tests safely on Travis.
> Fix & enable unit tests for injection and frame

- bin/inference/pycbc_inference
- pycbc/inference/sampler.py
- setup.py
This patch adds emcee's EnsembleSampler to the list of possible samplers in pycbc inference. Since emcee has no burn-in feature, `pycbc_inference` must be run with `--skip-burn-in` if using emcee. This patch also adds `emcee` to the list of required packages in `setup.py`. I tested this on my laptop with 4 processes and it seems to work well.
> Add emcee as a possible sampler to pycbc inference

- pycbc/io/record.py
This fixes a bug I introduced in #1032 when loading a field array from a ligolw table.
> Fix bug introduced in PR#1032

- bin/pycbc_submit_dax
- pycbc/workflow/pegasus_files/local-site-template.xml
This fixes the perl-ing problem for running PyCBC on OSG, but it may not work for running PyCBC on non-OSG.
Returns error:
```
`steven.reyes@sugar-dev3:aug19TestNoOSG$ ./submit.sh 
Enter your LIGO.ORG username in (e.g. albert.einstein): steven.reyes
Your identity: steven.reyes@LIGO.ORG
Enter pass phrase for this identity:
Creating proxy .................................... Done
Your proxy is valid until: Aug 22 19:54:11 2016 GMT
Attempt to use a remote site but --remote-staging-server not specified
```
Solution may be as simple as passing a remote-staging-server in pycbc_submit_dax, will conduct additional tests.
> Change URL so that the OSG workflows can copy files properly.

- pycbc/tmpltbank/lattice_utils.py
Karl recently updated the lalpulsar lattice tiling API and this is the corresponding PyCBC change. Tested with recent LAL, Travis will take care of the old one.
> Update An* lattice code for recent lalpulsar

- pycbc/workflow/pegasus_files/pegasus-properties.conf
Addressing open issue #874, Pegasus replica selector should just select by URI not URL. This should tell pegasus to try using these different URI's rather than a very particular URL.
> Pegasus Replica Selector URL to URI

- pycbc/inference/likelihood.py
This patch clears up some terminology in the Likelihood evaluators by adding some more descriptive doc strings. In the process, I've added a few different possible functions that the evaluators can return: `logposterior`,  `logplr`, `loglr`, `loglikelihood`, and `snr`. See the updated docstring for descriptions of each of these.
Concurrently, I now have GaussianLikelihood return `logplr` by default, since I realized it is a simpler term than the `logposterior`. Namely, I found that the `<d|d>` term could be quite large compared to the variation of the other terms (which are the only ones that change) when doing ringdown PE. I was worried that this might cause numerical overflow problems for MCMCs. In any event, this can be adjusted by changing the `__call__` function.
> Have GaussianLikelihood return prior weighted likelihood ratio by default.

- bin/hdfcoinc/pycbc_page_injtable
This small change adds the [:] command to the trigger ids in pycbc_page_injtable to ensure that the ids dictionary is populated with numpy arrays of integers. This matches what is done elsewhere, but I don't understand why sometimes this is necessary and sometimes it is not. I also feel we might be wasting RAM by doing this.
This is tested and works.
> Fix index issue with pycbc_page_injtable

- bin/hdfcoinc/pycbc_coinc_mergetrigs
- bin/hdfcoinc/pycbc_make_coinc_search_workflow
- bin/hdfcoinc/pycbc_plot_throughput
- bin/pycbc_inspiral
- pycbc/events/events.py
- pycbc/waveform/spa_tmplt.py
- pycbc/workflow/plotting.py
- setup.py
This pull request adds the ability to measure throughput as templates per core to `pycbc_inspiral` jobs in the coinc search workflow and histogram those throughputs in the results pages.
If the option `plot-throughput` is given in the section `workflow-matchedfilter` of the configuration file, then the sub-section `Throughput` will be added to the `Workflow` section of the results page, and will contain histograms of the templates per core for the full data and each injection run. A sample output may be seen [here](https://www.atlas.aei.uni-hannover.de/~hannah.hamilton/LSC/dev/o2/o1_analysis8/throughput_test_real/8._workflow/8.01_throughput/).
If re-analyzing earlier data before this capability was added, then the `plot-throughput` option should be omitted, or the workflow will break. An …
> Add plot throughput in coinc workflow

- bin/hdfcoinc/pycbc_plot_psd_file
With changes to PSD estimation there are now *more* PSD files being passed through the coinc_workflow and psd workflows. This means that memory usage of plot_psd_file can become problematic if estimating PSDs over long periods (e.g. the O1 duration).
This patch limits memory usage by slicing the PSDs when calculate medians and percentiles so the entire set of PSDs is never in memory. This doesn't seem to slow down runtime noticeably in tests and one can compare output plots from before:
https://galahad.aei.mpg.de/~spxiwh/LVC/aLIGO/plot_spec_patch/H1L1-PLOT_SPECTRUM-1126051217-3331800.png
and after:
https://galahad.aei.mpg.de/~spxiwh/LVC/aLIGO/plot_spec_patch/H1L1-PLOT_SPECTRUM_T-1126051217-3331800.png
this patch. Also the output when running the code with a high memory usage specified, …
> Limit memory footprint of plot_psd_file

- bin/inference/pycbc_inference
- pycbc/inference/option_utils.py
- pycbc/inference/sampler.py
- pycbc/io/inference_hdf.py
- pycbc/io/record.py
This patch moves the read/write samples to methods defined for the individual samplers. The read method in InferenceFile is now just a thin wrapper that calls the appropriate sampler's read function. This is to make it easier to add new samplers which may not have a similar structure as the current two MCMC samplers. For instance, I will be adding emcee's parallel tempered samplers (patch coming soon), which needs to be able to store temperature chains for each walker. Also, if anyone adds a nested sampling routine, I'm not sure they have a concept of walkers.
This results in a slight reorganization of the output in the hdf file; now, the sample chains and log posteriors are written to a `samples` group; acceptance fraction still lives in the top level.
I've also added the ability to have …
> Reorganize read/write samples

- install_pycbc.sh
- tools/static/build_dag.sh
@duncan-brown  I updated this PR so that it does the following edits in install_pycbc.sh and build_dag.sh
In install_pycbc.sh:
*  Removed MySQL-python and psycopg2 from the requirements.txt used because the script was unable to build them (when tested on sugar-test1) . Larne thinks we might not need MySQL-python anywhere. Not sure about where psycopg2
*  Added extra options --hidden-import M2Crypto --hidden-import cjson --hidden-import Cookie when pyinstaller builds ligolw bundles. ( Issue #1046 )
*  Added a prompt to ask users if they are ready to proceed with making bundles before the dag to make them is created. This provides an option to the user to make edits to files involved in creating the dag like build_dag.sh, cant_be_built and needs_full_build before the dag is created.
* …
> Changes to prevent the process of building bundles from failing,added option in install script to delete an existing virtual environment location

- bin/pycbc_submit_dax
Add the feature to put multiple cache and map files together into one cache file without user input.
Fails if one of the cache files is malformed or does not exist (Tested and this seems to fail when you give it a cache file that isn't in the form of `file:///` or `file:///foo.map` doesn't exist or `https://foo.cache` doesn't exist.
Current test workflow in progress. Do not merge yet. I noticed that this version of pycbc_submit_dax output a syntax error when generating:
`Querying Pegasus database for job..Error: near "wf_uuid": syntax error`
However, the workflow does not seem to have failed, nor does pegasus-dashboard signal that anything is wrong. The workflow is currently ~1/5 of the way complete.
> Allow pycbc_submit_dax to use more than a single cache file

- bin/inference/pycbc_inference
- pycbc/inference/likelihood.py
- pycbc/inference/option_utils.py
- pycbc/inference/prior.py
- pycbc/inference/sampler.py
- pycbc/io/inference_hdf.py
- pycbc/waveform/generator.py
This patch makes more changes to the sampler and related modules in order to prepare for adding the parallel tempered sampler. The changes include:
* Setting the initial walker positions is now a class method for each sampler.
* Calculating and writing acls are now also methods under each sampler. When writing acls, the acl of each chain is saved to the attribute of that chain's dataset. The maximum over all chains is still saved to the same spot (`fp.attrs['acl']`), with the default to use that value.
* The indexing of the returned chains and lnpost have been transposed to be consistent between samplers and with emcee. Now, chains always have shape `[additional dimensions x] niterations x ndim`, where `additional dimensions` is specific to the sampler. For `emcee` and `kombine`, this …
> More updates to sampler.py

- pycbc/inference/likelihood.py
- pycbc/inference/sampler.py
- pycbc/io/inference_hdf.py
This patch adds the ability to save the log likelihood ratio and the log prior to the output file of inference hdf. These values are saved instead of the lnpost (as it could mean different things, depending on the likelihood evaluator and sampler used). Along with the log noise likelihood (saved as an attribute), this allows one to reconstruct any of the canonical Bayesian statistics for the inference run.
Depends on PR #1056, so putting on hold until that is merged.
> Save log likelihood ratio and prior to inference file

- bin/inference/pycbc_inference
- pycbc/inference/likelihood.py
- pycbc/inference/option_utils.py
- pycbc/inference/prior.py
- pycbc/inference/sampler.py
- pycbc/io/inference_hdf.py
Adds emcee's PTSampler to `sampler.py` to allow for multiple temperature MCMC sampling. This allows for an accurate evidence calculation.
To get this to work, some further changes were needed to the likelihood and prior evaluators. For priors, instead of taking a list of args, PriorEvaluator's `__call__` now just takes a list, as likelihood does (that this didn't raise an error before was a bit lucky anyway). For likelihood, I added a class method to set the call function. I had to do this as a class function to allow for multi-pooling. This was necessary for PTSampler because it expects the likelihood function and prior functions to be separate.
I've also made it so that inference will try to compute evidence and save it when checkpointing, if the sampler supports it.
This patch depends …
> Add emcee's parallel tempered sampler

- pycbc/waveform/bank.py
The file handling of Condor-BOINC only preserves one filename extension 'level. Treat a template bank filename extension ".xmlgz" the same as ".xml.gz".
> support template bank filename extension '.xmlgz'

- pycbc/waveform/ringdown.py
Change complex128 to float64 in time domain ringdown waveforms.
> Time domain waveforms should not be complex

- bin/hdfcoinc/pycbc_coinc_bank2hdf
- bin/hdfcoinc/pycbc_coinc_mergetrigs
- pycbc/events/events.py
- pycbc/waveform/bank.py
* Centralize the generation of template hashes so all the code get the information from a consistent source
I've tested this with a workflow and by hand. You now get consistent template hashes from pycbc_coinc_bank2hdf and pycbc_inspiral
* Relax requirement in pycbc_coinc_mergetrigs on templates being in hash order within the template bank. 
I still need to test this point. DO NOT MERGE
> fix critical bug which scrambles template ids

- bin/hdfcoinc/pycbc_make_coinc_search_workflow
- bin/minifollowups/pycbc_foreground_minifollowup
- bin/minifollowups/pycbc_page_snglinfo
- bin/minifollowups/pycbc_sngl_minifollowup
- pycbc/io/hdf.py
- pycbc/workflow/core.py
- pycbc/workflow/minifollowups.py
This PR adds a new minifollowup page to our results page that is intended to run on non-coincident data only. Specifically the code currently uses the TRIGGERS_GENERATED segment lists to determine what is non-coincident data, so this will *not* include time where one detector was CAT_2 vetoed, for example (such triggers would show up in the full single-detector minifollowups though).
To enable this I make the following changes:
* Create a no-op job for minifollowups, which are used in the case of 0 triggers. This is enabled for both single and coinc minifollowups.
* Add ability in pycbc_page_snglinfo to followup a specific trigger instead of the nth loudest. This avoids having to recalculate what nth loudest means again.
* Add option to use non-coinc time only in singles minifollowup and …
> Add single-detector minifollowups for non-coincidence time only

- bin/pycbc_submit_dax
Ran a test workflow that made it through and the cache is filled out by both an absolute path (`file:///`) and relative path. Though the routine of sleeping and trying to query the pegasus database seems to not work well on atlas8.
```
Querying Pegasus database for job:Querying...Error: near "wf_uuid": syntax error
Query failed: sqlite3 -csv /home/steven.reyes/.pegasus/workflow.db "select submit_hostname,wf_id,wf_uuid from master_workflow where submit_dir = '/local/user/steven.reyes/pycbc-tmp.uIt65kuB8s/work';"
Sleeping for 0 seconds and retrying...
```
...
```
Sleeping for 8 seconds and retrying...
Querying...Error: near "wf_uuid": syntax error
Query failed: sqlite3 -csv /home/steven.reyes/.pegasus/workflow.db "select submit_hostname,wf_id,wf_uuid from master_workflow where submit_dir = …
```
> Add extra option to pycbc_submit_dax to use relative paths for regular files.

- bin/pycbc_ringinj
- pycbc/waveform/generator.py
- pycbc/waveform/ringdown.py
The current ringdown module doesn't know that the amplitudes of the subdominant modes will be smaller than the amplitude of the fundamental mode. Therefore, when running pycbc_inference with ringdowns that have higher modes, it can confuse the modes and think that the fundamental mode is the one with lower amplitude.
With this patch, when calling the ringdown approximant, one has to give the amplitude of the fundamental (220) mode and the fraction of the amplitudes of the subdominant modes relative to the fundamental mode. This way in pycbc_inference it will only be allowed that the subdominant modes have amplitudes up to a certain fraction of the fundamental mode.
> Amplitudes ringdown as relative amplitudes

- bin/pycbc_submit_dax
This patch prevents stderr from `curl` from appearing on the screen, however `echo $?` still returns the error message of `curl`, so the next segment still works fine if the cache file doesn't exist.
> Add a patch to get rid of curl error flag.

- docs/install.rst
- pycbc.spec
- pycbc/results/legacy_grb.py
- setup.py
This might be a bit provocative, but I'd like to remove pylal from the list of install requirements to PyCBC. It is not needed by the PyCBC library, except for a single function (pylal volume estimation) that we should be moving away from. The function, of course, will still work if pylal happens to be installed. For the time being, I think bundles should still be built with pylal, and some workflows (such as grb) will require pylal for scripts, etc. 
@duncan-brown @a-r-williamson @spxiwh Can we remove pylal as a requirement for the pycbc library itself? Are there any showstoppers?
> do not require pylal for pycbc library

- bin/pycbc_faithsim
- bin/pycbc_make_faithsim
This pull request adds the time-offset between waveforms to the faithsim output and adds a plot. To do this I had to rip out most of the code that faithsim was using to generate waveforms and just call directly the two_pol_filter function in waveform.py. I chose to use two_pol_filter because for precessing faithsims the polarization phase *must* be used, which currently faithsim cannot do. (What did people use for the v3/PhenomP reviews?)
The plots recently sent round the SEOBNRv4_ROM review were generated with this.
> Add time offset to faithsim

- bin/hdfcoinc/pycbc_coinc_mergetrigs
- bin/hdfcoinc/pycbc_plot_throughput
- bin/pycbc_inspiral
- pycbc/events/events.py
Here's a small addition to the throughput information: Specifically we now store the time it takes to make injections, condition, do gating, read data etc. This can be used to measure the fraction of time spent in setup, versus time spent in the main filtering loop. So far this is not added to the plotting code, but the information does get stored. (I have added a "mean average" entry to the plots' legends to have some number to clearly compare over runs).
This has been tested in a uberbank-style run with the injcutter stuff:
https://www.atlas.aei.uni-hannover.de/~spxiwh/LSC/aLIGO/O1/analyses/inj_cutter/chirp_time_window/o1_injcutter_v3cutter/8._workflow/8.01_throughput/
Also a test plot where I plot the new information ... Clearly the presentation is rubbish and we need to do something …
> Add setup time to throughput information

- install_pycbc.sh
- tools/static/hooks/hook-pycbc.py
This copies the bundled ligolw executables into the correct folder. This adds M2Crypto to the list of hidden dependencies.
> Ligolw install patch

- bin/inference/pycbc_inference_plot_posterior
As title says. All default to ``True``.
Example of using ``--hide-contours`` and ``--hide-density``: https://sugar-jobs.phy.syr.edu/~cbiwer/inference/sampler_testing/kombine/posterior.png
> Make contours, density map, and data points optional for posterior plot

- pycbc/waveform/generator.py
This patch adds the ability to use mchirp and eta as variable args and/or frozen parameters in the CBC waveform generators, even though mchirp and eta are not understood by `get_fd_waveform` and `get_td_waveform`. This is done by adding a decorator around the class method that calls the underlying generator function. If 'mchirp' and 'eta' are in the parameters, the decorator converts them to mass1 and mass2 before calling the generator functions. Right now only mchirp and eta are supported, but we could add more derived parameters in the future, such as chi_eff and chi_p. My hope is that by sampling in better measured parameters, the sampler will converge more quickly (I'm testing this now).
I've also added the ability to decorate the returned result. This patch doesn't make use of that, …
> Add ability to use mchirp, eta as variable/frozen params

- pycbc/pnutils.py
This adds a (``mchirp``,``q``) -> (``mass1``,``mass2``) map to pnutils.
I would like to use this for MCMC sampling but this PR just adds the function first.
Checked and looks fine.
```
>>> pnutils.mchirp_q_to_mass1_mass2(1.5, 2)
(2.4656277442758392, 1.2328138721379192)
>>> 2.4656277442758392/1.2328138721379192
2.0000000000000009
>>> pnutils.mass1_mass2_to_mchirp_eta(2.4656277442758392,1.2328138721379192)
(1.5, 0.22222222222222221)
```
> Add mchirp q to mass1 mass2 function.

- bin/pycbc_faithsim
Here I hook up tapering options to pycbc_faithsim. One can provide these either through the sim_inspiral table (in the normal way) or through new command-line arguments (as faithsim can run with sngl_inspiral as well as sim_inspiral).
In doing this I also did some cleanup:
* Moved from optparse to argparse
* Move from print X to logging.info(X)
* Put in the PSD option handling group
* Did some line wrapping
> Adding tapering and cleanup

- bin/pycbc_compress_bank
- pycbc/io/record.py
This adds an append method to FieldArray to so that two arrays can be easily combined. This is a bit smarter than a basic `numpy.append` in that if the two arrays have the same fields, but one or more of these are string with different lengths, the function will figure out what string length is needed to encompass both. Also, the type of the returned array is the same as the first array, so that any added virtual fields are preserved.
Example:
```
>>> bank1 = waveform.TemplateBank('compressed_bank-0_100.hdf', 'r').table
>>> bank2 = waveform.TemplateBank('compressed_bank-100_106.hdf', 'r').table
>>> combined = bank1.append(bank2)
>>> bank1.size, bank2.size, combined.size
(100, 6, 106)
>>> bank1.approximant.dtype, bank2.approximant.dtype, combined.approximant.dtype
(dtype('S23'), …
```
> Add append method to FieldArray

- pycbc/pnutils.py
- pycbc/waveform/bank.py
- pycbc/waveform/waveform.py
- test/test_lalsim.py
* Add the ability to get ringdown and final frequencies for SEOBNRv4 in pnutils.
* Add duration function for SEOBNRv4 templates.
* Enable SEOBNRv4 in the spaghetti plots.
* Unrelated to the main goal, also fix an import error which was preventing test_lalsim from doing anything useful.
* Remove some unused imports.
> Add various helpers for SEOBNRv4

- pycbc/inference/distributions.py
Makes the ``Gaussian`` distribution similar to the other distributions ``__init__`` in ``distributions.py``.
For Gaussian with bounds 1.4 and 1.5 and mean 1.3 and variance 0.01 do:
```
gauss = Gaussian(mass1=(1.3, 1.5, 1.4, 0.01))
```
This example is also in the docstring.
> Standarize Gaussian distribution input.

- pycbc/waveform/generator.py
Adds mchirp,q pregenerator to CBC waveform generator class. As was said in another PR, something more sophisticated will be need to use derived spin parameters with this but that can be another PR.
> Add mchirp,q pregenerator to CBC waveform generator class

- pycbc/coordinates.py
I couldn't find a Cartesian -> spherical -> Cartesian map that's already implemented in numpy or scipy. So I just added the functions, unless someone knows and I missed then I'll close the PR. I would have thought one exists.
I didn't just dump this in pnutils but there's kind of similar functions in there.
This is something I plan to use because I'd like to add sampling with spin magnitude and angles, instead of component spins in the Cartesian directions. Steven will also need that for part of the injection code hes writing.
EDIT:
Example:
```
In [2]: coordinates.cartesian_to_spherical(1,1,1)
Out[2]: (1.7320508075688772, 0.78539816339744828, 0.95531661812450919)
In [3]: coordinates.spherical_to_cartesian(1.7320508075688772, 0.78539816339744828, 0.95531661812450919)
Out[3]: (1.0, …
```
> Add cartesian and spherical coordinates map

- docs/install_lalsuite.rst
- install_pycbc.sh
I keep getting this warning every single time I source my virtualenv created with the install script:
```
lalsuiterc is deprecated; source /home/cbiwer/opt/pycbc-dev/opt/lalsuite/etc/lalsuite-user-env.[c]sh instead
```
I changed the install script and the documentation to use the new lalsuite env script.
> Install script use non-deprecated lalsuite env script

- pycbc/coordinates.py
- pycbc/io/record.py
- pycbc/waveform/parameters.py
Adds ``Parameter`` classes for spin magnitude (``spin1a``) and spin angles (``spin1phi``,``spin1theta``) for both component spins. Doesn't add it for primary and secondary masses.
The PR includes them ``WaveformArray`` as well. It uses ``pycbc.coordinates``, which I broke up the Cartesian -> spherical calculations into smaller functions since it would've been overkill for ``WaveformArray``.
Need this PR though just so spin magnitude and angle shows up in the default plotting parameters list.
EDIT:
Example:
```
In [1]: from pycbc import coordinates
__init__: Setting weave cache to /local/cbiwer/5451_python27_compiled/36c77c/36c77c7a0a1f2b2d85b9e22d339418d817f0890a
In [2]: coordinates.cartesian_to_spherical(1,1,1)
Out[2]: (1.7320508075688772, 0.78539816339744828, 0.95531661812450919)
In …
```
> Adds spin magnitude and angles Parameter classes

- pycbc/waveform/generator.py
So this uses a decorator to display what the input parameters and output parameters for the functions at the top of ``pycbc.waveform.generators``.
This is the sort of literal implementation from Collin's description in #1108:
>>  @ahnitz has suggested that we make it so that each function "advertises" the parameters it takes in and what it converts them to.
Though an alternatively would to have these functions become classes (kind of silly since they'll not have instances) with a ``staticmethod`` and ``input_params``/``output_params`` as attributes. If you'd prefer this way let me know and I'll change the PR.
EDIT: Though I think we'l just end up with the same pickling problem we're trying to avoid with these functions.
Anyways could use the superset operation between these lists and a …
> Display what parameters are input and output for pycbc.waveform.generator functions

- bin/hdfcoinc/pycbc_plot_singles_timefreq
- pycbc/io/hdf.py
- pycbc/pnutils.py
* Load triggers via the HFile class and its select() method to avoid reading huge datasets at once.
* Modify that class to optionally return a list of indices passing the selection function. 
* Fix a wrong function name preventing usage with SEOBNRv4.
After this change the script uses at most ~450 Mb of memory when plotting 20 s from all-O1 single trigger files.
> pycbc_plot_singles_timefreq: fix absurd memory usage and error with SEOBNRv4

- pycbc/types/array_cpu.py
"WEAVE_FLAGS" already contains the flags listed here, so it was redundant to add them again, and removes the option to set them through the environment.
> remove redundant flag option

- pycbc/__init__.py
Since some time ago, every time you use pycbc or import pycbc modules in ipython an init message appears saying 'setting weave to...'
This PR hides that message to appear only when verbose option selected.
> Hide message that says 'setting weave blah blah'

- pycbc/inference/sampler_base.py
- pycbc/inference/sampler_emcee.py
- pycbc/io/inference_hdf.py
This moves ``get_slice`` from the sampler modules and makes it an instance method of ``InferenceFile``. Something like this should be an instance method.
There are also a lot of if-else statements for a single iteration in the chain or a slice. These aren't really different things, ``slice(n, n+1, 1)`` is the same as getting the n-th iteration. We could remove these special cases later and just pass ``thin_start=n, thin_end=n+1, thin_interval=1`` but not for this PR.
> Make get_slice an instancemethod.

- pycbc/waveform/generator.py
Adds a ``self._pregenerate_functions`` attribute for keeping track of a list of functions to call before waveform generation with ``generators.py`` module.
Also replaces ``self._pregenerate`` with ``self._add_pregenerate`` that updates the list.
Then in the decorator (``_gdecorator``) iterate over these functions and call them before waveform generation.
Python ``set`` operations are used to decide what functions are needed.
Example:
```
In [2]: generator = waveform.FDomainCBCGenerator(variable_args=['mchirp', 'q'], delta_f=1./32, f_lower=30., approximant='TaylorF2')
In [3]: generator.generate(7, 4)
```
> Use set operations to add a list of functions to call before waveform generation in Generators

- pycbc/io/inference_hdf.py
I'm absent-minded and apparently I never included the commit that indented this function. It should be indented because its an ``instancemethod``.
> Indent function.

- bin/hdfcoinc/pycbc_coinc_mergetrigs
- bin/hdfcoinc/pycbc_plot_throughput
- bin/pycbc_inspiral
- pycbc/events/events.py
- pycbc/inject/__init__.py
- pycbc/inject/inject.py
- pycbc/inject/injfilterrejector.py
- pycbc/strain.py
- pycbc/waveform/bank.py
- setup.py
These are the changes to implement injfilterrejector in PyCBC. The basic idea is that 'injfilterrejector' is used to determine whether to filter a segment against a template based on the parameters of the template and any injections made into the segment.
There are currently two tests in injfilterrejector (though one could add more). A chirp-time test, as previously implemented, and a coarse-match test. Using both together speeds up injection runs by over an order of magnitude in tests I've done.
I'm running through some final checks with this version of the code now, to compare with and without injfilterrejector, but I wanted to post the PR now to deal with any comments or code-quality issues. By default injfilterrejector is not enabled, and if no injections are present it does nothing. …
> Implementing injection-filter-rejector in PyCBC

- pycbc/__init__.py
Reverts ligo-cbc/pycbc#1129
As noted in the mattermost chat, this has broken coinc_workflow.
> Revert "Hide message that says 'setting weave blah blah'"

- pycbc/waveform/generator.py
Resubmission of #1135.
Includes a check that if user provides an inappropriate set of options then it displays what args are not being used as an error. This is to keep people from thinking that are generating a waveform with the ``_pregenerate`` functions when they provide the wrong inputs. Eg. missing ``spin2_polar`` option:
```
In [1]: from pycbc import waveform
In [3]: generator = waveform.FDomainCBCGenerator(variable_args=['spin1_a', 'spin1_azimuthal', 'spin1_polar', 'spin2_a', 'spin2_azimuthal'], delta_f=1./32, f_lower=30., q=1, mchirp=2, approximant='IMRPhenomP')
ValueError: The following args are not being used: set(['spin1_a', 'spin1_polar', 'spin1_azimuthal', 'spin2_a', 'spin2_azimuthal'])
```
Also allows spin magnitude and angles to be used with generators.
> Add spin magnitude and angles to generators.

- bin/pycbc_hdf5_splitbank
- pycbc/waveform/bank.py
This PR adds an executable ```pycbc_hdf5_splitbank``` in ```pycbc/bin``` and modifies ```pycbc/waveform/bank.py```. @cdcapano Thanks for your comments on my last PR for the splitbank code. I closed that PR because I messed up it's commit history. This PR is a replacement of that one. I've added the changes you had suggested in this PR.
pycbc_hdf5_splitbank :
* The arguments are similar to pycbc_splitbank.
* The code reads in an input template bank and splits it into smaller banks where the number of output banks is a user input.
* The output banks are in hdf5 format.
Modifications in bank.py:
* Changes made to the ```write_to_hdf``` function in the ```TemplateBank``` class to produce a hdf5 file in which a subset of the template bank would be written 
* Removed white spaces
> Code for splitting a given compressed template bank into smaller banks in hdf5 format

- pycbc/workflow/pegasus_files/pegasus-properties.conf
Pegasus 4.7 uses a new hierarchical layout of the submit directories. However, this breaks our workflows as we don't give full paths to sub-daxes in the workflow. At some point we should fix this, but the workaround for now is to tell Pegasus 4.7 to use the same directory layout as 4.6.
> Force backwards compatibility for submit directory layout

- pycbc/workflow/core.py
- pycbc/workflow/pegasus_workflow.py
I said I would right a patch for this, and so I have. Unfortunately, I haven't had the chance to test this, so if someone is able to quickly, that would be helpful. 
This patch allows global profile information to be overriden by subsequent profile calls. This means that we can set a global minimum memory request in the [pegasus_profile] section and still have executables respect subsequent [pegasus_profile-exe] sections.
> allow profile to be overriden

- pycbc/workflow/pegasus_files/pegasus-properties.conf
For #1151 I think @duncan-brown changed the wrong setting. I think this is the right one to change. I think our workflows *will* run with pegasus.dir.submit.mapper set to its default value. But as an advanced user, a disadvantage to that is it may slow down debugging if I have to search for relevant submit files.
> Fix local-site-scratch variable

- bin/pycbc_aligned_bank_cat
- bin/pycbc_geom_aligned_bank
- pycbc/tmpltbank/bank_output_utils.py
- pycbc/tmpltbank/option_utils.py
This is needed for the uberbank workflow to produce a consistent bank when the variable cutoff is used in sbank. Tested with `pycbc_geom_nonspinbank`.
> Ability to save low-frequency cutoff into bank XML files

- pycbc/workflow/configuration.py
@ahnitz The recent change to add a pegasus_profile section broke the workflow because it doesn't obey the "no duplicate options in subsections" rule.
In this case I think it is best to allow a specific exemption. Maybe we should consider allowing options to be overridden at some point.
> Allow exemption for pegasus-profile section

- pycbc/frame.py
If the state vector channel can't be read but the hoft could, let's just treat that as a failure and return a failed status indicator.
> fail status if channel cannot be read

- bin/pycbc_banksim
This is a change to `pycbc_banksim` which enables picking up the per-template low-frequency cutoff from a given column in the template table.
I also moved print statements to the logging module, added some `required=True` to the CLI and simplified/cleaned up the code a bit.
I did some basic checks against an old banksim I had lying around, but please let me run this on the variable-flow bank before merging.
> pycbc_banksim: variable low-frequency cutoff and cleanup

- bin/pycbc_submit_dax
Currently the cleanup operation (basically a rm of the temporary "local-site-scratch" directory) in pycbc_coinc_search_workflow is not working because it is removing the wrong directory. The issue seems to be inconsistent use of relative-dir and relative-submit-dir in pycbc_submit_dax. Therefore the local-site-scratch for the sub-daxes is *not* a sub-directory of the local-site-scratch for the main uberdax.
This is easily fixed with the attached patch. Tested on pegasus 4.6.2 and 4.7.1dev.
I think I have also tracked down the reason why the workflow fails if we do not use "flat" directory layout (`pegasus.dir.staging.mapper=Flat`)in the local-site-scratch directories. I think it is a bug is pegasus 4.7.1dev, so will try to explain this to @vahi in email.
> Use relative-dir not relative-submit-dir

- bin/pycbc_geom_aligned_bank
Add memory requirements for the pycbc geometric aligned-spin bank generator.
Maybe at some point we should rewrite the aligned-spin workflow so that it just takes a configuration file like normal pycbc workflows. I don't have time for this before O2, so this is the best solution for now.
> Add memory statements for aligned bank

- bin/hdfcoinc/pycbc_coinc_findtrigs
This adds the ability for pycbc_coinc_findtrigs to accept multiple 'statistic-files' options. It properly merges them together into a single list of filenames internally.
> allow multiple statistic-files options

- pycbc/weave.py
…point PYTHONCOMPILED to the bundle directory
Required for a "onefile" PyInstaller bundle that contains a weave code cache to run, e.g. on OSG
> fixed-weave-cache: if running a 'frozen' 'onefile' PyInstaller bundle,

- pycbc/events/stat.py
This speeds up the call to the logsignalrate method by an order of magnitude. This is important for pycbc live.
> speed up logsignal term

- bin/hdfcoinc/pycbc_plot_throughput
@josh-willis, some more information about throughput has been added in recent patches, but has not yet made it into the plotting scripts. Here I propose some changes to the throughput plots to add some more details onto the review pages. An example of this on a test workflow is here:
https://galahad.aei.mpg.de/~spxiwh/LVC/aLIGO/O1/analyses/inj_cutter/injcutter_debugging/run7/8._workflow/8.01_throughput/
> Add more detail to throughput plots

- pycbc/weave.py
This should fix setting the weave cache location (PYTHONCOMPILED) for all relevant cases (E@H, OSG).
> base the behavior of --fixed-weave-cache on env. var. FIXED_WEAVE_CACHE

- bin/inference/pycbc_inference
Adds a `--config-overrides` option like workflow generators to edit config file from command line.
I didn't use the workflow option group because in the future someone might add options specific to the `Workflow` class and then this would be broken. If you think it should use the workflow option group instead, I'll change it.
> Add --config-overrides to pycbc_inference

- bin/inference/pycbc_inference
The end interval wasn't being set correctly in `pycbc_inference` checkpointing. It would do extra samples. For example if you used `--niterations 22 --checkpoint-interval 10` it would actually do 24 iterations instead of 22.
Adds a `--checkpoint-fast` option that delays writing the ACL/evidence till the end if checkpointing is on. If checkpointing is off, then it operates as usual.
Also adds some PEP8 to `pycbc_inference`.
EDIT: And uses pycbc logging instead of initializing it on its own.
> Fix end interval in pycbc_inference checkpointing and add --checkpoint-fast

- pycbc/weave.py
Not that urgent, as this case is not currently used for our purposes, but this issue should be fixed at some point.
> follow-up fix to #1183: cover all cases correctly

- setup.py
This PR is in response to #1016.
If people are not okay with adding corner to the required for install list they should say so, @ahnitz @cdcapano.
I personally don't care if I have to do ``pip install corner``, this is just a fix for #1016. But we should either do something like this PR or just close #1016 (I guess we could update the install docs with a ``pip install corner`` command in this case).
> Add corner to install required.

- bin/pycbc_submit_dax
- docs/install.rst
- docs/workflow/pycbc_make_coinc_search_workflow.rst
- pycbc/workflow/core.py
- pycbc/workflow/pegasus_files/osg-site-template.xml
This fixes issue https://github.com/ligo-cbc/pycbc/issues/704 by seeing if the user has a temporarty proxy created by an incoming gsissh session and, if they do, stashing it for use by the workflow.
This also fixes a bug in the way that the ``nonlocal`` site was introduced for OSG jobs and adds an addition ``pegasus_profile`` that can be specified for an executable 
```
[pegasus_profile-inspiral]
pycbc|site = osg
```
to tell pegasus that the URL is valid for a given site.
As a bonus, some documentation fixes.
> Fix for the X509_USER_PROXY issue with workflow submission

- docs/workflow/pycbc_make_coinc_search_workflow.rst
- pycbc/workflow/datafind.py
- pycbc/workflow/pegasus_files/osg-site-template.xml
If the datafind command returns file URLs that match the string
```
file:///cvmfs/oasis.opensciencegrid.org
```
then these are CVMFS file so they are also available on the OSG. Add additional PFN entries to the DAX to indicate this. These PFNs are ignored if the workflow is not running on OSG. The OSG PFNs are also ignored on the local site.
This doesn't affect command line datafind queries as they don't go through this code path. This removes the need to pass a separate cache file for frames for OSG running.
Also fix a documentation bug that I noticed.
> If datafind returns CVMFS urls then they can also be used on OSG

- docs/install_lalsuite.rst
Drop the ``--with-hdf5=no`` from the lalsuite configure instructions in the install documentation.
> Documentation fix: SEOBNRv4 ROM requires LAL to have HDF5

- bin/pycbc_submit_dax
This fixes https://github.com/ligo-cbc/pycbc/issues/1198
Tested and it works:
```
Querying Pegasus database for workflow stored in /usr1/dbrown/pycbc-tmp.04KuB58OSk/work
This may take up to 120 seconds. Please wait.................. Done.
Workflow submission completed successfully.
The Pegasus dashboard URL for this workflow is:
https://sugwg-osg.phy.syr.edu/pegasus/u/dbrown/r/309/w?wf_uuid=017abc17-99bd-42ea-a540-ab594ddb8019
Note that it make take a while for the dashboard entry to appear while the workflow
is parsed by the dashboard. The delay can be on the order of one hour for very large
workflows.
```
> Give dashboard longer to respond

- examples/cal/foton_filter_esd_saturation/pycbc_check_pcal_saturation.sh
Adds the option ``--filterbank-gain 1.0`` to the PCAL saturation script. This overrides checking the frame file for the gain and applies a gain of 1.0. The gain is now 0.0 unless an injection is active so checking the frame file for the gain zeroes the output.
> Add --filterbank-gain 1.0 to PCAL script since gain of filterbank is 0.0 if no active injection

- docs/install.rst
Since everyone is updating documentation, this adds quotes so people don't write a useless file.
> Add quotes so the user doesn't write a file.

- pycbc/results/versioning.py
We have already removed everything in pylal, so remove from pycbc-v1.5.5 release.
See the end of this section, where it shows that users are requested not to install pylal:
http://ligo-cbc.github.io/pycbc/latest/html/install.html#installing-source-from-github-for-development
> remove pylal from pycbc

- pycbc/detector.py
This piggybacks off of the current usage of the lal detector class to get the latitude and longitude of each detector. The optimal orientation is computed by adjusting the longitude based on the Greenwich Mean Sidereal Time. This can be verified using the `time_delay_to_earth_center` function. At optimal orientation, a signal should reach a detector on the surface of the Earth 21 ms before it reaches the center of the Earth.
Example usage and output:
```
In [1]: import pycbc.detector as det
In [2]: llo = det.Detector('L1')
In [3]: llo.latitude
Out[3]: 0.53342313506
In [4]: llo.longitude
Out[4]: -1.58430937078
In [5]: ra, dec = llo.optimal_orientation(1162598417)
In [6]: llo.time_delay_from_earth_center(ra,dec,1162598417)
Out[6]: -0.021256732778422018
```
> Added code to determine optimal orientation for a detector at a given GPS time

- bin/inference/pycbc_inference_plot_samples
As title says, this option wasn't added after the option group was added.
Also some PEP8 in the executable and use pycbc logging module.
> Add thin_end to fp.read_samples in pycbc_inference_plot_samples

- bin/workflows/pycbc_make_coinc_search_workflow
- bin/workflows/pycbc_make_psd_estimation_workflow
The subworkflows are always called ``main`` and ``finalization``, which can get confusing if you have a lot of dashboard tabs open showing different main workflows. This patch adds the name of the parent workflow to the sub-workflows for easier debugging.
@stevereyes01 please can you test this patch and merge if it works for you as well?
> Add the root workflow name to the sub-workflows

- bin/pycbc_geom_aligned_bank
Current code leads to Condor errors:
```
[...]
11/10/16 17:23:27 From submit:
11/10/16 17:23:27 From submit: ERROR: Parse error in expression:
11/10/16 17:23:27 From submit:  RequestMemory = 3000 = None
11/10/16 17:23:27 From submit:  ^^^
11/10/16 17:23:27 From submit: Error in submit file file
11/10/16 17:23:27 From submit: Failed to parse the job ClassAd. This may reflect a problem with your submit file syntax.
[...]
```
> geom_aligned_bank: fix syntax error from #1144

- pycbc/workflow/psd.py
Other than being useless, it leads to a LFN conflict in the Pegasus workflow and everything explodes.
> PSD est workflow: don't average over ifos in single ifo workflows

- bin/pycbc_single_template
This fixes https://github.com/ligo-cbc/pycbc/issues/1214 including @tdent's suggestion of having a default in the command line.
This only affects ``pycbc_single_template`` as this should raise a ``ValueError`` in e.g. ``pycbc_inspiral``.
I set this to 10 in the ER10 ini file based on @titodalcanton's suggestion
https://code.pycbc.phy.syr.edu/ligo-cbc/pycbc-config/commit/d46087faa2713ad6ac4ae2a280e3c824569e16bf
> Default to N chisq bins in case of NaN

- bin/pycbc_submit_dax
- pycbc/workflow/pegasus_files/osg-site-template.xml
This encodes HTML special characters in the command line properly and also allows correct parsing of the ``--append-site-profile`` argument.
> Encode html and parse append-site-profile properly

- README.md
- docs/index.rst
This saves us having to keep the citation up to date in the documentation.
> Use the automatic Zendo release for the DOI

- .travis.yml
This will speed up the build by caching, e.g. scipy, in the Travis cache. We don't need to re-build these pips unless a new version has been released.
See https://docs.travis-ci.com/user/caching/
> Cache the pip directory

- docs/workflow/pycbc_make_coinc_search_workflow.rst
Remind the user to set the main workflow name when setting the OSG staging site to local for the main workflow.
> Update OSG documentation

- bin/inference/pycbc_inference
- docs/workflow/pycbc_make_inference_workflow.rst
- pycbc/io/inference_hdf.py
This adds options to `pycbc_inference` to gate segments of data before analyzing. Both the data to be analyzed and the data used for PSD estimation may be gated. The data may be gated either before FFT-ing or after being overwhitened. I've found that doing the latter allows you to use a steep taper without incuring a bunch of noise. This is useful in case a significant signal occurs close to a glitch. It's also needed for the testing the area theorem paper, as we gate away the merger when doing PE on the insprial. Right now the gates are passed in by command line options. It's not very pretty. Not sure of a better way to do it though.
This patch also adds command line options to save the strain, PSD, and frequency domain strain to the output file. These are saved in similar groups as the …
> Add ability to gate data to pycbc inference

- README.md
- docs/workflow/pycbc_make_inference_workflow.rst
Example Inference file now references mass2 in the [prior-mass2] section instead of mass1.
> Documentation correction for pycbc_make_inference_workflow

- bin/pycbc_single_template
Incorrect syntax originally, a numpy float doesn't have the .isnan() option, use numpy.isnan(float) instead.
Without this patch `pycbc_single_template` crashes.
> Correct is NaN syntax mistake

- bin/pycbc_inspiral
- pycbc/vetoes/bank_chisq.py
- pycbc/waveform/bank.py
This updates pycbc inspiral (FilterBank) to read the start frequency of templates from the template bank. If an xml file is used the 'alpha6' column is used. If an hdf file, the 'f_lower' column is used. An explicity '--enable-bank-start-frequency' option needs to be given to pycbc_inspiral to enable this functionality. This will override all other options such as (--max-template-length).
> Read the template start frequency from the template bank

- bin/pycbc_faithsim
This will report errors when verbose mode is enabled that occur when trying to generating a waveform.
> pass errors through faithsim

- bin/hwinj/pycbc_generate_hwinj
Alternative to #1252. If this is merged we can close #1252.
The problem is when using a ASD/PSD file with ``pycbc_generate_hwinj`` it will still try and generate strain using the ``strain`` module. It only needs the strain to generate the PSD so its kind of worthless to keep this step in there if using ``opts.psd_file`` or ``opts.asd_file``.
This PR:
* Skips strain reading if ``opts.psd_file`` or ``opts.asd_file`` are set.
* Add interpolation to the waveform's ``delta_f`` if ASD/PSD files happen to be something different.
* Also have to remove the verify strain options because if ASD/PSD file are given, then user shouldn't be required to set something like ``--fake-strain zeroNoise``.
I got carried away and changed a lot of stuff to PEP-8 as well. So I'll point out that the interpolation …
> Allow pycbc_generate_hwinj to use --asd-file and --psd-file

- docs/install.rst
I had some trouble installing on MacOS 10.10 because of openssl and m2crypto. I've just added a line to the install instructions to explain how to solve it.
> Add note on MacOS installation of m2crypto in install instructions

- bin/hdfcoinc/pycbc_page_snrratehist
This PR changes the way that we bin histograms for this plot. The code before was trying to be clever in the way it decided minimum and maximum bounds for binning up the space. This changes it to a naive method of just take the min of the data, and max of the data, space it evenly with a fudge factor of two extra bins in case the min = max. The previous code failed due to there being a single foreground trigger that was louder than all of the background. This tried to force the histogram to use one bin for the background histograms.
Standby while I check that the code produces the same plots as before. The binning will be slightly different however for many plots, but I don't really think that's a big deal since it's just a change in bin locations. I'll post comparisons of the plots …
> Change the binning in histograms in pycbc_page_snrratehist

- bin/hwinj/pycbc_generate_hwinj
While waiting for pycbc_generate_hwinj to generate an SEOBNRv2 waveform I hacked it to eliminate the second waveform generation so as to speed it up. I don't know why Chris had put that in there in the first place, it seemed to be a sanity check of sorts but it looked like it was unnecessary.
> Faster pycbc_generate_hwinj

- bin/pycbc_submit_dax
- docs/install.rst
- docs/workflow/pycbc_make_coinc_search_workflow.rst
Change ``pycbc_submit_dax`` so that it does not create a proxy if the certificate is already a proxy. This fixes https://github.com/ligo-cbc/pycbc/issues/1248.
Change the OSG instructions now that ``pycbc_inspiral`` releases are available from CVMFS and the default Pegasus profile for the inspiral executable is ``installed = true``:
https://code.pycbc.phy.syr.edu/ligo-cbc/pycbc-config/commit/ca493a05911c7ece3864b1e7bfe8c43ae2c3d49b
> Minor bug fixes for OSG running

- bin/hdfcoinc/pycbc_coinc_findtrigs
This allows the coincidence to proceed in the event there are absolutely not single detector triggers....
> initialize findtrigs with empty list

- docs/workflow/pycbc_make_coinc_search_workflow.rst
> Remove --cache from the arguments to be added to pycbc_submit_dax in pycbc_make_coinc_search_workflow running docs.

- pycbc/workflow/core.py
This cleans up some messy code in the Executable() class that also prevents file urls being used on remote sites (see https://github.com/ligo-cbc/pycbc/issues/1264).
I have tested it with various combinations, including missing executables to trigger the error.
> Fix the way that executables are added to the DAX

- docs/workflow/pycbc_make_coinc_search_workflow.rst
This is a temporary workaround for https://github.com/ligo-cbc/pycbc/issues/1270
> Always say the executable is not installed

- pycbc/workflow/core.py
This stops pegasus from generating the warning message:
```
2016.11.20 13:09:22.656 EST: [WARNING]  profile hints.executionPool is deprecated. Replacing with hints.execution.site 
```
> Remove the profile hints.executionPool

- pycbc/workflow/configuration.py
There are two issues with the recently added sharedoptions section if using it in coinc_search workflows:
* The sharedoptions section must be removed after parsing, to avoid sub-daxes trying to repeat the sharedoption parsing and failing because options are already there.
* I want to support sharedoptions with sections that may not exist. In the case a section does not exist, just make it.
I would like this included in the next release, as I am using it with proposed O2 injection set (see today's call for more update).
Still being tested.
> Fixes to sharedoptions section

- pycbc/io/record.py
This patch fixes a couple of bugs I've noticed when using `FieldArray` and `WaveformArray`. If adding a single new virtualfield to a field array, you should be able to do:
```
farr = FieldArray.from_kwargs(foo=numpy.arange(10))
def bar(self):
return self.foo + 2
f2 = farr.add_virtualfields('bar', bar)
```
However, currently this ends up adding 3 virtual fields called `'b', 'a', 'r'`. This patch fixes this by converting the input arguments to lists if they are not already.
The second bug is specific to `WaveformArray`: if you have a waveform array that is not 1D, the current version will raise an error if you try to use derived fields such as `m_p` or `m_s`. For example, the following will raise an error:
```
>>> from pycbc.io import WaveformArray
>>> import numpy
>>> m1 = …
```
> Fix minor bugs in FieldArray and WaveformArray

- bin/inference/pycbc_inference_plot_movie
- bin/inference/pycbc_inference_plot_posterior
- pycbc/inference/option_utils.py
- pycbc/results/scatter_histograms.py
We found a couple bugs while using the new `plot_posterior` and `plot_movie` added in PR #1050: the marginal plots do not always have the same limits as the scatter/density plots, there is a large white space between the last plot and the colorbar when no marginal plots are created. This patch fixes these two issues and introduces a few new things:
* When just creating a 2D plot, the marginal plots are made to be 1/3 the density/scatter plot and the right one is rotated. I've found this is useful when creating plots for presentations and/or papers. (See 2D density plot example, below.)
* The colorbar is automatically turned on/off depending on whether a `z-arg` is specified, rather than making the user do it.
* Minimum and maximum values to plot for each parameter can be specified on the …
> Some bug fixes to the new posterior plots

- pycbc/waveform/waveform.py
- tools/install_travis.sh
Set the lalsuite version to the commit https://versions.ligo.org/cgit/lalsuite/commit/?id=a2a5a476d33f169b8749e2840c306a48df63c936
This includes the new waveform interface and the patch to change the SEOBNRv4 ROM data to the version 2 hdf files.
> Update lalsuite version and fix a bug in waveform.py

- bin/hdfcoinc/pycbc_coinc_bank2hdf
This changes the default, so that xml files with a populated f_lower column actually pass that to the output hdf file in pycbc_coinc_bank2hdf. This has become an issue because this hdf bank is now used internally for the inspiral jobs and we want to make use of this column.
> make sure bank2hdf also looks for f_lower column by default

- bin/hdfcoinc/pycbc_coinc_mergetrigs
This should patch the issue brought up in [here](https://github.com/ligo-cbc/pycbc/issues/1291).
> Fixes the IOError in pycbc_coinc_mergetrigs

- pycbc/fft/__init__.py
- test/fft_base.py
- test/test_autochisq.py
- test/test_fft_unthreaded.py
- test/test_fftw_openmp.py
- test/test_fftw_pthreads.py
- test/test_lalsim.py
- test/test_schemes.py
If I run `python setup.py test` I get a number of failures due to many of the test scripts being out-of-date. This patch allows all of the test scripts to run succesfully in all but two cases:
- The first is an FFT that _does_ run but shouldn't run (apparently). I'll comment on that at the line in question shortly.
- The second is test_lalsim.py. A whole bunch of waveforms fail in a variety of different cases here.  There are a number of different failure modes, and I don't want to track this down for waveforms that I think are not used in production analysis. However, some common issues that I have noticed: 
- The various EOB models are as stable as the test requires when making changes to input parameters at the tolerance level. This is known: The various numerical solvers are sensitive …
> Changes to make test cases work

- pycbc/workflow/jobsetup.py
Alright @ahnitz @titodalcanton @duncan-brown, here's my attempt to fix #1311.
First the problem: Currently the JobSegmenter in pycbc.workflow chooses a set of potential lengths of data for jobs to read in based on length of the lock stretch. For shorter lock stretches less data is read in per job than for longer lock stretches. Bounds can be placed on this in terms of *either* number of inspiral analysis segments *or* total data read in ... We currently use *both* bounds, which is also allowed.
Now, when choosing the data stretches JobSegmenter uses the possible number of analysis segments (which becomes somewhat more tricksy when zero-padding is enabled). Our stated minimum analysable lock length for O2 is 528s. This is *not* a multiple of analysis segments. So JobSegmenter rejects ~350s …
> Ensure minimum data length is always an option

- pycbc/workflow/jobsetup.py
- pycbc/workflow/splittable.py
Proposed patch to re-allow the use of pycbc_splitbank in workflows. This is still used in PyGRB as of the beginning of O2.
> Reinstating pycbc_splitbank as executable class

- pycbc/inference/boundaries.py
My commit in PR #1149 broke pycbc inference if using a prior with cyclic boundaries on multiple cores. The problem is the way the way `apply_cyclic` is done cannot be pickled, which causes `pycbc_inference` to fail. I didn't hit this bug when testing because I was using a patched version of kombine that sets up the pool in a more efficient way (see PR #1308 for detail). @Cyberface, who has been trying to use pycbc inference on master, discovered it. Eventually this won't be a problem, but as PR #1308 is held up until the patch it relies on in kombine is merged, another fix is needed now.
This patch fixes the pickling problem, allowing pycbc inference to work again. I've tested this with the non-patched kombine.
> Fix pickling error in pycbc inference

- bin/workflows/pycbc_make_coinc_search_workflow
- pycbc/workflow/tmpltbank.py
This PR is about making `pycbc_make_coinc_search_workflow` flexible to be able to read in the template bank in both hdf/h5 and xml format. If the bank read in is in hdf format, it is used as it is in the workflow. If not in hdf/h5 format (like xml), it is converted to hdf format and then used in the full data and injections jobs.
> Changes to make pycbc_make_coinc_search_workflow flexible to reading in a template bank in both hdf and xml format

- bin/inference/pycbc_inference
- pycbc/inference/option_utils.py
- pycbc/inference/sampler_base.py
- pycbc/inference/sampler_emcee.py
- pycbc/inference/sampler_kombine.py
This patch does a few things:
1. An update interval can be set on the command line to pass to kombine. This will cause kombine's internal kde to be updated after the given number of iterations. This is useful if we want to be able to skip using kombine's burn in function, or if its burn in function finishes before the sampler is actually burned in.
2. Only points since the last checkpoint are written to the output file. Right now, all points in the chain are re-written to the file on every checkpoint (that was my fault). This can result in the file writing taking just as long or longer than the actual MCMC evolution, particularly as the number of iterations gets large.
3. After checkpointing, the in-memory chain is cleared except for the last point. This is so that when doing a large …
> Add ability to set kombine's update interval and only save points since last checkpoint

- bin/pycbc_ringinj
There is a little bug in pycbc_ringinj that appears when using multi-mode approximants.
> Fix bug in pycbc_ringinj

- pycbc/results/str_utils.py
Currently, `format_value` in `str_utils` will drop the leading minus sign. This causes, e.g., the titles in `plot_posterior` to mis-report negative values as positive. For example, the reported median value of the secondary spin in [this plot](https://www.atlas.aei.uni-hannover.de/~cdcapano/LSC/projects/pycbc_inference/cbc/gw150914/kombine/no_burnin/density-last_pt.png) is 0.641, when it should be -0.641. I believe @Cyberface had run into this when creating posterior plots of effective spin in his runs.
This patch fixes this, adding a leading minus sign if the given value < 0 (it looks like I had originally addressed this at some point in the past, but it got messed up in subsequent edits).
> Format value drops minus sign

- docs/install.rst
Hi folks,
We attempted to follow the install instructions and found that the url in the docs for the hdf5 download appears to be broken. I tracked down a working url and have swapped it in.
Cheers,
Andrew
> Fixing broken hdf5 url in docs

- bin/hwinj/pycbc_generate_hwinj
- pycbc/types/optparse.py
This fixes the issues noted in #1338. I have overridden the boolean built-in testing for the multi-inspiral option types to match better behaviour in the single-inspiral options (ie. False if option not given on command line, True is *anything* given on command line, regardless of format). I also fix two places in generate_hwinj where it is broken.
I have tested that the correct boolean is returned in each of the 3 possibilities for multi-inspiral options (option not given; option given as value for all ifos [this is the one that was broken]; option given separately for all ifos) .
Please squash when merging.
> Fixes for pycbc_generate_hwinj

- bin/pycbc_make_html_page
- pycbc/results/render.py
If Michael Pürrer makes a commit on lalsuite that we run with pycbc_make_html_page will break.
This patch supports Michael by using utf-8 encoding when reading and writing files in the html generation.
This has been tested and I have verified that Michael's patches now build a web-page. Thanks to stackoverflow:
http://stackoverflow.com/questions/10908761/printing-non-ascii-characters-in-python-jinja
for the solution, I 1-upped the suggestion in use here.
Note that the errors.replace line will mean that even if you add in non-UTF8 characters into the html files, it should get converted into something that will at least show on the web-page (maybe you get a '?' symbol, not really sure).
> Support Michael

- pycbc/inference/boundaries.py
- pycbc/inference/distributions.py
The goal of this pull request is to have a distribution fro pycbc_inference that can take a file (given in the config file) and read the parameters from it. This could be, e.g., the posterior from one PE run that wants to be used as prior in another run.
Then distributions.py will compute the kde from the values in that file, construct the pdf, and draw a set of random variables to feed them to the walkers.
> Distribution for pycbc_inference that reads parameters from a file

- bin/minifollowups/pycbc_single_template_plot
- bin/pycbc_single_template
The `pycbc_single_template` plots can be a little difficult to reproduce because they only show the command line of the plotting utility, not the actual pycbc_single_template executable. This patch adds both command lines to the web page.
This has been tested.
> Show both command lines on sngl plots

- bin/pycbc_aligned_bank_cat
- bin/pycbc_bank_verification
- bin/pycbc_geom_aligned_bank
- bin/pycbc_tmpltbank_to_chi_params
- bin/workflows/pycbc_create_sbank_workflow
- bin/workflows/pycbc_create_uberbank_workflow
- docs/resources/sbank_example1.ini
- docs/resources/sbank_example2.ini
- docs/resources/uberbank_example1.ini
- pycbc/tmpltbank/partitioned_bank.py
- setup.py
This patch converts all uberbank-related codes to write HDF banks. This means that the uberbank construction will not write an XML bank, and will not use the XML format at any point duration bank generation.
@cdcapano agreed to make changes to the Bank class he wrote to allow creating a bank class from arbitrary sets of columns (m1,m2,s1z,s2z,[extra precessing/higher-order mode columns]) and then being able to write such a dataset as XML or HDF. In anticipation of this aligned_bank_cat uses a temporary short set of lines to write it's own HDF file, and the old code for XML writing. The *other* PyCBC bank generation utilities (not used for uberbank) currently cannot write to HDF. Once @cdcapano makes this change I will update all the PyCBC bank generation tools to use this.
It is possible …
> PyCBC bank codes will use HDF5 format

- pycbc/psd/__init__.py
- pycbc/psd/analytical.py
This PR adds a flat PSD model to ``pycbc.psd.analytical``.
It also sets the module up to use PSD models from PyCBC. If ever someone made a new PSD model, then they could just add the function to ``pycbc_analytical_psds`` at the bottom of the module. Then it can be accessed with ``--psd-model``, eg. ``--psd-model flat_unity``.
Example of flat unity model: https://sugwg-jobs.phy.syr.edu/~cbiwer/tmp/psd_test1.png
Example of LALSimulation model (just test to check): https://sugwg-jobs.phy.syr.edu/~cbiwer/tmp/psd_test2.png
> Adds flat_unity PSD model

- bin/inference/pycbc_inference
These lines are redundant since the default in ``pycbc/pycbc/fft/fftw.py`` is measure level 0, and actually these lines override whatever is on the command line option since we have added the fft option group. Should be removed.
> Remove setting measure level to 0 in pycbc_inference.

- bin/minifollowups/pycbc_foreground_minifollowup
- bin/minifollowups/pycbc_injection_minifollowup
- bin/minifollowups/pycbc_sngl_minifollowup
- pycbc/workflow/jobsetup.py
- pycbc/workflow/minifollowups.py
This fixes the edge condition in singles_timefreq reported by @duncan-brown. To fix this the workflow setup can (optionally) use the list of science segments (- CAT 1) to determine what range of data should be read in. If it is not possible to use 10s on each side, the data segment is shifted.
This has been tested on @duncan-brown 's failing workflow here:
https://sugwg-jobs.phy.syr.edu/~spxiwh/aLIGO/O2/test_runs/singlestimefreqfix/run3
And specifically see the plot A22 from here:
https://sugwg-jobs.phy.syr.edu/~spxiwh/aLIGO/O2/test_runs/singlestimefreqfix/run3/5._injections/5.18_followup_of_missed_BBHSEOBNRV3_INJ/
which was the problem. The red lines on that plot are unrelated to the actual injection. The injection is missed because it is injected *right* at the start of the science …
> Fix edge-condition in singles_timefreq

- bin/inference/pycbc_inference
- bin/pycbc_make_html_page
- pycbc/gate.py
- pycbc/gates.py
This PR moves all the gating functions at the top of ``pycbc_inference`` to its own module. This isn't specific to what's going on in ``pycbc_inference`` so lets just move it to its own module.
This PR also creates a option group for the gating options that were added to ``pycbc_inference`` for these functions.
This PR also removes 2 unused imports in ``pycbc_inference`` and fixes the shebang line in ``pycbc_make_html_page``.
> Move gating functions and options from pycbc_inference to its own module

- bin/hdfcoinc/pycbc_plot_bank_bins
Implements #1349, enabling various choices of x and y axes for bank visualization. To implement this conveniently I used a similar approach to the SingleDetTriggers class. I looked at existing bank classes, but couldn't find something like that already implemented. Suggestions welcome if I missed existing functionality.
I also fix here an apparent matplotlib bug which prevents the points from showing up on my local installation when linewidth is exactly 0.
Still testing.
> pycbc_plot_bank_bins: enable choice of x and y axes

- pycbc/__init__.py
IIRC these messages were annoying someone. It doesn't help to use the log functions since the logginng module has not been initialized at this point, so I filtered these with the value taken from INITIAL_LOG_LEVEL environment variable.
> write out weave cache settings only if INITIAL_LOG_LEVEL >= 10

- pycbc/weave.py
The environment variable PYTHONCOMPILED, which points to the weave cache, is set on various occasions, even outside pycbc/__init__.py (see option --fixed-weave-cache). Thus use the then current value of this variable as the location of the lockfile,
> use PYTHONCOMPILED as lockfile_dir

- docs/distributions.rst
- examples/distributions/mass_examples.py
- examples/distributions/spin_examples.py
- examples/distributions/spin_spatial_distr_example.py
An updated PR that includes using pycbc distributions.py to make distributions for mass and spins.
Note that this code will have to change as distributions.py moves from inference to wherever it goes next.
> Distributions examples for Documentation Purposes

- bin/minifollowups/pycbc_sngl_minifollowup
- bin/workflows/pycbc_make_coinc_search_workflow
- pycbc/workflow/configuration.py
- pycbc/workflow/minifollowups.py
Make the sngl minifollowups a little more general in the coinc_search_workflow, allowing for a larger number of such settings, with parameters given in the ini file.
Additional filtering options can be added to pycbc_sngl_minifollowup if one wanted to filter by mass, or by spins.
Unfortunately, this does require config file changes and is not backwards compatible. I will open a pull request with changes needed in the ini files, but that probably shouldn't be merged until this appears in a release.
Note: The changes to get_subsections are to allow this to work when a section_name that is itself a subsection like ['workflow-minifollowups'] is given.
> Generalize sngl_minifollowups

- docs/Makefile.std
- docs/psd.rst
- pycbc/results/followup.py
- pycbc/results/legacy_grb.py
- pycbc/results/scatter_histograms.py
This fixes #1379. That was caused by an error in psd.rst. I've also put a check around the matplotlib.use calls in the results module (matching the check that matplotlib does internally). I don't think these module code should be setting the backend at all. That should be the task of the executable. I didn't want to make that change mid-science run though. After O2 ends, I would like to just delete the matplotlib.use statements, and then codes can be fixed as they fail.
I've also enabled raise error on warning in the docs build, because the docs are *already* giving a warning from #1367. The effort that's going into improving documentation at the moment is awesome, but no-one seems to actually build and check that this documentation works. For e.g.: …
> Fix the docs ... again.

- LICENSE
We really should have this (our top-of-code notes actually promise it). This seems to be the git-hub standard, and should display GPL 3.0 on the PyCBC git-hub home when merged.
> Add standard GPL license

- bin/inference/pycbc_inference
- pycbc/waveform/generator.py
As title says. I think this is more general than just ``pycbc_inference`` and right now its just tossed at the top of the executable.
> Moves select_waveform_generator from pycbc_inference to generator module

- bin/pycbc_compress_bank
- pycbc/fft/fft_callback.py
- pycbc/psd/analytical.py
- pycbc/strain.py
- pycbc/waveform/bank.py
Anuradha (no git-hub handle) recently reported two issues when using an analytic PSD with SPA templates in PyCBC.
One is a bug in the filter-inj-only option, which I think is easily resolved. I hardcode the window, but I think this is "safe", and should not ever need changing ... So I don't want to complicate the code by making this a parameter.
Second is an issue between the SPA template norm and analytical PSDs having a 0 value at Nyquist. I resolved this by making the analytical PSDs match the second-to-last value at Nyquist, but I'm not sure this is the right solution ... We should *not* be using the Nyquist in *any* matched-filter calculations. However, I worry that we probably are in *many* places, so this approach seems safer. @ahnitz, what do you think?
> Fixes to two issues reported by Anuradha

- bin/pycbc_condition_strain
Currently, `pycbc_condition_strain` will fail if you try to generate fake strain from a psd file, as this option needs a `low-frequency-cutoff` option to be in the set of options. I suppose you could argue this is actually a bug in the strain module since `strain.insert_strain_option_group` doesn't add that option even though `strain.from_cli` looks for it when the fake strain options are used. However, since `pycbc_inspiral` and, I think, some other programs would get conflict errors if `low-frequency-cutoff` was added to the strain option group, the easiest thing to do is to just add this option separately to `pycbc_condition_strain`.
This patch also makes it so that if double precision is desired, that is just passed to `strain.from_cli`, instead of casting to single then casting back …
> Fix bugs in condition strain

- setup.py
We no longer need our own fork as they have released a version of mpld3 that is new enough. (I'd also suggest we remove our fork).
> depend on release mpld3

- pycbc/workflow/jobsetup.py
As title says.
The ``EventManager`` object used by ``pycbc_inspiral`` doesn't write XML files anymore so we should change the default.
> Change pycbc_inspiral workflow node output file default to HDF.

- pycbc/inference/distributions.py
- pycbc/waveform/generator.py
This PR adds a new distribution ``UniformRadius`` that can be used for sampling in uniform volume. I'm sure this would have other uses but the immediate idea I have is to use this for sampling spin magnitude and angles in ``pycbc_inference``. I've labeled this as work in progress because the docstrings need to be added and ``_pdf`` and ``_logpdf`` could be re-written. But this at least lets people know I've done this for now.
Since radius goes as cubed in volume you cannot just sample uniformly in radius. You will get a bunch of points near the center of the sphere.
Here's an example on uniform volume sampling I put together to test ``UniformRadius``:
```
#! /usr/bin/env python
from mpl_toolkits.mplot3d import Axes3D
import numpy
from pycbc import …
```
> Add distribution for uniform volume sampling

- pycbc/strain.py
On newer numpy versions, using a float as an index fails. This fixes one place that was causing job failures.
> make sure slice is integer in strain

- bin/inference/pycbc_inference_plot_geweke
- pycbc/inference/geweke.py
- setup.py
There are a couple convergence/divergence tests for posteriors that I would like to add. The simplest convergence test to implement is the Geweke convergence diagnostic. Basically it checks how similar the mean for a segment at the beginning of a chain is to a segment at the end of the chain. If the chain has converged then the mean shouldn't vary much and should fall within [-1,1] if its converged.
This is marked worked in progress because I'm still making some example plots but wanted to share that this is being worked on. Other tests we should add (and I plan to look at after this) are the Gelman-Rubin convergence and Kullback-Leibler divergence statistics.
> Add Geweke convergence diagnostic statistic

- bin/hdfcoinc/pycbc_coinc_statmap
We don't need to keep track of which foreground triggers have been hierarchically removed since there's only one bin now, the ones that are removed are just the loudest N foreground trigger by ranking statistic where N is the number of hierarchical removals.
This addresses one of the last comments in the Merge for PyCBC_Coinc_Statmap
> Remove extraneous lines and update comment for pycbc_coinc_statmap.

- bin/minifollowups/pycbc_foreground_minifollowup
- bin/minifollowups/pycbc_injection_minifollowup
- bin/minifollowups/pycbc_page_coincinfo
- bin/minifollowups/pycbc_sngl_minifollowup
- bin/workflows/pycbc_make_coinc_search_workflow
- pycbc/workflow/minifollowups.py
This patch makes a few more changes to minifollowups:
* Missed injection followups can now take a `--ifar-threshold` option. If given missed injections will include *all* injections with ifar less than this (including injections with no trigger). If not given the previous behaviour (of only considering injections with no trigger) will be used.
* For injections with an associated trigger, the injection minifollowups will also run a coinc_infopage job to display the parameters of the coincident trigger, including IFAR. (This is the same format as for foreground minifollowups, but some minor code changes is needed to use the same code for both cases).
* A maximum duration option is added to sngl_minifollowups.
An example of this is here: …
> Minifollowups changes

- docs/install.rst
It appears that setuptools has additional dependencies that pip is not fetching for some reason. You need to manually install six, packaging, and appdirs before upgrading setuptools.
This changes the install instructions to reflect that.
> Setuptools now has additional dependencies

- pycbc/weave.py
- only if it has not been set externally
- this is meant to allow using ROM files contained in a PyInstaller bundle
- untested yet, as the test analysis currently doesn't work for other reasons
> if using --fixed-weave-cache, set LAL_DATA_PATH to the cache directory

- tools/static/hooks/hook-pycbc.py
- don't fail if NOW_BUILDING is not set
- allow to specify a PYCBC_HOOKS_DIR other than cwd
- necessary if using PyInstaller >=3.0
> augment PyInstaller hook-pycbc for E@H

- requirements.txt
The PyCBC E@H build script is failing as pkgconfig 1.1.0 requires six 1.10.0 (see below). This updates the requirements accordingly. 
```
[Fri Jan 27 14:07:34 EST 2017] install six, pkgconfig and matplotlib beforehand
Collecting six==1.9.0
Downloading six-1.9.0-py2.py3-none-any.whl
Installing collected packages: six
Found existing installation: six 1.10.0
Uninstalling six-1.10.0:
Successfully uninstalled six-1.10.0
Successfully installed six-1.9.0
Collecting pkgconfig==1.1.0
Downloading pkgconfig-1.1.0.tar.gz
Complete output from command python setup.py egg_info:
File "<string>", line 1, in <module>
File "/tmp/pip-build-SrxO3B/pkgconfig/setup.py", line 16, in <module>
test_suite='test',
File "/home/dbrown/projects/pycbc/eah/pycbc-build/lib/python2.7/distu …
```
> Require the new version of six

- bin/pycbc_inspiral
when enough progress was made in pycbc_inspiral since the last update
* this allows to monitor progress (e.g. for E@H) with way less I/O
than following the --verbose output
* the argument to --update-progress is the amount of "progress" that
needs to be made since the last update. 0.01 will update at every
percent.
> With --update-progress write a value 0.0 .. 1.0 to a file 'progress.txt'

- bin/inference/pycbc_inference_plot_movie
- pycbc/results/scatter_histograms.py
This gives adds ability to set the dpi and start/end samples on the command-line for `plot_movie`. Right now the code will always use the last iteration, which is a problem if trying to run plot movie on an result file that hasn't completed yet (since everything after the checkpoint is just 0). I also changed the argument names from "thin-start" and "thin-end" to "start-sample" and "end-sample" to make it more clear what their purpose is.
> Set dpi, start/end sample in plot movie

- bin/hdfcoinc/pycbc_page_sensitivity
@ahnitz I've added the option to bin by template duration and to write all of the curves to an HDF file for replotting (such as comparing VT from different times on the same axes). Since calculating the template duration is time intensive, the calculation is not done unless the user sets `--bin-type template_duration`. Example call:
```
pycbc_page_sensitivity \
--dist-bins 50 \
--integration-method pylal \
--bin-type template_duration \
--bins 0 4 40 120 320 \
--dist-type vt \
--sig-type ifar \
--log-dist \
--injection-file /home/thomas.massinger/CBC/O1/analysis789-rerun/output/allinj/H1L1-HDFINJFIND_ALLINJ-1133173817-4080600.hdf \
--output-file H1L1-ANALYSIS789-FULL-DQ-VT-TEMPLATE-DURATION-TEST.png \
--f-lower 30 \
--hdf-out H1L1-ANALYSIS789-FULL-DQ-VT-DATA-WITH-ERROR-TEMPLATE-DURATION.hd …
```
> Added template duration option and HDF out option

- pycbc/detector.py
This adds a function to the Detector class that returns the time delay between two detectors for the given sky location. The LAL function that's called, `ArrivalTimeDiff`, is the same function that `TimeDelayFromEarthCenter` calls (in that function, the second detector is the geocentric reference frame).
> Add time_delay_from_detector to Detector class

- pycbc/io/hdf.py
Some clusters (e.g. LHO) cannot handle opening many files at once, so that for example one cannot look into all the PyCBC_Live trigger files from one day using DictArray.
This pull request is to close every file after being read.
> Close hdf files after usage

- bin/pycbc_banksim
- pycbc/waveform/bank.py
While @ahnitz is right that I should use the standard .hdf extension in the various template-bank related workflows in PyCBC (and I'll do that), `.h5` is still a valid extension for HDF files, and TemplateBank should be able to handle it (especially if it support the `.xmlgz` extension that I've *never* seen used).
Patch also includes a bug-fix in pycbc_banksim. This was introduced in the final round of commits when introducing bank_verificator and is causing banksim to fail (as `hfc` doesn't exist at all any more).
> H5 support

- bin/hwinj/pycbc_insert_frame_hwinj
- docs/distributions.rst
Adds the ``--scale-factor`` option that scales the amplitude of the waveform. And the ``--precision`` option that allows the user to specify the precision.
> Allow user to scale injection in pycbc_insert_frame_hwinj

- bin/pycbc_submit_dax
Currently the script exits if the check that the proxy exists fails. Wrap it with set +/-e so that the check doesn't abort the script and an error message can be printed.
> Gives error message when there is no proxy

- bin/pycbc_compress_bank
- pycbc/psd/__init__.py
- pycbc/waveform/compress.py
This PR adds in the ability in to implement the use of a psd in compress_bank and then use it in compress.py to calculate overlaps between the decompressed and full waveforms. This PR also makes the options in insert_psd_option_group to do a Welch estimate from data optional. 
@cdcapano This is the new PR. Please could you take a look.
> Ability to read in a psd in compress_bank

- docs/install.rst
- docs/workflow/pycbc_make_coinc_search_workflow.rst
This is a re-write of the data re-use instructions to explain how re-use works and give a few common examples.
A rendered version of the changes can be found [here.](https://github.com/duncan-brown/pycbc/blob/reuse_doc/docs/workflow/pycbc_make_coinc_search_workflow.rst#reuse-of-data-from-a-previous-workflow)
> Improved data re-use instructions

- bin/hdfcoinc/pycbc_page_snrratehist
The current code I've conjured up to make plots like those found on https://www.lsc-group.phys.uwm.edu/ligovirgo/cbcnote/PyCBC/hierarchical-removal-dev-O2
The gist of this is that we want to make plots that show the hierarchical removal process in motion. This code will plot the SNR - Rate histograms but with different inclusive backgrounds. The first plot is for the inclusive background made with no hierarchical removals. The second plot is for the inclusive background after removing the loudest foreground trigger that is louder than the background (GW150914). And the 3rd plot is for the inclusive background after removing the next loudest foreground trigger (GW151226):
https://sugwg-jobs.phy.syr.edu/~steven.reyes/ER10/hierarchical_removal_plots/bulk_bin_0th_background.png …
> SNR - Rate histograms with Hierarchical Removal

- docs/workflow/hdf_coincidence.rst
- docs/workflow/pycbc_make_coinc_search_workflow.rst
- pycbc/workflow/core.py
- pycbc/workflow/pegasus_files/local-site-template.xml
Pegasus 4.7.3 and above run ``pegasus-plan`` for sub-daxes under the kickstart script for better job management. This means that pegasus needs to be told about output map files in the DAX so that it can manage them. This is implemented by this patch. This should also fix @tdent's observation that data-reuse never seems to work if the reuse cache contains a ``.dax`` or ``.map`` file.
This is a fix for https://github.com/ligo-cbc/pycbc/issues/1448
For top-level workflows, the output map is tagged as a file needed by any sub-dax job and *also* added to the list of PFNs (since it is created by the workflow generation script not within the DAX):
```
<adag xmlns="http://pegasus.isi.edu/schema/DAX" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" …
```
> Tell pegasus about output map files in the dax

- docs/building_bundled_executables.rst
- tools/einsteinathome/pycbc_build_eah.sh
Made corrections for the variable names `--with-extra-approximants` and `--with-lal-data-path` in the bundle build script and docs. Also specified in the docs that `--pycbc-commit` is not required to be specified if `--pycbc-branch` is used.
> Fixed variable names in bundle build script and made corrections in docs.

- docs/workflow/pycbc_make_coinc_search_workflow.rst
The way we now run OSG workflows, there is only ``local-site-scratch`` so fix the instructions to reflect that.
> OSG workflows store their products in the local-site-scratch

- bin/hdfcoinc/pycbc_plot_psd_timefreq
Typo in pycbc_plot_psd_timefreq when defining asd_median, does not really affect the results of the code but should be removed
> Remove variable defined twice

- bin/pycbc_live
- pycbc/filter/matchedfilter.py
- pycbc/io/live.py
- pycbc/strain.py
- pycbc/tmpltbank/bank_output_utils.py
- pycbc/waveform/bank.py
This patch starts to implement the `--followup-detectors` option in `pycbc_live`. At the moment, followup detectors are only used for generating the SNR timeseries around triggers found in coincidence in the other detectors.
Note that the state and DQ vetoes of followup detectors are currently ignored, this will be addressed in a future PR.
This patch also fixes a bug caused by templates being sorted at the wrong time and leading to the SNR time series being calculated with an incorrect template.
> pycbc_live: enable followup detectors

- pycbc/io/live.py
Recent GraceDB uploads had `sngl_inspiral` tables whose `process_id` columns are always set to `process:process_id:0` regardless of how PyCBC Live is actually identified in the `process` table.
Note that this has not been tested.
> Fill in sngl_inspiral.process_id in GraceDB uploads

- bin/pycbc_live
In `pycbc_live`, `maxlen` can turn out to be float, which results in indexing an array with a float. Recent numpy versions throw an error because that is no longer tolerated.
> pycbc_live: fix float indexing for recent numpy

- bin/hdfcoinc/pycbc_distribute_background_bins
- bin/hdfcoinc/pycbc_fit_sngls_binned
- bin/hdfcoinc/pycbc_fit_sngls_by_template
- bin/hdfcoinc/pycbc_fit_sngls_over_param
- bin/pycbc_fit_sngl_trigs
- bin/pycbc_inspiral
- bin/pycbc_optimal_snr
- bin/pycbc_single_template
- pycbc/_version.py
- pycbc/full_version.py
- setup.py
This commit adds a very verbose versioning function and uses it to implement the ``--version`` argument in several programs that depend on PyCBC/LAL/LALSimulation being in sync. It works on Mac OS X and Linux. 
This fixes https://github.com/ligo-cbc/pycbc/issues/1477
Sample output is
```
(pycbc-dev)[dbrown@sugwg-osg ~]$ pycbc_inspiral --version
--- PyCBC Version --------------------------
Branch: hash_check
Tag: None
Id: 6d5326d954c4cb2fe884af8becf945314781f1a3
Builder: Duncan Brown <duncan.brown@ligo.org>
Build date: 2017-02-28 16:21:28 +0000
Repository status is UNCLEAN: Modified working tree
Imported from: /home/dbrown/src/pycbc-dev/lib/python2.7/site-packages/PyCBC-6d5326-py2.7.egg/pycbc/__init__.pyc
--- LAL Version ----------------------------
Branch: None
Tag: None
Id: …
```
> Add extended versioning information

- pycbc/workflow/core.py
Several of the ligolw segment manipulation tools need a valid version number. This sets the version to 1 by default in the segment files created by the workflow generators.
> Set a default segment version number

- bin/pycbc_hdf5_splitbank
- bin/pycbc_inj_cut
- pycbc/_version.py
- pycbc/results/versioning.py
This fixes three issues:
* Fix a couple of executables that did not implement ``--version``
* Fix the versioning module to use python 2.7 subprocess
* Fix the versioning module to work with PyPI released code
I also suppressed a spurious error message that happens when trying to ``ldd`` libraries in a bundle.
> Fixes to versioning in results pages

- bin/workflows/pycbc_make_coinc_search_workflow
- bin/workflows/pycbc_make_psd_estimation_workflow
- pycbc/workflow/configuration.py
This allows sections and options to be deleted before overriding them to fix https://github.com/ligo-cbc/pycbc/issues/1445
I also added logging to the option parsing so users can see what is being done, which requires initializing the logger properly before parsing the config file.
> Allow deletion of config parser options

- tools/einsteinathome/pycbc_build_eah.sh
This prevents the runtime error
```
scipy.weave.build_tools.CompileError: error: Command "g++ -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/tmp/_MEIRvNMrZ/scipy/weave -I/tmp/_MEIRvNMrZ/scipy/weave/scxx -I/tmp/_MEIRvNMrZ/numpy/core/include -I/tmp/_MEIRvNMrZ/include/python2.7 -c /tmp/_MEIRvNMrZ/sc_8c737c50380e767211ce7dc444fd21df0.cpp -o /tmp/scipy-dbrown-atHCLH/python27_intermediate/compiler_8d209134f2f9c02590a11606fa273eb2/tmp/_MEIRvNMrZ/sc_8c737c50380e767211ce7dc444fd21df0.o -march=native -O3 -w -march=native -O3 -w -fopenmp" failed with exit status 1
```
I have checked that the GW150914 test produces the same results.
> Turn on sg chisq veto so all code gets built

- pycbc/waveform/compress.py
The psd option should be added to the function `vecdiff` to calculate the overlap between the decompressed and the original waveform, and add sample points based on that, till the tolerance is satisfied. This is consistent with using a psd in `compress_waveform` to calculate the overlap there.
(This doesn't yet fix the infinite loop problem that I saw for at least one template while compressing the O1 bank with precision=single, tolerance=0.0001)
> Added psd option to calculate the overlap between waveforms in the function vecdiff

- pycbc/cosmology.py
- pycbc/io/record.py
- pycbc/waveform/parameters.py
This patch adds a `cosmology` module to pycbc that includes a function to compute redshift from luminosity distance `z(D)`. This is needed when calculating source parameters from PE runs. The module uses LAL's CosmologyCalculator, which provides a redshift-to-distance function `D(z)` based on given cosmological parameters (default is to use standard Lambda CDM). The inverse function is creeated by using a bunch of grid points in redshift to interpolate `z(D)`. If a distance is input that results in a redshift beyond the initial set of grid points, the grid is shifted until a relationship can be found.
I tested this by generating a range of distances from `10` to `10^10` Mpc, computing their redshifts using the function, then using LAL's function to compute distances from the given …
> Add cosmology module

- bin/hdfcoinc/pycbc_plot_singles_vs_params
Fixes the broken color scale of single-trigger hexbin plots when plotting `newsnr_sgveto`. Note that `--min-z` is required, otherwise there is no change.
Without `--min-z`:
https://www.atlas.aei.uni-hannover.de/~tito/LSC/o2/o2-analysis4-full4/H1-PLOT_SINGLES_MTOTAL_EFFSPIN_NEWSNR_FULL_DATA-1169107218-1066800_bad.png
With this patch and `--min-z 6`:
https://www.atlas.aei.uni-hannover.de/~tito/LSC/o2/o2-analysis4-full4/H1-PLOT_SINGLES_MTOTAL_EFFSPIN_NEWSNR_FULL_DATA-1169107218-1066800.png
> pycbc_plot_singles_vs_params: improve autolog

- bin/hdfcoinc/pycbc_plot_singles_timefreq
Changes the color of the inspiral tracks in the spectrograms so that it doesn't get confused with the spectrogram color scale.
Old:
https://www.atlas.aei.uni-hannover.de/~tito/LSC/o2/o2-analysis4-full4/3._single_triggers/3.08_H1_loudest_all_time_duration_lt_0.5_sec/H1-PLOT_SINGLES_TIMEFREQ_2-1169107218-1066800.png
New:
https://www.atlas.aei.uni-hannover.de/~tito/LSC/o2/o2-analysis4-full4/blue_spaghetti.png
>  plot_singles_timefreq: more visible inspiral tracks

- bin/hdfcoinc/pycbc_coinc_statmap
- bin/hdfcoinc/pycbc_page_snrifar
This pull request is the work in progress on making more of the hierarchical removal plots.
First, are the cumulative histograms which I believe are exactly as we want them to look.
**Cumulative Histograms**
With no hierarchical removal plot:
https://sugwg-jobs.phy.syr.edu/~steven.reyes/ER10/hierarchical_removal_plots/bulk_bin_cum_0th_background_alt.png
With 1 hierarchical removal plot:
https://sugwg-jobs.phy.syr.edu/~steven.reyes/ER10/hierarchical_removal_plots/bulk_bin_cum_1st_background_alt.png
With 2 hierarchical removals plot:
https://sugwg-jobs.phy.syr.edu/~steven.reyes/ER10/hierarchical_removal_plots/bulk_bin_cum_2nd_background_alt.png
**Non-Cumulative Histograms**
Here comes the tricky part. We should be able to see how the IFARs of foreground triggers change after the …
> Snr-rate Cumulative Histograms and Non-Cumulative Histograms (SNR- IFAR) Plots

- bin/pycbc_compress_bank
- pycbc/waveform/compress.py
This PR includes the changes made to `pycbc_compress_bank` and `compress.py` to use compressed waveforms in the search. The changes are :
* Change the default interpolation method from `linear` to `inline_linear`. This is because, scipy's `interpolate.interp1d` requires the `interpolation` argument to be specified as `linear`. So the inline linear decompression method should have a different name.
* Save the `precision` used to generate the compressed bank as metadata in the bank files.
* Includes the bug fix for segmentation fault issue faced while decompressing the compressed waveforms while running `pycbc_inspiral`.
I have test workflows going with the bug fixes. I'll remove the work in progress tag once the results look fine.
> Changes in pycbc_compress_bank and compress.py to use compressed waveforms in the search

- pycbc/filter/matchedfilter_cpu.py
- pycbc/waveform/compress.py
- pycbc/waveform/utils.py
(fix bug introduced in 4d11ed986a842bab489af6e33c2fed026d13fb0b, see #890 )
By default, WEAVE_FLAGS is set to '-march=native -O3 -w',
unless the environment variable WEAVE_FLAGS contains a
-march= specification on its own. ADDING these options
to WEAVE_FLAGS for extra_compile_args in the current way
is dysfunctional, as
- it's superfluous
- it's missing a blank, resulting in the invalid option
"-w-march=native"
- it prevents the user from overriding the default,
resulting in failure with compiler versions that
don't know this architecture.
> fix WEAVE_FLAGS usage

- .travis.yml
- tools/einsteinathome/pycbc_build_eah.sh
- tools/install_travis.sh
- tools/run_travis.sh
This pull request switches our Travis build and test infrastructure to use the Einstein@Home build scripts. This synchronizes our testing with @bema-ligo's so any errors in pull requests will be caught by Travis. The E@H build code also simplifies our Travis setup and adds a test that actually runs ``pycbc_inspiral`` and checks that it finds GW150914.
To implement this, I have made a few changes to the E@H build script to:
* Add an Ubuntu 12 OS target, with an addition check that skips building FFTW, HDF5, OpenSSL, lapack, zlib, freetype, and GSL if the target OS is a Travis Ubuntu machine. We get these libraries via apt in the container, so there is no need to build them.
* Implement a ``--slient-build`` option. Travis fails if stderr/stdout exceeds 4MB and fails if no output is written …
> Switch Travis to use the Einstein@Home build infrastructure.

- bin/pycbc_fit_sngl_trigs
Found while testing travis:
```
(pycbc-dev)[dbrown@sugwg-osg ~]$ pycbc_fit_sngl_trigs --help
File "/home/dbrown/src/pycbc-dev/bin/pycbc_fit_sngl_trigs", line 4, in <module>
__import__('pkg_resources').run_script('PyCBC==770rc47', 'pycbc_fit_sngl_trigs')
File "/home/dbrown/src/pycbc-dev/lib/python2.7/site-packages/pkg_resources/__init__.py", line 738, in run_script
self.require(requires)[0].run_script(script_name, ns)
File "/home/dbrown/src/pycbc-dev/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1499, in run_script
exec(code, namespace, namespace)
File "/home/dbrown/src/pycbc-dev/lib/python2.7/site-packages/PyCBC-770rc47-py2.7.egg/EGG-INFO/scripts/pycbc_fit_sngl_trigs", line 27, in <module>
from pycbc.events import trstats
ImportError: …
```
> Fixed bad import in pycbc_fit_sngl_trigs

- .travis.yml
The E@H script looks for the actual ROM files themselves, so no need to cache the tarball.
> Remove files that should not be cached

- docs/Makefile.std
Travis now checks that the documentation can build correctly before a merge can happen:
https://github.com/ligo-cbc/pycbc/blob/master/docs/Makefile.gh_pages#L7
This removes the ``-W`` from the non gh_pages build so that users can test the doc build, even if they don't have e.g. MKL. Any documentation failures will be picked up on the pull check in GitHub.
> Remove warning as error for documentation build

- tools/einsteinathome/pycbc_build_eah.sh
- hotfix for issue #1522 
Since #1505 analysis test now runs in a pipe, which means that if it fails, the pipe and the script still succeeds, which is exactly what this test is not for.
> E@H build script: set pipefail

- bin/inference/pycbc_inference_plot_movie
- bin/inference/pycbc_inference_plot_posterior
- pycbc/inference/option_utils.py
- pycbc/results/scatter_histograms.py
This patch adds the ability to plot the expected parameter values on posterior plots in `plot_posterior` and `plot_movie`. A posterior example: [here](https://www.atlas.aei.uni-hannover.de/~cdcapano/LSC/projects/pycbc_inference/cbc/spin_priors/inj-chieff_0p4-chip_0p1/prior-isotropic_spins/posterior_density-mass1_mass2.png). A movie example: [here](https://www.atlas.aei.uni-hannover.de/~cdcapano/LSC/projects/pycbc_inference/cbc/spin_priors/inj-chieff_0p4-chip_0p04/prior-uniform_chip_chieff/scatter_movie-1-52000-250.mp4).
The expected values are specified by an `--expected-parameters` option, which expects the name of a parameter which must correspond to one of the parameters, followed by the value. For example, to create the above posterior plot:
```
pycbc_inference_plot_posterior \ …
```
> Plot expected values in posterior plots

- bin/pycbc_geom_aligned_bank
- bin/workflows/pycbc_create_sbank_workflow
- bin/workflows/pycbc_create_uberbank_workflow
- pycbc/workflow/core.py
- pycbc/workflow/inference_followups.py
- pycbc/workflow/minifollowups.py
See #1532 . This fixes that problem by removing the now duplicated output_file_map usage in tmpltbank workflows. I also don't like how this was implemented. The output_map is a File, then a path, then a File. We should pass around Files when possible, so this now requires a File as input (this allows the output_map to be used (or even written by) other jobs if that's ever something we want to do).
The "save" function does want a path, but that is now made clearer.
This fixes #1532. Close #1532 (Trying to make git-hub close the issue automatically when this is merged)
> Fix tmpltbank workflows

- bin/pycbc_inspiral
- pycbc/filter/matchedfilter.py
The methods `full_matched_filter_and_cluster_symm`, `full_matched_filter_and_cluster_fc`, `full_matched_filter_thresh_only` in `MatchedFilterControl` return arrays for the snr and correlation vectors. It would be more useful if these return an snr TimeSeries and a corr FrequencySeries. This would for instance help in easily reading off the trigger times along with their SNRs wherever these functions are used. The patch would also be compatible with what is currently documented for the methods. 
Also, these methods return empty lists when a trigger is not found, which is decided by checking the length of `idx`. However, wherever `matched_filter_and_cluster` is called in pycbc for doing the matched filtering, the length of `idx` returned by it is checked after calling the function, and if …
> Make methods in MatchedFilterControl return a TimeSeries for snr and a FrequencySeries for corr instead of arrays.

- bin/hdfcoinc/pycbc_page_segtable
This fixes #1539 by changing the logic by which segments are identified. We now check if there is an exact match between the two strings or if the key starts with segment_flag followed by a ":". This indicates that a version number is being given.
It seems that the confusion here is because a version number is potentially expected in `seg_dict.keys()`. However, even though a version number *is* present, this simply returns `${IFO}:${CHANNEL_NAME}` ... SO i'm not really sure if this is expected or not, but this patch at least fixes #1539.
(Close #1539 fix #1539)
> Fix to pycbc_page_segtable

- bin/minifollowups/pycbc_foreground_minifollowup
- bin/minifollowups/pycbc_injection_minifollowup
- bin/minifollowups/pycbc_sngl_minifollowup
It looks like the minifollowups workflows didn't get updated with the output map changes. This fixes that.
> change name to output_map_path in minifollowups

- pycbc/inference/likelihood.py
- pycbc/pnutils.py
- pycbc/tmpltbank/coord_utils.py
- pycbc/waveform/parameters.py
- pycbc/waveform/waveform.py
This patch adds the ability to use a frequency cutoff function when generating waveforms. This is done by adding a new parameter to `parameters.py` called `f_final_func`. If this is specified in the keyword arguments given to `get_fd_waveform`, the final frequency derived on the fly from `pnutils.named_frequency_cutoffs`. In order to get `named_frequency_cutoffs` to work with `get_fd_waveform`, I had to change the names of parameters that are expected in the dictionary from `m1, m2, s1z, s2z` to `mass1, mass2, spin1z, spin2z`. This allows, e.g., `HybridMECO` to be used in PE codes.
One thing I wasn't sure about: it can happen that the final frequency ends up being larger than the lower frequency cutoff that was specified. I don't want this to raise an error, because this can happen in PE …
> Add ability to use frequency cutoff function

- bin/pycbc_inspiral
- pycbc/waveform/bank.py
This PR includes the changes made to `pycbc_inspiral` and `bank.py` to use compressed waveforms in the search to do the matched filtering. The changes primarily are :
* Addition of an argument `--use-compressed-waveforms` to let the user choose whether or not to use compressed waveforms from the template bank, and depending on that load compressed waveforms in `FilterBank` in `bank.py` .
* Tell `FilterBank` that the precision to be used to generate the decompressed waveforms should be `single` and raise an error if the bank was not constructed using the precision that `pycbc_inspiral` specifies.
* If the user chooses to load the compressed waveforms from the bank, read in the `amplitude`, `phase` and `sample_points` for the templates from the bank and decompress them using `decompress` in …
> Changes in pycbc_inspiral and bank.py to use compressed waveforms in the search

- bin/inference/pycbc_inference
- pycbc/inference/option_utils.py
- pycbc/io/inference_hdf.py
This patch moves the block of code that loads the psd, the strain, and FFTs the strain that's currently in `pycbc_inference` to a single function called `data_from_cli` in `option_utils`. The patch also moves the block of code for writing the strain/stilde/psd to a class method of `InferenceFile`.
@cmbiwer: This is unrelated to our patches for the spin priors project. The motivation for this is it is the first in a series of patches to get a hierarchical inference executable I wrote for doing the area theorem on to master. That program is basically a copy of `pycbc_inference`, but it allows you to do a single MCMC on different waveform models and data that share a subset of common parameters. For example, in the area theorem test, the inspiral and ringdown are distinct models looking at …
> Move inference data loading/writing to single functions

- bin/pycbc_compress_bank
This PR includes changes so that `---low-frequency-cutoff` is not a required argument in the bank compression code. It now allows the code to read in a variable low frequency cutoff for the templates in the bank taken in as input and then uses that to generate the compressed waveform points. If `---low-frequency-cutoff` is not provided, the code would look for the cutoff for each template in the bank. If the bank stores the cutoffs and a `---low-frequency-cutoff` is also provided, the `---low-frequency-cutoff` is used for the compression.
> Allow the bank compression code to read in a variable low frequency cutoff for templates if that is stored in the input bank and compress using that.

- bin/minifollowups/pycbc_sngl_minifollowup
- pycbc/workflow/minifollowups.py
This PR adds the functionality to print the loudest events in `pycbc_sngl_minifollowup` to the output directory of the loudest events.
I added a function to `minifollowups.py` to take a list or a numpy array and print it to a file with wiki table delimiting (`||`). If the `--wiki-file` option is provided to `pycbc_sngl_minifollowup`, this file will be written to the indicated output directory. I added this option to `setup_single_det_minifollowups()` so that the list of loudest events will be built every time `pycbc_sngl_minifollowup` is called.
I grabbed an example call of `pycbc_sngl_minifollowup` from a recent successful workflow and reran it by hand with the `--wiki-file` option and it ran to completion.
> Added code to print loudest events to a wiki table

- tools/einsteinathome/pycbc_build_eah.sh
fixes issue #1522 introduced in #1505.
PyCBC sets log levels `warning` and `debug` (with '--verbose'), however the log level used for (almost) all own messages is 'info'. The patch lowers the log level of the messages most frequently appearing during the analysis to 'debug', which doesn't affect the current behavior (default vs. '--verbose') at all. It introduces a new option '--info' to pycbc_inspiral to set the log level 'info', such that only the infrequent messages appear. Finally, the E@H build script is changed to fix the issue described in #1522 by using the new option and getting rid of the pipe.
> Silence E@H/OSG test analysis

- tools/install_travis.sh
This shouldn't be merged until ``--clean-lalsuite`` is removed, but I need one cycle with that to clean the build.
> Update lalsuite commit for issue 1558 and force a clean

- docs/inference.rst
This clarifies that the tc prior needs to change from the BBH example in order to run on GW150914.
> Clarification in the inference doc

- bin/pycbc_banksim_combine_banks
Update to use the new ``pycbc.version`` module, as this code currently causes travis to fail with
```
---------------------------------------------------------
File "/home/travis/build/pycbc-build/environment/bin/pycbc_banksim_combine_banks", line 4, in <module>
__import__('pkg_resources').run_script('PyCBC===73e4a5', 'pycbc_banksim_combine_banks')
File "/home/travis/build/pycbc-build/environment/lib/python2.7/site-packages/pkg_resources/__init__.py", line 735, in run_script
self.require(requires)[0].run_script(script_name, ns)
File "/home/travis/build/pycbc-build/environment/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1652, in run_script
exec(code, namespace, namespace)
File "/home/travis/build/pycbc-build/environment/lib/python2.7/site- …
```
> Use the pycbc.version module

- bin/minifollowups/pycbc_foreground_minifollowup
- bin/minifollowups/pycbc_injection_minifollowup
- bin/minifollowups/pycbc_sngl_minifollowup
- bin/pycbc_single_template
- pycbc/io/hdf.py
- pycbc/workflow/minifollowups.py
This patch resolves the issue noted in #1562 by using the value of f_lower stored in the template bank as an input to `pycbc_single_template` in all minifollowups codes. This is tested here:
https://galahad.aei.mpg.de/~spxiwh/LVC/aLIGO/O2/analyses/O2_chunk10/prelim_analyses/run5_TEST
Note that this requires a small change in the configuration file. Currently `--low-frequency-cutoff` is specified in the config file for all `pycbc_single_template` jobs. Now it would be given in the ini file only for jobs where the injection is going to be used as a template. That change should be coordinated with the 1.7.0 release so I am not making it now.
(Fixes #1562 Fix #1562 Close #1562)
> Use template's f_lower in minifollowups

- docs/install.rst
- requirements.txt
- tools/install_travis.sh
@duncan-brown This reverts the hack I had to introduce to ensure that old-glue got installed for Travis. I also update both the install instructions and Travis to install dqsegdb "properly" instead of the old hacky thing we had to do because it wasn't on PyPI. Would like this in v1.7.0.
Thanks Ryan Fisher for fixing this for us!
> Dqsegdb now properly on PyPI, YAY!!

- tools/docker_build_dist.sh
Use ``yum`` to remove the LAL rpms as it also takes care of the dependencies.
This also fixes a permissions problem with the Travis built virtualenv on CVMFS:
* Add a couple of chmod steps to make all the files world readable.
* Force python to [unzip all egg files on install](http://stackoverflow.com/questions/2604600/why-does-easy-install-extract-some-python-eggs-and-not-others) since CVMFS wants to deal with the individual files (and users don't have permission to extract them at runtime).
> Use yum to remove LAL RPMs and fix virtualenv permissions

- .travis.yml
- tools/docker_build_dist.sh
- tools/test_coinc_search_workflow.sh
This adds a script that tests ``pycbc_make_coinc_search_workflow`` in the CentOS 7 LDG Travis container prior to deploying the virtual environment. 
This test validates the virtual environment and checks that the workflow generation script runs properly. It tests the DAXes with ``pegasus-dax-validator`` and if that succeeds, then it tries to plan them (but without submitting them, since there is no pool to submit them to).
Note that the workflow script generated is just validated by Pegasus. There is no check that the workflow itself is scientifically correct.
> Test pycbc_make_coinc_search_workflow in Travis

- .travis.yml
- tools/docker_build_dist.sh
- tools/run_travis.sh
This significantly speeds up the Travis test suite by
* Using the [SL6](https://hub.docker.com/r/pycbc/sl6-travis/) pre-built Docker container for the ``pycbc_inspiral`` bundle build.
* Using the [LDG CentOS 7](https://hub.docker.com/r/pycbc/ldg-el7/) pre-built Docker container for the virtual environment build.
* Caching the E@H build tar balls in the Docker ``pycbc_inspiral`` bundle build.
> Speed up Travis using PyCBC docker containers and additional caching

- tools/run_travis.sh
- tools/test_coinc_search_workflow.sh
This patch fixes this [build error](https://travis-ci.org/ligo-cbc/pycbc/jobs/220413735#L5995) by fixing the section for ``datafind-check-frames-exist`` and this [build error](https://travis-ci.org/ligo-cbc/pycbc/jobs/220419735#L795) by creating the missing directory.
> Fix two problems with the Travis build

- tools/docker_build_dist.sh
- tools/einsteinathome/pycbc_build_eah.sh
This adds a ``--processing-scheme`` option to ``pycbc_build_eah.sh`` that is passed to ``pycbc_inspiral`` when testing.
> Allow the ability to test pycbc_inspiral with the MKL processing scheme

- docs/build_gh_pages.rst
- docs/install.rst
This commit adds instructions on how to publish to your own GitHub pages, e.g.
http://duncan-brown.github.io/pycbc/latest/html/
> Explain how to publish to github pages

- tools/einsteinathome/pycbc_build_eah.sh
There is no point in building more of LALSuite for E@H than what is needed for pycbc_inspiral, ie. the command-line switch '--build-minimal-lalsuite' is not necessary. However for configuring LALSuite I suggest to use the "positive" phrasing '--disable-all-lal' '--enable-'... which explicitly lists the parts that are needed instead of explicitly disabling all that is not. For now I'm leaving the '--build-minimal-lalsuite' switch in, so that the current command-lines don't fail.
> E@H build: always build minimal LALSuite

- docs/conf_std.py
- docs/install.rst
- pycbc/distributions/angular.py
- pycbc/psd/__init__.py
- pycbc/waveform/generator.py
- pycbc/workflow/minifollowups.py
- pycbc/workflow/pegasus_workflow.py
- requirements.txt
- tools/docker_build_dist.sh
- tools/install_travis.sh
This moves our documentation to use the builtin napoleon extension of Sphinx rather than numpydocs. The main reason for this is to trigger the "Warnings are errors" within the numpy-style formatting that are not triggered with numpydocs. This also removes a dependancy from pycbc!
This makes a minor cosmetic effect to the output pages. Example is here:
http://galahad.aei.mpg.de/~spxiwh/pycbc_docs
As one specific difference see here:
http://galahad.aei.mpg.de/~spxiwh/pycbc_docs/pycbc.psd.html?highlight=generate_overlapping_psds#pycbc.psd.generate_overlapping_psds
(especially the `opt` input parameter, which I messed about with), note that *some* of the classes are automatically linked to (probably we would need to edit the config if we wanted to link also to numpy or scipy or something …
> Move docs to sphinx.ext.napoleon

- bin/inference/pycbc_inference
- pycbc/waveform/generator.py
- pycbc/waveform/parameters.py
This supersedes #1211. The patch adds the ability to use time domain waveforms in `pycbc_inference`. A taper argument can be added to the ini file to taper the time domain waveform before converting to the frequency domain. It also adds the additional time shift needed to a TD waveform, since they are not generated such that the peak amplitude is at the end of a segment, as a FD waveform is.
> Add ability to do PE with time-domain waveforms

- tools/einsteinathome/pycbc_build_eah.sh
This fixes / improves the LALSuite build mainly for OSX & Cygwin. In general it 
- drops obsolete / unnecessary patching to build from a 'clean' git repository
- runs '00boot' only when necessary, which should speed up re-builds
- bumps up FrameCPP (used for OSX only) version to match the requirements of current LALSuite
> Rework lalsuite build

- bin/inference/pycbc_inference
- pycbc/inference/option_utils.py
Another patch in order to prepare for hierarchical inference, this one moves the blocks of code that load the config file to functions in `option_utils.py`.
> Move config file loading to option utils

- pycbc/results/templates/orange.html
No one ever added this to the HTML pages. Its only because the posterior table is on there, is why the labels loaded before.
> Fix mathjax rendering on HTML pages

- bin/workflows/pycbc_make_inference_workflow
This is the beginning in a series of PR to update the inference workflow HTML pages.
This PR:
* Adds sections.
* Adds workflow generator log, version, and configuration files to workflow section.
The bits of code for adding the log could probably be moved to a module since multiple workflow generators will use it. But that can be another PR.
Example (do not interpret the plots I used data reuse with some random images in places): https://sugwg-jobs.phy.syr.edu/~cbiwer/tmp/inference_workflow/r6/
> Add sections and workflow tabs to inference HTML pages

- tools/docker_build_dist.sh
- tools/einsteinathome/pycbc_build_eah.sh
I accidentally turned the HDF5 build off on the SL6 platform that Travis uses. I didn't notice this, as the E@H test runs SEOBNRv2, which uses txt files. @josh-willis' run failed when using SEOBNRv4 as that reads ROM data from HDF5.
I need to get back to @bema-ligo on https://github.com/ligo-cbc/pycbc/issues/1507 so that we can add a test that uses the v4 ROMs to the E@H test suite.
As part of this pull, I removed the remaining references to ``--build-minimal-lalsuite`` which @bema-ligo deprecated in https://github.com/ligo-cbc/pycbc/pull/1591
> Turn on the HDF5 build on for CERN SL6

- tools/einsteinathome/pycbc_build_eah.sh
We switched from scipy.weave to weave, so scipy can be updated now in the virtualenv, so we don't have t do this for every build.
This also makes patching scipy 0.16.0 for Cygwin obsolete.
> Revert "E@H build: don't update scipy until weave was swicthed"

- tools/docker_build_dist.sh
- tools/einsteinathome/pycbc_build_eah.sh
This adds an extra approximant to build the waveform compression code into the pycbc_inspiral bundle built for OSG.
I also:
* Switched from deploying to ``sugwg-test1`` to ``sugwg-condor``, as the latter is a production machine.
* Set the code to always copy the bundle and virtual environment to ``sugwg-condor``.
* Removed the deployment of the lalsuite source to /cvmfs as it's 1.6GB per release.
* Added the v11 ROM data to the E@H build.
> Add waveform compression to pycbc_bundle in Travis build

- bin/inference/pycbc_inference
@cdcapano This PR fixes a small bug introduced in #1555. 
I ran into this bug while running the current `pycbc_inference` on master. So thought of filing a patch. 
While generating the waveform, it does `waveform.FDomainDetFrameGenerator(...` but `waveform` is not imported in the code. So it should be `generator.FDomainDetFrameGenerator(...` instead. Also, using the name `generator` for the return value of the class as the module used to generate it creates a bit of confusion. So, I thought using a different name might be helpful. I've renamed `generator` as `generated_waveform` in this PR.
> Minor bug fix in calling waveform generator from pycbc_inference

- bin/workflows/pycbc_make_inference_workflow
- pycbc/results/layout.py
- pycbc/results/render.py
- pycbc/results/static/css/pycbc/orange.css
- pycbc/results/templates/wells/two_column.html
Allows keyword options to be passed to ``two_column.html`` via ``pycbc.results.layout``. And add a ``{{subtitle}}`` to ``two_column.html``.
So now can do:
```
layout.two_column_layout(rdir.base, layouts, subtitle="Hello World!")
```
to add some text to describe what is in the well.
And you'll get something like this: https://sugwg-jobs.phy.syr.edu/~cbiwer/tmp/inference_workflow/r11/4._samples/
> Allow kwargs to be passed to two_column.html from layout

- pycbc/inference/option_utils.py
- pycbc/inference/sampling_conversions.py
PR #1567 does not solve sampling in spherical coordinates and would require a duplication of all the functions in ``conversions.py``. Also PR #1567 makes these very long command lines. This PR makes ``results_from_cli`` include a set of basic parameters (``mass1``, ``mass2``, ``spin1x``, ``spin1y``, ``spin1z``, ``spin2x``, ``spin2y``, and ``spin2z``). Then you have full access to doing all the conversions.
So even if you sampled in say ``mchirp`` and ``q``, all you need to specify on the command line is ``--parameters mass1 mass2`` and it will plot those parameters.
These classes could probably be used to replace those same types of functions in ``pycbc.waveform.generators``.
Requires #1590.
> Include a set of basic parameters when reading InferenceFile

- pycbc/inference/option_utils.py
- pycbc/inference/sampler_base.py
- pycbc/inference/sampler_emcee.py
- pycbc/io/inference_hdf.py
This PR:
* Allows the CLI access to the ``likelihood_stats`` group in the HDF file.
* Writing ``chain`` and ``likelihood_stats`` now use the same helper function called  ``_write_samples_group``. There is a lot of duplicate code that can be avoided.
* Fixes bug in ``BaseSampler.write_chain`` that ignored the ``sample_group`` when trying to find what are the possible parameters.
Can plot on command line like:
```
PRECESSING_OPTS="--input-file /home/soumi.de/projects/cbc/inference_for_events/GW150914/H1L1/inference_GW150914_H1L1_100000iter.hdf --output-file /home/cbiwer/public_html/tmp/tmp.png --iteration 5999 --plot-marginal --plot-density --verbose"
pycbc_inference_plot_posterior ${PRECESSING_OPTS} --parameters mchirp
pycbc_inference_plot_posterior ${PRECESSING_OPTS} --parameters loglr …
```
> Allow likelihood_stats group to be plotted on command line

- bin/hwinj/pycbc_insert_frame_hwinj
Previosuly, the command line option was not passed on to from_cli
in strain, which resulted in single precision used regardless of
what was specified.
> The option "--precision" was igonred in pycbc_insert_frame_hwinj.

- tools/einsteinathome/pycbc_build_eah.sh
Some tuning mainly for some Cygwin installations. Most importantly added an option --blessed-lalsuite that greps the LALSuite commit to build from https://github.com/ligo-cbc/pycbc/releases/latest
> Eah build script update

- tools/einsteinathome/pycbc_build_eah.sh
This (finally!) enables us to use the same version of PyInstaller on all platforms, and ultimately to get rid of the workarounds required for the previously used PyInstaller 2.1. Note that this is based on #1635.
> use PyInstaller 3.2.1 also for Cygwin

- pycbc/inference/sampler_emcee.py
If wanting to plot values from ``likelihood_stats`` in ``InferenceFile`` need to use the ``samples_group`` that is passed to the function, not the default set in the class.
For an example of running emcee on sugwg, see: /home/cbiwer/projects/inference_samples_group/test/run_pycbc_inference.sh
And for plotting values from ``likelihood_stats``: /home/cbiwer/projects/inference_samples_group/test/test.sh
> Use samples_group option not default in file for reading samples from emcee sampler

- pycbc/waveform/waveform.py
When reading parameter estimation results, we sometimes end with a dictionary instead of a numpy record array (for the ability to add fields easily). With this (tiny) patch, one could pass such a dictionary to pycbc's interface to LALSimulation.
> Added ability to specify a dictionary of parameters to generate waveforms

- bin/pycbc_live
This is useful to synchronize pycbc live to the rate that frame files are produced. One of the restart steps does this manually, but after this, one shouldn't have to manually set the start time if one want to start from only roughly now.
> add option to round up start time

- pycbc/waveform/waveform.py
This lets us use EOBNRv2HM_ROM as a template within the standard analysis.
> add length for EOBNRv2HM_ROM

- requirements.txt
- setup.py
This sets the kombine version to use in setupy.py to 0.8.1, which is the current most recent version. This is to overcome the current bug in kombine's version history on pypi, in which version 1.1 is older than version 0.8.1. When Ben fixes this, we can go back to just getting the most recent version of kombine.
> Set kombine version in setup.py

- bin/pycbc_compress_bank
- pycbc/waveform/bank.py
This PR allows :
* `template_duration` for waveforms to be stored in compressed bank
* `template_duration` to be read directly from the compressed bank when decompressing. This would save the cost of getting the lengths for templates in a bank using `get_waveform_length_in_time`
@cdcapano Could you please take a look?
> Allow template_duration to be stored in compressed bank

- docs/inference.rst
This adds instructions to the inference docs for non-LIGO members to analyze GW150914. It uses the frame-type argument's ability to use LOSC data. That functionality appears not to work currently  however (I get an error claiming the gps times are not in public data), so I'm putting on hold until @ahnitz can fix.
> Add instructions for non-LIGO members to analyze GW150914

- pycbc/waveform/bank.py
There was a typo in PR 1646. Sorry about that.
> Corrected typo in variable name

- bin/hdfcoinc/pycbc_coinc_statmap
This is helpful for making the foreground trigger tables in another PR (https://github.com/ligo-cbc/pycbc/pull/1600).
> Store foreground trigger ids for downstream plotting codes

- pycbc/__init__.py
- pycbc/weave.py
This pull request is to restore the custom file locking in weave compilation that PyCBC relies on. Something seems to have broken the previous mechanism; I'm not sure it if happened when weave transitioned to a stand-alone package or not.  It is possible to see from the current master that the correct thing isn't happening: if you import `pycbc.weave` you will see that `pycbc.weave.inline_tools.compile_function` is not pointing at our custom function in `pycbc/weave.py`, but rather at the usual function from the standard package.
This pull request fixes that.  Note that the original approach had a `try/except` block around the imports within `__init__.py` because it said that we couldn't guarantee that `scipy` was available during installation.  I guess I really don't understand …
> Fix weave file locking

- pycbc/inject/injfilterrejector.py
- pycbc/waveform/bank.py
I'll keep this as work in progress till the issue with lesser number of triggers being generated when using compressed waveforms for inj_filter_rejector as compared to when using regular waveforms is resolved.
Also, this depends on #1646 .
> Allow InjFilterRejector template waveforms to be generated from compressed waveforms

- docs/inference.rst
- pycbc/distributions/angular.py
- pycbc/distributions/boundaries.py
- pycbc/distributions/bounded.py
This makes cyclic boundaries in the angular distributions optional, with the default set to False. This allows us to use `uniform_sky`, `uniform_solidangle`, and `uniform_angle` in the inference config files, instead of having to specify azimuthal angles separately using the uniform distribution. Cyclic boundaries can be turned back on for `uniform_angle` by setting `cyclic_domain = 1` in the ini file; for `uniform_solidangle` and `uniform_sky`, `azimuthal_cyclic_domain = 1`. I've updated the inference docs accordingly.
I also adjusted the upper bound on the distance prior in the BBH example to 1Gpc, since 500Mpc is too close to be used for GW150914.
> Make cyclic boundaries optional

- bin/pycbc_banksim
This patch makes some optimization changes in banksim, and fixes one bug that can cause matches > 1.
* A new option `--tau0-window` is added because absolute difference in tau0 seems to be a better check on "will things match" than mchirp fractional difference. For the frequency here I always use the filter low frequency cutoff.
* The mchirp window checks (and also the new check) were slow because they call the pnutils function in a non-vectorized way for each waveform. If you are rejecting *many* templates this becomes a significant factor. This is now computed once, for signals, and once for templates as an array. Cost disappears.
* Previously if the filter_low_frequency_cutoff was *larger* than the template's specified f-lower, we could see overlaps > 1 as signals would be normalized …
> Some optimizations, and a bug-fix, for banksim

- .landscape.yml
- pycbc/events/events.py
- pycbc/filter/matchedfilter.py
- pycbc/future.py
- pycbc/inference/likelihood.py
- pycbc/results/scatter_histograms.py
- pycbc/tmpltbank/em_progenitors.py
- pycbc/types/array.py
- pycbc/vetoes/chisq.py
- pycbc/waveform/generator.py
So the vulcan main fileserver went down (badly) this morning, meaning I can't access any of my ongoing projects. So what should I do instead for the day? Fix landscape warnings!! This is still work in progress, but I have a question for @ahnitz 
Commit 1:
Disable style messages in the config that we have been telling people to ignore.
https://landscape.io/github/ligo-cbc/pycbc/1795
Commit 2:
Silence false "not callable errors"
https://landscape.io/github/ligo-cbc/pycbc/1796
Commit 3:
Go through all the other errors and either fix it, or silence it. I have not touched issues that other people are already supposed to be fixing, or a few I am unsure of.
https://landscape.io/github/ligo-cbc/pycbc/1797
Remaining points:
Things like this: …
> Fixing landscape errors

- test/test_injection.py
- test/test_tmpltbank.py
- test/test_waveform.py
* Float indexing with recent numpy
* Unused/dangerous imports
* Blacklist waveform approximants requiring special params
> Fix a few simple test failures

- pycbc/inference/prior.py
Allows the user to pass a list of functions that impose multi-dimensional constraints on the prior.
The reason for putting this here is that this transcends parameters in different distributions.
Functions should have the convention that if the parameter values obey the constraint, the function returns ``True``, else if the parameter values disobey the constraint, then the function should return ``False``.
> Add multi-dimensional constraints to PriorEvaluator.

- pycbc/io/record.py
This fixes a typo that was caught by landscape in `record.py`.  At some point I must have changed `set_ilwd_as_int` to `ilwd_as_int` and forgot to update the call to this function in `default_strlen`.
> Fix typo in record.py

- pycbc/waveform/ringdown.py
When doing the multi-mode PE on time-domain ringdown (only) injections, we noticed that we were having issues due to the sharp turn on of the ringdown. This PR adds an option to taper the ringdown with a rapid exponential ringup.
Comparisons between the tapered and the non-tapered ringdown are [here](https://www.atlas.aei.uni-hannover.de/~miriam.cabero/LSC/tests/ringdown_taper/)
After this is accepted, I will make the corresponding changes to pycbc_ringinj to incorporate this option.
> Add option to ringdown module for tapering time-domain ringdowns

- pycbc/inference/option_utils.py
- pycbc/transforms.py
This patch makes the inverse transforms there own classes, rather than a method that changes the behavior of the class. This makes it a bit clearer what each thing is doing (I found it confusing that, e.g., to create a transform from mass1, mass2 to mchirp,q you needed to initialize MchirpQToMass1Mass2), and is needed if a transform takes input arguments, especially if the inverse does not take the same input arguments. This is to pave the way for the logit transform, and any other transform that may take input arguments.
This also defines a dictionary of all of the transform names -> transform classes, similar to what is in distributions. The current `to_/from_` base converters is renamed `standard(_inverse)_transforms`. These are meant to be only transforms that do not need arguments on …
> Make inverse transforms explicit and other updates

- bin/pycbc_live
- pycbc/filter/matchedfilter.py
In PyCBC Live, the SNR time series for sky localization is currently truncated early or late when the trigger happens too close to the boundary of the valid SNR segment. Since BAYESTAR does not handle a truncated SNR series, this patch extends the series with samples normally thrown away because of filters and wrap-around. After applying the patch, BAYESTAR completes on all the injections of my test, even the few ones close to the boundary of the valid segment, which were causing BAYESTAR to fail before. I have not reviewed the skymaps or the series themselves yet though.
Some unused imports are also dropped.
> pycbc_live: handle edge cases in SNR timeseries

- bin/pycbc_inspiral
- pycbc/waveform/bank.py
- pycbc/waveform/compress.py
This PR changes reading in compressed waveforms for all templates in bank and storing it in a dictionary as part of the `TemplateBank` class. Sample points would be read in only for those templates that are being decompressed in `get_decompressed_waveform` in `FilterBank` or those that are being written to an output hdf file in `write_to_hdf` in `TemplateBank`. This would avoid holding up memory in reading in compressed waveforms and metadata for unused templates.
> Avoid reading in compressed waveforms for unused templates

- pycbc/transforms.py
This patch adds the logit and logistic transforms to transforms.py. The logit transform basically movies boundaries to +/- infinity; this is needed for posteriors that peak close to, or at, a boundary. The logistic function is the inverse of the logit.
I'm putting this on hold for now. I realized there are some difficulties fitting these into the current structure for transforms as the logit and logistic function need variables to be specified on initialization. @cmbiwer I'll open another patch to try to deal with that first.
> Add logit and logistic transforms
